### ISSUE TITLE
Welcome to React Native Elements ( Button issue )

### ISSUE THREAD

**Issue by boraikizoglu** [react-native-training/react-native-elements#1002]
### Description

1. Explain what you did: I removed node_modules folder and then executed npm install command ( It should install the same version of react-native-elements since I didn't change version on package.json )
2. What you expected to happen: I expected that button component of react-native-elements will continue to work properly
3. What actually happens: Buttons show "Welcome to react native elements" text

<img width="415" alt="screen shot 2018-03-15 at 17 11 06" src="https://user-images.githubusercontent.com/17179767/37469143-b56bcae6-2875-11e8-932b-eb6c2438eb60.png">

Version: "react-native-elements": "^1.0.0-beta2",

### Reproduction Steps and Sample Code

```
               <Button
                loading={isLoading}
                text="SIGNUP"
                containerStyle={{ flex: -1 }}
                buttonStyle={styles.signUpButton}
                ViewComponent={require('expo').LinearGradient}
                linearGradientProps={{
                  colors: ['#FF9800', '#F44336'],
                  start: [1, 0],
                  end: [0.2, 0],
                }}
                textStyle={styles.signUpButtonText}
                onPress={this.signup}
                disabled={isLoading}
              />
```

### Solution

I replaced react-native-elements module in node_modules with the past folder (folder before I delete my node_modules file. I had a backup of node_modules folder )

When I replace it with this module, it fixes the problem.
https://drive.google.com/drive/folders/1GZMaMjAGTvUx68FC0mvQ_XJHhoJi2Jzk?usp=sharing

**Comment by iRoachie** [comment]
In the betas the default title for the Button is 'Welcome to React Native Elements'. This only shows if you haven't given the Button a `title`.

See https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L148

**Comment by boraikizoglu** [comment]
@iRoachie You are right. I realized that after posting this issue.  

but I still have a confusion. It should install the same version since I didn't change package.json and didn't modified react-native-elements module manually. 

It works properly when I replace module with the folder in the google drive link above. ( It is a backup of react-native-elements module before I delete and install node_modules )

**Comment by iRoachie** [comment]
@boraikizoglu You really shouldn't be editing or interfacing directly with node_modules. Let your package.json be the source of truth. If you still have any problems then do a fresh install of your packages.

`rm -rf node_modules && npm install`

**Comment by boraikizoglu** [comment]
@iRoachie I said "didn't modified react-native-elements module manually."

Anyway, I updated it to last version and changed the props. It is fixed now. Thanks

**Comment by ArthurInTheShell** [comment]
I was trying to make the title disappear and I accidentally look into this post. The way to do it is to make title=''. Thought I guess there are way easier way to do it, (maybe by Image)
