### ISSUE TITLE
Update website to use new props layout

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1006]
Using the props layout from the react native docs website

**Comment by iRoachie** [comment]
Each page should list all the available props in alphabetical order, with an anchor link to the description of the prop. 

See https://facebook.github.io/react-native/docs/image.html#props for example behaviour

**Comment by Gregjarvez** [comment]
@iRoachie this isn't replacing the table layout right ? just an addition. Id like to do this too

**Comment by iRoachie** [comment]
It's replacing the layout of all the docs pages, with the props layout similar to the react-native-docs. This is a very big PR

**Comment by Gregjarvez** [comment]
yeah seems really big :) few days maybe @iRoachie

**Comment by Monte9** [comment]
@Gregjarvez seems like you have been submitting a few PR's and helping out. Thanks for that! 😃 

I am putting a $30 bounty on this PR and @iRoachie will oversee it. So if you wanna work on this PR, go for it! 😉

**Comment by Gregjarvez** [comment]
sure i will work on this

**Comment by Gregjarvez** [comment]
@iRoachie I created a [gist](https://gist.github.com/Gregjarvez/a77fd849b21b64d0499f42cccd365329#activeopacity) for avatar.md. could verify if this is correct before I process to work on the others

**Comment by iRoachie** [comment]
Can you use `###` for the props in reference instead

**Comment by Gregjarvez** [comment]
@iRoachie sure I will do that 
Also what is the order of precedence of the md files
say button.md in directories version-0.19.0 and version-1.0.0-beta2 
which one do I edit ?

**Comment by iRoachie** [comment]
This is what I meant when I said its a big PR, all of them have to edited in every version

**Comment by xavier-villelegier** [comment]
New layout is now live [here](https://react-native-training.github.io/react-native-elements/). Thanks again @Gregjarvez 💯

**Comment by iRoachie** [comment]
Hey @Gregjarvez just reminding you to submit your expense on opencollective for $30.

Here's the link to the invoice https://docs.google.com/document/d/1bC_x-Lc1vxLGSfliKToTpaXQWS-luuUqPV_iBb9blb8/edit?usp=sharing. For the description - put "New Props Layout on Website".

You'll need a PayPal account to be able to receive funds.

Upload the invoice and submit the form [here](https://opencollective.com/react-native-elements/expenses/new). The description is same as above and put the category as Engineering.

**Comment by Gregjarvez** [comment]
@iRoachie i should have asked before submitting. I didn't have to do anything to the invoice correct?

**Comment by iRoachie** [comment]
You would've needed to change the details like name, address, description etc.

**Comment by Gregjarvez** [comment]
Oh right. I didn't read anything on it lol .
I will do that early today. :)

Thanks

**Comment by Gregjarvez** [comment]
sure !! I need right access for the receipt to be able to fill in my credentials @iRoachie

**Comment by iRoachie** [comment]
Just add a copy of it to your drive

**Comment by Gregjarvez** [comment]
sure @iRoachie

**Comment by Monte9** [comment]
Again great work here @Gregjarvez! Well deserved! 💯
