### ISSUE TITLE
Cleanup Typescript definitions 

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1008]
* Remove links to component pages (the links will always be broken since the website create new urls for each release)
* Replace usage of `JSX.Element` with `React.ReactElement`

**Comment by Gregjarvez** [comment]
@iRoachie I will submit a pr for this :)

**Comment by iRoachie** [comment]
Thanks. @Gregjarvez!

**Comment by Gregjarvez** [comment]
checking out a new branch with base next shouldn't mess up anything right 
`git checkout -b ts-definition upstream/next` 
I want to be sure before I mess up some more branches this time lol
?

**Comment by iRoachie** [comment]
Haha that should be it. Make your upstream is actually in sync.
Run `git fetch --all` first.

**Comment by Gregjarvez** [comment]
aha I knew I was gonna mess up again without asking. thanks lol @iRoachie

**Comment by iRoachie** [comment]
Merged in. Will be available in 1.0.0-beta4

**Comment by xavier-villelegier** [comment]
`v1.0.0-beta4` now live on npm
