### ISSUE TITLE
ButtonGroup blue background

### ISSUE THREAD

**Issue by bohdanbirdie** [react-native-training/react-native-elements#1011]
### Description

1. Used `ButtonGroup`
2. Can disable blue color behind button element
3. Once you will set `borderRadius` to buttonStyle - blue color behind will appear.

`v1.0.0-beta3`

### Reproduction Steps and Sample Code

```JavaScript
render() {
        return (
            <View style={styles.container}>
                <ButtonGroup
                    onPress={this.updateIndex.bind(this)}
                    selectedIndex={this.state.tab}
                    buttons={buttons}
                    containerStyle={styles.containerStyle}
                    buttonStyle={styles.buttonStyle}
                    selectedButtonStyle={styles.selectedButtonStyle}
                    innerBorderStyle={{width: 0, color: colorScheme.white}}
                    containerBorderRadius={0}
                    underlayColor={colorScheme.gray}
                />
            </View>

        );
    }
.......

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    containerStyle: {
        height: 50,
        width: '100%',
        // borderTopRightRadius: 20,
        borderWidth: 0,
        backgroundColor: colorScheme.white,
        marginTop: 0,
        borderRadius: 0
    },
    buttonStyle: {
        backgroundColor: colorScheme.white,
        borderTopRightRadius: 20,
        borderTopLeftRadius: 20,
        borderWidth: 0,
    },
    selectedButtonStyle: {
        backgroundColor: colorScheme.gray,
    }
});
```

![image](https://user-images.githubusercontent.com/23266928/37558108-b23f3280-2a06-11e8-889e-73b72eb0e3db.png)

**Comment by xavier-villelegier** [comment]
Hey @bohdanbirdie, you're right this is a bug, we also set the background to the default blue primary color. The problem is [this line](https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/ButtonGroup.js#L97) if someone wants to tackle this 💪

**Comment by k3ithl1m** [comment]
I would like to work on this. Will make a pr as soon as I can

**Comment by dincozdemir** [comment]
@k3ithl1m If you hadn't had a chance to work on this issue, like to fix it.

**Comment by k3ithl1m** [comment]
Hey @dincozdemir Sure thing. I forgot about this issue entirely as I was traveling. Go at it and have fun! :)

**Comment by dincozdemir** [comment]
While i was fixing the issue, I also noticed that this usage gives an error when the given style is defined using ``
StyleSheet.create``:

``borderRightColor:
                  (innerBorderStyle && innerBorderStyle.color) || colors.grey4,``

That's because in such case, innerBorderStyle is a style id, not the style itself.
It should be ``StyleSheet.flatten(innerBorderStyle)`` to avoid crashes.

I see this usage pattern through all the components. I wonder if this is a known issue.

**Comment by xavier-villelegier** [comment]
@dincozdemir As you can see [in the docs](https://react-native-training.github.io/react-native-elements/docs/button_group.html#buttongroup-props), the `innerBorderStyle` has the type `object { width, color }`, it cannot be a Stylesheet object, it's basically a simple object that allows you to override these two border props. Other styles has the type `object (style)`, which can be an object OR a Stylesheet object. The name is a bit confusing tho
