### ISSUE TITLE
Create two icons on <Header>

### ISSUE THREAD

**Issue by teamhide** [react-native-training/react-native-elements#1012]
I want to create two icons on `<Header>`

Just like this ->
<img width="740" alt="2018-03-18 4 54 03" src="https://user-images.githubusercontent.com/8403122/37559393-8df3f282-2a68-11e8-8029-7dd8453c257b.png">

I read the official document(https://react-native-training.github.io/react-native-elements/docs/0.19.0/header.html) But there is no way about this.

Is there any props or possible method?

**Comment by iRoachie** [comment]
Similar to the answer given in https://github.com/react-native-training/react-native-elements/issues/1014#issuecomment-373960237, You have to use the element syntax to accomplish this.

Here's an example snack to show this behavior https://snack.expo.io/@roach_iam/two-icons-in-header

**Comment by teamhide** [comment]
@iRoachie Thanks!
