### ISSUE TITLE
platform Prop for SearchBar is broken

### ISSUE THREAD

**Issue by jackcbrown89** [react-native-training/react-native-elements#1015]
### platform="ios" does nothing and looks like the default style

```
<SearchBar
            showLoading
            platform="ios"
            placeholder='Search'
/>
```
Installed `react-native-elements@0.19.0`

**Comment by iRoachie** [comment]
The iOS and Android styled search bars are only available in the betas. Use `npm install --save react-native-elements@beta` to get the latest one.

**Comment by jackcbrown89** [comment]
Thanks! Maybe we can throw that in the docs.

**Comment by xavier-villelegier** [comment]
@jackcbrown89 You can access versioned doc by clicking on the version in the header of the website. Check out [here](https://react-native-training.github.io/react-native-elements/versions.html) 👍
