### ISSUE TITLE
Add showcase section to website

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1018]
Area to showcase people who’ve built apps using react native elements.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Monte9** [comment]
Blog Post: https://medium.com/@austinhale/building-a-mobile-app-in-10-days-with-react-native-c2a7a524c6b4?source=userActivityShare-60b87ae09e91-1521325250

**Comment by Monte9** [comment]
PR #1704
