### ISSUE TITLE
[v1.0.0-beta3] [SearchBar-android]  Icons not showing on android (MaterialCommunitIcons?)

### ISSUE THREAD

**Issue by MaxInMoon** [react-native-training/react-native-elements#1019]
**Version**

v1.0.0-beta3

**Description**

In [SearchBar-android.js](https://github.com/react-native-training/react-native-elements/blob/master/src/searchbar/SearchBar-android.js#L10), the icon lib is `MaterialCommunitIcons`:

`import MaterialIcon from 'react-native-vector-icons/MaterialCommunitIcons';`

**Problem**

The `clearIcon` doesn' show on Android (cause 'close' doesn't exist in MaterialCommunitIcons?)

**Half fix**

Replace `MaterialCommunitIcons` by `MaterialIcons`like so:

`import MaterialIcon from 'react-native-vector-icons/MaterialIcons';`

But search icon still not show.

___________________________________

Can someone has a working code on android with the v1.0.0-beta3??

Thanks

**Comment by xavier-villelegier** [comment]
@MaxInMoon Replacing `MaterialCommunityIcons` by `MaterialIcons` won't solve the issue as `react-native-vector-icons` supports both ([check this](https://github.com/oblador/react-native-vector-icons#bundled-icon-sets))

You likely forgot to link (if you're using React Native) or to install `@expo/vector-icons` (if you're using Expo) (cf https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210)

**Comment by MaxInMoon** [comment]
@xavier-villelegier you are right thank you: I only used two fonts from vector-icons (and not MaterialCommunityIcons)

Could be cool to let us use a specific lib like:

        icon: {
          name: 'search',
          type: 'material',
          color: '#86939e',
        },

The goal is to link the fewer fonts as possible

**Comment by xavier-villelegier** [comment]
Closing this as you're now able to use custom icons (example for the [`clearIcon`](https://react-native-training.github.io/react-native-elements/docs/searchbar.html#clearicon) props)
