### ISSUE TITLE
Hide border bottom on v1.0.0-beta3 Input

### ISSUE THREAD

**Issue by Trnsmt** [react-native-training/react-native-elements#1024]
Hi! the prop underlineColorAndroid="transparent" on the Input component is not working as expected. The bottom border is still visible. This is on 1.0.0-beta3.

**Comment by xavier-villelegier** [comment]
Hey @Trnsmt, there is a `borderBottom` by default on the `Input` component. You can override it by doing:

```jsx
<Input
  …
  containerStyle={{ borderBottomWidth: 0 }}
/>
```

**Comment by Trnsmt** [comment]
Hey @xavier-villelegier , Thank you! This solved my issue. I was wondering since the documentation says that this component inherits all native TextInput props that come with a standard React Native TextInput element. But this fixed it! Thanks :-)

**Comment by abury** [comment]
This doesn't appear to be working on beta-5. I can't for the life of me hide the bottom border :(
I've tried setting borderBottomWidth, borderWidth and all other possible permutations on both container and input style, nothing seems to be working.

**Comment by xavier-villelegier** [comment]
@abury This became `inputContainerStyle`, you can have a look at the explanation [about the input styles](https://react-native-training.github.io/react-native-elements/docs/input.html#styles-explanation)

**Comment by abury** [comment]
Thanks @xavier-villelegier! Not sure how I missed that one 👍

**Comment by jstansbe** [comment]
"react-native-elements": "1.1.0"
"react-native": "0.58.6"


This works:
`inputContainerStyle={{ borderBottomWidth: 0 }}`

While this does not:
`inputContainerStyle={{ borderWidth: 0 }}`
