### ISSUE TITLE
Cannot verify whether button is disabled in unit test

### ISSUE THREAD

**Issue by lsiden** [react-native-training/react-native-elements#1027]
### Description

When unit testing my component, I want to verify that a certain button is enabled or disabled.

react-native-elements@0.19.0

### Reproduction Steps and Sample Code

1. create-react-native-app
2. yarn add --dev jest
3. yarn add react-native-elements
4. create and run the following test

```
import React from "react"
import renderer from "react-native-test-utils"
import { Button, Icon } from "react-native-elements"

test("can determine if button is disabled from property", () => {
  const button = renderer(
    <Button icon={<Icon name="arrow-up" />} disabled={true} />
  )
  expect(button.props.disabled).toBeTruthy()
  console.log("button props", button.props)
})
```

### Expecting
button.props.disabled should be truthy

### Getting
button.props.disabled is undefined

Based on this, I do not think it will be possible for my app to disable these buttons and I will have to find another solution.

**Comment by iRoachie** [comment]
Not sure if you’re using enzyme correctly, but the method should be `button.props().disabled`. Props is a method on the shallow wrapper.

See http://airbnb.io/enzyme/docs/api/ReactWrapper/props.html

**Comment by lsiden** [comment]
I'm not using enzyme.  I'm using react-native-test-utils.

I'm about to upgrade to react-native-elements#v1.0.0-beta3 to see if that
gives me better traction for simulating a button press.  I'm still on 0.19.0

**Comment by xavier-villelegier** [comment]
@lsiden Feel free to ping me if you think this should be reopened

**Comment by lsiden** [comment]
Thank you for your responses, Xavier.

There has been some progress
<https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md>
on getting enzyme to work with react-native but I couldn't get it to work
out of the box, so I decided to stick with react-native-test-utils and just
use Jest expect().toMatchSnapshot()  until I have time later to improve
this.

I've begun to realize that over-zealous testing is a newbie mistake.  For
example, it shouldn't be necessary to test that a library component
responds to a press isn't necessary since the library authors have already
tested the component.  If my event handler had non-trivial logic, I could
test that directly without simulating an event.  So simulating a browser
environment may not even be needed in many cases.

I also tried to update my project to react-native-elements#v1.0.0-beta3 (I
see that beta4 was released), but doing so introduced new unresolved
dependencies.  I don't need another rabbit hole, so I decided to stick with
v0.19.x until I reach a few milestones.  Then I'll explore it further.  I'm
eager to try it out.

Thanks again for your attention to this.

-Larry

**Comment by xavier-villelegier** [comment]
@lsiden Actually, the lib you choose to use should be testing these kind of things for you, you shouldn't have to test the package you use, but only your own components.
What do you mean by unresolved dependencies ? We didn't add any dependency from `v0.19.x` to `v1.0.0-beta3`. We added a new one in `beta4` but we'll most likely remove it because we don't like to add unnecessary dependencies

**Comment by lsiden** [comment]
FYI, I just tried updating again to 1.0.0-beta4 and didn't have the problems I had before. I'm not sure anymore what they were, but there are no unresolved dependencies this time, so all is good.
