### ISSUE TITLE
No raised prop on Button

### ISSUE THREAD

**Issue by laurence-myers** [react-native-training/react-native-elements#1028]
```<Button buttonStyle={{ raised: true }}```

This fails compilation in TypeScript.

Based on my understanding of PR #816, the "raised" property was moved as a prop of Button to a style property.

A possible fix is to change index.d.ts:L239, as below:
```buttonStyle?: StyleProp<ViewStyle & { raised?: boolean }>;```

**Comment by iRoachie** [comment]
You might be a bit confused by the PR. That PR was moving the styles for `raised` from the outer container, to the immediate container surrounding the button.

`raised` is still a prop, and it used as 
```tsx
<Button raised />
```

**Comment by laurence-myers** [comment]
Thanks for the clarification!

In that case, "raised" is missing from the ButtonProps type definition.

**Comment by Monte9** [comment]
Right. I def missed this on button v1. Might be good to add this back in in one of the upcoming betas. If anyone is interested to work on this, just comment below and feel free to submit a PR for it.

**Comment by iRoachie** [comment]
Here’s an example of how the raised styles were before https://github.com/react-native-training/react-native-elements/blob/v0.19.1/src/buttons/Button.js#L301

**Comment by xavier-villelegier** [comment]
@laurence-myers `v1.0.0-beta5` is out, thanks again @whitedogg13 🔥
