### ISSUE TITLE
Button: TS definitions: "title" property does not exist (1.0.0-beta3) 

### ISSUE THREAD

**Issue by laurence-myers** [react-native-training/react-native-elements#1029]
```<Button title="Hello World!"/>```

This will fail compilation in TypeScript.

There is another property called `text`, perhaps this is intended to be `title`.

**Comment by iRoachie** [comment]
Yes you're correct! This issue has already been fixed in https://github.com/react-native-training/react-native-elements/pull/1017/commits/57c5557093853980958d2c4e1edbca0a7fe6531c. It'll be available in the next release.

**Comment by iRoachie** [comment]
You can extend the `ButtonProps` if you want to be able to use it right now and still have your typings correct.

```tsx
import { ButtonProps, Button } from 'react-native-elements'

class MyButton extends React.Component<ButtonProps & { title?: string }> {
  render() {
    return <Button {...this.props} />;
  }
}
```

Then use MyButton in your source code:
```tsx
<MyButton title="yea" onPress={() => alert('ey')} />
```

**Comment by laurence-myers** [comment]
Ah, thanks very much for the workaround! Since this has been fixed, I'll close this issue.
