### ISSUE TITLE
Scrollbar is not displaying in <Card>

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-native-training/react-native-elements#1031]
Hello Guys,

I have displayed one horizontal bar chart on Card. As I have to use ScrollView on Card but it is not Scrollbar  displaying on Card. How can I do this ?

**Comment by xavier-villelegier** [comment]
Hey @ShaikhKabeer, [here is](https://snack.expo.io/SkdECyW5G) a quick example of how to put an horizontal scrollbar in the `Card`

**Comment by ShaikhKabeer** [comment]
Hey @xavier-villelegier , Thanks Man it is working !!
