### ISSUE TITLE
Congratulations, 10.000 stars

### ISSUE THREAD

**Issue by hosembafer** [react-native-training/react-native-elements#1032]
Guys, you have reached 10.000 stars.

<img width="191" alt="screen shot 2018-03-24 at 7 32 24 pm" src="https://user-images.githubusercontent.com/5071289/37865734-521146fc-2f9a-11e8-9c42-557ceddc297d.png">

**Comment by Monte9** [comment]
![](https://media1.tenor.com/images/774acad780cbd690b5291e942866269c/tenor.gif?itemid=5122518)

**Comment by Monte9** [comment]
The Twitter thread about reaching 10k 🌟
https://twitter.com/MThakkar_/status/977626100716064768

**Comment by martinezguillaume** [comment]
Awesoooooooooome 😯

**Comment by bozzmob** [comment]
Awesome work guys! Well done! Congratulations to the team
