### ISSUE TITLE
ListItem margin/padding for image and text

### ISSUE THREAD

**Issue by chibi-gunso** [react-native-training/react-native-elements#1034]
When using an image or an avatar in a list item

I would expect that an image/avatar can be placed in a list item without margin/padding.

What happens is that the list item always seems to have padding that I can't seem to control.

I've tried removing all the margin/padding styling from parent components but nothing seems to work. See the example attached.

https://snack.expo.io/r1bpxBrqz

It also seems to do the same thing with text in a subtitle as well.

Looks like it might be the wrapper style sheet in ListItem.

Apologies for the terrible code and if this isn't a bug but expected behavior, I'm still pretty new to react native.

**Comment by xavier-villelegier** [comment]
@chibi-gunso Mmh looking at your example, I think the `ListItem` doesn't fit to your use case. Using a simple `View` makes your code shorter and cleaner, [check out this example](https://snack.expo.io/Hy9hBKBcG)

**Comment by chibi-gunso** [comment]
Thanks for example, that was what I was trying to do!
