### ISSUE TITLE
Shadow is not working properly with borderRadius

### ISSUE THREAD

**Issue by doniyor2109** [react-native-training/react-native-elements#1035]
### Description

As given solution in issue #328 I followed the instruction and set ```borderRadius``` for ```containerViewStyle``` too. However my previously set shadow is cut with the ```borderRadius```

![photo5312075677396215954](https://user-images.githubusercontent.com/14192979/37878562-7b096324-3084-11e8-9c52-ca1aa39d578b.jpg)

### Sample Code
```jsx
<Button
  buttonStyle={{
    borderRadius: 20,
    elevation: 15,
  }}
  containerViewStyle={{
    borderRadius: 40,
  }}
/>
```

**Comment by doniyor2109** [comment]
The solution was to add shadow to ```containerViewStyle``` instead of ```buttonStyle```.

```jsx
<Button
  buttonStyle={{
    borderRadius: 20,
  }}
  containerViewStyle={{
    borderRadius: 20,
    elevation: 15,
  }}
/>
```

**Comment by doniyor2109** [comment]
As I applied previously mentioned solution to `containerViewStyle` it works. However when user long presses and holds the button it cuts the **shadow** again

**Comment by xavier-villelegier** [comment]
@doniyor2109 Have a look at https://github.com/react-native-training/react-native-elements/issues/535#issuecomment-320197586

**Comment by doniyor2109** [comment]
Thanks. That is final solution I guess

**Comment by loolooii** [comment]
@xavier-villelegier  That link is broken? Could you share the solution to this?

**Comment by vinhnglx** [comment]
@loolooii the react-native-training has been changed to react-native-elements, so the correct link is: https://github.com/react-native-elements/react-native-elements/issues/535#issuecomment-320197586
