### ISSUE TITLE
ListItem onPress not working

### ISSUE THREAD

**Issue by pensivej** [react-native-training/react-native-elements#1046]
### Description

1. Explain what you did

Hi, I used Expo and tested ListItem with examples provided. Also, I have <ScrollView> at the very top of the rendering layer.

2. What you expected to happen

I made a ListItem with onPress={console.log(l.name)} so that I can see the name of the clicked one when I press.

3. What actually happens

In the console I can see all the names while loading (unexpected), and it won't work when I press the item. It looks like the property works like onLoad(), not onPress().

Here's my dependencies.
"dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-elements": "^0.19.0"
  }

### Reproduction Steps and Sample Code

https://snack.expo.io/@jshim10/unnamed-snack

Here, I used a slightly older version, but still is the problem.
"dependencies": {
    "@expo/vector-icons": "6.2.1",
    "react-native-elements": "0.18.5"
}

**Comment by pensivej** [comment]
found the answer in a minute.
I should bind the function, not calling it.

Proper way would be 
onPress={()=>console.log("I want this")}

**Comment by Moshman20** [comment]
Damnn, thanks a lot man, had the exact same issue @pensivej
