### ISSUE TITLE
Is exporting config/fonts a good idea?

### ISSUE THREAD

**Issue by justin-calleja** [react-native-training/react-native-elements#1051]
#### Explain what you did
I am copying / modifying `ListItem` component because I want it to look differently. As I copy the code, I see I need access to `fonts`: https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L414

But this is not exported (unlike colors: https://github.com/react-native-training/react-native-elements/blob/master/src/index.js#L34)

#### What you expected to happen
I expect I can just import fonts directly instead of something like `import fonts from 'react-native-elements/src/config/fonts'`

Version of RNE: "0.19.0"

### Solution

I can submit a PR with the export if I get the go ahead here.

**Comment by justin-calleja** [comment]
Same "issue" / concern with `config/ViewPropTypes`.

**Comment by xavier-villelegier** [comment]
@justin-calleja We could export them yea, I think it's okay.
For me the concern is more "What do you need to achieve to be forced to copy the `ListItem` in order to modify it ?" The `ListItem` should be flexible enough to avoid as much as possible these kind of troubles to RNE users

Thoughts ? @iRoachie @martinezguillaume @Monte9

**Comment by justin-calleja** [comment]
@xavier-villelegier it's probably my inexperience with RNE. `ListItem` has a `title` and `subtitle` prop. I'm not a designer... but I wanted to have the 3rd line appear as shown below:

<img width="361" alt="listitem" src="https://user-images.githubusercontent.com/3186719/38165314-c40a5376-3511-11e8-8243-c4b8b2031d35.png">

The "estimated time" (EST) is not always present. When it is, it should be next to the "scheduled time" (SCH). Before, I was putting EST as `rightTitle` prop but the destination (second line) can get long sometimes and I think I prefer it on the left now anyway.

I got it to look like I wanted with a stripped down version of `ListItem` and the following below the `subtitle` prop:

```
// 	timeContainerStyle: { flexDirection: 'row', },
<View style={timeContainerStyle}>
    <View style={time1ContainerStyle}>{time1 !== null && <Text style={[styles.time1, time1Style]}>{time1}</Text>}</View>
    <View style={time2ContainerStyle}>{time2 !== null && <Text style={[styles.time2, time2Style]}>{time2}</Text>}</View>
</View>
```

I don't think it can be done with the current `ListItem`. I'm able to get the 2nd `subtitle` line if I use the `subtitleNumberOfLines` props and add a new line in it's value but then I'm stuck with the same style for the whole line. I want to highlight EST based on the selected color scheme.

To be honest, I'm not sure if exporting `fonts` etc… is a good idea or not. I ended up copying over values. That way I know they're going to stay the same. But if semantic versioning is kept on update of these exported values, I guess it's ok to export them from RNE.

Cheers

**Comment by xavier-villelegier** [comment]
@justin-calleja 

[Here is](https://snack.expo.io/@xavier-villelegier/complex-rne-listitem) an example the `ListItem` component ! It can be done pretty easily actually

<img src="https://user-images.githubusercontent.com/17592779/38165778-1e7a9166-3519-11e8-97b8-69ebc988b806.png" width="300" />

**Comment by justin-calleja** [comment]
woah thanks a lot @xavier-villelegier ! Of course, subtitle doesn't only take a string... my bad. It is my inexperience with RNE after all ^^;
