### ISSUE TITLE
Header centerComponent doesn't really center

### ISSUE THREAD

**Issue by kbrandwijk** [react-native-training/react-native-elements#1054]
This was already an existing issue in the previous version, and still is in 1.0.0-beta3. If the leftComponent and rightComponent of a Header don't have equal width, the centerComponent text isn't centered.

My current workaround is to wrap both leftComponent and rightComponent in a View with equal width, but it would still be nice if the centerComponent was actually centered regardless of left and right.

**Comment by iRoachie** [comment]
What's the proposed fix for this?
```
| flex: 1 | flex: 3 | flex: 1 | 
```
?

**Comment by martinezguillaume** [comment]
@iRoachie I’ve already noticed that bug, I think your fix can be good, I can take care of that if you want

**Comment by iRoachie** [comment]
Sure thing, all yours bud

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!

**Comment by n13** [comment]
Great, was about to file a bug

I had another issue that might be related:

When the centerComponent is too big - e.g. a text title that exceeds the available space between the buttons - then it would push the right button off screen, meaning the right button would be gone.

Does the flex solution fix that too?
