### ISSUE TITLE
Not Issue just Question ???

### ISSUE THREAD

**Issue by vbagustinus** [react-native-training/react-native-elements#1055]
Can I gets ` react-native-elements` copied to my project root. I just want to customize color and font default and my config not change when i delete my `node_modules` and `npm / yarn install` again??

**Comment by themakerman** [comment]
@vbagustinus Yup

**Comment by xavier-villelegier** [comment]
@vbagustinus You can still fork the repo and add your own fork in your `package.json`

```
yarn add https://github.com/vbagustinus/react-native-elements.git
```

You'll be glad to hear that we planned to add a theming feature for the `v1.0.0`, that will fit to your use case ! 🎉 We're currently at `v1.0.0-beta4` (most likely releasing today). You can follow this on #216

**Comment by vbagustinus** [comment]
This toolkit so easy to use. Thanks you very much. I'll be waiting for new Release.
