### ISSUE TITLE
Using non Element Components for the Badge component

### ISSUE THREAD

**Issue by aquacash5** [react-native-training/react-native-elements#1058]
I am trying to write a [PriorityBadge](https://snack.expo.io/H1Eb9RyiG)

I expected it to render a badge with an elevation shadow. However, on iOS it doesn't render the shadow.

Expected
![prioritybadge](https://user-images.githubusercontent.com/10753165/38203562-7b2626d2-3654-11e8-9b25-c820c7dbd23f.png)

iOS Render:
![prioritybadge noelevation](https://user-images.githubusercontent.com/10753165/38203730-0bbdf54e-3655-11e8-9c7f-3ba1ddcf370a.png)

I see that it is failing here on line 40 of `src/badge/badge.js`.
```javascript
if (React.isValidElement(component)) {
  Component = component;
}
```

Why does this have to be an Element? Why not let it be any Component?

I would suggest something like this for the Component creation

```javascript
let Component = View;

if (component) {
  Component = component
} else if (onPress) {
  Component = TouchableOpacity
}
```

**Comment by xavier-villelegier** [comment]
@aquacash5 Yea that could be a nice enhancement, feel free to open a PR if you want to take the lead on this one 👍

**Comment by xavier-villelegier** [comment]
@aquacash5 `v1.0.0-beta5` is out 🔥
