### ISSUE TITLE
SearchBar: on tapping clear it does clear the value but the text is still displayed in the search input

### ISSUE THREAD

**Issue by halaharr** [react-native-training/react-native-elements#1064]
### Description
 I have clearIcon set on a search bar. On tapping clearIcon the value is cleared but the search input still have the value. I would expect the values to be cleared from the input text and show the placeholder text.
1. Explain what you did
     Added SearchBar with clearIcon
2. What you expected to happen
    On Tapping clearIcon to clear the text and value and show the placeholder text
3. What actually happens
    On Tapping value is cleared but the text is still there in the searchbar text

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code
Version: 0.19.0
We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by xavier-villelegier** [comment]
Hey @halaharr, yea I noticed that too. As far as I can tell, it's a React Native issue https://github.com/facebook/react-native/issues/18272

**Comment by JanithaR** [comment]
I just started experiencing the same after updating,
"react": "16.2.0" => "16.3.1"
"react-native": "0.53.0" => "react-native": "0.55.2"
"react-native-elements": "^0.19.0" => "^0.19.1"

Should we just wait for react-native bug fix?

**Comment by xavier-villelegier** [comment]
@JanithaR I suppose yea, was it still working on react native `0.53.0` ?

**Comment by no23reason** [comment]
@JanithaR The way I got it working in `react-native` 0.55 was to make the `value` controlled. For example:
```jsx
export class Example extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            query: "",
        };
    }

    handleQueryChange = query =>
        this.setState(state => ({ ...state, query: query || "" }));

    handleSearchCancel = () => this.handleQueryChange("");
    handleSearchClear = () => this.handleQueryChange(""); // maybe differentiate between cancel and clear

    render(): JSX.Element {
        return (
            <View>
                <SearchBar
                    onChangeText={this.handleQueryChange}
                    onCancel={this.handleSearchCancel}
                    onClear={this.handleSearchClear}
                    value={this.state.query}
                />
                {...something else with the query}
            </View>
        );
    }
}
```

**Comment by iRoachie** [comment]
`onClear` should automatically trigger `onChangeText("")`. https://github.com/react-native-training/react-native-elements/blob/master/src/searchbar/SearchBar-default.js#L44

**Comment by xavier-villelegier** [comment]
@no23reason As long as you control the `value` in an internal state with `onChangeText`, this should work automatically. But as you've shown in your example, it's always good to control the `value` you use anyway. ([Quick snack example](https://snack.expo.io/HJR2cYjoM))

**Comment by JanithaR** [comment]
@xavier-villelegier yea, I thought I did something wrong on my end but I couldn't find any diff relating to search bar I have in my app. So I assumed it's something to do with the update and landed here.

**Comment by Monte9** [comment]
@halaharr glad that helped you.

@no23reason that's for posting the code snippet on how you use the `SearchBar` component.

**Comment by Monte9** [comment]
@xavier-villelegier do you think this is a bug with RNE SearchBar?

**Comment by xavier-villelegier** [comment]
@Monte9 Nope this is an issue from react-native, quite easy to test by downgrading RN. Anyway the best practice is to control the `value` you use, so this shouldn't be an issue for most of cases.

**Comment by rmushtaq21** [comment]
Adding `value={this.state.query}` to the SearchBar fixes this issue

**Comment by rdewolff** [comment]
Thanks @no23reason - your solution provided works: using the `value` props.
