### ISSUE TITLE
Some FontAwesome icons not working 

### ISSUE THREAD

**Issue by jarecsni** [react-native-training/react-native-elements#1065]
In an Expo React Native project I am trying to do the following:

```
<Button
   icon={{name: 'smile', type: 'font-awesome'}}
/>

```

However, I'm getting a warning saying 

ExceptionsManager.js:73 Warning: Failed prop type: Invalid prop `name` of value `smile` supplied to `Icon`, expected one of ["glass","music"...

And there's a huge list of permitted font names. As smile is a font awesome icon, I am a bit confused as to why this icon (and many others, like frown :)) do not work for me?

**Comment by xavier-villelegier** [comment]
Hey @jarecsni, if you're using Expo you're probably using `@expo/vector-icons`. We're using the `FontAwesome` component under the hood, and if you [check this Snack](https://snack.expo.io/SkfVv2goG), it appears that the `smile` icon just doesn't work at all with it… maybe you should open an issue on vector-icons `@expo/vector-icons`, or ask on the Expo Slack channel

**Comment by jarecsni** [comment]
Raised [#48](https://github.com/expo/vector-icons/issues/48) in @expo/vector-icons, thanks!
