### ISSUE TITLE
Documentation Proposal: Recipe Section

### ISSUE THREAD

**Issue by jstansbe** [react-native-training/react-native-elements#1072]
NOT AN ISSUE

### Proposed Feature of RNE Documentation
As the RNE components v1 gets closer to release I know docs will be updated.
I like how the current docs show base level and (occasionally) advanced features. There is an opportunity for an additional section in the docs to show common 'recipes' for single RNE components and combinations of RNE components.

### Solution
Create a section/page for typical component use cases and RNE component combinations.

Examples:
-  typical component use case -- component used in a <FlatList />.
-  typical component use case -- a card component that looks like a Tweet.
- component combinations -- add a badge to an icon (ex notification icon has badge showing unread notifications)

**Comment by iRoachie** [comment]
Haha! You are brilliant, we had this exact idea. Checkout https://github.com/react-native-training/react-native-elements/issues/681. Gonna close this so we can move the discussion over there.

**Comment by Monte9** [comment]
This is a great idea @jstansbe. Thanks for pitching it. As @iRoachie said, we are starting to work on it.. so feel free to pitch in on the discussion and help out if you are interested.
