### ISSUE TITLE
center Icon in Button

### ISSUE THREAD

**Issue by guitar9** [react-native-training/react-native-elements#1073]
Version:     "react-native-elements": "^0.19.0",

Hello how can i center the icon in the button?
The Icon is align left. This is what i tried
```
                            <Button
                                rounded
                                buttonStyle={{ backgroundColor: 'green', justifyContent: 'center', alignItems:'center'}}
                                icon={{ name: 'info', type: 'font-awesome' }}
                            />
```

**Comment by mhsekhavat** [comment]
@guitar9 See #771

**Comment by xavier-villelegier** [comment]
@guitar9 As @mhsekhavat referenced, you can use the `Icon` component directly. If you really want to use the `Button`, you will have to do this in `v0.19.0`
```jsx
<Button icon={{ name: "home",  style: { marginRight: 0 } }} buttonStyle={{ width: 50 }} />
```

-----------------
In the new `v1.0.0-beta4`, thanks to @mhsekhavat, you don't have to do anything !
```jsx
<Button icon={<Icon name="home" />} title={null} />
```

**Comment by xavier-villelegier** [comment]
Closing this as it is solved in the beta.
