### ISSUE TITLE
Dismiss Overlay by clicking outside of Overlay Modal (Blur area)

### ISSUE THREAD

**Issue by kevinscience** [react-native-training/react-native-elements#1074]
Is there anyway to dismiss the overlay by clicking the blur area or make this as a feature of overlay?
It would be a very useful and delightful feature for users to use.
Thank you!
<img width="479" alt="overlay" src="https://user-images.githubusercontent.com/19722517/38355341-99777270-388a-11e8-8b0c-2e72193b7a49.png">

**Comment by xavier-villelegier** [comment]
Hey @kevinscience, thanks for your feedback, this is definitely a nice improvement. The `Overlay` component is very new and only available in the beta, so it's missing some features for now. I'll address this in the next beta release 👍

**Comment by Gregjarvez** [comment]
@xavier-villelegier I was thinking. if i wrapped a `ToucableWithoutFeedback` around the outer `View` and added a prop called `overlayBackgroundPress` it would work fine however touching the children will also trigger that handler. Is there a way around this. I am unsure if a higher `zIndex` on the overlay would fix that

**Comment by xavier-villelegier** [comment]
@Gregjarvez Have a look at the [pointerEvents](https://facebook.github.io/react-native/docs/view.html#pointerevents) props of `View`, I think `box-none` can do the job if you apply it on the overlay white view. If not, maybe try to use `none` and add a subview to wrap the content with `auto`. Best way to test if it's not blocking all touch events is basically to add a `Button` in it

**Comment by Gregjarvez** [comment]
@xavier-villelegier oh there is that in react native. sure I will check that out !

**Comment by iRoachie** [comment]
Lol that's the problem he was showing you @xavier-villelegier. Think we may need to rebuild this from the ground up using the built in `Modal` component. 

Was looking at other libraries and they all use Modal underneath.
- [react-native-modal](https://github.com/react-native-community/react-native-modal/blob/master/src/index.js)
- [react-native-modal-popover](https://github.com/doomsower/react-native-modal-popover/blob/master/src/Popover.tsx)
- [react-native-lightbox](https://github.com/oblador/react-native-lightbox/blob/master/LightboxOverlay.js)

**Comment by Gregjarvez** [comment]
@xavier-villelegier yeah I have tried most of the [Responder lifeCycle Methods](https://facebook.github.io/react-native/docs/gesture-responder-system.html#responder-lifecycle)
still won't work

**Comment by xavier-villelegier** [comment]
@Gregjarvez Btw you can just wrap the content in a `TouchableWithoutFeedback` to prevent touch events https://snack.expo.io/HyusGE5oG

**Comment by iRoachie** [comment]
Ha that's actually a pretty neat hack. Empty touchable without a handler :D nice

**Comment by xavier-villelegier** [comment]
Fixed in `v1.0.0-beta5`, @Gregjarvez is a rockstar 🎸
