### ISSUE TITLE
LIstItem - Divider backgroundColor can't customize

### ISSUE THREAD

**Issue by ronadi** [react-native-training/react-native-elements#1075]
Hi All,
Can we customize backgroundColor of Divider in ListItem

[#topDivider](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L79)

```
...
{ topDivider && (
   <Divider style={{ backgroundColor: dividerColor || "blue" }} />
)}
```
[#bottomDivider](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L158)
```
...
{bottomDivider && (
    <Divider style={{ backgroundColor: dividerColor || "blue" }} />
 )}

ListItem.propTypes = {
...
dividerColor: PropTypes.string
}
```

**Comment by xavier-villelegier** [comment]
Hey @ronadi, which version are you using ?

On `v0.19.0` you can do:
```jsx
<ListItem
  …
  containerStyle={{ borderBottomColor: 'red' }}
/>
``` 

On `v1.0.0-beta4` and the new `ListItem` component this is not possible for now
cc @martinezguillaume

**Comment by ronadi** [comment]
Hey @xavier-villelegier  I used v0.19.0.
I already add "containerStyle={{ borderBottomColor: 'red' }}" but only for borderBottom of ListItem, not for borderTop first Child of ListItem.

**Comment by xavier-villelegier** [comment]
@ronadi The `ListItem` doesn't have a `borderTop`. If you're using the `List` component, just replace it by a simple `View` and add your own styling, it will be removed in the v1 anyways

**Comment by ronadi** [comment]
ooo I see, @xavier-villelegier  ok thanks

**Comment by martinezguillaume** [comment]
@ronadi Hey ! If you’re using ListItem in a FlatList, I strongly advice you to use ItemSeparatorComponent prop from FlatList to render separator !

**Comment by ronadi** [comment]
Hey @martinezguillaume, thanks for your advice, but I'm just using simple view not FlatList
