### ISSUE TITLE
Icon styles break when using TouchableNativeFeedback

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1084]
### Description

1. Use Icon with `TouchableNativeFeedback` using the `component` prop
2. Icon to render and styles show correctly
3. No styles are applied to the Icon

Also please include the version of `react-native-elements` that you are using.
> 1.0.0-beta4

### Reproduction Steps and Sample Code
```jsx
<Icon
  component={TouchableNativeFeedback}
  name="check"
  color="#fff"
  size={24}
  raised
  iconStyle={{ fontSize: 20 }}
  containerStyle={{ backgroundColor: Theme.accent, marginRight: 0 }}
  onPress={this.addReview}
/>
```

### Solution
The reason this breaks is that we assume that `component` is always a component that is `View` based. https://github.com/react-native-training/react-native-elements/blob/master/src/icons/Icon.js#L32
`TouchableOpacity` and `TouchableHighlight` both have views attached to them natively. 

However, this is not the case with `TouchableNativeFeedback` - which requires an encasing `View`.
So when we try to apply `containerStyle` it will fail. https://github.com/react-native-training/react-native-elements/blob/master/src/icons/Icon.js#L60.

The solution is to place a `View` inside the Touchable and apply the container styles to it.

**Comment by xavier-villelegier** [comment]
Related to #774, maybe we should fix both at the same time.
As we said that the `containerStyle` should always be the outter component, maybe we should do the same we did for the `Button` ? 
https://github.com/react-native-training/react-native-elements/blob/1c1561c00cdfeb6e554388707bc1c44e6097b646/src/buttons/Button.js#L60-L62

**Comment by iRoachie** [comment]
Yes! I’m in favor of that either way we need a View

**Comment by Gregjarvez** [comment]
I would submit a PR for this 
should I put the view inside the Touchable or encase it 

@iRoachie @xavier-villelegier

**Comment by xavier-villelegier** [comment]
@Gregjarvez Try to do the same as the `Button` to be consistent

**Comment by xavier-villelegier** [comment]
`v1.0.0-beta5` live on npm, thanks again @Gregjarvez 💯
