### ISSUE TITLE
Button with style prop not working properly in Android

### ISSUE THREAD

**Issue by unkownymouse** [react-native-training/react-native-elements#1085]
# Description

### Explain what you did

I've used style prop on `<Button />` to place the button at certain point using `top`, but it doesn't seem to work in Android. There is no problem with iOS.

### What you expected to happen

`<Button />` component should have followed the style prop `top`.
### What actually happens

In Android, it is not working.

### react-native, react and react-native-elements version:
"react": "16.3.1",
"react-native": "0.54.4",
"react-native-elements": "^0.19.1",
"react-native-vector-icons": "^4.6.0",

# Reproduction Steps and Sample Code

```
import React, { Component } from 'react';
import { StyleSheet, View} from 'react-native';
import { Button } from 'react-native-elements';

export default class MyApp extends Component {

  render () {
    return (
      <View style={styles.contain}>
        <Button title='Info!' />
        <Button style={styles.contain} title='Back!'  />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  contain: {
    top: 50
  }
})
```

# Screenshot of emulator:

<img width="361" alt="screen shot 2018-04-07 at 1 27 06 pm" src="https://user-images.githubusercontent.com/32857628/38452719-739d872c-3a67-11e8-858d-67536225ce7e.png">
<img width="493" alt="screen shot 2018-04-07 at 1 26 57 pm" src="https://user-images.githubusercontent.com/32857628/38452720-73d19ecc-3a67-11e8-907e-787b81f7007e.png">

**Comment by iRoachie** [comment]
Can you try using `marginTop` instead?

**Comment by unkownymouse** [comment]
@iRoachie 
I tried `marginTop: 200` but still same result.

It works fine on iOS but doesn't work on Android.

<img width="356" alt="screen shot 2018-04-07 at 1 38 20 pm" src="https://user-images.githubusercontent.com/32857628/38452815-296749d4-3a69-11e8-9d33-88986edb163b.png">
<img width="493" alt="screen shot 2018-04-07 at 1 38 30 pm" src="https://user-images.githubusercontent.com/32857628/38452816-299669da-3a69-11e8-8249-754c9de59e5c.png">

**Comment by unkownymouse** [comment]
@xavier-villelegier I used NativeBase and I encountered same problem. So, I shifted to this and  thought react-native-elements also takes `style` without reading the docs. 

Now it works. Thank you.

**Comment by nucklearproject** [comment]
@xavier-villelegier 
Don't work.
![imagen 2](https://user-images.githubusercontent.com/1203680/44304614-2e4b0f80-a337-11e8-8c5b-3527ac3137f5.png)

Wrapped the button work fine. It's correct?
` <View style={{margin:50}}>
     <Button containerStyle={{ marginTop: 50 }} onPress={this.props.counterReset} title='Resetar'/>
     </View>`
