### ISSUE TITLE
Component Input displayError was removed

### ISSUE THREAD

**Issue by Tonacatecuhtli** [react-native-training/react-native-elements#1088]
### Description

1. Explain what you did
  * Updated to beta4
2. What you expected to happen
  * Nothing because the components I use aren't referenced in the Release Notes
3. What actually happens
  * You deleted the **displayError** property from the **Input** Component now it always shows the Error message.

Also please include the version of `react-native-elements` that you are using.
1.0.0-beta4

### Solution
use
```Javascript
<Input
    secureTextEntry={secureTextEntry}
    placeholder={placeholder}
    value={(secureTextEntry ? null : (value === '') ? null : value)}
    containerStyle={{marginRight: 15, borderColor: '#ddd'}}
    onChangeText={text => onChangeText(name, text)}
    errorStyle={(displayError) ? errorStyle : null}
    errorMessage={(displayError) ? errorMessage : null}
/>
```
instead of:

```
<Input
    secureTextEntry={secureTextEntry}
    placeholder={placeholder}
    value={(secureTextEntry ? null : (value === '') ? null : value)}
    onChangeText={text => onChangeText(name, text)}
    displayError={displayError}
    errorStyle={errorStyle}
    errorMessage={errorMessage}
/>
```
or add it again xD

**Comment by LouisJS** [comment]
Come on, you could just add :
```
{ displayError && <Text style={errorStyle}> {errorMessage} </Text> }
```

😅

**Comment by Tonacatecuhtli** [comment]
I know that's why I added the solution xD but yours is more to the point.

**Comment by xavier-villelegier** [comment]
@Tonacatecuhtli You’re right we missed that in the release notes ! We added the a `label` feature + removed `displayError`. Will add that
