### ISSUE TITLE
Button title only partially showing 

### ISSUE THREAD

**Issue by amansahil** [react-native-training/react-native-elements#1089]
So after upgrading to the new expo sdk 26.0.0 , all my button titles started appearing only partially. I'm not sure if this is an issue with expo or with react native elements. 

Here is the snack :  https://snack.expo.io/HyNleeKof

Image of what is happening : 

![93963](https://user-images.githubusercontent.com/33552991/38502095-2df4e8c0-3c2c-11e8-9166-ad1cc046823b.jpg)

**Comment by xavier-villelegier** [comment]
Hey @amansahil, if you upgrade to `v1.0.0-beta4` you won't have this issue.

If you want to stay on `0.19.x`, just remove the `height: 45`. You can then override the `padding` if it's too big for you

```
<Button
  title="PLAY"
  large
  textStyle={{ fontWeight: "700" }}
  onPress={() => this.Play()}
  buttonStyle={{
    backgroundColor: "#41D3B7",
    width: SCREEN_WIDTH * 0.8,
    paddingVertical: 12,
    borderColor: "transparent",
    borderWidth: 0,
    borderRadius: 5,
  }}
/>
```
