### ISSUE TITLE
Input errorMessage

### ISSUE THREAD

**Issue by Syahrul** [react-native-training/react-native-elements#1093]
React-native-elements **1.0.0-beta4**
React **16.3.0-alpha.1**

Input props `errorMessage` is showing even though `displayError` is false

**Comment by xavier-villelegier** [comment]
hey @Syahrul, `displayError` was removed, it nows display an error whenever you provide an `errorMessage`. Have a look at the [release notes](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta4)

**Comment by Syahrul** [comment]
Okay thanks
