### ISSUE TITLE
Rewrite Avatar sizes props to use one size prop

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1095]
Right now avatar has `small`, `medium`, `large`,  and `xlarge` props for setting the size.

This doesn't make sense because the user shouldn't be able to set both `small` and `medium` at the same time.

Instead we should have one `size` prop that can take in either "small" | "medium" | "large" | "xlarge"

**Comment by xavier-villelegier** [comment]
@Gregjarvez You've been on fire recently man 🔥

**Comment by Gregjarvez** [comment]
@xavier-villelegier I know right !! 😄xd

**Comment by iRoachie** [comment]
Ha looks great @Gregjarvez

**Comment by xavier-villelegier** [comment]
`v1.0.0-beta5` released 🥇
