### ISSUE TITLE
Use refs for Input

### ISSUE THREAD

**Issue by M1chaelChen** [react-native-training/react-native-elements#1096]
### Description

I have two text input, email and password. I want to change focus to password input when user submit editing the email input. When trying to use the code below, the error display `Cannot read property 'focus' of undefined`, which means the ref is not working.
Guess the issue is caused by the wrapper component of Input. When I call `focus()` it actually points to the wrapper of password input but not the input itself.

Also please include the version of `react-native-elements` that you are using.
`1.0.0-beta4`

### Reproduction Steps and Sample Code

```
<Input
  onSubmitEditing={() => {
    this.passwordInput.focus();
  }}
/>
<Input
  ref={(passwordInput) => { this.passwordInput = passwordInput; }}
/>
```

**Comment by iRoachie** [comment]
Here's an example of this working https://snack.expo.io/Sy91gbjoz ✌🏽

**Comment by M1chaelChen** [comment]
@iRoachie Thanks that works. I found my problem is that I wrapped the Input component with my own component like this. So that I can customize the global style for the whole project, but somehow the ref is not working. Anyway, I am closing this issue. Thank you very much for the answer.
```
<Input
  containerStyle={[
    styles.input,
    styles[props.class],
    props.style ? props.style : {},
  ]}
  inputContainerStyle={{ borderBottomWidth: 0 }}
  onChangeText={props.onChange}
  underlineColorAndroid="transparent"
  {...props}
/>
```

**Comment by M1chaelChen** [comment]
@iRoachie I think the issue is that the ref points to my own component instead of the Input from `react-native-elements`. Do you have any solutions to make it work for my case?

**Comment by iRoachie** [comment]
You just need to assign the ref in your own component.

```js
class MyInput extends React.Component {
  render() {
    <Input
     ref={ref => this.ref = ref}
      containerStyle={[
        styles.input,
        styles[props.class],
        props.style ? props.style : {},
      ]}
      inputContainerStyle={{ borderBottomWidth: 0 }}
      onChangeText={props.onChange}
      underlineColorAndroid="transparent"
      {...props}
  />
  }
}
```

**Comment by M1chaelChen** [comment]
Finally figured this out. The ref in my case will point to my wrapper component instead of the Input component itself. The solution for me is this:
```
const HHInput = props => (
  <Input
    containerStyle={[
      styles.input,
      styles[props.class],
      props.style ? props.style : {},
    ]}
    inputContainerStyle={{ borderBottomWidth: 0 }}
    onChangeText={props.onChange}
    underlineColorAndroid="transparent"
    ref={props.inputRef}
    {...props}
  />
);
```
And whenever I want to use ref, I just need to pass it as inputRef like this:
```
<Input
  onSubmitEditing={() => {
    this.passwordInput.focus();
  }}
/>
<Input
  inputRef={(passwordInput) => { this.passwordInput = passwordInput; }}
/>
```
And now it works fine.

**Comment by iRoachie** [comment]
Well thats another way to do it using props (`inputRef`)! Glad you got it sorted out
