### ISSUE TITLE
Buttons seem to have a 15-20px margin on each side of it

### ISSUE THREAD

**Issue by kylewetton** [react-native-training/react-native-elements#1097]
### Description

Just trying out some Components, I noticed that buttons have a pesky margin on the sides I can't get rid of. I've tried buttonStyle and containerStyle margin attributes, just can't figure out how to get these buttons flush against elements next to it.

### Reproduction Steps and Sample Code

```
import React from 'react';
import { Button } from 'react-native-elements';

export default class DetailsScreen extends React.Component {
  render() {
    return (
        <Button
         title="Why the margin?"
        />
    );
  }
}

```

**Comment by xavier-villelegier** [comment]
@kylewetton Which version are you using ?

**Comment by xavier-villelegier** [comment]
Glad you got this working 👏
