### ISSUE TITLE
Input not working

### ISSUE THREAD

**Issue by carmenchapa** [react-native-training/react-native-elements#1099]
I added just added react-native-elements to my project and tried to use <Input> component, I got this error:

```
ExceptionsManager.js:73 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at LoginScreen.js:12.
    in LoginScreen (at SceneView.js:17)
    in SceneView (at CardStack.js:455)
    in RCTView (at View.js:78)
    in View (at CardStack.js:454)
    in RCTView (at View.js:78)
    in View (at CardStack.js:453)
    in RCTView (at View.js:78)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:78)
    in View (at CardStack.js:414)
    in RCTView (at View.js:78)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:78)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at App.js:77)
    in RCTView (at View.js:78)
    in View (at App.js:75)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34) 
```

I imported the component as usual: 
`import { Input, Badge } from 'react-native-elements';`

And then inside my component.
```
<Input
    placeholder='BASIC INPUT'
/>
```

I looked into the modules and in the input folder there is Search.js instead, it seems that something is messed up.

Thanks!

**Comment by iRoachie** [comment]
Closing as dup of #1025

**Comment by ferpalma21** [comment]
I can't make it work, I'm using Search as component instead of input and still with the same error. Path react-native-elements/src/Input/Search.js .

`
`
import React from 'react';
import {  View, Text, StyleSheet } from 'react-native';
import Icon  from 'react-native-vector-icons/FontAwesome';
import {  Button, Search } from 'react-native-elements';


export default class RegisterScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {

    }
  }
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Register</Text>
        <Search
       style={{height: 30, width: 300, borderColor: 'gray', borderWidth: 1}}
       placeholder="Name"
     />
      </View>
    );
  }
}


``

**Comment by iRoachie** [comment]
@ferpalma21 Please create a new issue, also stating which version of react-native-elements you're using. There's no `Search` component, it's `SearchBar`

**Comment by EdemOne** [comment]
This normally occurs when using a version of react-native-elements that doesn't support the element in question. Check your react native elements version and its supported elements from their website. For example <Input / > is not supported in the version 0.19.1 of react-native-elements, you will have to use FormInput instead. 
Thanks
