### ISSUE TITLE
Icon not rendering with the Button Component

### ISSUE THREAD

**Issue by vikrantnegi** [react-native-training/react-native-elements#1100]
Versions:
```
"react": "16.3.1",
"react-native": "0.55.1",
"react-native-elements": "^0.19.1",
"react-native-vector-icons": "^4.6.0",
````
### Description

1. Explain what you did
Trying to use the `Button` component with an Icon.

2. What you expected to happen
The `Button` component should have a vector icon along with the text. 

3. What actually happens
Button with text but no Icon is appearing. 

I thought this might be because react-native-vector-icons might not have installed properly but this is not the case as I'm able to use the vector icons when not using with the `Button` component of this library.

### Reproduction Steps and Sample Code

Here is the code snippet:
```
import React from "react";
import { View, Text, StyleSheet } from "react-native";
import { Button } from "react-native-elements";
import Icon from "react-native-vector-icons/FontAwesome";

const Home = () => (
  <View style={styles.container}>
    <Button
      icon={<Icon name="arrow-right" size={30} color="#000" />}
      title="BUTTON WITH ICON"
      buttonStyle={{
        backgroundColor: "rgba(92, 99,216, 1)"
      }}
    />
    <Icon.Button name="facebook" backgroundColor="#3b5998">
      Login with Facebook
    </Icon.Button>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center"
  }
});

export default Home;

```
Screenshot:
![screen shot 2018-04-12 at 3 14 13 pm](https://user-images.githubusercontent.com/3294287/38669506-337adba8-3e64-11e8-9822-486b267a2843.png)

**Comment by xavier-villelegier** [comment]
Hey @vikrantnegi 👋 
If you use `v0.19.x`, the `Button` component takes an object:
```jsx
<Button
  icon={{ name: 'arrow-right', type: 'font-awesome' }}
  title="BUTTON WITH ICON"
  buttonStyle={{
    backgroundColor: "rgba(92, 99,216, 1)"
  }}
/>
```

If you use the last version `v1.0.0-beta4`, the `Button` has been rewritten from scratch, and you should do:
```jsx
<Button
  icon={<FontAwesome name="arrow-right" color="white" size={18} />}
  title="BUTTON WITH ICON"
  buttonStyle={{
    backgroundColor: "rgba(92, 99,216, 1)"
  }}
/>
```

Remember that on the documentation website, you can see the versioned doc by clicking on the version on the header

**Comment by vikrantnegi** [comment]
Thanks. I was confused for the last 4 hours. 

I think this can be improved as by default when I install the `react-native-elements` it installs the stable version but when I go to the doc from the GitHub repo description I'm sent to the beta documentation.
Either the documentation should be the default for the stable version or it should be mentioned somewhere.

Or I am missing something here?

**Comment by vikrantnegi** [comment]
@xavier-villelegier Great. Let's make sure others don't face the similar problems that I faced.

Do you think there can be any other way by which users can be properly informed about this? 
Like mentioning somewhere in the readme or maybe in the documentation itself. Currently, the version number on the right of the logo is not something that user would look right away. Maybe some text to explicitly inform the user about this.

Thanks for the amazing library.

**Comment by xavier-villelegier** [comment]
@vikrantnegi I've opened a PR with a quick workaround to fix that #1101

**Comment by vikrantnegi** [comment]
Great. Thank you. :)
Feel free to close the issue.

**Comment by iRoachie** [comment]
Just added this in https://github.com/react-native-training/react-native-elements/commit/276b346c4ccef1a9b330de8bf9c7cd727724b2cd. Will roll it out on the 1.0.0-beta5 release
