### ISSUE TITLE
Opacity layer not following borderRadius on button press

### ISSUE THREAD

**Issue by carmenchapa** [react-native-training/react-native-elements#1102]
Hi guys, 

Sorry I'm opening this again, I know this issue has appeared a lot here, I have read #328, #535, #1035, #581, however I cannot make it work..

### Description

1. I have a button with borderRadius 

```
<Button 
        title='LOG IN'
        style={{ borderRadius: 50 }}
        borderRadius={25}
        buttonStyle={{ 
               width: 260,
               backgroundColor: '#58D7B5',
               borderWidth: 1,
               borderColor: '#fff',
               alignSelf: 'center',
               margin: 16,
               elevation: 0, 
               borderRadius: 25 }}
         containerViewStyle={{borderRadius:25}}
         // containerStyle={ {elevation: 0, borderRadius: 25}}
 />
```
2. I am expecting to see the border radius applied to the opacity layer when pressing the button.
3. But is just a rectangle instead.

![button_bug](https://user-images.githubusercontent.com/17295559/38675666-5d743df0-3e50-11e8-9332-5686e1461b56.png)

I am using "react-native-elements": "^1.0.0-beta4"

### Reproduction Steps and Sample Code

Snack example:

https://snack.expo.io/HyUL9T3if

Any help would be much appreciate 🙏
Thanks!

**Comment by xavier-villelegier** [comment]
Hey @carmenchapa,

You're right, in the `v1.0.0-beta4` we forgot to handle this case in the new refactored `Button`.

In the meantime, you can use this as a workaround:

```jsx
let background
if (Platform.Version >= 21) {
  background = TouchableNativeFeedback.Ripple(
    'ThemeAttrAndroid',
    true
  );
} else {
  background = TouchableNativeFeedback.SelectableBackground();
}

<Button
  background={background}
  title='LOG IN'
  buttonStyle={{ 
    backgroundColor: '#58D7B5',
    borderRadius: 25,
    elevation: 0,
  }}
  containerStyle={{
    width: 260,
    borderWidth: 1,
    borderColor: '#fff',
    margin: 16,
    borderRadius: 25,
  }}
/>
```
[Here is a snack example](https://snack.expo.io/HkZigC2of)

**Comment by xavier-villelegier** [comment]
For anyone who wants to tackle this issue, here are the lines that were in `v0.19.0`
https://github.com/react-native-training/react-native-elements/blob/e2bfb15a63e9383d647441e61678b9f83f12410c/src/buttons/Button.js#L128-L137

**Comment by carmenchapa** [comment]
Thanks a lot Xavier!!
That perfectly worked.

I am using the workaround from now, probably will tackle it later on.

**Comment by xavier-villelegier** [comment]
@carmenchapa Fixed in `v1.0.0-beta5` available on npm, thanks to @Gregjarvez 🔥 💯

**Comment by Sxubas** [comment]
Nor this solution or  #328 could solve it for me. I'm using 0.19.1. It's really strange, as when I pass the 'borderRadius' or 'containerViewStyle' props, the button disappears (no warning / error). This is my button code:

```
<Button
      title='Enviar'
      icon={{name: 'cloud-upload'}}
      /* borderRadius={8} */
      /* containerViewStyle={{borderRadius: 8}} */
      buttonStyle={styles.button}
/>
```

Am I missing something?
Thanks in advance

**Comment by iRoachie** [comment]
Hey @Sxubas you can see your example working fine in this example https://snack.expo.io/r1geIGq1Q

**Comment by Sxubas** [comment]
8px its really tiny to notice, took it up to 24px and got this
![image](https://user-images.githubusercontent.com/19129356/40632233-328c7b42-62aa-11e8-988f-77623f4d79d3.png)

**Comment by iRoachie** [comment]
I'm not seeing that at all even at 30px. https://snack.expo.io/HJb-6zqym

**Comment by xavier-villelegier** [comment]
@Sxubas Could you try 1.0.0-beta5 just to be sure ? We made some tiny changes in the condition above. Be sure you clean install your node modules and any lock file

**Comment by monkeykingblack** [comment]
@xavier-villelegier i use 1.0.0-beta5 now, and this still appear me

**Comment by sinodko** [comment]
whats up with this issue? I'm still encountering this in v1.0.0

**Comment by iRoachie** [comment]
@sinodko please create a new issue.
