### ISSUE TITLE
Unable to style header rightComponent

### ISSUE THREAD

**Issue by garethiv** [react-native-training/react-native-elements#1106]
I am using the header component and calling a method that returns JSX for the 'rightComponent'. This method returns a clickable + icon. On render, this item is pushed to the very bottom of the header (not aligned with vertically with the 'centreComponent'. 

Therefore, I tried to add style (in a similar way to the centre component), but receive an unexpected token error.

Am I missing something here?

```
      <Header
      centerComponent={{ text: this.props.headerText, style: styles.centerStyle }}
      rightComponent={this.renderAddButton(), style: styles.rightStyle }
      />
```

**Comment by garethiv** [comment]
@iRoachie I have tried that 

```
return (
    <Icon
      color='#4880FB'
      name="add"
      onPress={onPress}
      size={25}
      style={styles.buttonStyle}
    />
  );
};

const styles = {
  buttonStyle: {
    marginRight: 15,
    marginBottom: 40
  }
};
```

This has no effect unfortunately

**Comment by iRoachie** [comment]
You can wrap the component in a `View` first https://snack.expo.io/H1Xu0xaif

**Comment by garethiv** [comment]
@iRoachie It's that simple xD, thanks.
