### ISSUE TITLE
Typescript Definitions (0.19.1) ButtonGroup selectedButtonStyle missing (TS2339)

### ISSUE THREAD

**Issue by yamiscott** [react-native-training/react-native-elements#1111]
### Description

1. Create a `ButtonGroup` and try set the `selectedButtonStyle` prop
2. Everything to be fine and the style to be honoured
3. It works, but Typescript isn't happy as the prop is missing from the types file.

#### Error received
    Error:(40, 117) TS2339: Property 'selectedButtonStyle' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ButtonGroup> & Readonly<{ children?: ReactNode; }>...'.

React Native Elements 0.19.1

### Reproduction Steps and Sample Code

https://snack.expo.io/ryBLe4Asz

There's no TS linting in snack, so you'll need to try it out in a local project with TS enabled and elements added as a dependency.

The main issue is that `index.d.ts` states:

    export interface ButtonGroupProps {
      selectedIndex: number;
      onPress(selectedIndex: number): void;
      buttons: string[] | ElementObject[];
      component?: React.ComponentClass;
      containerStyle?: StyleProp<ViewStyle>;
      buttonStyle?: StyleProp<ViewStyle>;
      selectedBackgroundColor?: string;
      textStyle?: StyleProp<TextStyle>;
      selectedTextStyle?: StyleProp<TextStyle>;
      innerBorderStyle?: InnerBorderStyleProperty;
      underlayColor?: string;
      disableSelected?: boolean;
      activeOpacity?: number;
      containerBorderRadius?: number;
      lastBorderStyle?: StyleProp<TextStyle | ViewStyle>;
      onHideUnderlay?(): void;
      onShowUnderlay?(): void;
      setOpacityTo?(value: number): void;
    }

While the `ButtonGroup.js` file states:

    const ButtonGroup = props => {
      const {
        component,
        buttons,
        onPress,
        selectedIndex,
        containerStyle,
        innerBorderStyle,
        lastBorderStyle,
        buttonStyle,
        textStyle,
        selectedTextStyle,
        selectedButtonStyle,
        underlayColor,
        activeOpacity,
        onHideUnderlay,
        onShowUnderlay,
        setOpacityTo,
        containerBorderRadius,
        disableSelected,
        ...attributes
      } = props;

### Solution

Just add the following to the `index.d.ts` file:

    selectedButtonStyle?: StyleProp<ViewStyle>;

**Comment by iRoachie** [comment]
We're aware of this, and we fixed it for the upcoming `1.0.0-beta5` https://github.com/react-native-training/react-native-elements/pull/1077/commits/56aada4e73325a5d8df206b840292bacf12af251. I'm not sure if it will be available for the main `0.19.x`.

**Comment by Monte9** [comment]
@yamiscott thanks for bringing this issue to our attention. We are trying to minimize the work we put into `v0.19.1` as that's our "stable" version. Hence all non-critical bug fixes are going to go into the beta versions. 

In your case, if you need this fixed, I would recommend upgrading to our beta version and getting ahead of the migration to v1.0. We are currently on `v1.0.0-beta4` and that's the one we are actively developing. You can install it using `npm install react-native-elements@beta --save`

And as @iRoachie pointed out above, this has been fixed and will be avaible in the next beta release `v1.0.0-beta5`. Hope this helps. 

Just be aware that there are a few breaking changes when you upgrade to v1.. so please use the release notes to cross-reference any breaking changes you see in the app. Here are all the release notes: https://github.com/react-native-training/react-native-elements/releases

**Comment by xavier-villelegier** [comment]
`v1.0.0-beta5` live on npm 👍
