### ISSUE TITLE
Android - Button from background shows above Overlay

### ISSUE THREAD

**Issue by runia1** [react-native-training/react-native-elements#1112]
### Button from background screen showing above the Overlay.

1. Explain what you did
I have a login screen which has a Login Button.  When the user clicks "forgot password" we display an Overlay.  The issue is that the Login Button from the background displays above the Overlay.

Here you can see the background screen is somewhat darkened by the Overlay's background EXCEPT for the login button.
![screenshot_20180412-001435](https://user-images.githubusercontent.com/6709518/38682744-1bad26ce-3e29-11e8-9845-3b4d51926573.png)

This one is even more obvious because when the keyboard pushed the background screen up, the login Button actually shows over the Overlay's content.
![screenshot_20180412-001446](https://user-images.githubusercontent.com/6709518/38682848-55db0ffa-3e29-11e8-931f-9620ddec21ac.png)

2. What you expected to happen
The Overlay to cover everything in the background.

3. What actually happens
The Button from the background shows up above the overlay.

Also please include the version of `react-native-elements` that you are using.
1.0.0-beta4

**Comment by iRoachie** [comment]
Hey, instead of making a PR to add a higher elevation, you can use the ‘containerStyle’ prop and set the elevation there.

**Comment by iRoachie** [comment]
I think maybe the docs approach would be better. Setting it to 5 may help in your use case, however for someone else that has other elements on the page that have a elevation of 5, would have the problem still. So its more of letting people know the principle of how the overlay works - zIndex on iOS and elevation on android

**Comment by runia1** [comment]
That's fine with me, I didn't have the collision on ios.  It may be worth adding a bit to the Button docs letting people know the default elevation is set to 4 as well.

**Comment by KeKs0r** [comment]
I think the PR did actually make sense. By default the elevation of the overlay should be higher than the buttons (by default).

I understand that the elevation can manually be changed in other implementations and therefore it might not solve the problem in all cases, but I think sane defaults would make sense.

**Comment by iRoachie** [comment]
Good point @KeKs0r. I’ll reopen the PR

**Comment by xavier-villelegier** [comment]
@runia1 @KeKs0r Fixed in `v1.0.0-beta5`, live on npm 🎉
