### ISSUE TITLE
SearchBar should support returnKeyType prop (and default should be 'search')

### ISSUE THREAD

**Issue by abury** [react-native-training/react-native-elements#1114]
### Description

Search Bar should support the return key prop type, and default to Search given the desired functionality of the component.

I'll see if I can add this in and open a PR

**Comment by abury** [comment]
Bah, never mind. Obviously, it is supported, I just made a few mistakes. All good 👍

**Comment by iRoachie** [comment]
Glad you figured that out mate 👍

**Comment by robertmylne** [comment]
What is the prop called? I can't find it in the docs either.
