### ISSUE TITLE
textAlign right problem in ios

### ISSUE THREAD

**Issue by jsina** [react-native-training/react-native-elements#1115]
when I want to use **FormInput** with **right** textAlign on **IOS**, the input text in not show properly, but it's OK in android.

as you could see on the picture the **placeholder** and also when filling the textInput the **FormInput** is going to be filled from out of the box.

I wanna know that is there any solution for change the direction of FormInput without any bug on IOS devices?

```
<FormInput
              underlineColorAndroid='transparent'
              containerStyle={styles.inputContainer}
              inputStyle={{ textAlign: 'right', }}
              placeholder="نام کاربری"
              placeholderTextColor="#b2bec3" />

```
<img width="353" alt="screen shot 1397-01-25 at 12 57 27" src="https://user-images.githubusercontent.com/2977960/38766416-2e243f9e-3fe7-11e8-98f7-035d058c0639.png">

**Comment by xavier-villelegier** [comment]
Hey @jsina, what if you add `width: '100%'` ?

```jsx
<FormInput
  underlineColorAndroid='transparent'
  inputStyle={{ textAlign: 'right', width: '100%'}}
  placeholder="نام کاربری"
  placeholderTextColor="#b2bec3"
/>
```

By the way maybe you should test the beta version of the `v1.0.0`, the `Input` component handles this in a better way.
```
npm i -S react-native-elements@beta
```

**Comment by jsina** [comment]
@xavier-villegier Our team is gonna work on a new project so how the beta version is gonna be fragile for us in future? Because the beta version is not stable and it’s not sustainable yet.

**Comment by xavier-villelegier** [comment]
@jsina The padding is applied on iOS too, you can test it by putting a higher value (like 20 or so). But yea it seems to be handled in a different way on Android and iOS, not sure where it comes from, as we're just passing the `inputStyle` to the React Native `TextInput`…

Maybe you can just do something like
```js
inputContainer: {
  // width: '100%',
  paddingRight: Platform.OS === 'ios' ? 16 : 8,
  backgroundColor: '#fff',
  borderRadius: 10,
  // borderWidth: 1,
  // borderColor: 'rgba(110, 120, 170, 1)',
  height: 40,
  marginVertical: 5,
},
```

For the beta, I wouldn't say that it's not stable. It's just changing a lot comparing to `v0.19.0`, so using the beta might be the easiest way to so a smooth transition to the final `v1.0.0`
