### ISSUE TITLE
what does property "chevron" mean in ListItem

### ISSUE THREAD

**Issue by xiechao06** [react-native-training/react-native-elements#1117]
### Description

1. Explain what you did
in 
https://react-native-training.github.io/react-native-elements/docs/listitem.html#chevron,
I find nothing useful. I guess it controls whether the right arrow appears, but it doesn't.

version: 1.0.0-beta4

**Comment by xavier-villelegier** [comment]
@xiechao06 Yes it controls the right arrow.

|Code|Result|
|-----|-------|
|`<ListItem title="Hey" chevron />`|![image](https://user-images.githubusercontent.com/17592779/38778127-74a303ec-40b4-11e8-8d73-da35bf68a206.png)|
|`<ListItem title="Hey" chevron />`|![image](https://user-images.githubusercontent.com/17592779/38778129-7e3f3196-40b4-11e8-98bb-c3dfee8c8221.png)|

**Comment by 3ace** [comment]
I'm also experiencing this, I'm using version 0.19. By default Chevron is displayed, even setting chevron={false} wont hide it.

**Comment by 3ace** [comment]
@iRoachie ah thanks, I've been looking at 1.0.0 beta 4 documentation all this time without realizing that it's different :(

**Comment by iRoachie** [comment]
Sorry about that mate! In the next version the website will show 0.19 as the default version
