### ISSUE TITLE
[FEATURE REQUEST] Make padding value between ListItem components customizable

### ISSUE THREAD

**Issue by kanteankit** [react-native-training/react-native-elements#1119]
If you go into the code of `ListItem`, you'll see that there is a component named `PadView` which adds spacing between the leftComponent, the title component & right component. It has a static value of 16.

This should be customizable and user should be allowed to add this pad value

**Comment by iRoachie** [comment]
Seems like an easy change. Do you mind making a PR for it?

**Comment by ashishmusale** [comment]
When will this be available?

**Comment by ashishmusale** [comment]
any update on when the next release will be available?

**Comment by iRoachie** [comment]
Not as yet, still wrapping up some core features. If you want to use this feature you can use the `next` branch in your project.

`npm install --save https://github.com/react-native-training/react-native-elements.git#next`

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
