### ISSUE TITLE
adjustsFontSizeToFit property for the card Title

### ISSUE THREAD

**Issue by amansahil** [react-native-training/react-native-elements#1121]
I have a card with a fixed height and width. Whenever there is a long text , part of the text disappears, I added `titleNumberOfLines={3}`  but that just gave three dots to represent the faded characters. Is there any way to add `adjustsFontSizeToFit` to the title property of the Card or any other alternative workaround for this.

**Comment by xavier-villelegier** [comment]
@amansahil mmh the title is not truncated by default, even if you add a fixed height. ([Check this Snack](https://snack.expo.io/SJ4VeyfhM)). Can you be more precise and add an example ?

**Comment by amansahil** [comment]
Hi, here is the snack 

https://snack.expo.io/@amansahil/react-card


This is what's happening (Ignore the hotspot symbol)

![34395](https://user-images.githubusercontent.com/33552991/38800221-563ffe70-4184-11e8-83ae-5ca6e1953927.jpg)

Could the font size somehow adjust ?

**Comment by amansahil** [comment]
@xavier-villelegier I set the height cause I'm stacking the cards , without the height the texts that are longer than others stick out.

**Comment by xavier-villelegier** [comment]
@amansahil Okay I see. Using a custom component should do the job then.
