### ISSUE TITLE
Unable to resolve module react-native-vector-icons/Feather

### ISSUE THREAD

**Issue by KD-Dhiren** [react-native-training/react-native-elements#1124]
The development server returned response error code: 500

URL: http: //10.0.2.2:8081/index.android.delta?platform=android&dev=true&minify=false

Body: {
    "originModulePath": "G:\\ReactNative\\pApp\\node_modules\\react-native-elements\\src\\helpers\\getIconType.js",
    "targetModuleName": "react-native-vector-icons/Feather",
    "message": "Unable to resolve module `react-native-vector-icons/Feather` from `G:\\ReactNative\\pApp\\node_modules\\react-native-elements\\src\\helpers\\getIconType.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.",
    "errors": [
        {
            "description": "Unable to resolve module `react-native-vector-icons/Feather` from `G:\\ReactNative\\pApp\\node_modules\\react-native-elements\\src\\helpers\\getIconType.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."
        }
    ],
    "name": "Error",
    "stack": "Error: Unable to resolve module `react-native-vector-icons/Feather` from `G:\\ReactNative\\pApp\\node_modules\\react-native-elements\\src\\helpers\\getIconType.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (G:\\ReactNative\\pApp\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:158:1476)\n    at ResolutionRequest.resolveDependency (G:\\ReactNative\\pApp\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ResolutionRequest.js:92:16)\n    at DependencyGraph.resolveDependency (G:\\ReactNative\\pApp\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:271:4465)\n    at dependencies.map.relativePath (G:\\ReactNative\\pApp\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:379:19)\n    at Array.map (<anonymous>)\n    at resolveDependencies (G:\\ReactNative\\pApp\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:378:16)\n    at G:\\ReactNative\\pApp\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:203:33\n    at Generator.next (<anonymous>)\n    at step (G:\\ReactNative\\pApp\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:296:307)\n    at G:\\ReactNative\\pApp\\node_modules\\metro\\src\\DeltaBundler\\traverseDependencies.js:296:467"
}
processBundleResult
    BundleDownloader.java: 231
access$100
    BundleDownloader.java: 37
onResponse
    BundleDownloader.java: 204
execute
    RealCall.java: 135
run
    NamedRunnable.java: 32
runWorker
    ThreadPoolExecutor.java: 1133
run
    ThreadPoolExecutor.java: 607
run
    Thread.java: 761

**Comment by xavier-villelegier** [comment]
Closing this as this issue has been opened many times and has always been resolved by a fresh install of the vector icons. Be sure you follow exactly the steps stipulated in https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-340556299 or https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210, and that you've cleaned/restarted your environment

**Comment by kumbharketanm** [comment]
> Closing this as this issue has been opened many times and has always been resolved by a fresh install of the vector icons. Be sure you follow exactly the steps stipulated in [#620 (comment)](https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-340556299) or [#620 (comment)](https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210), and that you've cleaned/restarted your environment

I Followed your solution but i didn't worked for me. If you have any workaround for this then please tell me because i'm kind of Stuck on this error. Thanks

**Comment by kumbhar-ketan** [comment]
Should i Open new Issue for this one ??
