### ISSUE TITLE
Can i hide rightIcon in ListItem ?

### ISSUE THREAD

**Issue by motogod** [react-native-training/react-native-elements#1129]
Here is my ListItem
```
              <ListItem
                onPress={this.changeExpanded.bind(this)}
                key={i}
                title={item.title}
                leftIcon={{name: item.icon}}
                rightIcon={{name: null}}
              />
```
I find that if i remove leftIcon it will disappear, but i remove rightIcon it still shows default icon in my ListItem,  i can't find the setting about hide rifhtIcon.

I just try `rightIcon={{name: null}} `or r`ightIcon={{name: 'none'}}` they are no working?

Is there a setting about it or not ?  Thanks in advance.

**Comment by xavier-villelegier** [comment]
@motogod 
If you're using `v0.19.X`, use `hideChevron`
If your're using `v1.0.0-beta4`, just don't add the `chevron` props

**Comment by motogod** [comment]
Yes i'm using v0.19.x and hideChevron is working. Thanks for your help.

**Comment by mahgolfa** [comment]
add this prop : `hideChevron`
