### ISSUE TITLE
"RawText "" must be wrapped in an explicit <Text> component." for errorMessage props of Input

### ISSUE THREAD

**Issue by hpelitebook745G2** [react-native-training/react-native-elements#1136]
### Description

1. Assigned variable to errorMessage props for `Input` component.
2. Initially this variable is empty.
3. Upon rendering it gives `RawText "" must be wrapped in an explicit <Text> component.` error.

Current version is `"react-native-elements": "beta"`, `1.0.0-beta4:` specifically.

### Reproduction Steps and Sample Code

This is my local state: `this.state = {
	  emailError: {
		isError: false,
		message: '',
	  },
	};`

While this is the UI part:
`	<Input
	  errorStyle={{ color: 'red' }}
	  errorMessage={this.state.emailError.message}
	  shake={this.state.emailError.isError}
	/>`

On runtime, `this.state.emailError.errorMessage` will be supplied with a string. However upon initial rendering, I already got the error. How am I supposed to assign a variable to the errorMessage if I get this kind of error?

Any help would be accepted.

Thanks.

**Comment by xavier-villelegier** [comment]
@hpelitebook745G2 Not sure if this comes from the error message. Can you add more context to your use case ? [Here is](https://snack.expo.io/HJMEo5n3z) a simple example of how to use it, it works fine on Snack

**Comment by vsai** [comment]
@xavier-villelegier I see the same error message as above when the value passed into `errorMessage` is an empty string. Not sure if that has something to do with it.

As soon as I modify the initial state of the component, containing the errorMessage, to non-empty, the component renders fine.

**Comment by xavier-villelegier** [comment]
@vsai Do you have this error only on Android ?

**Comment by hpelitebook745G2** [comment]
I fixed this by using `null` value instead of having empty string. So my condition would be:
`
	errorMessage={ this.state.emailError.isError ? this.state.emailError.message : null }
`

**Comment by vsai** [comment]
@xavier-villelegier I had this error on the iOS simulator.

I fixed it by using null instead of empty string too.
But just pointing out why I was seeing the same error too.

**Comment by xavier-villelegier** [comment]
@vsai @hpelitebook745G2 
Okay guys, after investigating a bit, you're right, this is a bug.

Here is the source code:
https://github.com/react-native-training/react-native-elements/blob/d4da856a7f105c814cc162e507b48c49399cabef/src/input/Input.js#L109-L113

By doing this, when `errorMessage=""`, `errorMessage && …` returns `""`, and it's trying to render an empty string outside a `Text` component.

For anyone who wants to tackle this, you just need to do `!!errorMessage &&…` to avoid returning an empty string. Same goes for the `label` props
https://github.com/react-native-training/react-native-elements/blob/d4da856a7f105c814cc162e507b48c49399cabef/src/input/Input.js#L78

**Comment by iRoachie** [comment]
Fixed in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
