### ISSUE TITLE
Change font and text color on typing with SearchBar

### ISSUE THREAD

**Issue by loic-lopez** [react-native-training/react-native-elements#1137]
### Description

Hello, is it possible to change the font and text color on typing with the SearchBar component?
` "react-native-elements": "^0.19.0"`

### Example:
The default color of the text that the user writed is grey,
but in my case i need to have this text in white.

Thanks for reply .

**Comment by xavier-villelegier** [comment]
@loic-lopez [Here is](https://snack.expo.io/HkJ0Mi3hM) a simple example.
The idea is to use `onBlur` and `onFocus` to change between the two styles.

**Comment by loic-lopez** [comment]
Thanks for reply @xavier-villelegier,

Your example do what i needed.
 😃
