### ISSUE TITLE
ListItem renders unwanted vertical white-space that I cannot control

### ISSUE THREAD

**Issue by lsiden** [react-native-training/react-native-elements#1138]
On v1.0.0-beta4, ListItem renders vertical padding above and below its contents that I cannot get rid of.  When I examine this on Android with the inspector, it does not show any value for padding, but there is nevertheless white-space above and below the text that I cannot adjust.  This was not the case with v0.19.x.

**Comment by xavier-villelegier** [comment]
@lsiden Did you try `containerStyle={{ padding: 0 }}` ?

**Comment by xavier-villelegier** [comment]
I think it's a duplicate of #1119
