### ISSUE TITLE
Placeholder text color inside Input

### ISSUE THREAD

**Issue by Clafouti** [react-native-training/react-native-elements#1148]
Using v1.0.0-beta4

I'm trying to change the color of the placeholder text inside an Input component (I'm using a dark background). Is there a prop to do that ? I tried using `inputContainerStyle` without success.

**Comment by iRoachie** [comment]
The color of the placeholder is control by a prop not style. You're looking for [`placeholderTextColor`](https://facebook.github.io/react-native/docs/textinput.html#placeholdertextcolor)

**Comment by Clafouti** [comment]
I can't believe I missed that one! I was on that page but used it inside a StyleSheet inside inputContainerStyle.

Thanks a lot!

**Comment by anastely** [comment]
if I need to add some padding to placeholder?

**Comment by iRoachie** [comment]
@anastely The placeholder uses the same styles from the original Input. So you can add padding to `inputStyle`
