### ISSUE TITLE
SearchBar unwanted top and bottom gray lines

### ISSUE THREAD

**Issue by rk85097** [react-native-training/react-native-elements#1150]
### Description

I added a search bar into my app, gave it a container background color, yet, I still get top and bottom gray line. If I am not using the lightTheme those lines becomes black. Any way to remove them / change their color?

`<SearchBar
          round
          lightTheme
          containerStyle = {{width: 230, backgroundColor:'transparent'}}
          inputStyle     = {{backgroundColor:'white'}}
 />`

**See screenshot:**
<img width="161" alt="search" src="https://user-images.githubusercontent.com/5455346/39393847-d2969cc0-4ad2-11e8-9a29-754667d2c9e5.png">

As far as react-native-elements version this is what I have in my package json:

> "react-native-elements": "^0.19.0"

**Comment by xavier-villelegier** [comment]
Hey @rk85097 👋  The SearchBar has borders by default, but you can override it.
This should work:

```jsx
<SearchBar
  round
  lightTheme
  containerStyle={{
    width: 230,
    backgroundColor:'transparent',
    borderTopWidth: 0,
    borderBottomWidth: 0,
  }}
  inputStyle = {{backgroundColor:'white'}}
/>
```

**Comment by jalalat** [comment]
Hi @xavier-villelegier is it possible to remove/hide or blend the outer Container with white background. I tried following:

 containerStyle={{
    width: 230,
    backgroundColor:'white',
    borderTopWidth: 0,
    borderBottomWidth: 0,
  }}

still the greyness would not go away. If i change the backgroundColor to something else like Red or yellow nothing happens. 

for inputStyle backgroundColor is working fine. I am on 1.0.0-beta5

**Comment by xavier-villelegier** [comment]
@jalalat Which `platform` props are you applying to the `SearchBar` ? `ios`, `android` or nothing ?

**Comment by jalalat** [comment]
nothing. I tested it on android.

**Comment by xavier-villelegier** [comment]
@jalalat Actually there is a bug if you specified `lightTheme`, it overrides the `containerStyle` you set.

https://github.com/react-native-training/react-native-elements/blob/2f54bb14edea32d438873e6a5480a294319a6658/src/searchbar/SearchBar-default.js#L79-L84

`containerStyle` should be after everything. Feel free to open a PR to tackle this

**Comment by jalalat** [comment]
I just work around this issue by using darkTheme:

containerStyle={{ width: '100%', backgroundColor: "white", borderTopWidth: 0, borderBottomWidth: 0, }}
inputContainerStyle={{ backgroundColor: 'white'}}

**Comment by iRoachie** [comment]
@xavier-villelegier made https://github.com/react-native-training/react-native-elements/issues/1150#issuecomment-410670717 to track this.
