### ISSUE TITLE
ListItem - cannot use TouchableHighlight as a component

### ISSUE THREAD

**Issue by nonotest** [react-native-training/react-native-elements#1153]
### Description

1. Tried to use TouchableHighlight as a component
2. It should work
3. The test for the divider component generates a React element and we get the 
"expected to receive a single react element child" redbox

latest beta

### Reproduction Steps and Sample Code

```
 <ListItem
        component={TouchableHighlight}
/>
```
### Solution
Shouldn't the divider be purely handled via styles here? 
Possible solutions:
* Remove the divider and handle it with pure styling
* Use another wrapper at the top..

Please consider using TouchableHighlight as a default for this as its not uncommon to need underlineColor when using 'List Items'?

Thanks!

**Comment by martinezguillaume** [comment]
Yep, I think the divider should be just handled by borderBottom style you‘re right ! And for the Component to TouchableHighlight, I think you‘re right too ! Thoughts @xavier?

**Comment by xavier-villelegier** [comment]
@martinezguillaume Yea I think too. The `Divider` component might be a bit overkill here

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
