### ISSUE TITLE
Simply get FormInput's text value

### ISSUE THREAD

**Issue by elyran** [react-native-training/react-native-elements#1154]
Hi,

How do I get a FormInput's text value?
I'd expect that to be straightforward, but found myself trying to figure this out by looking at the source code, without success!

https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormInput.js

I see on the above link, in the source code, that `textInputRef` is deprecated.

Setting a 'ref' has failed:
`<FormInput ref='emailInput' />`

Found nothing in the docs, nor any example.

So, how can I just assign a 'ref' to a FormInput and take its value later? I'd like to avoid the overhead of callbacks etc' ('onChange' etc').

**Comment by elyran** [comment]
I've noticed that the NPM version, the default I've got is v0.19.1.
This, while the docs discuss v1.0.0-beta4.

That's a source of confusion, by the way. 'FormInput' is gone, while 'Overlay' is introduced.

I think someone should make things clear. This kind of problems cost hours of dev. time. That said with lots of respect for making the project happen, so please don't get me wrong - thanks for RNE :)

**Comment by elyran** [comment]
I'm sorry for the messages but I'm trying to figure out how to work with RNE v1+.

The docs at
https://react-native-training.github.io/react-native-elements/docs/text.html
don't discuss about 'FormInput' at all..

What's going on? Is someone working on this project?

**Comment by miadian** [comment]
you should use `onChangeText={(text) => this.setState({my_input_state: text})}` in your FormInput,
then use this.state.my_input_state to access your input

**Comment by iRoachie** [comment]
Closing as inactive
