### ISSUE TITLE
custom cursor color for searchbar

### ISSUE THREAD

**Issue by sabiya115** [react-native-training/react-native-elements#1160]
### Description

Not able to change cursor color from black to white.
Using container style as: 
`containerStyle={{ backgroundColor: 'transparent', borderBottomColor: 'transparent', borderTopColor: 'transparent'}}`

and input style as: 
`inputStyle={{ backgroundColor: 'transparent', color: 'white'}}`

Currently my search bar is all perfect except the cursor color.

Using version 0.19.0

![screen shot 2018-05-03 at 6 00 29 pm](https://user-images.githubusercontent.com/23252768/39576620-60b3c456-4efc-11e8-881d-2fc09352dce1.png)

### Solution

Can you suggest a possible fix that would address this issue?

**Comment by iRoachie** [comment]
Any props from the native `TextInput` you can pass to the `SearchBar`. The prop you're looking for is [`selectionColor`](https://facebook.github.io/react-native/docs/textinput.html#selectioncolor). Here's an example https://snack.expo.io/H1zlSK_az

**Comment by sabiya115** [comment]
@iRoachie It worked, thanks, dude 👍
