### ISSUE TITLE
[Android] Button RGBA transparency

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#1161]
### Description

1. Explain what you did

Implement a backgroundColor using Transparency (RGBA)

2. What you expected to happen

Have the same result on iOS & Android

3. What actually happens

It does work on iOS (TouchableOpacity) but doesn't work well on Android (TouchableNativeFeedback).
You can see the opacity difference on the border of the Button

`react-native-elements": "^1.0.0-beta4"`

### Reproduction Steps and Sample Code

```
<Button
  title="BUTTON"
  buttonStyle={{
      backgroundColor: "rgba(255, 255, 255, 0.3)"
  }}
/>
```

Would it be possible to force Android to use `TouchableOpacity` instead of `TouchableNativeFeedback` ?

**Comment by xavier-villelegier** [comment]
@LouisJS You have the [`TouchableComponent` props](https://react-native-training.github.io/react-native-elements/docs/button.html#touchablecomponent) 👍

**Comment by xavier-villelegier** [comment]
Closing this as `TouchableComponent` allows you to use `TouchableOpacity`. Feel free to reopen it if not.
