### ISSUE TITLE
SearchBar, hide cancel button when onBlur is called

### ISSUE THREAD

**Issue by Bonobomagno** [react-native-training/react-native-elements#1162]
If i press the arrow (back icon), the cancel button (the X/cancel) don't hide himself.
How to hide it?

**Comment by xavier-villelegier** [comment]
Are you talking about the clear icon ?

**Comment by xavier-villelegier** [comment]
@Bonobomagno Here is a simple example

```jsx
export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      focus: false,
    }
  }
  
  render() {
    return (
      <View style={styles.container}>
        <SearchBar
          onFocus={() => this.setState({ focus: true })}
          onBlur={() => this.setState({ focus: false })}
          clearIcon={this.state.focus}
        />
      </View>
    );
  }
}
```

Running on [on Snack](https://snack.expo.io/HJ8v-ctTM)

**Comment by xavier-villelegier** [comment]
Closing this as `1.0.0-beta5` is out and [the SearchBar docs](https://react-native-training.github.io/react-native-elements/docs/searchbar.html#props) were updated
