### ISSUE TITLE
CI error: opencollective: Permission denied

### ISSUE THREAD

**Issue by danactive** [react-native-training/react-native-elements#1163]
### Description

1. Explain what you did
My project is using *react-native-elements* as a dependency. Every time I make a change to my project my Continuous Integration service executes unit test. Before the unit test I have an install build step that runs `npm install` inside a Docker container.
2. What you expected to happen
All my project dependencies should install successfully without error.
3. What actually happens
This *react-native-elements* module fails occasionally and my build breaks. With this error

```
> native-base@2.3.10 postinstall /home/circleci/project/node_modules/native-base
> node addEjectScript.js

┌────────────────────────────────────────────────────────────────────────────────────────────┐
│ NativeBase 2.0 has been succesfully installed!                                             │
│ Run `node node_modules/native-base/ejectTheme.js` to copy over theme config and variables. │
│ Head over to the docs for detailed information on how to make changes to the theme.        │
└────────────────────────────────────────────────────────────────────────────────────────────┘

> react-native-elements@0.19.0 postinstall /home/circleci/project/node_modules/react-native-elements
> opencollective postinstall

sh: 1: opencollective: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! react-native-elements@0.19.0 postinstall: `opencollective postinstall`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the react-native-elements@0.19.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2018-05-03T01_08_44_889Z-debug.log
Exited with code 126
```

Also please include the version of `react-native-elements` that you are using.
Latest v0.19.1

### Question
What permissions are needed to execute the postinstall script? This install step is running inside Docker.

**Comment by danactive** [comment]
@xavier-villelegier I'm not currently able to put much thought into this issue. You have a valid question as you are trying to determine the severity of this issue. Do you have any ideas on how to restrict permission and then execute my unit tests or start my app?

**Comment by xavier-villelegier** [comment]
@danactive It's quite hard to reproduce on our side as it depends a lot on your environment 😕 I don't think it has any impact on your app as it is a "**post** install", but if it does, we'll add a env variable to disable this post install script. By the way, using `yarn` the opencollective post install script is not run

**Comment by xavier-villelegier** [comment]
Closing this, feel free to give some feedback if you find that it has an impact on your app
