### ISSUE TITLE
FormInput sizing issue

### ISSUE THREAD

**Issue by rrajasek92** [react-native-training/react-native-elements#1168]
I'm implementing elements into a react native app but am unsure how to go about resizing the FormInput component. I see there's a containerStyle property but I'm not really sure what to input to resize it. On iOS the input line is far too wide for the screen.

```
<FormLabel>{item.type}</FormLabel>
<FormInput containerStyle={{???}} onChangeText={(text) => this.handleInput(item.key,text)}/>
```

**Comment by xavier-villelegier** [comment]
Hey @rrajasek92 👋 

For example, you can add `containerStyle={{width: '90%'}}` if you want your input to take 90% of the container width.

![image](https://user-images.githubusercontent.com/17592779/39674526-90f3d55e-514d-11e8-97b5-8f8a14c1fb71.png)

**Comment by rrajasek92** [comment]
I've realized the actual issue is the way the form is being rendered in iOS. It is draggable left and right and when entering information will shift entirely. Here's a gif: 
https://im5.ezgif.com/tmp/ezgif-5-f75629a9d4.gif

My code is as follows:

```
      <FlatList
          data={this.state.investments}
          renderItem={({item}) => this._renderItem(item)}
        />

```

```
_renderItem = (item) => {
    return (
      <View>
        <FormLabel>{item.type}</FormLabel>
        <FormInput containerStyle={{width: '80%'}} onChangeText={(text) => this.handleInput(item.key,text)}/>
      </View>
    );
  }
```

Thank you so much!

**Comment by iRoachie** [comment]
Image not found @rrajasek92, can you post it here?

**Comment by pstanton** [comment]
This is because the width of the input is actually based on the screen dimensions:

```

const { width } = Dimensions.get('window');

  input: {
    ...Platform.select({
      android: {
        minHeight: 46,
        width: width - 30,
      },
      ios: {
        minHeight: 36,
        width: width,
      },
    }),

```

this makes the FormInput component unusable in terms of flex layout.

**Comment by pstanton** [comment]
also, i notice this has had a re-write in the beta - i haven't tested but the source doesn't use `Dimensions.get('window')`

**Comment by xavier-villelegier** [comment]
The `Input` in v1.0.0-beta5 doesn't use screen dimensions, only percentage, feel free to test it 👍
