### ISSUE TITLE
Searchbar text is cutoff RNE beta 5

### ISSUE THREAD

**Issue by jstansbe** [react-native-training/react-native-elements#1176]
### Description

1. Added searchbar component
2. Expected input text to be displayed correctly and for cancel button to be offscreen (when keyboard is inactive)
3. The top of the input text is cut off (both placeholder text and text entered by user) and the cancel button should be hidden until the keyboard is brought up

```
     "react-native-elements": "^1.0.0-beta5",
    "react": "16.3.1",
    "react-native": "0.55.2",
```

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

```
            <View>
                <SearchBar
                    platform='ios'
                    onChangeText={() => console.log('onChangeText')}
                    onClear={() => console.log('onClear')}
                    placeholder='Type Here...'
                />
    </View>
```
![image](https://user-images.githubusercontent.com/1250522/39727865-760df1ae-5222-11e8-91b4-b90e6a9554cd.png)

**Comment by iRoachie** [comment]
I'm not able to replicate this error. Could you provide anymore information that could help clear this up? See example here https://snack.expo.io/ry6qYo0pG

**Comment by jstansbe** [comment]
One additional detail I noticed after I posted... the text inside the input is scrollable. So for example, if you look at the screenshot I posted... i can scroll the text all the way down so the top of the text is fine but the bottom gets cut off.  In order to rule out issues from other components/styles, I tested this at the app level:
```
export default class App extends React.Component {
    render() {
        return (
            <SearchBar
                onChangeText={() => console.log('onClear')}
                onClear={() => console.log('onClear')}
                placeholder='Type Here...'
            />
        );
    }
}

```

**Comment by xavier-villelegier** [comment]
@jstansbe To be honest the `platform="ios"` SearchBar hasn't been tested that much on Android because it was not the intended purpose, so you might have a weird behavior (for example the blue Button that appears a bit on the right).

I don't see your issue on the Snack @iRoachie did even on Android, maybe the font size is bigger on the Note 8 ? Do you have this issue on the same emulator as Snack (Nexus 5) ?

**Comment by jstansbe** [comment]
@xavier-villelegier using a nexus 5 emulator netted the same result -- the input text is cut off and scrollable. Also, i've tried taking away the platform and other properties to see if that helps but nothing seems to work.

package.json
```
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "1.0.0-beta5",
    "react-native-vector-icons": "^4.6.0"
  },
```
![image](https://user-images.githubusercontent.com/1250522/39825534-ff2b716a-537f-11e8-83f3-252b2eeea38a.png)

**Comment by jstansbe** [comment]
After looking into the SearchBar comp, I saw it uses react-native-elements <Input />. So when I used just that component I had the same issue (text cutoff / scrollable). So the issue is with <Input /> and not necessarily <SearchBar />

**Comment by iRoachie** [comment]
Hey guys, the `Input` component doesn't have a defined size, it's uses `flex` to get it's size from it's parent. By default the `containerStyle` in the react native fresh setup has an `alignItems: 'center'` so it squashes the Input by making it only take it the space it needs to display it's components.

**Comment by xavier-villelegier** [comment]
@creambyemute You need to remove `alignItems: 'center'` from your container style
Could you confirm that you also have this issue on a regular `Input` as @jstansbe said ?

**Comment by iRoachie** [comment]
Hey guys, the `Input` component doesn't have a defined size, it's uses `flex` to get it's size from it's parent. By default the `containerStyle` in the react native fresh setup has an `alignItems: 'center'` so it squashes the Input by making it only take it the space it needs to display it's components.

The quick fix is to remove the `alignItems: 'center'` from the Parent `View` style. Here' a visual example.
https://snack.expo.io/HJrdY3eCz

**Comment by jstansbe** [comment]
Hey all,

My code example doesn't have a wrapper view so there isn't a `alignItems: 'center'` being applied.
Any other suggestions are appreciated.

**Comment by iRoachie** [comment]
@jstansbe  Can you replicate your example in https://snack.expo.io/ ?

**Comment by jstansbe** [comment]
@iRoachie If you look at my earlier comments you can see i'm having an issue when just adding the searchbar to app.js. I can't duplicate this in expo though.

**Comment by xavier-villelegier** [comment]
@jstansbe As we can't reproduce this on our devices, would you mind copying the SearchBars files, importing these in your project instead of the `from 'react-native-elements` import and trying to tweak with the styles to find out what's causing this issue on your device ?

**Comment by jstansbe** [comment]
Solved!!

I was able to fix my issue by setting the `inputStyle={{height: '100%'}}` for an `<Input />` and using `inputStyle={{height: 75}}`  for `<SearchBar />` on the elements... no need to tweak the src files.

@xavier-villelegier  @iRoachie,  thanks you for the help and ideas!
