### ISSUE TITLE
Using Beta Version

### ISSUE THREAD

**Issue by aryasadeghy** [react-native-training/react-native-elements#1178]
### Description

Hello , our Team is working on  an app that using react native element . we want to release our app next month but we need some features like passing a component to card component title prop that exist in beta version , as it's not a stable version we are afraid of using it , so what is your recommendation about  beta version in this situation we have   .

**Comment by iRoachie** [comment]
Hey @aryasadeghy glad to hear you're using react-native-elements with your team, that super exciting! 

Our betas despite the name beta, are usually very stable, and to the quality that you might find in a stable release. The only catch is that we may revisit previously implemented components between betas as we see the opportunity to improve them. This happens with stable releases as well, but changes are bit more frequent in the betas. We give the same level of support and care to our betas that we give the stable version.

Jumping to the beta for one change in a component might be bit of a stretch, however keep in mind that the beta will become the stable version eventually. The sooner you transition to the beta, the easier it'll be for your app to transition to 1.0.0 when it goes live.

Hope this helps!

**Comment by aryasadeghy** [comment]
I really appreciate it . Good job. thanks for your answer . now i'm confidently  can move to beta version
