### ISSUE TITLE
Update to react-native 0.54 at least

### ISSUE THREAD

**Issue by lc3t35** [react-native-training/react-native-elements#1180]
dependencies : 
In order to match at least Expo sdk 26, would it be possible to update to react-native 0.54 instead of 0.52.2 ?
Thank you

**Comment by Gregjarvez** [comment]
will submit a PR for this 💪🏽

**Comment by iRoachie** [comment]
Available now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
