### ISSUE TITLE
Checkbox title is not always displayed as expected

### ISSUE THREAD

**Issue by lc3t35** [react-native-training/react-native-elements#1181]
### Description
Using react-native-elements 1.0.0-beta5, expo sdk26 (react-native 0.54)

1. Explain what you did
I'm using the same Checkbox in 2 contexts : one in a View
````
<CheckBox
            title={I18n.t('account_accept_cguv')}
            checkedTitle={I18n.t('account_accepted_cguv')}
            textStyle={styles.infotext}
            containerStyle={{ marginLeft: 0, marginRight: 0, borderWidth: 0, backgroundColor: 'white' }}
            checked={this.state.checked}
            size={30}
            checkedColor={'#7363DD'}
            onIconPress={checked => this.setState({ modalVisible: true })}
            onPress={checked => this.setState({ modalVisible: true })}
          />
````
displays as : 
![capture d ecran 2018-05-08 a 15 14 47](https://user-images.githubusercontent.com/921372/39759532-31dc1d38-52d3-11e8-933a-39d40ef0c68c.png)

the other in a [Modal](https://github.com/react-native-community/react-native-modal) View 
````
<CheckBox
                title={I18n.t('account_accept_cguv')}
                checkedTitle={I18n.t('account_accepted_cguv')}
                textStyle={styles.infotext}
                containerStyle={{ marginLeft: 10, marginRight: 20, padding: 0, borderWidth: 0, backgroundColor: 'white'}}
                checked={this.state.checked}
                size={30}
                checkedColor={'#7363DD'}
                onIconPress={checked => this.setState({ checked: !this.state.checked, modalVisible: false })}
                onPress={checked => this.setState({ checked: !this.state.checked, modalVisible: false })}
              />
````
displays as
![capture d ecran 2018-05-08 a 15 14 37](https://user-images.githubusercontent.com/921372/39759550-3d2b553c-52d3-11e8-848c-c2873d39d942.png)

2. What you expected to happen

The text should be on 2 lines in both case

3. What actually happens

First one is incorrect (all the text is not displayed on 2 lines), second displays correctly on 2 lines.

**Comment by lc3t35** [comment]
@iRoachie flex:1  it's a test I've made among hundreds including modifiying CheckBox component to find out why this happens -> copy/paste error -> I've removed the flex:1 from my text above, same behaviour of course.

**Comment by iRoachie** [comment]
There's no inherit reason that 2 components should display differently in two instances once passed the same parameters. Check the styling on parent View's, if they're the same. Would love if you could recreate this on https://snack.expo.io

**Comment by xavier-villelegier** [comment]
On which device did you test ? Do you have this issue on iOS/Android/both ?
