### ISSUE TITLE
Add some tests

### ISSUE THREAD

**Issue by xavier-villelegier** [react-native-training/react-native-elements#1186]
Some things we need to add in the tests:

* Test for `onClear` on SearchBars
* _Add others here_

**Comment by iRoachie** [comment]
What's the test for this look like? Testing if `onClear` we pass in get's called?

**Comment by iRoachie** [comment]
Ahh I see. Alright

**Comment by iRoachie** [comment]
Is it for all the SearchBars that need this test?
