### ISSUE TITLE
Remove the arrow icon at the right side of a ListItem

### ISSUE THREAD

**Issue by moar55** [react-native-training/react-native-elements#1188]
Hello,
I want to remove the right icon in a `ListItem` but I am not sure how this can be done. Any help would be  appreciated.

**Comment by moar55** [comment]
using the solution here https://github.com/react-native-training/react-native-elements/issues/165, I modified the `fontSize` attribute to 0 but I am not sure if this is the best way to do it.

**Comment by xavier-villelegier** [comment]
@moar55 If you're using `v0.19.x` use `hideChevron`, check out [the docs here](https://react-native-training.github.io/react-native-elements/docs/0.19.0/lists.html#hidechevron)

**Comment by moar55** [comment]
That's much cleaner. 
It works, thx!

**Comment by mujahid** [comment]
> @moar55 If you're using `v0.19.x` use `hideChevron`, check out [the docs here](https://react-native-training.github.io/react-native-elements/docs/0.19.0/lists.html#hidechevron)

@xavier-villelegier getting page not found for the doc link.

**Comment by xavier-villelegier** [comment]
@mujahid Yes we changed our documentation, [here is](https://react-native-training.github.io/react-native-elements/docs/0.19.1/lists.html#hidechevron) the new link

**Comment by iRoachie** [comment]
@mujahid https://react-native-training.github.io/react-native-elements/docs/0.19.1/lists.html#hidechevron

**Comment by nazio11** [comment]
<ListItem.Accordion  noIcon={true ou false} />
