### ISSUE TITLE
Ability to customize cancelButton in Searchbar

### ISSUE THREAD

**Issue by codler** [react-native-training/react-native-elements#1194]
Using react-native-elements v1.0.0-beta5.

This doesn't work.
<SearchBar cancelButtonProps={{fontFamily: 'Somthing'}} />

Suggestion is to use a TouchableOpacity instead of Button

**Comment by iRoachie** [comment]
There's no way to do this currently. We use the `<Button />` component from react-native, and it doesn't support customizing the fontFamily or style. See props here https://facebook.github.io/react-native/docs/button.html#docsNav.

We should probably refractor this to use a styled Touchable instead cc @xavier-villelegier

**Comment by Cederman** [comment]
+1

**Comment by xavier-villelegier** [comment]
The goal of the platform specific SearchBars was to mimic exactly the platform look & feel and behaviour, that's why we used the Button from React Native, which is supposed to be the same as the iOS one. We'll change that by using the React Native Elements `Button` in beta6.
