### ISSUE TITLE
SearchBar Seems irresponsive to style props

### ISSUE THREAD

**Issue by andersonaddo** [react-native-training/react-native-elements#1195]
### Description

I set up `SearchBar` like so:
```
      <SearchBar
        round
        style = {{alignSelf: 'stretch', marginLeft: 30, marginRight: 30, minWidth: "100%"}}/>
```
The parent of this SearchBar has the following style:
```
const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```

I'm using version 1.0.0-beta2.

I expected the `alignSelf` prop to override the SearchBar's parent style and hence let the bar stretch, but it doesn't. The search bar instead stays very small and only expands when text is entered into it.
It only stretches when I remove the parent's `alignItems` style prop. Even then, the `SearchBar` doesn't respond to explicitly set width and margin props.

### Reproduction Steps and Sample Code

[I've made a Snack of this issue](https://snack.expo.io/rkGVdKDCf) for you guys to understand. Once you get to it, remove the parent view's `alignItems` prop and see how the SearchBars behave. Notice how the second SearchBar doesn't respond to the values set in it's style prop.

### Solution

Does anyone have a solution to this? I want to keep the styles in my parent view and still be able to have a `SearchBar` that can stretch and be able to respond to margin restrictions. If anyone has an idea, I wouldn't mind working on a PR.

Thanks!

**Comment by xavier-villelegier** [comment]
Please have a look at [the documentation](https://react-native-training.github.io/react-native-elements/docs/searchbar.html), you have `containerStyle`, `inputContainerStyle` and `inputStyle`.

You should also update to `v1.0.0-beta5`, as we completely refactored the SearchBars to be consistent

**Comment by andersonaddo** [comment]
Oh my bad, I assumed that SearchBars were styles normally like most components. Changing `style` to `containerStyle` indeed solved the problem.
Thanks.
