### ISSUE TITLE
Searchbar cuts off if margin/padding is applied to the View container.

### ISSUE THREAD

**Issue by sopdock** [react-native-training/react-native-elements#1198]
I have a View with a Searchbar inside:
```
 <View style={styles.container}>
            <View style={styles.searchView}>
                    <SearchBar
                        platform="android"
                        placeholder='Search123'
                    />
            </View>
</View>
```

This is the styles:

```
  container: {
    flex: 1,
    flexDirection: 'column',
  },  


  searchView: {
    height: 150,
    backgroundColor: 'blue',
    justifyContent: 'space-evenly',
    margin: 10,
  },
```

[Screenshot](https://imgur.com/a/xq9QFOH)

You can see that the 'X' cancel button on the right is cut off.

My package.json:
```
    "react-native": "0.55.4",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-vector-icons": "^4.6.0",
```

**Comment by xavier-villelegier** [comment]
@sopdock Yea cause the SearchBar is supposed to be full width. What if you add `inputContainerStyle={{ width: '100%' }}` ?

**Comment by sopdock** [comment]
@xavier-villelegier I tried adding `width: '100%' to `searchView` and then to `container`. It didn't solve the issue unfortunately.

**Comment by xavier-villelegier** [comment]
I meant something like:

```jsx
<SearchBar
  platform="android"
  placeholder='Search123'
  inputContainerStyle={{ width: '100%' }}
/>
```

**Comment by sopdock** [comment]
@xavier-villelegier Ah, thanks. I  misunderstood; still new to react-native stuff.

I added that in, and it does make the cancel button appear within the view now. But I have `margin: 10` in the View; why does the SearchBar still stretch all the way to the left and right? I wanted some space on the sides.

[Screenshot](https://imgur.com/a/9T0ZUBr)

**Comment by sopdock** [comment]
Actually, the margin is working as intended. Nevermind! Thanks again!
