### ISSUE TITLE
Using underlineColorAndroid with input

### ISSUE THREAD

**Issue by mathb67** [react-native-training/react-native-elements#1200]
Hi !
I need to set underlineColorAndroid to another color than transparent but it doesn't work... Did i miss something or is that an issue ?

https://github.com/react-native-training/react-native-elements/blob/d4da856a7f105c814cc162e507b48c49399cabef/src/input/Input.js#L100

Thanks !

**Comment by iRoachie** [comment]
You're correct! Can you make a PR that moves the `underlineColorAndroid="transparent"` line above `{...attributes}`?

**Comment by mathb67** [comment]
Done !
Thank you.

**Comment by jstansbe** [comment]
Does this mean beta-6 will have underlineColorAndroid="transparent" working? It looks like beta-5 has this line of code but does not work.

**Comment by iRoachie** [comment]
No-one hasn't made the fix as yet @jstansbe. You're welcomed to implement it.

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/be51a98e0c0465a9ed34aa9001336a2f70068022. Will be available next release

**Comment by ricardo-cf** [comment]
To hide it i found the following solution:

inputContainerStyle={{
     borderBottomColor: 'rgba(255, 255, 255, 0)',
}}

**Comment by iRoachie** [comment]
Available now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!

**Comment by lefrankleal** [comment]
> To hide it i found the following solution:
> 
> inputContainerStyle={{
> borderBottomColor: 'rgba(255, 255, 255, 0)',
> }}

Work for me, actually cant find any other way to make it.
