### ISSUE TITLE
Icon won't display in button. Posted solutions not working. (Is there an old version of the docs available?)

### ISSUE THREAD

**Issue by Etregoning** [react-native-training/react-native-elements#1205]
### Description

So this app I'm working on has been in development since last year, and it's so heavily reliant on RNE, that changing the version would be more trouble than it's worth... However, the docs only provide support for the most recent version.

1. Explain what you did
**Trying to use an icon in a button**
2. What you expected to happen
**The icon would show up**
3. What actually happens
**The icon does not show up**

Also please include the version of `react-native-elements` that you are using.
**0.17.0**
### Reproduction Steps and Sample Code

**Button Code**
```
<Button 
    buttonStyle={ styles.backButton }
    icon={{ name:'navigate-before', color:'white', size:20 }}
    onPress={() => {
        navigate('Login');
    }}
/>
```

**Button styles**
```
backButton: {
    width: 40,
    height: 40,
    backgroundColor: 'forestgreen',
    borderColor: 'white',
    borderWidth: 2,
    borderRadius: 25
},
```

### Solution

Can you suggest a possible fix that would address this issue? 
**Releasing an older version of the docs for those of us who can't upgrade versions due to the amount of restyling work it would require. The other solutions posted for this problem have not helped me**

**Comment by iRoachie** [comment]
The beauty of Git my friend is that we have all the source code right here! Here's the button doc from 0.17. https://github.com/react-native-training/react-native-elements/blob/v0.17.0/docs/API/buttons.md

**Comment by Etregoning** [comment]
Thanks! I still can't seem to figure out why it's not working though. The logo worked just fine as it's own component, but when I tried to use it inside of a button it's not showing up. I wanted the button because I wanted a border which apparently isn't possible on an icon itself. Is there possibly a better solution for making a simple clickable icon with a border? 

Thanks!

**Comment by xavier-villelegier** [comment]
@Etregoning You can use the `Icon` component which can take an `onPress` props

Also feel free to update to `0.19.1`

**Comment by Etregoning** [comment]
@xavier-villelegier I tried to use an Icon by itself, but it would not let me set a border on the icon. I googled my issue and I saw suggestions for using a button instead and setting a border. I want to make a circular back button sorta like the < character, and a close button for modals, same sorta thing but with an x....I guess I could just use the < and X as text for the button, to save myself the headache, but I thought there might be a more elegant solution. I may just try using local vector icons too, but I was trying to save myself the extra work -- that's the point of this library right? :P 

Also, I switched to 0.19.0 and it still seemed like a lot of my ui was all messed afterwards. I'm working full stack on the project until next month, but then I can go back to dedicated front end and I'd be glad to upgrade and fix the styles. Just no time to do that now!

**Comment by xavier-villelegier** [comment]
@Etregoning Using an `Icon` should do the job then ? You can have a border, an onPress, an icon… Everything you want 😛 

**Code**
```jsx
<Icon
  component={TouchableOpacity}
  raised
  type="entypo"
  name="chevron-left"
  color="white"
  containerStyle={{ backgroundColor: '#517fa4' }}
  onPress={() => console.log('Pressed !')}
/>
```

**Result**
![image](https://user-images.githubusercontent.com/17592779/40231288-e030a754-5a9a-11e8-8da5-488e39b2039c.png)

[Snack example](https://snack.expo.io/H1Ao-Vn0f)

**Comment by Etregoning** [comment]
I see what you mean now. I suppose I was going about it the wrong way. Can you really use borders? I remember it complaining when I tried to set a border, and that's why I ended up using a button.

I just realized it was because I was trying to use the `style` property and not `containerStyle`

Thanks!
