### ISSUE TITLE
Making Button More Customizable on PricingCard

### ISSUE THREAD

**Issue by gabrieldefazio** [react-native-training/react-native-elements#1207]
### Description

1. Explain what you did

I added some simple customization options to the PricingCard Button

2. What you expected to happen

The Developer can change the style of the button title with the prop "titleStyle" and can change the icon size with the prop "iconSize"

3. What actually happens

The Developer cannot affect the icon size nor title style.

Also please include the version of `react-native-elements` that you are using.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by iRoachie** [comment]
Implemented in https://github.com/react-native-training/react-native-elements/commit/a521fc53ead7c33d1d2ac08fcaae36ec51df4df4
