### ISSUE TITLE
Refractor PricingCard to accept style objects

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1212]
Currently right now the only overrides the PricingCard accepts are fonts:

- buttonFont
- infoFont
- pricingFont
- titleFont

Instead the user should be able to pass in a style object for each of these

**Comment by Gregjarvez** [comment]
I will submit a PR for this one !!.

**Comment by iRoachie** [comment]
Go for it!

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/a521fc53ead7c33d1d2ac08fcaae36ec51df4df4. Will be available next release

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
