### ISSUE TITLE
bug(Overlay): window resize will cause error 

### ISSUE THREAD

**Issue by geminiyellow** [react-native-training/react-native-elements#1215]
i use `rne beta5` with `react-native-web`.

**Explain what you did**
**Describe the bug**
![overlay](https://user-images.githubusercontent.com/929878/40292146-7417ab64-5d04-11e8-932f-fc54d88e53a6.gif)

**Expected behaviour**

background mask should update when window resize

**Comment by NickMckloski** [comment]
This is also happening on mobile devices when rotating your phone.

**Comment by iRoachie** [comment]
@Nickersoft Are you referring to react-native or react-native-web?

**Comment by NickMckloski** [comment]
@iRoachie react-native

**Comment by xavier-villelegier** [comment]
If anyone wants to tackle this, we're using screen width and height in https://github.com/react-native-training/react-native-elements/blob/master/src/overlay/Overlay.js, we should use percentages
