### ISSUE TITLE
Updating version

### ISSUE THREAD

**Issue by ezekel** [react-native-training/react-native-elements#1217]
Hi I need some help please How can I update the version of react-native-elements, I have this in my package.json
"react-native-elements": "^0.19.1",

But in your site you release the 1.0.0 ?

How can I make my version to your latest release ?

Thank you in advance

**Comment by iRoachie** [comment]
Hey @ezekel the `1.0.0` isn't officially released as yet. What we have currently are betas that added features incrementally. We're at `beta5` right now. The `1.0.0` should be released officially next month but you can use the betas right now. 

To update to the beta, run:
```bash
npm install --save react-native-elements@beta
```
Be sure to check the release notes to see what changed in each beta https://github.com/react-native-training/react-native-elements/releases

**Comment by ezekel** [comment]
@iRoachie ,

Thank you for the quick reply...can I do yarn add --save react-native-elements@beta , because if I use npm my project will be messed up.


Thank you in advance.

**Comment by iRoachie** [comment]
Yep that works as well!

**Comment by ezekel** [comment]
@iRoachie 

Ok thank you so much
