### ISSUE TITLE
React-Native-Elements (Header) for iPhone X.

### ISSUE THREAD

**Issue by nzrin** [react-native-training/react-native-elements#1220]
It seems Header does not support for iPhone X yet. Tried using SafeViewArea, but it shows empty space on top of header.

Is there a way to make this works?

Thank you.

**Comment by lksilva** [comment]
Versions 0.50.1 >= React native team introduced SafeAreaView. Check if this don't resolve your problem https://medium.com/react-native-training/react-native-iphonex-92ff511282af

**Comment by nextriot** [comment]
+1

**Comment by martinezguillaume** [comment]
The [pr](https://github.com/react-native-training/react-native-elements/pull/1221) will be merged soon. It'll be available in beta 6, sorry for the delay !

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
