### ISSUE TITLE
Button Group Error

### ISSUE THREAD

**Issue by AbhishekDS-Userfacet** [react-native-training/react-native-elements#1224]
I am referring to official documentation for implementing ButtonGroup for React Native app. But the following error is being displayed when I open the app after compiling.

Even in snack, the same is not opening.

How do I use the ButtonGroup in reactnative apps?

**Error :**

**Invariant Violation: Element type is invalid: expected a string or a class/function but got undefined.**

**Comment by xavier-villelegier** [comment]
@AbhishekDS-Userfacet Can you post how you use the `ButtonGroup` ?

Here is a basic example

```jsx
import { ButtonGroup } from 'react-native-elements';
…
<ButtonGroup
  buttons={['here', 'is a', 'test']}
  selectedIndex={0}
/>
```

**Comment by AbhishekDS-Userfacet** [comment]
@xavier-villelegier I used the following way which is in the documentation.


```
constructorconstructor  (())  {{
     supersuper(())
     thisthis..state state ==  {{
    selectedIndex     selected : 2
  }
  this.updateIndex = this.updateIndex.bind(this)
}

updateIndex (selectedIndex) {
  this.setState({selectedIndex})
}

render () {
  const buttons = ['Hello', 'World', 'Buttons']
  const { selectedIndex } = this.state

  return (
    <ButtonGroup
      onPress={this.updateIndex}
      selectedIndex={selectedIndex}
      buttons={buttons}
      containerStyle={{height: 100}}
    />
  )
}
```

Documentation - https://react-native-training.github.io/react-native-elements/docs/button_group.html

**Comment by xavier-villelegier** [comment]
@AbhishekDS-Userfacet The docs example works fine, you can check this [on Snack](https://snack.expo.io/r1uPVZEkQ)

Result:
![image](https://user-images.githubusercontent.com/17592779/40476864-5e10f18e-5f45-11e8-9ab2-9e23fad6bfb3.png)

**Comment by AbhishekDS-Userfacet** [comment]
@xavier-villelegier Thanks for that man. Had imported from react-native instead of react-native-elements.

But in snack and in the screenshot, selected color is blue by default. For me in the phone it is showing white and also it is not accepting any color when given from [selectedBackgroundColor="rgba(27, 106, 158, 0.85)"]()

**Comment by xavier-villelegier** [comment]
@AbhishekDS-Userfacet Yea cause we're using `1.0.0-beta5`, you can install it by doing
```jsx
npm i -S react-native-elements@beta
```

**Comment by AbhishekDS-Userfacet** [comment]
@xavier-villelegier default color is blue which is as per the screenshot but can that be changed?
Used selectedBackgroudColor but it is not getting changed.

**Comment by xavier-villelegier** [comment]
@AbhishekDS-Userfacet Please have a look at [the docs](https://react-native-training.github.io/react-native-elements/docs/button_group.html#props). You need to use `selectedButtonStyle`

**Comment by AbhishekDS-Userfacet** [comment]
Thanks @xavier-villelegier
