### ISSUE TITLE
Flat View Rendering

### ISSUE THREAD

**Issue by Oraclesports** [react-native-training/react-native-elements#1225]
Hi all, this is regarding 'OnPress' function on my FlatView rendering of items.
I am not able to include 'OnPress function' on renderitem function for Scenario1 while i am able to do that for Scenario2. 

1)Can anyone explain this?
2)And how I can improve the code for Scenario 1 in order for OnPress function to work.

**Scenario 1**
> 
        renderItem({ item }) {
        return(
                     <Text > {item.name}</Text> -<<<< I like to know why it is not possible to place onPress function on my text here?
            )
        }
       
       render()

        {
  
         return (
               <View style={styles.row}>
                   <Text>
                       FlatList
                   </Text>    
                       <FlatList  
                           data={this.state.dataSource}
                           renderItem={this.renderItem} 
                         />
                   );
         }

However, Onpress function will work on rendered items if it was coded in this manner.
**Scenario 2**
> 
 
        GetFlatListItem (name) {
   
            Alert.alert(name);
           
            }

     render()

        {
  
         return (
               <View style={styles.row}>
                   <Text>
                       FlatList
                   </Text>    
                       <FlatList  
                             renderItem={({item}) => <Text onPress={this.GetFlatListItem.bind(this, item.name)} }> 
                             {item.name} </Text>}
                 />
             );
         }

**Comment by Oraclesports** [comment]
Hi thanks for your feedback. But I was able to do that on Scenario 2.

**Comment by iRoachie** [comment]
Sorry about that! I actually now just checked it https://facebook.github.io/react-native/docs/text.html#onpress.

Try trying to change your renderItem function to:

```jsx
 renderItem = ({ item }) =>  {
    return(
                 <Text > {item.name}</Text> -<<<< I like to know why it is not possible to place onPress function on my text here?
        )
    }
```

**Comment by Oraclesports** [comment]
Thank you Roachie. It is working now.

-Benedict
