### ISSUE TITLE
Events of onCancel and onClear are not fired

### ISSUE THREAD

**Issue by cowboybebopran** [react-native-training/react-native-elements#1226]
**Explain what you did**
Assign functions:
onClear={() => this.handleSearchClear()}
onCancel={() => this.handleSearchCancel()}

**Expected behaviour**
When press cancel button, the input should become empty. It should print "cancel".
When press clear button, the input should become empty. It should still focus on search bar. It should print "clear".

**Describe the bug**
When press cancel button, the input remains the same. Nothing print out.
When first press clear button, the input remains the same. It lost focus on search bar. Nothing print out.
When second press everything works. It prints "clear"

**To Reproduce**
Please note cancel will alert but won't clear text in expo. However, it won't alert on my iphone.

```bash
# Snack
https://snack.expo.io/rk2_Tp4yQ

# Steps
1. Click search bar
2. Input some text
3. Click cancel
4. See error
5. Click search bar
6. Click clear icon
7. See error
```
**Possible Solution**
No idea

**Screenshots**
Not applicable

**Your Environment (please complete the following information):**

| software | version |
| react-native-elements | 1.0.0-beta5 |
| react-native | 0.55.2 |
| npm or yarn | 5.10.0 |

**Comment by xavier-villelegier** [comment]
@cowboybebopran You are not using `1.0.0-beta5` on the snack you provided. With the good version, it works fine. [Check out this snack](https://snack.expo.io/BJDqMBS1X)

**Comment by cowboybebopran** [comment]
Checked. 
It works outside but not in FlatList.
I put it in ListHeaderComponent and did not work. Don't know why.

Thanks!
Ran

**Comment by xavier-villelegier** [comment]
@cowboybebopran Add `keyboardShouldPersistTaps="handled"` to your `FlatList` 😉

**Comment by cowboybebopran** [comment]
That works perfectly well. Thanks!
