### ISSUE TITLE
jest cannot import react-native-elements

### ISSUE THREAD

**Issue by geminiyellow** [react-native-training/react-native-elements#1227]
**Explain what you did**

i use
- react-native-web
- react-native-elements
- jest

and, i try to test a component who use react-native-elements by jest

**Expected behaviour**

test will pass

**Describe the bug**

```
 FAIL  src/components/TestLink/TestLink.spec.js
  ● Test suite failed to run

    /Users/dev/broadbill/node_modules/react-native-elements/src/index.js:2
    import Button from './buttons/Button';
           ^^^^^^
    
    SyntaxError: Unexpected identifier
      
      at new Script (vm.js:74:7)
      at Object.<anonymous> (src/components/TestLink/TestLink.js:2:26)

```

**To Reproduce**

- TestLink.js
```
import React from 'react';
import { Text } from 'react-native-elements';
import { isWeb } from '../../utils/common';
import ReactRouter from '../../utils/react-router';

const { Link } = ReactRouter;

const TestLink = ({ to, children, style, textStyle }) => {
  return (
    <Link to={to} style={isWeb ? {} : style} className={isWeb ? style : ''}>
      <Text style={textStyle}>{children}</Text>
    </Link>
  );
};

export default TestLink;
```

- TestLink.spec.js
```
...
  it('render properly - ' + Platform.OS, () => {
    const tree = renderer.create(
      <Router>
        <TestLink to={path} style={2} textStyle={3}>
          Test Link
        </TestLink>
      </Router>,
    );
    expect(tree.toJSON()).toMatchSnapshot();
  });
...
```

**Comment by pamontep** [comment]
I also got this error and still finding solution.

**Comment by spbisya** [comment]
+1, still finding.

**Comment by leugimmai** [comment]
@geminiyellow importing as so should help:   `import { Button } from 'react-native-elements';`

**Comment by xXZang3tsuXx** [comment]
I had the same issue 

So I removed 
`"transformIgnorePatterns": [
      "node_modules/(?!(react-native|react-native-vector-icons|react-native-config)/)"
  ]`
that was in my Jest configuration in `package.json`

That got rid of the above error, however prompted with some other errors in snapshot testing such as 

`react native Invariant Violation: Could not find "store" in either the context or props of "Connect"....`

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by shtefanilie** [comment]
Encountering same issue as soon as I added `react-native-elements`.
Did anyone find a way to fix this?

**Comment by huyenpham-agilityio** [comment]
same issue here. Did you fix it?

**Comment by geminiyellow** [comment]
hi @shtefanilie 

have no idea, nobody do reply and nobody fix, just inactive and close, 
so i use [react-native-paper](https://github.com/callstack/react-native-paper) instead of this.

**Comment by huyenpham-agilityio** [comment]
@geminiyellow I just try to use react-native-pager, but I get the error when try to test it
```node_modules/react-native-paper/src/index.js:3
    import * as Colors from './styles/colors';
           ^

    SyntaxError: Unexpected token *
```
Did you meet this issue?

**Comment by geminiyellow** [comment]
> Did you meet this issue?

yep

>  SyntaxError: Unexpected token *

maybe your babel config need some change.

and, if not work, you can create a issue in react-native-paper repo, 
or create a new issue in react-native-elements.

**Comment by ngduc** [comment]
I still see the same issues with latest libs:

```
Details:

    /Users/.../project/node_modules/react-native-elements/src/index.js:7
    import Button from './buttons/Button';
    ^^^^^^

    SyntaxError: Unexpected token import
```
Any workaround ? Thanks

**Comment by iRoachie** [comment]
you have to use babel-jest. React Native Elements ships JSX to npm

**Comment by canastro** [comment]
I'm having this issue while using ts-jest and react-native 0.61. Any tip on how to fix this on my configuration?

```js
module.exports = {
  preset: 'react-native',
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js',
    '^.+\\.tsx?$': 'ts-jest'
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|react-native-cookies|@sentry/react-native)/)'
  ],
  globals: {
    'ts-jest': {
      tsConfig: 'tsconfig.jest.json',
      diagnostics: false
    }
  },
  moduleFileExtensions: ['ts', 'tsx', 'js'],
  testRegex: '(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$'
};
```
