### ISSUE TITLE
How do we access JSON Objects that have spaces? 

### ISSUE THREAD

**Issue by Oraclesports** [react-native-training/react-native-elements#1228]
Similar to https://stackoverflow.com/questions/10311361/accessing-json-object-keys-having-spaces. However, I am asking inregards to reactnative.

Code looks like 
 > 
        renderItem = ({ item }) => {
                        
                    
                    return(
                             <Text onPress={this.GetFlatListItem.bind(this, item.email)} > {item.email}</Text>
                     
                    )
                }

How to replace '**email**' with '**My Email**'

**Comment by xavier-villelegier** [comment]
@Oraclesports This is not related to React Native Elements or React Native, this javascript.

You can do `item['My email']`
