### ISSUE TITLE
Parsing JSON Objects on REACT NATIVE

### ISSUE THREAD

**Issue by Oraclesports** [react-native-training/react-native-elements#1229]
Hello.
Are there any docs in regards to Parsing JSON OBJECTS?
I am trying to PARSE another Object within Object.
I am able to Parse item['email'] but am trying to **Parse ['street'] of Address.**

**JSON DATA**
<img width="413" alt="screen shot 2018-05-25 at 7 02 04 pm" src="https://user-images.githubusercontent.com/17598567/40541447-61f2eb68-604e-11e8-9bd4-81920a4d166f.png">

**REACT NATIVE**
>              
            renderItem = ({ item }) => {
                          return(
                         <Text onPress={this.GetFlatListItem.bind(this, item['email'])} > {item['email']}</Text>
                     
                                )
                            }

             render() {
                return (

            <FlatList  
                    data={this.state.dataSource}
                    ItemSeparatorComponent = {this.FlatListItemSeparator}
                    renderItem={this.renderItem}     
                    keyExtractor={(item, index) => index.toString()}
             
            />

**Comment by Oraclesports** [comment]
I apologise. I did not know that.

**Comment by bilalarab** [comment]
i can help you but i won't

**Comment by mrameera** [comment]
use this link https://www.npmjs.com/package/json-query
