### ISSUE TITLE
[Button] Width Fit to content

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#1230]
**Is your feature request related to a problem? Please Describe.**

I'm implementing a button to filter a List. The name of the button will change according to the selected filter ("In Progress", "Closed", "Awaiting Confirmation").

**Describe the solution you'd like**

I'd like that the Button would grow according to the content text length

**Describe alternatives you've considered**

I did implement a button such as 

```
<Button
    title={filter.title}
    titleStyle={style.buttonTitle}
    buttonStyle={style.buttonStyle}
    icon={ <FontAwesome name="caret-down" size={28} color={colors.white} /> }
    iconRight
    onPress={() => this.filter()}
    TouchableComponent={TouchableOpacity}
/>
```

```
buttonTitle: {
    fontSize: 16,
    letterSpacing: 2,
    color: colors.white
  },
buttonStyle: {
    width: 140,     //  <= I have to set width otherwise it takes whole length due to flex container)
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 20,
    elevation: 1
  }
```

Using `RNE "^1.0.0-beta5"`

**Comment by mcwissink** [comment]
This [StackOverflow answer](https://stackoverflow.com/a/49263706) seems to provide a temporary solution. If you just apply that style on the Button containerStyle or buttonStyle it works.

**Comment by joaozitopolo** [comment]
I was with the same problem, but I put the Button in a <View> and now it's rendering ok, without any extra style:
        <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }}>
            <View style={styles.checkout}>
                <Button title="Checkout " icon={{ name: "shopping-cart", type: "feather", color: '#fff' }} iconRight />
            </View>
        </View>
![screenshot from 2018-05-30 12-09-38](https://user-images.githubusercontent.com/4305828/40728921-9455af58-6401-11e8-89cc-0bc2dc698dfa.png)

**Comment by LouisJS** [comment]
Yes 👍

**Comment by xavier-villelegier** [comment]
Feel free to post the workaround here and suggest how we could improve this in next version.

**Comment by ggunti** [comment]
You can simply use containerStyle={{ flexDirection: 'row' }} property on Button
