### ISSUE TITLE
[Input] Direct Manipulation

### ISSUE THREAD

**Issue by mcwissink** [react-native-training/react-native-elements#1232]
**Is your feature request related to a problem? Please Describe.**
There seems to be no way to call setNativeProps on the TextInput wrapped by the Input element.
It would be nice to be able to manipulate the actual text displayed by Input

**Describe the solution you'd like**
A setNativeProps prop on Input that forwards function onto the TextInput child.

**Describe alternatives you've considered**
Using the react-native TextInput and styling it similar to the other Input elements on the page, a poor solution.

**Additional context**
This would be useful for [clearing](https://facebook.github.io/react-native/docs/direct-manipulation.html) Input, or in my specific case, using a formatter for phone number input

**Comment by iRoachie** [comment]
Hey @mcwissink while you can call actually call the `clear` method on the input it'll clear the text value. Here's an example https://snack.expo.io/rkFRK2Pk7.

I do however understand that some persons may want to access the TextInput directly, so we could add this as a method on the Input

**Comment by iRoachie** [comment]
Don't think we are going forward this with this at this time.
