### ISSUE TITLE
Sperator Inset of ListItem (add dividerStyle prop)

### ISSUE THREAD

**Issue by PMExtra** [react-native-training/react-native-elements#1234]
Please add `topDividerStyle` and `bottomDividerStyle` props to ListItem.

It's hard for us to implement `Sperator Inset` effect without them.

**Comment by iRoachie** [comment]
@martinezguillaume You think you could add this in to your PR?

**Comment by martinezguillaume** [comment]
@Roachie , with the pr, the divider is just container styling (borderColor & borderWidth). If you want different color or width, just override them in the container style

**Comment by iRoachie** [comment]
Implemented in https://github.com/react-native-training/react-native-elements/pull/1233.
