### ISSUE TITLE
Button:loadingRight not showing spinner

### ISSUE THREAD

**Issue by AlvaDamian** [react-native-training/react-native-elements#1235]
**Explain what you did**
Add a button with the prop **loadingRight** set on **true**.

**Expected behaviour**
A spinner has to appear on the right of the button text.

**Describe the bug**
The spinner will not appear. This is working on the left side of the button text using **loading** prop.

**To Reproduce**
[Expo example](https://snack.expo.io/ByYRYdYJ7)

```
import React, { Component } from 'react';
import { View } from 'react-native';

import { Button } from 'react-native-elements'; 

export default class App extends Component {
  render() {
    return (
      <View>
        
        <Button
          title='LOADING BUTTON'
          loading={true}
          onPress={() => {}}
        />
        
        <Button
          title='LOADING RIGHT BUTTON'
          loadingRight={true}
          onPress={() => {}}
        />
      </View>
    );
  }
}
```

**Possible Solution**
Not from my part.

**Screenshots**
Not applicable.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements  | 0.19.1 |
| react-native |  0.55.4 |
| npm |  6.0.1 |

**Comment by AlvaDamian** [comment]
Looking at the [code of Button](https://github.com/react-native-training/react-native-elements/blob/e0406c72f341b354f2861b85eb9a432863a50768/src/buttons/Button.js#L42) I could see that this property is not available.

Maybe the generated documentation is not updated.

[Button documentation source](https://github.com/react-native-training/react-native-elements/blob/master/docs/button.md)
[Button#loadingRight Documentation page](https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html#loadingright)

**Comment by iRoachie** [comment]
`loadingRight` is indeed in the source as you can see: https://github.com/react-native-training/react-native-elements/blob/v0.19.1/src/buttons/Button.js#L27. The link you posted was the source for `1.0.0-beta5`.

You have to use both the `loading` and the `loadingRight` props.
`loading` - describes the state
`loadingRight` - describes the position

Here's an example https://snack.expo.io/S1oIZiKyX

**Comment by AlvaDamian** [comment]
You're right, I misunderstood the documentation. It is working.

**Comment by mths0x5f** [comment]
Not possible to do this on version 1.1.0?

**Comment by iRoachie** [comment]
Not at the moment @mths0x5f
