### ISSUE TITLE
Must click an input field twice on Android

### ISSUE THREAD

**Issue by MeKyleH** [react-native-training/react-native-elements#1236]
**Explain what you did**
I have several FormInput fields in my project. When I test the app on an Android device and click one field it brings up the keyboard. When I try to click a Button or a different FormInput it closes the keyboard instead of clicking the button or placing the keyboard input on the new FormInput.

**Expected behaviour**
When I have typed something into a FormInput field and then I click a button it should process the onPress function rather than closing the keyboard. When I have typed something into a FormInput field and then click the next FormInput field it should move the cursor to that FormInput field so I can continue typing, not close the keyboard and have my click the FormInput field again to open the keyboard and type.

**Describe the bug**
When you are on a FormInput field and you select another element (Button, FormInput, Checkbox, etc) it closes the keyboard rather than interacting with the selected element. Then you have to select the element a second time in order to interact with it.

**To Reproduce**
# Steps
1. Add a FormInput and any other element to a screen (Button, Checkbox, FormInput, etc)
2. Launch the app on an Android device
3. Click on the FormInput and watch the keyboard open
4. Click on any other element and watch the keyboard close as opposed to interacting with the element and closing the keyboard if not a text field.

**Your Environment (please complete the following information):**
| Expo version | 27 |
| react-native-elements version | 0.19.1 |
| react-native version | Expo version 27 |
| npm version | 5.6.0 |

**Comment by MeKyleH** [comment]
@xavier-villelegier that worked! Thanks so much! Hopefully this helps someone else in the future as well.

**Comment by WiseWillian** [comment]
@MeKyleH It helped haha

**Comment by bobber205** [comment]
Same for me!

**Comment by duenwaldd1** [comment]
Same here!
