### ISSUE TITLE
[Icon] loading props

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#1237]
**Is your feature request related to a problem? Please Describe.**

If you want to implement a Button which only has an Icon, and add a loader behavior, you can't do it either by using Button nor Icon using `beta-v5`

**Describe the solution you'd like**

Implement the same `'loading` props for Icon as Button such as :

- loading
- loadingProps
- loadingStyle

**Question**

Is there anyone else finding this interesting ?

**Comment by xavier-villelegier** [comment]
@LouisJS Are you trying to do something [like this](https://snack.expo.io/Hk1-rTqy7) ?

**Comment by xavier-villelegier** [comment]
Closing this because the `Button`already has a loading feature. @LouisJS Feel free to reopen this issue if you still need some help
