### ISSUE TITLE
Input touch prevent to scroll

### ISSUE THREAD

**Issue by tinchoz49** [react-native-training/react-native-elements#1239]
**Explain what you did**
I update react-native-element from 0.19.0 to 1.0.0-beta5 and change FormInput to Input.

**Expected behaviour**
The scroll needs to work even if the user taps on an input text.

**Describe the bug**
The scroll functionality works using FormInput on 0.19.0 but stop working on the last v1 beta5.

**To Reproduce**
Example with `FormInput` 0.19.1:

```bash
# Snack
https://snack.expo.io/SkUzXuh1m

# Steps
1. Tap on an input and at the same time try to scroll.
2. It works
```

Example with `Input` 1.0.0-beta5:

```bash
# Snack
https://snack.expo.io/B1Clr_2JQ

# Steps
1. Tap on an input and at the same time try to scroll.
2. It doesn't work
```

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5|
| react-native | 0.55.4|
| npm or yarn | npm|

**Comment by archvill** [comment]
Workaround:
there is an inputStyle prop with these defaults:

    input: {
        alignSelf: 'center',
        color: 'black',
        fontSize: 18,
        marginLeft: 10,
        flex: 1,
        height: 40,
    },

Looks like this happens only when given `height` is not enough to display text with given `fontSize`.
Solution: either increase height, or decrease fontSize, or just pass { height: undefined } to reset value to optimal.

**Comment by RuiSa** [comment]
> Workaround:
> there is an inputStyle prop with these defaults:
> 
> ```
> input: {
>     alignSelf: 'center',
>     color: 'black',
>     fontSize: 18,
>     marginLeft: 10,
>     flex: 1,
>     height: 40,
> },
> ```
> Looks like this happens only when given `height` is not enough to display text with given `fontSize`.
> Solution: either increase height, or decrease fontSize, or just pass `{ height: undefined }` to reset height to optimal.

After 3h looking up for the solution finally found this! Thank you! :fist_oncoming:
