### ISSUE TITLE
Button prop iconRight causes error

### ISSUE THREAD

**Issue by GregTheGreek** [react-native-training/react-native-elements#1242]
When the prop `iconRight` is applied to `Button` it seems to crash with the following error:
<img width="295" alt="screen shot 2018-06-04 at 20 50 03" src="https://user-images.githubusercontent.com/16929357/40948971-8f151bc8-6839-11e8-84ca-fbc303fba8a4.png">

Removing it stops the error and iconLeft works.

```
<Button
    style={buttonStyle}
    backgroundColor={'purple'}
    title='Continue'
    icon={{ name: 'arrow-forward' }}
    iconRight
    loading={this.props.loading}
    loadingRight
    disabled={!isValid}
    onPress={() => this.props.finishStep1(
		  this.state.email,
		  this.state.phoneNumber
	  )}
/>
```

|iOS|
| react-native-elements |0.19.0 |
| react-native | ^0.54.0 |
| npm or yarn |5.7.1 |

**Comment by iRoachie** [comment]
There's no`iconRight` prop for the button in `v0.19.0`. If you want to display an icon on the right of the button, then you use the `rightIcon` prop.  Similarly, if you want an icon to the left then use the `icon` prop.

See button docs for `0.19.0` [here](https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html#lefticon-or-icon).

Here's an [example snack](https://snack.expo.io/SycBYO7xQ) as well.

**Comment by Srija-t2s** [comment]
![screenshot_1528191805](https://user-images.githubusercontent.com/27417357/40968487-4939848c-68d3-11e8-9e1b-4ae9179ed49b.png)
Getting box type of icon instead of chevron

**Comment by Srija-t2s** [comment]
This happens in my emulator

**Comment by xavier-villelegier** [comment]
@Srija-t2s Make sure you installed correctly the vector icons https://react-native-training.github.io/react-native-elements/docs/0.19.0/troubleshooting.html#fontfamily-font-name-is-not-a-system-font

**Comment by GregTheGreek** [comment]
@iRoachie thank you, i think the prop name changed over some versions ago.

@Srija-t2s Im closing this but @xavier-villelegier is most likely right you're probably using the icons incorrectly, grey box would indicated it cannot find the icon.
