### ISSUE TITLE
[TypeScript] inputContainerStyle missing from InputProps type definition

### ISSUE THREAD

**Issue by KevinShiCA** [react-native-training/react-native-elements#1249]
The `inputContainerStyle` prop seems to be missing from the interface `InputProps`.
The prop works correctly, but throws a TypeScript error.

For my version the interface declaration is on line 692 of the declaration file.

Environment:

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |
| react-native | 0.55.4 |

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/9fc469e083d22c34c66c02db47f5239444c7f89c. Will be available next release.

**Comment by iRoachie** [comment]
Fixed in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
