### ISSUE TITLE
Horizontal Gap between List Item Bottom Borders and edge of Screen

### ISSUE THREAD

**Issue by gusba** [react-native-training/react-native-elements#1252]
<img width="377" alt="screen shot 2018-06-10 at 3 48 07 pm" src="https://user-images.githubusercontent.com/29487619/41205672-bcc49dce-6cc5-11e8-8080-6361f94f607e.png">
 
I want to add a gap to the list item's bottom border so it looks like the screenshot. How would I achieve this?

**Comment by M-Jas** [comment]
@gusba how are you implementing the list above? FlatList?

**Comment by xavier-villelegier** [comment]
Closing this in favor of #1282
