### ISSUE TITLE
rightElement prop of ListItem not being rendered

### ISSUE THREAD

**Issue by betoharres** [react-native-training/react-native-elements#1254]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I'm trying to display a **custom** badge as right element of the list item

**Expected behaviour**
to show the badge

**Describe the bug**
The badge is not showing, actually neither a simple ``Text`` inside of it

**To Reproduce**
-

**Possible Solution**
Can you suggest a possible fix that would address this issue? 
I don't know, but I could look into it.

**Screenshots**

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 0.19.1 |
| react-native |  0.55.4 |
| yarn | 1.7.0 |

**Comment by iRoachie** [comment]
You can see the usage for the badge [here](https://react-native-training.github.io/react-native-elements/docs/0.19.0/lists.html#badges)

**Comment by betoharres** [comment]
Hello, sorry to confuse the thread with the ``Badge`` component.  It happens to be a badge, but any other element is not being rendered, I've tried a simple ``Text`` component and it did not worked too, maybe I missed something? Any clarification would be welcome, cheers!

**Comment by MeKyleH** [comment]
Here's an example that I ran across today:

```
      <ListItem
        roundAvatar
        key={key}
        title={title}
        subtitle={subTitle}
        rightElement={this.renderRightElement()}
      />
```

and 

```
  renderRightElement() {
    return (
      <View>
        <Icon
          name='add'
          size={20}
          color='blue'
        />
        <Icon
          name='accessibility'
          size={20}
          color='red'
        />
      </View>
    );
  }
```

The list item displays with just the normal chevron, it doesn't show the blue and red icon as I would expect.

**Comment by iRoachie** [comment]
@MeKyleH The LisItem in 0.19.1 doesn't have a `rightElement` prop. You have to use [`rightIcon`](https://react-native-training.github.io/react-native-elements/docs/0.19.0/lists.html#righticon).

**Comment by betoharres** [comment]
@iRoachie oh, I get it, I was viewing the 1.0.0-beta5 docs; I did even bother to check this since it was a fresh install. Thanks!

**Comment by MeKyleH** [comment]
P.S. changing it to rightIcon worked. Thanks @iRoachie
