### ISSUE TITLE
ListItem Icon overlayContainerStyle Bug

### ISSUE THREAD

**Issue by DeanmvSG** [react-native-training/react-native-elements#1258]
**Explain what you did**
When setting a `backgroundColor` within the `overlayContainerStyle` for a `leftAvatar` the value applies to the background of the icon if the size is anything from `small` through to `large`.  When changing the `size` to `xlarge` the `backgroundColor` value then applies to the icon.

**Expected behaviour**
The color should apply to the background for all of the sizes.

**Describe the bug**
Values within the `overlayContainerStyle` get applied to the icon itself, not its background.

**To Reproduce**
Test the following code in a project.

Working background color:
```
<ListItem
	title="Working"
	leftAvatar={{
		size: 'large',
		rounded: true,
		icon: {
			name: 'building-o',
			type: 'font-awesome'
		},
		overlayContainerStyle: {
			backgroundColor: '#2c2e2f',
		}
	}}
/>
```

Broken version:
```
<ListItem
	title="Not working"
	leftAvatar={{
		size: 'xlarge',
		rounded: true,
		icon: {
			name: 'building-o',
			type: 'font-awesome'
		},
		overlayContainerStyle: {
			backgroundColor: '#2c2e2f',
		}
	}}
/>
```

**Screenshots**
Working:
<img width="74" alt="screen shot 2018-06-12 at 21 47 51" src="https://user-images.githubusercontent.com/15265711/41316796-3975cd68-6e8b-11e8-9c78-21ab1019be2e.png">

Broken:
<img width="66" alt="screen shot 2018-06-12 at 21 54 37" src="https://user-images.githubusercontent.com/15265711/41316800-3c47c870-6e8b-11e8-92aa-728436d3ee59.png">

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | v1.0.0-BETA5 |
| react-native | 16.3.1 |
| npm or yarn | npm 6.10 and yarn 1.70  |

**Comment by xavier-villelegier** [comment]
Hey @DeanmvSG, actually, it is working but the icon is too big to show the background color. You can add a size to the `icon` props:

**Code**
```jsx
<ListItem
	title="Not working"
	leftAvatar={{
		size: 'xlarge',
		rounded: true,
		icon: {
			name: 'building-o',
			type: 'font-awesome',
			size: 20,
		},
		overlayContainerStyle: {
			backgroundColor: '#2c2e2f',
		}
	}}
/>
```

**Result**
![image](https://user-images.githubusercontent.com/17592779/41338393-5a438b9a-6ef2-11e8-8187-a967c70d7643.png)

**Comment by DeanmvSG** [comment]
@xavier-villelegier I could have sworn I tried that last night! It was a long day! 😫 Thanks!

All working fine 👍
