### ISSUE TITLE
IconRight bug 

### ISSUE THREAD

**Issue by yeomann** [react-native-training/react-native-elements#1265]
**Explain what you did**
Hi, It seems that whenever `iconRight` attribute is preset in Button tag. the whole app went to a red screen.

**Expected behaviour**
show icon on right side.

**Describe the bug**
I highly believe this is a bug. whenever I add iconRight the whole app crashes in button component. I attached already screenshot as well. I am just importing Button component above on my file and writing button jsx while adding icon like  `icon={{ name: "code" }}`

**Screenshots**
<img width="1081" alt="screen shot 2018-06-17 at 10 54 45" src="https://user-images.githubusercontent.com/5970751/41505972-ea931c9c-721c-11e8-91b2-b2bf8d28268e.png">

**Your Environment (please complete the following information):**
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-elements": "^0.19.1",
"npmn": 6.1.0

**Comment by yeomann** [comment]
I think its because I didn't install library with beta tag? I don't know I have reverted to specific versions `"react-native-elements": "0.19.0"`

**Comment by yeomann** [comment]
ok It was bcz of the Version. I had to use beta. this can be closed now

**Comment by iRoachie** [comment]
Hey @yeomann, it's good that you updated to the beta. But just letting you know that you didn't have to, and you could've done it in the stable version.

 `iconRight` takes in an object just like `icon`. Example here https://snack.expo.io/rkVQq0m-m

**Comment by iRoachie** [comment]
Whenever in doubt, check the documentation https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html#righticon

**Comment by yeomann** [comment]
Hi Rocahie yeah you are right, I am currently using Gradient as well so it was good idea to upgrade
