### ISSUE TITLE
how to set only Integer value for Rating instead Float Values

### ISSUE THREAD

**Issue by Ramaraju1992** [react-native-training/react-native-elements#1267]
for my API calls floating values like 1.2,2.3,3.1,...etc are not acceptable... Only i can Send Integer values like 1,2,3,... etc. i can trim float into integer for API calls but user will knowledge as he given floating value only as UI for Rating images will be like half Star only... but that is wrong... can you make one more param for only full stars(only integers) or by default Half stars(for Float)...

**Comment by iRoachie** [comment]
Sounds like a good feature to have. What do you think @Monte9? [react-native-star-rating[(https://github.com/djchie/react-native-star-rating) has that prop called `halfStarEnabled`. Maybe we can do something similar.

**Comment by iRoachie** [comment]
Closing this. If anything open a PR over at https://github.com/Monte9/react-native-ratings

**Comment by illuminist** [comment]
Setting `fraction` props to 0 will force Rating to output only integer.
```javascript
<Rating showRating fractions={0} startingValue={3} />
```
