### ISSUE TITLE
Beta:: Error: Unable to resolve module `expo`

### ISSUE THREAD

**Issue by devautor** [react-native-training/react-native-elements#1270]
**Explain what you did**
I am trying to create a Button component with styled text.

**Describe the bug**
```
error: bundling failed: Error: Unable to resolve module `expo` from `G:\WorkingOn\Storyteller\node_modules\react-native-elements\src\buttons\Button.js`: Module `expo` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
```

**To Reproduce**
```
<Button
  buttonStyle={styles.buttonStyle}
  title="Get started"
  titleProps={styles.buttonText}
/>
```

```
const styles = StyleSheet.create({
  buttonStyle: {
    backgroundColor: Colors.twitter,
    borderColor: "transparent",
    borderWidth: 0,
    borderRadius: 40
  },
  buttonText: {
    fontWeight: "bold",
    fontSize: Fonts.size.h3
  }
});
```

**Possible Solution**
This issue has previously been reported for a prior beta version [here](https://github.com/react-native-training/react-native-elements/issues/826).

**Your Environment (please complete the following information):**
From package.json => 
"react-native": "0.55.1",
"react-native-elements": "^1.0.0-beta"

**Comment by iRoachie** [comment]
@devautor We really can't provide any more solutions other than the ones suggested in the issue linked above. We can't reproduce this on a newly created project, so it's an issue local to your environment.

**Comment by devautor** [comment]
@iRoachie Okay, great! Do you have any suggestions on what could that local issue be, or how to fix it?

**Comment by iRoachie** [comment]
Can you update to the latest beta and confirm if you still have the issue??

```bash
# yarn
yarn add react-native-elements@beta

# npm
npm i --save react-native-elements@beta
```

**Comment by devautor** [comment]
It works following the "@beta" command you proposed. Thanks!

**Comment by sunerasv95** [comment]
@devautor 
error: bundling failed: Error: Unable to resolve module `expo-font` from `C:\Users\Kumara\MegaGym\node_modules\@expo\vector-icons\createIconSet.js`: Module `expo-font` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

and in my package.json ,
...
 "react": "16.6.0",
 "react-native": "0.57.3",
 "react-native-elements": "^1.0.0-beta7",
...
