### ISSUE TITLE
ListItem: TextInput w/ No Title Portion

### ISSUE THREAD

**Issue by ericmorgan1** [react-native-training/react-native-elements#1272]
Using React Native Elements 0.19.1.

**Is your feature request related to a problem? Please Describe.**
If using a `ListItem` with a `textInput` and no `title`, the title portion still takes up some space, despite being blank.

We may want to have a TextInput-ListItem with no title because the `textInputPlaceholder` can serve the same purpose as a title.

Example:
I would like to get a UI similar to this:
![img_9725](https://user-images.githubusercontent.com/10346191/41637572-3806ab16-741a-11e8-9653-59ae129191bf.PNG)

But the best I could come up with was this:
![screen shot 2018-06-19 at 11 43 40 pm](https://user-images.githubusercontent.com/10346191/41637668-a21eae4a-741a-11e8-9329-0f3971afc425.png)

```
<ListItem 
      hideChevron={true} textInput={true} leftIcon={{name: "email"}} textInputPlaceholder="Email"
      textInputStyle={{textAlign: "left" }} textInputContainerStyle={{ flex: 3 }} containerStyle={{backgroundColor: "white"}}
    />
```

**Describe the solution you'd like**
Make it easier to have the `textInput` portion fill up the remaining width.
Based on comments in #801 maybe that would involve allowing the `title` to be removed, like:

`<ListItem hideTitle={true} />`

But I would be open to alternative solutions.

**Describe alternatives you've considered**
I tried adjusting the various style properties that are available, but could not get it looking the way I wanted.

**Comment by iRoachie** [comment]
Hey @ericmorgan1, there's no way to do it explicitly in `0.19.1` other than in the example you saw in #801. 

However, we do have a new `ListItem` component that gives you that flexibility in the beta. Here's an example of it https://snack.expo.io/BJzeyeqWm.

To install the beta, simply run:
```bash
# npm
npm i --save react-native-elements@beta

#yarn
yarn add react-native-elements@beta
```

**Comment by ericmorgan1** [comment]
@iRoachie Nice, thanks!
