### ISSUE TITLE
Input text overflow not working on iOS

### ISSUE THREAD

**Issue by michael-molina** [react-native-training/react-native-elements#1276]
**Explain what you did**
Big text input with slashes (http://www.aaaaaaaaaaaaaaaaaaaaaaa.com/v1)

**Expected behaviour**
Truncated text with ellipsis.

**Describe the bug**
When a big text input contains slashes ( / ) and you click on another input, the first input is truncated strangely. Only happens on iOS.

**To Reproduce**

Example:

```bash
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { Input } from 'react-native-elements';

export default class App extends React.Component {

  constructor() {
    super();

    this.state = {
      server: undefined,
      email: undefined
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <Input
          onChangeText={server => this.setState({ server })}
          value={this.state.server}
          autoCapitalize='none'
        />
        <Input
          onChangeText={email => this.setState({ email })}
          value={this.state.email}
          autoCapitalize='none'
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  }
});
```

**Possible Solution**
Can you suggest a possible fix that would address this issue?
No

**Screenshots**
![1](https://user-images.githubusercontent.com/40404971/41741187-3b5d4d8e-754f-11e8-8264-9cf50b25f85b.JPG)![2](https://user-images.githubusercontent.com/40404971/41741194-3e29d4f6-754f-11e8-92ba-d454a5449edc.JPG)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta4 |
| react-native | 0.55.2 |
| npm or yarn | 6.1.0 |

**Comment by xavier-villelegier** [comment]
@michael-molina Actually, this is a React Native issue, you can see that this bug appears also on the RN `TextInput` https://snack.expo.io/r1ly4yob7 🤔

But if you find any workaround to this issue feel free to share it !

**Comment by michael-molina** [comment]
@xavier-villelegier Thank you for your feedback. I opened a bug #19871 in react-native github.

**Comment by brunoreis** [comment]
If someone else finds this, you might try to remove the padding/extra styles of the input. Worked for me.
