### ISSUE TITLE
How to show text and Button view in right side of ListItem 

### ISSUE THREAD

**Issue by Srija-t2s** [react-native-training/react-native-elements#1277]
In listItem on right side i need to show a textview along with button.I tried rightElement and rightTitle.But it doesn't work.What props I can try ?? Any suggestions?

| react-native-elements | | - 0.19.1
| react-native | |-0.55.1
| npm or yarn | |5.5.1

**Comment by xavier-villelegier** [comment]
@Srija-t2s `rightTitle` and `rightElement` are from `v1.0.0-beta5`. You can try the beta by doing:

```
yarn add react-native-elements@beta
```

**Comment by xavier-villelegier** [comment]
Have a look at the `bottomDivider` props in the doc 😉
