### ISSUE TITLE
Button with loading props turns into a grey box on Android only

### ISSUE THREAD

**Issue by msevestre** [react-native-training/react-native-elements#1278]
**Explain what you did**
Using 1.0.0.beta5
I have a view with a Button. The loading prop is set according to some state in the component

**Expected behaviour**
When the loading prop is set, I am expecting the button style to stay the same albeit with a loading indicator. This is the behavior in iOS and was the behavior on Android until I updated from beta2 to beta2

**Describe the bug**
On android, the button with loading prop set to true forgets about button style and becomes square
I tried to set the `loadingSyle` explicitely but it does not change anything

**Screenshots**

IOS:
![image](https://user-images.githubusercontent.com/1041237/41779073-a894474a-75fe-11e8-9878-e682cb218337.png)

![image](https://user-images.githubusercontent.com/1041237/41779157-ed7f8266-75fe-11e8-86d7-6defbe57c3a9.png)

Android:

![image](https://user-images.githubusercontent.com/1041237/41779239-31f113f6-75ff-11e8-9ffb-e5e74a30df29.png)

![image](https://user-images.githubusercontent.com/1041237/41779267-4c991636-75ff-11e8-96ce-af04c894b443.png)

My button looks like so

```
<Button
              buttonStyle={styles.signInButton}
              containerStyle={styles.signInButtonContainer}
              activeOpacity={0.8}
              title={t('signIn')}
              onPress={this.signIn}
              textStyle={styles.loginTextButton}
              loading={isAuthenticating}
              disabled={isAuthenticating}
            />
```
with
```
 signInButton: {
  borderRadius: 30,
  height: 50,
  width: 200,
  backgroundColor: colors.primary,
  },
```
| software | version |
| -- | -- |
| react-native-elements |1.0.0.beta5 |
| react-native |0.55.4 |
| npm or yarn |yarn |

I am not really sure what else to try at that stage,

Cheers,
Michael

**Comment by xavier-villelegier** [comment]
Hey @msevestre, I think this can be improved.

If anyone wants to tackle this, we just need to remove these lines
https://github.com/react-native-training/react-native-elements/blob/e0406c72f341b354f2861b85eb9a432863a50768/src/buttons/Button.js#L196-L199

In the meantime, you can override the `borderRadius` in the `disabledStyle`
```jsx
<Button
  buttonStyle={styles.signInButton}
  disabledStyle={{ borderRadius: 30 }} // <- Add this
  containerStyle={styles.signInButtonContainer}
  activeOpacity={0.8}
  title={t('signIn')}
  onPress={this.signIn}
  textStyle={styles.loginTextButton}
  loading={isAuthenticating}
  disabled={isAuthenticating}
/>
```

**Comment by msevestre** [comment]
@xavier-villelegier Great find man.  Thanks

How would you like to improve it?

**Comment by xavier-villelegier** [comment]
@msevestre We just need to remove the `android` style applying a weird `borderRadius: 2` for the disabled style, I honestly don't know why it's here lol, the disabled style shouldn't be overriding any radius

**Comment by msevestre** [comment]
@xavier-villelegier ok I'll do it and submit a PR. Cheers

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
