### ISSUE TITLE
ListItem borderBottom Length Control

### ISSUE THREAD

**Issue by TheSolly** [react-native-training/react-native-elements#1282]
I am trying to control the length of the BottomBorder on my ListItem which is rendered inside a List Component, going through the doc the only way i could found is through borderBottomStartRadius which is working and achieving my desired overall look. But it doesnt look perfect from UI point of view.

Here i am using
`containerStyle={{
                marginTop: 0,
                borderBottomStartRadius: 50,
              }}` 

![listitem](https://user-images.githubusercontent.com/31882844/41862745-102dd184-78a5-11e8-92ac-84207297c7bf.PNG)

but if one looked carefully on the left end of Border, it look distorted cause of the radius behavior. Is there any other means i can control the border length?!

**Comment by xavier-villelegier** [comment]
Hey @TheSolly, thanks for the workaround ! This is currently not possible but is something we need to improve. (cc @martinezguillaume)

**Comment by martinezguillaume** [comment]
Hello @TheSolly ! If you want to do this, please use [ItemSeparatorComponent](https://facebook.github.io/react-native/docs/flatlist#itemseparatorcomponent) prop from FlatList. And you can use `Divider` component with an appropriate style to render your separator 😀. At this time, we can't implement this in the `ListItem` component without make it complex (adding View wrapper). But if someone has an idea on how to do it, I'll be glad to hear it !

**Comment by TheSolly** [comment]
@xavier-villelegier no worries. understood.

Yup, already implemented the ItemSeparatorComponent solution, thanks for the info.
