### ISSUE TITLE
'numberOfLines' prop for Input component doesn't take effect

### ISSUE THREAD

**Issue by mashwinprdxn** [react-native-training/react-native-elements#1283]
I'm trying to create a multiline input as shown below, but I'm still getting a single-line input box:
```javascript
<Input
  multiline={true}
  numberOfLines={4}
  labelStyle={{ color: global.PALETTE.WHITE }}
  containerStyle={{ width: '100%' }}
  inputContainerStyle={{
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: global.PALETTE.WHITE
  }}
  {...props}
/>
```
I'm able to press the return key and create new lines, but the size of the Input box remains the same.
What am I doing wrong here? Thanks

**Comment by mashwinprdxn** [comment]
Testing on Android
react-native: 0.55.4
react-native-elements: 1.0.0-beta5

**Comment by iRoachie** [comment]
Hey @mashwinprdxn the input has a default height of 40 https://github.com/react-native-training/react-native-elements/blob/master/src/input/Input.js#L147. 

To override this and derive the height from the `numberOfLines` set the height on the `inputStyle` to null. https://snack.expo.io/HkRPsEXzQ

**Comment by mashwinprdxn** [comment]
@iRoachie Thanks a lot, That worked! Also I'd like to add that for it to work on Android, you need to add the following prop: `textAlignVertical={'top'}` [(stackoverflow question)](https://stackoverflow.com/questions/41378036/position-of-placeholder-text-in-multiline-textinput-for-android-react-native)

**Comment by platonish** [comment]
@iRoachie Hi, I tried your [snack](https://snack.expo.io/HkRPsEXzQ) on an iPhone, and the text input is a single line: 

![img_1586](https://user-images.githubusercontent.com/24620401/43252336-d8daf178-90df-11e8-93f3-d40db103b336.jpg)

**Comment by xavier-villelegier** [comment]
@platonish Which version of RNE do you use on snack ? Make sure you use the last beta (`1.0.0-beta5`)

**Comment by xavier-villelegier** [comment]
@platonish The input is not a single line, you can enter multiple lines, just hit the "Return" key.

And this is the same behavior on RN TextInput. Check out [this snack](https://snack.expo.io/HkRPsEXzQ)
![image](https://user-images.githubusercontent.com/17592779/43392970-b1279b18-93f5-11e8-93c7-597d417fb139.png)

**Comment by platonish** [comment]
@xavier-villelegier  Yeah, but isn't the `numberOfLines` prop supposed to set an initial number of lines? Here's the same snack running on Android, without pressing return. Initially the input box renders with 5 lines (since the `numberOfLines` prop is set to 5) and after pressing return on the 5th line, the input box expands to show the 6th line.
![screenshot_2018-07-30-16-39-34-1612095398](https://user-images.githubusercontent.com/24620401/43394127-4092fe48-9417-11e8-8c75-948366563088.png)

**Comment by iRoachie** [comment]
`numberOfLines` set's the max number of lines the TextInput is allowed to have https://facebook.github.io/react-native/docs/text.html#numberoflines. It seems like you just need to use height if you want a taller input.

**Comment by platonish** [comment]
@iRoachie I see, I checked out the [docs](https://facebook.github.io/react-native/docs/textinput#numberoflines) and according to it, `numberOfLines` is only for Android. Setting a fixed height to the input won't let it expand with the content 😕 I set height in `inputStyle` to null as you mentioned in an earlier comment, and it worked exactly as expected on Android.

**Comment by iRoachie** [comment]
Why not use `minHeight`?

**Comment by platonish** [comment]
@iRoachie Perfect! That worked, thanks a lot!

**Comment by nokieng17** [comment]
Set like this
```
inputContainerStyle={{
          alignItems: "flex-start" // You need this when you add icon
}}
inputStyle={{
          height: 400
}}
```
`numberOfLines` and `multiline` as well
