### ISSUE TITLE
'innerBorderStyle' prop doesn't take effect

### ISSUE THREAD

**Issue by mashwinprdxn** [react-native-training/react-native-elements#1284]
I used the `ButtonGroup` component to create a group of three buttons like so:
```javascript
<ButtonGroup
  buttons={['Hello', 'World', 'Buttons']}
  selectedIndex={0}
  containerStyle={{ backgroundColor: 'transparent' }}
  innerBorderStyle={{ color: global.PALETTE.WHITE }}
  textStyle={{ color: global.PALETTE.WHITE }}
  selectedButtonStyle={{ backgroundColor: global.PALETTE.WHITE }}
  selectedTextStyle = {{ color: global.PALETTE.PRIMARY.MAIN }}
/>
```

However the lines between the buttons don't show up:

![screenshot_2018-06-27-17-01-19-0449323749](https://user-images.githubusercontent.com/39124207/41971439-0cf315dc-7a2c-11e8-8e36-92b0d57fe739.png)

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |
| react-native | 0.55.4 |

**Comment by iRoachie** [comment]
Hey @mashwinprdxn you can see here in this example that setting the `innerBorderStyle` works https://snack.expo.io/HJZpPB-Gm.

You may be experiencing this error if you're testing in a simulator.

**Comment by mashwinprdxn** [comment]
Hi @iRoachie, thanks for the reply. I'm testing on a real device running Android Nougat. Below is a screenshot of the above snack running on my phone. I'm not sure if this is an Android exclusive problem.


![screenshot_2018-06-29-10-41-50-0266167468](https://user-images.githubusercontent.com/39124207/42074409-bfe41ea8-7b89-11e8-9a34-8737afe8dbde.png)

**Comment by xavier-villelegier** [comment]
@mashwinprdxn Did you finally fix this ? It may be an issue related to the resolution of the screen (when you use a borderWidth < 1, this can cause some issues on some devices or simulators). Feel free to reopen this issue if needed

**Comment by iRoachie** [comment]
Was fixed in https://github.com/react-native-training/react-native-elements/pull/1193/commits/dc783de99d7ee2f3f92ac0b84d1fb49db822eaa7

**Comment by mashwinprdxn** [comment]
@xavier-villelegier it works fine on iOS but not on Android, so for the time being, I gave the buttons a borderWidth. 
@iRoachie thanks :thumbs_up:
