### ISSUE TITLE
Warning: failed prop type: Invalid prop 'iconRight' of type 'object' supplied to 'Button', expected 'boolean'.

### ISSUE THREAD

**Issue by jpdesignerrio** [react-native-training/react-native-elements#1286]
I don't speak English so good, so I'll resume.
When I do, like documentation:

```
import * as Elements from 'react-native-elements';

<Elements.Button
                large
                iconRight={{name: 'arrow-forward'}}
                title='CONTINUAR'
                onPress={() => {}} />
```
It's returning: 

> Warning: failed prop type: Invalid prop 'iconRight' of type 'object' supplied to 'Button', expected 'boolean'.

Finally, I added a single line, and changed another:
`Included: iconRight={true}`
`changed: icon={{name: 'arrow-forward'}}`

And this works fine :)

I install the plugin right now, so I thing that is the last version.

**Comment by iRoachie** [comment]
Sorry about that, `iconRight` should not be there. The prop is `rightIcon` see https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html#righticon. Sorry about the confusion, will update the example.

**Comment by xavier-villelegier** [comment]
Closing this since it has been merged

**Comment by methodbox** [comment]
Looks like this is still a problem, but there is an actual problem, not just a typo:

```js
<Button
  icon={{
    name: 'arrow-right',
    size: 15,
    color: 'white'
  }}
  title='BUTTON WITH ICON OBJECT'
/>
```

That's from your examples, but reading through the error, ```arrow-right``` is indeed invalid; the value provided in the error is ```arrow-forward```; this works.

What NOT using this as an object to pass the prop values, but instead as in Icon Component, it works fine:

```js
<Button
  icon={
    <Icon
      name='arrow-right'
      size={15}
      color='white'
    />
  }
  title='BUTTON WITH ICON COMPONENT'
/>
```

Looks like there's some naming scheme issues in props as objects vs. the component's usage of the same name.

**Comment by iRoachie** [comment]
@methodbox please create a new issue and mention the version of react native elements you’re using
