### ISSUE TITLE
Input field value does not change when setting state.

### ISSUE THREAD

**Issue by HardikDhanani** [react-native-training/react-native-elements#1289]
I have a field where I want the name field to accept only characters and spaces.
```
onChangeText={(name) => {
  let fullName = name.replace(/[^a-zA-Z\s]/g, "");
  this.setState({name: fullName}, () => {
    alert(this.state.name) <----- I get the updated state value here
  })
}}
```

My input takes value from state.
```value={this.state.name}``` <----- I also get the updated state value here

This is also being passed to the render method on the Input.js in the library.
But the element is not getting updated.

**Comment by iRoachie** [comment]
What version of react-native-elements are you using?

**Comment by HardikDhanani** [comment]
Hello @iRoachie 

I'm using below Packages version and Environment. 

Packages: (wanted => installed)
  react: 16.4.0 => 16.4.0
  react-native: 0.55.4 => 0.55.4
  react-native-elements: 1.0.0-beta5 => 1.0.0-beta5

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.3
  npm: 5.5.1
  Watchman: 4.9.0

**Comment by xavier-villelegier** [comment]
@HardikDhanani Could you reproduce this on snack ? Feel free to post the answer if you found it.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
