### ISSUE TITLE
underlayColor on Button not working

### ISSUE THREAD

**Issue by celsosa** [react-native-training/react-native-elements#1290]
The prop underlayColor is not working for me... why? How can I do this using Button component? Because my button is black, and on android, nativefeedback dont give a feedback for the user because the button is already darker.

example:

```
...
import {
    Button
} from 'react-native-elements'
...
<Button 
                backgroundColor='#000000' 
                underlayColor='#515151' 
                title='Register'
                 />
```

**Comment by iRoachie** [comment]
Can you please let me know what version of react-native-elements you are using?

**Comment by celsosa** [comment]
sry, wrong command haha
> npm view react-native-elements version
0.19.1

**Comment by iRoachie** [comment]
Here's an example using the `component` prop https://snack.expo.io/rJbqGZjfm

**Comment by iRoachie** [comment]
Sorry about that, there's a typo in documentation. It's `Component`.

**Comment by celsosa** [comment]
Thank u very much ^-^
Working now <3

**Comment by StanislavVoronov** [comment]
Your decision does not work in version 1.0.0-beta5

**Comment by iRoachie** [comment]
@StanislavVoronov the name of the prop in beta5 is `TouchableComponent`

**Comment by StanislavVoronov** [comment]
Nothing happen. Also button doesn't have prop underlayColor in beta5

**Comment by iRoachie** [comment]
@StanislavVoronov this has been fixed in the next beta https://github.com/react-native-training/react-native-elements/commit/ae0c4132f56a40b67803672392cbf482c0da70a1
