### ISSUE TITLE
Really need to keep both Form and Beta5. What should I do? Crying~~~T o T

### ISSUE THREAD

**Issue by brilliantjc** [react-native-training/react-native-elements#1291]
Hello,

We really need to keep both Form and Beta5. What should I do? Crying~~~T o T
There is no Form in Beta5~~~
I tried to just copy "form" folder from old file to the file updated with beta5 : /Users/username/project/myApp/node_modules/react-native-elements/src/form
not working. Please help !!!

**Comment by brilliantjc** [comment]
don't know why, I downgrade to 0.19.0 version, and my "beta5 only functions" are still working as beta5 described.

**Comment by iRoachie** [comment]
Hey @brilliantjc the form elements were replaced by the `Input` component in the betas, which has both FormInput, FormValidationMessage and FormLabel built into one component
