### ISSUE TITLE
Icon spin animation.

### ISSUE THREAD

**Issue by PMExtra** [react-native-training/react-native-elements#1296]
I want to set a spinner at right of `ListItem` while it's waiting for some operating.
Then I thought, why don't we make the `Icon` support spin animation?
There are many Font-Icon library such as `FontAwesome` that support spin animation.

**Comment by xavier-villelegier** [comment]
@PMExtra We're trying to use less dependencies as possible. For the icons, we're using `react-native-vector-icons` that currently doesn't support spin animation. However, it's really easy to use [`react-native-animatable`](https://github.com/oblador/react-native-animatable) on a icon to spin it. (you can also use the `Animated` API of RN directly if you don't want any dependency, but it's not as easy as RN animatable)

**Comment by PMExtra** [comment]
Thank you, I will try it. But I sincerely hope that there will be a simpler way.

**Comment by iRoachie** [comment]
Here's an example of how you'd do it with Animated https://snack.expo.io/SkLEOjkQ7

**Comment by xavier-villelegier** [comment]
And here is a simple example with `react-native-animatable` https://snack.expo.io/ByAxx6y7m

Closing this as both methods work well, feel free to ping us if you still need some help 👍
