### ISSUE TITLE
Where is the ButtonsTab (Bottom Menu) at the Screens?

### ISSUE THREAD

**Issue by Bizarrus** [react-native-training/react-native-elements#1297]
I can't find some examples. Where is the Bottom Menu on the Screens?

**Comment by xavier-villelegier** [comment]
@Bizarrus Don't know exactly what you're talking about but I think you're looking for a `TabNavigator` from [React Navigation](https://reactnavigation.org/docs/en/tab-based-navigation.html)

**Comment by arnaud-zg** [comment]
I guess you talked about this screen @Bizarrus 
![image](https://user-images.githubusercontent.com/10991546/42473409-d6b10536-83c4-11e8-9b81-292f435d390e.png)
