### ISSUE TITLE
'innerBorderStyle.width' = 0 can not hide the border 

### ISSUE THREAD

**Issue by jianggaocheng** [react-native-training/react-native-elements#1300]
I want to hide the border of buttonGroup, so I tried to set innerBorderStyle.width = 0, but it do not work.
However, when I set the value of innerBorderStyle.width = 0.1, it take effect...

**Comment by jianggaocheng** [comment]
https://snack.expo.io/HkVu0u4QQ

Here is a snack page that can see the effect

**Comment by iRoachie** [comment]
Fixed on next. Will be available next release

**Comment by iRoachie** [comment]
Fixed in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
