### ISSUE TITLE
righTitle textInputValue not showing

### ISSUE THREAD

**Issue by Sourabhd1164** [react-native-training/react-native-elements#1304]
Padding on textInputStyle doesn't work 
<View>
                <List>
                    <ListItem
                        title='Left Title:'
                        textInput={true}
                        textInputStyle={{
                            backgroundColor:'#fff',     
                            marginLeft: 30
                            }}
                        textInputValue='Right Title'
                    />
                </List>
</View>

![screenshot_1531488649](https://user-images.githubusercontent.com/36767253/42695301-f0e72a46-8682-11e8-82ef-34e4c25ae905.png)

**Comment by iRoachie** [comment]
Hey @Sourabhd1164, you can see here in this example that the `textInputStyle` works correctly https://snack.expo.io/S1q1CvjQX. Try updating to the latest version and see if the problem still persists `0.19.1`.

**Comment by xavier-villelegier** [comment]
Closing this as inactive
