### ISSUE TITLE
Invariant Violation: Element type is invalid when adding Overlay tag

### ISSUE THREAD

**Issue by robreuss** [react-native-training/react-native-elements#1308]
**Explain what you did**
I want to use the Overlay component.  I upgraded to 1.0.0 beta 5 and refactored all my usage of RNE elements so the app runs fine.  I then added an Overlay component and I get the "Invariant Violation" error.  If I remove the Overlay component, error is gone.

**Expected behaviour**
I expect to be able to use the Overlay component.

**Describe the bug**
Use of the Overlay component causes an Invariant Violation error.

**To Reproduce**
Try to use the Overlay component on beta 5 in this manner:

`        <Overlay isVisible={true}>
          <Text>My text</Text>
        </Overlay>`

**Possible Solution**
Is Overlay being exported properly?

**Screenshots**
![simulator screen shot - iphone 8 - 2018-07-16 at 19 25 14](https://user-images.githubusercontent.com/588682/42788535-094ae160-892e-11e8-8a67-6ce13d6b5a89.png)

**Your Environment (please complete the following information):**
RNE 1.0.0 beta 5
React Native 0.55.4

**Comment by iRoachie** [comment]
Hey @robreuss the `Overlay` works with no issues for beta5 as you can see in this example snack https://snack.expo.io/HyXL2vimm.

Have you tried clear the rn cache, watchman, and restarting the packager?

**Comment by robreuss** [comment]
@iRoachie I found the problem.  I was doing this:

`import Overlay from "react-native-elements";`

instead of...

`import { Overlay } from "react-native-elements";`

In other contexts, I've been able to import single modules without curly braces.  Am I misunderstanding something (I'm a novice to RN)?

**Comment by robreuss** [comment]
Thanks @iRoachie, I understand now.
