### ISSUE TITLE
FormInput component hava a unanticipated border of bottom on IOS.

### ISSUE THREAD

**Issue by TheSixth** [react-native-training/react-native-elements#1309]
I set 'underlineColorAndroid=transparent' only have effect on android.

**Comment by iRoachie** [comment]
`underlineColorAndroid` is an android only prop. The border you are seeing is an actual border style. You can set this using the `containerStyle` prop. Here's an example https://snack.expo.io/ryH89vomm

**Comment by TheSixth** [comment]
@iRoachie thanks
