### ISSUE TITLE
Rating background color

### ISSUE THREAD

**Issue by randanunn** [react-native-training/react-native-elements#1310]
The stars are contained inside of a white box, I would love to be able to modify that white color, or have it set to transparent by default.  I tried setting the ratingBackgroundColor which changes the background color of empty stars.  And tried setting the style of the Rating component to a different backgroundColor but that wraps the white box in another box of the color I defined.

![image](https://user-images.githubusercontent.com/5419140/42806099-dcf43d9a-896a-11e8-8b72-0b9f909eef6e.png)

I apologize ahead of time if I have missed something obvious in the settings.

**Comment by btav** [comment]
The `Rating` component has a `style` prop used to style the the container view. Can you try setting the `backgroundColor` in there?

**Comment by randanunn** [comment]
yes. I tried that like:

`<Rating
                readOnly
                fractions={1}
                startingValue={t4.5}
                imageSize={11}
                style={{ padding: 5, backgroundColor: 'red' }}
              />`

and I get this:
![image](https://user-images.githubusercontent.com/5419140/42831731-601cf3d8-89ac-11e8-97d1-f26a00f3a00d.png)

**Comment by Monte9** [comment]
yes, I think you are right. It does have a white background color.

The source of this is a npm module called `react-native-ratings`. There is a solution posted on the repo here: https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-401279355

Let me know if this helps.

**Comment by swanie42** [comment]
The solution that worked for me was to actually change the start.png in photoshop.  
![star](https://user-images.githubusercontent.com/1048176/43206065-0a2e9cf6-8fe2-11e8-9216-1361417f3ca0.png)
![node_modules_reactnativeelements_src_rating_images_star](https://user-images.githubusercontent.com/1048176/43206071-0f13dd76-8fe2-11e8-839d-2cf84bb8f5d0.png)

**Comment by badarshahzad** [comment]
Does someone like to tell, can we change the star color without using the custom star?

**Comment by ReactDevBeginner** [comment]
Hi @swanie42,

How to make a transparent background for start.png  in Photoshop ?

Thanks

**Comment by xavier-villelegier** [comment]
Closing this as for now the only solution is to use a custom star. Please feel free to check the repo of the rating package, or open a new issue here https://github.com/Monte9/react-native-ratings/issues

**Comment by chentao1006** [comment]
there is a tintColor prop which is not included in the documentation for changing the background color
https://github.com/Monte9/react-native-ratings/issues/26#issuecomment-480532803

**Comment by markgalang** [comment]
Found this as an alternative: [react-native-stars](https://www.npmjs.com/package/react-native-stars ). I believe react-native-ratings still performs better because react-native-stars only let you show the full and half stars.

It can be styled as a regular Icon. Here is the [documentation](https://www.npmjs.com/package/react-native-stars#usage) for that.

Here is mine:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/49332686/104517935-e9d60380-55c4-11eb-9629-62a7535d86f0.png">

If you want to hide the empty stars just set the color as "transparent" for the emptyStar prop.

Final code:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/49332686/104518413-a0d27f00-55c5-11eb-8625-39d98b421a73.png">

**Comment by KonstantinZhukovskij** [comment]
**tintColor** doesn't work if set to transparent background. Still waiting for a decision...

**Comment by slasho** [comment]
is this feature dump?

**Comment by Kamaluddin0302** [comment]
change to tintColor = "your background color"

**Comment by fsaraos27** [comment]
> cambie a tintColor = "su color de fondo"

Gracias amigo, está respuesta funcionó para mi...

![image](https://user-images.githubusercontent.com/70808971/212355706-3388a94d-dad6-42ff-8e0a-459e35c97f5b.png)

**Comment by mahabubr** [comment]
the tint color to remove the background
`
<Rating
	type='star'
	ratingCount={item.ratting}
	imageSize={15}
	readonly
	tintColor={colors.gray}
	style={styles.ratting}
/>
`

**Comment by ShwetKhatri2001** [comment]
To get the transparent background use [AirbnbRating](https://github.com/Monte9/react-native-ratings#airbnbrating). 
It's because the images they are using have a white background when it's being used in `Rating` but have a transparent background in the case of `AirbnbRating`.

**Comment by bhandarimanoj612** [comment]
![image](https://github.com/react-native-elements/react-native-elements/assets/105379940/c198ba8d-ac7a-4fbc-b613-9a381e20743a)

**Comment by bhandarimanoj612** [comment]
i have added solution for changing the background image of rating for react native

**Comment by sikirumoshood** [comment]
Use `tintColor` props and wrap in a view 
``` 
<View> <Rating /> </View> 
```
