### ISSUE TITLE
Typescript - Button missing props from TouchableNativeFeedback / TouchableHighlightFeedback

### ISSUE THREAD

**Issue by Barbiero** [react-native-training/react-native-elements#1314]
Version 1.0.0-beta5

**Explain what you did**
While using RNE with typescript, I noticed the compiler didn't recognize the `background` attribute for my buttons. When inspecting `Button`, I noticed that `ButtonProps` is extending `TouchableWithoutFeedback`, even though the [docs](https://react-native-training.github.io/react-native-elements/docs/button.html) state:
> Also receives all TouchableNativeFeedback (Android) or TouchableOpacity (iOS) props

**Expected behaviour**
`ButtonProps` should extend both `TouchableNativeFeedback` and `TouchableOpacity` classes, so that typescript won't complain when using either attributes. Wether they actually affect the end component depends on the target device, but it shouldn't be an error.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |
| react-native | 0.55.4 |
| npm | 6.1.0 |

**Comment by iRoachie** [comment]
Good find! Would you be willing to make a PR to fix it?

**Comment by iRoachie** [comment]
Available now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
