### ISSUE TITLE
SearchBar.clear is missing in Typings (1.0.0)

### ISSUE THREAD

**Issue by PMExtra** [react-native-training/react-native-elements#1316]
https://github.com/react-native-training/react-native-elements/blob/dc783de99d7ee2f3f92ac0b84d1fb49db822eaa7/src/index.d.ts#L1427-L1430

https://github.com/react-native-training/react-native-elements/blob/dc783de99d7ee2f3f92ac0b84d1fb49db822eaa7/src/searchbar/SearchBar.js#L22-L24

There is no `clearText` but `clear` here. I think the typings definition should be updated.

**Comment by PMExtra** [comment]
Let me ask a question about github.
How to reference a code like the below comment?

https://github.com/react-native-training/react-native-elements/issues/1184#issuecomment-387698011

**Comment by iRoachie** [comment]
Implemented in https://github.com/react-native-training/react-native-elements/commit/5a65c9b2fcedd1a7d90e41da71433d732a4d8232. Will be available next release

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
