### ISSUE TITLE
need "visible" props for icon

### ISSUE THREAD

**Issue by ZeroCool00** [react-native-training/react-native-elements#1317]
what if i wanted to hide icon by default and only visible on certain condition, is this possible..

current solution i m using is like this:

  ```
renderDeleteIcon() {
		if (this.state.rowSelected) {
			return <Icon name="delete" />;
		}
  }
```

Feature request:
```
<Icon
      visible={this.state.visible} // this one.
      color='#FF0000'
      type='MaterialIcons'
      name='delete'
  />
```

now you can see the different. it would be great if we can manage like this.. it save lot of code and time..

i m using native-base lib too. but there is no `visible props` for any component.. 
but i m using this library more often so it would be great if this props is available to **`each component`**

**Comment by iRoachie** [comment]
Is there any reason why you don't conditionally render the component?

```jsx
{this.state.visible && <Icon />
```

**Comment by ZeroCool00** [comment]
i m native android developer..  i dont know very much javascript shortcuts like you do.  you can see the line difference of my condition and your condition.

in short it would be easy if we are able to manage via props..

**Comment by iRoachie** [comment]
Handling via props in this case doesn’t make any sense. If the component doesn’t need to be rendered then don’t render it. This is beginner react fundamentals  https://reactjs.org/docs/conditional-rendering.html
