### ISSUE TITLE
Need to click for multiple times to make SearchBar clear icon work

### ISSUE THREAD

**Issue by incrediblink** [react-native-training/react-native-elements#1319]
**Explain what you did**
I used the SearchBar component and enabled the clearIcon feature.
```
<SearchBar
  ref={(search) => this.search = search}
  value={this.state.search}
  onChangeText={(text) => this.setState({ search: text })}
  containerStyle={searchBarStyle.searchContainer}
  inputStyle={searchBarStyle.searchInput}
  clearIcon={{ color: '#86939e', name: 'close' }}
  placeholder='输入事件/新闻关键词'
  lightTheme
/>
```

**Expected behaviour**
I expect that once I click (or touch) on the clear icon, the text I type in will be reset as `null`.

**Describe the bug**
I need to click on the clear icon at least twice to reset the input.

**To Reproduce**
The source code: [Search.js](https://github.com/v2land/v2land-mobile/blob/feature/search-page/src/components/Search.js)
To preview the bug, scan the following QR code with Expo.
![image](https://user-images.githubusercontent.com/7604366/43041121-9787a694-8d24-11e8-927f-a67dab69bc96.png)

```
# Steps
1. Go to '搜索', the second navigation tab on the bottom.
2. Type in something in the search bar.
3. Try click on the clear icon.
4. See error
```

**Your Environment (please complete the following information):**

| software | version |
| react-native-elements | 0.19.1 |
| react-native | 0.55.4 |
| yarn | 1.6.0 |

**Comment by ZeroCool00** [comment]
and its also open keyboard if its close..

**Comment by iRoachie** [comment]
This isn’t an issue with the library. You have to manage touch events when the keyboard is visible and the text input is in a scroll view. See https://medium.com/react-native-training/todays-react-native-tip-keyboard-issues-in-scrollview-8cfbeb92995b?source=linkShare-60b87ae09e91-1532345903

**Comment by incrediblink** [comment]
@iRoachie It works, thanks!
