### ISSUE TITLE
registerCustomIconType isn't exported in index.d.ts

### ISSUE THREAD

**Issue by AdrianoRuberto** [react-native-training/react-native-elements#1320]
**Explain what you did**
I followed the [Custom Icon Fonts](https://react-native-training.github.io/react-native-elements/docs/icon.html#custom-icon-fonts) to register my costum font.
I'm using typescript and try to import the function `registerCustomIconType('customid', customFont)` as written in the doc.

**Expected behaviour**
`import {registerCustomIconType} from "react-native-elements";` should work.

**Describe the bug**
`registerCustomIconType` doesn't exists in types `react-native-elements`.

**To Reproduce**
Just `import {registerCustomIconType} from "react-native-elements";` from anywhere.

**Possible Solution**
`export function registerCustomIconType(id: string, font: any): void;`
or maybe
`export function registerCustomIconType(id: string, font: typeof Icon): void;`
But typeof onPress isn't the same
**Screenshots**

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5|
| react-native | 0.55.4|
| npm or yarn | npm|

**Comment by iRoachie** [comment]
`registerCustomIconType` isn't apart of react-native-elements. Instead you should be importing `registerCustomIconType` from react-native-vector-icons.

**Comment by AdrianoRuberto** [comment]
@iRoachie It seems to exists on [react-native-elements](https://github.com/react-native-training/react-native-elements/blob/470dde7d7a9ddfd11483f5d3a06d3871a4faa6ca/src/helpers/getIconType.js)

I didn't find it on `react-native-vector-icons`, have you a link to it ?

**Comment by iRoachie** [comment]
You have to add the types fro react-native-vector-icons.
`npm i --save @typres/react-native-vector-icons`.

Oh and by the way `registerCustomIconType` is now `createIconSet` https://github.com/oblador/react-native-vector-icons#custom-fonts

**Comment by iRoachie** [comment]
Would you willing to send a PR to update our docs so they have the correct function?

**Comment by AdrianoRuberto** [comment]
I don't want to create an IconSet, I want to register my custom font to use it in the `Icon` element of `react-native-elements`.

Using 
https://github.com/react-native-training/react-native-elements/blob/470dde7d7a9ddfd11483f5d3a06d3871a4faa6ca/src/helpers/getIconType.js#L15

I can write
```typescript
<Icon name="my-custom-icon-name" type="my-custom-icon-type" />
```

Maybe I didn't understand correctly the docs, but it's written:
> Register your own custom icons by calling `registerCustomIconType('customid', customFont).`

If I use the `createIconSet` as you say, I can't write the above code

**Comment by iRoachie** [comment]
Ohh my bad I did not understand you at all. Yea it's missing from the definitions. I guess if you want to add it you can add it at the bottom here https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L1750

**Comment by wxlittle** [comment]
May I know if you have solved this issue? @AdrianoRuberto

**Comment by AdrianoRuberto** [comment]
@wxlittle @iRoachie I'll write a PR during this week, didn't have the time before.

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
