### ISSUE TITLE
Input - Property 'autoCorrect' does not exist on type

### ISSUE THREAD

**Issue by Ken-Lim** [react-native-training/react-native-elements#1321]
On 1.0.0-beta5, using 'autoCorrect' props for **Input** component produced a TypeScript error.

Based on the documentation at https://react-native-training.github.io/react-native-elements/docs/input.html, It says:

> This component inherits all native TextInput props that come with a standard React Native TextInput element

Pretty sure 'autoCorrect' is a valid prop for **TextInput**, but it is not recognised by the **Input** component.

**Comment by iRoachie** [comment]
What's the error it shows? It's working in my local typescript projects. It should be extended from TextInputProperties.

https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L692

**Comment by Ken-Lim** [comment]
This is the error I got:
Property 'autoCorrect' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Input> & Readonly<{ children?: ReactNode; }> & Rea...'

Am I doing something incorrectly? 
Below is my sample code:
`
<Input
    label="Username"
    autoCorrect={false}
    autoCapitalize={'none'}
    multiline={false}
/>
`

**Comment by iRoachie** [comment]
Can you link your project, I don't understand why this should fail for you

**Comment by Ken-Lim** [comment]
False alarm, I blew away the node_modules folder and run yarn again.
It is all good now.
Sorry for the trouble.
