### ISSUE TITLE
placement="left" not working when using custom components for Header

### ISSUE THREAD

**Issue by naiduprakash** [react-native-training/react-native-elements#1322]
**version : react-native-elements@1.0.0-beta5**

```
<Header
  placement="left"
  leftComponent={<MyCustomLeftComponent />}
  centerComponent={<MyCustomCenterComponent />}
  rightComponent={<MyCustomRightComponent />}
/>
```

**Comment by martinezguillaume** [comment]
This [pr](https://github.com/react-native-training/react-native-elements/pull/1221#discussion_r206594716) will fix this problem !

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
