### ISSUE TITLE
Strange Button behavior inside flexDirection: column View.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [react-native-training/react-native-elements#1324]
**Explain what you did**

Display a full-width button inside a view with `flexDirection: 'column'`.

**Expected behaviour**

That it would be possible.

**Describe the bug**

It's not possible from all the many tricks I've tried.

**To Reproduce**

https://snack.expo.io/BkunwEBEm

**Possible Solution**

The only workaround was to wrap that particular button in another `View` that had `flexDirection: row`.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |

**Comment by iRoachie** [comment]
Is this what you're trying to do? https://snack.expo.io/Sy17AuS4Q

**Comment by AndrewSouthpaw** [comment]
Close. I also specifically want other components to be centered, so the View also has `justifyContent: center` and `alignItems: center`. Like so: https://snack.expo.io/rkCbRIP4X

**Comment by iRoachie** [comment]
Here you go, https://snack.expo.io/Bywz6vD47

**Comment by AndrewSouthpaw** [comment]
Wow, that was so simple, I'm embarrassed I didn't try that combination. I saw so much other "full width button discussions" that involved the `flex: 1` but it seems to have caused the problem. Thank you for the help!
