### ISSUE TITLE
Name prop for FormInputs

### ISSUE THREAD

**Issue by giacomocerquone** [react-native-training/react-native-elements#1325]
**Is your feature request related to a problem? Please Describe.**
Using a FormInput (or TextInput) I don't have the possibility to use a name prop. This is an unbelievable native missing feature and an opportunity for react-native-elements to integrate this thing.

**Describe the solution you'd like**
I'd like to be able to get somehow through onChange (overriding the native method maybe?) the name of the FormInput that spawned the event.

**Additional context**
I give you my usual context:

I have a form with 10 values.
The container components maintain the internal state and pass down to the presentational 10 setMethods to set the respective values in the container state (they need to be ten right because we can't use a name prop to distinguish which one fired the change text event)

**Comment by xavier-villelegier** [comment]
@giacomocerquone I agree, I often do a custom wrapper to avoid having too many `onChange` functions for each input. This can be a nice enhancement. If anyone wants to tackle this issue, feel free to submit a PR 👍

**Comment by giacomocerquone** [comment]
I'll happily submit it, assign it to me! I'll write it asap

**Comment by xavier-villelegier** [comment]
Awesome, you rock ! 🎸

**Comment by iRoachie** [comment]
Even though I get what you're saying. I'm wondering why you don't pass back up an object. This is a pattern that's used on web as well.

```js
// Container

...
updateValue = data => {
  this.setState(data)
}
...


// Children
<Input value={this.state.email} onChangeText={email => this.updateValue({ email })} />

<Input value={this.state.name} onChangeText={name => this.updateValue({ name })} />

```

Am i misunderstanding your use case?

**Comment by giacomocerquone** [comment]
This is not much different than what we are doing. It's true though that you pass one function from the container to the presentational, but in this way you cannot avoid to define a new function at every render (and that is expensive in a large application I'm maintaining). Then to solve this you would define multiple function inside a presentational component and that's something you don't wanna do usually because:

1. you've got something like 50% faster components through babel transpiler when you're using a functional component
2. you're introducing some kind of logic in a pres. comp. and you don't want that

**Comment by iRoachie** [comment]
Not disagreeing with you, just wanted to get your use case. Technically your argument could hold for any **controlled** component. Should we add name props to all of them?

**Comment by giacomocerquone** [comment]
I'd say yes, it should hold for any controlled component since it's a react native lack.
React native core team is well known to be really slow on reviewing and accept pull requests and I'm saying this because it is something should be ported there. So if you ask me, no it shouldn't  be added everywhere since this is an anomaly, but in the main and most used controlled components and push for approval on react native core. If we don't succeed there we can think to add this everywhere.

Ps. You could even disagree with me and I'd still be fine :D as long as everything stay polite! We're just doing what we love.
