### ISSUE TITLE
Icon component showing up as ? when published in XCode

### ISSUE THREAD

**Issue by cngodles** [react-native-training/react-native-elements#1328]
"react-native": "^0.55.2",
"react-native-elements": "^0.19.1",

**Explain what you did**
Tried to show an icon using the Icon Component.
https://react-native-training.github.io/react-native-elements/docs/icon.html

**Expected behaviour**
Shows an icon

**Describe the bug**
Icon shows up as a square with rounded corners with a question mark inside. The icons display fine when displayed using the Expo app on iPhone.

Not full source, but how I imported and used it:

```
import { Icon } from 'react-native-elements';

<Icon name="menu" />
```

**Comment by iRoachie** [comment]
Expo bundles the icon files by default. if you're on a project that uses `react-native init myApp` you have to go through the linking process for fonts.

![screen shot 2018-07-27 at 9 45 36 am](https://user-images.githubusercontent.com/5962998/43324322-d5134962-9181-11e8-90f6-f83796de16b7.png)

**Comment by cngodles** [comment]
Excellent, this is what I was looking for. I'll have to wait until tonight to test it when I get back into XCode.

**Comment by xavier-villelegier** [comment]
Closing this as inactive. Feel free to ping us if it's still an issue

**Comment by cngodles** [comment]
Sorry, I did go ahead and test this. It worked great! However, I started publishing with Expo, which already had the icons linked. Thank you for the help.
