### ISSUE TITLE
Is that possible to set background color to Card element title?

### ISSUE THREAD

**Issue by supunlakmal** [react-native-training/react-native-elements#1329]
I need help with Card Card element title background color .
I try  using  this  code  but  no  luck.

`<Card  titleStyle={[styles.thinkMinTextTitle , robotoWeights.light]}
  title='Think a minute!'></Card>`  

and  this  is  my  styles  code  
`const styles = StyleSheet.create({     thinkMinTextTitle:{  backgroundColor:'#32cb00'  }});`

Thanks

**Comment by xavier-villelegier** [comment]
@supunlakmal Actually you can't simply specify a background color because this is a simple text, but you can easily specify your own title component by doing this

```jsx
<Card
  title={
    <View style={{ backgroundColor: 'red', padding: 12 }}>
      <Text>Custom title</Text>
    </View>
  }
/>
```

[Here is a simple Snack example](https://snack.expo.io/ryCrn-qN7)

**Comment by iRoachie** [comment]
Just to add what @xavier-villelegier said, the style properties on the `Text` component from react-native don't include `background-color`, so that's why you have to use a `View`.

https://facebook.github.io/react-native/docs/text#style

**Comment by supunlakmal** [comment]
ok  ok I got  it Thanks  @xavier-villelegier  , @iRoachie

**Comment by RonanFelipe** [comment]
I was trying to set a background color for a card. Is that possible?

**Comment by iRoachie** [comment]
@RonanFelipe can use `wrapperStyle`

**Comment by RonanFelipe** [comment]
@iRoachie I just tried it and it only changed the title background.
`wrapperStyle={{ backgroundColor: 'pink' }}`
I was looking for something to change the color of the whole card.

**Comment by msevestre** [comment]
@RonanFelipe have you tried `containerStyle`? This is what I am using for this purpose

**Comment by iRoachie** [comment]
Try `containerStyle`. https://snack.expo.io/@roach_iam/mad-beef-jerky

**Comment by RonanFelipe** [comment]
Ohhh thank you guys!!! It worked with containerStyle.
