### ISSUE TITLE
InnerButtonStyle of ButtonGroup

### ISSUE THREAD

**Issue by StanislavVoronov** [react-native-training/react-native-elements#1330]
**Is your feature request related to a problem? Please Describe.**
InnerButtonStyle props i can set only color and borderRightWidth(borderLeftWidth).
I need opportunity to control width of whole buttonGroup. I need control flex.

**Describe the solution you'd like**
 It may be fullWidht props.  In picture, I remove flex from style.button of Component.

**Describe alternatives you've considered**
There are none.

<img width="632" alt="screen shot 2018-07-28 at 16 29 11" src="https://user-images.githubusercontent.com/20968322/43357024-e0ac151c-9283-11e8-9649-93b6c2d74633.png">

**Comment by StanislavVoronov** [comment]
I need width which will be equal content.

**Comment by xavier-villelegier** [comment]
Hey @StanislavVoronov sorry for the inactivity. Did you finally do what you want ?
Actually I think that the actual styles doesn't allow you to do what you want, as it ensures that all buttons have the same width. This implies using `flex: 1` for each `Button`

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
