### ISSUE TITLE
unable to build release apk after installing rn-elements

### ISSUE THREAD

**Issue by SreevatsaAcharya** [react-native-training/react-native-elements#1332]
/res/merged/release/drawable-mdpi/node_modules_reactnativeelements_src_rating_images_bell.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

> Task :app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

tried enableaapt2=false but it's going to be deprecated and latest build tools do not allow to use it.

| software | version |
| -- | -- |
| react-native-elements |0.19.1 |
| react-native |0.55.4 |
| npm or yarn |npm 5.3.0 |

**Comment by xavier-villelegier** [comment]
@SreevatsaAcharya This is a known issue on React Native but it's not strictly related to `react-native-elements`. You will have this issue with any module that has image resources. I have a project with `react-navigation` with the same error (https://github.com/react-navigation/react-navigation/issues/1976), I had to add `android.enableAapt2=false` in the `gradle.properties` file.

Feel free to ping us if you find another solution though

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
