### ISSUE TITLE
Remove default Button title

### ISSUE THREAD

**Issue by StanislavVoronov** [react-native-training/react-native-elements#1334]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I want to display icon in button without text. 

**Expected behaviour**
Icon display without text. I do it, because I need ref of element. Icon does not have it, because it is stateless component. 

**Describe the bug**
When button does not have text prop, but have icon. The default text of react native elements is visible. 

Example:

<Button icon = {<Avatar source = {{uri: someIcon}} />} />

**Possible Solution**
Set defaultProps title to empty text

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements  | 1.0.0-BETA5
| react-native | 0.56
<img width="547" alt="screen shot 2018-07-29 at 10 37 46" src="https://user-images.githubusercontent.com/20968322/43364112-9dd823cc-931c-11e8-925e-6ba656afee90.png">

| npm or yarn | |

**Comment by methodbox** [comment]
Did this actually get fixed? I create a button with no title prop and it fills it with "Welcome to React Native Elements" - it's unusable like this.

There's plenty of Material examples showing rounded buttons with just an icon, yet that seems to be missing here.

**Comment by iRoachie** [comment]
It’s been fixed for the 1.0.0 milestone. 1.0.0 hasn’t been been released as yet but the fix is on the `next` branch with other changes that will be apart of the next release.

If you want to remove the title you can simply set `title={null}`. Sorry for the confusion
