### ISSUE TITLE
Indicate compatibility with react-native-vector-icons 5.x

### ISSUE THREAD

**Issue by LinusU** [react-native-training/react-native-elements#1335]
**Is your feature request related to a problem? Please Describe.**
Currently `npm` complains about unmet peerDepedency when using `react-native-elements@beta` together with `react-native-vector-icons@5.x`.

**Describe the solution you'd like**
I don't think that any of the breaking changes are affecting us, so we should be able to update the `peerDependecy` to accept both 4.x and 5.x.

**Describe alternatives you've considered**
We could potentially bump it to only accept 5.x, to get people to upgrade quicker.

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
