### ISSUE TITLE
Control margin

### ISSUE THREAD

**Issue by darionato** [react-native-training/react-native-elements#1337]
I just need to now how much is the control's margin. I need to know how exactly it is because adding external controls I have to align them at the same distance from the screen border.
Thanks

**Comment by iRoachie** [comment]
Which component(s) are you referring to?

**Comment by darionato** [comment]
FormLabel or FormInput

**Comment by iRoachie** [comment]
FormLabel is here https://github.com/react-native-training/react-native-elements/blob/stable/src/form/FormLabel.js#L43

FormInput is here https://github.com/react-native-training/react-native-elements/blob/stable/src/form/FormInput.js#L132

**Comment by darionato** [comment]
Perfect, thank you
