### ISSUE TITLE
Style to wrap checkbox label icon to stack them vertically

### ISSUE THREAD

**Issue by devth** [react-native-training/react-native-elements#1339]
Does the Checkbox expose a style prop I could use to wrap a checkbox and its label like this?

![image](https://user-images.githubusercontent.com/86107/43469327-24bb97ac-94a3-11e8-9596-eaf440078828.png)

**Comment by iRoachie** [comment]
What version of react-native-elements are you using?

**Comment by devth** [comment]
`0.19.1`

**Comment by iRoachie** [comment]
There's no way to do this right now with `CheckBox`. To be able to do this, we'd have to expose a `wrapperStyle` prop to control the `flex-direction`. https://github.com/react-native-training/react-native-elements/blob/stable/src/checkbox/CheckBox.js#L60

**Comment by devth** [comment]
Ok, thanks. Is this something you'd consider exposing?

**Comment by iRoachie** [comment]
Yea definitely! If you're willing to make a PR to add it, that would be awesome. Make sure your PR is based from `next` though

**Comment by devth** [comment]
Got it. I'll see what I can do!

**Comment by devth** [comment]
Hey @iRoachie, how's this? https://github.com/react-native-training/react-native-elements/pull/1348

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!

**Comment by devth** [comment]
Awesome, thanks!!
