### ISSUE TITLE
Add label props for label input

### ISSUE THREAD

**Issue by msevestre** [react-native-training/react-native-elements#1341]
Similar to `ListItem` where we can define specific props for title, rightTitle etc via the corresponding props, I'd like to propose the addition of `labelProps` for the `Input` component.

To be consistent, one could consider also adding an `InputProps` for the actual InputText but this is somewhat already (implicitly) available with the [attributes](https://github.com/react-native-training/react-native-elements/blob/d4da856a7f105c814cc162e507b48c49399cabef/src/input/Input.js#L98) props already 

I am going to submit a PR for that.

**Comment by iRoachie** [comment]
Sounds like a good idea.

**Comment by msevestre** [comment]
@iRoachie I am a bit puzzled with the changes in the next branch compared to master
if you look at https://github.com/react-native-training/react-native-elements/blob/next/src/list/ListItem.js#L110,  the `next` branch now calls the helper `renderText` instead of `renderNode` previously

However renderText does not pass along the props anymore!!
```
const renderText = (content, defaultProps, style) =>
  renderNode(Text, content, {
    style: [style, defaultProps && defaultProps.style],
  });
```

so unless I am mistaken, those `defaultProps` are completely ignored. 

This is the master implementation in 
```
const renderNode = (content, props, style) =>
  content == null ? null : React.isValidElement(content) ? (
    content
  ) : (
    <Text {...props} style={[style, props && props.style]}>
      {content}
    </Text>
  );
```

Do you concur that something is quite off?

**Comment by msevestre** [comment]
it should be 
```
const renderText = (content, defaultProps, style) =>
  renderNode(Text, content, defaultProps, {
    style: [style, defaultProps && defaultProps.style],
  });
```

**Comment by msevestre** [comment]
going to fix that in my PR too :)

**Comment by msevestre** [comment]
actually it should probably be another PR so that it's easier to track.

**Comment by iRoachie** [comment]
I'm not too sure of the implementation off my head, but @martinezguillaume is the one who usually deals with the ListItem

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
