### ISSUE TITLE
ListItem: xxxProps for text component are ignored

### ISSUE THREAD

**Issue by msevestre** [react-native-training/react-native-elements#1343]
see description in https://github.com/react-native-training/react-native-elements/issues/1341#issuecomment-409363792

Problem was introduced with following commit
https://github.com/react-native-training/react-native-elements/commit/f8af41c1959625c1d3679a88ad9437059abe39aa

**Comment by iRoachie** [comment]
Fixed in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
