### ISSUE TITLE
leftAvatar isn't a propType for <ListItem />

### ISSUE THREAD

**Issue by nicer00ster** [react-native-training/react-native-elements#1345]
Hey I just installed react-native-elements, and I have to say, this is awesome! I did notice while checking out the docs within ListItem [https://react-native-training.github.io/react-native-elements/docs/listitem.html](url)
that the leftAvatar prop for the <ListItems /> component doesn't work. At least not for me, not sure if it's a known issue. I did do a search and didn't see anything related.

I ended up just passing avatar={{  uri: li.avatar_url }} and roundAvatar as props and it works. 😄

**Comment by iRoachie** [comment]
Which version of react-native-elements are you using?

**Comment by nicer00ster** [comment]
@iRoachie "react-native-elements": "^0.19.1"

**Comment by nicer00ster** [comment]
Hmmm weird whatever link I went to brought me to beta 1.0.0 which is the link above. My bad!
