### ISSUE TITLE
default Badge from the docs is incorrectly displayed

### ISSUE THREAD

**Issue by PavelPolyakov** [react-native-training/react-native-elements#1349]
**Explain what you did**
I just want to insert `Badge` from [the docs](https://react-native-training.github.io/react-native-elements/docs/badge.html)

**Expected behaviour**
I see the nice tiny badge

**Describe the bug**
I see the big wide non-badge

**To Reproduce**
https://snack.expo.io/BysYWxZrm

It was partially touched here: https://github.com/react-native-training/react-native-elements/issues/478 , but I did not find any resolution

**Screenshots**
![image](https://user-images.githubusercontent.com/839290/43611186-a271f19e-96a8-11e8-9dbe-e0db48b91d42.png)

**Your Environment (please complete the following information):**

I've tried both `0.19` and `beta5`

Regards,

**Comment by iRoachie** [comment]
The badge like most of our components, take up the all of the available space of the parent. To have a badge like an example shown in the docs, you have to either:
- control the width from the parent
- use a flex style on the parent such as `align-items` or  `justify-content`

https://snack.expo.io/BJ6F51zrm

**Comment by PavelPolyakov** [comment]
@iRoachie Thanks for the answer and example.
I thought that the default behaviour of the badge is to have min size, like  I experienced it in the html frameworks (bootstrap).

**Comment by iRoachie** [comment]
Yea i definitely understand. It’s probably something we should look into doing. However the layout system on mobile has a lot of differences than web
