### ISSUE TITLE
According PR 759 support for react-native-web was added. However using latest release i'm running into multiple "Module Parse Failed" errors

### ISSUE THREAD

**Issue by futrespec** [react-native-training/react-native-elements#1354]
ERROR in /Users/dmenace/Documents/projects/apollo-universal-starter-kit/node_modules/react-native-elements/src/list/List.js
Module parse failed: Unexpected token (8:36)
You may need an appropriate loader to handle this file type.
| 
| const List = props => {
|   const { children, containerStyle, ...attributes } = props;
|   return (
|     <View
 @ /Users/demenace/Documents/projects/apollo-universal-starter-kit/node_modules/react-native-elements/src/index.js 4:0-31
 @ ./src/modules/news/components/Article.js
 @ ./src/modules/news/App.js
 @ ./src/modules/news/containers/News.jsx
 @ ./src/modules/news/index.web.jsx
 @ ./src/modules/index.js
 @ ./src/app/Main.jsx
 @ ./src/index.tsx
 @ multi raf/polyfill babel-polyfill webpack/hot/dev-server webpack-dev-server/client?http://localhost:3000/ ./src/index.tsx

Has the PR 759 or RN Web Branch been merged with master? Are there any sample projects that can be used as a reference to setup the correct babel loaders, presets and/or webpack.config.js?

I been at this for 36 hours trying to get react-native-elements to load on react-web to no avail. Any help would be greatly appreciated.

Thanks

**Comment by iRoachie** [comment]
Hey @futrespec, we didn't go ahead with publishing support for react-native-web. You can check the thread here https://github.com/react-native-training/react-native-elements/pull/867#issuecomment-365653062

**Comment by futrespec** [comment]
@iRoachie thanks for responding. You saved me from going further down this rabbit hole. I would definitely recommend getting this merged in when the team believes it to be stable.

For anyone else who sees this thread and is having similar issues, I was able to get past the hurdle using sample project created by @MillerGregor.

https://github.com/MillerGregor/rne-cross-platform-example

If you follow the webpack config in config-overrides.js and use the .babelrc as a reference, you should be able to get react-native-elements to load on the web.

**Comment by iRoachie** [comment]
Thanks for posting that! Sure it'll be super helpful for those trying a similar setup. Next time don't wait 36 hours to submit an issue :P
