### ISSUE TITLE
Keep showing cancel button even when search bar not in focus

### ISSUE THREAD

**Issue by chetanparakh** [react-native-training/react-native-elements#1356]
Currently I can only see cancel button when I click on search bar. Is there any option by which I could keep showing the cancel button even when search bar is not in focus?

<img width="391" alt="screen shot 2018-08-08 at 1 58 48 pm" src="https://user-images.githubusercontent.com/18354984/43855340-4253f914-9b13-11e8-9d38-5499e9ca5d05.png">

<img width="380" alt="screen shot 2018-08-08 at 1 59 07 pm" src="https://user-images.githubusercontent.com/18354984/43855341-42612f58-9b13-11e8-940b-4edc9ba71efe.png">

**Comment by iRoachie** [comment]
It's not possible at the current moment but sounds like a good feature to have.

**Comment by iRoachie** [comment]
Will leave it open so we know it's something to work on

**Comment by chetanparakh** [comment]
@iRoachie do you know of any workaround for this?

**Comment by chetanparakh** [comment]
@iRoachie 
Can you suggest any work around to this.
When i am on this page, I want to place the cursor directly on the search bar so that the user does not have to press on the search bar to bring up the keyboard.

**Comment by iRoachie** [comment]
If it's to only place the cursor on the search bar, you can focus the search bar when the component mounts. 

See https://snack.expo.io/BJc_9Tprm

**Comment by xavier-villelegier** [comment]
For now the idea is to have the same behavior as the iOS SearchBar.

![sep-14-2018 09-46-28](https://user-images.githubusercontent.com/17592779/45537041-832d5900-b803-11e8-8aa5-16b38e766375.gif)

We'll first focus on being more similar to the official SearchBar, and then add some new features. Hope you understand !
