### ISSUE TITLE
[CheckBox] Need Help. Bugs Or Not ? Correct me if i'am wrong please.

### ISSUE THREAD

**Issue by rendy14s** [react-native-training/react-native-elements#1358]
Hallo developers,

i have issue with checkbox from react-native-elements. i have checkbox, if any data, thats value is true, so the checkbox is checked. i have video for demo : 

Note: Cant upload video, so i created in ZIP, if any request video upload in youtube just comment thanks.

[Demo.zip](https://github.com/react-native-training/react-native-elements/files/2271883/Demo.zip)

and the code here : 

1.  `<CheckBox
       containerStyle={{ backgroundColor: 'transparent', borderColor: 'transparent', height: 0 }}
      checked={this.state.dataCheckBoxSubMaterial.includes(itemSubMaterial)}
      onPress={() => this.checkedSubMaterial(itemSubMaterial)}
/>`

2. `checkedSubMaterial(data) {
        const { dataCheckBoxSubMaterial } = this.state;
        if (!dataCheckBoxSubMaterial.includes(data)) {
            this.setState({
                dataCheckBoxSubMaterial: [...dataCheckBoxSubMaterial, data]
            });
        } else {
            this.setState({
                dataCheckBoxSubMaterial: dataCheckBoxSubMaterial.filter(a => a !== data)
            });
        }
    }`

3. `componentDidMount() {
if (this.props.navigation.state.params.dataSub) {
            this.setState({ dataCheckBoxSubMaterial: this.props.navigation.state.params.dataSub })
        }
}`

**Comment by iRoachie** [comment]
Hey! I see your video, and I see the problem that's happening, however, it's hard to determine what the issue is from just watching the video. Can you reproduce any part of this on https://snack.expo.io?

**Comment by rendy14s** [comment]
Hello @iRoachie , Thanks for your response, i will reproduce in snack, and i will share the link . thank you

**Comment by rendy14s** [comment]
Hallo, @iRoachie , this is link for snack reproduce, thanks very much :)

https://snack.expo.io/@rendy14s/demo

**Comment by iRoachie** [comment]
I can't understand what's happening from your snack. What should I be looking for?

**Comment by rendy14s** [comment]
If you see in the second page.
1. I render the first data in combo box.
2. And i choose ex : "Baja"
3. And the second data will render for the checkbox.
4. And you can checked the data, data you checked will show in the top under titleHeader.
5. And you change the combo, ex : "Benang" or else,
6. And the other data will render . And you checked again. 
7. Now you have 2 data checked. And show on top.
8. Back again on combo box and choose "Baja" again (No. 2), and what you checked data fisrt, is not checked. Actually is it checked right?

In other case :
You choose 1 data checked. And back again on first page, and add again to second page and see the data you have checked is not checked again right?

**Comment by iRoachie** [comment]
Thanks for clarifying. I've watched the video again and read your steps. What I'm seeing here is really a problem of state management and not with the CheckBox component. 

Even though we sometimes help out with some general questions; it's often best for issues to be related to bugs with components in react-native-elements and suggestions for improvements. I suggest you raise your question on StackOverflow, or maybe head to Reactiflux or our [slack group](https://reactnativetraining.herokuapp.com), where you can possibly get one on one help with your solution.
