### ISSUE TITLE
I want to customize the image to be displayed using the checkbox component, but the '?' Font is displayed.

### ISSUE THREAD

**Issue by okayu8** [react-native-training/react-native-elements#1359]
I would like to use the checkbox component and display the image on the check part.
So I set the Image component in the properties of 'checkedIcon' and 'uncheckedIcon'.
 As below.

```
<CheckBox
    checked={this.state.checked}
    center
    containerStyle={styles.checkStyle}
    checkedIcon={<Image
                                  style={{ width: 16, height: 16, margin: 8, }}
                                  source={require('../images/checked.png')}/>}
    uncheckedIcon={<Image 
                                   style={{ width: 16, height: 16, margin: 8, }} 
                                   source={require('../images/unchecked.png')} />} 
     onPress={() => this.setState({
                        checked: !this.state.checked
                    }
                    )}
                />
```

But that does not work as expected. '?' Font icon will be displayed.

Do you know how to do it to display the image?

**Comment by okayu8** [comment]
@iRoachie 
Thank you for your reply!
We were able to set up components by installing v1.0.0@beta.

Thank you very much!

**Comment by shiftrtech** [comment]
Hi, is there a date when this gonna be on a stable release, (i dont want to use a beta on my production app), thanks.

**Comment by dasoga** [comment]
Hey for me it worked something like this:

```
checkedIcon='check-square'
checkedColor='white'
```
