### ISSUE TITLE
"SyntaxError: Invalid or unexpected token" while testing component with jest & enzyme

### ISSUE THREAD

**Issue by Ashniu123** [react-native-training/react-native-elements#1360]
I was using jest to test my react-native application and while testing the only components which use react-native-elements, I ran into this error and can't figure out a workaround.

**Expected behaviour**
Test cases should pass.

**Describe the bug**
Test suite failed to run. I have not used the *rating* image anywhere as per the error log

    E:\Workspace\React-Native\todo_list\node_modules\react-native-elements\src\rating\images\star.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/react-native-elements/src/rating/Rating.js:39:18)
      at Object.<anonymous> (node_modules/react-native-elements/src/index.js:58:15)`

My test case is as simple as this (modified to match the snack link below)
```
import React from 'react';
import { shallow } from 'enzyme';

import { AssetList } from './AssetList';

test('should render AssetList component correctly', () => {
	const wrapper = shallow(<AssetList />);

	expect(wrapper).toMatchSnapshot();
});
```

**To Reproduce**
This snack is not exact as my app as it uses redux & realm but is 99% same. I have put comments where data is actually coming from redux. Though during test cases, I am not using the *connected* react-redux component.

https://snack.expo.io/BJ72SlcHX

**My Environment:**

| software | version |
| -- | -- |
| react-native-elements | 0.19.1|
| react-native | 0.55.4|
| npm or yarn | 6.3.0|
| jest | 23.1.0|
|enzyme|3.3.0|

**Comment by Ashniu123** [comment]
Found solution [here](https://github.com/facebook/jest/issues/2663). Basically we have to mock the files.

**Comment by iRoachie** [comment]
Thanks for sharing!
