### ISSUE TITLE
Adding additional params to  Rating component callback

### ISSUE THREAD

**Issue by spiro-stathakis** [react-native-training/react-native-elements#1363]
I would like to render multilple Rating components as part of a ListItem within a SlideDeck. However the callback  accepts only a single param: rating and does not allow me to specify which instance of the Rating component has triggered the callback.  

It would be great if you permitted overloaded callback or if the function simply accepted the rating as one parameter and a object as another (default to null). I could then put whatever I want in the object and so could every one else. 

I have looked at using other components that don't specify the interface of the callback but I would rather use one library that bundles many components than use many libraries only offering a single component. This mainly for maintenance reasons. 

Thanks !

**Comment by iRoachie** [comment]
Hey, would like to help if I could. When you said the callback accepts only a single param, which component are you referring to?

**Comment by spiro-stathakis** [comment]
Hi Kyle,

Thanks for the response. The component I am referring to is the Rating
component which can be found here:
https://react-native-training.github.io/react-native-elements/docs/rating.html

Best wishes,

Spiro

**Comment by iRoachie** [comment]
Which example are you referring to? I'm trying to get an idea of what you're trying to do

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
