### ISSUE TITLE
CheckBox doesnt change fontFamily 

### ISSUE THREAD

**Issue by rendy14s** [react-native-training/react-native-elements#1368]
Description

1.  I am trying to change fontFamily of CheckBox
2. I expect fontFamily to change
3. It doesn't change
4. But if the fontSize, and color is change, etc.

i'am look this post : 
https://github.com/react-native-training/react-native-elements/issues/788

Version : 
"react-native-elements": "^0.19.1"

in Other case my issue doesnt reply : 
https://github.com/react-native-training/react-native-elements/issues/1358

![1](https://user-images.githubusercontent.com/10143804/44059587-13654d98-9f7c-11e8-9af4-caf981c778ae.PNG)
![2](https://user-images.githubusercontent.com/10143804/44059588-1395b6ae-9f7c-11e8-95b7-03c11b640f6b.PNG)
![3](https://user-images.githubusercontent.com/10143804/44059589-13c7e854-9f7c-11e8-853a-1023aa64dfc9.PNG)

**Comment by iRoachie** [comment]
Hey @rendy14s this is usually an issue with linking of fonts. Does the custom font work in other components such as built-in react-native Text component?

**Comment by rendy14s** [comment]
@iRoachie yes, i change the other component its work, but not in checkbox react-native-elements,
ex : i have a draw circle of blue in top capture, its work

**Comment by iRoachie** [comment]
@rendy14s This may be an issue with how you are linking your fonts. Here's an example snack with `fontFamily` working as expected https://snack.expo.io/Hk-s98OIm

**Comment by rendy14s** [comment]
Theres no issue in my linking font. Because my component else is working perfectly. What version react-native-elements you are?

**Comment by iRoachie** [comment]
The example I posted was 0.19.1

**Comment by rendy14s** [comment]
i will try it again, and i will repost in here again. thanks @iRoachie

**Comment by rendy14s** [comment]
Hahahaha... until now i am not resolved this issued, and dont know why.
package version same with you : `"react-native-elements": "0.19.1",`  💃

**Comment by iRoachie** [comment]
I'm not sure I can help if I can't replicate the bug

**Comment by rendy14s** [comment]
Oke thanks you for reply my issue @iRoachie 
May be i will close this issue. And i will try it again later. And i will info in this thread for how thats can be work. Thank you very much @iRoachie

**Comment by LimAlbert** [comment]
Had the same issue, I don't know if it's gonna work for you or someone else but setting fontWeight to "normal" did the trick !

**Comment by ironworkshop** [comment]
@LimAlbert that is the fix thanks for that, I had the same issue and the font-weight solved it.

**Comment by anantaramdas** [comment]
@LimAlbert Thanks worked for me too - I put it into textStyle property

**Comment by TheDistanceHQ** [comment]
This worked a treat @LimAlbert and @anantaramdas! Thank you :)
