### ISSUE TITLE
Cannot get CheckBox to update from state var

### ISSUE THREAD

**Issue by billtlee** [react-native-training/react-native-elements#1369]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

0.19.1

**Explain what you did**
I have a list of checkboxes and I am trying to get the checkboxes to change state.  The checked property is based on a state variable.  I don't understand what I am doing wrong.  Any help will be greatly appreciated!

**Expected behaviour**
When I click on the checkbox, the checkbox should toggle.

**Describe the bug**
I am not sure this is a bug.  Probably me not knowing how to get it to work.

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

I have created a snack at https://snack.expo.io/@billtlee/checkbox-test

**Your Environment (please complete the following information):**
Macbook Pro

    "react": "16.2.0",
    "react-native": "0.54.0",
    "react-native-camera": "1.0.1",
    "react-native-elements": "^0.19.1",
    "react-native-modal": "5.2.0",
    "react-native-permissions": "1.1.1",
    "react-native-qrcode-svg": "5.0.6",
    "react-native-sensitive-info": "5.1.0",
    "react-native-snackbar": "0.4.6",
    "react-native-svg": "6.2.2",
    "react-native-vector-icons": "4.5.0",
    "react-navigation": "1.4.0",

yarn

**Comment by xavier-villelegier** [comment]
@billtlee Have a look at https://github.com/react-native-training/react-native-elements/issues/603#issuecomment-387719130 :)

**Comment by billtlee** [comment]
@xavier-villelegier thanks for the reply!  Are you suggesting that I need to wrap the checkboxes in flatlist and include extraData?

**Comment by billtlee** [comment]
I copied the code and used flatlist and got it to work.  Thanks.
