### ISSUE TITLE
Searchbar Add Icon and Handler

### ISSUE THREAD

**Issue by darioajr** [react-native-training/react-native-elements#1370]
I need to include the Searchbar in a new screen with the navigation icon to go back to the previous screen, and also include in the Searchbar component two more icons on the right, one with the save search option and the other with the option to open a option pickers to filter the list.

In short, add icons to the right and capture an event when the icons are clicked.

**Comment by iRoachie** [comment]
Don't think we're going forward with this right now. This might a bit too specific for a searchbar component. If anything you can create your own component which wraps the searchbar and adds your extra functionality.
