### ISSUE TITLE
access to header via ref

### ISSUE THREAD

**Issue by codex7** [react-native-training/react-native-elements#1382]
how can access to header via "ref" ?
i want to animated the text(fade in, fade out) when user scroll the view, such as image below:

https://user-images.githubusercontent.com/7143583/28991088-f617b5e4-7940-11e7-92ca-ca14ba6b4d5d.gif

**Comment by iRoachie** [comment]
Why do you need a ref to do this? Can't you set the props when the scroll position changes?
