### ISSUE TITLE
How to display a sidemenu ?

### ISSUE THREAD

**Issue by cullsin** [react-native-training/react-native-elements#1387]
Hi, 
Can you please suggest me how do I display sidemenu ?  The sidemenu component is not listed in the recent version. How do I configure with Header menu element.

Thanks,
Raja K

**Comment by iRoachie** [comment]
There's no Sidemenu component in react-native-elements. If you want to implement a sidemenu or "drawer" as it's called - you can check react-navigation https://reactnavigation.org/docs/en/drawer-based-navigation.html.

**Comment by DavidSvetlik** [comment]
@iRoachie Any plans for it? I'm not using "react-navigation" ("react-router-native" seems as a better choice to me) and the other packages seem outdated or buggy. NativeBase has a drawer.

**Comment by iRoachie** [comment]
> Hi, any plans for it?
Not at the current moment. React navigation, or react-native-side-menu(if you don't want a nav library) handles drawers and their gestures well.
