### ISSUE TITLE
Button fontSize type documentation is wrong(v0.19.0)

### ISSUE THREAD

**Issue by UllasBC** [react-native-training/react-native-elements#1388]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I want to increase the text size in Button.

**Expected behaviour**
Currently the documentation shows type should be string but type should be in number.

**Describe the bug**
Replace type string to number in documentation(v0.19.0).
Error:-Error while updating property 'fontSize' in shadow node type:RCTText
java.lang.String cannot be cast to java.lang.Double

**Possible Solution**
Replace type string to number

**Screenshots**
![image](https://user-images.githubusercontent.com/23297395/44617396-11569500-a87f-11e8-9815-de92ca7ad761.png)

**Your Environment (please co
blob:https://web.whatsapp.com/ec273baf-76ad-4497-9c31-aaef27a79275mplete the following information):**

| software | version |
| -- | -- |
| react-native-elements |0.19.0 |
| react-native |0.55.2 |
| npm or yarn |1.9.2|

**Comment by iRoachie** [comment]
Fixed
