### ISSUE TITLE
Rendering a `ListItem` with `rightTitle` set to an empty string throws an error on Android.

### ISSUE THREAD

**Issue by tallpants** [react-native-training/react-native-elements#1391]
**Explain what you did**
Tried to render a `ListItem` on Android with `rightTitle` set to an empty string.

**Expected behaviour**
No right title renders.

**Describe the bug**
It throws:

"Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'RCTRawText[text: ]' to a 'RCTView')"

This works just fine on iOS however, the bug only occurs on Android.

**To Reproduce**
Render this:

```js
  <ListItem
    title="Something"
    subtitle="Another thing"
    rightTitle=""
  />
```
![screen shot 2018-08-27 at 11 53 17 am](https://user-images.githubusercontent.com/15325890/44643907-d45de000-a9ef-11e8-8806-25f3058f2a4a.png)

| software | version |
| -- | -- |
| react-native-elements | 0.19.0 |
| react-native | 0.56.0  |
| npm or yarn | yarn |

**Comment by iRoachie** [comment]
Fixed now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
