### ISSUE TITLE
Buttons are not able to be stretched in flexbox

### ISSUE THREAD

**Issue by pianoman730** [react-native-training/react-native-elements#1393]
I am using `react-native-elements 0.19.1`

I posted a question on [stackoverflow](https://stackoverflow.com/questions/52051069/flex-buttons-with-scrollview-react-native) because I thought this was just my own inexperience getting in the way. But I feel like it may be a limitation in the `Button` component. I want to be able to put multiple buttons in one row underneath a scrollview. However the buttons have gaps in between them. A working example is [here on snack](https://snack.expo.io/BJNEmvMvQ).

I'm not sure how to fix it or what the solution is, but I feel like the button should allow more styling on the container. Is there a way that `react-native-elements` would recommend doing this?

![image](https://user-images.githubusercontent.com/35585841/44735674-5579ad80-aaaa-11e8-96d4-b5aa8876ce1a.png)

| software | version |
| -- | -- |
| react-native-elements |0.19.1 |
| react-native |0.56.0 |
| npm or yarn | 5.6.0|

**Comment by iRoachie** [comment]
The Button has default style that includes `marginLeft: 15` and `marginRight: 15`. You only need to remove this margin and the button will display as expected.

See example here https://snack.expo.io/@roach_iam/smiling-popsicle.

**Comment by pianoman730** [comment]
@iRoachie Is there a way to make them expand to fill the available space?

**Comment by iRoachie** [comment]
Just add `flex: 1` to the group. https://snack.expo.io/@roach_iam/smiling-popsicle

**Comment by pianoman730** [comment]
Ah yes, perfect. That is exactly what I was looking for. I also tried this with `buttonStyle` instead of `containerViewStyle` and it does not perform as expected. I guess I don't understand the difference between the two. Is it something where `buttonStyle` is like the color and such of it, and `containerViewStyle` is how the container looks (e.g. border, etc.)?

**Comment by iRoachie** [comment]
Yep that's exactly it. The container is the area around the actual button. Click on the container won't fire any touch events. It's usually used to put margins to separate it from other elements on the screen.

**Comment by pianoman730** [comment]
Ok perfect. Thanks so much!
