### ISSUE TITLE
I think you should update the docs

### ISSUE THREAD

**Issue by Evangelione** [react-native-training/react-native-elements#1395]
it's too old, too simple, hard to understand, and need to look at the updated docs to understand component usage

**Comment by iRoachie** [comment]
What about the docs is hard to understand? Each component page has examples of how the component can be used. How would you improve it?

**Comment by Evangelione** [comment]
[ListItem](https://react-native-training.github.io/react-native-elements/docs/listitem.html#using-map-function-implemented-with-link-and-icon)
The code does not match the Picture. i can't see the arrow in my page,
This is a cool library. I just think the docs should be updated. After all, I am a rookie.
