### ISSUE TITLE
Last character is not going of FormInput

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [react-native-training/react-native-elements#1396]
FormInput is not clearing and there is no text on the InputField

![image](https://user-images.githubusercontent.com/25581796/44835094-a9be9200-ac50-11e8-93f9-f700cd969f0f.png)

![image](https://user-images.githubusercontent.com/25581796/44834688-80513680-ac4f-11e8-9df1-80a213077c03.png)

**Comment by iRoachie** [comment]
Could you explain your issue a bit clearer? Please use the issue template. From this I can't tell:

- What you are doing
- What you are trying to do
- What is the expected outcome

**Comment by shubham-srivastava-goku** [comment]
I am trying to clear the FormInput field using backspace. But last character is not removing from FormInput.

Expected outcome: It should remove the last character too and show placeholder.

**Comment by iRoachie** [comment]
As you see by this example that the FormInput works as expected https://snack.expo.io/@roach_iam/nervous-cookie
