### ISSUE TITLE
When used with react-navigation BottomTabNavigator, FornInput long press functionality doesn't work on android

### ISSUE THREAD

**Issue by sjsakib** [react-native-training/react-native-elements#1399]
**Explain what you did**
I'm using `FormInput` with `react-navigation` BottomTabNavigator

**Expected behaviour**
When long-pressed a `FormInput` component, a menu should appear which lets the user select text or copy/paste text .

**Describe the bug**
Long-press does nothing. The problem could be with `react-navigation`, but since pure react-native `TextInput` works fine in this case, I'm reporting it here.

**To Reproduce**

```bash
# Snack
https://snack.expo.io/@sjsakib/react-navigation-copy-paste-problem

# Steps
1. Open the snack
2. Long press the input field at the top
```

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | ^0.19.1|
| react-native |0.56.0 |
| npm |1.6.0 |
|react-navigation|^2.11.2|

**Comment by iRoachie** [comment]
Definitely a bug, same is happening on 1.0.0-beta5 Input

**Comment by Monte9** [comment]
@iRoachie isn't `FormInput` deprecated? For v1 we are using the input component right? If yes, can we remove this issue be relevant to the v1 milestone?

**Comment by iRoachie** [comment]
It happens with `Input` as well. See I said in the comment

**Comment by iRoachie** [comment]
Can't seem to replicate this issue anymore. Received similar behaviour with both React Native TextInput and our Input component.

![kapture 2019-01-20 at 23 20 34](https://user-images.githubusercontent.com/5962998/51451100-1292cd80-1d0a-11e9-8d38-79e9c41b87fb.gif)
