### ISSUE TITLE
Show header at the bottom of the screen

### ISSUE THREAD

**Issue by codex7** [react-native-training/react-native-elements#1400]
How to display a header at the bottom of the screen?

**Comment by iRoachie** [comment]
The header isn't fixed to the top it displays like any other element. https://snack.expo.io/@roach_iam/ashamed-blueberries

**Comment by xavier-villelegier** [comment]
Closing this as @iRoachie snack shows you how to do it ! You can also wrap the `Header` in an `View` with absolute positioning at the bottom.
