### ISSUE TITLE
the Haste module map

### ISSUE THREAD

**Issue by omi10859** [react-native-training/react-native-elements#1402]
react-native-elements/src/buttons/Button.js`: Module `react-native-vector-icons/MaterialIcons` does not exist in the Haste module map

```import { Button } from 'react-native-elements'```

**Comment by iRoachie** [comment]
Did you follow the [installation instructions?](https://react-native-training.github.io/react-native-elements/docs/0.19.0/getting_started.html)

**Comment by omi10859** [comment]
It's working now. Thanks for support

**Comment by mobiledevelopersprojects** [comment]
@omi10859 ,

How did you fix the problem?

Thanks.
