### ISSUE TITLE
Form Label font not change

### ISSUE THREAD

**Issue by palakvc** [react-native-training/react-native-elements#1405]
**Explain what you did**
As per [doc](https://react-native-training.github.io/react-native-elements/docs/0.19.0/forms.html#formlabel-props) I'm trying to apply fontFamily on FormLabel but It's not work.

Not able to create https://snack.expo.io Bcoz I have no idea about how to set rnpm and load font on it.

But, I already follow [custom-fonts-in-react-native](https://medium.com/@kswanie21/custom-fonts-in-react-native-tutorial-for-ios-android-76ceeaa0eb78) So, this issue not about this. Even custom fonts working well on Form Input and Form Validation Message. Just have problem with FormLabel.

**Expected behaviour**
fontFamily should update FormLabel style.

**Screenshots**
![image](https://user-images.githubusercontent.com/42599914/45010770-b8c88a00-b02c-11e8-8489-c8bc2bb129c9.png)

![image](https://user-images.githubusercontent.com/42599914/45010831-07762400-b02d-11e8-9842-2b58bcab1fb0.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 0.19.1 |
| react-native | 0.55.4 |
| npm or yarn | 5.6.0 |

**Comment by iRoachie** [comment]
This happens because custom fonts don't work along with fontWeight bold. To get it to work you'll need to add a labelStyle.

`<FormLabel fontFamily="Merriweather-Bold" labelStyle={{ fontWeight: '400' }}/>`

**Comment by xavier-villelegier** [comment]
Closing this as @iRoachie answer works well. Feel free to ping us if you still have this issue !
