### ISSUE TITLE
Allow global/local overriding of TextInput element used?

### ISSUE THREAD

**Issue by mgcrea** [react-native-training/react-native-elements#1408]
Would be nice to always be able to override the native elements used by the components:

For instance if you want to use a custom `TextInput`, in my case I wanted to try https://github.com/zackify/react-native-autofocus, which exports an HOC to the native `TextInput`. Alas, there is no way to override the `TextInput` component used by your `Input` component…

Possible API for local override:
```js
import { TextInput } from 'react-native-autofocus'
<Input inputComponent={TextInput} />
```

It is something that is already possible for the `Icon` component. Would be great to have this as well for `Input`.

Could quickly work on a PR if there is consensus.

---

Edit: looks like the Icon component no longer have an `inputComponent` prop. Only a `component` prop which will be the WrapperView used.

Looking at Button there is a `ViewComponent` prop. Looks like the API needs to be unified on this. (lowercase/camelcase, Component vs. ViewComponent`.

IMO, not fond of the `ViewComponent` upperfirst case pattern: a component isn't necessarily a class (can be a simple function).

Also it's strange that the `component` prop for the Icon does end up being the wrapper component used (and not the Icon one as expected by the API).

**Comment by mgcrea** [comment]
@iRoachie my use case was to build a `Select` component that looks like and has the same API than an `Input` component but I fake the Input as a touchable view that will present a picker on touch. Will gladly send a PR to add a `Select` when the current one is accepted.

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!

**Comment by YikSanChan** [comment]
@mgcrea Seems `Select` component effort is tracked #253
