### ISSUE TITLE
Make Android style default

### ISSUE THREAD

**Issue by piu130** [react-native-training/react-native-elements#1419]
**Is your feature request related to a problem? Please Describe.**
Currently there is no consistent style applied to components for `react-native-web` (Platform `web`), `electron` (Platform `desktop`), etc.

**Describe the solution you'd like**
We should set `android` style as default for all platforms.

**Describe alternatives you've considered**
We could set `ios` as default or create a third `default` style.

**Additional context**
Some examples:

- [Avatar](https://github.com/react-native-training/react-native-elements/blob/master/src/avatar/Avatar.js#L173) has no shadow
- Button is a bit random: [here](https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L186) and [here](https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L196) not android and [here](https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L208) and [here](https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L224) no style
- [Button](https://github.com/react-native-training/react-native-elements/blob/master/src/checkbox/CheckBox.js#L123) text is not bold
- ...

**Comment by iRoachie** [comment]
Sounds like a great idea, Can you make a PR to do this?

**Comment by iRoachie** [comment]
Also could you outline the steps you did to get react-native-web working? Would love to put it in the docs.

**Comment by piu130** [comment]
Created a PR [here](https://github.com/react-native-training/react-native-elements/pull/1421).

I use [neutrino](https://neutrinojs.org/) for the setup. Just create a new project as described [here](https://neutrinojs.org/installation/create-new-project.html) and select react.

Then add `react-native-web`, `babel-preset-react-native`, (`react-art` - is optional but for my setup it fails without it), `react-native-elements` and `react-native-vector-icons` with your package manager.

Currently you must add `.web.js` and `.web.jsx` to webpacks resolve extensions (see `.neutrinorc.js` below). But you can remove it with the next neutrino release (fixed [here](https://github.com/neutrinojs/neutrino/pull/1064)).

Then you must add the react-native modules to webpacks include (see `.neutrinorc.js` below), because webpack does not transpile `node_modules` (webpack assumes they are already transpiled).

My `.neutrinorc.js` looks like this:

```js
const { join } = require('path');

const nodeModulesDir = join(__dirname, 'node_modules')

module.exports = {
  use: [
    [
      '@neutrinojs/react',
      {
        html: {
          title: 'test'
        }
      }
    ],
    (neutrino) => {
      neutrino.config.resolve.extensions.prepend('.web.jsx').prepend('.web.js')
      neutrino.config.module
        .rule('compile')
          .include
            .add(join(nodeModulesDir, 'react-native-elements'))
            .add(join(nodeModulesDir, 'react-native-vector-icons'))
            .add(join(nodeModulesDir, 'react-native-touchable-scale'))
            .end();
    }
  ]
};
```
