### ISSUE TITLE
Buttons with only icon have different padding than buttons with text

### ISSUE THREAD

**Issue by apaatsio** [react-native-training/react-native-elements#1427]
**Explain what you did**
I tried to create multiple buttons of which some have text and some have only icon. 

**Expected behaviour**
I expected all buttons to have the same padding. It would be great if all the buttons had the same padding out of the box without having to write custom styles.

**Describe the bug**
Buttons with only icon have smaller padding (no padding?) and it makes them different size than other buttons.

**To Reproduce**
Relevant part of code:
```javascript
<Button title='' icon={{ name: 'minus', type: 'font-awesome' }} />
<Button title='RESET' />
<Button title='' icon={{ name: 'plus', type: 'font-awesome' }} />
<Button title='ADD' icon={{ name: 'plus', type: 'font-awesome' }} />
```

https://snack.expo.io/@apaatsio/petrified-chip

**Possible Solution**
Add padding to buttons that have only icon.

**Screenshots**
![react-native-elements icon buttons size diff](https://user-images.githubusercontent.com/195210/45590062-d81abd80-b930-11e8-9978-a202192308c8.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |
| expo | 30.0.0 |
| npm | 5.6.0 |

**Comment by simbirsky** [comment]
i have same problem :(

**Comment by iRoachie** [comment]
Buttons by default actually have no padding or margin. The additional padding you're seeing is from the title style https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L207.

If there's no title in the button, is there any reason you don't use the [Icon component](https://react-native-training.github.io/react-native-elements/docs/icon.html)?

**Comment by apaatsio** [comment]
Using the Icon component might be a good workaround, but I still think this is a bug/design flaw because:

1. This is not expected or standard behavior. For example, on Material UI and Bootstrap all buttons are the same height.
2. It's hard to think of a use-case where it's preferable to have *inconsistent* button sizes. I can think of many use-cases where *consistent* button sizes are required, though.

**Comment by iRoachie** [comment]
I agree with you 100%. However both Bootstrap and Material UI only use one font library, while react-native-vector-icons bundles 7+. But I do think this is something that we should work on
