### ISSUE TITLE
Different icons have different widths in ListItem

### ISSUE THREAD

**Issue by apaatsio** [react-native-training/react-native-elements#1430]
**Bug description**
Different icons have different widths when they are used in ListItem. Even icons in the same icon set can have different widths. This makes the titles of the ListItems misalign.

**Expected behavior**
All icons should be the same size by default so that the titles of the ListItems align nicely.

**Snack**
https://snack.expo.io/@apaatsio/react-native-elements---list-icon-alignment

**Screenshots**
![screenshot_20180918-115943](https://user-images.githubusercontent.com/195210/45680490-521e9280-bb3b-11e8-8e3f-cc131e092b00.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |
| expo | 30.0.0 |

**Comment by reedyrm** [comment]
I'm not sure how you can solve it effectively for everyone, but one workaround is by using a fixed width for your icons.

FontAwesome solved it [this way](https://github.com/FortAwesome/Font-Awesome/blob/v4.7.0/scss/_fixed-width.scss) in CSS land.

**Comment by apaatsio** [comment]
I'll close this since this is a react-native-vector-icons issue.

Here's essentially a duplicate issue: https://github.com/oblador/react-native-vector-icons/issues/751

**Comment by hakkikonu** [comment]
wrap your every icon with `<View>` and give absolute with to `<View>`

example:

```
<View style={{width: 20}}>
    <FontAwesome5 name={"ice-cream"} size={18} color={'#fff'} />
 </View>

<View style={{width: 20}}>
    <FontAwesome5 name={"plus"} size={18} color={'#fff'} />
 </View>

```
..

**Comment by nikdo** [comment]
@hakkikonu Setting fixed widths does not scale well when user increases font size manually. This works:

```js
const fixedWidthStyle = { fontSize: 30, aspectRatio: 1, textAlign: 'center' }
<Icon name={icon} style={fixedWidthStyle} allowFontScaling />
```
