### ISSUE TITLE
The need of using "npm install" after installing react native elements on a fresh project.

### ISSUE THREAD

**Issue by TheFirstMe** [react-native-training/react-native-elements#1434]
I am using the create-react-native-app tool for making a test project. When I try to install react native elements, I have to run "npm install" or else I am getting an error when I try to "expo start" saying that react native is not installed. Why is this happening? I don't see this anywhere in the docs.

**Comment by iRoachie** [comment]
It's the same command, that's all that's required to use this package.

**Comment by TheFirstMe** [comment]
The package works fine. It's just that I'm getting a "React native not installed" error after installing the package. I have to run npm install again. Is this normal? I also see so many warnings. I feel like something is wrong somewhere.

**Comment by iRoachie** [comment]
It's possible that create-react-native-app may have setup up the project using `yarn` instead of npm. Therefore when you ran `npm install --save react-native-elements` it removed the previous packages that were set up.

Try removing your node_modules folder and try running npm install

**Comment by TheFirstMe** [comment]
You are right. When I run the command for installing the package, it removed a lot of packages from node_modules. I never used yarn so any way to prevent this?

**Comment by iRoachie** [comment]
I think it's the default package manager for facebook projects. You may want to look at https://github.com/react-community/create-react-native-app/issues/693. I'll close this issue now since it's outside react-native-elements.
