### ISSUE TITLE
errorMessage not displaying on Android

### ISSUE THREAD

**Issue by JamesDuBois1994** [react-native-training/react-native-elements#1437]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I am trying to use the errorMessage prop to display my message on android.

**Expected behaviour**
The error message should be displaying under the input.

**Describe the bug**
The error message is displaying on ios just fine but there is no error messages being displayed on android.

**To Reproduce**
I am working on form validation. I am using "react-native-elements": "^1.0.0-beta2". Now to display my errorMessages I am using the errorMessage prop. The error message is displaying perfectly fine on ios. On android there is no message showing at all. Any clue whats going on? Below is a snippet of an input.

```    
      <Input
            containerStyle={styles.input}
            inputContainerStyle={{ borderBottomWidth: 0 }}
            placeholder={"Old Password"}
            placeholderTextColor={"grey"}
            autoCapitalize={"none"}
            errorStyle={{ color: "red", marginTop: 0 }}
            errorMessage={this.state.oldPasswordError}
            autoCorrect={false}
            returnKeyType={"next"}
            secureTextEntry
            onChangeText={text => this.setState({ oldPassword: text })}
            value={this.state.oldPassword}
            onSubmitEditing={() => this.newPassword.focus()}
          />
```
**Your Environment (please complete the following information):**

 "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-elements": "^1.0.0-beta2",

**Comment by iRoachie** [comment]
Think you may have forgotten the [`displayError` prop](https://react-native-training.github.io/react-native-elements/docs/1.0.0-beta2/input.html#displayerror). Here's an example of it working https://snack.expo.io/@roach_iam/graceful-macaroni-and-cheese

In the latest beta (1.0.0-beta5) you don't need to use the `displayError` prop. It shows whenever `errorMessage` has a value.

**Comment by xavier-villelegier** [comment]
In `1.0.0-beta6` there is no `displayError` anymore, it's displayed whenever `errorMessage` is provided.
