### ISSUE TITLE
Naming convention change for platform specific code

### ISSUE THREAD

**Issue by martinjms** [react-native-training/react-native-elements#1439]
**Is your feature request related to a problem? Please Describe.**
Current name convention for platform specific components as used in SearchBar component will compile all files regarding the platform

**Describe the solution you'd like**
This can be improved by changing the name convention as specified by react-native docs in [here](https://facebook.github.io/react-native/docs/platform-specific-code). In this way it will ship only the specific component to each platform and eliminate the need for a "base" component.

for example:
BigButton.ios.js
BigButton.android.js

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
This is also the only thing currently preventing react-native-web compatibility according to my tests

Drawbacks: Testing platform specific code will not be posible with current setup. A platform mock would be required.

**Comment by iRoachie** [comment]
The different naming convention on the SearchBar isn't for including them on a particular platform. The platform in the name only refers to the *style* of that platform.

The user is free to use the iOS styled SearchBar on Android and vice versa.
