### ISSUE TITLE
Recommended Navigation

### ISSUE THREAD

**Issue by jfrey** [react-native-training/react-native-elements#144]
Hi All,

I was wondering if there was any recommended navigation frameworks for use with your components?

**Comment by seand88** [comment]
I have been using https://github.com/aksonov/react-native-router-flux

I tried react-native-navigation from Wix, but it doesnt support current react version yet and i ran into some issues there were no solutions for.

Not sure what everyone else is using

**Comment by Nickman87** [comment]
I'm using https://github.com/exponent/ex-navigation now, as I'm also using exponent to build/run my app.
They have a broad range of features and the next version will be released trough react-native itself, so it seems to be pretty much recommended by the react-native devs themselves.

**Comment by Monte9** [comment]
I use `NavigationExperimental`. The core React Native is working on this and I believe they plan to make it the default navigation library with react-native soon. 
Here's a good article that should get you started with this: https://medium.com/react-native-training/react-native-navigationexperimental-in-depth-6910b9b0b990#.sdqpxdk5n

**Comment by jfrey** [comment]
Thanks for the replies!  I spent some time mocking up navigation with both react-native-router-flux and ex-navigation.  I noticed ex-navigation appears to be slated for inclusion in the reactjs organization which seems to be a good sign for that project.  I'll take a peak at experimental as well for due diligence.

Do you have any plans to integrate navigation with components like your tabs or side menu or perhaps provide some more examples?

**Comment by Nickman87** [comment]
@jfrey note that ExNavigation is also implemented on top of NavigationExperimental to tweak it's behaviour ;)

**Comment by jfrey** [comment]
@Nickman87 Yep I noticed :)  Being new to RN I'm still trying to sort out the state of the various projects and components.  There seems to be caution around using NavigationExperimental until it moves away from the 'experimental' phase but I admittedly don't know what that timeline looks like yet nor whether it's really all that experimental anymore.

**Comment by dabit3** [comment]
Definitely recommend [React Navigation](https://github.com/react-community/react-navigation) going forward, now that it's out.

**Comment by voidstarfire** [comment]
Don't recommend React Navigation, there are many issues with this library.

- Bad animation support
- No updates on core issues such as componentWillUnmount or performance issues where all previous screens are rending causing drops in frames
- Cannot modify the existing tree state
- Basic utilities such as popToRoute isn't implemented.
- goBack({id}) broken and not fixed.
- reset shows all preview screens, no way to go right to a screen and clear the stack.

Many more problems.

Other Navigation frameworks I've used are either completely deprecated or build on top of the original React native navigation which is also deprecated.

At the moment I've not found a decent React native navigator, it's a real shame.

**Comment by Monte9** [comment]
Thanks for your detailed response @voidstarfire. You do raise some valid points. I am curious to know what other alternatives would you recommend?

Also fyi, the team over at React Navigation recently released a blog post talking about a roadmap to v1. You can read the full blog post here: https://reactnavigation.org/blog/2017/9/Renewed-v1

**Comment by Monte9** [comment]
Also reopening this issue, as getting rid of our dependency on `react-native-tab-navigator` and `react-native-side-menu` in our 1.0 release coming soon. This issue might help users decide which navigation library they can use instead.

**Comment by iRoachie** [comment]
Closing in favor of the navigation guide on the react-native website, which gives a good breakdown of navigation and different libraries available. https://facebook.github.io/react-native/docs/navigation.html
