### ISSUE TITLE
Search bar icon align right

### ISSUE THREAD

**Issue by nu5rim3** [react-native-training/react-native-elements#1441]
**How set the Search bar search icon to align right**

**Comment by iRoachie** [comment]
You can use a mixture of `containerStyle` and `inputStyle` to accomplish this.
See example https://snack.expo.io/@roach_iam/rude-chip

**Comment by nu5rim3** [comment]
@iRoachie thank you fixed it!

**Comment by kunalkp** [comment]
How to set the search icon at the center?
