### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by yx920609** [react-native-training/react-native-elements#1443]
After npm ,i run the project again...
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native-vector-icons/FontAwesome` from `/Users/xin.yang/Desktop/antdmobile/antd/node_modules/react-native-elements/src/social/SocialIcon.js`: Module `react-native-vector-icons/FontAwesome` does not exist in the Haste module map

**Comment by iRoachie** [comment]
Follow getting started guide https://react-native-training.github.io/react-native-elements/docs/0.19.0/getting_started.html. You don't have react-native-vector-icons setup

**Comment by yx920609** [comment]
no ,i have installed react-native-vector-icons
![1538294126782](https://user-images.githubusercontent.com/16204811/46254898-4d59c700-c4c9-11e8-9ccd-afdcf5222276.jpg)

**Comment by iRoachie** [comment]
Did you link the package?

**Comment by yx920609** [comment]
... i forgeted,sorry

**Comment by iRoachie** [comment]
All good man!

**Comment by perfectdudu** [comment]
> All good man!

handsome man
