### ISSUE TITLE
Android Input component cropped on top

### ISSUE THREAD

**Issue by massivespace** [react-native-training/react-native-elements#1445]
The top of an Input component with no extra styling on Android is cropped slightly, causing 1 or 2 pixel rows of the text to be cut off on top.  This is in beta 5.  It appears worse on an actual device, don't notice it on an emulator.  The emulator I'm using is running API 28 with Nexus 5X frame.  My real device is a Galaxy S8+ running API 26.

Adding inputStyle={{paddingTop:2}} to the Input component props works around it.

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by xavier-villelegier** [comment]
Closing this as inactive but if you found a way to reproduce this please feel free to reopen it 👍

**Comment by matheusmessora** [comment]
Same here, and the solution worked like a charm.
```
inputStyle={{paddingTop:2}} 
```
