### ISSUE TITLE
Remove card default style

### ISSUE THREAD

**Issue by johnreytanquinco** [react-native-training/react-native-elements#1446]
I have in my app that displays a card with a background image that is resized on top of it(but inside the card). However, when I use the card component, I am always getting an extra margin from the background image. How this can be removed?

```
    <Card style={{ alignItems: 'center'}}>
      <ImageBackground source={{ uri: backgroundPhotoUrl }}
        style={{ width: '100%', height: 100}}>
        <View
      ...
      ...
```

**Comment by Mukeyii** [comment]
As far as i know there is no style-prop for the card-component of RNE. Try wrapperStyle or maybe even containerStyle.

**Comment by johnreytanquinco** [comment]
thanks!
