### ISSUE TITLE
[ListItem] error adding on(Long)Press

### ISSUE THREAD

**Issue by piu130** [react-native-training/react-native-elements#1456]
**Explain what you did**
Created a `FlatList` with a `ListItem` that has an `on(Long)Press` action on it.

**Expected behaviour**
Should throw no error.

**Describe the bug**
It throws the error `Invariant Violation: "Touchable child must either be native or forward setNativeProps to a native component"`

**To Reproduce**
I cannot create a Snack because it throws some errors (no expo-font.js found etc.)

The code to reproduce:

```js
import React, { Component } from 'react'
import { FlatList } from 'react-native'
import { ListItem } from 'react-native-elements'

export class List extends Component {
  render () {
    const data = [{ name: 'hello', id: '1' }, { name: 'world', id: '2' }]
    return (
      <FlatList
        data={data}
        keyExtractor={item => item.id}
        renderItem={({ item }) => <ListItem
          title={item.name}
          onPress={() => {}}
        />}
      />
    )
  }
}
```

**Possible Solution**
I surrounded the [`PadView`](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L107) with a `View` and it worked. See [here](https://github.com/facebook/react-native/issues/1040) and [here](https://facebook.github.io/react-native/docs/direct-manipulation.html#composite-components-and-setnativeprops)

**Full error**
```
The above error occurred in the <TouchableHighlight> component:
    in TouchableHighlight (at ListItem.js:101)
    in ListItem (at withTheme.js:24)
    in Themed.ListItem (created by CellRenderer)
    in div (created by View)
    in View (created by CellRenderer)
    in CellRenderer (created by VirtualizedList)
    in div (created by View)
    in View (created by ScrollView)
    in div (created by View)
    in View (created by ScrollViewBase)
    in ScrollViewBase (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by List)
    in List (created by Connect(List))
    in Connect(List) (created by ListPage)
    in div (created by View)
    in View (created by MainView)
    in MainView (created by Connect(MainView))
    in Connect(MainView) (created by ListPage)
    in ListPage (created by Connect(ListPage))
    in Connect(ListPage) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter) (created by App)
    in PersistGate (created by App)
    in Provider (created by App)
    in App
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta6 |
| react-native | 0.55 |
| npm or yarn | yarn@1.9.4 |

**Comment by xavier-villelegier** [comment]
Hey @piu130, thanks for reporting that !

Could you recreate this on Snack, but using the `1.0.0-beta5` ? Apparently we have some issues on the `1.0.0-beta6` on Snack, we're working on that.

It works fine with the code you provided on `1.0.0-beta5` [here](https://snack.expo.io/H1kKuQCq7)

**Comment by piu130** [comment]
@xavier-villelegier It throws the error described only with `1.0.0-beta6` (and `1.0.0-beta7`). Cannot create a Snack for that currently.

**Comment by xavier-villelegier** [comment]
@piu130 Yep we updated the react native version in the `beta6`, I think they changed something and we need to wrap the `ListItem`. (cc @martinezguillaume)

We reached out the Expo team about the expo-font.js thing, we'll let you know !

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by patsissons** [comment]
I ran into this issue tonight when using playing around with [`react-native-web`](https://github.com/necolas/react-native-web). The issue i had was that their [`TouchableHightlight`](https://github.com/necolas/react-native-web/blob/8ce5750d3437d1caa3d74a74a3625c70c54b66ab/packages/react-native-web/src/exports/TouchableHighlight/index.js#L267) uses a `ref`, and that doesn't work with the [functional `PadView`](https://github.com/react-native-training/react-native-elements/blob/c668c78dddd9315f6ca5ec2548e051b2a7e29c73/src/list/ListItem.js#L351). This seems like an issue with `react-native-web`, but maybe there is something that could be done to protect against this in RNE?

```tsx
function Repro() {
  return <ListItem title="❌ Repro" onPress={() => {}} />;
}
```

I wound up with a relatively simple workaround (might be useful for others running into this issue).

```tsx
function WebTouchableHighlight({children, ...props}: any) {
  return (
    <TouchableHighlight {...props}>
      <View>{children}</View>
    </TouchableHighlight>
  );
}

const SafeTouchableHighlight =
  Platform.OS === 'web' ? WebTouchableHighlight : TouchableHighlight;

function Fixed() {
  return <ListItem title="✅ Fixed" Component={SafeTouchableHighlight} onPress={() => {}} />;
}
```

**Comment by smeevil** [comment]
Thanks @patsissons, I was running into this exact same issue (with 1.1.0). 

As soon as I add a onPress to the list item, on web it will throw: `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? Check the render method of `TouchableHighlight`. in PadView (at ListItem.js:107)`

Your wrapper did work fine and saved my day :)
