### ISSUE TITLE
Publish beta6 on NPM

### ISSUE THREAD

**Issue by tux-tn** [react-native-training/react-native-elements#1461]
```react-native-elements@1.0.0-beta6``` has been released two days ago but the latest verison on npmjs.org is still beta-5

Can you please update the package on npmjs.org ?

**Comment by iRoachie** [comment]
We had a small hiccup where we mistakenly published 1.0.0-beta6 as the **current stable version** and not as a beta. So we had to remove the version. Currently fixing the problem now and it'll show as beta7 in a few minutes

**Comment by iRoachie** [comment]
Beta 7 just published to resolve this.
