### ISSUE TITLE
React Native Elements beta7 complains when React Native Vector Icons 6.x or higher is installed

### ISSUE THREAD

**Issue by janhesters** [react-native-training/react-native-elements#1464]
**Explain what you did**
I installed RNE and RNV. 

**Expected behaviour**
No console warning.

**Describe the bug**
The latest version of RNV is 6.x, but RNE wants 4.2.x or 5.x.

**To Reproduce**
```
npm install --save react-native-elements@beta
npm install --save react-native-vector-icons
```

**Screenshots**
<img width="961" alt="screen shot 2018-10-14 at 08 28 06" src="https://user-images.githubusercontent.com/31096420/46913315-3320ee00-cf8b-11e8-821c-6cd14d98d119.png">
<img width="286" alt="screen shot 2018-10-14 at 08 28 37" src="https://user-images.githubusercontent.com/31096420/46913316-374d0b80-cf8b-11e8-8898-7eff74d16ecc.png">

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.57.2 |
| npm or yarn | 6.4.1 |
| react-native-vector-icons | 6.0.2 |

**Comment by iRoachie** [comment]
I'm thinking maybe we should change this to using the `>` sign https://stackoverflow.com/a/25861938/1862272
