### ISSUE TITLE
Types for ThemeProvider are incorrect

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1467]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Use a custom component for the ListItem using the component prop through the ThemeProvider.

**Expected behaviour**
It should work and not have errors.

**Describe the bug**
```jsx
const ElementsTheme = {
  ListItem: {
    component:
      Platform.OS === 'ios' ? TouchableOpacity : TouchableNativeFeedback,
  },
}

<ThemeProvider theme={ElementsTheme}>
```

This throws an error because the colors property is not defined in the theme.

**To Reproduce**
Example:

```bash
# Steps
1. Setup react-native project with typescript
2. Add react-native-elements@1.0.0-beta7
3. Use the example code above
4. See error
```

**Possible Solution**
Change the definition to the correct type.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7|
| react-native | 0.56.0 |
| npm or yarn | 1.10.1 |

**Comment by diosney** [comment]
Hi! It still gives the error, any ideas on how mute it?
