### ISSUE TITLE
[Button] v.1.0.0-beta7

### ISSUE THREAD

**Issue by danielkolesnik** [react-native-training/react-native-elements#1470]
Version **1.0.0-beta7**
Component **Button**

**Explain what you did**
Using _**rightIcon**_/_**raised**_/_**leftIcon**_ 

**Expected behaviour**
I've expected to see behaviour that described in docs.

**Describe the bug**
It seems to be unrealized functionality, so when you use one of these attributes nothing happens.. 

**To Reproduce**
Just npm i react-native-elements and try to use Button functionality.

**Possible Solution**
I don't know actually is it bug or just unrealized features, so I just leave it here for devs to know:)
I've decided to just re-install to stable version 0.19.0

**Your Environment (please complete the following information):**
| **WebStorm** + **NOX**(to emulate Android device) |
| -- | -- |
| **react-native-elements** | 1.0.0-beta7 |
| **react-native** | 0.55.4 |
| **react-native-cli** | 2.0.1 |
| **expo** | 2.2.0 |
| **npm** | 6.1.0 |

**Comment by iRoachie** [comment]
Hey @danielkolesnik, you can check the props for v1.0.0-beta7 button herehttps://react-native-training.github.io/react-native-elements/docs/button.html#props. There's no `rightIcon` or `leftIcon` prop.

`icon` displays an icon to the left. `rightIcon` is a boolean you can set to display the icon to the right. The `raised` prop should work the same as 0.19.1

**Comment by danielkolesnik** [comment]
@iRoachie I understood that I've missed docs for v.1.0.0-beta7 on the official site.. Nevertheless thank you so much for your answer!))
