### ISSUE TITLE
List component not available

### ISSUE THREAD

**Issue by PaddyLock** [react-native-training/react-native-elements#1471]
**Explain what you did**
yarn add react-native-elements@beta
to install v.1.0.0-beta7

**Expected behaviour**
Lists should work

**Describe the bug**
List is no available to use. It is missing from node_modules/react-native-elements/src/list

**To Reproduce**
Load a view importing List

Example:

`import { List, ListItem, Icon } from 'react-native-elements';`

**Possible Solution**
Make sure the List.js file is in the directory

**Screenshots**

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements |  v.1.0.0-beta7 |
| react-native | https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz |
| npm or yarn | yarn |

**Comment by iRoachie** [comment]
v1.0.0-beta7 has no List component. The List component is only in 0.19.1. It was removed in the betas.
Always refer to the documentation for available components per version.

0.191.
<img width="310" alt="screen shot 2018-10-16 at 6 55 43 am" src="https://user-images.githubusercontent.com/5962998/47011729-99834900-d110-11e8-9926-9d261070ae05.png">

1.0.0-beta7
<img width="324" alt="screen shot 2018-10-16 at 6 55 53 am" src="https://user-images.githubusercontent.com/5962998/47011743-a30cb100-d110-11e8-82d7-fa7f0596aafb.png">
