### ISSUE TITLE
Ant Design Missing from Icon Types

### ISSUE THREAD

**Issue by d-p-s** [react-native-training/react-native-elements#1473]
**Explain what you did**
I wanted to use an icon from Ant Design by supplying 'AntDesign' as the type prop or similar.

**Expected behaviour**
I expected the icon to be loaded.

**Describe the bug**
Instead I got the question mark. I investigated and found that AntDesign isn't included in the helper function at this link: https://github.com/react-native-training/react-native-elements/blob/master/src/helpers/getIconType.js

**To Reproduce**
Try to use an ant design icon.

**Possible Solution**
Can you suggest a possible fix that would address this issue?
Import the ant design icon library and add it to the switch statement in  https://github.com/react-native-training/react-native-elements/blob/master/src/helpers/getIconType.js

**Comment by thomasarogers** [comment]
Having the same issue

**Comment by iRoachie** [comment]
Hey! This has been added in https://github.com/react-native-training/react-native-elements/pull/1529. Will be available in 1.0.0 release.
