### ISSUE TITLE
##Check box => checkedIcon and uncheckedIcon not working 

### ISSUE THREAD

**Issue by trancanh2202** [react-native-training/react-native-elements#1475]
I used :
"react-native": "0.57.1",
"react-native-elements": "^0.19.1",
"react-native-vector-icons": "^5.0.0",
==>> I cannot custom checkedIcon and uncheckedIcon. Icon not show. Please help me.

![screen shot 2018-10-17 at 11 41 23 am](https://user-images.githubusercontent.com/42834870/47069223-92476280-d218-11e8-9a86-c43ff86794cb.png)

**Comment by iRoachie** [comment]
Custom `checkedIcon` and `uncheckedIcon` isn't available in 0.19.1. This is a feature we added in the beta.

The props for 0.19.1 checkbox is here https://react-native-training.github.io/react-native-elements/docs/0.19.0/checkbox.html#props

**Comment by trancanh2202** [comment]
thanks iRoachie!.. I will remove "react-native-elements" => so banana :)

**Comment by iRoachie** [comment]
Great to hear!
