### ISSUE TITLE
Add customization to custom fonts

### ISSUE THREAD

**Issue by likern** [react-native-training/react-native-elements#1480]
**Is your feature request related to a problem? Please Describe.**
It's not possible to pass properties to custom fonts. I suggest it's not enough to generate custom **Icon** component, it also should be flexible to pass special properties.

_For example_, after registering **Awesome Font Pro** font I can't use it's **ligh** / **solid** / **brand** properties which modifies font style.

And I think it's very important as it's one of the reasons why people buy this font - light font style.

**Describe the solution you'd like**
Add property **customIconProps** which takes object and will pass it directly to Icon component. 

Thus I'll be able to call
```
<Icon 
    name='circle' 
    size={28} 
    type='fontawesomepro'
    customIconProps={{ light: true }}
/>
```
This solution will also work with custom fonts which are not related to **react-native-vector-fonts**.

**Describe alternatives you've considered**
Add propogation of **brand / light / solid** props of **Icon** component if **Awesome Font Pro** font is used otherwise ignore them.

**Additional context**
This feature important because:

1. It gives unified interface to all Icon fonts, including custom. You don't need to work with custom fonts differently as now we work with **Awesome Font Pro** directly through **react-native-vector-fonts**
2. Styling and other properties will be inherited automatically to all fonts. For example now **FontAwesome5Pro** is rendered _differently_ than **RNE Icon** component, because **Icon** applies additional styles like _black color_.

Now only Icon component is changed based on **type** property. But, depending on component it might require special custom properties to be passed.
![screenshot from 2018-10-17 14-59-06](https://user-images.githubusercontent.com/842306/47084812-64185180-d21d-11e8-89a9-466ca90ba7c1.png)
![screenshot from 2018-10-17 14-58-50](https://user-images.githubusercontent.com/842306/47084813-64185180-d21d-11e8-8d67-daee64f351d2.png)

**Comment by vsai** [comment]
@likern Do you currently have a working implementation using FontAwesomePro?
I'm trying to figure out if there is an alternative make-do integration option for something urgent I have to do.

**Comment by likern** [comment]
> @likern Do you currently have a working implementation using FontAwesomePro?
> I'm trying to figure out if there is an alternative make-do integration option for something urgent I have to do.

@vsai  I've given up using Icon component of react-native-elements. I've switched to using FontAwesomePro directly through https://github.com/oblador/react-native-vector-icons. Also I've written own Icon wrap based on react-native-vector-icons.

**Comment by vsai** [comment]
> @vsai I've given up using Icon component of react-native-elements. I've switched to using FontAwesomePro directly through https://github.com/oblador/react-native-vector-icons. Also I've written own Icon wrap based on react-native-vector-icons.

@likern Using `react-native-vector-icons` seems to require ejecting the app / linking to native libraries and cocoapods based on the installation docs. I'm looking for a solution that wouldn't require all of that too. As of now, using the `react-native-elements` Icon component doesn't require doing any of that.
Note: I'm using Expo.

I'm considering downloading the `.ttf` files, adding the font-family and handling it manually.

Please let me know if you have a simple integration of this, that doesn't require native linking for the app. Thanks!

**Comment by vsai** [comment]
@likern Ok. Thanks for the help. I think I'll try doing that then.
Did you have to register it as a new font though? Because from the library, it seems like only FontAwesome is directly supported.

**Comment by likern** [comment]
> @likern Ok. Thanks for the help. I think I'll try doing that then.
> Did you have to register it as a new font though? Because from the library, it seems like only FontAwesome is directly supported.

[react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) support multiple fonts out of the box. Probably there is a way how to register custom font. But I didn't try because have chosen to use Font Awesome Pro with lots of icons and several stylings. So in my application I use only Font Awesome Pro.
