### ISSUE TITLE
Can't register custom font with dashed type name

### ISSUE THREAD

**Issue by likern** [react-native-training/react-native-elements#1481]
**Explain what you did**
Tried to register custom **Awesome Font Pro** like below:
```
import FontAwesome5Pro from 'react-native-vector-icons/FontAwesome5Pro';
registerCustomIconType('font-awesome-pro', FontAwesome5Pro);
```
suggesting this should work the same way as **font-awesome** type.

**Expected behaviour**
Custom fonts should work with dashed type names.

**Describe the bug**
It's not working now.

**To Reproduce**
Enable **Awesome Font Pro** for using and then try to register with dashed type name as in code above.

**Possible Solution**
I suggest the reason is in [getIconType.js file](https://github.com/react-native-training/react-native-elements/blob/master/src/helpers/getIconType.js). Custom type becomes **dashed** property of **customIcons** object and check 
```
if (customIcons.hasOwnProperty(type)) {
    return customIcons[type];
}
```
stops working.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements |0.19.1 |
| react-native | 0.57.2|
| npm or yarn |6.4.1 |

**Comment by xavier-villelegier** [comment]
@likern Not sure this is because of the dash. Js seems to work properly with dashed property and `hasOwnProperty`:
```js
> test = { 'this-is-test': 'foo' }
> test.hasOwnProperty('this-is-test')
true
```

Does it work without the dash ?

**Comment by likern** [comment]
@xavier-villelegier Yes, it is working without dash. I found this in debugger - that this check didn't pass. It's strange, might be I had some modified debug environment or something like this. Ok, I will close this for now I will test this thoroughly when Awesome Font 5 Pro support will be added.
