### ISSUE TITLE
I can not decrease space between ListItems 

### ISSUE THREAD

**Issue by Taher62** [react-native-training/react-native-elements#1482]
Hi 

How i can decrease the space between ListItems in FlatList?

Is there any way?

**Comment by iRoachie** [comment]
Can you please use the issue template? RNE has different components in different versions and there's no way for me to know what version you are using.

**Comment by Taher62** [comment]
can sen me issue template?
thanks

**Comment by iRoachie** [comment]
It's there when you create an issue. For now just fill out this:

| software | version |
| -- | -- |
| react-native-elements | |
| react-native | |
| npm or yarn | |

**Comment by Taher62** [comment]
react-native-elements : 0.19.1
react-native 0.54.0
npm or yarn 1.7.0

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
