### ISSUE TITLE
[Avatar] Option to override shadow effect on editIcon

### ISSUE THREAD

**Issue by galeels** [react-native-training/react-native-elements#1484]
**Is your feature request related to a problem? Please Describe.**
It would be great to provide an option to override the shadow effect on editIcon.

**Describe the solution you'd like**
When showEditIcon is enabled, there is shadow effect on iOS around the icon. For users who likes to have same style across iOS and Android and don't like that shadow effect, we should provide option to disable the shadow effect.

**Describe alternatives you've considered**
Otherwise remove the default platform specific shadow effect. Those who wish to have can use the style props to override it.

**Additional context**
Here is the code snippet to be considered...
 ```
editButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DEFAULT_COLORS[4],
    ...Platform.select({
      ios: {
        shadowColor: DEFAULT_COLORS[0],
        shadowOffset: { width: 1, height: 1 },
        shadowRadius: 2,
        shadowOpacity: 0.5,
      },
      android: {
        elevation: 1,
      },
    }),
  }
```

**Comment by iRoachie** [comment]
You can already override the props of the editButton include style. See https://github.com/react-native-training/react-native-elements/blob/master/src/avatar/Avatar.js#L203

**Comment by galeels** [comment]
Your suggestion works if someone prefers to alter or customize the shadow effect, but effective for removing the shadow.
At most 5 properties  needs to be overridden for removing the shadow effect. 
Instead of overriding the styles Its better to have a boolean which toggles shadow on/off.
