### ISSUE TITLE
In which directory should we install react-native-elements?

### ISSUE THREAD

**Issue by Vinay-Revankar** [react-native-training/react-native-elements#1496]
In which directory should we install react-native-elements?

https://react-native-training.github.io/react-native-elements/docs/getting_started.html#step-1-install-react-native-elements

**Comment by iRoachie** [comment]
The directory that has your react-native project.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
