### ISSUE TITLE
[Jest] Failing tests on Windows and WSL

### ISSUE THREAD

**Issue by haruelrovix** [react-native-training/react-native-elements#1497]
**Explain what you did**
Run `yarn test` in **Windows** and [**WSL**](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Expected behaviour**
Test should all passed like in Travis CI, [here](https://travis-ci.org/react-native-training/react-native-elements/builds/443595703).

**Describe the bug**
In **Windows**:
```sh
Summary of all failing tests
 FAIL  src/rating/__tests__/Rating.js
  ● Test suite failed to run

    D:\Projects\react-native-elements\src\rating\images\star.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      17 | import { ViewPropTypes, withTheme } from '../config';
      18 |
    > 19 | const STAR_IMAGE = require('./images/star.png');
         |                    ^
      20 | const HEART_IMAGE = require('./images/heart.png');
      21 | const ROCKET_IMAGE = require('./images/rocket.png');
      22 | const BELL_IMAGE = require('./images/bell.png');

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.require (src/rating/Rating.js:19:20)
      at Object.<anonymous> (src/rating/__tests__/Rating.js:8:1)


Test Suites: 1 failed, 23 passed, 24 total
```
In **WSL**:
```sh
Test Suites: 24 passed, 24 total
Tests:       11 skipped, 180 passed, 191 total
Snapshots:   144 passed, 144 total
Time:        15.608s, estimated 104s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**To Reproduce**

# Steps
1. A Windows machine with WSL
2. Clone RNE repo, `git clone https://github.com/react-native-training/react-native-elements.git`
3. Install dependencies `yarn`
4. Run test `yarn test`
5. See errors

**Possible Solution**
Creating an [`assetsTransformer.js`](https://github.com/facebook/jest/issues/2663#issuecomment-317109798)

**Screenshots**
![image](https://user-images.githubusercontent.com/17120764/47213491-60273380-d3c5-11e8-91be-77073c9c476f.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7|
| react-native |0.55.4 |
| npm or yarn |yarn 1.10.1 |

**Comment by haruelrovix** [comment]
See [882107c](https://github.com/react-native-training/react-native-elements/commit/882107cd1af813f9691572770435fc55f925850e).

It fixes the issue, but also updating the snapshots. _Not sure it's the right way_.

![image](https://user-images.githubusercontent.com/17120764/47215179-b21e8800-d3ca-11e8-92b3-0f8ceb7d2fcd.png)

**Comment by iRoachie** [comment]
Hey @haruelrovix did you send a PR for this? Would be happy to review/merge it

**Comment by haruelrovix** [comment]
@iRoachie PR sent, #1504 .
