### ISSUE TITLE
SocialIcon

### ISSUE THREAD

**Issue by borgogelli** [react-native-training/react-native-elements#1500]
I use "react-native-elements": "^0.19.1"

`<SocialIcon  title='Sign In With Google'  button  type='google' />`

When rendered the icon not styled  (colors are black and white).
While the other types are displayed correctly

**Comment by massivespace** [comment]
Regarding the google-plus-official icon, it was using the Google+ icon as of beta 5.  Refer to this article as that icon has been deprecated.  https://9to5google.com/2016/11/17/google-plus-sign-in-replaced/ . Also, Google+ is shutting down.

**Comment by iRoachie** [comment]
Hey @massivespace thanks for the info, could you put this into a separate issue?

**Comment by borgogelli** [comment]
@iRoachie thank you

**Comment by LouisJS** [comment]
Are SocialIcon using icon from a certain icon set such as 'FontAwesome' or is it custom by yourself ?
I'd like to suggest adding: 'VKontakte', 'Weibo', as well as 'WeChat'

**Comment by iRoachie** [comment]
It uses font-awesome at the moment. If we add other icon sets it means we'd need to have some way of mapping icon name to corresponding name in each icon set

**Comment by LouisJS** [comment]
I'm using `react-native-elements` with Expo. And expo installs by default[ this icon set](https://docs.expo.io/versions/latest/guides/icons)
You can find many more social networks available in `FontAwesome` than here exposed in react-native-elements.

**Few examples:**
houzz
vk (vkontakte)
weibo
bandcamp
flicker
ect

If there is a way to contribute, i'll be more than happy to help

**Comment by iRoachie** [comment]
Oh my bad i now get what you're saying. These are icons you're asking to be added? Can you make this suggestion in another issue?

**Comment by LouisJS** [comment]
Yes sure ! Well i see you are using `https://oblador.github.io/react-native-vector-icons/` so i will try to make a PR for this 💪
