### ISSUE TITLE
Input Element Not supported in RNInit App

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-training/react-native-elements#1502]
**Explain what you did**

I started new app from scrach( React native init ) but there input not wotk.
error occured when i implement input.
i think react native elements is the best library in react native.

**Expected behaviour**

WORKING FINE

**Describe the bug**
Below image
![a](https://user-images.githubusercontent.com/30401136/47268478-445f9100-d56f-11e8-899b-194d4886b675.png)

**To Reproduce**

 <View style={{ backgroundColor: 'transparent', marginTop: SCREEN_HEIGHT / 15 }}>

                <Input
                  placeholder='INPUT WITH ICON'
                  leftIcon={{ type: 'font-awesome', name: 'chevron-left' }}
                />
 </View>

Example:

OR

              <View style={{ backgroundColor: 'transparent', marginTop: SCREEN_HEIGHT / 15 }}>

                <Input
                  inputContainerStyle={{
                    borderRadius: 40, backgroundColor: 'rgba(41,122,94,0.4)', borderWidth: 1,
                    borderColor: "transparent", height: SCREEN_HEIGHT / 15, width: SCREEN_WIDTH / 1.3, marginVertical: 10
                  }}
                  maxLength={40} multiline={false}
                  ref={input => this.emailInput = input}
                  onChangeText={(email) => {
                    this.setState({ email: email })
                    this.setState({ email_valid: this.validateEmail(email) })
                    // this._onshow({ text, id, type })
                  }}
                  value={email}
                  // value={this.state.answerArray.hasOwnProperty(id) ? this.state.answerArray[id] : null}
                  leftIcon={<Icon type='feather'
                    name="mail" color="rgba(63, 174, 135,0.6)" size={SCREEN_HEIGHT / 35} />}
                  iconContainerStyle={{ marginLeft: 30 }} placeholder="Email"
                  placeholderTextColor="rgba(63, 174, 135,0.6)"
                  inputStyle={{ marginLeft: 10, marginRight: 10, color: "white", fontSize: SCREEN_HEIGHT / 41 }}
                  autoCapitalize="none" autoCorrect={false} keyboardAppearance="light"
                  errorStyle={{ textAlign: 'center', fontSize: Fonts.size.regular }}
                  errorMessage={email === "" ? null : email_valid ? null : "Please enter a valid email address"}
                  keyboardType="email-address" returnKeyType="next"
                  onSubmitEditing={() => {
                    this.setState({ email_valid: this.validateEmail(email) });
                    this.otpInput.focus();
                  }} blurOnSubmit={false} />
              </View>

**Your Environment (please complete the following information):**

{
"name": "New app from Start",
"version": "0.0.1",
"private": true,
"rnpm": {
"assets": [
"./assets/fonts"
]
},
"scripts": {
"start": "node node_modules/react-native/local-cli/cli.js start",
"test": "jest"
},
"dependencies": {
"@babel/runtime": "^7.1.2",
"axios": "^0.18.0",
"moment": "^2.22.2",
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.1",
"react-native-elements": "^0.19.1",
"react-native-linear-gradient": "^2.4.2",
"react-native-screen-orientation": "^1.1.0",
"react-native-vector-icons": "^6.0.2",
"react-navigation": "^2.18.0",
"schedule": "0.4.0"
},
"devDependencies": {
"babel-jest": "23.6.0",
"jest": "23.6.0",
"metro-react-native-babel-preset": "0.48.1",
"react-test-renderer": "16.6.0-alpha.8af6728"
},
"jest": {
"preset": "react-native"
}
}

**Comment by iRoachie** [comment]
The Input component isn’t available in v0.19.1. The list of components in that version are 
https://react-native-training.github.io/react-native-elements/docs/0.19.1/overview.html on the side.

If you want a text input type component in 0.19.1 it’s [FormInput](
https://react-native-training.github.io/react-native-elements/docs/0.19.1/forms.html)

Interestingly where did you see about an Input component?

**Comment by Biplovkumar** [comment]
What should i do ? 
i love react native element all components.
reQured help

**Comment by Monte9** [comment]
@Biplovkumar please upgrade to our v1 beta version. We have an even better input component that I am sure you'll love using.

`yarn add react-native-elements@beta`

**Comment by Biplovkumar** [comment]
Thanks @Monte9
