### ISSUE TITLE
ButtonGroup innerBorderStyle propTypes needs a small change

### ISSUE THREAD

**Issue by dkaushik95** [react-native-training/react-native-elements#1506]
**Is your feature request related to a problem? Please Describe.**

When I use the `ButtonGroup` component and I want to apply a style from the StyleSheet object, the prop [`innerBroderStyle`](https://github.com/react-native-training/react-native-elements/blob/1f76514f863ea48899236b35f5e963ce6ecb397f/src/buttons/ButtonGroup.js#L193) requires an object. So I have to specify the style inline instead of an object outside the component definition. 

**Describe the solution you'd like**

It would be awesome if we could use `Proptypes.style` instead of `Proptypes.shape`.

**Comment by dkaushik95** [comment]
Sure! I will make a change this week.

**Comment by dkaushik95** [comment]
On further investigation, I saw that these styles are being applied using a custom styles on a View. And an issue was referenced [here](https://github.com/facebook/react-native/issues/8236). 

I can replace it by ViewStyleProp, but then Anyone can add other values to it. (Apart from border color and width). 

I think that would go against the use case for the ButtonGroup. 

What do you guys think?

**Comment by iRoachie** [comment]
Yea you're right, maybe we should just leave it as it is. They're other props already if they want to change common things like backgroundColor.
