### ISSUE TITLE
Change Icon onPress

### ISSUE THREAD

**Issue by fedecroqueta** [react-native-training/react-native-elements#1509]
Hi i am very newbie in RN, i want to change mi icon when it is pressed , example change ' favorite-border' to 'favorite'. I have tried a lot of things, this is my actual code : 

	state = {
		loading : false,
		data : [],
		fav : false
	}

	constructor(props){
		super(props);	

		this.addFav = this.addFav.bind(this);	
	}

	componentDidMount(){
		this.getRandomUsers();
	}

	getRandomUsers(){
		const url = 'https://randomuser.me/api/?seed=1&page=1&results=20';
		this.setState({loading:true});

		fetch(url)
		.then(res => res.json() )
		.then(res => {
			this.setState({
				data : res.results,
				loading:false,
			})
		})
	}

	addFav = () => this.setState({fav: !fav})
		

	

	renderRow ({ item }) {
		return (
			<ListItem
				roundAvatar
				title={item.location.street}
				subtitle={item.location.city}
				avatar={{uri:item.picture.thumbnail}}
				rightIcon={
					<Icon
						name='favorite-border'
					 	onPress={() => this.addFav}
					/>
  				}			
			/>
		)
	}

	render() {
		if(this.state.loading ){
			return (
			<View style={styles.container}>
				<ActivityIndicator size="large" color="#FFFFFF" />
			</View>
		);
		}else{
			return (
			<View style={styles.container}>
				<List containerStyle={{width: 300}}>
					<FlatList
						data={this.state.data}
						renderItem = {this.renderRow}
						keyExtractor = {item => item.name.first}
						extraData={this.state.fav}
					/>
				</List>
			</View>
		);
		}

	}
And this is how i see it 

![untitled](https://user-images.githubusercontent.com/26797781/47523457-71ad8700-d86e-11e8-8add-ccb92da2890d.png)

Thank you so much, i wish not to be a pain in th.... :)

**Comment by shaunsational** [comment]
you can try this 

```
renderRow ({ item }) {
	var iconFav = (item.fav) ? 'favorite' : 'favorite-border'
	return (
		<ListItem
			roundAvatar
			title={item.location.street}
			subtitle={item.location.city}
			avatar={{uri:item.picture.thumbnail}}
			rightIcon={
				<Icon
					name={iconFav}
				 	onPress={() => this.addFav}
				/>
			}			
		/>
	)
}
```
right before the return I'm declaring a variable `iconFav` thats set based on a property of the item (I didn't see any place you were storing the value of favorite), then down in the icon property you're pulling the value of `{iconFav}` which is set by the ternary statement

**Comment by fedecroqueta** [comment]
I will try with my best effort ! I really appreciate your time to answer my question  , i will be notice if that works :)

**Comment by shaunsational** [comment]
if it doesn't work, change the var line to this:
```var iconFav = (this.state.fav) ? 'favorite' : 'favorite-border'```
that should work

**Comment by fedecroqueta** [comment]
With a little changes by my side and you comment it works changing all the icon of all rows and i only want to change the icon of the row that i pressed.  Do you know if can i do something to keep the row that is pressed ?

**Comment by shaunsational** [comment]
You would have to store the fav property to each individual object, I'm fairly new to react myself so I'm not sure if that can be done with the state or if it needs to be stored in the object itself.

**Comment by iRoachie** [comment]
Here's a working example of this. Instead of storing a fav property to each object, instead, we can manage an array on our state that has all the "favorited" items.

https://snack.expo.io/@roach_iam/favorite-listitem

**Comment by iRoachie** [comment]
Of course not, you have to persist the data and read it from AsyncStorage or another react-native db library when it's updated

**Comment by shaunsational** [comment]
ah thanks, im still new as well, and thought I may have just done all that AsyncStorage code in my app for no reason

**Comment by fedecroqueta** [comment]
@iRoachie Excellent !!! That's what i want, thank you very much !!!
