### ISSUE TITLE
Missing typescript type for ButtonGroupProps selectedButtonStyle in 0.19.1

### ISSUE THREAD

**Issue by gareys** [react-native-training/react-native-elements#1511]
**Is your feature request related to a problem? Please Describe.**

There is a missing type for the selectedButtonStyle under the ButtonGroupProps in react-native-elements v0.19.1

**Describe the solution you'd like**

Add the type:

```
  /**
   * Specify styling selected button
   *
   * @default 'white'
   */
  selectedButtonStyle?: StyleProp<ViewStyle>;
```

**Describe alternatives you've considered**
Patching my local package until it is fixed in the repository.

**Additional context**
N/A

**Comment by gareys** [comment]
https://github.com/react-native-training/react-native-elements/blob/v0.19.1/src/index.d.ts#L584

**Comment by iRoachie** [comment]
This has already been fixed in the beta. 
https://github.com/react-native-training/react-native-elements/blob/v1.0.0-beta7/src/index.d.ts

We’re not making any patches to 0.19.1. To try the beta run `npm install —save react-native-elements@beta`
