### ISSUE TITLE
Themed Overlay needs keys for children

### ISSUE THREAD

**Issue by LucidityDesign** [react-native-training/react-native-elements#1517]
**Explain what you did**
I'm using `ThemeProvider` with Overlays

**Expected behaviour**
Adding multiple children without keys should be possible

**Describe the bug**
If you add children to an themed overlay, they get added as an array and therefore need a key

**To Reproduce**
I don't know how to display warnings in snacks, but the warnings should get thrown here:
https://snack.expo.io/@lucidity/dGhlbW

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.57.3 |
| npm or yarn | 5.6.0 |

**Comment by iRoachie** [comment]
Confirming this. Will check into it
