### ISSUE TITLE
Can't change cursor color of input.

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-training/react-native-elements#1519]
**Explain what you did**
I want to change cursor  color with respect to my theme color

**Expected behaviour**
Blue color

**Describe the bug**

Cursor color not changed.

Example:

**Screenshots**

![change_cursor_color](https://user-images.githubusercontent.com/30401136/47639526-839d6b80-db87-11e8-8752-508e0abc5b33.png)

**Your Environment (please complete the following information):**

 "dependencies": {
    "@babel/runtime": "^7.1.2",
    "react": "^16.5.0",
    "react-native": "0.57.1",
    "react-native-elements": "^1.0.0-beta7",
    "react-native-firebase": "^5.0.0",
    "react-native-linear-gradient": "^2.4.2",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.18.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.1"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.1",
    "react-test-renderer": "16.6.0-alpha.8af6728",
    "schedule": "^0.4.0"
  }

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io or show the code that reproduces this?

**Comment by xavier-villelegier** [comment]
@Biplovkumar Did you try to use `selectionColor` props ? https://facebook.github.io/react-native/docs/textinput#selectioncolor

**Comment by xavier-villelegier** [comment]
Closing this as `selectionColor` should do the job. Feel free to reopen this if you still have this issue ! ✌️

**Comment by andidavies92** [comment]
I'm still having this issue, even when setting `selectionColor`. Please let me know what info you require from me for a minimal reproduction and I'll put some details together for you.

**Comment by samcampisi** [comment]
I am experiencing the same situation. ```selectionColor``` only works in the selected part of the input text, not the cursor, which remains android green.

I also tried adding
```
<item name="colorControlActivated">#0069FF</item>
```

to styles.xml but I get the same result.

Am I missing something?

**Comment by samcampisi** [comment]
Update: after cleaning the project cache and rebuilding the app on android it worked.

Also for some reason I had two "styles.xml" files and was putting the item in the wrong file.

**Comment by colemars** [comment]
Which style props are you guys passing `selectionColor` to? I'm receiving errors on `containerStyle` `inputContainerStyle` and `inputStyle`.
