### ISSUE TITLE
where is `rounded`, `outline`, and `transparent`

### ISSUE THREAD

**Issue by geminiyellow** [react-native-training/react-native-elements#1520]
hi all, i using `0.19.0`, when i update to `1.0.0-beta7`, i found that `Button` props ` rounded`, `outline`, and `transparent` is gone. and there is no release log and no reason. could i know if we will use it in later or not? if not, please add why you delete it to the docs, thank you.

**Comment by geminiyellow** [comment]
and i check the history, from here : 2649b131f47ff042bf774d48853e0b39ff9ede5b
the breaking change. 

you pass all the props as `attributes ` into `TouchableComponent` in #817 

https://github.com/react-native-training/react-native-elements/blob/2ea3b07c49d889e84b49eb6bd4344980653bd822/src/buttons/Button.js#L76

**Comment by geminiyellow** [comment]
should i use something like `buttonStyle` to re-create my button ?

**Comment by xavier-villelegier** [comment]
@geminiyellow Actually we introduced theming in the latest beta, could you try to use it and tell give us some feedback ? https://react-native-training.github.io/react-native-elements/docs/customization.html#theming

**Comment by geminiyellow** [comment]
opps, got it , i will try it later.
use theming to manage the style is the best practices ?

**Comment by iRoachie** [comment]
Hey @geminiyellow, this is something we definitely want to re-added in the future. The only way to get this in the betas is to apply the styles yourself.

**Comment by geminiyellow** [comment]
and same in the Button component, i think `title` 's default value should be empty sting not `Welcome` message. every icon only button have to set `title={null}` is not a good idea.

**Comment by iRoachie** [comment]
Gotcha! Thanks for feedback.

**Comment by iRoachie** [comment]
Made an issue here to track https://github.com/react-native-training/react-native-elements/issues/1525

**Comment by geminiyellow** [comment]
👏  thank you @iRoachie , and i will try theming later, and give a feedback in here[?] or maybe a new issue. thank you again.
