### ISSUE TITLE
How to user linearGradientProps in non expo project?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-native-training/react-native-elements#1524]
How to user linearGradientProps in non expo project? The doc says supports only expo. Isthere any ways to make it work with react native linear gradient node module? 

| software | version |
| -- | -- |
| react-native-elements | Latest |
| react-native | 0.57.0 |
| npm or yarn | latest |

**Comment by ManigandanRaamanathan** [comment]
@iRoachie The gradient works. But there is one issue. The Ripple effect goes outside the button. Is there any fix for this bug?

**Comment by ManigandanRaamanathan** [comment]
This is the code I'm using

<Button
                                    title="Sign In"
                                    titleStyle={{ fontFamily: 'regular', fontSize: 20, color: 'white', textAlign: 'center' }}
                                    buttonStyle={{
                                      height: 54, borderRadius: 100, 
                                    }}
                                    
                                    ViewComponent={LinearGradient}
                                    linearGradientProps={{
                                        colors: ['rgba(214,116,112,1)', 'rgba(233,174,87,1)'],
                                        start: { x: 0, y: 0.5 },
                                        end: { x: 1, y: 0.5 },
                                    }}
                                    containerStyle={{ marginVertical: 20 }}
                                    style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}
                                    onPress={() => console.log('Message Theresa')}
                                    activeOpacity={0.5}
                                />

**Comment by ManigandanRaamanathan** [comment]
This is code i'm using
`<Button
                                    title="Sign In"
                                    titleStyle={{ fontFamily: 'regular', fontSize: 20, color: 'white', textAlign: 'center' }}
                                    buttonStyle={{
                                      height: 54, borderRadius: 100, 
                                    }}
                                    
                                    ViewComponent={LinearGradient}
                                    linearGradientProps={{
                                        colors: ['rgba(214,116,112,1)', 'rgba(233,174,87,1)'],
                                        start: { x: 0, y: 0.5 },
                                        end: { x: 1, y: 0.5 },
                                    }}
                                    containerStyle={{ marginVertical: 20 }}
                                    style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}
                                    onPress={() => console.log('Message Theresa')}
                                    activeOpacity={0.5}
                                />`

**Comment by xavier-villelegier** [comment]
@ManigandanRaamanathan What if you try to add the same radius to the `containerStyle` or `style` ?

**Comment by ManigandanRaamanathan** [comment]
Its still the same

**Comment by ManigandanRaamanathan** [comment]
@iRoachie @xavier-villelegier  if remove the borderRadius then the entire ripple not visible

**Comment by iRoachie** [comment]
@ManigandanRaamanathan Can you create a new issue to track this?
