### ISSUE TITLE
Rounded Button on Android has graphical bug

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1537]
**Explain what you did**
Create a button that's perfectly rounded.

**Expected behaviour**
It should work.

**Describe the bug**
There's a graphical issue on android.
<img width="206" alt="screen shot 2018-10-31 at 2 04 37 pm" src="https://user-images.githubusercontent.com/5962998/47809038-45828200-dd16-11e8-918f-29f87fe18e82.png">

**To Reproduce**
https://snack.expo.io/@roach_iam/dGhvdW

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |

**Comment by Monte9** [comment]
Good catch. Looks like when a `borderRadius` style property is added to `buttonStyle`, it even doesn't obey the ripple effect within the bounds. 

<img width="257" alt="screen shot 2018-10-31 at 11 56 56 am" src="https://user-images.githubusercontent.com/7840686/47811931-3bf01e80-dd04-11e8-9009-149eb1fd57e5.png">


Adding a `containerStyle={{ borderRadius: 150}}/>` fixes this.

<img width="236" alt="screen shot 2018-10-31 at 11 57 41 am" src="https://user-images.githubusercontent.com/7840686/47811932-3bf01e80-dd04-11e8-91d5-935be0fd224b.png">

**Comment by Monte9** [comment]
@iRoachie I found the bug for this issue. Currently, we are adding a `elevation: 4` to the button style. Adding a `elevation: 0` fixes that border UI issue.

<img width="298" alt="screen shot 2018-10-31 at 12 06 26 pm" src="https://user-images.githubusercontent.com/7840686/47812353-6abac480-dd05-11e8-920b-85d8d924cde0.png">

Here's the line that needs to be updated: https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L187

**Comment by Monte9** [comment]
great turnover on the PR + merge @iRoachie! 👏

**Comment by SiSa68** [comment]
I still have this issue in beta7 version. what should I do?

**Comment by iRoachie** [comment]
It's been fixed on`next` https://github.com/react-native-training/react-native-elements/pull/1538. It'll be available next release @SiSa68
