### ISSUE TITLE
React Navigation + Themes - navigationOptions being ignore

### ISSUE THREAD

**Issue by Monte9** [react-native-training/react-native-elements#1541]
Using React Navigation + RNE Themes

When exporting a class with `withTheme`, if the class has `static navigationOptions` it ignore it.

Snack to reproduce: https://snack.expo.io/@monte9/rne---showcase

**Comment by xavier-villelegier** [comment]
Actually the static methods are applied to the children, not to the HOC.
As a workaround, you can do:

```jsx
class HomeScreen…
…
const ThemedHomeScreen = withTheme(HomeScreen);
ThemedHomeScreen.navigationOptions = {
  title: 'Home',
};

export default ThemedScreen
```

If we know the static methods we want to forward to the children we can just copy it through the `withTheme` decorator. Of course, this implies that we have a list of methods we want to forward (see [this section of the React docs](https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over))

There is also the package [`hoist-non-react-statics`](https://github.com/mridgway/hoist-non-react-statics) that handles this kind of things for us, without having to know each static methods. Redux [uses this package](https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L1)
