### ISSUE TITLE
Button ripple effect overflow outside button container

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-native-training/react-native-elements#1543]
**Explain what you did**
Button ripple effect overflow outside button container. The ripple effect appears only after adding the borderRadius. Without the radius the ripple is not visible. When the ripple visible after adding borderRadius, the entire  ripple effect overflow outside the button forming a big circle ripple effect.

**Expected behaviour**
The ripple effect should be contained within the button.

This is code i'm using
<Button
title="Sign In"
titleStyle={{ fontFamily: 'regular', fontSize: 20, color: 'white', textAlign: 'center' }}
buttonStyle={{
height: 54, borderRadius: 100,
}}

 ViewComponent={LinearGradient}
 linearGradientProps={{
      colors: ['rgba(214,116,112,1)', 'rgba(233,174,87,1)'],
      start: { x: 0, y: 0.5 },
      end: { x: 1, y: 0.5 },
 }}
 containerStyle={{ marginVertical: 20 }}
 style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}
 onPress={() => console.log('Message Theresa')}
 activeOpacity={0.5}
/>

@xavier-villelegier  @iRoachie

**Comment by RyanTG** [comment]
You should probably state which version of RNE, and RN, you're using. 

But, I _think_ I'm experiencing this, as well. If mine's a different issue, I'll create my own issue. 

RNE 1.0.0-beta5, RN 0.54.0. **Android only**. It's fine on iOS.

See the screenshot below. Is the white background (with shadow) that I'm seeing the "ripple"? I'd love to find a solution! I've found that, in general, my buttons and icons are way different in iOS than Android. Beautiful in iOS, jacked up in Android :D

![screenshot_20181101-133717-clipped](https://user-images.githubusercontent.com/632682/47880881-bb9feb00-dde1-11e8-823b-3ff896df9957.jpg)

````
<View style={{padding:15}}>
                      <Button
                          onPress={() => this.props.navigation.navigate('Login')}
                          raised
                          buttonStyle={s.buttonBlue}
                          titleStyle={s.titleStyle}
                          title="Current User? Log In"
                          accessibilityLabel="Log In"
                      />
                      <Button
                          onPress={() => this.props.navigation.navigate('Signup')}
                          raised
                          buttonStyle={s.buttonPink}
                          titleStyle={s.titleStyle}
                          title="New User? Sign Up"
                          accessibilityLabel="Sign Up"
                      />
                      <Text 
                          onPress={() => {
                              this.props.loginLater()
                              this.props.navigation.navigate('Map')}} 
                          style={{fontSize:14,textAlign:"center"}}
                      >{"skip this for now"}
                      </Text>
</View>

    buttonPink: {
        backgroundColor:"#fdd4d7",
        borderRadius: 50,
        marginTop: 15,
        marginBottom: 25
    },
    buttonBlue: {
        backgroundColor:"#D3ECFF",
        borderRadius: 50,
    },
    titleStyle: {
        color:"black",
        fontSize:18
    }
````

**Comment by iRoachie** [comment]
This should be fixed in https://github.com/react-native-training/react-native-elements/commit/56733235c9d5b5a919bbba7e8173c1e484d8e3cf and available in 1.0.0 release. Probably was that the borderRadius wasn't also being applied to the container

**Comment by RyanTG** [comment]
Thanks. If I add `containerStyle={{borderRadius: 50}} to the buttons, it does indeed hide the white area behind the button. However, if the buttonStyle has margins (as I do with the pink button above), then those margins show up as white. I tried applying the margins to `style` instead, and didn't work. It's strange that in iOS, I can simply add padding to the buttonStyle and the buttons will be spaced apart, but not so on Android. I guess I need to wrap each button in its own View and apply the margin/padding there?

Anyway, I'll wait for 1.0.0.

**Comment by iRoachie** [comment]
You should never apply margins to the `buttonStyle`. `containerStyle` is for styles that affect how the component interacts with other components on the screen. If you're applying margins they should always be applied to the `containerStyle`

**Comment by RyanTG** [comment]
Ahh, gotcha. Thanks again! I don't have the deepest knowledge of which props accept which parameters. I get a little lost sometimes. RNE is great, though! Thanks for it.

**Comment by iRoachie** [comment]
That's okay! All good, if anyway you think the docs could be clearer, let me know. I'm always working on improving the docs :D

**Comment by RyanTG** [comment]
I'd been thinking about that as I work on my project. I hope to contribute to the docs when I'm done. But my basic desire is: I want to see an example of _everything_. Like, the examples at the top of https://react-native-training.github.io/react-native-elements/docs/button.html are invaluable for someone at my level (first RN project, and I'm a front-end dev/designer). And I get a little lost in the Reference section, because there aren't examples. Things like: how would I actually use `TouchableComponent`? Took me way too long to figure out that it's something like `TouchableComponent={TouchableOpacity}`

**Comment by iRoachie** [comment]
So a section like Frequent Asked Questions? With code snippets?

**Comment by xavier-villelegier** [comment]
Actually we could do something similar than Material UI docs ([see the Button docs](https://material-ui.com/demos/buttons/))
They show a lot of use cases using almost every props and you can expend the code of the examples

**Comment by iRoachie** [comment]
Yea that's pretty nice, they do seem to have two pages per component though, one for examples and one for the api.

**Comment by RyanTG** [comment]
Yeah, I think a FAQ might be too much of a burden to maintain. Like @xavier-villelegier mentioned, I think use cases for almost every prop would be nice. Your code snippet at the top covers a lot, but it still leaves out some of the commonly-used props. To work with the current layout of those pages, you could simply add more examples in there.

**Comment by iRoachie** [comment]
Yea but even with the approach from material-ui, a question like yours woudn't be covered. (TouchableComponent)

**Comment by iRoachie** [comment]
Any thoughts on this @RyanTG https://www.useloom.com/share/b7ac823fb9904c459696cd34c1a6a870 ?

**Comment by RyanTG** [comment]
This seems wise. The multiple usage sections would help link up the example styles (that are currently all at the top, with not much info saying what each one is) with the code for each one.

Just today a colleague said, "An example for every prop would be nice. Last night it took me forever to figure out which part of the ListItem needed to be styled to add highlighting to a selected machine." It's great having so many props, but there's an initial hurdle for new users when figuring out which ones should be used for certain things.

**Comment by iRoachie** [comment]
Thanks for the insight mate! Super helpful.
