### ISSUE TITLE
Passing in Animated values to search bar styles.

### ISSUE THREAD

**Issue by zsaraf** [react-native-training/react-native-elements#1548]
Is there any way to accomplish passing in Animated values into assorted searchbar styles? I would like to animate the following values: containerStyle, inputContainerStyle, inputStyle. I'm using a shared Animated.Value to add themes into my app! And the searchBar styles need to animate with the rest of the app. The only way I see of doing this right now is forking the entire project and making all of the relevant views Animated.View's. Any better way? Thanks

**Comment by xavier-villelegier** [comment]
Mmh for now there is no way to do that except forking the project. Some component have a `Component` props where you can pass what you want (like `Animated.View`) but this can become quite complicated  in the case of composed components like the `SearchBar`, that is using the `Input` under the hood for example. I'll let this opened if someone has a better idea though

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
