### ISSUE TITLE
Not able to set FormInput Focus via componentDidLoad event once page load. 

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-native-training/react-native-elements#1550]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Not able to set FormInput Focus via componentDidLoad event once page load.  I'm trying to set the textInput on focus when the page is load. But currently it is not working. It only works within it self as per the example code for form input focus upon onSubmitEditing.

**Expected behaviour**
Wants the text input on focus upon  navigated to the screen

**Describe the bug**
The traditional way as per react native doc is not working as well.

Example:

```bash
# Code
<FormInput
                                    refInput={input => {this.OTPInput = input;}}
                                    //icon="contacts"
                                    value={this.state.OTP}
                                    //editable={false}
                                    onChangeText={OTP => this.setState({ OTP: OTP })}
                                    placeholder="Enter OTP"
                                    keyboardType="numeric"
                                    returnKeyType="go"
                                    errorMessage={this.state.OTPValid ? null : 'Please enter a valid OTP'}
                                    onSubmitEditing={() => {
                                        if(this.validateOTP())
                                            this.OTPInput.focus()
                                        else
                                            this.continue
                                    }}
                                />

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements |  ^1.0.0-beta7 |
| react-native | 0.57.0 |
| npm or yarn | latest |

**Comment by iRoachie** [comment]
You can just use the `autoFocus` prop on the Input.

**Comment by ManigandanRaamanathan** [comment]
@iRoachie  I tried using autoFocus within the formInput but it wasn't working too

**Comment by iRoachie** [comment]
Where are you getting FormInput from? There's no FormInput component in 1.0.0-beta7. You mean the `Input` component?

**Comment by iRoachie** [comment]
Can you link to that example?

**Comment by ManigandanRaamanathan** [comment]
> Can you link to that example?

@iRoachie  this is the link refer to line 181
https://github.com/react-native-training/react-native-elements-app/blob/master/src/views/login/screen2.js

**Comment by ManigandanRaamanathan** [comment]
@iRoachie is it not working because the componentdidmount livecyle event couldn't identify because the inut component is located outside the class?

**Comment by iRoachie** [comment]
Here's an example using `autoFocus` prop https://snack.expo.io/@roach_iam/quiet-chips When you go to screen 2 it focuses the input

**Comment by ManigandanRaamanathan** [comment]
@iRoachie This isn't working in my case

**Comment by ManigandanRaamanathan** [comment]
@iRoachie  It works only if i setTimeout like 1000 milliseconds and then focus then (this.Input.focus() ) works. Else if directly calls out the focus, it won't work at all.

**Comment by iRoachie** [comment]
I can’t really help If I can’t reproduce the error. You have it in a repo or something ?

**Comment by ManigandanRaamanathan** [comment]
> I can’t really help If I can’t reproduce the error. You have it in a repo or something ?

Found solution. Thanks
