### ISSUE TITLE
Get value of checked checkboxes

### ISSUE THREAD

**Issue by Taimoormk** [react-native-training/react-native-elements#1555]
I don't seem to get values of checked react native checkboxes, I have used refs and tried to look through the event object but couldn't find the value of the checkbox in event object. 

Ideally, I would like to access checked value of react native checkbox through either, the event object or using the refs. It appears that <CheckBox /> doesn't accept ref attribute.

Would you please guide me how this can be done?

**Comment by Taimoormk** [comment]
Nevermind... I sorted this issue.

**Comment by iRoachie** [comment]
Don't forget to post your solution. Helps when others search for a similar issue!

**Comment by Taimoormk** [comment]
@iRoachie Thanks.

Actually, there wasn't any issue with the repo, rather with my thought process. I was trying to handle checkboxes like we handle text input fields, which is why I was trying to extract the checkbox value through either event or ref - but then realised that I can easily get the checkbox value via the props im sending to generate its component.

Hope it helps ...
