### ISSUE TITLE
weird; when use reac-native-elements icon, it does not accept the syntax in their website.!!!

### ISSUE THREAD

**Issue by nwabdou85** [react-native-training/react-native-elements#1558]
**Explain what you did**
I want to add some icons to my apps like smile-o of FontAwesome and also card

**Expected behaviour**
I expect to rendre me the icon and card.

**Describe the bug**
It throw an error for the icon and suggest me some names sometimes. for the card it display only the arrow even if I don't require an arrow in my card

**To Reproduce**

# Steps
1. Add a react native elements to app
2. add any icon with name from here https://oblador.github.io/react-native-vector-icons/
3. refresh the app
```


**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements |^0.19.1 |
| react-native | 0.57.3|
| npm or yarn | ^4.2.0|

**Comment by iRoachie** [comment]
You can see here that the icon `smile-o` works fine. 
Example - https://snack.expo.io/@roach_iam/arrogant-cheese.

Remember that you have to specify which font you want to use.

```jsx
<Icon name="smile-o" type="font-awesome" />
```

**Comment by nwabdou85** [comment]
@iRoachie  I specified the font  before. I will try your example and keep you in touche

**Comment by nwabdou85** [comment]
@iRoachie  the example you give me is the example I used; but this one for example does not work 
<Icon name='emoticon-sad' type='MaterialCommunityIcons' size={50}  color='red' />

and this is the secreen of the error
![emtionerror](https://user-images.githubusercontent.com/6404998/48156482-c7058180-e2cd-11e8-88fc-d2c3b4f2a1e6.png)

**Comment by iRoachie** [comment]
What code did you use to get this?

**Comment by nwabdou85** [comment]
the same one . but remplace  type = MaterialCommunityIcons; name=emoticon-sad

**Comment by nwabdou85** [comment]
Thank's for your relpy
alos when try entypo or Entypo like name and emoji-sad=type; does not work;

**Comment by iRoachie** [comment]
Working fine here https://snack.expo.io/@roach_iam/blessed-chocolate.
```jsx
<Icon name="emoji-sad" type="entypo" />
```
