### ISSUE TITLE
When a FormInput is in focus, the screen doesn't scroll to the element

### ISSUE THREAD

**Issue by nausharipov** [react-native-training/react-native-elements#1562]
When a FormInput is in focus, the keyboard covers the element instead of scrolling just below the FormInput as expected.

**Comment by iRoachie** [comment]
There's nothing about the TextInput component that controls scrolling to an element. There's no way the input can know about your other components on the screen. You have to implement this yourself.

Look at:
- KeyboardAvoidingView - https://facebook.github.io/react-native/docs/keyboardavoidingview#docsNav
- react-native-keyboard-aware-scrollview - https://github.com/APSL/react-native-keyboard-aware-scroll-view
