### ISSUE TITLE
[SocialIcon] Additional Social Network

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#1563]
**Is your feature request related to a problem? Please Describe.**
I want to use social networks's icons available from [FontAwesome](https://oblador.github.io/react-native-vector-icons/)

**Describe the solution you'd like**
Add social networks list in `SocialIcon` Component such `weibo`, `vkontakte`, `flickr`

**Additional context**
I've seen there is a [PR](https://github.com/react-native-training/react-native-elements/pull/1534) which will impact the current `SocialIcon` component.

Should i wait first that this PR is merged before opening mine ?

**Comment by iRoachie** [comment]
Will be live in 1.2.0
