### ISSUE TITLE
v1.0.0-beta7 Button style broken

### ISSUE THREAD

**Issue by hefengxian** [react-native-training/react-native-elements#1564]
**Explain what you did**

I'm using `"react-native-elements": "^1.0.0-beta7"` and I'm trying to write a login screen; then i found a problem  with the `Button` component from `react-native-elements`, the style is not I expected.

I copied code from the example  [login `screen1.js`](https://github.com/react-native-training/react-native-elements-app/blob/master/src/views/login/screen1.js#L126) , here is my code

```jsx
import React, {Component} from 'react'
import {StyleSheet, View, Dimensions, Text, ImageBackground} from 'react-native'
import {Button} from 'react-native-elements'

const BG_IMAGE = require('../assets/images/bg_login.jpg')

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
})

export default class Flexbox extends Component {
    render() {
        return (
            <View style={styles.container}>
                <ImageBackground source={BG_IMAGE} style={{flex: 1, alignItems: 'center'}}>
                    <View style={{flex: 1, backgroundColor: 'transparent'}}>
                        <Button
                            title='LOG IN'
                            activeOpacity={1}
                            underlayColor="transparent"
                            onPress={console.log('nothing...')}
                            loading={false}
                            loadingProps={{size: 'small', color: 'white'}}
                            disabled={false}
                            buttonStyle={
                                {
                                    height: 50,
                                    width: 250,
                                    backgroundColor: 'transparent',
                                    borderWidth: 2,
                                    borderColor: 'white',
                                    borderRadius: 30
                                }
                            }
                            containerStyle={{marginVertical: 10}}
                            titleStyle={{fontWeight: 'bold', color: 'white'}}
                        />
                    </View>
                </ImageBackground>
            </View>
        )
    }
}
```
then I got the result from Android Simulator

![image](https://user-images.githubusercontent.com/4338497/48182665-08963b00-e367-11e8-8998-c95e739f3b7f.png)

not the one from example, then I try to use `"react-native-elements": "1.0.0-beta5"` everything is OK, i got the button like this
![image](https://user-images.githubusercontent.com/4338497/48182768-6cb8ff00-e367-11e8-9ceb-b5debabc6ce6.png)

**Expected behaviour**
button style like this
![image](https://user-images.githubusercontent.com/4338497/48182768-6cb8ff00-e367-11e8-9ceb-b5debabc6ce6.png)

**Possible Solution**
maybe rollback the Button code to beta5

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7  |
| react-native | 0.57.4 |
| npm or yarn | npm 5.4.2 |

**Comment by iRoachie** [comment]
Hey @hefengxian  we have to update the example app. It hasn't been updated to reflect changes from our last release. Also they're some fixes and changes made on the button right now that fixes some errors on android. They'll be released in v1.

In v1, the example you were trying to achieve will be as easy as:
```js
<Button type="outline" title="LOG IN" />
```

**Comment by hefengxian** [comment]
@iRoachie  Very appreciate for your reply, when v1 release I will give a try. for now I'm using back to `beta5`
