### ISSUE TITLE
Ref to component inside `Overlay` inaccessible

### ISSUE THREAD

**Issue by platonish** [react-native-training/react-native-elements#1567]
**Explain what you did**
Tried to access a ref to a component wrapped within react-native-elements' `<Overlay/>`

**Expected behaviour**
Should be able to access the ref to the wrapped component

**Describe the bug**
The ref is inaccessible only when wrapped with `Overlay`. No problem without the `Overlay` wrapper.

**To Reproduce**
```javascript
_scrollToTop = () => {
  this.flatlist.scrollToIndex({ index: 0, animated: true }) // this.flatlist is undefined
}

...

render() {
  return (
    ...
    <Overlay
      isVisible={showSortDialog}
      height="auto"
      onBackdropPress={() => this.setState({ showSortDialog: false })}
    >
      <FlatList
        ref={ref => this.flatlist = ref}
      />
    </Overlay>

  )
}
```

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5|
| react-native | 0.56.0|
| npm or yarn | npm 6.4.1|

**Comment by iRoachie** [comment]
Seems to work, https://snack.expo.io/@roach_iam/sponaneous-candy

**Comment by platonish** [comment]
Thanks @iRoachie, unfortunately I'm not able to replicate the problem in isolation either. I guess I messed up the refs somewhere in my component. Closing this.
