### ISSUE TITLE
Avatar: Add example for editButton usage

### ISSUE THREAD

**Issue by jstansbe** [react-native-training/react-native-elements#1568]
Looking at the docs, avatar section, avatar with title placeholder subsection.
https://react-native-training.github.io/react-native-elements/docs/avatar.html

The gif doesnt match what the <ListItem /> code shows. I understand it's supposed to show placeholder and image loading... but the code to have the offset edit icon (pencil icon in gif) would be awesome!

Can the code to create the offset icon be included with the code snippet?

![image](https://user-images.githubusercontent.com/1250522/48290124-db698b80-e43f-11e8-8464-c90b80c0e21c.png)

**Comment by iRoachie** [comment]
You're correct! Avatar actually has a prop called `editButton` and `showEditButton` in the source but it's undocumented.

**Comment by epshtielsl** [comment]
@iRoachie Looks like if the Avatar is rounded, it cuts off the edit button.

**Comment by iRoachie** [comment]
@epshtielsl already fixed on next by https://github.com/react-native-training/react-native-elements/commit/acf5add5e4c0d37764810a3e6bdf608e29a75016#diff-01df5c99eb23405f8e8740d6c99aa666

**Comment by Sbphillips19** [comment]
@epshtielsl @iRoachie this isn't really an issue, so I didn't want to open anything, but is there a way to make the show edit button clickable? 

Lets say I had something like this:

```
<Avatar
                  size="xlarge"
                  rounded
                  source={{ uri: profilePicture }}
                  onPress={this.openPhotoPicker}
                  showEditButton
                />
```

The showEditButton isn't clickable.  Is the only way to get around this to wrap the whole Avatar with a onPress/ something like a TouchableHighlight?  Just wondering if there is a way to make it respond with the Avatar directly.

**Comment by iRoachie** [comment]
@Sbphillips19 Yea sure you can use the [`editButton`](https://react-native-training.github.io/react-native-elements/docs/avatar.html#editbutton) prop. It accepts all the props from the Icon component (including `onPress`).

```jsx
<Avatar showEditButton editButton={{ onPress: () => console.log('hey') }}/>
```

**Comment by syedamirali14** [comment]
where can i give size to this edit button icon?
any prop for that?

**Comment by iRoachie** [comment]
The same editButton prop accepts size property
