### ISSUE TITLE
linear-gradient in Header Component

### ISSUE THREAD

**Issue by angelos3lex** [react-native-training/react-native-elements#1569]
Hi, i have successfully installed react-native-linear-gradient and used it in other parts of my app. Though, i can't make it working on Header Component. I have tried like this:
```
<Header
        ViewComponent={LinearGradient}
        linearGradientProps={{
          colors: [colors.gradientLeft, colors.gradientRight],
          start: [1,0],
          end: [0.2,0],
        }}
        leftComponent={...}
        centerComponent={...}
        rightComponent={...}
      />
```
Is it supported?

**Comment by iRoachie** [comment]
There's no `ViewComponent` prop for the Header as yet. This sounds like a good idea to have though!

**Comment by mitulsavani** [comment]
hey @iRoachie 
I am not sure if I can def get this working but I wanna give it a shot!

With that being said I have never ever contributed to open source before!!
I did fork the repo and checked out `next` branch, but I wonder how I can run the code? I wanna see how it looks as I am changing things in.

Will really appreciate if you can give me pointers.

**Comment by iRoachie** [comment]
Oh awesome! Thanks for showing interest. There isn’t a smooth way to work and develop on react native libraries locally. 

Currently what i do is create a test project(either natively or with expo) - I mostly use expo cause it’s easier setup.

Then install react native elements pointing to your fork. So `npm install —save <github_url>`.

After I edit the files in node_modules. So `<my-project>/node_modules/react-native-elements`. After seeing if my changes work, I then copy them into my local fork of react native elements. And commit and push.

It’s not the best way! But that’s what we have right now.

**Comment by mitulsavani** [comment]
Thank you so much for the detailed info. It kinda sounds complex, but I will try to do it that way. Lets see what happens

**Comment by haruelrovix** [comment]
@mitulsavani any updates on this? 

You can refer to how Button component works with `ViewComponent`

```
  ViewComponent = !disabled && linearGradientProps && global.Expo
    ? global.Expo.LinearGradient
    : View
```

[source](https://github.com/react-native-training/react-native-elements/blob/aa47a38b141833454fc9a250d50d93634816cd83/src/buttons/Button.js#L54)

**Comment by mitulsavani** [comment]
@haruelrovix I haven't look into it yet :/  I was caught up doing some other things at work.

**Comment by iRoachie** [comment]
Will be live in 1.2.0
