### ISSUE TITLE
Can't remove border container checkbox.

### ISSUE THREAD

**Issue by huynguyen2903** [react-native-training/react-native-elements#1570]
How can I remove border color grey ?. I just want to show only cycle checkbox
![image](https://user-images.githubusercontent.com/40721082/48371412-68397100-e6ee-11e8-859d-f4a772e9b5ff.png)

**Comment by Abdalmajid** [comment]
just make the background color and border color to transparent as:
<CheckBox
title="hi"
containerStyle={{ backgroundColor: "transparent", borderColor: "transparent"}}
/>
