### ISSUE TITLE
[ThemeProvider] does not update on theme state change

### ISSUE THREAD

**Issue by piu130** [react-native-training/react-native-elements#1571]
**Explain what you did**
I tried to update the theme in `ThemeProvider` at runtime (see code).

**Expected behaviour**
The theme should update after changing state of `ThemeProvider`.

**To Reproduce**
```js
import React, { Component } from 'react';
import { ThemeProvider, Button, Text } from 'react-native-elements'

const createTheme = (color) => ({
  Button: { titleStyle: {color: color} }
})

export default class App extends Component {
  state = {
    color: 'red'
  };

  render() {
    return (
      <ThemeProvider theme={createTheme(this.state.color)}>
        <Text>{JSON.stringify(createTheme(this.state.color))}</Text>
        <Button title='Change Theme' onPress={() => this.setState({color: 'blue'})} />
      </ThemeProvider>
    );
  }
}

```
| react-native-elements | 1.0.0-beta7 |

Do you think this will be fixed for 1.0.0? I tried something like 
```js
componentDidUpdate (prevProps, prevState, snapshot) {
  if (this.props.colors !== prevProps.colors) this.forceUpdate()
}
```
but even with forceUpdate() it does not update the style.

**Comment by iRoachie** [comment]
That's not how we update the theme. If you want to update the Theme please use the withTheme hoc or the ThemeContext which both allow you to use the updateTheme function.

See https://react-native-training.github.io/react-native-elements/docs/customization.html#using-the-theme-in-your-own-components

**Comment by piu130** [comment]
@iRoachie @xavier-villelegier  Oh thanks that worked.

What so you think about adding this

```js
// use isEqual from lodash.isequal (new dependencie in package.json)
componentDidUpdate (prevProps, prevState) {
  const { theme } = this.props
  if (!isEqual(theme, prevProps.theme) && !isEqual(theme, prevState.theme)) 
    this.updateTheme(theme)
}
```

to the `ThemeProvider` so it does autoupdate on theme change?

I can create a PR if you wish.

**Comment by iRoachie** [comment]
Even though it's a simple change it. I wouldn't want that be the way that users use it. Also, isEqual is an expensive call since it deep checks objects.
