### ISSUE TITLE
ListItems in 1.0.0-beta7 have black backgrounds when pressed

### ISSUE THREAD

**Issue by epshtielsl** [react-native-training/react-native-elements#1573]
**Explain what you did**
Utilize the ListItem component 

**Expected behaviour**
Normal ListItem component

**Describe the bug**
There is now a black background when pressing ListItem components.  I do not see anywhere in the updated documentation that shows how to edit the color of the ListItem's outermost container.

**To Reproduce**
Upgrade from 1.0.0-beta5 to 1.0.0-beta7 and voila!  Now all your ListItem components will have an ugly black background when pressed (you can hold the press to further illustrate the issue).

**Example:**
I am aware I need to adjust my scale props.

```javascript
<ListItem
   leftAvatar={(this.props.imageUrl) ?
      <Avatar
         source={{ uri: this.props.imageUrl }}
         title={`${this.props.firstName.substring(0, 1)}${this.props.lastName.substring(0, 1)}`}
         titleStyle={{ fontFamily: 'Nexa Light' }}
         size='large'
         rounded
      />
   :
      <Avatar
         title={`${this.props.firstName.substring(0, 1)}${this.props.lastName.substring(0, 1)}`}
         titleStyle={{ fontFamily: 'Nexa Light' }}
         overlayContainerStyle={{ backgroundColor: COLORS.color1 }}
         size='large'
         rounded
      />
   }
   title={`${this.props.firstName} ${this.props.lastName}`}
   titleStyle={[commonStyles.text_normal, { color: (this.props.enableDark) ? COLORS.darkTheme.text : COLORS.lightTheme.text }]}
   subtitle={`${this.props.phone}\n${this.props.email}`}
   subtitleStyle={[commonStyles.text_normal, { color: COLORS.placeholderText }]}
   chevron
   chevronColor={(this.props.enableDark) ? COLORS.darkTheme.text : COLORS.lightTheme.text}
   onPress={() => this.props.navigation.navigate('UserInfo')}
   scaleProps={{
      friction: 90,
      tension: 100,
      activeScale: 0.90,
   }}
   containerStyle={[commonStyles.card_viewStyle, { backgroundColor: (this.props.enableDark) ? COLORS.darkTheme.view : COLORS.lightTheme.view }]}
/>
```

**Screenshots**

![simulator screen shot - iphone 6s - 2018-11-13 at 23 58 43](https://user-images.githubusercontent.com/40307141/48461591-616c3600-e7a2-11e8-96f7-4472edef85f9.png)

![simulator screen shot - iphone 6s - 2018-11-14 at 00 07 29](https://user-images.githubusercontent.com/40307141/48461595-65985380-e7a2-11e8-9a55-c8e22cc28146.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.56.0 |
| npm or yarn | yarn |

**Comment by xavier-villelegier** [comment]
@epshtielsl You're right, actually we changed the wrapper component that's why it acts differently.
As a workaround you can add `component={TouchableOpacity}` to your `ListItem`'s props.

@martinezguillaume Why did we switch from `TouchableOpacity` to `TouchableHighlight` ? [Here is the cange](https://github.com/react-native-training/react-native-elements/blame/d42ccb57d03ae2ec92d79b0e455ca8684931ca73/src/list/ListItem.js#L7)

**Comment by iRoachie** [comment]
I think TouchableHighkight is actually what iOS uses for lists

**Comment by epshtielsl** [comment]
@xavier-villelegier Looks like that fixed the issue.  All that's left is adding the correct typings for component to play nicely with Typescript.  Thanks!

**Comment by iRoachie** [comment]
@epshtielsl what typings do we need to change?

**Comment by epshtielsl** [comment]
![screen shot 2018-11-15 at 10 06 47 am](https://user-images.githubusercontent.com/40307141/48561569-3aa32200-e8be-11e8-8b05-6bc840ce1d5d.png)

Above is the error I am seeing when I try to assign TouchableOpacity to the component prop.  But it may not be react-native-elements related, now that I look at it.

**Comment by iRoachie** [comment]
Also fixed on next. https://github.com/react-native-training/react-native-elements/blob/next/src/index.d.ts#L1062

**Comment by xavier-villelegier** [comment]
Closing this as the original issue can be fixed by adding `component={TouchableOpacity}`. (Not using the label `fixed next release` as it can be confusing with the issue title.)

**Comment by SinanBaymammadli** [comment]
better just give `underlayColor="transparent"`

**Comment by jacobsmith** [comment]
@xavier-villelegier Is there any way to update the types of `ListItem` to support `underlayColor`? I'm still new with TypeScript and would make the PR, but I'm not sure how to support `underlayColor` only if `Component` evaluates to `TouchableHighlight`.

**Comment by iRoachie** [comment]
@jacobsmith Could you open a separate issue about this? I'll help you through it

**Comment by jacobsmith** [comment]
@iRoachie I opened up https://github.com/react-native-training/react-native-elements/issues/1842 to move it to a separate issue. Thanks for any guidance you can provide!
