### ISSUE TITLE
(1.0.0-beta7) Header component height issue in android 

### ISSUE THREAD

**Issue by kumaresan-cgvak** [react-native-training/react-native-elements#1574]
Hi I was trying to use the Header component in my app, the header component was working as expected in iOS but in Android I am getting status bar height along with the header component. Is there anyway to remove the status bar height from Android.

Here is the code snippet I have used:

```
<Header
            centerComponent={<Text>Title</Text>}
          rightComponent={
            <Image source={require('../../assets/images/navbar-logout.png')} />
          }
        />
```

Here is the result I am getting in Android and iOS:

Example:
![image](https://user-images.githubusercontent.com/5547152/48479100-49d98f80-e82c-11e8-92d5-702945ef90d8.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native |0.57.5 |
| npm or yarn |6.4.1 |

**Comment by kumaresan-cgvak** [comment]
in this file

**Comment by kumaresan-cgvak** [comment]
The possible fix could in file `config/statusBar.js`. Where we need to update the `getStatusBarHeight` function as follows.

```
export function getStatusBarHeight() {
  if (Platform.OS === 'ios') {
    return ifIphoneX(44, 20);
  } else {
    return 0;
  }
}
```

**Comment by iRoachie** [comment]
What version of android are you doing this test on? We use a library for doing this now on next https://github.com/react-native-training/react-native-elements/pull/1553

**Comment by kumaresan-cgvak** [comment]
In latest android version (API 28).

**Comment by iRoachie** [comment]
Alright, this is fixed on next.

![screenshot_1542293436](https://user-images.githubusercontent.com/5962998/48560499-501b4a80-e8c4-11e8-96b3-ba82d1dd1dbc.png)

**Comment by iRoachie** [comment]
Look out for 1.0.0 release

**Comment by KPS250** [comment]
> Look out for 1.0.0 release

When can we expect the next release?

**Comment by iRoachie** [comment]
Was going to be tonight, however it’s a long weekend Monday (holiday) and some of the maintainers are out. Will still try to wrap up this weekend though

**Comment by Theng** [comment]
1.0.0 just release, I still have this problem.
