### ISSUE TITLE
Avatar, 1.0.0-beta7: Expose Avatar's placeholderStyle in index.d.ts file

### ISSUE THREAD

**Issue by epshtielsl** [react-native-training/react-native-elements#1578]
**Explain what you did**
Change the backgroundColor property on Avatar component.

**Expected behaviour**
overlayContainerStyle property was used in the past to change the backgroundColor.

**Describe the bug**
overlayContainerStyle no longer changes the background color of the Avatar component.  After some digging, it looks like the placeholderStyle property can be used for the same result.  However, placeholderStyle is not exposed in the index.d.ts file, so Typescript throws an error when trying to edit.

**To Reproduce**
Example:
```javascript
<Avatar
   size='large'
   rounded
   title={`${employee.user!.name.split(' ')[0].charAt(0)}${employee.user!.name.split(' ')[1].charAt(0)}`}
   source={(employee.user!.avatar === 'some url') ? undefined : { uri: employee.user!.avatar }}
   placeholderStyle={{ backgroundColor: 'blue' }}
/>
```

**Possible Solution**
Add placeholderStyle to index.d.ts, or change the code so that overlayContainerStyle functions again.

**Your Environment (please complete the following information):**
| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.56.0 |
| npm or yarn | yarn |

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/81d241b234cab7cbad2553c61336da570d5e1c72. Will be available next release.

**Comment by souhaiebtar** [comment]
@epshtielsl in your issue  #1573, about the snippet in the example, would you please 
share with me `commonStyles.card_viewStyle` style because i really liked i want to use this style thanks anyway
