### ISSUE TITLE
Upgrade "react-native-vector-icons" dependency

### ISSUE THREAD

**Issue by incrediblink** [react-native-training/react-native-elements#1581]
**Is your feature request related to a problem? Please Describe.**
Many icon websites such as Ionic have been updating their icon libraries. The version of the `react-native-vector-icons` used in `react-native-elements` is just too old (^4.4.2), considering that module is currently in its [6.1.0](https://www.npmjs.com/package/react-native-vector-icons) version.

**Describe the solution you'd like**
Upgrade the dependency. Adapt to the new APIs, if any change.

**Comment by iRoachie** [comment]
How were you trying to use the icons?

**Comment by incrediblink** [comment]
@iRoachie I was trying to use the Ant-Design icon library. I found out that you guys have supported that in the latest `next` branch. I guess I'll just sit tight and wait for the v1.0.0@beta-8 rolled out.

**Comment by iRoachie** [comment]
Yea we added it in already. Fear not there's no beta8, we're going 1.0.0!
