### ISSUE TITLE
SearchBar - Changing Search Icon

### ISSUE THREAD

**Issue by renato-bvdash** [react-native-training/react-native-elements#1589]
In my project I am required to set the Search Icon of the SearchBar but I am not finding a way to do it. I have been searching for hours on how to do this. I'm baffled it's not [possibly] implemented yet.

My icon is an SVG file (and I am using react-native-svg-uri to render it), but support for images, or fonts will even do the job.

I have no alternatives since I haven't found a way to hack it.

**Comment by renato-bvdash** [comment]
I am using the default platform, possibly will change to the ios look later.

I am using react-native-elements 1.12.3

**Comment by iRoachie** [comment]
We don't have a version 1.12.3?

**Comment by renato-bvdash** [comment]
My bad. Seems the terminal goofed on me. Package.json says the version is ^0.19.1

**Comment by xavier-villelegier** [comment]
@renato-bvdash Try to install the `1.0.0-beta7` where the SearchBar has been reworked, [here is the documentation](https://react-native-training.github.io/react-native-elements/docs/searchbar.html#platform-specific-searchbar)

To install the beta:
```
npm i react-native-elements@beta
```

You'll be able to use the `searchIcon` props to pass a custom component here 👍

**Comment by renato-bvdash** [comment]
Thank you! I changed to the beta, but I seem to be getting a side effect error now:
![screen shot 2018-11-20 at 09 31 02](https://user-images.githubusercontent.com/44821537/48780096-1329cc00-eca7-11e8-9729-7c7a22960489.png)

I am currently using these packages:
import React, { Component } from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
import { List, ListItem } from 'react-native-elements';
import { FlatList, Text } from 'react-native';

I can share the full code if so required.

**Comment by xavier-villelegier** [comment]
The `List` component doesn't exist anymore, it was just a styling wrapper. The `ListItem` API has also some breaking changes, see [the docs](https://react-native-training.github.io/react-native-elements/docs/listitem.html)

**Comment by iRoachie** [comment]
If you just want to change the icon to another icon, you can stay on 0.19.1 and use the [`icon`](https://react-native-training.github.io/react-native-elements/docs/0.19.1/searchbar.html#icon) prop

![image](https://user-images.githubusercontent.com/5962998/48780554-96035480-ecb0-11e8-83d0-7ad0e755ae53.jpeg)

```jsx
<SearchBar icon={{ name: 'home' }} />
```

**Comment by renato-bvdash** [comment]
OH! May the Gods smile upon you! I have successfully fixed the side issue and changed the icon too :D This may be closed!

**Comment by xavier-villelegier** [comment]
My bad I thought you wanted to use a custom component 😄 Note that you won't be able to use your custom svg icon with v0.19.1, unless you use a custom font icon. Only v1+ allows you to pass a custom component for the search icon

**Comment by Rutheniceye92** [comment]
What if dont use **icon** prop and want my custom image in that place, How can i pass my own component in place of default icon?

**Comment by Rutheniceye92** [comment]
> @Rutheniceye92 The icon prop can render custom elements.
> 
> ```js-jsx
> <SearchBar searchIcon={<View />} />
> ```

Imma try this now and let you know in a moment..

**Comment by Rutheniceye92** [comment]
@iRoachie I tried, didn't work.

 ```
<SearchBar
      placeholder="Type Here To Search"
      lightTheme
      round
      onChangeText={text => this.searchFilterFunction(text)}
      autoCorrect={false}
      searchIcon={<View><Image source={require('../res/search.png')} style={{ width: 15, height: 15}} /></View>}
      noIcon
    />
  );
};
```

**Comment by iRoachie** [comment]
Not sure what you are doing. I hope you are using the right version of react-native-elements.

This is with 1.0.0

![screen shot 2019-02-01 at 9 06 55 am](https://user-images.githubusercontent.com/5962998/52124821-deb88180-2600-11e9-99d3-8fc9725e4477.jpg)

https://snack.expo.io/@roach_iam/healthy-cheese

**Comment by Rutheniceye92** [comment]
@iRoachie  Turns out I was using 0.19.1 and it didn't have any searchIcon prop. So i updated react-native-elements and now it works.

In case anyone else ends up having same issue: to update run `npm install react-native-elements@* --save`
