### ISSUE TITLE
demo impossible with Expo

### ISSUE THREAD

**Issue by CorentinHeroux** [react-native-training/react-native-elements#1596]
demo impossible with Expo :/ 

This project needs an update
This project uses Expo SDK v23.0.0

![sans titre](https://user-images.githubusercontent.com/25199721/48906659-7a8d7a80-ee65-11e8-88a1-0177f344ecc2.png)

**Comment by iRoachie** [comment]
Duplicate of https://github.com/react-native-training/react-native-elements-app/issues/62
