### ISSUE TITLE
round button

### ISSUE THREAD

**Issue by kouraf** [react-native-training/react-native-elements#1597]
Hello
how about create a round button ? 
it will simplify our life 
![oval_shape_android_button](https://user-images.githubusercontent.com/22027736/48918502-4d54c280-ee8d-11e8-8829-6ef61387a2e4.png)
thank you

**Comment by andrewmarmion** [comment]
If you pass a prop of buttonStyle to the button then you can change how the button looks. The following will make the a round button with a height and width of 60, settings the border radius to be half the height and width will give the desired effect. 

```
<Button
  ...
  buttonStyle={{height: 60, width: 60, borderRadius: 30}}
  ...
/>
```

See the docs for more information [https://react-native-training.github.io/react-native-elements/docs/0.19.1/button.html#buttonstyle](https://react-native-training.github.io/react-native-elements/docs/0.19.1/button.html#buttonstyle)

**Comment by Louis345** [comment]
@andrewmarmion thanks man helped me also.
