### ISSUE TITLE
FA5 light or solid conditional

### ISSUE THREAD

**Issue by nica0012** [react-native-training/react-native-elements#1598]
Hi all, 

for FontAwesome5Pro, is there a way to conditionally have the icon render as light or regular?

example:

      <FontAwesome5Pro
        name={'images'}
        color={props.focused ? colors.green : colors.grayIcon}
        size={24}
        solid //make solid if props.focused and light when not focused (like the color's ternary operator)
      />

I am not to sure how to do this without a key.

Cheers.

**Comment by iRoachie** [comment]
I think you have the wrong repo, Try opening an issue over at https://github.com/oblador/react-native-vector-icons
