### ISSUE TITLE
Social button/icon type: Google

### ISSUE THREAD

**Issue by atrauzzi** [react-native-training/react-native-elements#1600]
I haven't [seen a new issue](https://github.com/react-native-training/react-native-elements/issues/1500#issuecomment-432767984) by @massivespace yet and I've just started using some of the social buttons in this library.

Given that Google Plus is being shut down, I would love to see a non-google-plus third party auth button added to this library.

Probably something akin to this: https://developers.google.com/identity/sign-in/android/

**Comment by iRoachie** [comment]
More info https://developers.google.com/identity/branding-guidelines

**Comment by iRoachie** [comment]
Not sure what we can do with this. They're no icon sets from react-native-vector-icons that would have the colored "G" and google only provides svg and images.

**Comment by atrauzzi** [comment]
Hm.  I'm thinking something will have to happen because it's not going to be around for much longer, but google login is still going to be a thing.

**Comment by iRoachie** [comment]
Merged. Will be available in 1.2.0
