### ISSUE TITLE
Bug: rightTitle prop for ListItem works incorrectly solo

### ISSUE THREAD

**Issue by janhesters** [react-native-training/react-native-elements#1605]
**Explain what you did**
I wanted to display an item, that just has a `rightTitle`.

**Expected behaviour**
I expected the title to show up on the right of the item.

**Describe the bug**
The title appears in the middle of the item.

**To Reproduce**
1. Create a new RN project: `react-native init rnebug`.
2. Install React Native Elements:
```
npm install --save react-native-elements@beta react-native-vector-icons && react-native link
```
3. Replace the code in `App.js` with the following:
```
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import { ListItem } from "react-native-elements";

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <ListItem rightTitle="Hello" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#F5FCFF"
  }
});
```
4. Run your app and see the bug.

**Possible Solution**
Can you suggest a possible fix that would address this issue?
Not yet, no. It probably has to do with the styling of the item or something.

**Screenshots**
<img width="744" alt="screenshot 2018-11-27 at 09 29 20" src="https://user-images.githubusercontent.com/31096420/49068409-f4878000-f226-11e8-8fb1-26d25b02a7c5.png">

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 | 
| react-native |  0.57.6 |
| npm or yarn | 6.4.1 | 

**Edit:**
This also applies if you just add a rightSubtitle (`<ListItem rightTitle="Hello" rightSubtitle="World" />`).

**Comment by iRoachie** [comment]
Definitely a bug. Reproduced here https://snack.expo.io/@roach_iam/frisky-waffle. That's because the title isn't rendered when it's empty.

A workaround for right now is to set the title to an empty string.

```jsx
<ListItem title=" " rightTitle="Hey" />
```
