### ISSUE TITLE
SearchBar not considering 'allowFontScaling' prop

### ISSUE THREAD

**Issue by prateekgoel** [react-native-training/react-native-elements#1622]
While using `<SearchBar />` it seems that it is not considering the allowFontScaling prop provided by the React Navite's `<TextInput />`.
When I pass `allowFontScaling` as `false`, and increase the device font size, the Search input font size also scales.

I am testing on Android Pie. Device - Google Pixel 2

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.56.0 |
| npm or yarn | npm 6.2.0 |

**Comment by iRoachie** [comment]
Which SearchBar were you using? default, ios, or android?

**Comment by prateekgoel** [comment]
@iRoachie I am using the default SearchBar.

**Comment by iRoachie** [comment]
@xavier-villelegier can you look into this?

**Comment by xavier-villelegier** [comment]
@prateekgoel Actually I don't think it comes from the props itself, because we're passing every props to the `TextInput` of React Native (easy to test by setting a `selectionColor` to the `SearchBar`).

I just tested and the `allowFontScaling` is passed to the `TextInput`.

I never used this props, could it be because we pass a `fontSize` to the `TextInput` ?

**Comment by xavier-villelegier** [comment]
Closing this as it is a React Native issue. You can track it here https://github.com/facebook/react-native/issues/17898

**Comment by AaronWatson2975** [comment]
I had this issue and it was because I was setting Text.defaultProps.allowFontScaling = false when I should have been setting it on Input.


```
import { Input } from 'react-native-elements';

if (Input.defaultProps == null) {
  Input.defaultProps = {};
}
Input.defaultProps.allowFontScaling = false;
```

**Comment by tarung** [comment]
> I had this issue and it was because I was setting Text.defaultProps.allowFontScaling = false when I should have been setting it on Input.
> 
> ```
> import { Input } from 'react-native-elements';
> 
> if (Input.defaultProps == null) {
>   Input.defaultProps = {};
> }
> Input.defaultProps.allowFontScaling = false;
> ```

Found this after searching a lot, and worked fine Thanks!!
