### ISSUE TITLE
fontFamily isn't working with Tile titleStyle

### ISSUE THREAD

**Issue by martinbcg** [react-native-training/react-native-elements#1633]
react-native-elements version: 0.19.1
react-native version: 28

**Comment by iRoachie** [comment]
Seems to be working fine https://snack.expo.io/@roach_iam/mad-pizza

**Comment by martinbcg** [comment]
Thanks for the test @iRoachie. 

It's very weird, since I can't make it work in my code. The attribute `titleStyle` works fine with other options like `fontSize`, but nothing happen when I use `fontFamily`. 🤷🏻‍♂️

**Comment by iRoachie** [comment]
Make sure your custom font is actually loaded correctly.

**Comment by martinbcg** [comment]
It is, the same font works perfectly with other elements, event it works fine with Tile's `captionStyle`.

**Comment by iRoachie** [comment]
I'm assuming this is on android, you'll have to set the fontWeight to 400.

**Comment by martinbcg** [comment]
@iRoachie thank you!! You saved my life 🙌

**Comment by eambutu** [comment]
Wait, I'm confused here. What is the relevance of 400 for the fontWeight?

**Comment by iRoachie** [comment]
Custom fonts on mobile don't have weights within a single font file. Instead you add a ttf for each weight so:
- mycustomfont-regular.ttf
- mycustomfont-bold.ttf

By default the `titleStyle` on the Tile uses `fontWeight: bold` cause it's using the **system font**. 

However, when you use font family and set your custom font along with `fontWeight: bold`,it'll begin looking for the bold variant of your font which doesn't exist so it defaults back to the original. Setting `fontWeight: 400` tells android we're not using a single font file that has different weights. Instead we're explicitly providing a different font file for every weight we want to use.
