### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'y.hasOwnProperty')

### ISSUE THREAD

**Issue by cateixeira** [react-native-training/react-native-elements#1634]
My Expo snack suddenly  stopped working showing this message!

**Comment by cabteix** [comment]
and now it shows all sorts of error messages like... TypeError: TypeError: undefined is not an object (evaluating 'y.hasOwnProperty')

**Comment by iRoachie** [comment]
Did you figure it out?

**Comment by cabteix** [comment]
I believe they changed something in the library... it keeps showing this error :(

**Comment by cabteix** [comment]
they must have changed something in their library... it keeps showing error messages :(

**Comment by iRoachie** [comment]
Aware of this bug, we have to release a new version for the them to fix it.

**Comment by cabteix** [comment]
when?!

**Comment by cabteix** [comment]
is there a stable (older) version I could use in the meantime?

**Comment by iRoachie** [comment]
What version were you using in your snack?

**Comment by cabteix** [comment]
"react-native-vector-icons/MaterialIcons": "6.1.0"

**Comment by iRoachie** [comment]
Of react native elements

**Comment by Myll** [comment]
I'm also seeing this issue with my Expo snack, `"react-native-elements": "^1.0.0-beta7"`.

**Comment by iRoachie** [comment]
This seems to be working now again. Just tested using 1.0.0
