### ISSUE TITLE
Theming requires explicit empty object in the element to work

### ISSUE THREAD

**Issue by tiagoalves** [react-native-training/react-native-elements#1635]
I'm using v1.0.0-beta7 and the theming feature seems to be working fine. However, I had to implement a small workaround for it to work as expected.

It seems as if I must pass an object, even if empty, for the theming feature to take effect in a  particular theming override. For instance, if I'm overriding a Header's `containerStyle`, I have to explicitly pass `<Header containerStyle={{}} ... />` when creating the Header element. Otherwise, the theming properties have no effect.

(Btw, In issue 1629 I mentioned everything was working fine but I forgot about this workaround I had to implement)

I was expecting the Theming feature to not require us to provide a base setting for the properties we're trying to override in the theme.

**Expo**

I tried to create a snack but it kept throwing the error `Device: (XXXX:YYY) Unable to resolve module 'module://expo-font.js'`.

Here's the code anyway:

```bash
# Snack

import * as React from 'react';
import { View } from 'react-native';
import { Constants } from 'expo';
import { Header, ThemeProvider } from 'react-native-elements';

const rneTheme = {
  Header: {
    containerStyle: {
      borderBottomColor: "red",
      borderBottomWidth: 2
    },
    backgroundColor: "green"
  }
}

export default class App extends React.Component {
  render() {
    return (
      <View style={{ paddingTop: Constants.statusBarHeight }}>
        <ThemeProvider theme={rneTheme}>
          <Header
            leftComponent={{ icon: 'menu', color: '#fff' }}
            centerComponent={{ text: 'MY TITLE', style: { color: '#fff' } }}
            rightComponent={{ icon: 'home', color: '#fff' }}
            containerStyle={{}} // this is required, ortherwise the theme's `Header > containerStyle` will have no effect
          />
        </ThemeProvider>
      </View>
    );
  }
}
```

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.57.4 |
| npm or yarn | yarn |

**Comment by xavier-villelegier** [comment]
Oops missclicked

**Comment by iRoachie** [comment]
Can't reproduce, works fine https://snack.expo.io/@roach_iam/spunky-ramen. (may have to export and run locally, snack doing weird things)

**Comment by tiagoalves** [comment]
Apologies, you're right. If the property `containerStyle` is not passed (undefined), it works as expected.

I was setting my `containerStyle` to `null` in my wrapping component's `.defaultProps`.

So, the following allows reproducing the error:

```
<Header 
  // ...
  containerStyle={null}
/>
```

Maybe it should still be considered an issue but I'll leave it up to you guys to close the issue if you think it works as designed.

Thanks.

**Comment by iRoachie** [comment]
Null and undefined are different things in javascript, defaultProps only work if the param is not present(undefined). Null is an actual value and defaultProps won't work

**Comment by tiagoalves** [comment]
Sounds good to me. Feel free to close the issue.
