### ISSUE TITLE
Recommended version for new projects?

### ISSUE THREAD

**Issue by Slapbox** [react-native-training/react-native-elements#1636]
When starting a new project is it recommended to use the `0.19.x` versions, or the `1.0.0` betas? With some projects using a late stage beta is recommended over starting with the stable version, but it seems like there's a very long release cycle at play in this case.

Does the documentation for `1.0.0` differ significantly and is there somewhere to find that documentation?

**Comment by kdbcinco-cs** [comment]
Go for the latest stable release if its enough for your needs. The beta versions are "stable enough", though I'd recommend going with `1.0.0-beta5` as I had issues with `1.0.0-beta7`. You'd be missing out with the `ThemeProvider` in `beta7`, though I think we'll be getting `1.0.0` this month or the next.

**Comment by iRoachie** [comment]
Correct going @kdbcinco-cs the last beta (1.0.0-beta7) had a few issues we missed while testing. For now, I'd recommend using beta5. 

We have documentation for each release both on github and on the website. 
Github: https://github.com/react-native-training/react-native-elements/releases
Website: https://react-native-training.github.io/react-native-elements/versions.html

v1.0.0 should release this month.

**Comment by Slapbox** [comment]
Thanks for the info @kdbcinco-cs and @iRoachie! That helps a lot.
