### ISSUE TITLE
Feature Request :- Add Linear Gradient Component for Views and components.

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-training/react-native-elements#1643]
**Is your feature request related to a problem? Please Describe.**

When i added linear gradient of react native then so many work in ios and android too.

**Describe the solution you'd like**

Want a component For Gradient like input & Tooltip and all.
because react-native -elements is the best library in react native.
i love its all component. 

**Describe alternatives you've considered**
Right now, I am using react-native linear-gradient.

**Comment by iRoachie** [comment]
Gradients are native modules by default, so it'll be pretty hard to have a gradient component which doesn't rely on`react-native-linear-gradient`. We don't have any plans to rewrite a gradient component. We'd prefer to use the well known and battle tested react-native-linear-gradient package instead.

**Comment by Biplovkumar** [comment]
Thanks @iRoachie
