### ISSUE TITLE
Proptypes error with ListItem

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1645]
**Explain what you did**
Use the ListItem component

**Expected behaviour**
Should display ListItem with the title without any errors.

**Describe the bug**
PropType error shows for padview

**To Reproduce**
Example:

```jsx
<ListItem title="Hey" />
```

**Possible Solution**
Update the propType to include object

**Screenshots**
![simulator screen shot - iphone x - 2018-12-05 at 10 57 31](https://user-images.githubusercontent.com/5962998/49521961-e5cf4780-f87c-11e8-9975-b6fcb4fc80f4.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |

**Comment by sshmyg** [comment]
Have same issue for version `1.1.0`

**Comment by iRoachie** [comment]
@sshmyg please create a new issue. Also trying using `1.2.x` to see if you are still encountering the problem there
