### ISSUE TITLE
ButtonGroup, onPress doesn't get triggered

### ISSUE THREAD

**Issue by mojtabamarashee** [react-native-training/react-native-elements#1650]
In the following simple ButtonGroup, when the middle button's **text** (`World`) is touched,  the onPress doesn't get triggered.
the problem doesnt exist with first and third buttons

 ```js
 renderHeader = () => {
    const buttons = ['Hello', 'World', 'Buttons']
    return (
      <ButtonGroup
        selectedIndex={this.state.selectedIndex}
        onPress={this.SetSelected}
        buttons={buttons}
      />
    );
  };
```

version :
react-native-elements@1.0.0-beta7

**Comment by iRoachie** [comment]
I can't seem to replicate this, did you encounter on android or iOS

**Comment by mojtabamarashee** [comment]
on android.

**Comment by iRoachie** [comment]
Still unable to replicate, Can you create an example on https://snack.expo.io that reproduces this?

**Comment by mojtabamarashee** [comment]
Yep, I will

**Comment by calebbriggs** [comment]
I am seeing the same thing

**Comment by calebbriggs** [comment]
```
<ButtonGroup
            buttons={[
              { element: () => <Text>10</Text> },
              { element: () => <Text>25</Text> },
              { element: () => <Text>50</Text> },
              { element: () => <Text>100</Text> }
            ]}
            selectedIndex={selectedButton}
           
            onPress={i => {
              this.setState({ selectedButton: i });
            }}
          />
```
"react-native-elements": "^0.19.1"
"react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
"react": "16.5.0"

**Comment by mojtabamarashee** [comment]
Why there is not any test for call of `onPress `prop in ` __tests__/ButtonGroup.js` ?

**Comment by iRoachie** [comment]
@calebbriggs i can't replicate this on iOS nor Android. Your exact example works fine. When i press the text it updates

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
