### ISSUE TITLE
Cancel button should be Touchable Opacity instead of Button for SearchBar-ios.js

### ISSUE THREAD

**Issue by renato-bvdash** [react-native-training/react-native-elements#1654]
**Explain what you did**
Setup the platform look to ios.

**Expected behaviour**
Expected to see the Cancel button as I do in iOS: Transparent background color, just the text in it.

**Describe the bug**
Not so much of a bug, but rather an oversight: In android, buttons have a certain style, and thus the ios look-and-feel is not persistent.

**To Reproduce**
Use SearchBar with `platform="ios"` on android.

**Possible Solution**
Switch to TouchableOpacity

**Screenshot**
![image](https://user-images.githubusercontent.com/44821537/49665541-354f7800-fa23-11e8-8f59-a4d09acd2ffa.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | ^1.0.0-beta7 |
| react-native | 0.57.4 |
| yarn | 1.12.3 |

**Comment by iRoachie** [comment]
Already implemented in https://github.com/react-native-training/react-native-elements/commit/733e38c39a115e84942e6d3e9ad2ca68bdcf51bd
