### ISSUE TITLE
Bug: Spaces at the end of the input string do not display while editing inside ListItem.  They only appear after editing is complete

### ISSUE THREAD

**Issue by lukewlms** [react-native-training/react-native-elements#1655]
**Explain what you did**
Create an input control within ListItem

**Expected behaviour**
When typing into the control, the full string is shown with spaces.

**Describe the bug**
Spaces at the end of the string do not appear until a non-space character is typed.

This creates a bad user experiences as it appears the spaces are not being registered.

**To Reproduce**
1. Create a list item input
2. In the app, start editing it.
3. Type any number of spaces

RESULT: Spaces do not show up until another non-space character is pressed.

**Possible Solution**
Make sure that **while editing** the input is shown with all spaces, untrimmed.  (Note that *after* editing the spaces do display.)

**Screenshots**
GH is rejecting the upload right now for some reason

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
react-native-elements@^1.0.0-beta7:
react-native@0.57.5:
yarn@1.12.3

**Comment by iRoachie** [comment]
Closing as this seems to be the solution. Feel free to message or create a new issue if this is still a concern.
