### ISSUE TITLE
Text component h1 - h4 props don't follow order of styles

### ISSUE THREAD

**Issue by shawnventi** [react-native-training/react-native-elements#1663]
**Explain what you did**
I am working to add RNE to my RN project. I've used the RNE Text component a few different places with various different styles. The styles have been applied both externally and via a theme.

**Expected behavior**
When applying any of the h1 - h4 props externally I expected them to override my default font size style that I have set within my theme. 

**Describe the bug**
Either this is a bug or the documentation for these props should be adjusted. Digging into the source for this version I believe I have discovered what is happening.

When you use any of the h1 - h4 props on a Text component the provided value (either true or false) is passed in externally. The problem is that passing in those props externally I expect the style that those props control to also be applied externally however that is not the case. The props are passed down through the theme wrapper to the internals of the component and then the correct style is applied. Given this order of operations, the style set inside the theme overrides the h1 - h4 set style as it should the way the code is written.

https://github.com/react-native-training/react-native-elements/blob/f01271b5af795b9774c64cae02d4dfa1b68807c4/src/text/Text.js#L15-L22

**Possible Solution**
A quick fix is to at least note in the documentation that the h1 - h4 props are applied internally and will not follow the correct order of styles.

**Environment**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta7 |
| react-native | 0.56.0 |
| npm | 6.1.0 |

**Comment by iRoachie** [comment]
Thanks for bringing this up. This one is a bit tricky and i’m not sure what’s the best way to fix it.

Ideally local props should override the size set in the theme. Maybe just for the text component we should apply the style prop first and then the h1, h2, etc

**Comment by hamraa** [comment]
this is didn't fixed in the latest  release.
