### ISSUE TITLE
Button gives no visual feedback on Android ?

### ISSUE THREAD

**Issue by Gys** [react-native-training/react-native-elements#1665]
**Explain what you did**
I have a project with a Button from react-native-elements and want to give the user clear visual feedback when a button is pressed.

**Expected behaviour**
On Android I expected the button to give clear visual feedback when pressed, like on iOS: there the button turns from (for example) black to lightgrey.
However, on Android I can only achieve a very tiny color change :-(

**To Reproduce**
I created a small example in Snack, based on https://github.com/react-native-training/react-native-elements/issues/1290

https://snack.expo.io/ryMm8DegV

The Snack uses version 0.19.1 while I use 1.0.0beta7. However, Snack crashes when anything else then 0.19.1 is used. It seems to me that in 1.0.0beta7 the color change is even less then I was able to create in 0.19.1 :-(

**Comment by iRoachie** [comment]
On Android the default Touchable is `TouchableNativeFeedback` and on iOS it's `TouchableOpacity` https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L164. 

If you want to have the same exact effect you can change the Touchable.

```jsx
<Button TouchableComponent={TouchableOpacity} />
```

https://snack.expo.io/@roach_iam/button-underlaycolor

Oh and for the beta snack, you just need to add `"expo-font": "latest"` in the package.json

**Comment by Gys** [comment]
Great ! Thank you very much !!!

**Comment by phanbien9x** [comment]
Thank you so much!
