### ISSUE TITLE
New props for Button to disable ripple effect 

### ISSUE THREAD

**Issue by lipabi** [react-native-training/react-native-elements#1667]
**Is your feature request related to a problem? Please Describe.**
Currently, when buttonStyle.borderRadius set a value, it automatically enable ripple effect and turn the button background to transparent

**Describe the solution you'd like**
It should be controllable by props.

Pull request: #1666

**Comment by iRoachie** [comment]
If you don't want the ripple you can just another touchable.

```jsx
<Button TouchableComponent={TouchableWithoutFeedback} />
```

Next time open an issue to discuss your problem before sending a PR

**Comment by Hamid313-coder** [comment]
👍👍👍
