### ISSUE TITLE
Button -> loadingRight not updating on setState (loading is working)

### ISSUE THREAD

**Issue by brycedeneen** [react-native-training/react-native-elements#1669]
**Explain what you did**
Created a button. when you press the button it calls a function that changes a bool flag to the opposite.

**Expected behavior**
I expect the loadingRight spinner to show when the state variable is changed to true, and hide when it changes to false.

**Describe the bug**
When I set the default state of loadingRight to true it shows the spinner (working)
When I set the default state of loadingRight to false it hides the spinner (working)
When I call setState on my bool flag it should change the state, however it is not (bug)
If I make the change from loadingRight to loading it works as desired (it shows and hides the spinner when I change the state of the flag).

**To Reproduce**
Button:
<Button title='Save'
                            raised
                            loadingRight={this.state.saving}
                            rounded={true}
                            buttonStyle={registerStyleSheet.button}
                            onPress={this.register}
                    />

Function:
    register() {
        this.setState({saving: !this.state.saving});
    }

Constructor:

this.register = this.register.bind(this);
this.state = {...... saving: false};

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 0.19.1 |
| react-native | 0.57.7 |
| npm or yarn | 6.4.1 |

**Comment by brycedeneen** [comment]
Not sure what happened to the button code:
<Button title='Save'
                            raised
                            loadingRight={this.state.saving}
                            rounded={true}
                            buttonStyle={registerStyleSheet.button}
                            onPress={this.register}
                    />

**Comment by iRoachie** [comment]
@brycedeneen The problem you are describing because you are not clear on how the loading props work.

`loading` is a state prop, that determines if the button is in a loading state or not.
`loadingRight` only determines the placement of where the loading indicator shows.

So if you changing a button from a normal state to a loading state then it's the `loading` prop you'll have to change.

**Comment by brycedeneen** [comment]
Yup that was exactly it! Thanks for letting me know!
