### ISSUE TITLE
Missing keyboardType on Input

### ISSUE THREAD

**Issue by matheusmessora** [react-native-training/react-native-elements#1670]
I want to pass keyboardType to Input for better user experience.

**Describe the solution you'd like**
The component Input doesn't allow to override the keyboardType of TextInput react-native element.
The solution proposed:
Create a new attribute on Input element, named keyboardType. This attribute is resend to TextInput from react-native. The default value if not informed is `default`
https://facebook.github.io/react-native/docs/textinput#keyboardtype

**Describe alternatives you've considered**
Today my input allow alphanumerical chars but I created a regex on changeState to only allow numeric values.

**Comment by iRoachie** [comment]
The Input has all the props of the TextInput component from react native. Any props you add to the Input are passed directly to TextInput.

**Comment by matheusmessora** [comment]
Oh sorry, didn't know that.
I'll give it a try, thank you so much.

**Comment by JPSantistebanQ** [comment]
I have the same problem. "react-native-elements": "^1.2.7",
