### ISSUE TITLE
onPress within Icon within IconRight of Input does not trigger on first press

### ISSUE THREAD

**Issue by PaddyLock** [react-native-training/react-native-elements#1678]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Add onPress to Icon within rightIcon for Input

**Expected behaviour**
The onPress event should be triggered the first time it is pressed, after entering text in the input

**Describe the bug**
The icon requires focus first so it has to be pressed twice

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

Example:

```
<Input
                        containerStyle={globalStyles.inputContainer}
                        placeholder='Please enter your password'
                        label='Password'
                        value={this.state.password}
                        autoCapitalize='none'
                        secureTextEntry={this.state.secure}
                        rightIcon={<Icon
                            name={this.state.secureIcon}
                            type='font-awesome'
                            color='#000'
                            size={20}
                            onPress={() => this.toggleReveal()}
                        />}
                        onChangeText={(text) => this.setState({password: text})}
                    />
```

# Steps
1. set up as above
2. type something in password field
3. press icon
4. press icon again
```

**Possible Solution**
Trigger onPress at same time as focus on Icon

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | ^1.0.0-beta7 |
| react-native | https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz |
| npm or yarn | npm |

**Comment by iRoachie** [comment]
I couldn't replicate this behaviour. See https://snack.expo.io/@roach_iam/calm-nachos.

Remember if you're using it within a ScrollView then you have to manage the keyboard events, https://medium.com/react-native-training/todays-react-native-tip-keyboard-issues-in-scrollview-8cfbeb92995b

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by elkillerproHD** [comment]
I have the same problem, if the input is focus i cant tab the right icon because the input do onblur
