### ISSUE TITLE
Error import React native elements

### ISSUE THREAD

**Issue by ValPicot** [react-native-training/react-native-elements#1680]
installed react-native-elements using npm
`npm i react-native-elements --save`

**Error**
Metro Bundler has encountered an internal error, please check your terminal error output for more details

**Import code**
`import { List, ListView } from 'react-native-elements'`

If I comment the line when I import my code works perfectly

| macOs | |
| react-native-elements | |
| react-native | |
| npm | |

**Comment by iRoachie** [comment]
There's no ListView element in React Native Elements. You maybe mean `ListItem`

**Comment by ValPicot** [comment]
Oh yes sorry I was wrong. But when I want to import a button, I have the same error

**Comment by iRoachie** [comment]
Well show the code that gives that problem

**Comment by ValPicot** [comment]
`import { Button } from 'react-native-elements'`

**Comment by iRoachie** [comment]
Please follow the issue template.... for a bug report
