### ISSUE TITLE
Icon prop for checkmark does not work with font-awesome value

### ISSUE THREAD

**Issue by janhesters** [react-native-training/react-native-elements#1681]
**Explain what you did**
I wanted to display the font-awesome icon `square-o` (click [here](https://oblador.github.io/react-native-vector-icons/) and type in `square-o`) as a checkmark for a `<ListItem />`.

**Expected behaviour**
I expected the desired icon to show up on the right.

**Describe the bug**
The placeholder question mark appears and (using the debugger) you get the error that the icon wasn't found.

**To Reproduce**
I couldn't figure out how to reproduce this bug with a Snack Expo, because I have no idea how to use it with RNE beta and RNVI. Therefore I did it with `react-native init`.

Example:

```bash
react-native init rnebug && cd rnebug && npm install --save react-native-elements@beta react-native-vector-icons && react-native link
```

Now change `App.js` to reflect the following:

```js
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import { ListItem } from "react-native-elements";

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <ListItem title="Bug" checkmark={{ name: "square-o" }} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#F5FCFF"
  }
});
```

**Possible Solution**
No I can't. I looked in to the code, and it's being called with the `renderNode` helper function. I couldn't find a bug with it.

**Screenshots**
![screenshot 2018-12-20 at 15 45 36](https://user-images.githubusercontent.com/31096420/50291318-81aca600-046e-11e9-9763-23de063adc8b.png)

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | ^1.0.0-beta7 |
| react-native |0.57.8 |
| npm ~~or yarn~~ | 6.5.0 |

**Comment by iRoachie** [comment]
The default type for the Icon is `material`, if you want to use font-awesome then you have to specify it.

```jsx
<ListItem title="home" checkmark={{ name: "square-o", type: 'font-awesome' }} />
```

**Comment by janhesters** [comment]
@iRoachie Oh wow 🤦🏻‍♂️ Thank you!

**Comment by AlexanderBalson** [comment]
I know this is closed, but I'm trying to use checkboxes from this library, and trying to use the iconType at all with any icon set results in a huge error, starting with `Warning: Failed prop type: Invalid prop `name` of value `square-o` supplied to `Icon`, expected one of ["stepforward","stepbackward","forward","banckward","caretright","caretleft","caretdown","caretup","rightcircle","leftcircle","upcircle","downcircle","rightcircleo","leftcircleo","upcircleo","downcircleo","verticleleft","verticleright","back","retweet","shrink","arrowsalt","doubleright","doubleleft","arrowdown","arrowup","arrowright","arrowleft","down","up","right","left","minussquareo","minuscircle","minuscircleo","minus","pluscircleo","pluscircle","plus","infocirlce","infocirlceo","info","exclamation","exclamationcircle","exclamationcircleo","closecircle","closecircleo","checkcircle","checkcircleo","check","close","customerservice","creditcard","codesquareo","book","barschart","bars","question","questioncircle","questioncircleo","pause","pausecircle","pausecircleo","clockcircle","clockcircleo","swap","swapleft","swapright","plussquareo","frown","menufold","mail","link","areachart","linechart","home","laptop","star","staro","filter","meho","meh","shoppingcart","save","user","videocamera","totop","team","sha...`

The checkbox gives the same `?` as the original issue comment.

Here's the code for the checkbox:
`<CheckBox
						center
						title='Booked'
						iconRight
						iconType='antdesign'
						checked={this.state.bookedSwitch}
						onPress={() => this.setState({bookedSwitch: !this.state.bookedSwitch})}
					/>
`
Is this a stupid problem on my end or something bigger? Not sure if it's worth making an issue for it.

**Comment by iRoachie** [comment]
@AlexanderBalson You have to provide which icon you are using for the checked and unchecked states.

There's `checkedIcon` prop and `uncheckedIcon` prop
