### ISSUE TITLE
Combining theming and styled-components 

### ISSUE THREAD

**Issue by AlekzanderDee** [react-native-training/react-native-elements#1684]
When use `react-native-elements` theme provider and apply additional styles through `styled-components` it results in loosing styles defined in the theme.

I'm at 1.0.0-beta7 version and trying to combine theming (as top-level styling) and `styled-components` (for further tuning). 

**Explain what you did**
I have a setup that looks like:

Application `index.js`:
```js
import React from 'react';
import { View } from  'react-native';
import { ThemeProvider, Text } from 'react-native-elements';
import { StyledText } from 'styled/Text/styled';
import theme from 'constants/theme';
...

class App extends React.Component {
  render(){
    return (
        <ThemeProvider theme={theme}>
           <View>
             <Text>Foo</Text>
             <StyledText>Bar</StyledText>
           </View>
        </ThemeProvider>
    );
  }
}
```

`theme.js`
```js
import { Text } from 'react-native-elements';

export default {
  Text: {
    style: {
      color: 'red',
    }
  }
};
```

`styled.js`, which intent is to provide further styling for the `Text` component:
```js
import styled from 'styled-components/native';

import { Text } from 'react-native-elements';

export const StyledText = styled(Text)`
  font-size: 16px;
`;
```

**Expected behaviour**
I expect both `Text` and `StyledText` elements rendered with the `red` text color.

**Describe the bug**
Only the `Text` component gets a `red` colored text `Foo`, `StyledText` doesn't get `red` color.

I'm not honestly sure if it is a bug, but I can't find the way for styled component to respect the theme.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements |1.0.0-beta7 |
|styled-components|4.1.3|
| react-native | https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz|
| yarn | 1.7.0|

**Comment by iRoachie** [comment]
This is a little tricky to fix on our end. The probably here is that styled-components ends up passing a style prop that is an array of objects.

Example:
```js
export const StyledText = styled(Text)`
  font-size: 16px;
`
```

The above results in:
```jsx
<Text style={[{ fontSize: 16 ]} />
```

---
The value in your theme results in:
```jsx
<Text style={{ color: 'red' }} />
```
 
The theme withTheme hoc on the Text component tries to merge the incoming props, but the problem is that one is array and the other is an object. Since these two can't merge the latter is taken and that's why you only see the font size being taken effect.

An easy way to fix this in user land is to change the value in your theme to an array:
```jsx
// theme.js

import { Text } from 'react-native-elements';

export default {
  Text: {
    style: [{
      color: 'red',
    }]
  }
};

```

This should solve the problem, **except for a proptypes warning**

**Comment by iRoachie** [comment]
Fix for the proptypes warning is made in https://github.com/react-native-training/react-native-elements/commit/12e830f09e320746d3c3fd4e1ec366f717e856a0

**Comment by AlekzanderDee** [comment]
Thanks for the suggestion! 

Unfortunately, I've tried defining a style in the `theme` as an array, but it didn't do a trick.

May it be related to the order of the modules resolution/import? I've noticed if I put a `console.log` statement in both `styled.js` and `theme.js` modules, the code in `styled.js` is resolved first, and then `theme.js`. So I wonder if my `StyledText` component remains to be unaware of `theme`.

**Comment by gluons** [comment]
> This is a little tricky to fix on our end. The probably here is that styled-components ends up passing a style prop that is an array of objects.
> 
> Example:
> 
> ```js
> export const StyledText = styled(Text)`
>   font-size: 16px;
> `
> ```
> 
> The above results in:
> 
> ```js
> <Text style={[{ fontSize: 16 ]} />
> ```
> 
> The value in your theme results in:
> 
> ```js
> <Text style={{ color: 'red' }} />
> ```
> 
> The theme withTheme hoc on the Text component tries to merge the incoming props, but the problem is that one is an array and the other is an object. Since these two can't merge the latter is taken and that's why you only see the font size being taken effect.
> 
> An easy way to fix this in userland is to change the value in your theme to an array:
> 
> ```js
> // theme.js
> 
> import { Text } from 'react-native-elements';
> 
> export default {
>   Text: {
>     style: [{
>       color: 'red',
>     }]
>   }
> };
> ```
> 
> This should solve the problem, **except for a proptypes warning**

I'm finding solution for hours. Finally I found the solution. 🥰  
Thank you very much. You save me.  
I really want this solution on [Troubleshooting](https://reactnativeelements.com/docs/troubleshooting) page, is it possible?

**Comment by arpitBhalla** [comment]
Yupp, Could you create a PR for this?

**Comment by arpitBhalla** [comment]
Wait, I believe this would work without `[]` in version 4, Can you make changes in versioned docs, only please?

**Comment by gluons** [comment]
> Wait, I believe this would work without `[]` in version 4 (#3324), Can you make changes in versioned docs, only please?

Add only v3, right?

**Comment by gluons** [comment]
> > Wait, I believe this would work without `[]` in version 4 (#3324), Can you make changes in versioned docs, only please?
> 
> I should add only v3, right?

#3408 created.
