### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by tozaicevas** [react-native-training/react-native-elements#1690]
**Is your feature request related to a problem? Please Describe.**
TypeScript types as props

**Describe the solution you'd like**
Define the types

**Describe alternatives you've considered**
-

**Additional context**
Just started learning typescript, is there a reason not all props of some components (e.g. Button) defined?

**Comment by iRoachie** [comment]
Which props did you find not typed? What version of react-native-elements are you using?

**Comment by tozaicevas** [comment]
Im using CRNA (expo) with react-native sdk 31. Tried to use <Button> with borderRadius, didn't seem to compile. Am I missing something?

**Comment by iRoachie** [comment]
What version of react native elements

**Comment by tozaicevas** [comment]
1.0.0-beta7

**Comment by iRoachie** [comment]
There’s no borderRadius prop on Button in beta7
https://react-native-training.github.io/react-native-elements/docs/button.html#props
