### ISSUE TITLE
Dynamic Font Sizing

### ISSUE THREAD

**Issue by CarterBland** [react-native-training/react-native-elements#1693]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I am building an app and I'm finding bugs where our clients have font scaling turned on. This leads to many issues, but most noticeably in the forminput component.

**Expected behaviour**
The form input height should scale with the font size

**Describe the bug**
Using font scaling causes the forminput component to not work properly

**To Reproduce**
Add a text forminput and use font scaling

**Possible Solution**
Can you suggest a possible fix that would address this issue?

**Screenshots**
<img width="304" alt="screen shot 2018-12-26 at 9 40 09 am" src="https://user-images.githubusercontent.com/16313465/50450240-412bad00-08f2-11e9-92d4-879a33c01ba5.png">

**Your Environment (please complete the following information):**

| software | version |
| react-native-elements | 0.19.1 |
| react-native | 0.55.2 |
| npm |

**Comment by iRoachie** [comment]
In such a scenario what would be the expected outcome? The text input to get bigger?

**Comment by CarterBland** [comment]
Yes, I would expect the border outline should stretch with the font-size.

**Comment by iRoachie** [comment]
Can you describe the code you're using that displays this behaviour? 
I tried using the FormInput component from version "0.19.1" and it displays as expected.

### Normal
![simulator screen shot - iphone xr - 2018-12-29 at 21 07 38](https://user-images.githubusercontent.com/5962998/50543390-dad2b300-0bad-11e9-9a75-3f19533939e4.png)


### Larger
![simulator screen shot - iphone xr - 2018-12-29 at 21 07 56](https://user-images.githubusercontent.com/5962998/50543389-dad2b300-0bad-11e9-84f4-a07906fb9223.png)

**Comment by CarterBland** [comment]
Hey, thanks for the help! The behavior is inside the content inside the text input.

**Comment by iRoachie** [comment]
The placeholder font size correctly sizes, what do you mean?

**Comment by CarterBland** [comment]
Look at the example I posted, does the font you type in correctly size?

**Comment by iRoachie** [comment]
The two pictures i sent above is one at the normal font size and then the second is one with the setting all the way to the right.

Settings > General > Accessibility > Larger Text

![simulator screen shot - iphone xr - 2018-12-29 at 23 35 17](https://user-images.githubusercontent.com/5962998/50544138-6a825c80-0bc2-11e9-8f6b-1b587695fafd.png)
