### ISSUE TITLE
Change chevron for text

### ISSUE THREAD

**Issue by jasuno** [react-native-training/react-native-elements#1696]
In one of my listItems "Version" I want to change the Chevron for text. I would like it to say the version of the app, I found a way to hide the chevron, but a way to substitute it for text.

**Comment by iRoachie** [comment]
You can just use the [`rightTitle`](https://react-native-training.github.io/react-native-elements/docs/0.19.1/lists.html#righttitle) prop.

```jsx
<ListItem title="Hey" rightTitle="Nah" hideChevron />
```

See example snack here https://snack.expo.io/@roach_iam/bG9uZW

**Comment by jasuno** [comment]
Thanks, that works.
