### ISSUE TITLE
SearchBar  containerStyle  marginRight can't work

### ISSUE THREAD

**Issue by kanapan** [react-native-training/react-native-elements#1699]
cannot set marginRight in SearchBar containerStyle 
   <SearchBar
          platform={Platform.OS === 'ios' ? "ios" : "android"}
          containerStyle={{backgroundColor: 'green',marginRight:100 }}
          inputContainerStyle={{ backgroundColor: 'white', }}
        />

not working on android

**Comment by iRoachie** [comment]
With the `containerStyle` prop, set the width to auto.

```jsx
<SearchBar platform="android" containerStyle={{ width: 'auto', marginHorizontal: 10 }} />
```

**Comment by iRoachie** [comment]
Just fixed this officially in https://github.com/react-native-training/react-native-elements/pull/1701.

For now for a workaround you had use the width null hack:

```jsx
<SearchBar
    platform="android"
    containerStyle={{ marginHorizontal: 30, width: null }}
    inputContainerStyle={{ width: null }}
    showLoading
  />
```
