### ISSUE TITLE
Problem with animation on Fancy ListItem

### ISSUE THREAD

**Issue by felops** [react-native-training/react-native-elements#1700]
It seems that scale feedback is not working on ListItem as expected in the example showed on Docs:
https://react-native-training.github.io/react-native-elements/docs/listitem.html#linear-gradient-scale-feedback

I followed the documentation, but when I click on the fancy ListItem, there is no animation, just a flash black backgroud (probably a bug behavior). In the expo demo (https://expo.io/@monte9/react-native-elements-app) there is no animation as well, despite the the parameter "scaleProps" in on the example - but no "component" parameter (https://github.com/Monte9/react-native-elements-app/blob/master/src/views/lists_home.js#L281).

There is a problem on the documentation as well: in the code example shows "friction", "tension" and "activeScale" as parameters on example code (https://react-native-training.github.io/react-native-elements/docs/listitem.html#linear-gradient-scale-feedback), but below, on the parameters list, shows only "scaleProps" and none of that parameters on example code (https://react-native-training.github.io/react-native-elements/docs/listitem.html#props). Which one is right?

Is bad behaviour on the animation of Fancy ListItem knowm?

**Comment by iRoachie** [comment]
Hey @felops, thanks for bringing this to our attention. There's no actual prop call `scaleProps` on the ListItem as you can see the props [here](https://github.com/react-native-training/react-native-elements/blob/next/src/list/ListItem.js#L56). The documentation needs to actually remove that prop, and the example app needs to reflect this change.

The scale feedback does work though:

```jsx
import { ListItem } from 'react-native-elements';
import TouchableScale from 'react-native-touchable-scale';

<ListItem
  ViewComponent={TouchableScale}
  title="BNou"
  friction={90}
  tension={100}
  activeScale={0.95}
  onPress={() => null}
/>
```

![kapture 2018-12-31 at 13 10 31](https://user-images.githubusercontent.com/5962998/50564689-7fafd600-0cfd-11e9-9930-f1a2cfcfda02.gif)

**Comment by felops** [comment]
Hey @iRoachie, thanks for your feeedback! I forgot to reply you.

The animations really works as expected with your code, but seems that the prop onPress doesn't work when I pass TouchableScale as prop on ViewComponent. Besides of that, the documentation pass TouchableScale to the prop component, so I got confused.

I am not sure how to make it works. I am using the code of documentation beucase of the gradient, but I would like to have animation as well.

Is that an issue or just the parameters from docs are worng?

**Comment by iRoachie** [comment]
I'm not sure what you're saying. Are you saying that when you add the prop `component={TouchableScale}` that your `onPress` prop doesn't work?

**Comment by felops** [comment]
Actually when I add the prop `ViewComponent={TouchableScale}`, like in your example above. When I use `component={TouchableScale}` the animation just do not works.

**Comment by iRoachie** [comment]
Did you also add the other props?

```
 friction={90}
  tension={100}
  activeScale={0.95}
```

**Comment by felops** [comment]
Yeah, I did. My code:

```
<ListItem
  component={TouchableScale}
  friction={90}
  tension={100}
  activeScale={0.90}
  linearGradientProps={{
    colors: [this.props.color1, this.props.color2],
    start: [1, 0],
    end: [0.2, 0],
  }}
  title={this.props.title}
  titleStyle={{ color: 'white', fontWeight: 'bold' }}
  containerStyle={{
    borderRadius: 8,
    marginVertical: 8,
    marginHorizontal: 8,
  }}
  onPress={this.props.onPress}

  rightIcon={ this.props.loading ? <ActivityIndicator color="#fff" /> : null }

  chevron={ !this.props.loading }
  chevronColor="white"
/>
```

But the animation still doesn't works..

**Comment by iRoachie** [comment]
You're using Expo?

**Comment by felops** [comment]
Yeah, I do!

**Comment by iman2420** [comment]
@felops use `Component` instead `component`
