### ISSUE TITLE
 expo snack Unable to resolve module 'module://expo-font.js' 

### ISSUE THREAD

**Issue by lizhensheng** [react-native-training/react-native-elements#1702]
🥇 react-native-elements-app project  run error on expo snack
👍 
Device: (1002:881) Unable to resolve module 'module://expo-font.js'
  Evaluating module://expo-font.js
  Evaluating module://react-native-elements.js
  Evaluating module://src/drawer/components.js
  Evaluating module://App.js
  Loading module://App.js

**Comment by iRoachie** [comment]
Yes it's a weird bug that we're aware of. Should be fixed in next release according to expo team.

You can try adding `"expo-font": "latest"` to your package.json

**Comment by rakeshbpatel** [comment]
is there any update on this bug?

**Comment by iRoachie** [comment]
@rakeshbpatel It should be fixed when we release next version according to expo team

**Comment by jay-jlm** [comment]
I'd prefer this to not be closed just for visibility since it has not been fixed by Expo.
Maybe just label it as "won't fix" or something else?

**Comment by iRoachie** [comment]
This issue doesn't exist any more @jay-jlm . If you create a snack and use any of Icons, they work out the box without the error above. That's why it's closed.

**Comment by rajnishcoder** [comment]
Did not understand if `@expo/vector-icon` needs `expo-font` So, why it did not installed it automatically?

BTW, you can install it by running this command `npm install expo-font` and it will resolved the issue.
