### ISSUE TITLE
Estimate Request

### ISSUE THREAD

**Issue by waltermvp** [react-native-training/react-native-elements#1703]
How much would it cost/time to create  UI a react-native component like :

https://github.com/igalata/Bubble-Picker
or
https://github.com/efremidze/Magnetic

API would be declarative accept props of an array like `items' for the bubbles.

The reason I need this is so I can just use one lib. Understand that the physics would need work, but would like to get an idea of the price. (Ballpark figure would be great as to not invest to much time drilling too deep.

Thank you.

**Comment by Monte9** [comment]
Hi Walter! Thanks for reaching out. Those libraries look really interesting and fun to use.

Currently, we are focused on our v1 release and don't think we'll be able to develop it ourselves (RNE team). 

Although if anyone else has the time to work on it, feel free to respond here.

**Comment by waltermvp** [comment]
Got it thanks anyways :)

**Comment by waltermvp** [comment]
Got it thanks anyways :)
