### ISSUE TITLE
[RNE Ecosystem] react-select Creatable in React Native

### ISSUE THREAD

**Issue by YikSanChan** [react-native-training/react-native-elements#1712]
I need someone help to build [this](https://react-select.com/creatable#creatable), but in react native. @Monte9 Thanks!

**Comment by cidevant** [comment]
@YikSanChan Go to StackOverflow! Don't post irrelevant things here!

**Comment by iRoachie** [comment]
It's on our roadmap eventually to do a select/picker/dropdown component. There's already a ticket for it #253. Feel free to submit a PR if you have any ideas.

**Comment by YikSanChan** [comment]
> @YikSanChan Go to StackOverflow! Don't post irrelevant things here!

This is not irrelevant. See https://github.com/react-native-training/react-native-elements/blob/master/README.md#rne-ecosystem:

> React Native Elements also serves as a platform that connects small teams/individuals that needs help developing their RN app with open source contributors that are willing to build complex UI screens & animated interactions for 💰💰💰 ... If this sounds interesting and you would like to participate, kindly open a new issue with the design & spec of the UI screen that you need to be developed. One of our developers will respond to your issue with an estimate of time & cost.

Highlight: **_kindly open a new issue with the design & spec of the UI screen that you need to be developed_**
