### ISSUE TITLE
onPress doesn't work in overley component

### ISSUE THREAD

**Issue by blueturtle13g** [react-native-training/react-native-elements#1713]
I tried to put a yes or no button on overley component and take an action depending on it.
But `onPress ` event doesn't work on anything! no buttons, no texts or touchableOpacity.
this is an example:
` <Overlay isVisible={true}>
       <Button
             onPress={() => {
                   alert("pressed")
              }}
              title={"hello"}
       />
  </Overlay>`
but nothing happens.

**Comment by MD3XTER** [comment]
Same here, it works on iOS, but not on Android :(

**Comment by kewilson** [comment]
Strange, try plugging in the code snippet below into a regular view, works for both android and ios. If you touch anywhere not on the dismiss button in the window the overlay should hide itself. The dismiss button also makes it hide as well, obviously.

Are you using latest RNE? 

"react-native-elements": "git+https://github.com/react-native-training/react-native-elements.git#next"
******************************************************************************************************
this.state = {
            checked: false,
            overlayVisible: false,
        }

<Overlay
                    isVisible={this.state.overlayVisible}
                    windowBackgroundColor="white"
                    overlayBackgroundColor="grey"
                    onBackdropPress={() => this.setState({overlayVisible: !this.state.overlayVisible})}
                    width="auto"
                    height="auto"
                    borderRadius={5}
                >
                    <View style={styles.modal}>
                        <Text/>
                        <Badge
                            status='success'
                            value={1}
                        />
                        <Text style={styles.overlayText}>Event:</Text>
                        <Text style={styles.overlayText}>Test OnPress in Overlay</Text>
                        <Text/>
                        <Text/>
                        <Text/>
                        <Button
                            title='Dismiss'
                            onPress={() => this.setState({overlayVisible: !this.state.overlayVisible})}
                        />
                    </View>
                </Overlay>

modal: {
        backgroundColor: Colors.background.dark,
        flex: 1,
        opacity: 0.9,
        padding: 20
    },

**Comment by iRoachie** [comment]
This has been fixed on next https://github.com/react-native-training/react-native-elements/pull/1648. Now uses the Modal api under the hood, so issues with zIndex should be fixed.

Give it a shot on the `next` branch and let me know if it's still broken.
