### ISSUE TITLE
Theme disabled when using an array in style

### ISSUE THREAD

**Issue by supagu** [react-native-training/react-native-elements#1721]
"react-native-elements": "^1.0.0-beta7",

**Explain what you did**
Trying to style Buttons using a ThemeProvider, it fails when using an array in the style field.

**Expected behaviour**
This works, it makes my styled button blue:
<Button buttonStyle={GlobalStyles.blueBackground} />

This fails:
<Button buttonStyle={[GlobalStyles.blueBackground]} />

I have a blue button as expected but the button styling from my ThemeProvider is not being applied.

**Describe the bug**

Sample theme:

const theme = {
  Button: {
    buttonStyle : {
      borderRadius: 20,
      elevation: 0,
      marginTop:5,
      marginBottom:5
    },
  },
};

<ThemeProvider theme={theme}>

**Comment by iRoachie** [comment]
What does your button look like, and what are the styles you have set on it?

**Comment by supagu** [comment]
The theme above is the style I'm using.
It gives me a square  button with I use the array, but the background colour is correct.
When I do not use an array I get a rounded button which is what I would expect with the array usage also.

![array_button](https://user-images.githubusercontent.com/11153232/51514747-0a997180-1e61-11e9-983c-a04ba76a79dc.jpg)

background colour is setup like so:
```
greenBackground:{
        backgroundColor:"#3a9d21"
    },
```

**Comment by iRoachie** [comment]
Ah yes, i’m aware now what you mean. It’s because it’s trying to merge an object with an array, which are two different types. For now you can use StyleSheet.flatten([style1, style2]) in your buttonStyle which will create an object instead that can be merged with the styles set in the ThemeProvider

**Comment by iRoachie** [comment]
Think the best we can do in this case is to add a "Gotchas" section under the Theme provider docs to let persons know of this behaviour
