### ISSUE TITLE
Consider publishing a transpiled dist folder for react-native-web support

### ISSUE THREAD

**Issue by chris-rosney** [react-native-training/react-native-elements#1724]
**Is your feature request related to a problem? Please Describe.**
I've been trying to integrate `react-native-elements` into a cross platform web/mobile app that uses `react-native-web`. I'm using beta 7 and followed the instructions in https://github.com/react-native-training/react-native-elements/pull/1664 to get everything going.

And it works! But having to modify webpack to transpile the source as per this gist https://github.com/haruelrovix/gitphone/commit/8c0e6036d9231cc934285502528a2061b848ce2d is a bit cumbersome, and forces anyone using create-react-app to eject the config in order to modify webpack (unless there is some workaround I'm unaware of).

I'm also using storybook, and I'll need to modify it's webpack.config to get everything working for the same reason, which I haven't quite been able to figure out yet.

**Describe the solution you'd like**
Would you consider publishing a transpiled `dist` or `lib` folder in your package, rather than just the src? It should eliminate some of the extra setup required for web projects.

As a side note, it looks like `react-native-vector-icons` already does this, so that part of the setup step doesn't appear to actually be required.

**Comment by OKNoah** [comment]
> I'm also using storybook, and I'll need to modify it's webpack.config to get everything working for the same reason, which I haven't quite been able to figure out yet.

Let me know if you get this working!

**Comment by OKNoah** [comment]
> Let me know if you get this working!

@chris-rosney I did manage to get this working! I created the file `storybook/webpack.config.js`, you may have it in `.storybook/` depending on your config. Here is what I did:

```js
const path = require('path')
const paths = require('../config/paths')

module.exports = async ({ config, mode }) => {
  /*
    This is the same code I have in `config/webpack.config.dev.js`.
    If you have made other configurations to your webpack to make `npm run web` work, you'll need to put them here too most likely.
    I'm using `create-react-native-web-app`, btw.
  */
  const newLoader = {
    test: /\.(js|mjs|jsx|ts|tsx)$/,
    include: [
      paths.appSrc,
      path.resolve(paths.appNodeModules, 'react-native-elements'),
      path.resolve(paths.appNodeModules, 'react-native-ratings'),
      path.resolve(paths.appNodeModules, 'react-native-vector-icons'),
    ],
    loader: require.resolve('babel-loader'),
    options: {
      customize: require.resolve(
        'babel-preset-react-app/webpack-overrides'
      ),
      plugins: [
        ['@babel/plugin-proposal-class-properties'],
        [
          require.resolve('babel-plugin-named-asset-import'),
          {
            loaderMap: {
              svg: {
                ReactComponent: '@svgr/webpack?-prettier,-svgo![path]',
              },
            },
          },
        ],
        'react-hot-loader/babel',
      ],
      cacheDirectory: true,
      cacheCompression: false,
    },
  }

  config.module.rules.splice(8, 1, newLoader)

  /* As above, you may or may not need all these loaders, or you may need more. */
  config.module.rules[0].include.push(
    path.resolve(paths.appNodeModules, 'react-native-elements'),
    path.resolve(paths.appNodeModules, 'react-native-ratings'),
    path.resolve(paths.appNodeModules, 'react-native-vector-icons'),
  )

  /* Same here. */
  config.resolve.alias = {
    ...config.resolve.alias,
    'react-native': 'react-native-web',
    'react-native-svg': 'swgs',
    'reactotron-react-native': 'reactotron-react-js',
  }

  return config
}
```
I've added notes. Namely that you may need to add or remove some things as needed. You can and should also try make it more DRY by making a `loader.js` file somewhere and simply importing it to your `config/webpack.config.dev.js` (and `webpack.condig.prod.js`/`storybook/webpack.config.js`) instead of needing to change 3 files when you add or remove packages that need this kind of thing.

Hope this helps someone!

**Comment by iRoachie** [comment]
Seems to do this we'd have to bundle and transpile all our dependencies as well. See https://github.com/react-native-training/react-native-elements/issues/1808#issuecomment-469387205 for reference.
