### ISSUE TITLE
TAB key support

### ISSUE THREAD

**Issue by sebastso** [react-native-training/react-native-elements#1725]
I'm using Checkbox control in React Native -Windows UWP Application and looks like the TAB key is not supported to focus the control or to check/uncheck using the keyboard, this causes a problem for Accessibility, please provide the support.

**Comment by iRoachie** [comment]
Could you set a project where we could test? I don’t have a windows machine personally but I can look into it.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
