### ISSUE TITLE
组件如何更新

### ISSUE THREAD

**Issue by CleverLeng** [react-native-training/react-native-elements#1726]
版本不对，用不了新版本的属性

**Comment by Monte9** [comment]
English Translation:
Title: How to update components
Description: The version is wrong, you can't use the new version of the property.

**Comment by iRoachie** [comment]
@CleverLeng Can you describe what you are trying to do?

> 你能描述一下你想做什么吗？

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
