### ISSUE TITLE
Cannot pass 'testID' to 'Divider' component

### ISSUE THREAD

**Issue by brooksbecton** [react-native-training/react-native-elements#1727]
**Is your feature request related to a problem? Please Describe.**
I am unable to add a 'testID' prop to the 'Divider' component in TypeScript. 

It doesn't seem like this line allows the 'testID' prop to come through to the 'View' Component
https://github.com/react-native-training/react-native-elements/blob/master/src/divider/Divider.js#L7

**Describe the solution you'd like**
Destructure the 'testID' prop and add it to the 'View' 

or 

Spread the rest of the props out onto the 'View' component for full control over all the possible props for the 'View'

**Describe alternatives you've considered**
I could make a wrapper component around react-native-script's 'Divider' that is a 'View' around the 'Divider' that takes in the props described above

**Additional context**

**Comment by iRoachie** [comment]
Good catch! 

DividerProps should extend from ViewProps https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L706
