### ISSUE TITLE
RNE-1.0.0 <Input /> doesn't work with <Picker />

### ISSUE THREAD

**Issue by YikSanChan** [react-native-training/react-native-elements#1730]
**Explain what you did**
I try to migrate from 0.19.1 to 1.0.0.

**Expected behaviour**
`<Input />` with `Picker` as `inputComponent` should work the same as `<FormInput />` in 0.19.1. See a working sample with RNE 0.19.1 [here](https://snack.expo.io/@evanchan/rne019-forminput-works-with-picker).
![image](https://user-images.githubusercontent.com/17229109/51816178-3742f400-227a-11e9-9ef4-c02a91ffff97.png)

**Describe the bug**
See the not working sample with RNE 1.0.0 [here](https://snack.expo.io/@evanchan/rne1-input-doesnt-work-with-picker).
![image](https://user-images.githubusercontent.com/17229109/51816096-dd422e80-2279-11e9-8e4f-d1b9ec3af1db.png)

Note: I add below to solve problems mentioned #1719 and #1702.
```
// package.json
  "dependencies": {
    "expo-font": "^1.0.0",
    "react-native-vector-icons/MaterialIcons": "6.2.0",
    ...
  }

// App.js
import {Icon} from "react-native-vector-icons/MaterialIcons";
```
Credits to:
- https://stackoverflow.com/a/54272373/7550592
- https://forums.expo.io/t/snack-runs-on-the-simulator-but-not-in-a-real-phone/16595/9?u=evanchan

**Comment by iRoachie** [comment]
Thanks for those workarounds to snack! We reached out to the expo team and we'll correlate with them on a proper fix.

On the note of the Input with the Picker. I don't think there's a one to one replacement there. Before FormInput, FormValidationMessage, and FormLabel were 3 separate component, and you basically created your own PickerInput. 

The Input isn't really used in that way. The InputComponent was added to supported other TextInput type components. Picker doesn't really fit into that category. In this case it might be best to use standard react native Text components to build you special PickerInput

**Comment by YikSanChan** [comment]
@iRoachie thanks for the quick response. For the convenience of discussion, let's refer to code https://github.com/YikSanChan/react-native-formik-example-app/tree/upgrade-rne. 

What I was trying to do with `<Picker />` is basically **borrow** styled `<FormLabel />` and `< FormValidationMessage />` from RNE-0.19.1 (because I am lazy dealing with css), and create my own PickerInput (See https://github.com/YikSanChan/react-native-formik-example-app/commit/5c81ae97bab062aca601d990a3bc7c97999bb97d). Same to DatePickerInput (see https://github.com/YikSanChan/react-native-formik-example-app/commit/1beb8b513a67eb37d93515661eb7886c50dc0c03) and ImageInput (see https://github.com/YikSanChan/react-native-formik-example-app/commit/4871cc0515440208bee8da452ec50f2ef7a7e242). `inputComponent` is not for such use case.

However, to my surprise, even though PickerInput and DatePickerInput stop working, my `ImageInput` still works (see https://github.com/YikSanChan/react-native-formik-example-app/commit/90173a15f0e0a8e94391d8ed183111d133ac4a8a).

Anyway, if as you said,

> The InputComponent was added to supported other TextInput type components.

I will stop using `<Input />` for other types of input. Though I do feel `<FormLabel>` and `<FormValidationMessage>` are nice because it enables effortless integration with non-TextInput. An app using https://github.com/jaredpalmer/formik usually does such things like I did I guess.
