### ISSUE TITLE
Doesn't work with pre Expo 30 app

### ISSUE THREAD

**Issue by zeulb** [react-native-training/react-native-elements#1733]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
What you were trying to accomplish.
Trying to use react native elements on an expo app

**Expected behaviour**
No error

**Describe the bug**
Received ```Unable to resolve "@expo/vector-icons/AntDesign" from "node_modules/react-native-elements/src/helpers/getIconType.js"```

**Possible Solution**
Can you suggest a possible fix that would address this issue?
It seems AntDesign is only available on newer version of react-native-icons,
so I tried https://react-native-training.github.io/react-native-elements/docs/troubleshooting.html#using-an-expo-app-create-react-native-app-or-expo-xde, got different error ```Unable to resolve "expo-font" from "node_modules/@expo/vector-icons/createIconSet.js"``` because I'm using SDK 28 that doesn't include `expo-font`.

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |         |
| npm or yarn           |         |

**Comment by iRoachie** [comment]
Definitely aware of this. This was the only way at the time to implement AntDesign. To make it a hard requirement on expo.

This is definitely something we'd like to fix better in the future. See #1613

**Comment by iRoachie** [comment]
There really isn't a temporary fix for this. The easiest way to fix is to upgrade your version of expo.

**Comment by tthamel** [comment]
"@expo/vector-icons/AntDesign" from "node_modules/react-native-elements/src/helpers/getIconType.js"

running expo@32.0.6


do we have to run at expo 30

**Comment by LouisJS** [comment]
Same issue here. Running with Expo SDK 30.

From which Expo SDK is it working guys ? 31 ? 32 ?

**Comment by acsel1985** [comment]
I update Expo SDK to 32 version, but I have this bug.

**Comment by iRoachie** [comment]
Did you guys install `@expo/vector-icons` in your projects? When I tested using the icons I didn't have this installed.

**Comment by acsel1985** [comment]
I'm install `react-native-vector-icon` and this resolve this bug

**Comment by JulianKingman** [comment]
I updated my @expo/vector-icons from 6.3.1 (to 10.0.1), cleared and reinstalled node_modules, now it works
