### ISSUE TITLE
[ThemeProvider] Themed.ListItem should have a unique "key" prop

### ISSUE THREAD

**Issue by alvarojunior** [react-native-training/react-native-elements#1735]
**Explain what you did**
I'm using ThemeProvider with FlatList and ListItem

**Expected behaviour**
No warning message.

**Describe the bug**
When I use ThemeProvider with FlatList and ListItem the warning messages appears:
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.

 in ListItem (at withTheme.js:42)
 in Themed.ListItem (at Item.jsx:120)

**To Reproduce**
ThemeProvider  with FlatList and ListItem
And yes, I'am using keyExtractor in FlatList.

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.0.0      |
| react-native          |    0.57.7     |
| yarn           |    1.13.0     |

**Comment by iRoachie** [comment]
How are you using ThemeProvider?

**Comment by alvarojunior** [comment]
> How are you using ThemeProvider?

Yes.

```
<ThemeProvider theme={theme}>
    <Example />
</ThemeProvider>
```

If I don't use ThemeProvider that error does not appears.

`<Example />`

**Comment by iRoachie** [comment]
Alright I've been able to replicate it.

**Comment by iRoachie** [comment]
Found the bug https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L357. It's in the map

**Comment by iRoachie** [comment]
After much debugging, narrowed down the issue to https://github.com/react-native-training/react-native-elements/blob/master/src/config/withTheme.js#L35. Seems keys and or the children are affected in strange ways by lodash.merge
