### ISSUE TITLE
React-Native-Vector-Icons Dependency Outdated - Missing AntDesign

### ISSUE THREAD

**Issue by bgerhards** [react-native-training/react-native-elements#1736]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I upgraded my version of React-Native-Elements to v1.0.0. My React-Native-Vector-Icons version was at v4.5.0. I received an error regarding a missing dependency, 'React-Native-Vector-Icons/AntDesign'

**Expected behaviour**
My expected behavior was that the app would test and load correctly, no errors 😄 

**Describe the bug**
The bug is expecting an imported dependency found in `src/helpers/getIconType.js` that is not present in the package mandated dependency for React-Native-Vector-Icons. Line 12 calls for AntIcons from `react-native-vector-icons/AntDesign` which was not available until a later version of React-Native-Vector-Icons. 

**To Reproduce**
1. Create a react-native project with React-Native-Vector-Icons version 4.5.0 and React-Native-Elements v1.0.0 and 
2. Try to run the project. 

Example:

**Possible Solution**
Update the version of React-Native-Vector-Icons to a later version, preferably v6.0.0, the most modern version, that includes AntIcon.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.0.0    |
| react-native          |    0.55.3     |
| npm or yarn           |   yarn 1.12.3      |

**Comment by waltermvp** [comment]
Im getting the same with RN V 57.8

**Comment by iRoachie** [comment]
Thanks for bringing this up. The peer dependency should be `>6.0.0`. Just fixed this. Will release next version.

**Comment by waltermvp** [comment]
@iRoachie thanks. Might be helpful to add a note to the release notes about the missing outline Ionicons icons. They removed them and this will cause breaking changes for anyone using them. 
More info below.
https://github.com/ionic-team/ionicons/issues/550
https://github.com/ionic-team/ionicons/issues/604

**Comment by iRoachie** [comment]
Yep definitely came across that myself. Although I'm not sure if documenting that in *our* release notes is best. This is more a breaking change in react-native-vector-icons.

**Comment by waltermvp** [comment]
yep i see your point
