### ISSUE TITLE
After update from 1.00. beta7 to 1.0.0, icon in buttons have lost their padding

### ISSUE THREAD

**Issue by msevestre** [react-native-training/react-native-elements#1737]
**Explain what you did**
I updated one app  to use the latest and greated 1.0.0 from 1.0.0. beta7

**Expected behaviour**
I am expecting the UI to somewhat look the same. Especially, I am expecting the buttons icon to have the same right margin/padding 

**Describe the bug**
The icon is stuck to the label

**To Reproduce**
Using the example from the website (https://react-native-training.github.io/react-native-elements/docs/button.html)

Example:

```
import { Button } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';

<Button
  icon={
    <Icon
      name="arrow-right"
      size={15}
      color="white"
    />
  }
  title="Button with icon component"
/>
```

Here is how it looks like
![image](https://user-images.githubusercontent.com/1041237/51945627-3b435300-23ed-11e9-8243-15a9afb4e5cf.png)

In my app
![image](https://user-images.githubusercontent.com/1041237/51945737-79407700-23ed-11e9-926f-872470c059c0.png)

It used to look different (note the padding)
![image](https://user-images.githubusercontent.com/1041237/51945790-9ecd8080-23ed-11e9-8717-c5d2d8c37233.png)

Any idea what has changed?

**Comment by iRoachie** [comment]
This was done as bug fix in https://github.com/react-native-training/react-native-elements/pull/1505. 

The horizontal padding on the title component was removed. Instead, the padding is on the icon instead. The reason you have no padding is cause you're passing in your own icon component so you have to handle the padding yourself.

Using the icon prop as an object results in the button working correctly.

```jsx
<Button
  title="hey"
  icon={{
    name: 'arrow-right',
    size: 15,
    color: 'white',
    type: 'font-awesome',
  }}
/>
```

![screen shot 2019-01-30 at 8 41 15 pm](https://user-images.githubusercontent.com/5962998/52022502-7f0e8900-24cf-11e9-9f2d-5d39764d8e67.jpg)

**Comment by msevestre** [comment]
Ok I see. Ok all good then. If this is by design, I'll adjust the code.
Thanks @iRoachie for the quick feedback
