### ISSUE TITLE
After update from 1.0.0.beta7 to 1.0.0, minimum slider track does not have the right height 

### ISSUE THREAD

**Issue by msevestre** [react-native-training/react-native-elements#1738]
**Explain what you did**
I have updated an application to use v1.0.0. I notice that among the issue I already mentioned in #1737, there as also another issue with the slider component

When changing the height of the slider component, I am expecting the height of the minimumTrack to also change. This was happening in v1.0.0.beta7 but is not the case anymore. Instead, the minimumTrack has the constant height of 4 it seems 

**Expected behaviour**
I am expecting the minimumTrack to have the same height as the track

**Describe the bug**
BEFORE UPDATE
![image](https://user-images.githubusercontent.com/1041237/52006778-f8d84f80-249a-11e9-9e54-0e2e1318b615.png)

AFTER UPDATE
![image](https://user-images.githubusercontent.com/1041237/52006811-0beb1f80-249b-11e9-969c-358bf4842a3b.png)

If I make the track even bigger, the effect is quite noticeable
![image](https://user-images.githubusercontent.com/1041237/52006865-26bd9400-249b-11e9-82fe-aaba3f83221d.png)

**To Reproduce**
Put the slider into a component and change set the track like so
```
<Slider
              value={this.state.sliderValue}
              onValueChange={this.handleSliderValueChanged}
              trackStyle={styles.track}
              minimumTrackTintColor={color}
/>


with 
styles track: {
    height: 16,
    borderRadius: 10,
  },
```

I'll create a snack and add it here when I have time. I just wanted to report the issue before I forget

**Comment by rawad663** [comment]
Hey @msevestre, I've been able to reproduce your problem. I noticed that the thumb's positioning is set to a fixed value. I created a solution that takes the height/width provided into account.

I have a PR ready if anyone is willing to go over it GH-1739
