### ISSUE TITLE
V1.0.0 ESLint error found under Text.js component

### ISSUE THREAD

**Issue by rawad663** [react-native-training/react-native-elements#1740]
While working on GH-1738, I attempted to commit my changes done to `src/slider/Slider.js`, but the pre-commit linter would not allow me to commit due to a linting error found in `src/text/Text.js`.

**Describe the bug**
ESLint error in `src/text/Text.js` : 
`'fontFamily' is missing in props validation`
 
**To Reproduce**
run `./node_modules/.bin/eslint src/text/Text.js`

**Possible Solution**
add fontFamily propType on line 39
```javascript
TextElement.propTypes = {
  ...
  fontFamily: PropTypes.string,
};
```
add fontFamily defaultProp on line 48
```javascript
TextElement.defaultProps = {
  ...
  fontFamily: '',
};
```

**Screenshots**

Before Fix:
![image](https://user-images.githubusercontent.com/14206171/52089705-38776800-257d-11e9-8d86-05e80a665028.png)

After Fix:
![image](https://user-images.githubusercontent.com/14206171/52090995-f819e900-2580-11e9-93ac-6e4a994f3680.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.0.0      |
| react-native          |    --     |
| npm or yarn           |    --     |

**Comment by Monte9** [comment]
@rawad663 good catch! And the fix makes sense. 

Can you please submit a PR for it? 🙌

**Comment by rawad663** [comment]
@Monte9 PR created and tested right here! GH-1741

**Comment by rawad663** [comment]
The PR got merged for this, can we update the labels?

**Comment by iRoachie** [comment]
Thanks @rawad663 💯
