### ISSUE TITLE
cancelButtonTitle property of SearchBar missing from type definitions

### ISSUE THREAD

**Issue by Freysi21** [react-native-training/react-native-elements#1742]

**Comment by iRoachie** [comment]
Good catch! Should be added to this interface 
https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L1462

**Comment by Freysi21** [comment]
While I got you, for some reason this.props.onCancel in searchBar doesn't fire. I end up passing cancelButtonProps with onPressOut property to add my functionality on cancel.

**Comment by iRoachie** [comment]
Can you make a separate issue @Freysi21  about that?
