### ISSUE TITLE
I need to add icon to searchbar outside of the container

### ISSUE THREAD

**Issue by hesamsameni** [react-native-training/react-native-elements#1746]
I need to shrink down the inputcontainer in searchbar and add an icon outside of the input container . how can I do that ?
![capture](https://user-images.githubusercontent.com/20930323/52174997-f6833780-27b1-11e9-8169-7c851170b561.PNG)

**Comment by iRoachie** [comment]
Try using a wrapper view. 

https://snack.expo.io/@roach_iam/adequate-bagel

**Comment by hesamsameni** [comment]
Thanks !
