### ISSUE TITLE
Badge component since upgrade to 1.0.0 from 1.0.0-beta7 not displaying correct on IOS

### ISSUE THREAD

**Issue by nates-dennis** [react-native-training/react-native-elements#1750]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
What you were trying to accomplish.
- Upgrading version from 1.0.0-beta7 to 1.0.0
**Expected behaviour**
- After upgrading react native elements version the Badge component to display number/text with the correct shape and font size changing the badge size using padding.
**Describe the bug**
- When upgrading to the latest version the badges UI have changed. On attempting to resolve this back to how it looked on 1.0.0-beta7. i was able to get the badges looking okay on android but IOS the badge text does not display due to the padding i have added to correct the badge shape. On Both platforms the badge size is not rendering based on the font size also.
**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

Example:

**Snack**
https://snack.expo.io/@nates/nate-badge-bug

**Possible Solution**
Can you suggest a possible fix that would address this issue?
Check what changes has been made from 1.0.0-beta7 and see what is missing. 
**Screenshots**
android:
![image](https://user-images.githubusercontent.com/6730537/52210521-3532f380-287f-11e9-83ca-06c819dc0397.png)

ios:
![image](https://user-images.githubusercontent.com/6730537/52210330-a7ef9f00-287e-11e9-8485-78f7a8ceee9a.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |  0.57.8       |
| npm or yarn           |    yarn 1.6.0     |

**Comment by nates-dennis** [comment]
i have tried with the additional styles yes the text gets displayed on IOS but the badge does not look right. Here what i had on 1.0.0-beta7 compared on 1.0.0 on my real code 

**v1.0.0-beta7**
![screenshot_1549289505](https://user-images.githubusercontent.com/6730537/52213592-70d1bb80-2887-11e9-88e0-6fed6fe1bfc1.png)
![screenshot_1549289500](https://user-images.githubusercontent.com/6730537/52213593-70d1bb80-2887-11e9-99b4-20a5958157d8.png)
![simulator screen shot - iphone x - 2019-02-04 at 14 11 07](https://user-images.githubusercontent.com/6730537/52213594-70d1bb80-2887-11e9-8b35-e2c1f9a87852.png)
![simulator screen shot - iphone x - 2019-02-04 at 14 11 00](https://user-images.githubusercontent.com/6730537/52213595-70d1bb80-2887-11e9-9745-b23563d80a94.png)

**v1.0.0**
![screenshot_1549288944](https://user-images.githubusercontent.com/6730537/52213650-952d9800-2887-11e9-90ea-04c780650b34.png)
![screenshot_1549288934](https://user-images.githubusercontent.com/6730537/52213651-952d9800-2887-11e9-9fff-90ba45c89dd4.png)
![simulator screen shot - iphone x - 2019-02-04 at 14 01 16](https://user-images.githubusercontent.com/6730537/52213653-952d9800-2887-11e9-8dd7-71f0f0c02eca.png)
![simulator screen shot - iphone x - 2019-02-04 at 14 01 11](https://user-images.githubusercontent.com/6730537/52213654-95c62e80-2887-11e9-9eb2-a56966a96669.png)

In particular on IOS the badges are much smaller the shape is different and the spacing between text and the badge edge.

**Comment by iRoachie** [comment]
Yes, as I said previously the badges now scale horizontally instead and remains a constant height. 

You can see the badge styles here https://github.com/react-native-training/react-native-elements/blob/master/src/badge/Badge.js#L61.

To start getting design similar to beta7 behavior, you'll have to remove height on the badge and then apply your padding like before.

```jsx
badgeStyle={{
  height: 'auto'
}}
```

**Comment by nates-dennis** [comment]
Hi the above style and removing the additional styles dis help quite a bit but the badge still seem to be more horizontal than it was before comparing to how it was on 1.0.0-beta7

![simulator screen shot - iphone x - 2019-02-04 at 16 47 00](https://user-images.githubusercontent.com/6730537/52223179-fdd33f80-289c-11e9-83ab-1d374e8c15a7.png)
![screenshot_1549298810](https://user-images.githubusercontent.com/6730537/52223180-fdd33f80-289c-11e9-8ea7-d8e5f264dddf.png)

**Comment by iRoachie** [comment]
Alright let's see if we can close this out. Can you make a snack on https://snack.expo.io with the old version of react-native-elements? (0.19.1) that has a Badge that looks like exactly like you had? Then i'll try to remake it in 1.0.0. Cool?

**Comment by nates-dennis** [comment]
i was using 1.0.0-beta7 also i have tried to re-create how it looked on this version with snack but it is not identical as shown in the previous images i have sent. https://snack.expo.io/@nates/badge-test-react-native-elements-1.0.0-beta7

**Comment by nates-dennis** [comment]
height: 'auto' on the badgeStyle helped on phones with some padding on the containerStyle. for tablets i had to add flex:1 and a border radius removing the height: 'auto' and also adding a paddingHorizontal
