### ISSUE TITLE
How to add multiple rightComponents menus/icons in the header

### ISSUE THREAD

**Issue by lekeCoder** [react-native-training/react-native-elements#1752]
I am in love with the react-native-elements. I need help regarding header navigation. I want to add two menus to the rightcomponents but its only allowing one,

please help

**Comment by rawad663** [comment]
hello @lekeCoder, is there a reason you would need to menu icons in the header? Seems like an anti-pattern to me.

**Comment by lekeCoder** [comment]
I want to display two arrows backward and forward so that on click of either arrow the navigation will perform an action. Also I can't seem to perform onPress on any of the header menu.
Kindly help

**Comment by rawad663** [comment]
Okay @lekeCoder, is there something in the code stopping you from adding multiple icons? What have you attempted and didn't seem to work? (screenshots can be helpful too)
Also please specify which version of react-native-elements and react-native you are using.

Thanks!

**Comment by iRoachie** [comment]
The `rightComponent` can also accept a react element as it's value.

See example here https://snack.expo.io/@roach_iam/humiliated-churros

**Comment by Monte9** [comment]
> humiliated-churros

😂

**Comment by lekeCoder** [comment]
Thanks @iRoachie @rawad663 and thank you all. The example @iRoachie  gave solved my problem and expanded my understanding.
