### ISSUE TITLE
Add to Showcase

### ISSUE THREAD

**Issue by zenorocha** [react-native-training/react-native-elements#1762]
First of all, congratulations on the 1.0.0 release! 🎉 🎉 🎉

I saw that you now have a [showcase section](https://github.com/react-native-training/react-native-elements/commit/4af1ce373d825bbe7002574b922cb4ae13708e07) and I'm wondering if you're open to submissions.

I have an app called Le Cheese that uses `<SearchBar />` and could be featured there.

Let me know if you're interested so I can send a PR.

* https://itunes.apple.com/us/app/le-cheese/id1449930676
* https://play.google.com/store/apps/details?id=com.lecheese.app

**Comment by iRoachie** [comment]
Of course! We would love to have it in our showcase.

You'll need to add it to this array here https://github.com/react-native-training/react-native-elements/blob/master/website/pages/en/index.js#L145

**Comment by iRoachie** [comment]
You can send this PR to `master` instead of `next`

**Comment by zenorocha** [comment]
Thanks @iRoachie!

**Comment by Monte9** [comment]
@zenorocha your app looks delicious! 😍 Thanks for using RNE! 😉

**Comment by zenorocha** [comment]
Thanks @Monte9! 😍🧀😍🧀😍

**Comment by Monte9** [comment]
@zenorocha I downloaded your app and played around with it. not sure how seriously you are building it, but I have some feedback in case you are interested to take it to the next level in terms fo UX & designs patterns.

**Comment by zenorocha** [comment]
I would LOVE that! I come from a web background and this is my first app, any feedback would be extremely helpful. 

Maybe email is the best place to talk about it? Here's mine: zno.rocha@gmail.com

**Comment by Monte9** [comment]
@zenorocha sorry about the delay. I have sent you an email!
