### ISSUE TITLE
Clickable card

### ISSUE THREAD

**Issue by Lythenas** [react-native-training/react-native-elements#1764]
Is it possible to make the whole card clickable?

Like described in [material design](https://material.io/design/components/cards.html#actions) I want the card itself to be the primary action.

**Comment by iRoachie** [comment]
Is there any reason you can't wrap the Card component in a touchable? https://snack.expo.io/@roach_iam/bold-salsa

**Comment by Lythenas** [comment]
TouchableOpacity does work. When I tried TouchableNativeFeedback (for the ripple effect) it did not work. However I just replaced TouchableOpacity with TouchableNativeFeedback in your snack and it worked just fine. Apparently that was my mistake.

Thanks for taking the time to check this our.
