### ISSUE TITLE
searchBar cancel function type missing

### ISSUE THREAD

**Issue by novasponge** [react-native-training/react-native-elements#1765]
**Is your feature request related to a problem? Please Describe.**
`this.search.cancel(); // Only available if `platform` props is "ios" | "android"`
typescript type checking thinks cancel function is not typed
```
export class SearchBar extends React.Component<SearchBarProps, any> {
  /**
   * Holds reference to the stored input.
   */
  input: TextInput;

  /**
   * Call focus on the TextInput
   */
  focus(): void;

  /**
   * Call blur on the TextInput
   */
  blur(): void;

  /**
   * Call clear on the TextInput
   */
  clear(): void;
}
```
**Describe the solution you'd like**
Should we add cancel type?

**Describe alternatives you've considered**

**Additional context**

**Comment by iRoachie** [comment]
Good catch, we missed that one. It should be added to the class definition here 
https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L1485

**Comment by novasponge** [comment]
@iRoachie I have a fix but can not push my branch to remote.

**Comment by iRoachie** [comment]
You push to your own remote (fork). And the make a pull request to this repo
