### ISSUE TITLE
Component request: ActionSheet

### ISSUE THREAD

**Issue by hoboman313** [react-native-training/react-native-elements#1766]
I'm looking to switch away from the spaghetti that is native-base. They have a pretty handy ActionSheet component that they have that I was hoping this library could incorporate: http://docs.nativebase.io/Components.html#actionsheet-def-headref
Basically it uses the ActionSheetIOS on iOS and a custom made solution for Android.

**Comment by iRoachie** [comment]
Something like https://github.com/react-native-training/react-native-elements/issues/1266?

**Comment by hoboman313** [comment]
that looks like it
