### ISSUE TITLE
Getting 'opencollective-postinstall' is not recognized as an internal or external command while installing 'react-native-elements'

### ISSUE THREAD

**Issue by sharief-edv** [react-native-training/react-native-elements#1767]
> react-native-elements@1.0.0 postinstall F:\..\..\node_modules\react-native-elements
> opencollective-postinstall

'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-elements@1.0.0 postinstall: `opencollective-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-elements@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\....\npm-cache\_logs\2019-02-08T10_07_06_547Z-debug.log

**Comment by iRoachie** [comment]
When does this happen? Running `npm install react-native-elements`? What version of node do you have?

**Comment by poovarasanvasudevan** [comment]
yes this happening me too. i am installing with npm ```npm install react-native-elements --save```
And Full Logs
```
> react-native-elements@1.0.0 postinstall C:\Users\Poovarasan\IdeaProjects\ServiceFocus\node_modules\react-native-elements
> opencollective-postinstall

'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","ar
ch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-elements@1.0.0 postinstall: `opencollective-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-elements@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Poovarasan\AppData\Roaming\npm-cache\_logs\2019-02-10T02_05_29_691Z-debug.log

Process finished with exit code 1

```

**Comment by bilobom** [comment]
I solved the problem by installing react-native-vector-icons
`npm install react-native--vector-icons`
then rerun 
`npm install react-native-elements`

**Comment by sharief-edv** [comment]
> When does this happen? Running `npm install react-native-elements`? What version of node do you have?

node v8.11.3

**Comment by sharief-edv** [comment]
Today I tried again to install  ,it just installed like that , this is so weird , Below is the log @poovarasanvasudevan 
PS F:\WorkspaceInhouse2\REact\MobileApp3\....\...> node -v
v8.11.3
PS F:\WorkspaceInhouse2\REact\MobileApp3\...\....> npm install --save react-native-elements

> react-native-elements@1.0.0 postinstall F:\WorkspaceInhouse2\REact\MobileApp3\VMSUI02\VMS\node_modules\react-native-elements
> opencollective-postinstall

Thank you for using react-native-elements!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/react-native-elements/donate

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ react-native-elements@1.0.0
added 9 packages from 11 contributors and audited 103659 packages in 37.827s
found 0 vulnerabilities

And @bilobom thanks for your suggestion but i didn't tried though

**Comment by iRoachie** [comment]
Glad you got it figured out

**Comment by alphadzingina** [comment]
> Glad you got it figured out

Nope! he didn't figure anything out he said he just tried it another time using the same commands and it worked. Could you please loom into this issue. I also get the same error.
Thanks

**Comment by iRoachie** [comment]
There's no way for me to debug a postinstall script other than by running npm install. I haven't experienced it in my testing

**Comment by user0604** [comment]
The solution is as trivial as it sounds.

`npm install --save opencollective-postinstall`

**Comment by dhiazfathra** [comment]
> The solution is as trivial as it sounds.
> 
> `npm install --save opencollective-postinstall`

In my case I somehow need to install it globally. Works.

`npm i -g opencollective-postinstall`

**Comment by aalraai** [comment]
@dhiazfathra I can confirm. This solution worked for me as well.

**Comment by xo28122000** [comment]
@dhiazfathra  yes this solution works been held up because of this for days now .
