### ISSUE TITLE
SearchBar won't stop clearing text

### ISSUE THREAD

**Issue by avivbarel** [react-native-training/react-native-elements#1774]
SearchBar seems like it is stuck in a "clear loop", it clears the text after every key I press.
I encountered this after upgrading from 1.0.0-beta7 to 1.0.0.
I'm using "android" for the platform prop, I tried setting the prop to "default" but ended with same results.
I tried rolling back to 1.0.0-beta7 and it worked properly.

**Comment by iRoachie** [comment]
Can you post the code here that you used to result in that?

**Comment by avivbarel** [comment]
SearchBar.js( wraps SearchBar )

```
import React from "react";
import { Platform } from "react-native";
import { SearchBar as SearchBarElements } from "react-native-elements";

export default class SearchBar extends React.Component {
    render() {
        return (
            <SearchBarElements
                onChangeText={this.props.onChangeText}
                platform={Platform.OS}
                placeholder="Search a place..."
            />
        );
    }
}
```

That's how I render it
```
<View>
    <SearchBar onChangeText={this._onChangeTextSearchBar} />
    <Swiper width={width} height={height / 5} places={this.props.featuredPlaces} />
    <List places={this.state.displayedPlaces} onItemPress={this._onPressListItem} />
</View>
```

And that's the onChangeText function
```
_onChangeTextSearchBar = text => {
        const allPlaces = this.props.allPlaces;
        const displayedPlaces = text
            ? allPlaces.filter(place => place.name.toLowerCase().includes(text.toLowerCase()))
            : allPlaces;

        this.setState({
            displayedPlaces
        });
    };
```

**Comment by iRoachie** [comment]
You aren't using the SearchBar correctly. It's a [controlled component](https://reactjs.org/docs/forms.html#controlled-components), which means you have to set the `value` prop which is updated through state.

**Comment by avivbarel** [comment]
Thanks a lot, it worked.
Strange it worked without `value` prop in the previous version.
