### ISSUE TITLE
Align 3 dots icon on Top in ListItem

### ISSUE THREAD

**Issue by sharathm89** [react-native-training/react-native-elements#1775]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Trying to align 3 dots icon on Top Right in ListItem

**Expected behaviour**
Align 3 dots icon on Top Right in ListItem

**Sample Code**
```
<ListItem
  containerStyle={styles.containerStyle}
  title={this.getTitleView(data)}
  subtitle={this.getAddressView(data)}
  leftElement={<Avatar
          size="medium"
          rounded
          title="AB"
          activeOpacity={0.7}
          overlayContainerStyle={{ backgroundColor: "red" }}
          titleStyle={{ color: "#fff" }}
        />}
  rightElement={<Icon type="material" color="#C8C8C8" name="more-vert" />}
  />
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17666778/52582411-276b0880-2e53-11e9-8a0d-7dea3b873285.png)

**Basically I want the rightElement to be placed on top instead of center**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.0.0 |
| react-native          |  0.58.3  |
| npm or yarn           | yarn  |

**Comment by iRoachie** [comment]
You can use the `containerStyle` prop. https://snack.expo.io/@roach_iam/supportive-marshmallows

![screen shot 2019-02-11 at 1 58 31 pm](https://user-images.githubusercontent.com/5962998/52583141-46db4480-2e05-11e9-88ba-3c2844b2ad89.jpg)

**Comment by sharathm89** [comment]
@iRoachie it works but as shown in above snapshot even the **Avatar** gets moved to top...  But I Just need the 3 dots icon to move top right side

**Comment by iRoachie** [comment]
Try using `rightContentContainerStyle` along with `rightTitle` instead. https://snack.expo.io/@roach_iam/supportive-marshmallows

![image](https://user-images.githubusercontent.com/5962998/52586925-1dbfb180-2e0f-11e9-88ba-0c65ebc45746.jpeg)

**Comment by sharathm89** [comment]
thanks...
