### ISSUE TITLE
Input component doesn't respond to textContentType native prop from TextInput

### ISSUE THREAD

**Issue by methodbox** [react-native-training/react-native-elements#1776]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).
1.0.0

**Explain what you did**
What you were trying to accomplish.
Use the ```TextInput``` value of ```textContentType``` on the react-native-elements component ```Input```.

**Expected behaviour**
It would respond to the assigned ```textContentType``` in the same manner as the react-native ```TextInput```

**Describe the bug**
Nothing happens. It does not change the contextual behaviour of the keyboard.

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:
https://snack.expo.io/@methodbox/textinput

Make an input. Assign the prop ```textContentType``` with the value ```'telephoneNumber'```. Watch as it doesn't work when you use the text field and instead you just get the alpha keyboard (instead of the number pad).

**Possible Solution**
Can you suggest a possible fix that would address this issue?
I'm guessing you're not passing the prop through. I looked at your source and I can see that there is a ```setNativeProps``` function, but I can't see where it's getting what is passed to it.

I found this:

```setNativeProps(nativeProps: Partial<TextInputProps>): void;```

But I'm not really clear WTF this is doing other than apparently only pulling a ```Partial``` of the ```TextInputProps```. Not really familiar w/that.

In VS Code ```TextInputProps``` links to the React Native docs for TextInput ... which leads us to the reason for this post.

*edit* Remove irrelevant and confusing comments. See below for an example of how this is supposed to work.

**Comment by methodbox** [comment]
I believe this may be related: https://github.com/facebook/react-native/pull/22611

**Comment by iRoachie** [comment]
This doesn't even seem to work for the native TextInput component, and that's what we use under the hood. 

However, you can still accomplish the same effect using the `keyboardType` prop. https://snack.expo.io/@roach_iam/textinput

**Comment by methodbox** [comment]
> This doesn't even seem to work for the native TextInput component, and that's what we use under the hood.
> 
> However, you can still accomplish the same effect using the `keyboardType` prop. https://snack.expo.io/@roach_iam/textinput

You're right (that it doesn't work for the TextInput) and that's why I referenced that issue from RN above.

And yes, the ```keyboardType``` works fine; that's not really what this does. It is supposed to display contextually-based suggestions.

For example, if you select an email field and you've specified ```emailAddress``` it should find your email address you've setup in Mail app or used previously, but it doesn't work; it just has generic suggestions.

Another popular use is ```oneTimeCode``` where the keyboard auto-suggests an OTP SMS code as you receive it.

Apparently, though, this appears to be a React Native bug, apparently associated with (per that issue above) incorrect naming of the prop values as they are passed to iOS, though I'll admit I didn't fully understand that bug report.

**Comment by iRoachie** [comment]
Ahh I see now. Thanks for explaining. I guess we can close this issue now then
