### ISSUE TITLE
Can I add 2 images in Card component with some text something like in the pics.

### ISSUE THREAD

**Issue by istarter** [react-native-training/react-native-elements#1782]
I want to implement 2 countries flags in Card  with some text like a competition between countries that's it just like this https://www.google.com/search?rlz=1C5CHFA_enPK667PK667&ei=si1lXJbtMKyclwTmmp2oAg&q=icc&oq=icc&gs_l=psy-ab.3..35i39l2j0i67l5j0i131j0j0i131.1108255.1108656..1109264...0.0..0.222.653.2-3......0....1..gws-wiz.......0i71.UwatbrlIQd8

**Comment by iRoachie** [comment]
Hey @istarter the Card component can accept any react element as its children. You'll have to create the look and feel for this yourself.

**Comment by istarter** [comment]
> Hey @istarter the Card component can accept any react element as its children. You'll have to create the look and feel for this yourself.

Thank you @iRoachie for your time can you help me out how should I do this I am actually new to react-native your help must be appreciated. I have attached if help me out with any of this one would be great. 
![card](https://user-images.githubusercontent.com/11480617/52949935-88d52f00-339f-11e9-87f9-f84f4a3f094e.png)
![vs](https://user-images.githubusercontent.com/11480617/52949936-896dc580-339f-11e9-883f-821b92997247.png)

**Comment by iRoachie** [comment]
@istarter Here's an example i mocked up https://snack.expo.io/@roach_iam/bWF0Y2
