### ISSUE TITLE
ListItem prop titleNumberOfLines isn't working?

### ISSUE THREAD

**Issue by rauldeheer** [react-native-training/react-native-elements#1783]
**Explain what you did**
I'm trying to limit the numberOfLines for the title of a ListItem to one, but it is displaying unlimited numbers of lines.

**Expected behaviour**
The amount of lines should be limited to one.

**Describe the bug**
It seems like the titleNumberOfLines is totally ignored.

**To Reproduce**
This is my code, so that's all you'll have to use to reproduce this issue:

```
<ListItem
                  title={`${userInformation.street} ${userInformation.houseNumber}, ${userInformation.zipcode} dkawduwidw aidbwaidbiwaudbuw abduwbd iwad nbiwabdi wabdiaiwd niawd ubwa`}
                  titleNumberOfLines={1}
                  leftIcon={<MaterialCommunityIcons name="map-marker" size={30} color={primaryColor}/>}
                  bottomDivider={true}
                />
```

**Possible Solution**
-

**Screenshots**
-

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.0.0   |
| react-native          |   0.58  |
| npm or yarn           |    npm 6.5.0     |

**Comment by iRoachie** [comment]
There's no `titleNumberofLines` prop in 1.0.0. Not sure where you got that from. Achieving this effect, you need to use [`titleProps`](https://react-native-training.github.io/react-native-elements/docs/listitem.html#titleprops) prop.

```jsx
<ListItem titleProps={{ numberOfLines: 1}} />
```

**Comment by rauldeheer** [comment]
@iRoachie Thanks, that was the solution. I saw a lot of old posts talking about those props, but I guess they were removed in v1.
