### ISSUE TITLE
ButtonGroup - containerBorderRadius doesn't work

### ISSUE THREAD

**Issue by trane294** [react-native-training/react-native-elements#1784]
Version 1.0.0

Works:

```
<ButtonGroup
	containerStyle={{borderRadius: 0}}
</ButtonGroup>
```
Doesn't work even mentioned in documentation

```
<ButtonGroup
	containerBorderRadius={0}
</ButtonGroup>
```

**Comment by iRoachie** [comment]
Correct. I think we can remove this prop altogether but this would be a breaking change. Let's put this back for a bit.

**Comment by trane294** [comment]
Please just remove it from documentation. Thank you
