### ISSUE TITLE
Button's label is chopped on One plus 6t mobiles

### ISSUE THREAD

**Issue by mateen-hussain** [react-native-training/react-native-elements#1785]
**Explain what you did**
Loading a simple `Button` with label and icon on One plu6t mobile is chopping the label. This happens on One plus 6T mobile phone, but appears fine a Moto G4 and Samsung S9.

**Expected behaviour**
Full label to be displayed on the button

**Describe the bug**
Button's usage
```
<View style={styles.actionButton}>
	<NextButton
	text={lang.signButton}
	icon="sign-in"
	iconType="font-awesome"
	loading={this.props.signInInProgress}
	onPress={() => this.props.setSignInUser(
		this.props.signInEmail,
		this.props.signInPassword,
	   )}
         />
</View>
```

Button's decleration
```
const NextButton = ({
	onPress, text, icon, iconType, loading,
}) => {
	const buttonIcon = (<Icon
		name={icon}
		type={iconType}
		color={tertiaryColor}
		style={styles.nextButtonIcon}
	/>);
	return (
		<Button
			text={text}
			raised
			icon={buttonIcon}
			iconRight
			onPress={onPress}
			buttonStyle={styles.nextButton}
			textStyle={styles.nextText}
			loading={loading}
		/>
	);
```

styles used
```
nextButton: {
		backgroundColor: primaryColor,
		width: deviceWidth - 40,
		height: 50,
	},
nextText: {
		color: tertiaryColor,
		fontSize: 20,
		fontWeight: 'bold',
	},
nextButtonIcon: {
		marginLeft: 10,
	},
```

**Screenshots**
Samsung s9 screenshot with correct display of button labels
![whatsapp image 2019-02-16 at 10 34 14](https://user-images.githubusercontent.com/26531653/52915506-d339ab80-32cc-11e9-93d5-86bd93fedd93.png)

One plu 6t screenshot of labels getting chopped
![whatsapp image 2019-02-16 at 10 29 46](https://user-images.githubusercontent.com/26531653/52915509-daf95000-32cc-11e9-8310-3290186adab3.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.0.0-beta2    |
| react-native          |    https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz     |
| npm or yarn           |    6.4.1     |

**Comment by iRoachie** [comment]
Can you please try this using v1.0.0 instead of a beta and let me know if the problem still exists?

**Comment by mateen-hussain** [comment]
@iRoachie Sorry I dont have any OnePlus device to test to see if any upgrading the react-native-elements version would work. This bug was reported by one of the app users who happen to use OnePlus 6T. I was hoping someone else would have faced the same problem and would have a solution for it.

**Comment by CarusonSan** [comment]
I had this same issue on my OnePlus 5T and I believe it is to do with the "OnePlus Slate" font that is used on OnePlus device.

Try changing the font to Roboto instead, otherwise try looking at this thread:
https://forums.expo.io/t/text-cut-off-on-oneplus-device/4999

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
