### ISSUE TITLE
How do I get react native elements to work with styled components?

### ISSUE THREAD

**Issue by artivilla** [react-native-training/react-native-elements#1786]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Trying to wrap my RNE in a styled component and would like to pass the prop styles exposed via the styled wrapper.

As an example:
```
import { Input } from 'react-native-elements';
import styled from 'styled-components/native';

const StyledInput = styled(Input)`
	width: '100%';
`;

				<StyledInput
					placeholder='Email address'
					autoCapitalize='none'
					autoCorrect={false}
					errorStyle={{ color: 'red' }}
					errorMessage='Already taken.'
					inputContainerStyle={{ backgroundColor: Colors.purpleFog }}
					containerStyle={{ width: '100%' }}
				/>
```

**Expected behaviour**
I'd like to get the 100% width setup in my styled HOC rather than via the style props exposed in RNE.

**Describe the bug**
`containerStyle={{ width: '100%' }}` works but defining `width: '100%';` does not.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.0.0-beta7        |
| react-native          |  https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz       |
| npm           | 6.7.0        |

**Comment by iRoachie** [comment]
Styled components only work directly with components that have an implicit `style` prop. We use props for styling in react native elements so you have to specify using the attr method.


```jsx
const StyledInput = styled(Input).attrs({
  containerStyle: {
    width: 100%;
  },
})
```

**Comment by mihaerzen** [comment]
@iRoachie In your code the backticks (\`\`) are missing, which results in `Invariant Violation: Objects are not valid as a React child` error. Code which works for me is:

```javascript
import { Input } from 'react-native-elements';
import styled from 'styled-components';

const StyledInput = styled(Input).attrs({
  textAlign: 'right',
  containerStyle: {
    width: '100%',
  },
})``;
```
