### ISSUE TITLE
 Button ripple effect overflows outside button container Even without borderRadius

### ISSUE THREAD

**Issue by aliassar** [react-native-training/react-native-elements#1787]
**Explain what you did**
I wrote a simple button with react-native-element .
` <Button onPress={() => this.login()} title='login' containerStyle={styles.buttonContainer} />`

**Expected behaviour**
I expected ripple not to be borderless.

**Describe the bug**
ripple is borderless.

**To Reproduce**

Example:

https://snack.expo.io/@ali.assar/button-problem
# Steps

    1. Click on 'Button'

    2. See the overlay

**Possible Solution**
In line 65 of Button.js maybe changing the bloolean from true to false (borderless property) can fix it.

` if (Platform.Version >= 21) { attributes.background = TouchableNativeFeedback.Ripple( 'ThemeAttrAndroid', true ); }`
----------------------------------->>>>>>>> ` if (Platform.Version >= 21) { attributes.background = TouchableNativeFeedback.Ripple( 'ThemeAttrAndroid', false ); }`

**Screenshots**

![untitled](https://user-images.githubusercontent.com/40848213/52952444-cfc02600-3399-11e9-9bbd-4553712a31e2.png)

**My Environment**

| software | version |
| react-native-elements | 1.0.0|
| react-native | 0.58 |
| yarn | 1.13.0|

**Comment by xavier-villelegier** [comment]
Hey @aliassar 👋 , sorry for the delay !
I just tested it on Snack, and apparently the solution you provided fixes the bug ([repro here](https://snack.expo.io/@xavier-villelegier/tactless-celery))

Would you mind opening a PR to fix it ? 💯

**Comment by aldoreyes** [comment]
This is still happening in 3.1.0, was this rolled back for some reason? I don't see the merged change from PR #1799 on 3.1.0

**Comment by andrei0807** [comment]
yes me too.
I can see same error.

**Comment by FerminIriarte-0324** [comment]
I also same issue but update android version from 9 to 10 with API 29. this issue disappears.
Development environment is geomotion/win10.

**Comment by HugoGresse** [comment]
Just updated to 3.3.0, ripple is crazy big :/

**Comment by flyingcircle** [comment]
@HugoGresse just tested in snack and was not able to reproduce. Maybe create a snack showing the issue.

**Comment by koaladlt** [comment]
I had a similar issue. My mistake was to use margin on "buttonStyle" prop. Using it on "containerStyle" fixed the problem.

**Comment by mdovn** [comment]
> I had a similar issue. My mistake was to use margin on "buttonStyle" prop. Using it on "containerStyle" fixed the problem.

Save my day, thanks @koaladlt

**Comment by HugoGresse** [comment]
Sorry @flyingcircle I just made the update to 3.x and the issue is linked to this one: https://github.com/react-native-elements/react-native-elements/issues/2958
