### ISSUE TITLE
Case Sensitive Problem in webpack? Unable to resolve "./badge/badge"

### ISSUE THREAD

**Issue by lucidlemon** [react-native-training/react-native-elements#1788]
Hi there,

I am using react-native-elements pretty much only for some form fields, but I get this error while compiling:

`Unable to resolve "./badge/badge" from "node_modules/react-native-elements/src/index.js"`

I am not even using the badge anywhere in my project (unless expo does that by default), so I am quite surprised to see this message.

Could it be that this is an issue with case sensitivity? because the file /badge/Badge would be there..

I am using:

* macOS 10.14.3
* npm 6.8.0
* node 10.15.0

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |   32.0.0      |
| npm            |      6.8.0   |

my packages to start with:

```
    "@expo/samples": "2.1.1",
    "axios": "^0.18.0",
    "babel-plugin-module-resolver": "^3.1.3",
    "eslint": "^4.19.1",
    "expo": "^32.0.0",
    "i18n-iso-countries": "^3.7.8",
    "immutable": "^3.8.2",
    "lodash": "^4.17.10",
    "moment": "^2.22.1",
    "normalizr": "^3.2.4",
    "onchange": "^4.0.0",
    "prettier": "^1.13.5",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-calendars": "^1.19.4",
    "react-native-communications": "^2.2.1",
    "react-native-elements": "^1.0.0",
    "react-native-immutable-list-view": "^0.7.2",
    "react-native-local-storage": "^1.5.2",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-render-html": "^3.10.0",
    "react-native-tab-view": "^1.0.2",
    "react-navigation": "2.0.0",
    "react-redux": "^5.0.7",
    "redux": "^3.0.0",
    "redux-logger": "^3.0.6",
    "redux-loop-symbol-ponyfill": "^2.2.2",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0"
```

**Comment by xavier-villelegier** [comment]
Hey @lucidlemon, did you finally fix this ? Are you using react-native-web ?

**Comment by lucidlemon** [comment]
Hi!
No I didn't. I cant seem to get it running right now. No I am not, I am just building the native app for ios and android.

**Comment by iRoachie** [comment]
You may need to remove react-native-elements and re-install it. Before v1 the badge was located at `src/badge/badge.js`. After v1 it's now at `src/badge/Badge.js`

**Comment by lucidlemon** [comment]
I have no idea what I did. but I opened my project again today without reinstalling npm modules or anything and it works.... weird stuff.

**Comment by linchen2chris** [comment]
same issue here, after upgrade to v1.1.0, the issue happen, remove node_modules and reinstall, still has the issue, the reason probably is that file name is case-insensitive in macbook, I move my project to another folder and reinstall, then fix it

**Comment by Mukeyii** [comment]
Same issue here. Using the latest RNE and tried reinstalling nodemodules, rne, deleted npm cache, reinstalled app etc., nothing helped. Any other suggestions?
