### ISSUE TITLE
Avatar title text not displaying on Android

### ISSUE THREAD

**Issue by mojorisin7** [react-native-training/react-native-elements#1795]
**Explain what you did**
Trying to have text display in the avatar which returns the first two characters of the contacts name

**Expected behaviour**
Mi should be displayed in the avatar to represent Michael

**Describe the bug**
iOS works as expected where as Android avatar title text does not display.

`<Avatar title="Mi" />`

Also tried:

`<Avatar title="Mi" titleStyle={{ color: '#fff' }} />`

**Screenshots**
IOS (working as expected)
![screenshot 2019-02-21 at 15 27 58](https://user-images.githubusercontent.com/2281054/53180600-ca5b1980-35ed-11e9-87a4-dc80f4a71df5.png)

Android (text not displaying)
![screenshot 2019-02-21 at 15 30 51](https://user-images.githubusercontent.com/2281054/53180611-d3e48180-35ed-11e9-8879-a0e6243ebe7d.png)

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |   0.58.4      |
| npm or yarn           |    1.13.0     |

**Comment by iRoachie** [comment]
Hey @mojorisin7 I could not replicate this on android. The Avatar title displayed without any issues.

**Comment by mojorisin7** [comment]
Thanks @iRoachie. Can you confirm it works with the theme provider?

Android
![screenshot 2019-02-25 at 13 58 01](https://user-images.githubusercontent.com/2281054/53342318-980b2e00-3905-11e9-9312-ddc5340b9283.png)

iOS
![screenshot 2019-02-25 at 13 57 53](https://user-images.githubusercontent.com/2281054/53342332-a0fbff80-3905-11e9-8254-3afdc4839b36.png)


```<Avatar titleStyle={{ color: '#fff' }} title="He" />```

Seems to be an issue when using the theme provider. Below is a sample from our theme. Removing Avatar from them seems to fix this. However, we would like to style the avatar via the theme provider

```
import colors from './colors';

export default {
  colors,
  Avatar: {
    avatarStyle: {
      backgroundColor: 'red',
    },
    titleStyle: {
      color: '#ffffff',
    },
  }
};
```

**Comment by iRoachie** [comment]
Works the same way. https://snack.expo.io/@roach_iam/more-cereal

**Comment by iRoachie** [comment]
Ahh i see now. Seems to be a mismatch. The avatar component needs a bit cleanup since it's a bit confusing which styles are being applied where. You can use the [`overlayContainerStyle`](https://react-native-training.github.io/react-native-elements/docs/avatar.html#overlaycontainerstyle) prop when using `title` to achieve the effect you want

**Comment by mojorisin7** [comment]
Thanks @iRoachie. Will do what you have suggested 👍

**Comment by dimgrav** [comment]
I experience the same behaviour on Android, `titleStyle` does not seem to apply the provided color.
