### ISSUE TITLE
Build error after installing react-native-elements

### ISSUE THREAD

**Issue by hybridshams** [react-native-training/react-native-elements#1797]
Installed react-native-elements by following the guide [here](https://react-native-training.github.io/react-native-elements/docs/getting_started.html)

After installation the app does not seem to be build. It gives out the following build error.

**Could not compile settings file 'D:\reactnative\app\android\settings.gradle'.> startup failed:
  settings file 'D:\reactnative\app\android\settings.gradle': 3: unexpected char: '\' @ line 3, column 127.**

When I checked the file the error says that the slash after **react-native-vector-icons** is unexpected

`project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '..\node_modules\react-native-vector-icons\android')`

This is a fresh app that was created for testing purposes and no other libraries were installed and it's the default code(i.e. nothing was changed other than installing the react-native-element and react-native-vector-icons)

Also the react-native-vector-icons were linked as instructed [here](https://react-native-training.github.io/react-native-elements/docs/getting_started.html)

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.0.0    |
| react-native          |     0.58.5    |
| npm or yarn           |    6.4.1     |

Glad if anyone can help ASAP.

**Comment by iRoachie** [comment]
This error usually shows when you haven't restarted the app after add react-native-vector-icons.

After you `npm install` and `react-native link react-native-vector-icons` then you have to restart `react-native run-android` or `react-native run-ios`

**Comment by hybridshams** [comment]
I tried restarting/building it several times and each time there is a build error. I tried `npm install` even after installing the two packages but that did not resolve the issue either.

**Comment by iRoachie** [comment]
Do you have a github repo that i can test this on?

**Comment by hybridshams** [comment]
I created a new react native app so that I can share it with you. This does not even finish the gradle sync in the android studio as it is producing the same error. I will share the git repo link with you in a short while anyway.

![image](https://user-images.githubusercontent.com/47857656/53178427-da87ee80-3617-11e9-906e-e3ce8d72162d.png)

**Comment by hybridshams** [comment]
Here is the link to the git repo

https://github.com/hybridshams/test-react-elements

**Comment by hybridshams** [comment]
@iRoachie were you able to figure out the issue?

**Comment by CarusonSan** [comment]
Could you try the following?
Go to folder Android
Open file settings.gradle

rootProject.name = 'CareAppSolutions'
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '..\\node_modules\\react-native-vector-icons\\android')
include ':react-native-gesture-handler'
project(':react-native-gesture-handler').projectDir = new File(rootProject.projectDir, '..\\node_modules\\react-native-gesture-handler\\android')

include ':app'

**Comment by hybridshams** [comment]
Thank you @CarusonSan. That solved the issue!
