### ISSUE TITLE
Overlay rotates to portrait in a landscape app

### ISSUE THREAD

**Issue by DevonTomatoSandwich** [react-native-training/react-native-elements#1798]
**Is your feature request related to a problem? Please Describe.**
I'd like the Overlay component to keep the same orientation that the App is in.
Right now i have an app that is defined as landscape in my app.json:
```
"expo": {
    ...
    "orientation": "landscape",
```
When I change the Overlay Component's isVisible prop to true, the whole app changes to a portrait orientation. If i then press onBackdropPress, setting the isVisible prop to false, the app returns to its normal landscape orientation.

**Describe the solution you'd like**
I'd like to keep the orientation to landscape for opening and closing the Overlay

**Describe alternatives you've considered**
Modal (I've had similar orientation issues with Modal),
Alert (can't insert my own views)

**Additional context**
![img_1634](https://user-images.githubusercontent.com/35514332/53219885-ea561000-36b5-11e9-9e73-9043643c4101.png)
![img_1635](https://user-images.githubusercontent.com/35514332/53219981-533d8800-36b6-11e9-8d85-32a5f0da0ddf.png)

**Comment by iRoachie** [comment]
The overlay uses react-native's [Modal](https://facebook.github.io/react-native/docs/modal) under the hood.

On iOS you have to specify which orientations are allowed for a modal. You can set this by using the [`supportedOrientations`](https://facebook.github.io/react-native/docs/modal#supportedorientations) prop.

```jsx
<Overlay
  isVisible={modal}
  onBackdropPress={toggle}
  animationType="fade"
  supportedOrientations={['portrait', 'landscape']}
>
  <Text>My Modal</Text>
</Overlay>
```

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
