### ISSUE TITLE
Unable to show the checkbox in react-native-elemets

### ISSUE THREAD

**Issue by nihp** [react-native-training/react-native-elements#1807]
I need to show the Checkbox for selecting and unselecting a list

I have used react-native-elements to show this. But it not rendering the icon which I am expecting here. Refer the attachment

![screenshot 2019-02-28 at 12 40 13 pm](https://user-images.githubusercontent.com/36992338/53547816-034b3f00-3b56-11e9-9045-b8c418c854e2.png)

In the above image red color is the icon which is shown the attachment.

```
  <CheckBox
            iconRight
            iconType='evilicon'
            checkedIcon='close-o'
            uncheckedIcon='close'
            checked={this.state.checked}
              />
```

**Comment by nihp** [comment]
I fixed this issue

**Comment by iRoachie** [comment]
Glad you solved it!
