### ISSUE TITLE
Button compile failure on Web with react-native-web

### ISSUE THREAD

**Issue by fungilation** [react-native-training/react-native-elements#1808]
**Explain what you did**
While following https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html, `import { Button } from 'react-native-elements' triggers screenshot below.

Native (Android) would render Button fine.

**Expected behaviour**
Button renders on Web, as it does on native platforms.

**Describe the bug**
![image](https://user-images.githubusercontent.com/3803466/53616455-732de980-3b97-11e9-91f4-74b95d50c17a.png)

**To Reproduce**
Follow https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html

In src/App.js:
```
import { Button } from 'react-native-elements
```

Run `yarn web`

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |     0.55.4    |
| npm or yarn           |     yarn: 1.13.0    |

Related: #882

**Comment by oxyii** [comment]
@fungilation [Metro react-native bundler](https://github.com/facebook/metro) compile modules in `node_modules`. And most libraries for react-native are published without compilation. But RNWeb applications compile with [react-scripts](https://github.com/facebook/create-react-app) like standard React application. So you must eject your application for including `node_modules` libraries into [babel](https://github.com/babel/babel). See [this discussion](https://github.com/facebook/create-react-app/issues/167) about babel config without ejecting.

If you don't want to eject you can replace react-scripts with [react-app-rewired](https://github.com/timarney/react-app-rewired) and change babel config using [customize-cra](https://github.com/arackaf/customize-cra). Ok, step-by-step:

1. `npm install --save-dev react-app-rewired customize-cra @babel/plugin-proposal-class-properties`

2. Change scripts in your package.json:
```json
scripts: {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
}
```

3. Create `config-overrides.js` in your project root
```js
const path = require("path");
const {override, addBabelPlugins, babelInclude} = require("customize-cra");

module.exports = override(
    babelInclude([
        path.resolve("src"), // your src folder can be another
        path.resolve("node_modules/react-native-elements"),
        path.resolve("node_modules/react-native-ratings"),
        path.resolve("node_modules/react-native-status-bar-height"), // <- I'm not sure that this is necessary
        path.resolve("node_modules/react-native-vector-icons"),
    ]),
    addBabelPlugins(
        "@babel/plugin-proposal-class-properties",
    ),
);
```

And woo a la - [react-native-elements](https://github.com/react-native-training/react-native-elements) buttons works fine without ejecting!

**P.S.** `@babel/plugin-proposal-class-properties` plugin resolve static class properties like `propTypes` or `defaultProps`.

**P.P.S.** Sorry for my english )))

**Comment by oxyii** [comment]
@fungilation And one more...

If you planning use icons in buttons you must load icon fonts manually, something like [this](https://github.com/oblador/react-native-vector-icons#web-with-webpack). Without changes in webpack config works fine too! Just append `@font-face` style into `<head>` node

**Comment by Monte9** [comment]
@haruelrovix thoughts on this issue? Any suggestions on how to fix it?

**Comment by oxyii** [comment]
It's impossible I think... Even if you compile your `src` and publish it into npm, you cannot force third-side developers to do that. I mean your deps [react-native-status-bar-height](https://github.com/ovr/react-native-status-bar-height) or [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). You can try to include this libs into your bundle but I'm not sure that it is correct way.

**Comment by fungilation** [comment]
@oxyii I installed and added exactly what you wrote on https://github.com/react-native-training/react-native-elements/issues/1808#issuecomment-468869382, but no dice. `yarn web` with `import { Button } from 'react-native-elements'` hits the same compile syntax error.

@Monte9 @haruelrovix can you reproduce this, or I somehow did something outside of https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html?

**Comment by oxyii** [comment]
@fungilation Ohh... If your app is already ejected I see no problem to add pathes above into your config!

Can you share your webpack config ?

**Comment by fungilation** [comment]
<Details><Summary>My webpack.config.dev.js</Summary>

```js
const fs = require('fs')
const path = require('path')
const resolve = require('resolve')
const webpack = require('webpack')
const PnpWebpackPlugin = require('pnp-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin')
const InterpolateHtmlPlugin = require('react-dev-utils/InterpolateHtmlPlugin')
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin')
const ModuleScopePlugin = require('react-dev-utils/ModuleScopePlugin')
const getCSSModuleLocalIdent = require('react-dev-utils/getCSSModuleLocalIdent')
const getClientEnvironment = require('./env')
const paths = require('./paths')
const ManifestPlugin = require('webpack-manifest-plugin')
const ModuleNotFoundPlugin = require('react-dev-utils/ModuleNotFoundPlugin')
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin-alt')
const typescriptFormatter = require('react-dev-utils/typescriptFormatter')


// Webpack uses `publicPath` to determine where the app is being served from.
// In development, we always serve from the root. This makes config easier.
const publicPath = '/'
// `publicUrl` is just like `publicPath`, but we will provide it to our app
// as %PUBLIC_URL% in `index.html` and `process.env.PUBLIC_URL` in JavaScript.
// Omit trailing slash as %PUBLIC_PATH%/xyz looks better than %PUBLIC_PATH%xyz.
const publicUrl = ''
// Get environment variables to inject into our app.
const env = getClientEnvironment(publicUrl)

// Check if TypeScript is setup
const useTypeScript = fs.existsSync(paths.appTsConfig)

// style files regexes
const cssRegex = /\.css$/
const cssModuleRegex = /\.module\.css$/
const sassRegex = /\.(scss|sass)$/
const sassModuleRegex = /\.module\.(scss|sass)$/

// common function to get style loaders
const getStyleLoaders = (cssOptions, preProcessor) => {
  const loaders = [
    require.resolve('style-loader'),
    {
      loader: require.resolve('css-loader'),
      options: cssOptions,
    },
    {
      // Options for PostCSS as we reference these options twice
      // Adds vendor prefixing based on your specified browser support in
      // package.json
      loader: require.resolve('postcss-loader'),
      options: {
        // Necessary for external CSS imports to work
        // https://github.com/facebook/create-react-app/issues/2677
        ident: 'postcss',
        plugins: () => [
          require('postcss-flexbugs-fixes'),
          require('postcss-preset-env')({
            autoprefixer: {
              flexbox: 'no-2009',
            },
            stage: 3,
          }),
        ],
      },
    },
  ]
  if (preProcessor) {
    loaders.push(require.resolve(preProcessor))
  }
  return loaders
}

// This is the development configuration.
// It is focused on developer experience and fast rebuilds.
// The production configuration is different and lives in a separate file.
module.exports = {
  mode: 'development',
  // You may want 'eval' instead if you prefer to see the compiled output in DevTools.
  // See the discussion in https://github.com/facebook/create-react-app/issues/343
  devtool: 'cheap-module-source-map',
  // These are the "entry points" to our application.
  // This means they will be the "root" imports that are included in JS bundle.
  entry: [
    // Include an alternative client for WebpackDevServer. A client's job is to
    // connect to WebpackDevServer by a socket and get notified about changes.
    // When you save a file, the client will either apply hot updates (in case
    // of CSS changes), or refresh the page (in case of JS changes). When you
    // make a syntax error, this client will display a syntax error overlay.
    // Note: instead of the default WebpackDevServer client, we use a custom one
    // to bring better experience for Create React App users. You can replace
    // the line below with these two lines if you prefer the stock client:
    // require.resolve('webpack-dev-server/client') + '?/',
    // require.resolve('webpack/hot/dev-server'),
    require.resolve('react-dev-utils/webpackHotDevClient'),
    // Finally, this is your app's code:
    paths.appIndexJs,
    // We include the app code last so that if there is a runtime error during
    // initialization, it doesn't blow up the WebpackDevServer client, and
    // changing JS code would still trigger a refresh.
  ],
  output: {
    // Add /* filename */ comments to generated require()s in the output.
    pathinfo: true,
    // This does not produce a real file. It's just the virtual path that is
    // served by WebpackDevServer in development. This is the JS bundle
    // containing code from all our entry points, and the Webpack runtime.
    filename: 'static/js/bundle.js',
    // There are also additional JS chunk files if you use code splitting.
    chunkFilename: 'static/js/[name].chunk.js',
    // This is the URL that app is served from. We use "/" in development.
    publicPath: publicPath,
    // Point sourcemap entries to original disk location (format as URL on Windows)
    devtoolModuleFilenameTemplate: info =>
      path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
  },
  optimization: {
    // Automatically split vendor and commons
    // https://twitter.com/wSokra/status/969633336732905474
    // https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366
    splitChunks: {
      chunks: 'all',
      name: false,
    },
    // Keep the runtime chunk seperated to enable long term caching
    // https://twitter.com/wSokra/status/969679223278505985
    runtimeChunk: true,
  },
  resolve: {
    // This allows you to set a fallback for where Webpack should look for modules.
    // We placed these paths second because we want `node_modules` to "win"
    // if there are any conflicts. This matches Node resolution mechanism.
    // https://github.com/facebook/create-react-app/issues/253
    modules: ['node_modules'].concat(
      // It is guaranteed to exist because we tweak it in `env.js`
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
    ),
    // These are the reasonable defaults supported by the Node ecosystem.
    // We also include JSX as a common component filename extension to support
    // some tools, although we do not recommend using it, see:
    // https://github.com/facebook/create-react-app/issues/290
    // `web` extension prefixes have been added for better support
    // for React Native Web.
    extensions: paths.moduleFileExtensions
      .map(ext => `.${ext}`)
      .filter(ext => useTypeScript || !ext.includes('ts')),
    alias: {
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
    plugins: [
      // Adds support for installing with Plug'n'Play, leading to faster installs and adding
      // guards against forgotten dependencies and such.
      PnpWebpackPlugin,
      // Prevents users from importing files from outside of src/ (or node_modules/).
      // This often causes confusion because we only process files within src/ with babel.
      // To fix this, we prevent you from importing files out of src/ -- if you'd like to,
      // please link the files into your node_modules/ and let module-resolution kick in.
      // Make sure your source files are compiled, as they will not be processed in any way.
      new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
    ],
  },
  resolveLoader: {
    plugins: [
      // Also related to Plug'n'Play, but this time it tells Webpack to load its loaders
      // from the current package.
      PnpWebpackPlugin.moduleLoader(module),
    ],
  },
  module: {
    strictExportPresence: true,
    rules: [
      // Disable require.ensure as it's not a standard language feature.
      { parser: { requireEnsure: false } },

      // First, run the linter.
      // It's important to do this before Babel processes the JS.
      {
        test: /\.(js|mjs|jsx)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: require.resolve('react-dev-utils/eslintFormatter'),
              eslintPath: require.resolve('eslint'),

            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: paths.appSrc,
      },
      {
        // "oneOf" will traverse all following loaders until one will
        // match the requirements. When no loader matches it will fall
        // back to the "file" loader at the end of the loader list.
        oneOf: [
          // "url" loader works like "file" loader except that it embeds assets
          // smaller than specified limit in bytes as data URLs to avoid requests.
          // A missing `test` is equivalent to a match.
          {
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
            loader: require.resolve('url-loader'),
            options: {
              limit: 10000,
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
          // Process application JS with Babel.
          // The preset includes JSX, Flow, and some ESnext features.
          {
            test: /\.(js|mjs|jsx|ts|tsx)$/,
            include: paths.appSrc,
            loader: require.resolve('babel-loader'),
            options: {
              customize: require.resolve(
                'babel-preset-react-app/webpack-overrides'
              ),

              plugins: [
                [
                  require.resolve('babel-plugin-named-asset-import'),
                  {
                    loaderMap: {
                      svg: {
                        ReactComponent: '@svgr/webpack?-prettier,-svgo![path]',
                      },
                    },
                  },
                ],
                'react-hot-loader/babel',
              ],
              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true,
              // Don't waste time on Gzipping the cache
              cacheCompression: false,
            },
          },
          // Process any JS outside of the app with Babel.
          // Unlike the application JS, we only compile the standard ES features.
          {
            test: /\.(js|mjs)$/,
            exclude: /@babel(?:\/|\\{1,2})runtime/,
            loader: require.resolve('babel-loader'),
            options: {
              babelrc: false,
              configFile: false,
              compact: false,
              presets: [
                [
                  require.resolve('babel-preset-react-app/dependencies'),
                  { helpers: true },
                ],
              ],
              cacheDirectory: true,
              plugins: ['react-hot-loader/babel'],
              // Don't waste time on Gzipping the cache
              cacheCompression: false,

              // If an error happens in a package, it's possible to be
              // because it was compiled. Thus, we don't want the browser
              // debugger to show the original code. Instead, the code
              // being evaluated would be much more helpful.
              sourceMaps: false,
            },
          },
          // "postcss" loader applies autoprefixer to our CSS.
          // "css" loader resolves paths in CSS and adds assets as dependencies.
          // "style" loader turns CSS into JS modules that inject <style> tags.
          // In production, we use a plugin to extract that CSS to a file, but
          // in development "style" loader enables hot editing of CSS.
          // By default we support CSS Modules with the extension .module.css
          {
            test: cssRegex,
            exclude: cssModuleRegex,
            use: getStyleLoaders({
              importLoaders: 1,
            }),
          },
          // Adds support for CSS Modules (https://github.com/css-modules/css-modules)
          // using the extension .module.css
          {
            test: cssModuleRegex,
            use: getStyleLoaders({
              importLoaders: 1,
              modules: true,
              getLocalIdent: getCSSModuleLocalIdent,
            }),
          },
          // Opt-in support for SASS (using .scss or .sass extensions).
          // Chains the sass-loader with the css-loader and the style-loader
          // to immediately apply all styles to the DOM.
          // By default we support SASS Modules with the
          // extensions .module.scss or .module.sass
          {
            test: sassRegex,
            exclude: sassModuleRegex,
            use: getStyleLoaders({ importLoaders: 2 }, 'sass-loader'),
          },
          // Adds support for CSS Modules, but using SASS
          // using the extension .module.scss or .module.sass
          {
            test: sassModuleRegex,
            use: getStyleLoaders(
              {
                importLoaders: 2,
                modules: true,
                getLocalIdent: getCSSModuleLocalIdent,
              },
              'sass-loader'
            ),
          },
          // "file" loader makes sure those assets get served by WebpackDevServer.
          // When you `import` an asset, you get its (virtual) filename.
          // In production, they would get copied to the `build` folder.
          // This loader doesn't use a "test" so it will catch all modules
          // that fall through the other loaders.
          {
            // Exclude `js` files to keep "css" loader working as it injects
            // its runtime that would otherwise be processed through "file" loader.
            // Also exclude `html` and `json` extensions so they get processed
            // by webpacks internal loaders.
            exclude: [/\.(js|mjs|jsx|ts|tsx)$/, /\.html$/, /\.json$/],
            loader: require.resolve('file-loader'),
            options: {
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
        ],
      },
      // ** STOP ** Are you adding a new loader?
      // Make sure to add the new loader(s) before the "file" loader.
    ],
  },
  plugins: [
    // Generates an `index.html` file with the <script> injected.
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
    // Makes some environment variables available in index.html.
    // The public URL is available as %PUBLIC_URL% in index.html, e.g.:
    // <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
    // In development, this will be an empty string.
    new InterpolateHtmlPlugin(HtmlWebpackPlugin, env.raw),
    // This gives some necessary context to module not found errors, such as
    // the requesting resource.
    new ModuleNotFoundPlugin(paths.appPath),
    // Makes some environment variables available to the JS code, for example:
    // if (process.env.NODE_ENV === 'development') { ... }. See `./env.js`.
    new webpack.DefinePlugin(env.stringified),
    // This is necessary to emit hot updates (currently CSS only):
    new webpack.HotModuleReplacementPlugin(),
    // Watcher doesn't work well if you mistype casing in a path so we use
    // a plugin that prints an error when you attempt to do this.
    // See https://github.com/facebook/create-react-app/issues/240
    new CaseSensitivePathsPlugin(),
    // If you require a missing module and then `npm install` it, you still have
    // to restart the development server for Webpack to discover it. This plugin
    // makes the discovery automatic so you don't have to restart.
    // See https://github.com/facebook/create-react-app/issues/186
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    // Moment.js is an extremely popular library that bundles large locale files
    // by default due to how Webpack interprets its code. This is a practical
    // solution that requires the user to opt into importing specific locales.
    // https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
    // You can remove this if you don't use Moment.js:
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    // Generate a manifest file which contains a mapping of all asset filenames
    // to their corresponding output file so that tools can pick it up without
    // having to parse `index.html`.
    new ManifestPlugin({
      fileName: 'asset-manifest.json',
      publicPath: publicPath,
    }),
    // TypeScript type checking
    useTypeScript &&
      new ForkTsCheckerWebpackPlugin({
        typescript: resolve.sync('typescript', {
          basedir: paths.appNodeModules,
        }),
        async: false,
        checkSyntacticErrors: true,
        tsconfig: paths.appTsConfig,
        compilerOptions: {
          module: 'esnext',
          moduleResolution: 'node',
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: 'preserve',
        },
        reportFiles: [
          '**',
          '!**/*.json',
          '!**/__tests__/**',
          '!**/?(*.)(spec|test).*',
          '!src/setupProxy.js',
          '!src/setupTests.*',
        ],
        watch: paths.appSrc,
        silent: true,
        formatter: typescriptFormatter,
      }),
  ].filter(Boolean),

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty',
  },
  // Turn off performance processing because we utilize
  // our own hints via the FileSizeReporter
  performance: false,
}
```
</Details>

**Comment by oxyii** [comment]
@fungilation 

```js
............
          // Process application JS with Babel.
          // The preset includes JSX, Flow, and some ESnext features.
          {
            test: /\.(js|mjs|jsx|ts|tsx)$/,
            include: [  // <- as array
              paths.appSrc,
              path.resolve(__dirname, "node_modules", "react-native-elements"),  // <- JSX libs
              path.resolve(__dirname, "node_modules", "react-native-ratings"),  // <- JSX libs
              // ... and others libs with source code only
            ],
            loader: require.resolve('babel-loader'),
            options: {
............
```

You can change `__dirname` if webpack config is not in project root

**Comment by haruelrovix** [comment]
@fungilation Do you have the repo (with minimal code to reproduce the issue) that can you share?

**Comment by fungilation** [comment]
I just followed https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html, other than upgrading RNE to latest stable.

Zipped from github private repo:
[RNE-RNW-test.zip](https://github.com/react-native-training/react-native-elements/files/2929113/RNE-RNW-test.zip)

**Comment by oxyii** [comment]
@fungilation I'm leaving this issue. I recommend you to read about webpack and babel.

From your repo, after install deps and `@babel/plugin-proposal-class-properties`

![config](https://user-images.githubusercontent.com/39907210/53781126-8a166800-3f18-11e9-824a-783f9c7a4610.png)

![result](https://user-images.githubusercontent.com/39907210/53781130-8f73b280-3f18-11e9-8daf-171c0af17e9d.png)

**Comment by fungilation** [comment]
Thanks, that works. But this should be documented in the docs/blog post.

**Comment by fungilation** [comment]
Thanks, this works. But on end of step 4 in blog post, on web I now get this:

![image](https://user-images.githubusercontent.com/3803466/53785867-c7560800-3ece-11e9-8a4b-a14b9cd0d8de.png)

which isn't center aligned. Breaking change or regression between RNE 1.0 and 1.1?

**Comment by oxyii** [comment]
@fungilation I see 3 errors and 3 warnings in your browser. Share your console tab instead react devTool.

**Comment by oxyii** [comment]
About vertical alignment: As I see in [CRNWA](https://github.com/VISI-ONE/create-react-native-web-app) `index.html` template, react root tag is with no styles. It means empty tag have no height! You need to set height of root tag. Then vertical align will works. I believe in it. Add styles below into `<head>` tag of `public/index.html`

```html
<style>
    html, body {
        height: 100%;
    }
    body {
        overflow: hidden;
    }
    #root {
        display: flex;
        height: 100%;
    }
</style>
```

**Comment by Monte9** [comment]
@fungilation this is great! Thanks for working through the blog post and figuring out the kinks and bugs. Would be really cool if you are able to get to the end of it and then maybe submit a PR to fix the bugs you ran into along the way! 👍 

Also thanks a lot @oxyii for helping out with this issue! 💯 Your help is much appreciated!

**Comment by oxyii** [comment]
@Monte9  I'll try to find the time to test all RNE components on the web. Please wait for the PRs ) I think this issue is solved exhaustively.

**Comment by oxyii** [comment]
@fungilation I added web platform to [Demo app](https://github.com/Monte9/react-native-elements-app). You can clone [this repo](https://github.com/oxyii/react-native-elements-app). Please install deps and start it via `npm start`. For native platforms install globally `expo-cli` and start app via `expo start`. UI is not optimized for web, navigation is not best choice for web but it's works! )))

@Monte9 I added [PR](https://github.com/Monte9/react-native-elements-app/pull/74) with my changes but I believe that it is not yet for master-branch )))

Someone, please, finally close this issue!

**Comment by Bessonov** [comment]
@oxyii thank you very much for your workaround! It works!

**Comment by Bessonov** [comment]
> Someone, please, finally close this issue!

I think it's better to document it in quick start.

**Comment by oxyii** [comment]
@Bessonov Антон, спасибо.

> I think it's better to document it in quick start.

I don't think so. RNE is a **react-native** library. Web platform support is not the main for RNE. But it can be documented on one page near the end of docs, somethink like in [react-navigation docs](https://reactnavigation.org/docs/en/web-support.html). IMHO ))) @Monte9

**Comment by Bessonov** [comment]
> RNE is a **react-native** library.

Well, that's very interesting:
![image](https://user-images.githubusercontent.com/182451/54624879-8503fd80-4a6e-11e9-8033-3324d752b646.png)
:nerd_face:

**Comment by oxyii** [comment]
**far far away offtop**

@Bessonov Let's be realists. How many real RNWeb developers with **real** RNWeb projects in the world? Not only for tests, playing or trying... I do not think that there are more than one thousand. And these people no longer need such detailed docs. They look at the lib sources anyway. For those who use lib to play or try, one docs page near the end is enough, IMHO.

Anybody, please, close this issue )))

**Comment by fungilation** [comment]
I appreciate your help @oxyii and showing workaround. But what's with you, is an open issue offensive to your being? I'm leaving it open until docs are updated, somewhere, I don't care well, doesn't need to be more than 1 liner on the main README, but it should be documented/linked. For everyone's benefit.

Also, it is ironic you are discrediting your own work with getting RNW to work with RNE. How about me and company I'm with, to the contrary. I work for what is effectively Indonesia's Expedia. They are android and native app dominant, but iOS and Web are still obviously important for a ticket booking site/app. I'm leading the charge for them to adopt RN as a faster and better way to iterate on native app dev. And for that, we are attempting to use RNW to share 90%+ of code between iOS, Android and Web.

The company is adding a million app downloads per month. How's that for a use case? Not enough? RNW is also used by Twitter. That's right, Twitter's mobile website is entirely RN and rendered with RNW. Go look it up on google.

So, issue is staying open. Until this project's maintainers says otherwise. 😉

**Comment by oxyii** [comment]
@fungilation 

> RNW is also used by Twitter.

Thanks, I already know that

But issue named `Button compile failure on Web with react-native-web` turned into a discussion about web platform docs. It is not correct for subsequent searches I think. You can open new issue with relevant title about web platform documentation. That is why I ask to close this issue

**Comment by oxyii** [comment]
Exactly related #874, even duplicate !!!

@fungilation 

Do you really compare yourself with twitter? )))

> I'm leading the charge for them to adopt RN as a faster and better way to iterate on native app dev than raw Java+ObjC.

Personal advice: don't do this before you test **all** libs you plan to use. `better way` - may be. `faster` - definitely **not** (if you don’t have a development team like twitter). `react-native-web` is still too "young". I have a just completed project on RNWeb and please trust my experience: problems with web platform integration will arise with **every** library! And not every library contains web platform support docs. You will be forced for hours, even days, to read libs sources. You will be forced to negotiate changes with libs developers or fork and edit libs independently. If you want to bring your platforms closer for now you can pick out platform-independent code such a data models, some behavior and more into private npm packages. Then make two projects: RN for iOS and Android and pure react for web. Maybe later you will be able to integrate web platform into existing RN project.

If anyone gave me such advice in September'18, I would have done so.

**Comment by necolas** [comment]
Twitter has not yet updated to the latest version of RNW but will be soon

**Comment by oxyii** [comment]
@necolas Waiting for m.twitter.com sources, maybe partially, to improve the quality of RNWeb developers code

**Comment by Bessonov** [comment]
> Let's be realists. How many real RNWeb developers with real RNWeb projects in the world? 

And...? Why should it not be improved? RNWeb is why I try `react-native-elements` in the first place. And this error was first feedback which I get. It's not nice experience.

There are another ui libraries for plain react-native, but without web support.

> And not every library contains web platform support docs.

There are not much libraries with web support. Can you suggest one beside of `react-native-elements` and `react-native-web`?

> Exactly related #874, even duplicate !!!

Yes, but your solution not.

**Comment by oxyii** [comment]
@Bessonov You are wrong. Bugs are the best experience!!! They make you delve into the details. And this is a great experience but takes a long time. Most libraries come down to use `TouchableOpacity`, `View` and `Text` in deep sources that work on web. Some developers don't even know that their library supports web platform. So I said that I have to read a lot of libs sources.

> Can you suggest

[react-native-popup-menu](https://github.com/instea/react-native-popup-menu) for example. Web (and UWP) support is a **Community driven features**. This means that someone once tried to run it on web. It worked, but with errors that were corrected by joint efforts. Repo owner did not set web such a goal.

Finally, web is a third-party platform for react-native like Qt or [any other](https://facebook.github.io/react-native/docs/out-of-tree-platforms). I did not say that the docs is not needed. I said that it should not be too much and it should not be mainstream I think.

**Comment by fungilation** [comment]
That's it. @oxyii you are entitled to your own opinions, and I'm entitled to blocking you. Please unsubscribe from this issue, as I'm still not closing this yet. RNE maintainers can clearly overrule me.

I'm with @Bessonov in opinion, obviously. RNW+RNE looks great, I want them to work together for my next project and projects to come.

**Comment by Monte9** [comment]
Guys, first of all.. calm down! There is no reason to turn this discussion into an argument. We are here to help each other and improve the library from the feedback we get. 

Here are my thoughts: 
I think RNW is def a priority for RNE. So we will make sure that we improve the docs & readme with the workaround/solutions discussed here before closing this issue.

@Bessonov I assume this is the workaround that worked and needs to be added to the docs? https://github.com/react-native-training/react-native-elements/issues/1808#issuecomment-468869382

**Comment by Bessonov** [comment]
@Monte9 yes!

**Comment by fungilation** [comment]
For me, these 2 as well I integrated to get RNE 1.1.0 release to the same state as step 4 on the [tutorial](https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html):
* https://github.com/react-native-training/react-native-elements/issues/1808#issuecomment-469533414
* https://github.com/react-native-training/react-native-elements/issues/1808#issuecomment-469594636

These 3 together are both project default and docs updates, to get RNE+RNW to a working state without fussing around. Before Jest (snapshot) tests too to ensure future RNE releases doesn't break what step 4 on tutorial as a working state that should not be broken?

By working state in step 4, I'm referring to this screenshot:
![image](https://user-images.githubusercontent.com/3803466/54770536-a96fef00-4bc0-11e9-8d4b-6bd76bbaff6c.png)

My 2c. Thank you @Monte9 for the great work with RNE, know that if we make this work well together with RNW, we are piloting for potentially multiple future apps we'll introduce to a 200 developers company. Not big like Twitter but still a win nonetheless, that I may write a Medium article about in the future with our experiences.

**Comment by iRoachie** [comment]
A lot of healthy and not so healthy discussion here. Glad we could come to a consensus about going forward. Made another issue to make this actionable.

**Comment by mikeaustin** [comment]
@iRoachie What's the new issue link? I, like many use Create React App to get started quickly, but at some point it becomes a blocker like this situation. Ultimately, I think CRA needs more support for customization.

**Comment by iRoachie** [comment]
https://github.com/react-native-training/react-native-elements/issues/1957
