### ISSUE TITLE
SearchBar missing onPress 

### ISSUE THREAD

**Issue by EddieEJ** [react-native-training/react-native-elements#1809]
Is there a way to check if the SearchBar has been focused (pressed on and the keyboard is up)? I am aware of onChangeText property but it will not trigger if the SearchBar has been only focused and not text has been written.

**Comment by iRoachie** [comment]
Have you looked at [`onFocus`](https://facebook.github.io/react-native/docs/textinput#onfocus)?

**Comment by parnekov** [comment]
> Have you looked at [`onFocus`](https://facebook.github.io/react-native/docs/textinput#onfocus)?

<SearchBar
              ref={(ref) => {this.searchBarRef = ref}}
              autoFocus
              placeholder="Search..."
              onClear={()=> this.searchBarRef.focus()}
            />

answer => this.searchBarRef.focus()
