### ISSUE TITLE
Unable to resolve "lodash.merge" from "ThemeProvider.js"

### ISSUE THREAD

**Issue by pieter888** [react-native-training/react-native-elements#1810]
**Explain what you did**
I wanted to update react-native-elements from v1.0.0 to v1.1.0. 
Ran `npm update` > `npm start` > `react-native run-android`

**Expected behaviour**
Enjoy v1.1.0

**Describe the bug**
The build is successful and my app opens in the android simulator, then the Metro Bundler does his part and halfway trough spits out the following error:

> error: bundling failed: Error: Unable to resolve module `lodash.merge` from `D:\Documenten\GitHub\react-native-houston\node_modules\react-native-elements\src\config\ThemeProvider.js`: Module `lodash.merge` does not exist in the Haste module map

Reverting back to 1.0.0 makes everything work again.

**To Reproduce**
I tried deleting node_modules and run `npm install` again, same error. So I'm not sure what the conditions are that triggers it, just that it never runs on my end. 

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |    0.58.6     |
| npm or yarn           |      6.8.0   |

**Comment by iRoachie** [comment]
You have to restart your packager and clear the cache. It's because we removed lodash.merge for deepmerge in v1.1.0.

`npm start -- --reset-cache`

**Comment by pieter888** [comment]
Thanks that worked perfectly!
Should have tried that first of course... the oversight was 100% on my end.

**Comment by zagorsky** [comment]
I installed the separate [lodash.merge module](https://www.npmjs.com/package/lodash.merge):
`npm install lodash.merge@4.6.1`

**Comment by kiwicopple** [comment]
For those using expo: `expo r -c`
