### ISSUE TITLE
Typing in SearchBar does not work

### ISSUE THREAD

**Issue by pytyl** [react-native-training/react-native-elements#1817]
**Explain what you did**
Attempting to use SearchBar in my app. I have never had a problem using react-native-elements SearchBar in past apps.

**Expected behaviour**
When I type something in the SearchBar, that text should display in the SearchBar.

**Describe the bug**
It seems that typing into the SearchBar is not working in versions 1.0.0 and 1.1.0. Strangely, it works in 1.0.0-beta7.

**Possible Solution**
It seems to work as expected if I use version 1.0.0-beta7 instead of 1.0.0 or 1.1.0.

**Code**
```
<SearchBar
      lightTheme
      platform={Platform.OS}
      containerStyle={{ backgroundColor: "#F5F5F5" }}
      placeholder="Search a Route..."
/>
```

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.1.0 and 1.0.0   |
| react-native          |    0.58.6     |
| npm or yarn           |    npm     |

**Comment by Monte9** [comment]
SearchBar is a controller component, that means you need to use state to set/get the value of the input.

Follow this example: https://react-native-training.github.io/react-native-elements/docs/searchbar.html#usage

**Comment by pytyl** [comment]
Oh ok. I guess since I used version 1.0.0-beta7 in previous apps I never noticed this. Thanks for the great library.

**Comment by lyahyaoui** [comment]
It works perfectly in the previous versions !!! It's a bug!!!! 
SearchBar inherite from TextInput it supposed to behave same way for a TextInput it is not necessary to specify the value it's even not logic to make required  
If we have to set state of our components using searchBar every time a caractere typed the performence will be nasty!!!!
