### ISSUE TITLE
ListItem / FlatList doc examples confusing

### ISSUE THREAD

**Issue by antgel** [react-native-training/react-native-elements#1821]
In the two examples of the [docs](https://react-native-training.github.io/react-native-elements/docs/listitem.html) that deal with RN `FlatList`, I noticed two issues:

1. The data is in `const list`, but the `data` attribute is set to `{this.state.dataSource}` which doesn't exist, and `list` is never used.
2. `keyExtractor = (item, index) => index` returned a warning, so I had to change the code to `keyExtractor = (item, index) => index.toString()`.

**Comment by iRoachie** [comment]
Hey @antgel thanks for submitting. At least one of these has been fixed:
```
keyExtractor = (item, index) => index.toString()
```

Would you mind submitting a PR to fix the first one?

**Comment by antgel** [comment]
To be honest, ordinarily I'd happy submit a PR, but I'm so new to RN, I'd rather leave it to someone who has a clue. Once I get more knowledgeable, for sure I'll submit PRs where I can.

**Comment by YikSanChan** [comment]
Fixed in https://github.com/react-native-training/react-native-elements/pull/1829
