### ISSUE TITLE
alignSelf: 'center' on a button misaligns buttons on Android if button has minWidth set

### ISSUE THREAD

**Issue by devlinb** [react-native-training/react-native-elements#1823]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Expected behaviour**
alignSelf doesn't misalign text of a button

**Describe the bug**
alignSelf: 'center' makes the button text on android all sorts of wrong, using default font Roboto and when using third party fonts.

Only seems to happen with minWidth being set.

Example:

```
<Button 
    title="Find activities"
    buttonStyle={{minWidth: 160, alignSelf: center, borderRadius: 100}}
/>
```

Setting a manual padding seems to work around this issue.

**Screenshots**

![image](https://user-images.githubusercontent.com/11895351/54163881-b8fc7480-4417-11e9-870a-1abf823d3c6a.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1     |
| expo | 32 |

**Comment by devlinb** [comment]
FWIW I removed the ViewComponent in button and moved the styles there to the TouchableComponent up above and that solved multiple bugs I was having with button.

 Any and all other attempts to center a button aside from alignSelf resulted in a lot of misery, trying to use justifyContent: 'center' in containerStyle was being ignored due to some phantom space off to the right of the button, I eventually figured out this blank space was being caused by the ViewComponent.

Note that this is only the case if the button has multiple lines of text! With just 1 line of text the component generally behaves itself, though I am still able to do odd things to it now and then.

**Comment by iRoachie** [comment]
What are you trying to do visually?

**Comment by devlinb** [comment]
> What are you trying to do visually?

Center text on a button that has a minimum width set. My pull request #1831 solves both these issues.

**Comment by iRoachie** [comment]
Really can’t replicate this. See https://snack.expo.io/@roach_iam/grounded-orange

Using your exact code.

![Screenshot 2019-07-14 at 7 22 37 PM](https://user-images.githubusercontent.com/5962998/61190593-c72ffb00-a66c-11e9-8743-11417eb0b45b.png)

**Comment by devlinb** [comment]
> 
> 
> Really can’t replicate this. See https://snack.expo.io/@roach_iam/grounded-orange
> 

Seems to work in newer versions of react native/expo. Closing as it isn't repoing anymore.
