### ISSUE TITLE
Multi-line Buttons do not respect justifyContent: 'center' on containerStyle (or another wrapping view) on iOS

### ISSUE THREAD

**Issue by devlinb** [react-native-training/react-native-elements#1824]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Center a button, with multiple lines of text

**Expected behaviour**
The button is centered

**Describe the bug**
There is unfortunate white space on the right side of the button

**To Reproduce**
https://snack.expo.io/H1PVxsNvN

**Possible Solution**
for iOS, not rendering the <ViewComponent> inside of button.js and moving its style to the parent TouchableComponent works. Breaks android though. 

**Screenshots**

iOS vs Android

![image](https://user-images.githubusercontent.com/11895351/54171658-67b0ad00-4438-11e9-8386-48dc056fb884.png)

![image](https://user-images.githubusercontent.com/11895351/54171735-aa728500-4438-11e9-9f24-4cd8e346721d.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.1.0      |
| react-native          |    Expo 32     |
| npm or yarn           |     NPM    |

**Notes**

Wrapping the Button in another view that attempts to center it doesn't help any.

**Comment by xavier-villelegier** [comment]
@devlinb Why did you use `flexDirection: 'row'` ? If you just use `alignItems: 'center'` it works fine

![image](https://user-images.githubusercontent.com/17592779/54369825-e2ffa200-4676-11e9-9776-55cc76ba77e4.png)


Repro: https://snack.expo.io/@xavier-villelegier/aW50cm

**Comment by devlinb** [comment]
> @devlinb Why did you use `flexDirection: 'row'` ? If you just use `alignItems: 'center'` it works fine

Unfortunately that does not work on Android, text is misaligned.

My fix correctly renders on both iOS and Android.

![image](https://user-images.githubusercontent.com/11895351/54379475-b3d13c80-4646-11e9-8160-339560f88c15.png)

Repro: https://snack.expo.io/rJTM4zdPV

**Comment by devlinb** [comment]
@xavier-villelegier Ping, any concerns you have about my approach here?

**Comment by iRoachie** [comment]
Your example works if you move the maxWidth from the `buttonStyle` to the `containerStyle`.
![Screenshot 2019-07-14 at 7 13 26 PM](https://user-images.githubusercontent.com/5962998/61190527-a1eebd00-a66b-11e9-9339-b4fad7d7f119.png)
![Screenshot 2019-07-14 at 7 13 52 PM](https://user-images.githubusercontent.com/5962998/61190528-a2875380-a66b-11e9-8e0a-e493a2c53700.png)

**Comment by devlinb** [comment]
> 
> 
> Your example works if you move the maxWidth from the `buttonStyle` to the `containerStyle`.
> 
> https://snack.expo.io/@roach_iam/intrigued-fudge

`minWidth` only works if applied to buttonStyle, on both iOS and Android, so I'd still consider this a bug. 

`maxWidth` and `minWidth` should both work on either `buttonStyle` or `containerStyle`.

My proposed fixed means buttonStyle can be used as expected.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
