### ISSUE TITLE
Customize TouchableComponent of Button

### ISSUE THREAD

**Issue by matthieu994** [react-native-training/react-native-elements#1826]
Is it possible to customize the style of the `TouchableComponent` of a Button ?
Ex: I would like to manually set its elevation, but it's not possible apparently.

**Comment by iRoachie** [comment]
You can just use the `buttonStyle` prop.

https://snack.expo.io/@roach_iam/brave-tortilla

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
