### ISSUE TITLE
Change overlay color in Tooltip by props

### ISSUE THREAD

**Issue by cleoreo** [react-native-training/react-native-elements#1827]
First of all, thanks of this awesome library!

Can you add change overlay color props to Tooltip component? I found no way to change the color.

I hoped I can change the overlay color like this.

```
<Tooltip popover={<Text>Info here</Text>} overlayColor={'rgba(0, 0, 0, 0.6)'}>
  <Text>Press me</Text>
</Tooltip>
```

Added a pull request to add this ( #1828 )

**Comment by iRoachie** [comment]
You can use the `windowBackgroundColor` prop https://snack.expo.io/@roach_iam/bad-sandwich

**Comment by cleoreo** [comment]
Thank you for your reply!

I wanna change the tooltip overlay to something like below, and your example cannot help.
If #1828 pull request is not okay, can you suggest another way to achieve the following please?

Thanks again!


![Screen Shot 2019-03-18 at 10 36 17 AM](https://user-images.githubusercontent.com/22050666/54503391-002fbb80-496a-11e9-97c0-fcf8d9728010.png)

**Comment by iRoachie** [comment]
Sorry about that, I saw overlay and thought you were referring to the Overlay component
