### ISSUE TITLE
Font family android

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#1833]
I have a simple ThemeProvider and specify the components style for Text

```ts
export const components: Partial<FullTheme & any> = {
  Text      : {
    style: {
      fontFamily   : type.regular,
      color: Colors.Graphite
    },
  },
};
```

This works fine. But now I want to have a `h1` text with a different fontFamily, so I supply a `style` prop but on android, it doesn't use the supplied fontFamily. I think it has to do with one of the Platform.selects: https://github.com/react-native-training/react-native-elements/blob/master/src/text/Text.js#L72

That being said, if there's a way for me to style all h1 components using the provider it's a fine workaround for me. But I still think it's a bug :D

**Comment by iRoachie** [comment]
You can use the [`h1Style`](https://react-native-training.github.io/react-native-elements/docs/text.html#h1style) prop

**Comment by RWOverdijk** [comment]
@iRoachie I know, but that doesn't do the trick. The android override still happens.

**Comment by RWOverdijk** [comment]
@iRoachie The order of the styles in the component actually tell the same story. styles.bold overrides h1Styles because it's loaded last.

**Comment by iRoachie** [comment]
Ahh, that definitely needs to be fixed.

**Comment by RWOverdijk** [comment]
Maybe a more flexible typography system would be nice? Paragraphs, headers etc being their own components? Flattening styles isn't ideal (for performance) so that could help? Then you can also configure the styles of specific typography components.

**Comment by iRoachie** [comment]
>  Flattening styles isn't ideal (for performance) so that could help
Do you have any research on this?

**Comment by RWOverdijk** [comment]
I'll have to look up the resources. But it has to do with how Stylesheet.create sends the styles over and from there uses the id to reference them.

With flatten, this isn't possible so every render sends the styles over the bridge.
