### ISSUE TITLE
Global config for icon type

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#1834]
Hei!

It would be cool if I could configure the icon pack to use for my entire application without having to pass in the type every time.

I checked the docs and couldn't find it. But I might be blind, and I might not have looked in the right place. It seems like the type of thing I could do using the Themeprovider.

Thanks :D 

**Update:** I found a workaround. But it makes me feel dirty.

```ts
import { Icon } from 'react-native-elements';

Icon.defaultProps = {
  ...Icon.defaultProps,
  type: 'feather',
};
```

**Comment by iRoachie** [comment]
You can set this up in your ThemeProvider, just note that the names used in some icons may not be available in that icon pack.


```jsx
import { ThemeProvider } from 'react-native'

// Define a theme
const theme = {
  Icon: {
    type: 'feather'
  }
}


// Wrap your app in the ThemeProvider
...
<ThemeProvider theme={theme}>
  <App />
</ThemeProvider>
```

**Comment by RWOverdijk** [comment]
Oh.

Are there any docs on configurable properties? I find myself going through the code trying to find these options. Like this one, I did not see.

**Comment by iRoachie** [comment]
Yes it's in the docs as well in the next section https://react-native-training.github.io/react-native-elements/docs/customization.html#the-theme-object

**Comment by RWOverdijk** [comment]
Yeah I found that one, but it doesn't contain the Icon for example. Not a complaint by the way :)

**Comment by iRoachie** [comment]
> Setting styles in the theme is as simple as using the name of the component, as a key and the props you want to change as the value.

**Comment by RWOverdijk** [comment]
🤦‍♂️
