### ISSUE TITLE
SocialIcon does not adhere to default icon type

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#1837]
Configuring the theme with:

```ts
{
  Icon: {
    type: 'feather',
  },
}
```

Works great with regular Icons. However, SocialIcon uses font awesome and not Feather.

**Comment by iRoachie** [comment]
SocialIcon is a different component than the icon. So the theme for entry for Icon would affect it. It's not possible right now to change the icon type for the SocialIcon, see #1534

**Comment by iRoachie** [comment]
SocialIcon is a different component than the icon. So the theme for entry for Icon would affect it.

**Comment by RWOverdijk** [comment]
Too bad it doesn't use the same Icon component... Is that something that would make a nice feature perhaps?

**Comment by iRoachie** [comment]
It could maybe, but the Icon has padding and other styles on it that social icon would have to configure
