### ISSUE TITLE
Feature Request - Additional prop for SearchBar in order to completely customize placeholder style

### ISSUE THREAD

**Issue by augustosamame** [react-native-training/react-native-elements#1840]
Currently it's not possible to style the placeholder for SearchBar component. Only placeholderTextColor is available, but it's insufficient for some uses cases.

I'd propose a prop like placeholderTextStyle

**Comment by augustosamame** [comment]
I've been researching this a bit more and it turns out it's a limitation of the React Native TextInput component the SearchBar uses. Currently React Native only lets you customize placeholder color but all other styling will match the TextInput content styling.

An alternative would be to utilize a custom TextInput component that includes this proposed functionality. Something like this for example:

https://stackoverflow.com/a/39764112/4759794

I can submit a PR if it's something the authors would consider.

**Comment by Monte9** [comment]
Interesting. Thanks for the detailed issue & follow up.

So this `TextInputEnhanced` component would basically extend all the existing props of the RN `TextInput` component and add some additional ones? I assume the behavior will be the same.

**Comment by augustosamame** [comment]
That's correct. It's just a wrapper in order to add the new prop
functionality. All other functionality would be the same.

My only doubt would be which of the following would take precedence in case
of a conflict: placeholderTextColor or the color prop in the new
placeholderTextStyle prop. I can see an argument either way.

**Comment by iRoachie** [comment]
@Monte9 I don't think this is functionality that should be handled by RNE itself. It's not very common that a placeholder will be that different than the content it holds 🤷🏽‍♂️.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
