### ISSUE TITLE
Button Group underlayColor doesn't work

### ISSUE THREAD

**Issue by hydr93** [react-native-training/react-native-elements#1844]
Version: 1.1.0

I tried to to change the underlayColor of ButtonGroup.

```
<ButtonGroup
    ...
    underlayColor="black"
/>
```
However, the color didn't change by that.

Moreover, I believe that Component prop is not working also.

**Comment by iRoachie** [comment]
Seems to work okay. https://snack.expo.io/@roach_iam/amused-tortilla

![Kapture 2019-03-28 at 6 54 31](https://user-images.githubusercontent.com/5962998/55152268-606eec00-5126-11e9-98b8-8cc4e71e5d0e.gif)

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by akhatriST** [comment]
Anyone unable to use underlayColor, In order to change the underlayColor, you need to pass in the `Component` as `TouchableHighlight` like this
```
<ButtonGroup
    ...
    Component={TouchableHighlight}
    underlayColor="black"
/>
```

**Comment by imont034** [comment]
> 
> 
> Anyone unable to use underlayColor, In order to change the underlayColor, you need to pass in the `Component` as `TouchableHighlight` like this
> 
> ```
> <ButtonGroup
>     ...
>     Component={TouchableHighlight}
>     underlayColor="black"
> />
> ```

This worked! Thank you!
