### ISSUE TITLE
Invariant Violation: Element type invalid

### ISSUE THREAD

**Issue by phuquoc** [react-native-training/react-native-elements#1845]
Hello, i'm a newbie on ReactNative, I tried to learn about react-native-elements from this example https://snack.expo.io/rJu6gJfBZ 
I did not use Expo but run my apps on a virtual machine instead, I got the error below, I spent hours and hours to fix it but not worked :(((
![image](https://user-images.githubusercontent.com/20508535/55162393-0b53ca00-5168-11e9-933f-9a38a8fd6880.png)

This problem comes whenever I use an element from react-native-elemen, I tried CheckBox; Button; Text; ...
I installed react-native-elements 1.1.0 and react-native-cli: 2.0.1 react-native: 0.52.3

PLEASEEE help me, many thanks

**Comment by iRoachie** [comment]
The error you are seeing is when you try to import something that doesn't exist. Can you post the code that you wrote to get this error?

**Comment by phuquoc** [comment]
> The error you are seeing is when you try to import something that doesn't exist. Can you post the code that you wrote to get this error?
Oh, thanks for your replies. This is the content of my QuestionItem.js
In the _displayPropositions function; when i added the <Button></Button> tag, it caused the error, same for CheckBox. I dont know why i got it, i tried many ways searched on the Internet but not work

`import React from 'react'
import {View, Text, TouchableOpacity, StyleSheet} from 'react-native'
import {propositions} from '../Data/sampleData'
import { Button} from 'react-native-elements'

export default class QuestionItem extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            propositions : [],
            checked : []
        }
    }

_displayPropositions = () => {
        return(
            <View style={styles.propositions_container}>
                {
                    this.state.propositions.map((option) => {
                        return (
                            <View style={styles.option_container}>      
                                <Text>{option.intitule}</Text>
                                <Button></Button>
                            </View>
                        )
                    })       
                }
            </View>
        )    
       
    }
    
    render() {
        const {question} = this.props
        return (
            <View style={styles.main_container}>
                <View style = {styles.header_container}>
                    <Text style={styles.title_text}>{question.intitule}</Text>                   
                </View>               
                {this._displayPropositions()}
                
            </View>
        )
    }
}
`

**Comment by iRoachie** [comment]
Do you have an example repo or you can replicate with https://snack.expo.io? Just looking at the code you posted it should work

**Comment by ncuillery-youitv** [comment]
I got this one too:
Button is not working, but other components do work:

```javascript
import { Button, Badge, Card, Text, CheckBox } from 'react-native-elements';

render() {
    console.log('###', Button);
    console.log('###', Badge);
    console.log('###', Card);
    console.log('###', Text);
    console.log('###', CheckBox);

    return (
      <View style={styles.screen}>
        <Button title="Hello" />
        <Text>Hello</Text>
      </View>
    );
  }
```
The code above repro the error. In my console, I have the following output:
```
2019-05-22 14:14:21.574 testApp[12802:291061]  I/JavaScript: '###', { '$$typeof': {},
  render: { [Function: forwardRef] displayName: 'Themed.Button' } }
2019-05-22 14:14:21.574 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.Badge' }
2019-05-22 14:14:21.574 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.Card' }
2019-05-22 14:14:21.575 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.Text' }
2019-05-22 14:14:21.575 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.CheckBox' }
```

It noticed that the variable `Button` has not the same shape as the others, so I've updated the render function to return `<Button.render title="Hello" />`... and it works 🙄

Note that I use TypeScript.

Hope I helped

**Comment by ncuillery-youitv** [comment]
I got this one too:
Button is not working, but other components do work:

```javascript
import { Button, Badge, Card, Text, CheckBox } from 'react-native-elements';

render() {
    console.log('###', Button);
    console.log('###', Badge);
    console.log('###', Card);
    console.log('###', Text);
    console.log('###', CheckBox);

    return (
      <View style={styles.screen}>
        <Button title="Hello" />
        <Text>Hello</Text>
      </View>
    );
  }
```
The code above repro the error. In my console, I have the following output:
```
2019-05-22 14:14:21.574 testApp[12802:291061]  I/JavaScript: '###', { '$$typeof': {},
  render: { [Function: forwardRef] displayName: 'Themed.Button' } }
2019-05-22 14:14:21.574 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.Badge' }
2019-05-22 14:14:21.574 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.Card' }
2019-05-22 14:14:21.575 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.Text' }
2019-05-22 14:14:21.575 testApp[12802:291061]  I/JavaScript: '###', { [Function: ThemedComponent] displayName: 'Themed.CheckBox' }
```

It noticed that the variable `Button` has not the same shape as the others, so I've updated the render function to return `<Button.render title="Hello" />`... and it works 🙄

Note that I use TypeScript.

Hope I helped

**Comment by iRoachie** [comment]
Closing as inactive. Unable to replicate this issue. Feel free to message or create a new issue with an example repo if this is still a concern.

**Comment by LinusU** [comment]
I'm running into this problem as well on React Native `0.54.4` and React `16.3.0-alpha.1`...

**Comment by ncuillery-youitv** [comment]
@LinusU I'm using 0.55.0, also a pretty old version too. It may be the cause.

**Comment by LinusU** [comment]
Yeah, probably, currently holding off updating to react-native-elements@1.x until we're on the latest React Native...
