### ISSUE TITLE
Android SearchBar clear button now visible when changing value prop

### ISSUE THREAD

**Issue by Lythenas** [react-native-training/react-native-elements#1846]
**Explain what you did**

I'm setting the value of the search bar after it is first displayed.

**Expected behaviour**

The clear button should appear if the value is not empty.

**Describe the bug**

The clear button does only appear if the user changes the text but not when changing the text programmatically.

**To Reproduce**

https://snack.expo.io/B1fr1vquN

**Possible Solution**

This seems related to #1247 and looks like an easy fix. Don't only set `isEmpty` in the constructor and onChange. Check it dynamically in render.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |     0.59.1    |
| npm or yarn           |     yarn 1.12.3    |

**Comment by Lythenas** [comment]
I can create a pull request if you want.

**Comment by yloeza** [comment]
+ 1 on the suggested solution. I don't see any benefit of maintaining the `isEmpty` in the state, it can be check on the render directly based on `props.value` directly.
Is there any plan on fixing this issue? 
One workaround we  found is via setting a diff `key` value on the component to force react to create a new instance, but this brings some unnecessary complexity.

**Comment by bradylcarey** [comment]
https://github.com/react-native-training/react-native-elements/pull/1868 This PR has been out there since April and should fix this issue. Just need to get it merged....
