### ISSUE TITLE
[v1.1.0] SearchBar input testID not setting

### ISSUE THREAD

**Issue by bensont1** [react-native-training/react-native-elements#1848]
**Explain what you did**
Testing of SearchBar using Detox

**Expected behaviour**
Setting `testID` prop should allow selecting by id

**Describe the bug**
`testID` prop is not being set, defaults to `searchInput` for all SearchBar

Example:

**Possible Solution**
Allow setting of `testID` prop for SearchBar

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |     0.57.5    |
| npm or yarn           |     npm    |

**Comment by yogeshthanvi** [comment]
Hi any updates on this

**Comment by iRoachie** [comment]
Implemented

**Comment by rafaelmotta** [comment]
I didn't get well how to use.

I tried with passing directly testID and inside attributes={{ testID: 'foo' }} but din't work.

Any clue?

Using v1.1.0
