### ISSUE TITLE
Tile image resizeMode

### ISSUE THREAD

**Issue by jcroft** [react-native-training/react-native-elements#1850]
**Explain what you did**
Wanted to change my image in a Tile to resizeMode: contain

**Expected behaviour**
Expected there to be some prop to take this option

**Describe the bug**
It seems to me that resizeMode is always set to cover and cannot be changed.

Is there a reason for this, or a way to do it that I'm not seeing?

Thanks for such a great library!

**Comment by jcroft** [comment]
Thanks so much! :)

**Comment by ethanyuwang** [comment]
having the same issue

**Comment by iRoachie** [comment]
@ethanyuwang Tile now has an `imageProps` prop in which you can pass in the values
