### ISSUE TITLE
Button Icon position to the left side

### ISSUE THREAD

**Issue by trane294** [react-native-training/react-native-elements#1858]
Right now all button icons being shown together with a text on left or right side. Is there any way to make it on left side?

![image](https://user-images.githubusercontent.com/1409277/55778550-0a6c4380-5a58-11e9-81db-c98c9c47bd80.png)

I have tried to use `iconContainerStyle` to make it position absolute but it didn't do anything.

Thank you

**Comment by iRoachie** [comment]
If you add the [`iconRight`](https://react-native-training.github.io/react-native-elements/docs/button.html#iconright) prop it'll display it to the right.

**Comment by smxdevst** [comment]
I asked if there is a way to make it on left side

Smth like this:
![image](https://user-images.githubusercontent.com/13336971/55815340-0ca8bf00-5aa5-11e9-9e09-beb053dbe9ce.png)

**Comment by iRoachie** [comment]
Ohh sorry, misread. There's no way to **only move the icon left and not affect other components inside**. Button uses flexbox with `justify-content: center` to align the elements inside the button to the center.

Most you can do is  `justify-content: space-between`  or `justify-content: flex-start`. But this will move both the title and icon.

### space-between
```jsx
<Button
  title="Icon"
  icon={{ name: 'check-circle', color: '#fff' }}
  buttonStyle={{ justifyContent: 'space-between' }}
/>
```
![image](https://user-images.githubusercontent.com/5962998/55837978-f3c5fb00-5af0-11e9-8d87-8ad34ac514eb.jpeg)
 

### flex-start
```jsx
<Button
  title="Icon"
  icon={{ name: 'check-circle', color: '#fff' }}
  buttonStyle={{ justifyContent: 'flex-start' }}
/>
```
![image](https://user-images.githubusercontent.com/5962998/55838063-2ff95b80-5af1-11e9-897b-c20e81a79bfb.jpeg)

---

If your button has a set width you can hack around with the margin.
```jsx
<Button
  title="Icon"
  icon={{ name: 'check-circle', color: '#fff' }}
  iconContainerStyle={{marginRight: 50 }}
  buttonStyle={{ justifyContent: 'flex-start', width: 200 }}
/>
```

![image](https://user-images.githubusercontent.com/5962998/55838152-76e75100-5af1-11e9-8e74-502b4ba0ceb3.jpeg)

**Comment by umair-khanzada** [comment]
@iRoachie, Sorry, but I think adding a `margin `is not a solution.
I also come around in the same issue and solve with `position` have a look at below fix.

```
containerStyle={{position: 'relative'}}
iconContainerStyle={{position: 'absolute', left: 10}}
```

**Comment by iRoachie** [comment]
Sure, just know that with position absolute if you have a long button title that the icon may cover the title

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by devmagedmaher** [comment]
another solution is to set titleStyle flex to 1.
`
titleStyle={{flex: 1}}
`

**Comment by albertbuchard** [comment]
I solved it by passing `<View>` components in the title and icon with appropriate flex parameters, and using `buttonStyle={{ justifyContent: "space-between" }}`.

```
<Button
        raised
        icon={
          <View
            style={{
              flex: 0.2,
              alignItems: "center",
              justifyContent: "center",
            }}>
            <Icon name={"local-hospital"} type={"material"} color={"#F3F3F4"} />
          </View>
        }
        buttonStyle={{
          borderRadius: 100,
          padding: 12,
          justifyContent: "space-between",
        }}
        title={
          <View
            style={{
              flex: 0.8,
              justifyContent: "center",
              alignItems: "flex-start",
            }}>
            <Text style={{ fontWeight: "300", fontSize: 18, color: "#F3F3F4" }}>
              Aligned button
            </Text>
          </View>
        }
        containerStyle={{
          marginHorizontal: 32,
          marginVertical: 16,
          borderRadius: 100,
        }}
      />
```

<img width="285" alt="Screenshot 2021-08-31 at 21 22 55" src="https://user-images.githubusercontent.com/5343149/131563343-fe903e08-c6ca-424b-9275-5cc11d252972.png">

**Comment by uahnbu** [comment]
I solved it simply by adding
```javascript
<Button titleStyle={{ marginHorizontal: 'auto' }}>
```
![image](https://user-images.githubusercontent.com/27907396/132134479-7e39e399-8b7d-4f1c-b4b4-86bec7995a88.png)

**Comment by mcanikhilprajapati** [comment]
iconRight={true} with icon props
