### ISSUE TITLE
h4Style array

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#1860]
h4Style on the Text component has weird side-effects and don't get applied the same.

Repro is simple:

`<Text h4 h4Style={styles.cardTitle}>{title}</Text>`

and

```js
  cardTitle: {
    marginLeft: Metrics.BaseMargin,
    fontWeight: '400',
    color: Colors.White,
  },
```

<img width="308" alt="Screenshot 2019-04-11 12 46 45" src="https://user-images.githubusercontent.com/781745/55951577-e2e3c980-5c57-11e9-9f3b-32fa7c7cfe7c.png">

Does what's expected but:

`<Text h4 h4Style={[styles.title, styles.cardTitle]}>{title}</Text>`

and

```js
  title: {
    fontWeight: '400',
    color: Colors.White,
  },
  cardTitle: {
    marginLeft: Metrics.BaseMargin,
  },
```

<img width="258" alt="Screenshot 2019-04-11 12 47 35" src="https://user-images.githubusercontent.com/781745/55951615-fd1da780-5c57-11e9-92d3-2e0a7748a859.png">

does not.

**Comment by iRoachie** [comment]
I can't seem to reproduce, they look the same. https://snack.expo.io/SypGI9HcN

![image](https://user-images.githubusercontent.com/5962998/56340467-0212b780-6180-11e9-8fc6-cddebb571b24.png)

**Comment by RWOverdijk** [comment]
I do have some overrides in my theme.. Maybe that addition is the cause?

```
  Text: {
    h4Style: {
      fontFamily: FontFamily.Regular,
      fontSize: FontSize.H4,
      color: Colors.Jet,
    },
```

Could it be that those overrides somehow get applied differently?

**Comment by iRoachie** [comment]
If you have overrides then they won't merge with `h4Style` when the type is different. https://react-native-training.github.io/react-native-elements/docs/customization.html#my-local-styles-aren-t-working-with-the-theme

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by SteveAquino** [comment]
@ RWOverdijk @iRoachie This is still a problem for h1, h2, h3, and h4 elements, specifically with applying `fontWeight` on Android devices.

The problem is with the order of the styles, which is fixed by simply changing the order such that custom styles override the defaults:

```
StyleSheet.flatten([
  styles.text,
  style && style,
  h1 && StyleSheet.flatten([{ fontSize: normalize(40) }, h1Style]),
  h2 && StyleSheet.flatten([{ fontSize: normalize(34) }, h2Style]),
  h3 && StyleSheet.flatten([{ fontSize: normalize(28) }, h3Style]),
  h4 && StyleSheet.flatten([{ fontSize: normalize(22) }, h4Style]),
  h1 && styles.bold,
  h2 && styles.bold,
  h3 && styles.bold,
  h4 && styles.bold,
])
```

Becomes this:

```

StyleSheet.flatten([
  styles.text,
  style && style,
  h1 && styles.bold,
  h2 && styles.bold,
  h3 && styles.bold,
  h4 && styles.bold,
  h1 && StyleSheet.flatten([{ fontSize: normalize(40) }, h1Style]),
  h2 && StyleSheet.flatten([{ fontSize: normalize(34) }, h2Style]),
  h3 && StyleSheet.flatten([{ fontSize: normalize(28) }, h3Style]),
  h4 && StyleSheet.flatten([{ fontSize: normalize(22) }, h4Style]),
])
```

I've already started working on a fix, although I haven't figured out how to simulate an Android device to write a proper test.  The style that needs to be overridden only applies to Android:

```
const styles = StyleSheet.create({
  ...,
  bold: {
    ...Platform.select({
      android: {
        ...fonts.android.bold,
      },
    }),
  },
});
```

**Comment by SteveAquino** [comment]
Here's a PR to resolve this issue: https://github.com/react-native-training/react-native-elements/pull/1969

**Comment by RWOverdijk** [comment]
Haaaa, see I wasn't crazy 😄
