### ISSUE TITLE
showEditButton icon resize

### ISSUE THREAD

**Issue by syedamirali14** [react-native-training/react-native-elements#1862]
where can i give size to showEditButton icon?
any prop for that?

**Comment by iRoachie** [comment]
The editButton prop takes all the props from the Icon component. Size is one of them https://react-native-training.github.io/react-native-elements/docs/avatar.html#editbutton

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
