### ISSUE TITLE
Add background color to the theme object

### ISSUE THREAD

**Issue by AhmedMKamal** [react-native-training/react-native-elements#1863]
I'm using the theme provider of your package to control the app theme but I'm missing the background color property, so can you please add it to your theme object?

**Comment by iRoachie** [comment]
You can add whatever colours you want to the theme object. See https://react-native-training.github.io/react-native-elements/docs/customization.html#the-theme-object,

Which background colour are you referring to?

**Comment by AhmedMKamal** [comment]
Hi @iRoachie, here's the theme object I'm using for now.

```
export interface ITheme extends Theme {
  colors: Theme['colors'] & {
    backgroundColor: string
    backgroundShadeColor: string // this one specific for my current project
    text: { primary: string }
  }
}
```

**Comment by iRoachie** [comment]
I'm trying to understand what problem you're having.

**Comment by deeuu** [comment]
Jumping on the back of this:

@iRoachie would this be an appropriate way to extent the default theme in Typescript, such that the theme attributes can be type-checked?
e.g.
```
export interface ITheme extends Theme {
  colors: Theme['colors'] & {
    backgroundColor: string
  }
}
```
Then use wtih the consumer like so:
```
<ThemeConsumer>
   {( { theme }: ThemeProps<ITheme> ) => (...)
</ThemeConsumer>
```

Many thanks

**Comment by iRoachie** [comment]
See https://github.com/react-native-training/react-native-elements/pull/1894#issuecomment-494019019 @deeuu

**Comment by deeuu** [comment]
Awesome. Thanks.
