### ISSUE TITLE
SearchBar doesn't behave as a TextInput ! SearchBar typing does not work !

### ISSUE THREAD

**Issue by lyahyaoui** [react-native-training/react-native-elements#1864]
Attempting to use SearchBar in my app. I have never had a problem using react-native-elements SearchBar in past apps.
When I type something in the SearchBar, that text should display in the SearchBar.
It seems that typing into the SearchBar is not working in version 1.1.0. Strangely

Code:

<SearchBar containerStyle={{ backgroundColor: "#F5F5F5" }} placeholder="Movie title"/>

The SearchBar inherite from TextInput. TextInput is a controlled component, where the prop value is not required!!! But if value prop is provided the native value will be forced to match it!

So as the SearchBar supposed to behave like TextInput specifying the value must not be mandatory this will impact hardly the performance if we have to set/get state of our component using SearchBar each time a caractere is being typed

Waiting for a this bug fix in the next release !

**Comment by iRoachie** [comment]
You seem to be very flustered, the reason why search bar is controlled component is because of a bug in react native's TextInput, with setNativeProps and `clear` which doesn't behave as expected. This is why it's recommended to use it as a controlled component.

See https://github.com/react-native-training/react-native-elements/issues/1064

**Comment by Chanach** [comment]
Typing in SearchBar does not work. I've followed official documentation: https://react-native-elements.github.io/react-native-elements/docs/searchbar.html

`        <SearchBar 
          placeholder="From" 
          lightTheme
          onChangeText={this.handleSearch}
          value={this.state.searchText}
        />

handleSearch = (searchText) => {
    
    this.setState({searchText});
    //alert(searchText);
  }
`
"react-native-elements": "^1.2.7",

Whould be great get a help

**Comment by iRoachie** [comment]
@Chanach Works as expected https://snack.expo.io/@roach_iam/ranting-chips
