### ISSUE TITLE
Rating BackgroundColor and TextColor props don't work

### ISSUE THREAD

**Issue by lyahyaoui** [react-native-training/react-native-elements#1872]
I am using the Rating component and when I try to change the background color it doesn't change! The box around cannot be adjusted to an other color... This box always stays white.
Also the rating text color does not work!!!!
Do you plan to deliver a fix for this bug there is a workaround that can i use at the moment ?
Here is my code:

                        <Rating readonly
                                startingValue={(item['vote_average'])/2}
                                count={item['vote_count']}
                                ratingBackgroundColor="#000"
                                ratingTextColor="#FFF"
                                ratingColor="#F0AB00"
                                imageSize={24}/>

**Comment by oxyii** [comment]
@lyahyaoui you forgot to add `type={"custom"}` I think. Please read this [docs](https://react-native-training.github.io/react-native-elements/docs/rating.html#ratingbackgroundcolor)

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
