### ISSUE TITLE
Can't use font awesome 5?

### ISSUE THREAD

**Issue by Slodin** [react-native-training/react-native-elements#1877]
**Explain what you did**
Trying to use {Icon} from react-native-elements with type=''font-awesome". 

**Expected behavior**
Show an icon as per font awesome's website list

**Describe the bug**
using type='font-awesome', don't give me font awesome 5 icon sets. Instead it seems to be giving me icons from older (FA4.7) sets if their name match. If nothing matched, it just gives me an error and shows up as a ?

The error only tells me that the name I provided is not matching anything, and gave me a long list of available names.

**How to fix**
I'm not sure if this is a bug or this is purely my end that I installed it incorrectly? But given the doc has 2 steps for installation, I kind of doubt it's installed incorrectly?...I can use vector icon without a problem tho.

Example:

```
import { Icon } from 'react-native-elements';

**omit class constructors and etc**
 
<Icon 
      type='font-awesome'
     name=''file-invoice"
      size={15}
      raised
 />
```

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.1.0  |
| react-native          | 0.59.6 |
| npm or yarn           | npm |
|react-native-vector-icons| 6.4.2|

**Comment by iRoachie** [comment]
We don't support font-awesome 5 currently.
