### ISSUE TITLE
backHandler listener no work if tooltip is visible

### ISSUE THREAD

**Issue by lgngnr** [react-native-training/react-native-elements#1880]
**Explain what you did**
after adding a listener to a back button if the tooltip is visible the listener does no work anymore until i click on the tooltip to close it.
```javascript
 backHandler = BackHandler.addEventListener('hardwareBackPress', () => {
            ... logic
};
```
**Expected behaviour**
the listener should work even if the tooltip is visible

**To Reproduce**
https://snack.expo.io/@lgngr/tooltip-backhandler

in componentDidMount the tooltip is toggled 

1) try press back button and nothing logged in console
2) try to close the tooltip and press backbutton, now can log in console

**Comment by AndreiCalazans** [comment]
The tooltip uses the React Native Modal which overrides the Backhandler as you can see here: https://facebook.github.io/react-native/docs/modal#onrequestclose, You will have to deal with the back call using the `onClose` prop of the tooltip for when it's open https://github.com/react-native-training/react-native-elements/blob/master/src/tooltip/Tooltip.js#L189

**Comment by s349856186** [comment]
@AndreiCalazans How should I use it, can you provide a small example? Thanks

**Comment by AndreiCalazans** [comment]
Unfortunate, due to the way the tooltip was done, you will have to duplicate whatever you are doing in the BackHandler callback. 

So let's say you got something like:

```
 backHandler = BackHandler.addEventListener('hardwareBackPress', handleBackAction)
```

You will have to call this `handleBackAction` in the `onClose` of the tooltip.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by revathskumar** [comment]
> @AndreiCalazans Unfortunate, due to the way the tooltip was done, you will have to duplicate whatever you are doing in the BackHandler callback.

But if the backHandler have a navigation, this will cause the navigation when ever the user closes the Tooltip right? 

Since we are passing `onClose` to `onRequestClose` when the Tooltip is shown and user press the backbutton, the `onClose` should get triggered right? Correct me if I am wrong. 
But when I tested `onClose` is getting triggered with `onDismiss` not with `onRequestClose`.  

the [doc of onRequestClose](https://facebook.github.io/react-native/docs/modal#onrequestclose) says  

> be aware that BackHandler events will not be emitted as long as the modal is open.

This means we won't be able to capture the backHandler as long as the tootip is open?

**Comment by AndreiCalazans** [comment]
Hey @revathskumar, I apologize but I have not been able to get notifications from github. 

I recommend you take a look at the code for the Tooltip, it is not a large component and I am sure you will understand it. https://github.com/react-native-elements/react-native-elements/blob/next/src/tooltip/Tooltip.js

It seems onClose is getting called in`onRequestClose` and `onDismiss`. 

The problem with the BackHandler has to do with React Native. But, the BackHandler subscriber will not trigger when the Modal component is open this is the reason of this comment:

> be aware that BackHandler events will not be emitted as long as the modal is open.


I don't know if this has been changed recently.
