### ISSUE TITLE
[ListItem] Unexpected result when setting "alignItems"

### ISSUE THREAD

**Issue by carsonwah** [react-native-training/react-native-elements#1881]
### Situation

Suppose I have a simple view like this:

```jsx
      <View style={styles.container}>
        <ListItem title='Hello World' subtitle='123' leftIcon={{name: 'av-timer'}} chevron bottomDivider />
        <ListItem title='Hello World' chevron bottomDivider />
        <ListItem title='Hello World' chevron bottomDivider />
        <ListItem title='Hello World' chevron bottomDivider />
        <ListItem title='Hello World' chevron bottomDivider />
      </View>
```

It produces **unexpected behaviour** (see below) when I set the style like this:

```javascript
export default StyleSheet.create({
  container: {
    alignItems: 'center',  // whatever value it is
  },
});
```

I bang my head for a while until I come across this issue: https://github.com/react-native-training/react-native-elements/issues/1142. Then I know the behaviour comes from `alignItems`.

### Screenshots

With `alignItems`:

![螢幕截圖 2019-05-07 02 29 23](https://user-images.githubusercontent.com/25053707/57246525-0f7cdc80-7070-11e9-8ddf-5976f4707040.png)

Without `alignItems`:

![螢幕截圖 2019-05-07 02 28 59](https://user-images.githubusercontent.com/25053707/57246529-11df3680-7070-11e9-8b00-abb71d96b186.png)

### Snack Example

https://snack.expo.io/@carsonwah/cmVhY3

### Comment

I don't think we can just explain the cause in Github Issue and let it be. Many developers will be wasting their time because of this.

### Possible Solution

Either:

- Document this behaviour, or
- Fix it, so that `alignItems` is allowed

### Environment

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |    0.58.6     |
| npm or yarn           |     yarn    |

**Comment by batjko** [comment]
I just ran into the same thing and was wondering why I see no title and subtitle for a while.
Based on this ticket, I will now go without the `alignItems`, but it's really a head scratcher at first.

**Comment by iRoachie** [comment]
Why would you align items center a ListItem though? This is expected behavior, this is how flexbox works in react native

**Comment by batjko** [comment]
> Why would you align items center a ListItem though?

Why wouldn't you? It's not exactly an outlandish use case to want to show items in a list aligned at the center instead of the left.

> This is expected behavior, this is how flexbox works in react native

Well perhaps that's what flexbox does, that's good to know.
But "expected behavior" is certainly not that your items disappear when you're trying to "align items" in whatever way.

It's fine to close the ticket if fixing this would go against react native, but I wouldn't dismiss these concerns so nonchalantly.
