### ISSUE TITLE
Shake effect on Input not working

### ISSUE THREAD

**Issue by isaackhoo** [react-native-training/react-native-elements#1882]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Shake on Input does not work, taken from V1.1.0 example:
<Input
  placeholder='INPUT WITH SHAKING EFFECT'
  shake={true}
/>

**Expected behaviour**
input expected to shake when set to true.

**Describe the bug**
Nothing happens regardless of what is set to it.

**To Reproduce**
follow example given on site:
<Input
  placeholder='INPUT WITH SHAKING EFFECT'
  shake={true}
/>

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | v1.1.0  |
| react-native          |  0.57.1       |
| npm or yarn           |  6.9.0       |

**Comment by iRoachie** [comment]
Shake is a method on the Input not a prop. We need to update the documentation on this.
https://snack.expo.io/@roach_iam/input-shaking

**Comment by isaackhoo** [comment]
Why would it be removed as a prop? Would have been a lot easier to set a boolean on it like in the documentations.
Your example for using refs work, but how could i get it to work in a lifecycle event?

e.g.
`componentDidUpdate() {
  if(shakeInput === true) {
    this.input.current.shake(); 
  }
}`

does not make the input shake when the redux-shakeInput is updated to true.

**Comment by isaackhoo** [comment]
I see, good point made.
I was thinking of handling this issue via redux thunk, to have a second dispatch put on a 2s timeout to change the shake bool back to false.

I'll be closing this issue now, Thanks for the clarification
