### ISSUE TITLE
Image loading placeholder covers children of `ImageBackground`

### ISSUE THREAD

**Issue by SimenB** [react-native-training/react-native-elements#1885]
**Explain what you did**
Rendered a `Button` inside of an `Image` backed by `ImageBackground`.

**Expected behaviour**
For the button to be clickable.

**Describe the bug**
The button is not clickable.

**To Reproduce**
https://snack.expo.io/@folio/image-background-button.

Note that it just fails on iOS, it works correctly on Android.

Swapping `Image` for `ImageBackground` directly also works.

**Possible Solution**
Somehow remove the overlay after it has been faded out? That's what I did in our app to work around this.

**Screenshots**
N/A

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | v1.1.0  |
| expo                  | v32.0.0 |
| npm or yarn           | yarn    |

**Comment by iRoachie** [comment]
Fix Merged. Will be live in 1.2.0
