### ISSUE TITLE
Which props is for CheckBox value?

### ISSUE THREAD

**Issue by emclab** [react-native-training/react-native-elements#1887]
I just started using the CheckBox. Where is the value for the checkbox stored?

**Comment by iRoachie** [comment]
The props is called [checked](https://react-native-training.github.io/react-native-elements/docs/checkbox.html#checked)

**Comment by emclab** [comment]
I have [user_id] as data, but I did not see how I can attached the use_id to a specific checkBox. The `checked` only tells you if the box has been checked and did not tell which user_id was checked.

**Comment by iRoachie** [comment]
How does the data in your state look?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
