### ISSUE TITLE
Tooltip Positioning Issue on Android 

### ISSUE THREAD

**Issue by ManishSharmaApporio** [react-native-training/react-native-elements#1888]
Hi,

getting issue positioning of tooltip in android and in ios works fine

**Comment by oxyii** [comment]
@ManishSharmaApporio duplicate #1871 ?

Please give more info:

1. It is in `Modal`?
2. Are you using `expo`? If yes, in your `app.json` exists `androidStatusBar` prop?
3. Are you using `react-navigation` with `stack` behavior?

**Comment by ManishSharmaApporio** [comment]
1. i m not opening in modal
2.i m not using expo
3.yes i m using react-navigation with stack behavior.

**Comment by oxyii** [comment]
Anyway it looks like StatusBar height issue. `react-navigation` [handle StatusBar height](https://reactnavigation.org/docs/en/handling-iphonex.html#android-notches) (( Please try to use my gist instead RNE Tooltip. See [comment](https://github.com/react-native-training/react-native-elements/issues/1871#issuecomment-485255900). If not, please share code to reproduce.

**Comment by ManishSharmaApporio** [comment]
import React from "react";
import { View, TouchableOpacity, Image, Text, Dimensions } from "react-native";
import { ICON22, ICON21, ICON23 } from "../../../values/ICON";
import { GO } from "../../../values/STRINGS";
import { GREEN } from "../../../values/COLOR";
const slideWidth = 240;
const horizontalMargin = 2;
import { Tooltip } from "react-native-elements";

const itemWidth = slideWidth + horizontalMargin * 2;
const itemHeight = 130;

class HolderMapItem extends React.Component {
  render() {
    const { data } = this.props;
    const { toggleOnPress } = this.state;
    return (
      <TouchableOpacity
        onPress={() => this.props.onItemCLick(data._id, data.coordinates)}
        activeOpacity={1}
        style={[
          {
            position: "relative",
            backgroundColor: "white",
            width: itemWidth,
            height: itemHeight,
            borderRadius: 5
          }
        ]}
      >
        <View style={{ paddingLeft: 5, paddingRight: 5 }}>
          <Text
            style={{
              fontWeight: "500",
              fontSize: 18,
              color: "black",
              padding: 2
            }}
          >
            {data.title["en-US"]}
          </Text>
          <Text style={{ fontSize: 12, color: "black", padding: 2 }}>
            4 rue Tibout-75000 paris-85 m
          </Text>

          <View style={{ flexDirection: "row", padding: 2 }}>
            <Text style={{ fontSize: 14, color: "black", fontWeight: "bold" }}>
              OUVERT-
            </Text>
            <Text style={{ fontSize: 12, color: "black" }}>Ferme a 18000</Text>
          </View>
        </View>

        <View
          style={{
            width: "100%",
            position: "absolute",
            bottom: 0,
            height: 50,
            paddingLeft: 5,
            paddingRight: 5,

            flexDirection: "row"
          }}
        >
          <View
            style={{
              width: "40%",

              flexDirection: "row",
              alignItems: "center",
              justifyContent: "space-around"
            }}
          >
            <Tooltip
              ref="tooltip"
              withOverlay={false}
              popover={
                <View style={{ flex: 1 }}>
                  <TouchableOpacity
                    onPress={() => {
                      this.refs.tooltip.toggleTooltip();
                      this.props.onItemCLick(data._id, data.coordinates);
                    }}
                  >
                    <View style={{ flexDirection: "row" }}>
                      <Image
                        source={{
                          uri:
                            "https://cdn4.iconfinder.com/data/icons/ios7-essence/22/add_plus-512.png"
                        }}
                        style={{ width: 20, height: 20, tintColor: "white" }}
                      />
                      <Text style={{ fontSize: 14, color: "white" }}>
                        Create a new Map
                      </Text>
                    </View>
                  </TouchableOpacity>
                </View>
              }
            >
              <Image source={ICON22} style={{ width: 30, height: 30 }} />
            </Tooltip>

            <Image source={ICON21} style={{ width: 30, height: 30 }} />
          </View>
          <View
            style={{
              width: "60%",
              justifyContent: "center",
              alignItems: "flex-end"
            }}
          >
            <TouchableOpacity
              style={{
                width: 80,
                height: 35,

                borderRadius: 20,
                backgroundColor: GREEN
              }}
            >
              <View
                style={{
                  width: "100%",
                  height: "100%",

                  justifyContent: "space-evenly",
                  alignItems: "center",
                  flexDirection: "row"
                }}
              >
                <Image source={ICON23} style={{ width: 20, height: 20 }} />
                <Text
                  style={{ fontWeight: "bold", color: "white", fontSize: 18 }}
                >
                  {GO}
                </Text>
              </View>
            </TouchableOpacity>
          </View>
        </View>
      </TouchableOpacity>
    );
  }
}

export default HolderMapItem;

**Comment by oxyii** [comment]
@ManishSharmaApporio  this code cannot be reproduced, Please use [markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for code sharing. Or you can create [snack](https://snack.expo.io) to reproduce.

**Comment by oxyii** [comment]
@ManishSharmaApporio I could [run](https://snack.expo.io/@oxyii/tooltip-pos) your code. But I don't see any issue 
![Screenshot_1](https://user-images.githubusercontent.com/39907210/57571123-989a6780-7412-11e9-98be-fae6a845b144.png)
It looks like issue is in StatusBar handled by `react-navigation`. Did you try to use gist?

**Comment by ManishSharmaApporio** [comment]
@oxyii  Have  you tried above example  with gist ?

**Comment by oxyii** [comment]
@ManishSharmaApporio Can you create a [snack](https://snack.expo.io/) with this issue? I don't know how to reproduce your problem including without your assets

**Comment by s349856186** [comment]
I get same issue only android, looks like about "react-navigation", because I used react-navigation@3.0.9, and it's work ok when I test it at snack without react-navigation.
If i modify **Tooltip.js**  --->  yOffset: pageOffsetY, it's work fine. @oxyii

**Comment by ManishSharmaApporio** [comment]
@s349856186 Yeah it works .Thanks a lot man.
If i modify Tooltip.js ---> yOffset: pageOffsetY.

**Comment by Homerade** [comment]
@ManishSharmaApporio can you be more specific about how you used your solution?

**Comment by FDiskas** [comment]
I can reproduce on Pixel 3 XL emulator

**Comment by sashiksu** [comment]
Just use `skipAndroidStatusBar` prop of ToolTip component. No need to edit tooltip.js file.
This works for me. 😋
