### ISSUE TITLE
Ability to use theme props in StyleSheet of react native

### ISSUE THREAD

**Issue by maharjanaman** [react-native-training/react-native-elements#1892]
Can we use theme props in StyleSheet of react native?

**Comment by iRoachie** [comment]
Not understanding the question? Can you be bit more specific?

**Comment by maharjanaman** [comment]
Sorry about the confusion. Just curious if we could use theme props directly when creating styles like
```
const styles = StyleSheet.create({
  container: {
    backgroundColor: theme.color.primary
  }
});
```
?

**Comment by iRoachie** [comment]
Not directly. The theme is passed through the components by using React.Context. To access the context you have to use a component.
