### ISSUE TITLE
Type definition of Avatar/Card/Header image source

### ISSUE THREAD

**Issue by Phecda** [react-native-training/react-native-elements#1897]
**Describe the bug**
From JS Code, Avatar prop `source` should be `ImageSourcePropType`, so as Card and Header.

**Possible Solution**
Change these lines:
https://github.com/react-native-training/react-native-elements/blob/4c900a4d5abd1bcb95ae8ebd35b396c1af88859b/src/index.d.ts#L139

https://github.com/react-native-training/react-native-elements/blob/4c900a4d5abd1bcb95ae8ebd35b396c1af88859b/src/index.d.ts#L494

https://github.com/react-native-training/react-native-elements/blob/4c900a4d5abd1bcb95ae8ebd35b396c1af88859b/src/index.d.ts#L971

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |    0.59.5     |
| npm or yarn           |    yarn     |

**Comment by iRoachie** [comment]
Would you be willing to make this change? Make your PR against `next`

**Comment by mitulsavani** [comment]
@Phecda

Would it look something like this? And is that all that needs to be changed to fix the issue?
> Before
```
source?: ImageURISource; 
```

> After
```
source?: ImageSourcePropType; 
```

**Comment by Phecda** [comment]
@mitulsavani Yes, I think so.

**Comment by mitulsavani** [comment]
Nevermind you already sent a PR. 👍

**Comment by iRoachie** [comment]
Merged. Will be live 1.2.0
