### ISSUE TITLE
Icon load delay

### ISSUE THREAD

**Issue by afshawnlotfi** [react-native-training/react-native-elements#1899]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Load icon aside the ```<Input>```

**Expected behaviour**
Load icon without delay 

**Describe the bug**
The icon has 3-4 seconds delay on iPhone 5 but no delay on iPhone X simulator

**To Reproduce**
Version :     "react-native-elements": "^1.1.0"  
Phone Type : iPhone 5

Step 1 : Run code
```
import { Input, Icon } from 'react-native-elements'

 <Input
            keyboardType={'phone-pad'}
            placeholder='LOGIN WITH PHONE NUMBER'
            leftIcon={
                <Icon
                iconStyle={styles.phoneIcon}
                name='phone'
                size={24}
                color='black'
                />
            }
            />
```

**Possible Solution**
Maybe the phone is too old or the CDN is too slow ...

**Comment by iRoachie** [comment]
Couldn't replicate this on my simulator. Feel free to message or create a new issue if this is still a concern.

**Comment by parthya** [comment]
@iRoachie Try on Android. Works fine on iOS.

**Comment by afshawnlotfi** [comment]
Oh back then I was literally on an iPhone 5 temporarily. This wasn't on the iPhone 5 simulator. But at that point things get slow haha.
