### ISSUE TITLE
inputComponent: propType not allows functions wrapped in React.forwardRef 

### ISSUE THREAD

**Issue by avasuro** [react-native-training/react-native-elements#1901]
**Explain what you did**
Passed function wrapped in React.forwardRef in inputComponent property

**Expected behaviour**
No warning shown

**Describe the bug**
If I pass function wrapped in React.forwardRef in inputComponent property - I got a warning _"Warning: Failed prop type: Invalid prop \`inputComponent\` supplied to \`Input\`."._

**To Reproduce**

Snack:
https://snack.expo.io/HJmRSmSa4

Steps:
1. Run code presented in snack on your device/emulator, because snack web don't display warnings (see this issue https://github.com/expo/snack-web/issues/21)
2. After view will be rendered you will see a warning _"Warning: Failed prop type: Invalid prop \`inputComponent\` supplied to \`Input\`."_

**Possible Solution**
add PropTypes.elementType to list of possible types that can be passed in inputComponent

**Screenshots**
![image](https://user-images.githubusercontent.com/11969473/58312826-c6b97780-7e14-11e9-8bdc-9b5fe367bf90.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |    0.59.8     |
| npm           |    6.9.0     |

**Comment by iRoachie** [comment]
I didn’t get any warnings when i ran your snack https://snack.expo.io/HJmRSmSa4. Is this still occurring for you?

**Comment by avasuro** [comment]
@iRoachie Yes, it is still occurring. If you are run my snack via expo web - please run it on your device or emulator instead, because as I said:

> ...snack web don't display warnings (see this issue expo/snack-web#21)

**Comment by iRoachie** [comment]
Merged 🚀 will be live in 1.2.0
