### ISSUE TITLE
Permission to convert ThemeProvider.js into functional component using react hook

### ISSUE THREAD

**Issue by alexakasanjeev** [react-native-training/react-native-elements#1902]
**Is your feature request related to a problem? Please Describe.**
ThemeProvider.js file inside config folder uses Class component. It can be extracted into functional component using react new hook useState. 

**Describe the solution you'd like**
``` [js]
import React, { useState } from 'react';

const ThemeProvider = ({ theme }) => {
  const [theme,setTheme] = useState({ ...colors, ...theme});

  const updateTheme = updates => {
    setTheme({
        ...theme,
        ...updates,
    });
  };

  const getTheme = () => theme;
   return (
      <ThemeContext.Provider
        value={{
          theme: theme,
          updateTheme: updateTheme,
        }}
      >
        {this.props.children}
      </ThemeContext.Provider>
   );
}
export default ThemeProvider;

```
I would like to create a pull request extracting ThemeProvider but useState hook to use, React dependency need to be updated. in package.json file currently react is using 16.3.1 I want to know whether I can do this, and if yes can I update react dependency to 16.8+ and React native will be updated as a result.

**Additional context**
All it will do is create smaller class file and remove the dependency of using Javascript class

**Comment by iRoachie** [comment]
I don't see why not, go for it

**Comment by alexakasanjeev** [comment]
@iRoachie Thank you for responding, react-native elements is currently using React version `16.3.1` and React hooks were introduced in `16.8`, in order to extract, I have to update react and preferably react-native dependencies to use hooks

My question, can I update react version too ?

**Comment by iRoachie** [comment]
You can try some testing with it and see if it works. I'm assuming you'd have to update tests as well

**Comment by alexakasanjeev** [comment]
Ok sure, and what do you mean by update tests, I don't know anything about testing in general?

**Comment by iRoachie** [comment]
Oh when you clone the project and npm install. You can run the npm test script which will run the unit tests for the components. See https://react-native-training.github.io/react-native-elements/docs/testing.html

**Comment by apihlaja** [comment]
I think that would fix the use-case when you want to change styles on fly. Currently theme cant be updated via props because it's copied in constructor and updates are ignored: https://github.com/react-native-training/react-native-elements/blob/64392b06c00bbf09f8c33e893e5ab25d0e052c25/src/config/ThemeProvider.js#L18

**Comment by alexakasanjeev** [comment]
Hi @iRoachie I tried updating react to 16.8.0+ in order to use react hook, and in order to make it work I started changing other dependency and when I ran `npm test` it was a blood bath, I haven't seen my console this red.

Can you please help me, updating the react dependency is breaking everything, can you guide me, I just want react version to be 16.8.0 so that I can use hooks.

**Comment by kyler-hyuna** [comment]
"blood bath" haha, what'd you see exactly?

**Comment by iRoachie** [comment]
"blood bath" haha, what'd you see exactly?

**Comment by alexakasanjeev** [comment]
Thanks finally managed to update React to 16.8.0 and ran `npm test` and all test are passing.

My second question: in package.json there are other scripts like  `test:update`, 'test:ci` do I need to run that too, if yes how do I run those test?
```
"scripts": {
    ...
    "test": "jest",
    "test:update": "jest -u",
    "test:ci": "jest --runInBand",
    "test:watch": "jest --watch",
    ...
  },
```

**Comment by iRoachie** [comment]
test:update is only to update snapshots if needed

**Comment by alexakasanjeev** [comment]
ok, that means if `npm test` is passing I am good to go

**Comment by alexakasanjeev** [comment]
Hi @iRoachie, Please help, In order to use react hooks, `react` should be >= `16.8.0` and `react-native` should be >= `0.59.0`, when I updated react-native and ran test, it all failed this is the error I am getting
```
✖ jest --env=jsdom --bail --findRelatedTests found some errors. Please fix them and try committing again.
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |        0 |      100 |        0 |        0 |                   |
 ThemeProvider.js |        0 |      100 |        0 |        0 |... 12,14,26,31,37 |
------------------|----------|----------|----------|----------|-------------------|

 FAIL  src/config/__tests__/ThemeProvider.js
● Test suite failed to run

  /home/sanjeev/ReactNativeProjects/react-native-elements/node_modules/react-native/Libraries/Utilities/Platform.ios.js: Unexpected token (51:0)

    Jest encountered an unexpected token
    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
    Details:
      49 | };
      50 | 
    > 51 | module.exports = Platform;
         | ^
      52 | 


```

This is the error related to configuration, and I am unable to resolve it, can you please help me, I have provided the branch on which I have staged code below.

code: https://github.com/alexakasanjeev/react-native-elements/tree/bug/unable-to-update-dependency

**Comment by iRoachie** [comment]
Not to sure about that error, would have to do some debugging.

**Comment by alexakasanjeev** [comment]
Ok, I am currently learning jest, it some error related to parsing javascript code. will try my best

**Comment by wolverineks** [comment]
@alexakasanjeev any progress? I'm reading that enzyme requires jumping through hoops to test `useContext`. https://medium.com/7shifts-engineering-blog/testing-usecontext-react-hook-with-enzyme-shallow-da062140fc83

**Comment by alexakasanjeev** [comment]
Nopes, currently haven't worked in a while will try again

**Comment by iRoachie** [comment]
@alexakasanjeev I just merged a PR that bumps the packages in order to use hooks https://github.com/react-native-training/react-native-elements/pull/1991. You should only need to add your changes on top and update the tests

**Comment by alexakasanjeev** [comment]
Thanks :)

**Comment by iRoachie** [comment]
So don't think we are doing this anymore. Found out recently that by introducing hooks in the project, it will break it for everyone that isn't using a version of react/react-native that doesn't support hooks.

See https://github.com/react-native-training/react-native-elements/issues/2076

**Comment by alexakasanjeev** [comment]
yes, I tried that, and everything is failing. So gave up

**Comment by wolverineks** [comment]
i think react-router does something where you can get the context state from a consumer, ```typescript
<Route>
  {({ match: { params }}) => (<Foo id={params.id} />)}
</Route>
```
or from hooks 
```typescript
const params = useParams()
```

but unless you use the hooks, then its still backward compatible

heres the file i think would be most relevant
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/hooks.js
