### ISSUE TITLE
Jest/enzyme tests fail when importing react-native-elements button

### ISSUE THREAD

**Issue by ksavransky** [react-native-training/react-native-elements#1903]
**Explain what you did**
Every Jest test file that mounts a component using a react-native-element button has started failing when we upgraded from react-native-element 0.19.1 to 1.1.0. Previously all jest tests working working fine. Also, after the upgrade and fixing the props to the new documentation the app components using the RNE buttons actually look and work just fine. But the Jest tests are failing. 

**Expected behaviour**
Expect Jest testing of components using RNE buttons to pass.

**Describe the bug**
Every Jest test for files testing components with RNE button throws this error:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
      
      Check the render method of `Button`.
          in Button (created by Context.Consumer)
          in ThemedComponent (created by ForwardRef(Themed.Button))
          in ForwardRef(Themed.Button) (created by Button)
          in Button (created by Formik)
          in react-native-mock (created by View)
          in View (created by Formik)
          in Formik (created by LoginForm)
          in LoginForm (created by WrapperComponent)
          in WrapperComponent
    console.error node_modules/react-dom/cjs/react-dom.development.js:17117
      The above error occurred in the <react-native-mock> component:
          in react-native-mock (created by View)
          in View (created by Button)
          in Button (created by Context.Consumer)
          in ThemedComponent (created by ForwardRef(Themed.Button))
          in ForwardRef(Themed.Button) (created by Button)
          in Button (created by Formik)
          in react-native-mock (created by View)

**To Reproduce**
Use Jest with Enzyme mount on any component using RNE buttons.
Button imported into component as follows:
import { Button } from 'react-native-elements'

**Possible Solution**
Don't know solution.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |       1.1.0  |
| react-native          |       0.59.8  |
| yarn           |        1.16.0 |

**Comment by iRoachie** [comment]
You need to upgrade your version of enzyme. 1.1.0 introduces ThemeProvider which uses React.forwardRef api. This will fail in older versions of enzyme and react

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by bgneu** [comment]
@iRoachie The current version of enzyme seems to be the latest 3.10.0 and we are still seeing this issue. 

Since this ticket was opened the only thing that has changed from the original description is the following.

software | version
-- | --
react-native | 0.59.9

**Comment by iRoachie** [comment]
Can you create a minimal repo to test this

**Comment by brunsy** [comment]
@ksavransky Maybe you forgot to also update your react-native-elements mocks when updating your project? They will need to include the ThemeProvider.
