### ISSUE TITLE
React native elements checkbox icon display as questions mark

### ISSUE THREAD

**Issue by examineyou65** [react-native-training/react-native-elements#1907]
I am using following version of react native elements and vector icons
 "react-native-elements": "^1.1.0",
 "react-native-vector-icons": "^6.4.2",
I am passing following icon to checkbox component,
  type: "material",
      checkedIcon: "check-box",
      uncheckedIcon: "check-box-outline-blank"
but it shows question mark . i have checked icon list in material where both icons are available.I don't know what is reason it display like question mark.

**Comment by iRoachie** [comment]
Works fine in my tests.

![Kapture 2019-05-30 at 6 46 19](https://user-images.githubusercontent.com/5962998/58628336-69577780-82a7-11e9-9a4d-01b9c9c1b12b.gif)

**Comment by dominictwlee** [comment]
@examineyou65 

I've had this issue before and it was related to the installation of react-native-vector icons. Might want to double check that you have that correctly installed.

**Comment by maxto024** [comment]
@examineyou65  its related to react-native-vector  please make sure you install it and link it

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by romandr25** [comment]
Me too. Please **help**.

At first I had crosses inside squares but now I too have these question marks! 
Trying <Icon> :
```
import { Icon } from 'react-native-elements'
....
<Icon
    raised
    name='heartbeat'
    type='font-awesome'
    color='#f50'
    onPress={() => console.log('hello')}
/>
```
**ReferenceError: Can't find variable: Icon**

Should I open a new question for that?
