### ISSUE TITLE
Allow to change "container" element on Image component

### ISSUE THREAD

**Issue by nartc** [react-native-training/react-native-elements#1908]
**Is your feature request related to a problem? Please Describe.**
Sometimes I want to animate the `Image` component and its parent/wrapper component, I'd have to wrap the `Image` with another `Animated.View` and add animated values to the this `Animated.View` `style` props. `containerStyle` on the `Image` component refers to a normal non-animated `View` so adding animated value to `containerStyle` results in an error.

**Describe the solution you'd like**
Add a `container` prop to `Image` component that will receive a different component other than `View`. Allowing modifying the `container` using prop will reduce the hierarchy to the component tree.

**Describe alternatives you've considered**
If a `container` prop doesn't cut it, allow a prop to notify the Image component that its parent should be an `Animated` component. However, I think this alternative approach would be bad because there is not one defactor Animation library out there. How to determine which Animated API to use would be a hassle. (or impossible)

**Additional context**

**Comment by iRoachie** [comment]
Can you use the [`createAnimatedComponent`](https://facebook.github.io/react-native/docs/animated#createanimatedcomponent) function from Animated to do this?

```jsx
import { Animated } from 'react-native'
import { Image } from 'react-native-elements'

const AnimatedImage = Animated.createAnimatedComponent(Image);

// Use as normal animated component
<AnimatedImage />
```

**Comment by nartc** [comment]
@iRoachie I sure can. In face if I want to animate the Image, that’s what I have to do. But there are cases I want to animate both the Image and the Image container as well. Changing Image to AnimatedImage does not automatically change the View (parent) to AnimatedView. “containerStyle” prop is still a normal View’s StyleProps, it’s not working with animated value.

**Comment by iRoachie** [comment]
Can you explain in an example what you would animate? I don't see a use case where you would want to animate the container itself.

https://snack.expo.io/@roach_iam/amused-carrot
![Kapture 2019-05-31 at 8 15 18](https://user-images.githubusercontent.com/5962998/58705129-421eaa00-837c-11e9-81b4-bdd4d8406a3c.gif)

**Comment by nartc** [comment]
@iRoachie Yes. In my case, I want to animate the Image on scroll. If I only animate the Image height, the image will shrink. To achieve the desired behavior, I need to animate the height of the Container as well as the position (I use translateY for the Container in this case). 

<a href="https://cl.ly/bcf6d205a817" target="_blank"><img src="https://d3r69eeiwn2k86.cloudfront.net/items/12062Y1Q3s441I3l2Z1w/Screen%20Recording%202019-05-31%20at%2010.51%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by nartc** [comment]
Any update on this?

**Comment by iRoachie** [comment]
Can you update them? Sorry about that. You can actually add your gifs here in the issue. Github will upload them

**Comment by nartc** [comment]
@iRoachie I've solved the issue. Turned out it's just some animations problem on my part. Thanks for your time.
