### ISSUE TITLE
I can't change button activity Indicator color 

### ISSUE THREAD

**Issue by voody2506** [react-native-training/react-native-elements#1909]
Hello. I can not change activity indicator color in button element.
This is not working:
`    activityIndicatorStyle:{
      color:'black',
    },`

According to this issue #684
i put color='black' to the button prop

`    <Button
    title=""
    type="solid"
    loading={true}
    color='black'
    />`

But it is not working too!

Could you help me, thanks in advance!

**Comment by iRoachie** [comment]
See [`loadingProps`](https://react-native-training.github.io/react-native-elements/docs/button.html#loadingprops) prop.

```jsx
<Button loading loadingProps={{ color: 'black'}} />
```

**Comment by voody2506** [comment]
It is working! Thank you.

**Comment by Seanmclem** [comment]
This works, but don't make my mistake. I used `loadingStyle={{ color: "black" }}`, but that wasn't right. After changing it to `loadingProps={{ color: "black" }}`, it changes the loading activity indicator on the button as expected. Thanks
