### ISSUE TITLE
Accessibility types in typescript definitions.

### ISSUE THREAD

**Issue by mrmurphy** [react-native-training/react-native-elements#1912]
According to this issue:
https://github.com/react-native-training/react-native-elements/issues/1444

We can use accessible props with `Icon` and `Button`, which is great! But the `index.d.ts` file doesn't list them as acceptable props, so we can't actually pass them in when using typescript without compilation errors.

Thanks for the library!

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/pull/1959. Will be available in 1.2.0
