### ISSUE TITLE
Pricing card array style fo pricingStyle

### ISSUE THREAD

**Issue by aliazizi** [react-native-training/react-native-elements#1913]
**Explain what you did**
I'm trying to add multi style to pricingStyle

**Expected behaviour**

**Describe the bug**
I get this error
`Failed prop type: Invalid prop `pricingStyle` of type `array` supplied to `PricingCard`, expected `object``

**To Reproduce**
Create a PricingCard like this
```
<PricingCard
            pricingStyle={[CommonStyles.textPrimary, { fontSize: 18 }]}
/>
```
**Possible Solution**
Change props types of priingStyle

**Screenshots**
![image](https://user-images.githubusercontent.com/8492767/58870272-23e6e000-86d5-11e9-8a05-de58bd2bd10c.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |      v1.1.0   |
| react-native          |     v0.57    |
| npm or yarn           |         |

**Comment by iRoachie** [comment]
Fixed. Will be available in 1.2.0
