### ISSUE TITLE
[SearchBar] Add option to remove cancel button

### ISSUE THREAD

**Issue by zenorocha** [react-native-training/react-native-elements#1916]
**Is your feature request related to a problem? Please Describe.**

I'm trying to build a UI that contains the SearchBar and a filter icon on the right side. However, I'm having trouble to remove the Cancel button on iOS.

**Describe the solution you'd like**
If there was an attribute that I could set, it would be great, like `<SearchBar cancelButton={false} />`

**Describe alternatives you've considered**

I tried using setting `cancelButtonTitle={''}` and `cancelButtonProps={{ buttonStyle: { opacity: 0 } }}` but it didn't work as expected.

**Comment by bmuthoga** [comment]
@zenorocha I may be wrong, but taking a look at the [tests](https://github.com/react-native-training/react-native-elements/blob/master/src/searchbar/__tests__/common.js#L158) of the `searchbar` component,  I think what you're looking is `clearIcon={false}`. Have you given this a try?

**Comment by zenorocha** [comment]
Thanks!

**Comment by noelq** [comment]
this do not remove the cancel button but the Clear Icon, it is two different things
