### ISSUE TITLE
SocialIcon ReferenceError: Cannot access 'Component' before initialization

### ISSUE THREAD

**Issue by semiautomatix** [react-native-training/react-native-elements#1917]
Added a SocialIcon component with an onPress

**Expected behaviour**
Button to render.

**Describe the bug**
Received an error ReferenceError: Cannot access 'Component' before initialization

```
SocialIcon
E:/tim/React Native/amplify-test/node_modules/react-native-elements/src/social/SocialIcon.js:67
  64 | loading,
  65 | onLongPress,
  66 | onPress,
> 67 | Component = onPress || onLongPress ? Component || TouchableHighlight : View,
     | ^  68 | raised,
  69 | small,
  70 | style,
```

Add SocialIcon to page, make sure to include onPress property.

```
import { Button, Input, Text, SocialIcon } from 'react-native-elements';

...

const Login = () => {

  ...

  return (
    <View style={styles.container}>
          <SocialIcon
            title='Sign In With Facebook'
            button={true}
            type='facebook'
            onPress={() => { }}
          />  
    </View>
  )
}

...

export default Login;

```
> yarn run web

![image](https://user-images.githubusercontent.com/20738236/59358568-182a9780-8d2d-11e9-82f8-53d30f16f786.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | ^1.1.0        |
| react-native          |https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz         |
| npm or yarn           |    yarn 1.16.0     |

**Comment by iRoachie** [comment]
Ahh just confirmed this.

**Comment by iRoachie** [comment]
Alright this is fixed and merged. Will release in 1.2.0
