### ISSUE TITLE
Are form elements gone from new versions? 

### ISSUE THREAD

**Issue by vonwao** [react-native-training/react-native-elements#1921]
I searched google for form elements, and it took me to this page: 
https://react-native-training.github.io/react-native-elements/docs/0.19.1/forms.html

I didn't notice that the URL had an old version, so I was surprised that my form didn't work, and apparently, these components are now gone.  This is confusing.

**Comment by iRoachie** [comment]
Breaking changes are documented both in the release notes and on the website. https://react-native-training.github.io/react-native-elements/blog/2019/01/27/1.0-release.html
