### ISSUE TITLE
Global default for icon type

### ISSUE THREAD

**Issue by dquessenberry** [react-native-training/react-native-elements#1926]
It appears that the default icon font type is "Material Icons". It would be nice to not have to set the type to my preferred icon font each time I want to use an icon. I can't seem to find this feature in the docs or issues on here. If there was a way to configure that default icon type somewhere in the application, that would be a nice feature.

**Comment by iRoachie** [comment]
You technically can do this right now with ThemeProvider as most components used the Icon component.

So it should be as easy as specifying the type in your theme.
```js
{
  Icon: {
    type: 'Ionicons'
  }
}
```

See theming docs https://react-native-training.github.io/react-native-elements/docs/customization.html#theming

**Comment by dquessenberry** [comment]
Thanks, @iRoachie. I'm a newb to this module and I didn't quite understand that the ThemeProvider applies to all children down the tree of components. This is exactly what I was wondering. Thank you.
