### ISSUE TITLE
Divider after <Header/>

### ISSUE THREAD

**Issue by youssefnahas** [react-native-training/react-native-elements#1929]
I found this issue: https://github.com/react-native-training/react-native-elements/issues/654. However, the solution didn't work for me.

**Explain what you did**
Exactly the same, that the other guy was trying to do
![screenshot](https://user-images.githubusercontent.com/46625358/60212254-139fcc00-9861-11e9-9af4-9531d10155b4.jpg)

**My Code**
```
<Header
        placement="right"
        backgroundColor={this.props.backgroundColor}
        leftComponent={this.renderBackButton(this.props.renderBackButton)}
        centerComponent={this.renderSearchButton(this.props.renderSearchButton)}
        rightComponent={this.renderLogo(false)}
      />
```

**The Solution I tried**
I tried to add a containerStyle={styles.headerOuterContainer}

```
<Header
        placement="right"
        backgroundColor={this.props.backgroundColor}
        containerStyle={styles.headerOuterContainer}
        leftComponent={this.renderBackButton(this.props.renderBackButton)}
        centerComponent={this.renderSearchButton(this.props.renderSearchButton)}
        rightComponent={this.renderLogo(false)}
      />

const styles = StyleSheet.create({
  headerOuterContainer: {
    borderBottomWidth: 0,
  }
});
```

I also tried it with outerContainerStyle

**Comment by iRoachie** [comment]
The prop is just `containerStyle` https://react-native-training.github.io/react-native-elements/docs/header.html#containerstyle
