### ISSUE TITLE
ListItem with onPress not working in Browser using react-native-web

### ISSUE THREAD

**Issue by kim-marcel** [react-native-training/react-native-elements#1935]
**Description**
I'm trying to make a list using ```ListItem``` where every item is clickable using the following code:

```javascript
<View>{
       this.props.items.map((items, index) => (
           <ListItem
                key={index}
                title={item.name}
                onPress={() => this.onPress(item)}
           />
       ))
}</View>
```
 
This works perfectly fine on iOS but when I try to run it in the browser using ```react-native-web``` I get the following errors:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

and

```
Invariant Violation: Touchable child must either be native or forward setNativeProps to a native component
```

When I remove ```onPress={..}``` the error disappears.

**Environment**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.1.0      |
| react-native-web |   0.11.4     |
| react-native          |   0.59.8      |
| yarn           |      1.9.4   |

**Comment by ebuckley23** [comment]
You can use one of the touchable components from react-native and set it as the Component prop as such:

`import { TouchableOpacity } from 'react-native'`

`<ListItem
Component={TouchableOpacity}
/>`

**Comment by kim-marcel** [comment]
Thanks @ebuckley23, it works!
