### ISSUE TITLE
Invalid Prop 'subtitle' supplied to 'ListItem'

### ISSUE THREAD

**Issue by Mohammad-Quanit** [react-native-training/react-native-elements#1936]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
What you were trying to accomplish.

**Expected behavior**

**Describe the bug**

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behavior:

Example:

```bash
# Snack
https://snack.expo.io/xxx

# Steps
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

**Possible Solution**
Can you suggest a possible fix that would address this issue?

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |    0.59     |
| npm or yarn           |    yarn  1.12.3   |

I have just tried using react-native-elements but I m facing an issue. I am using ListItem in FlatList for showing list. Everything works fine but 'subtitle' prop not working in my ListItem. Instead, it is giving me a warning: Failed prop type: Invalid Prop 'subtitle' supplied to 'ListItem'.
I am following their documentation and subtitle prop is provided in there doc. but not working in ListItem...
Here's the screenshot
![Screenshot from 2019-07-02 02-34-22](https://user-images.githubusercontent.com/32056694/60468336-bd70c580-9c72-11e9-9ea3-ac82ab2c287e.png)

**Comment by Mohammad-Quanit** [comment]
Here's my code as well.
`{this.state.contactsArr && <FlatList
          data={this.state.contactsArr}
          renderItem={({ item }) => (
            <ListItem
              leftAvatar={{ source: { uri: item.thumbnailPath || 'https://en.toppng.com/public/uploads/thumbnail//contacts-icon-galaxy-s6-11530957358ztr0pj3zte.png' } }}
              title={`${item.givenName != null && item.givenName} ${item.familyName != null && item.familyName}`}
              subtitle={item.phoneNumbers && item.phoneNumbers[0]}
            />
            )}
        />}`

**Comment by iRoachie** [comment]
The `subtitle` prop accepts either a string or a react element in its proptype https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L314. 

The condition `item.phoneNumbers && item.phoneNumbers[0]` will return `false` if the condition fails, and false is a boolean (not a string or an element). Or the value in `item.phoneNumbers[0]` isn't a string or an element.

Instead you can use `item.phoneNumbers ? item.phoneNumbers[0] : ''` and if the condition fails then it'll just be an empty string.

---

In recap there are 2 possible problems:
1. The condition fails returning the value `false`
2. The value stored in ` item.phoneNumbers[0]` is not a string or an element

**Comment by Mohammad-Quanit** [comment]
Thanks @iRoachie , looks like i was doing wrong....i just want to do conditional rendering.
