### ISSUE TITLE
Overlay does not response with Android

### ISSUE THREAD

**Issue by cyb3rsalih** [react-native-training/react-native-elements#1937]
**Explain what you did**
I use Overlay component in any page in my App.
**Expected behaviour**
I expected that it will work just like iOS

**Describe the bug**
The time overlay is visible app does not respond to touches.

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |   1.1.0      |
| react-native          |  59.9       |
|  yarn           |     1.16.0    |

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by cyb3rsalih** [comment]
After a few days I look the code and see my mistake
isVisible value should connect with state.visible. 

This is my previous code.
The condition for hide Overlay, connect with `visible && ` and `isVisible` and `onBackdropPress={() =>setVisible(false)}` 

May android messed up with this.
```
{visible && (
        <Overlay
          onBackdropPress={() =>setVisible(false)}
          isVisible
        />
      )}
```

This works good. 
```
 <Overlay
        onBackdropPress={() => this.setState({visible:false})}
          isVisible={this.state.visible}
        />
```
https://snack.expo.io/@mehmetsalihbindak/lonely-pudding
