### ISSUE TITLE
using react-native-elements with expo web v33

### ISSUE THREAD

**Issue by kluz9** [react-native-training/react-native-elements#1940]
Hello All,

I have been using react-native-elements with react native web for some time now. I recently upgraded to expo v33 and it supports web now.
I am wondering if anyone knows what should I put in webpack.config.js so it works with expo web.

A sample webpack.config.js from expo is given below. Any suggestion how to add instruction to transpile react-native-elements in here

=======================================
const merge = require('webpack-merge');
// This will automatically get the dev/prod config based on process.env.NODE_ENV.
const expoConfig = require('@expo/webpack-config');

// Create a loader which can import `.obj` & `.mtl` (popular 3D model files (not popular enough to be part of the default config though... 😏))
const modelLoaderConfiguration = {
  test: /\.(obj|mtl)$/,
  use: {
    loader: 'file-loader',
  },
};

// Expo expects a function so we can pass around options.
module.exports = function(env, argv) {
  return merge(expoConfig(env, argv), {
    module: {
      rules: [modelLoaderConfiguration],
    },
  });
};

**Comment by iRoachie** [comment]
So i just set up react-native-elements with RNW using create-react-app last night. 

For the babel loader, you need to add to `include` of the babel loader to have:
```js
 path.resolve(__dirname, "node_modules/react-native-elements"),
 path.resolve(__dirname, "node_modules/react-native-vector-icons"),
 path.resolve(__dirname, "node_modules/react-native-ratings"),
```

The libraries ship jsx to npm (not transpiled to es5). So we have to tell babel to transpile them.

See https://github.com/iRoachie/rnw-cra-playground/blob/master/config-overrides.js for example

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by tafelito** [comment]
@iRoachie do you have an example on bow to do this with expo? Where do you put the include? in the babel.config.js or in the webpack.config.js?

**Comment by iRoachie** [comment]
Expo now has a guide for customizing via webpack https://docs.expo.io/versions/v34.0.0/guides/customizing-webpack/

**Comment by tafelito** [comment]
yes thanks I saw that, but not sure how setup RNE properly using the expo webpack config, if there is anything else to be done

**Comment by iRoachie** [comment]
Actually right now if you're using later version of expo, there's no configuration needed.

I just created a fresh expo project, and added react-native-elements.

```bash
npm start
"press w"
```

Project works fine!

![image](https://user-images.githubusercontent.com/5962998/66135777-6a3b4580-e5c8-11e9-862a-2904b58df49d.png)

**Comment by tafelito** [comment]
Does this work to you?
```js
  <ListItem
          title="Test"
          chevron
          bottomDivider
          topDivider
          onPress={() => console.log('press')}
   />

```

I get `Touchable child must either be native or forward setNativeProps to a native component`

**Comment by iRoachie** [comment]
No it doesn't. I think this a problem only with ListItem, but will open another issue on this

**Comment by iRoachie** [comment]
Hey @tafelito just letting you know we released a new version to fix this. [v1.2.5](https://github.com/react-native-elements/react-native-elements/releases/tag/v1.2.5)
