### ISSUE TITLE
LeftAvatar not working on Android

### ISSUE THREAD

**Issue by styk-tv** [react-native-training/react-native-elements#1946]
**leftAvatar** doesnt seem to load on Android based on ListItem example in doc.

Left (Android)  Right (IOS)
<img width="657" alt="Screenshot 2019-07-06 at 11 04 32" src="https://user-images.githubusercontent.com/838921/60754780-12e40400-9fde-11e9-98ea-599f873e54cc.png">

Internet permissions. Check.
<img width="518" alt="Screenshot 2019-07-06 at 11 06 37" src="https://user-images.githubusercontent.com/838921/60754782-24c5a700-9fde-11e9-99c7-403acf1921ee.png">

React-Native info
```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 43.90 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.0 => 0.60.0
  npmGlobalPackages:
```

Versions:
<img width="320" alt="Screenshot 2019-07-06 at 11 08 18" src="https://user-images.githubusercontent.com/838921/60754800-66565200-9fde-11e9-92a7-4d90ec42e57b.png">

Not sure what to think of it since IOS works fine with the example. Any hints would be appreciated.

**Comment by iRoachie** [comment]
Seems to work fine https://snack.expo.io/@roach_iam/rude-blueberries
![image](https://user-images.githubusercontent.com/5962998/60756741-63a03080-9fcf-11e9-920d-8c45d36d7869.png)

**Comment by styk-tv** [comment]
@iRoachie thank you for checking.  i pasted this into snack and confirming all works https://snack.expo.io/@polfilm/elements-with-nav 

but, not on raw emulator, could you please try code from snack **without Expo**? 

I double checked on another version of emulator. Both produce same result. This is killing me.

```
Pixel_2_API_26
Pixel_2_API_28
```

package.json

```
{
  "name": "elementsnav",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "jetifier": "^1.6.1",
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.1",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by iRoachie** [comment]
Just tested on new react-native project:

```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-elements": "https://github.com/react-native-training/react-native-elements.git#next",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/runtime": "^7.5.4",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.1",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  }
```

Works fine!

![image](https://user-images.githubusercontent.com/5962998/61190213-d2802800-a666-11e9-8e47-2e9b2ad3972d.png)

**Comment by leonardo2204** [comment]
Are you on Android 9+? If you are and your images are not https it won't work.
See if [this helps](https://medium.com/mindorks/my-network-requests-are-not-working-in-android-pie-7c7a31e33330).

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
