### ISSUE TITLE
🛎️ UPDATE: Better support 🎉  & accelerated 🚀 development for RNE ❤️️

### ISSUE THREAD

**Issue by Monte9** [react-native-training/react-native-elements#195]
At RNE, we recently committed to providing better support for community issues and PR's as well as an accelerated development for feature requests and new UI components for this library. 

If you come across any UI component that is lacking in this library, we would be more than happy to discuss it with you and develop it over a reasonable timeline. 

Feel free to tag any of us in an issue or PR and we will get back to you ASAP. 
@binoy14 @monte9 @bozzmob @dabit3

**Comment by Monte9** [comment]
Roadmap Features:
1. (Floating labels on FormInput)[https://github.com/react-native-community/react-native-elements/issues/94]

**Comment by Monte9** [comment]
## 1.0 Release Features:
1. Support importing specific components from RNE
2. [Add Theming & Default Styles](https://github.com/react-native-community/react-native-elements/issues/216) - NOT STARTED

**Comment by PavelPZ** [comment]
I would like to vote for "Compatibility with react-native-web" feature.

Looks like there is not easy way to build UIs across all three platforms (ios/android/web). NativeBase web port is stopped (see https://github.com/Chion82/native-base-web - no NativeBase 2.0 support) and it seems to me that only small step is necessary to make **react-native-elements** ready for true cross platform development:

- on #110 I can read ``` I gave react-native-elements a try and the results are great! ```
- on this page I can read ``` It'd be great if react-native-elements can detect Platform & use Platform-specific style properties (like on web, there is no "tintColor") ```

Am I true (I am beginner in react-native)?

**Comment by RWOverdijk** [comment]
Whatever happened to the floating labels for inputs? Both this, and the other issue got closed.

**Comment by shiftrtech** [comment]
> Whatever happened to the floating labels for inputs? Both this, and the other issue got closed.

It would have been nice to have this in version 1.0.0, don't know why is not there and is closed.

**Comment by iRoachie** [comment]
I reopened the issue https://github.com/react-native-training/react-native-elements/issues/94. Feel free to discuss what implementation may look like and how it should behave.
