### ISSUE TITLE
Add docs on using react-native-elements on the web

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#1957]
We currently have a blog post in which we set up react-native-web https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html. However it isn’t really a docs page that’s updated over time.

There was some lengthy discussion on https://github.com/react-native-training/react-native-elements/issues/1808 about improving the instructions for getting this set up. I think we can add a docs page similar to https://callstack.github.io/react-native-paper/using-on-the-web.html.

**Comment by mikeaustin** [comment]
Is create-react-native-web really needed? It has only 161 GitHub stars which seems very low. I installed react-native-web after using create-react-app just fine, but I'm having problems with react-native-elements. Seems package.json/main is pointing to src/index.js. The JSX is not even compiled!

**Comment by iRoachie** [comment]
@mikeaustin you’ll find that for most react native libraries. This is cause metro bundler can read jsx and typescript so libraries don’t go through the stress of compiling.

I didn’t use `create-react-native-web` but it’s useful if you’re starting an app from scratch that’ll support all the platforms in one codebase.
