### ISSUE TITLE
Avatar bad performance with flatlist with multiple rows

### ISSUE THREAD

**Issue by fgagneten** [react-native-training/react-native-elements#1968]
This is the problem:
Is there a way to lazy-load image? Or a way to load image with a % of quality? Because I have a FlatList with 23 rows, each row is an element with an avatar image (230KB). Removing the avatar, the app works fluently, with the avatar the app has a bad performance and is really difficult to navigate (too slow). 

react-native-element: 1.1.0
react-native: 59.5

**Comment by leonardo2204** [comment]
@fgagneten Try [this lib](https://github.com/DylanVann/react-native-fast-image), see if it helps!

**Comment by iRoachie** [comment]
Is this something you can replicate on https://snack.expo.io? Avatar uses the standard RN Image.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by dzpt** [comment]
Same issue putting it on `FlatList` will cause the block of rendering.
