### ISSUE TITLE
about tooltips

### ISSUE THREAD

**Issue by mingxin-yang** [react-native-training/react-native-elements#1982]
**Is your feature request related to a problem? Please Describe.**

**Describe the solution you'd like**
1. The tooltips should be close when I click the back button on android devices.
2. I need a method that can close the tooltips when the tooltips is opening.
**Describe alternatives you've considered**

**Additional context**

**Comment by Gregjarvez** [comment]
@mingxin-yang can you add any screenshot or a basic [expo](https://snack.expo.io/) example of this behaviour, please?

**Comment by mingxin-yang** [comment]
The screenshot does not explain the problem very well.
1. I want the tooltips to disappear when I click on the physical back button of my Android phone. (modal has an onRequestClose method that can do this)
2. There can be a method called to actively close the tooltips. For example, there is a tooltips.close() method for closing the tips.

**Comment by Gregjarvez** [comment]
@iRoachie cheers. I meant a gif of some sort. Thanks for answering that !

**Comment by mingxin-yang** [comment]
![](https://ws1.sinaimg.cn/thumbnail/006d1CrTly1g5kltlftrjg30go0tnnpl.gif)

**Comment by mingxin-yang** [comment]
![img](https://github.com/mingxin-yang/mingxin-yang.github.io/blob/master/images/ezgif.com-gif-maker.gif?raw=true)

**Comment by iRoachie** [comment]
Tooltip has a method called `toggleTooltip` that you can use to close the Tooltip when it is open. https://react-native-training.github.io/react-native-elements/docs/tooltip.html#interaction-methods
