### ISSUE TITLE
inputComponent

### ISSUE THREAD

**Issue by xepisode** [react-native-training/react-native-elements#1984]
Hi,

i have been struggling on how to use picker inside input. is there any documentation or example available that i can refer to? 
been searching for it but no result that help me.

Thanks!

**Comment by Gregjarvez** [comment]
@xepisode why exactly do you need a picker inside an input? Could you clarify your intentions a little bit more? Possibly provide a "half-made"  [expo](https://snack.expo.io/) example  Put comments at the place you intend to put a Picker

**Comment by iRoachie** [comment]
Duplicate of https://github.com/react-native-training/react-native-elements/issues/1730
