### ISSUE TITLE
Unable to resolve "react-native-vector-icons/FontAwesome" using @expo/vector-icons ^10.0.0

### ISSUE THREAD

**Issue by Mr-Cool** [react-native-training/react-native-elements#1986]
We have upgraded our expo project to expo SDK 34, which includes an upgrade of @expo/vector-icons from ^9.0.0 to ^10.0.0.

@expo/vector icons has since removed the dependency they had on react-native-vector-icons and as a result react-native-elements produces the following error:

`Unable to resolve "react-native-vector-icons/FontAwesome" from "node_modules\react-native-elements\src\social\SocialIcon.js"`

![image](https://user-images.githubusercontent.com/4737643/62243004-ba393880-b3dc-11e9-929d-5192d3097994.png)

Would the suggestion be to now install react-native-vector-icons as a standalone dependency?

This is also no longer correct as a result of the above:

![image](https://user-images.githubusercontent.com/4737643/62243135-f1a7e500-b3dc-11e9-8f5b-5cabe90f9965.png)

Thanks

**Comment by iRoachie** [comment]
This is a common problem we have with expo users. Adding react-native-vector-icons should fix this.

```
npm i react-native-vector-icons --save
```

**Comment by Mr-Cool** [comment]
That does indeed fix it, I just wanted to know whether or not this was the right approach to take. Thanks for providing feedback 👍

**Comment by iRoachie** [comment]
Looking forward to making this experience better in the future

**Comment by jgutierro** [comment]
same issue here

**Comment by 5ervant** [comment]
> This is a common problem we have with expo users. Adding react-native-vector-icons should fix this.
> 
> ```
> npm i react-native-vector-icons --save
> ```

Did not work.. :( https://github.com/react-native-elements/react-native-elements/issues/2127
