### ISSUE TITLE
Image placeholder in android, always showing

### ISSUE THREAD

**Issue by vincegnzls** [react-native-training/react-native-elements#2000]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I have an Image component and I added a PlaceholderContent in it. Please see code below for reference:

const spinner = () => {
        return (
            <View style={{alignItems: 'center', 'justifyContent': 'center'}}>
                <Spinner color='#fff' />
            </View>
        )
    }

styles.image = {
        width: responsiveWidth(13),
        height: responsiveWidth(13)
    }

<Image style={styles.image} source={{ uri: image }} resizeMode="cover" placeholderStyle={{ backgroundColor: 'transparent' }} PlaceholderContent={spinner()} />

**Expected behaviour**
In android, after loading an image, the spinner should not render anymore.

**Describe the bug**
In android, after loading the image, the spinner is still showing up. It works fine however in iOs

**To Reproduce**
#Steps
1. Use <Image/> component from 'react-native-elements'
2. Add a PlaceholderContent
3. Run on android device
4. Image will render with PlaceholderContent always

**Screenshots**
![bug](https://user-images.githubusercontent.com/12133723/62419508-3d47e080-b6b4-11e9-95dc-27aaf85dfb37.jpg)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements ^1.1.0
| react-native ^0.59.9
| npm or yarn  6.10.0

**Comment by vincegnzls** [comment]
The image has a transparent background with png file extension.

**Comment by iRoachie** [comment]
Already fixed in the upcoming version. https://github.com/react-native-training/react-native-elements/pull/1992

**Comment by pavilion** [comment]
I believe this bug is still happening

**Comment by pavilion** [comment]
Loading when processing works, however it keeps loading after the image has been loaded.

**Comment by iRoachie** [comment]
@pavilion I couldn't replicate this. https://snack.expo.io/@roach_iam/calm-yogurt. Check if you're on the most up to date version.

If you have any other problems open a new issue
