### ISSUE TITLE
supplying invalid prop to subtitle (callback function)

### ISSUE THREAD

**Issue by dmargu** [react-native-training/react-native-elements#2002]
*Explain what you did**
So I am conditionally rendering the subtitle based on if my listitem has a date prop. That's all fine except then if it does have a date prop I want to format the subtitle depending on if it is the current day or not (so like nested conditional rendering).

**Expected behaviour**
It works perfectly fine I am just getting a warning saying I supplied an invalid prop type. I believe it is because I am using a callback function that returns a text tag, instead of just writing in a text tag.

**Describe the bug**
Warning: failed prop type: invalid prop 'subtitle' supplied to 'listitem'

| expo          |   3.0.6      |
| npm or yarn           |  6.9.0       |

//this is how I call the subtitle
subtitle={todoItem.date ? this.renderDate.bind(this) : null}

//this is my renderDate() function

renderDate() {
    const todoItem = this.props.todoItem;
    return moment(todoItem.date).format('YYYY MM DD') === moment(new Date()).format('YYYY MM DD') ?
      <Text>{moment(todoItem.date).format('h:mm a')}</Text> :
      <Text>{moment(todoItem.date).format('MMM DD')}</Text>;
  }

I am unsure if there is a way to do this without a callback function.

**Comment by iRoachie** [comment]
Why wrap it in braces? 

Can't you return:

```js
renderDate() {
  const todoItem = this.props.todoItem;
  return moment(todoItem.date).format('YYYY MM DD') ===
    moment(new Date()).format('YYYY MM DD')
    ? moment(todoItem.date).format('h:mm a')
    : moment(todoItem.date).format('MMM DD');
}

```

**Comment by dmargu** [comment]
When I try doing that I get-

Invariant violation: text strings must be rendered within a text component.

However when I do it the way I posted it actually works completely fine it just gives me the warning.

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by dmargu** [comment]
https://snack.expo.io/HJuZh-vmS

Here is the snack, I don't see a warning on the snack but I do every time I run it on the iphone (real device or simulator).

**Comment by iRoachie** [comment]
That's because you are not actually calling the renderDate method instead you are just passing a function as a prop.

` this.renderDate.bind(this)` is a function and not executing the function. This is why you get the propType warning. 

Instead you can either use class properties:
```jsx

/* Notice arrow function here */
renderDate = () => {
  const item = { text: 'item1', date: new Date() };

  return moment(item.date).format('YYYY MM DD') ===
    moment(new Date()).format('YYYY MM DD') ? (
    <Text>{moment(item.date).format('h:mm a')}</Text>
  ) : (
    <Text>{moment(item.date).format('MMM DD')}</Text>
  );
};

render() {
  const item = { text: 'item1', date: new Date() };
  return (
    <View style={styles.container}>
      <ListItem
        title={item.text}
        subtitle={item.date ? this.renderDate() : null}
      />
    </View>
  );
}
```


Or call the binded function:
```jsx

/* Notice arrow function here */
renderDate() {
  const item = { text: 'item1', date: new Date() };

  return moment(item.date).format('YYYY MM DD') ===
    moment(new Date()).format('YYYY MM DD') ? (
    <Text>{moment(item.date).format('h:mm a')}</Text>
  ) : (
    <Text>{moment(item.date).format('MMM DD')}</Text>
  );
};

render() {
  const item = { text: 'item1', date: new Date() };
  return (
    <View style={styles.container}>
      <ListItem
        title={item.text}
        subtitle={item.date ? this.renderDate.bind(this)() : null}
      />
    </View>
  );
}
```

**Comment by dmargu** [comment]
Yes! Adding the extra parenthesis and calling the function fixed the problem. Thank you very much for your help!
