### ISSUE TITLE
Header backgroundImage incorrect prop type?

### ISSUE THREAD

**Issue by aaronmgdr** [react-native-training/react-native-elements#2003]
**Explain what you did**

I used the `Header` component's `backgroundImage` prop to add a background image 

```
<Header     backgroundImage={require("./assets/images/background.jpg")} />
```
This works however I get a proptype warning about how it should be an object (see bug description)

**Expected behaviour**
`backgroundImage` of `Header` can accepts the same type of prop as the `source` prop of `Image`

**Describe the bug**

When I use `backgroundImage={require("./assets/images/background.jpg")} ` i get 
```
Warning: Failed prop type: Invalid prop `backgroundImage` of type `number` supplied to `Header`, expected `object`.
```

when I use the object form like 
` backgroundImage={{uri :require("./assets/images/background.jpg")}}`  the image doesn't show and I get another prop error 

```
Warning: Failed prop type: Invalid prop `source` supplied to `Image`.
```

so this leads me to think the correct was is `backgroundImage={require("./assets/images/background.jpg")}` and that the propType for  backgroundImage should be  compatible with `number` 

**To Reproduce**
```
<Header  backgroundImage={require("./path/toA/localImage.jpg")} />
```

also see above

**Possible Solution**
changing propType of backgroundImage to be compatible with require('path.jpg') and OR making it more clear what the object that it wants should look like

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.1.0    |
| react-native          |    0.59.8     |
| npm or yarn           |    yarn 1.17.3|

**Comment by iRoachie** [comment]
Just fixed on `next` branch. Will be available in 1.2.0
