### ISSUE TITLE
Avatar - anomaly change backgroundColor for container editButton

### ISSUE THREAD

**Issue by bsatria** [react-native-training/react-native-elements#2009]
**Explain what you did**
i'm trying to change backgroundColor for container editButton in Avatar Component,  its work but not fully change a circle of editButton.

**Expected behaviour**
can fully change the container of backgroundColor in editButton

**Screenshots**
<img width="188" alt="Screen Shot 2019-08-11 at 13 49 43" src="https://user-images.githubusercontent.com/15060063/62830861-e2783100-bc3f-11e9-8ed7-eaa51b206be4.png">

**My Code**
`
<Avatar 
          rounded
          size={110}
          source={{
            uri:
              "https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg"
          }}
          onEditPress={() => alert("edit")}
          showEditButton
          editButton={{
            name: "ios-camera",
            type: "ionicon",
            color: "#fff",
            containerStyle: { backgroundColor: "red" }
          }}
        />
`

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.1.0    |
| react-native          |     0.60.4    |
| npm or yarn           |      1.6   |

**Comment by iRoachie** [comment]
The prop you should use here is just the style attribute. 

```jsx
<Avatar
  showEditButton
  editButton={{
    style: { backgroundColor: 'red' },
  }}
/>
```

See example https://snack.expo.io/@roach_iam/smiling-sandwich

**Comment by bsatria** [comment]
thanks, @iRoachie its work, but I don't see prop style in Icon documentation, and then what the purpose of containerStyle? the containerStyle not working.

**Comment by iRoachie** [comment]
`containerStyle` is for changes like margin. It mainly for controlling how components around it are affected.

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
