### ISSUE TITLE
Is there a way to slide a ListItem to show a button?

### ISSUE THREAD

**Issue by Jatapiaro** [react-native-training/react-native-elements#2010]
I'm looking for some feature like this using ListItem:

https://koenig-media.raywenderlich.com/uploads/2014/01/iOS-Simulator-Screen-shot-Nov-28-2013-1.06.41-PM-213x320.png

Is there a way to achieve this?

**Comment by iRoachie** [comment]
Not possible at the moment. Dup of #242
