### ISSUE TITLE
Will removing the opencollective-postinstall module installed by npm with react-native-elements break anything?

### ISSUE THREAD

**Issue by stephenstewart-ca** [react-native-training/react-native-elements#2013]

**Comment by iRoachie** [comment]
What's the issue you're asking? Removing opencollective-postinstall doesn't change anything

**Comment by stephenstewart-ca** [comment]
To be clear, do I have your assurance that removing the opencollective-postinstall module installed in my project by npm with the react-native-elements module won't break anything?

**Comment by iRoachie** [comment]
It's not needed for the library to run, so if it is removed the library would still work. However, we still want to include it. It lets users know that we have an open collective and how they can contribute to the development of the library.

**Comment by stephenstewart-ca** [comment]
That's fine, you included it. I got the message. If I use react-native-elements, I'll contribute to your open collective, but I don't want your message to users in my project. If you can live with that, I'll delete the opencollective-postinstall module in my project and evaluate react-native-elements.

If the opencollective-postinstall can't be deleted from my project, either because it will break something or just because you want me to include it in my project, then my evaluation is over and I'll delete react-native-elements.

Pick one.

**Comment by iRoachie** [comment]
> If I use react-native-elements, I'll contribute to your open collective, but I don't want your message to users in my project

Your users are developers?

> If the opencollective-postinstall can't be deleted from my project, either because it will break something or just because you want me to include it in my project, then my evaluation is over and I'll delete react-native-elements.

React Native Elements is an open source library. In the true nature of open source if you don’t agree with something you’re free the fork the project and maintain your own fork. You threatening to delete react native elements from your project has no effect on me or any of the contributors. The project aims to provide value to users. If you don’t find value from it then you’re free to not use it.

**Comment by stephenstewart-ca** [comment]
"Your users are developers?"

Of course not. My users use apps that might include react-native-elements if, among other things, opencollective-postinstall is removed from the library. 

"You threatening to delete react native elements from your project has no effect..."

No threat intended.

1. Developers report errors thrown by opencollective-postinstall during development with react-native-elements.

2. If using react-native-elements requires embedding your fundraising pitch in my product, it isn't the library for me. I can't find your fundraising pitch anywhere in my product specification.

**Comment by iRoachie** [comment]
> Of course not. My users use apps that might include react-native-elements if, among other things, opencollective-postinstall is removed from the library.

Postinstall scripts don't affect actual users of the app or whatever you're building. The user has no idea these scripts even exist.

> Developers report errors thrown by opencollective-postinstall during development with react-native-elements.

Open collective doesn't have any negative effects on developer UX. The issues we had before were with another opencollective library which we changed out. See https://github.com/react-native-training/react-native-elements/pull/1410. We then made a second change where the postinstall will never affect developer builds in https://github.com/react-native-training/react-native-elements/pull/1865

**Comment by stephenstewart-ca** [comment]
Stop. May I remove opencollective-postinstall from react-native-elements? Yes or no. Pick one.

**Comment by iRoachie** [comment]
You can make whatever changes you need to in your fork. You haven't provided any discussions on why we as a library should remove it, or how it would improve the library.

You've only spoken of your own feelings/what you want. There's no point in continuing this discussion.  Best of luck in your OSS journey.
