### ISSUE TITLE
SearchBar on IOS can't input Chinese

### ISSUE THREAD

**Issue by kangbb** [react-native-training/react-native-elements#2021]
**Explain what you did**
I use a `SearchBar` with `reagent`, which builds by `Expo`.

**Expected behaviour**
The SearchBar can run correctly.

**Describe the bug**
SearchBar call ios keyboard, but all options of input methods will input a English.

**Comment by iRoachie** [comment]
What is reagent?

**Comment by kangbb** [comment]
> What is reagent?

I'm so sorry, this is reason of `reagent`. I will close the issue.

**Comment by musesfish** [comment]
？？
