### ISSUE TITLE
Button underlay color

### ISSUE THREAD

**Issue by gunnartorfis** [react-native-training/react-native-elements#2022]
**Explain what you did**
While a touch is active on the Button component, this happens.
The button has the background color as specified in the theme. 

**Expected behaviour**
The button should use the background color (underlayColor) that is trying to be overwritten via the buttonStyle prop. 

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |     0.60.4    |
| npm or yarn           |    1.17.0     |

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this? Which platform are you seeing this on?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
