### ISSUE TITLE
Update the theme object at runtime

### ISSUE THREAD

**Issue by msageryd** [react-native-training/react-native-elements#2028]
**Is your feature request related to a problem? Please Describe.**
My original theming information lives in the database behind an API. Based on which user logs in the theme is sent to the app so it can be branded correctly. 

I cannot find any way to update the theme object and reapply the new theme to the whole component tree.

**Describe the solution you'd like**
I would like to be able to change the details of a theme at runtime. Hopefully, this is already possible and I have missed something.

**Comment by iRoachie** [comment]
You can use the `updateTheme` function that's apart of the theming utils. https://react-native-training.github.io/react-native-elements/docs/customization.html#using-the-theme-in-your-own-components

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.
