### ISSUE TITLE
Rating: 'componentWillReceiveProps is deprecated'

### ISSUE THREAD

**Issue by zbagley** [react-native-training/react-native-elements#2029]
## Reproduction
Add basic `<Rating>` element.

## Expected behavior
Fully comply with 0.60 RN.

## Warning
Warning: componentWillReceiveProps is deprecated and will be removed in the the next major version. Use static getDerivedStateFromProps instead. Please update the following components: SwipeRating.

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.1.0       |
| react-native          |       0.60.3  |
| npm          |      6.10.3   |

**Comment by iRoachie** [comment]
@Monte9 You'll need to update this in your lib https://github.com/Monte9/react-native-ratings/search?q=componentWillReceiveProps&unscoped_q=componentWillReceiveProps

**Comment by Monte9** [comment]
This is fixed in RNRatings v6.5. @iRoachie can you upgrade the version in RNE and close this issue?

**Comment by iRoachie** [comment]
Done
