### ISSUE TITLE
Chevron color in listitem not working and listitem row lines are not showing

### ISSUE THREAD

**Issue by heyaj19** [react-native-training/react-native-elements#2032]
**Explain what you did**
I tried to add a color a to a chevron in a list item and it does not work. I tried adding a color dynamically and just by setting it like chevronColor.  Also row lines are not showing in listitem

**Expected behaviour**
Chevron color should change to the color set and rowlines are not showing either

**To Reproduce**

```
<ListItem
      	containerStyle={{backgroundColor: 'green'}}
         key={i}
         title = { item.title }
         chevron
       	 chevronColor ='red'
         leftIcon = {{ name: item.icon, color: Colors.brandMainRed, type: item.type }}
         onPress = {() => {console.log('hello')}}
         
      />
```

| software              | version |
| --------------------- | ------- |
| react-native-elements |      1.1.0   |
| react-native          |      0.59.9   |
| npm or yarn           |    1.17.3     |

**Comment by iRoachie** [comment]
`chevronColor` isn't a prop. Being in the docs was a mistake. See #2033 

Instead, you should use the `chevron` prop to do this.

```jsx
<ListItem chevron={{ color: 'red' }}/>
```

**Comment by heyaj19** [comment]
@iRoachie  Awesome ill fix that, any idea about the lines not showing up?

**Comment by iRoachie** [comment]
You'll have to make use of the [bottomDivider](https://react-native-training.github.io/react-native-elements/docs/listitem.html#bottomdivider) prop.

**Comment by heyaj19** [comment]
@iRoachie thanks that fixed it. Sorry the documentation made no mention of it in the examples. My bad thank you

**Comment by iRoachie** [comment]
Thanks for heads up. Made an issue to add it to the examples https://github.com/react-native-training/react-native-elements/issues/2035
