### ISSUE TITLE
Avatar source null no title initials back

### ISSUE THREAD

**Issue by Cchumi** [react-native-training/react-native-elements#2034]
> version 1.1.0

**Explain what you did**
Hi I have a component which display my profile image from Firebase. If I have no image the initial was displayed.
I have some interaction to delete the remote image or change the image.
When I hit the delete button my avatar remove the image but it is empty. The initials title are not going back.

**Expected behaviour**
I search a way to force back the initials if the source is set to undefined or null.
I was thinking this is what it must happen.

My props are well passed to my child component and updated.

this is how I cal my child component :

`<ProfileImage profile={this.props.profile} backgroundColor={theme.SECONDARY_COLOR} deletefunction={this.deleteImage} modifyfunction={this.pickImage} imgSource={this.state.imgSource} flexDirection={'row'} size={'large'} showEditButton={this.state.editMode} />`

Here in my child component how I use ternary to set to undefined if no image are loaded.
I use an alternative state to store the image before saving to firebase on save button press.

`source={imgSource ? { uri: imgSource.uri } : profile.profileImg ? { uri: profile.profileImg } : undefined}`

If I reload my app the title initials are back as intended.

**Screenshots**
Before set an image 

![image](https://user-images.githubusercontent.com/40697701/63449287-19202980-c440-11e9-9eaf-d98371eb192d.png)

after set an image 

![image](https://user-images.githubusercontent.com/40697701/63449315-2b9a6300-c440-11e9-8d53-5a85b15d1a3c.png)

when image is deleted 

![image](https://user-images.githubusercontent.com/40697701/63449349-3bb24280-c440-11e9-8f3d-ccc2f9e4a7d1.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.1.0       |
| react-native          | 0.59.3        |

**Comment by Cchumi** [comment]
After some react native debugger research it appears that the opacity was not restored.
But stranger things is the the image component of your library in my node module directory was not the same.
I see that your image component is update since 19 days my project was build before that. How to get this modification in my node module.
I copy paste and now my problem is solved. But strange thing.
If i removed it from my local folder then install it with yarn add react-native-elements
And I go back to the image File I got the file before the edit since 19 days...

Please can you explain to me ?

**Comment by iRoachie** [comment]
The fix for this was made on the `next` branch so it isn't released on npm as yet. If you want to use this version at the moment you can do:


```bash
yarn add https://github.com/react-native-training/react-native-elements.git\#next
```

**Comment by Cchumi** [comment]
Hi thanks for your answer this is what I am thinking.
Do you know when this next branch will be release ?

Thank you

**Comment by iRoachie** [comment]
Will try to push out this week.

**Comment by Cchumi** [comment]
Great thanks again 

Cchumi
