### ISSUE TITLE
Need help in creating react native library

### ISSUE THREAD

**Issue by sureshsamanthapudi** [react-native-training/react-native-elements#2038]
Hi,

This issue is not related to 'react-native-tableview'.  
We are creating a new private component library for our organization. 
I tried the following:
1. Component library itself as a separate project with react and react-native as peer dependencies in my project.
2. But having just the components code in component library is not useful because we have to add new code or fixes and we have to run the story book(Because of peer dependencies could not be able run story book).

Could you please help me with the model I have to follow for creating a react native library?

Thank you in advance.

**Comment by iRoachie** [comment]
Answered you in another repo
