### ISSUE TITLE
When will there be a new version released?

### ISSUE THREAD

**Issue by Collin3** [react-native-training/react-native-elements#2040]
**Is your feature request related to a problem? Please Describe.**
There have been a number of bug fixes and improvements made since `v1.1.0`. I'm just wondering when a new release will be published so I can pull it into my app and fix some outstanding bugs from React Native Elements.

**Describe the solution you'd like**
An update on when the next version will be released. The last release was in February, so I'm wondering if the next release will be released in a matter of days, weeks, or months.

**Describe alternatives you've considered**
Forking the repo and managing any bug fixes and releases on my own.

**Additional context**
N/A

**Comment by bdombro** [comment]
In the mean time, you can install from a git commit like I do:

```
yarn add https://github.com/react-native-training/react-native-elements.git#01fc42625ece49649058aab4a254e09909a9cd28
```

**Comment by iRoachie** [comment]
Didn’t happen yesterday. Instead got stuck closing issues. Will  try for today

**Comment by DominicSherman** [comment]
Any update on this?

**Comment by iRoachie** [comment]
Testing the example app now. The release will happen in a few minutes

**Comment by iRoachie** [comment]
[v1.2.0](https://github.com/react-native-training/react-native-elements/releases/tag/v1.2.0) released.
