### ISSUE TITLE
Social Icons are not rendering well in Genny Motion emulator 

### ISSUE THREAD

**Issue by AliYar-Khan** [react-native-training/react-native-elements#2041]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
import { SocialIcon } from 'react-native-elements'
```
<SocialIcon
  title='Sign In With Facebook'
  button
  type='facebook'
/>
```

**Expected behaviour**
It should display a beautiful icon with symbol and text. Like show on the docs 
[https://react-native-training.github.io/react-native-elements/docs/social_icon.html](url)

**Describe the bug**
But the symbol is not rendering properly as shown below
![screenshot-2019-08-27_11 13 29 287](https://user-images.githubusercontent.com/37889962/63745470-b73a4680-c8bb-11e9-8407-f9991f0858aa.png)

**To Reproduce**
yarn add react-native-elements
# or with npm
npm i react-native-elements --save
```
class component extend React.Component 
{
  render(){
     return (
             <SocialIcon
                 title='Sign In With Facebook'
                 button
                type='facebook'
             />
       );
  }
}
```
**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    "^1.1.0"     |
| react-native          |   "0.60.3"     |
| npm or yarn           |    6.9.0     |

**Comment by AliYar-Khan** [comment]
> 
> 
> Are you in a standard react native project or expo?

standard project !

**Comment by iRoachie** [comment]
Please make sure that you correctly set up react-native-vector-icons. See https://github.com/oblador/react-native-vector-icons#android

**Comment by AliYar-Khan** [comment]
> 
> 
> Please make sure that you correctly set up react-native-vector-icons. See https://github.com/oblador/react-native-vector-icons#android

thanks it worked !
