### ISSUE TITLE
How To: Achieving Stack/Overlap Icons using RNE

### ISSUE THREAD

**Issue by naiduasn** [react-native-training/react-native-elements#2043]
Hi,
How to achieve stack of icons in RN using RNE?

What i want looks like below: 

https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons 

Any help would be appreciated.

**Comment by iRoachie** [comment]
There's no way to directly support this. The only way is to use multiple icons and use absolute positioning.

https://snack.expo.io/@roach_iam/vigorous-blueberries

**Comment by naiduasn** [comment]
@iRoachie Thanks. Exactly what i was looking for
