### ISSUE TITLE
I have problem with installing react-native-elements

### ISSUE THREAD

**Issue by MakkiAnjum** [react-native-training/react-native-elements#2044]
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
tried to install the react native elements

**Expected behaviour**
it is to be installed

**Describe the bug**
It is not getting installed
it is stuck after '  extract:react-native-elements: sill extract react-native-elements@latest extracte '
i have been waiting for an hour but it is still here.

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.1.0       |
| react-native          |     0.60    |
| npm or yarn           |      npm   |

**Comment by iRoachie** [comment]
This is probably an issue with your connection or npm setup. I suggest you try again. There's no errors on my end.
