### ISSUE TITLE
Invariant Violation: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by RoniFinTech** [react-native-training/react-native-elements#2045]
Hi,

I'm trying to render a list of deals where each deal is a react-native-elements Card and I'm getting an error.

This is my code

```
  render() {
    const { deals, loading, navigation } = this.props;

    return (
      <ScrollView style={{ marginTop: 10 }}>
        {loading && <Text>...loading</Text>}

        <Button
          title="Create Deal"
          style={{ paddingBottom: 15 }}
          onPress={() => navigation.navigate("CreateDeal")}
        />
        {deals.map(d => (
          <Card
            key={`${d.id}-fdc`}
            title={d.dealType}
            image={d.picUrl[0] ? { uri: d.picUrl[0] } : undefined}
          >
            <Text style={{ marginBottom: 10 }}>{d.owner.username}</Text>
          </Card>
        ))}
      </ScrollView>
    );
  }
```

> 
> Invariant Violation: Text strings must be rendered within a <Text> component.
> 
> This error is located at:
>     in RCTView (at View.js:45)
>     in View (at Card.js:47)
>     in RCTView (at View.js:45)
>     in View (at Card.js:39)
>     in Card (at withTheme.js:27)
>     in Themed.Card (at FindDealsConnector.tsx:22)
>     in RCTScrollContentView (at ScrollView.js:976)
>     in RCTScrollView (at ScrollView.js:1115)
>     in ScrollView (at FindDealsConnector.tsx:13)
>     in C (created by Query)
>     in Query (created by Apollo(C))
>     in Apollo(C) (at SceneView.js:9)
>     in SceneView (at StackViewLayout.tsx:899)
>     in RCTView (at View.js:45)
>     in View (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at StackViewCard.tsx:93)
>     in RCTView (at View.js:45)
>     in View (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at screens.native.js:59)
>     in Screen (at StackViewCard.tsx:80)
>     in Card (at createPointerEventsContainer.tsx:95)
>     in Container (at StackViewLayout.tsx:971)
>     in RCTView (at View.js:45)
>     in View (at screens.native.js:83)
>     in ScreenContainer (at StackViewLayout.tsx:383)
>     in RCTView (at View.js:45)
>     in View (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at StackViewLayout.tsx:379)
>     in PanGestureHandler (at StackViewLayout.tsx:372)
>     in StackViewLayout (at withOrientation.js:30)
>     in withOrientation (at StackView.tsx:103)
>     in RCTView (at View.js:45)
>     in View (at Transitioner.tsx:267)
>     in Transitioner (at StackView.tsx:40)
>     in StackView (at createNavigator.js:61)
>     in Navigator (at createKeyboardAwareNavigator.js:12)
>     in KeyboardAwareNavigator (at SceneView.js:9)
>     in SceneView (at createTabNavigator.js:39)
>     in RCTView (at View.js:45)
>     in View (at ResourceSavingScene.js:37)
>     in RCTView (at View.js:45)
>     in View (at ResourceSavingScene.js:26)
>     in ResourceSavingScene (at createBottomTabNavigator.js:121)
>     in RCTView (at View.js:45)
>     in View (at screens.native.js:83)
>     in ScreenContainer (at createBottomTabNavigator.js:111)
>     in RCTView (at View.js:45)
>     in View (at createBottomTabNavigator.js:110)
>     in TabNavigationView (at createTabNavigator.js:197)
>     in NavigationView (at createNavigator.js:61)
>     in Navigator (at SceneView.js:9)
>     in SceneView (at SwitchView.js:12)
>     in SwitchView (at createNavigator.js:61)
>     in Navigator (at createAppContainer.js:429)
>     in NavigationContainer (at src/index.tsx:39)
>     in ApolloProvider (at src/index.tsx:38)
>     in App (at withExpoRoot.js:20)
>     in RootErrorBoundary (at withExpoRoot.js:19)
>     in ExpoRootComponent (at renderApplication.js:35)
>     in RCTView (at View.js:45)
>     in View (at AppContainer.js:98)
>     in RCTView (at View.js:45)
>     in View (at AppContainer.js:115)
>     in AppContainer (at renderApplication.js:34)
> 
> createTextInstance
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:14369:18
> completeWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:21499:64
> completeUnitOfWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23616:44
> performUnitOfWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23779:36
> workLoop
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23789:47
> renderRoot
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:23855:21
> performWorkOnRoot
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24593:23
> performWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24520:30
> performSyncWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24496:20
> requestWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24394:26
> scheduleWork
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:24267:22
> dispatchAction
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:18660:23
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:155778:28
> notifySubscription
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161284:24
> onNotify
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161328:23
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161378:17
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:156986:27
> iterateObserversSafely
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:156985:34
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:156950:39
> invoke
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:157975:31
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:158061:19
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:158428:25
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:158426:35
> broadcastQueries
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:158424:29
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:158551:37
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161463:27
> notifySubscription
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161284:24
> onNotify
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161328:23
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161378:17
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:157522:42
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:157521:30
> notifySubscription
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161284:24
> onNotify
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161328:23
> next
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:161378:17
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:165338:24
> tryCallOne
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3768:16
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3869:27
> _callTimer
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28280:17
> _callImmediatesPass
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28316:19
> callImmediates
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:28535:33
> __callImmediates
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3170:35
> <unknown>
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2991:34
> __guard
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:3153:15
> flushedQueue
>     AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:2990:21
>

**Comment by iRoachie** [comment]
Do you have a sample of the data you were trying to render?

**Comment by RoniFinTech** [comment]
> Do you have a sample of the data you were trying to render?

Hi, yes... this is passed as a prop...

```
{
  "data": {
    "findDeals": [
      {
        "id": "b5ba03a7-6088-47be-b66b-1c7b1b9b04ff",
        "picUrl": [
          "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg"
        ],
        "dealType": "Discount",
        "owner": {
          "username": "user2",
          "email": "user2@gmail.com"
        }
      },
      {
        "id": "fb3dd9f0-57bc-409c-89aa-825bcd83a789",
        "picUrl": [
          "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg"
        ],
        "dealType": "Discount",
        "owner": {
          "username": "user1",
          "email": "user1@gmail.com"
        }
      }
  }
}
```

**Comment by RoniFinTech** [comment]
Looks like when i remove the Card prop 'title', it renders fine... hmm

**Comment by iRoachie** [comment]
Your example works fine. See https://snack.expo.io/@roach_iam/bold-tortillas

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Comment by c-goettert** [comment]
I think this issue still occures if you pass an empty string as title property for card component.
