### ISSUE TITLE
when support the version of react-native 0.6?

### ISSUE THREAD

**Issue by rendongsc** [react-native-training/react-native-elements#2053]
The react-native0.6 version has been released for several months.
when support the version of react-native 0.6?
thanks！

**Comment by iRoachie** [comment]
What do you mean? We already support react native 0.60. What problems are you having?

**Comment by rendongsc** [comment]
My react-native is the latest 0.60.5. I compiled a lot of errors after importing react-native-elements. I will be compatible with version 0.6 in the future. I just re-installed the react-native-elements and it works fine.
However, there is still a question, that is, the devDependencies of the package.json of the react-native-elements project.
```
"react-native": "0.59.10"
```

**Comment by iRoachie** [comment]
devDepdencies don't affect the version you can use. However we will upgrade eventually to 0.60.0 internally to see if they are any benefits we can gain.
