### ISSUE TITLE
Conditionally adding rightIcon to ListItem

### ISSUE THREAD

**Issue by antgel** [react-native-training/react-native-elements#2056]
I'd like to add a `rightIcon` to a `ListItem` if the `subtitle` has a certain value ('Notes'). I tried something like:
``` 
  renderItem = ({ item }) => {
    return (
      <ListItem
        title={item.title}
        subtitle={item.subtitle}
        topDivider
        bottomDivider
        {item.subtitle === 'Notes' &&
            rightIcon={{ name: 'edit', type: 'material' }}
        }
      />
    );
  };
```
but I get `Parsing error: Unexpected token, expected "..."`

Is my syntax wrong, or is this not possible?

I got it to work with a ternary that returns the whole `ListItem` with or without the `rightIcon`, but it's more code duplication than I'd like, I'd like just the `ListItem` to be conditional.

**Comment by iRoachie** [comment]
You can do this.

```jsx
<ListItem
  key={a.id}
  title={a.title}
  subtitle={a.subtitle}
  rightIcon={
    a.subtitle === 'Notes' ? { name: 'edit', type: 'material' } : null
  }
/>
```

https://snack.expo.io/@roach_iam/joyous-fudge

**Comment by antgel** [comment]
@iRoachie Works great, thanks. I can see why yours works, but where did I fall down, JSX syntax-wise?

**Comment by iRoachie** [comment]
So my example doesn't exactly do what you intended to although it has the same effect. 

What you intended to do was **optionally include the rightIcon prop**. At it's core jsx is just a function that takes in props as an object.

```jsx
// The two of these are the same
<ListItem {...{ title: 'Hello', rightIcon: { name: 'edit', type: 'material' }}} />

<ListItem title="Hello" rightIcon={{ name: 'edit', type: 'material' }} />
```

So if we want to optionally include the `rightIcon` prop. We can do this:

```jsx
<ListItem
  title="Hello"
  {...(subtitle === 'Notes' ? { rightIcon: { name: 'edit', type: 'material' } : {})}
/>
```

**Comment by antgel** [comment]
@iRoachie Thank you so much. I believe I need to learn more about the `...` operator. :)

**Comment by antgel** [comment]
(By the way, I decided that I prefer the `null` approach, it's more readable in that it keeps `rightIcon` aligned to the left with the other props...)
