### ISSUE TITLE
Unable to add border to avatar

### ISSUE THREAD

**Issue by jjg77** [react-native-training/react-native-elements#2059]
The border does not render correctly.  See code below.

```
<Avatar
      avatarStyle={props.avatarStyle}
      rounded
      size={props.size || 'medium'} 
      icon={{name: 'face', type: 'material', color: Colors.primary}}
      overlayContainerStyle={getStyle('overlay', theme)}
      onPress={props.onPress}
      activeOpacity={0.7}
      containerStyle={getStyle('container', theme)}/>
```

`<AvatarHeader size="xlarge" avatarStyle={{ borderWidth: 2, borderColor: 'white', borderTopLeftRadius: 1, borderStyle:'solid' }} />`
![ss1](https://user-images.githubusercontent.com/3186418/64552833-1c535a80-d306-11e9-8fb3-c9e79a192409.png)

**Comment by iRoachie** [comment]
This is a bug, `overlayContainerStyle` should override any changes made by the `rounded` prop. The order needs to change here https://github.com/react-native-training/react-native-elements/blob/next/src/avatar/Avatar.js#L137

**Comment by sudeepto-dutta** [comment]
@iRoachie So you mean moving the line `137` to  line `138` ? Will that work ?

**Comment by iRoachie** [comment]
Yes!

**Comment by ugrdursun** [comment]
Hello, I am experiencing same issue; changed line 137 with 138 as you told but it did not solve the issue.

Any recommendation ?

**Comment by pranshuchittora** [comment]
Use `container style` for the following purpose.
You can test the following functionality here -> https://react-native-elements-playground.netlify.app

**Comment by ugrdursun** [comment]
> Use `container style` for the following purpose.
> You can test the following functionality here -> https://react-native-elements-playground.netlify.app

Ahh ok, Turns out im using 1.2.7; I think this is fixed at next releases
