### ISSUE TITLE
Badge as separate component

### ISSUE THREAD

**Issue by sercanov** [react-native-training/react-native-elements#206]
Good to have I think.

**Comment by binoy14** [comment]
@sercanov Not a bad idea. It might actually already be the case just not exposed. I will take a look and update you. Thanks for reporting

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).

**Comment by binoy14** [comment]
This should be very easy for anyone to do. The badge component already exits. 

https://github.com/react-native-training/react-native-elements/blob/master/src/badge/badge.js

To implement this import the component in the below file and update documentation.

https://github.com/react-native-training/react-native-elements/blob/master/src/index.js

**Comment by tarang9211** [comment]
@binoy14 I'll take this up.

**Comment by Monte9** [comment]
@tarang9211 you might have to do some refactoring as part of this issue;
1. Refactor props to use ES6 spread
2. Flush this component out a little bit to make it more customizable.

**Comment by binoy14** [comment]
@tarang9211 @Monte9  #285 takes care of Number 1.

**Comment by tarang9211** [comment]
> Flush this component out a little bit to make it more customizable.

what exactly needs to be done for this?

**Comment by RWOverdijk** [comment]
I'd love this feature :) It's perfect to display tags I think.

**Comment by binoy14** [comment]
@tarang9211 add ability to style the container using containerStyle and the text using textStyle and that should do it.

**Comment by Monte9** [comment]
@binoy14 it already does that. I think having an `onPress` might be valuable as well. 

@tarang9211 let's aim to get this merged in for our the next release which is mid next week. Shouldn't take too long imo. 

@RWOverdijk you are making me hungry. 🌮

**Comment by binoy14** [comment]
@tarang9211 let's change the API to be similar to over elements. 

`if (!badge) throw Error('badge prop is required');`

Instead of passing an object with options we should pass props

**Comment by Monte9** [comment]
This is available with `v0.11.2`
