### ISSUE TITLE
Setting input in ListItem, how to set onPress?

### ISSUE THREAD

**Issue by zhengxing0705** [react-native-training/react-native-elements#2075]
<ListItem
            title="name"
            input={{
              inputStyle: {...Size.fontSize30, color: Color.dark1}
            }}
            containerStyle={styles.listItem}
          />

**Comment by iRoachie** [comment]
onPress on what? The input? TextInput doesn't have an onPress prop.

**Comment by zhengxing0705** [comment]
How to set up onChangeText in input? Thank you!

**Comment by iRoachie** [comment]
You can pass any of the input props as arguments:

```jsx
<ListItem
  title="name"
  input={{
    placeholder: 'Type Here',
    input: this.state.value,
    onChangeText: text => {
      this.setState({ input: text });
    },
  }}
/>
```

Example https://snack.expo.io/@roach_iam/sadistic-fudge

**Comment by zhengxing0705** [comment]
Thank you. I've settled it here.

> 
> ```js-jsx
> const { name } = this.state;
> <ListItem
>   title="name"
>   input={{
>     placeholder: 'Type Here',
>     value: name,
>     onChangeText: text => {
>       this.setState({ name: text });
>     },
>   }}
> />
> ```
