### ISSUE TITLE
Avatar error after 1.20 update

### ISSUE THREAD

**Issue by skiddolo** [react-native-training/react-native-elements#2076]
Hi, 
after last update, Avatar component make an error

> TyperError: (0, _react.useState) is not a function

in
> Image ( at withTheme.js:42 )

how's the problem? i'm using avatar component like this:
`<Avatar
                                rounded
                                size={90}
                                title={this.getAbbrevationName()}
                                source={{ uri: item.avatar }}
                                titleStyle={{ fontFamily: styleguide.secondFont.bold, 
                                    paddingTop: Platform.OS === 'ios' ? 15 : 0 
                                }}
                            />`

**Comment by iRoachie** [comment]
Be sure to reset your react-native/metro cache and re-install your node_modules. We bumped react version in the last update.

**Comment by skiddolo** [comment]
nothing after cleaning :(

**Comment by classyuan** [comment]
![image](https://user-images.githubusercontent.com/2560670/65273538-f3c42f80-db53-11e9-86fd-b9eba11f7a56.png)
I also encountered this problem. How can I solve it?

**Comment by iRoachie** [comment]
Can you create an example on https://snack.expo.io that reproduces this? Or a test repo?

**Comment by skiddolo** [comment]
Exactly the same problem. I'm using react native 0.60. There's some incompatible version with your new release about RN or vector-icons?

**Comment by classyuan** [comment]
> Can you create an example on https://snack.expo.io that reproduces this? Or a test repo?

My react-native version is  "react-native": "0.57.7"
Sorry, I can't use expo. Here's demo.

`import * as React from "react";

import { Avatar } from "react-native-elements";

export default class Profile extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <Avatar
        size="small"
        rounded
        title="MT"
        onPress={() => console.log("Works!")}
        activeOpacity={0.7}
      />
    );
  }
}
`

**Comment by iRoachie** [comment]
Can confirm. Will implement a fix asap

**Comment by iRoachie** [comment]
Fixed released in [1.2.1](https://github.com/react-native-training/react-native-elements/releases/tag/v1.2.1).

Very sorry about that! Will be much more careful next time.

**Comment by classyuan** [comment]
> Fixed released in [1.2.1](https://github.com/react-native-training/react-native-elements/releases/tag/v1.2.1).
> 
> Very sorry about that! Will be much more careful next time.

Thanks very much
