### ISSUE TITLE
Toolbar lost focus after typing one symbol when searching

### ISSUE THREAD

**Issue by ThomasPerche** [react-native-training/react-native-elements#2077]
**Explain what you did**
I have a Toolbar from react-native-element and I want to make a searchable with auto completion. This autocompletion was made with a ListView.
Before it worked great with ListView but since it has been deprecated in react native version 0.48, I'm trying to replace ListView by a FlatList. So my method searchForTerm(term) had been slightly modified but not that much.

**Expected behaviour**
Each type I type a symbol in the input of my Toolbar, the onChangeText method call this.searchForTerm(text) who made a request on a API.
This API send back an array of words.
This array populates the flat list.
The autocompletion is made.
If the user decide to add symbols for his term or delete symbols, the flat list should be refreshed with the new result of the api.

```
<Toolbar
                    searchable={{
                      autoFocus: true,
                      placeholder: '',
                      onChangeText: (text) => this.searchForTerm(text),
                      onSearchClosed: () => this.searchClosed()
                    }}
/>
```

**Describe the bug**
When I type in the toolbar searchable placeholder, it stops the toolbar and close it with only one symbol of input. When I put the onChangeText method in comment, it allows me to type more than one symbol so I guess this onChangeText method is the real trouble but I'm not able to fix it. 

My question is : Is the toolbar is compatible with a FlatList populated by a request of my API in a goal of an auto completion ?

**To Reproduce**

- My method searchForTerm(term)

```
    searchForTerm(term){
        let url = this.state.feedURL + term
        this.setState({query: term})
        this.setState({isRefreshing: true})
        console.warn(term);
        fetch(url).then((response) => response.json()).then((newsItems) => {
            this.setState({
                //loading:false,
                data:newsItems,
                loaded: true,
                isRefreshing: false,
                isAnimating: false
            })
        }).catch((error) => {
            console.error(error);
        });
    }
```

- The API 
https://api.urbandictionary.com/v0/autocomplete?term=

- The toolbar
(See up)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |         |
| react-native          |     0.55.4    |
| npm or yarn           |  6.9.0        |

**Comment by iRoachie** [comment]
I think you may have confused this with another library. React Native Elements doesn't have a Toolbar component.
