### ISSUE TITLE
Remove themed styles from component

### ISSUE THREAD

**Issue by JavanPoirier** [react-native-training/react-native-elements#2082]
From what I have read in the docs, currently, the only way to overwrite the theme object is by applying styles on the component. I am unsure of how this works under the hood, but would it be possible to pass a prop to the component such as "clearTheme" that defaults true and is only used in the true case. This would be shorter than overwriting every style of the component you would like to remove and just defaults to the default component style. Is there something I am missing or have not seen that provided this functionality? If not, thoughts?

**Comment by iRoachie** [comment]
How are you using ThemeProvider? Mostly when persons use it they're setting a consistent look and feel for components throughout the app. When would a clearTheme prop make sense?

**Comment by JavanPoirier** [comment]
Yes, I am using the ThemeProvider. How would it not make sense to have a clearTheme prop if you want a few components to not inherit the look? There are plenty of instances where an app might not want the theme default on a component. My example is most of my app inputs have a borderRadius, width, and background color. Instead of clearing each style individually for a input why not exclude it from using the ThemeProvider?

**Comment by iRoachie** [comment]
I understand what you are saying. However, I recommend in your situation to use composition, and create different inputs for your usage. See https://react-native-training.github.io/react-native-elements/docs/customization.html#using-composition

If you find that you havent to override the theme multiple places then maybe composition might be a better approach

**Comment by JavanPoirier** [comment]
Alrighty, composition I will do then. The reason I did not do this before is because, now I will have one component that does not use the main theme from the provider and this requires me to replace every other instance of the Input component to use the composition. If you have 99% of your components using the base theme and 1% not; composition will required you to replace all other instances which is a lot more work/code than exempting the 1% of components from using the theme. You do understand what I mean, right? Anyways, thanks for your response.

**Comment by iRoachie** [comment]
The component that you use with composition can still make use of the theme. Once it exists in the subtree, it'll inherit from the theme. I'm saying with composition you could make your overrides of the theme in one place and then use that.

**Comment by JavanPoirier** [comment]
Ok, yep, that did just occur to me. Even with that, a simple prop would be a simpler solution by a users standpoint, but there is enough on your folk's plate. Thanks again for your response.
