### ISSUE TITLE
Help request - How to set Overlay height to match height of children

### ISSUE THREAD

**Issue by tberghuis** [react-native-training/react-native-elements#2086]
I want the height to match the height of the contents shown in the overlay so there is no excess white space. I could set it to a fixed height but there should be an easy way.

snack: https://snack.expo.io/@tberghuis/overlay-example

**Comment by iRoachie** [comment]
Add ` height: 'auto'` to the overlayStyle

**Comment by tberghuis** [comment]
Works, thank you @iRoachie
