### ISSUE TITLE
ADD Toasts

### ISSUE THREAD

**Issue by SheppardX** [react-native-training/react-native-elements#236]
I use your Elements and now i slide in some user interactions and wanted to use toasts for successful actions... but there are no toasts :(

**Comment by binoy14** [comment]
@SheppardX thanks for reporting. We are currently swamped with feature requests and this won't be on the immediate roadmap. That being said check out @dabit3 's article on [Creating A Custom Toast Module for React Native](https://medium.com/@dabit3/creating-a-custom-toast-module-for-react-native-770fd1c0dcf5) and feel free to send a PR.

**Comment by Monte9** [comment]
We are looking to implement "custom toasts" soon. Since this issue closely resembles it, I am closing this. Follow along [here]( #190 )
