### ISSUE TITLE
FormInput width (Android only)

### ISSUE THREAD

**Issue by szakhlypa** [react-native-training/react-native-elements#239]
By default TextInput receives width equals to window width, but it's HOC View has marginHorizontal equals to 15. That creates issue on android:
![screenshot](https://cloud.githubusercontent.com/assets/26611935/24225107/fe30c7ee-0f5e-11e7-8a74-cf61755b8ad0.png)
Also HOC View margins can be redefined using containerStyle prop.
Seems that this issue connected with #70. Maybe @binoy14 should take a look at it.
Thanks for great package

**Comment by binoy14** [comment]
@szakhlypa hmm makes sense. If you think you have solved the issue feel free to send a PR and I can review it.

**Comment by binoy14** [comment]
@szakhlypa This should be fixed in latest release. Let me know if its still an issue

**Comment by Monte9** [comment]
@binoy14 can you point me to the PR that fixes this issue? Thanks.

**Comment by binoy14** [comment]
@Monte9 looks like it was closed not merged. My bad, I will send a PR soon

**Comment by mwarger** [comment]
I was able to work around this by explicitly setting `marginRight: 0` on the component style.  Any update on the PR?

**Comment by binoy14** [comment]
I will fix this in the next release. I had fixed it but some reason i didn't create a PR and it got lost. I will fix it again

**Comment by Monte9** [comment]
This has been fixed and will be released in `v0.12.3`

**Comment by DenisDov** [comment]
`width: '100%'`
