### ISSUE TITLE
Why is Avatar Component using a different Icon component?

### ISSUE THREAD

**Issue by joncursi** [react-native-training/react-native-elements#245]
https://github.com/react-native-community/react-native-elements/blob/master/src/avatar/Avatar.js#L9

This library has it's own `<Icon />` component which brings support for half a dozen icon libraries. Why is `<Avatar />` not using it, and instead using a font-awesome specific icon component from an external lib?

The API docs are written with *this* library's `<Icon />` component in mind:

<img width="812" alt="screen shot 2017-03-23 at 1 57 32 pm" src="https://cloud.githubusercontent.com/assets/4974609/24262549/c43f7202-0fd0-11e7-88c8-c2e448417b7c.png">

So right now, the implementation does not match the API docs.

See also: https://github.com/react-native-community/react-native-elements/issues/244

**Comment by Monte9** [comment]
@joncursi Good catch. I was the one that worked on the Avatar component and this is clearly a mistake. 

Will push a fix for it later this evening. Keep an eye out for it.

**Comment by Monte9** [comment]
PR #244 has been merged. This fix should be out in our next release `v0.11.0`
