### ISSUE TITLE
FormInput with keyboardType="numeric" can't lose focus

### ISSUE THREAD

**Issue by Quas94** [react-native-training/react-native-elements#246]
Typically a numeric input loses focus when anything else on the screen is touched, however when using a react-native-elements FormInput, it's not possible to make it lose focus. The only way appears to be to have another non-numeric input on the screen and switch focus to that, then "return" can be pressed to get rid of the keyboard.

Tested only on iPhone via CRNA

**Comment by binoy14** [comment]
@Quas94 Is this the case with using TextInput from react native also?
