### ISSUE TITLE
SearchBar clearIcon and showLoadingIcon are overlapped.

### ISSUE THREAD

**Issue by abdurrahmanekr** [react-native-training/react-native-elements#263]
![](http://g.recordit.co/NDfocbIy3x.gif)
If both are present, the loading icon can be given the padding-right
How can it be a solution?

**Comment by binoy14** [comment]
@abdurrahmanekr Would having the ability of changing the style of the loadingIcon and clearIcon help? 

cc @Monte9

**Comment by Monte9** [comment]
> If both are present, the loading icon can be given the padding-right

This seems like a decent solution to me. Feel free to submit a PR if @abdurrahmanekr or anyone else wants to submit a fix for this.

**Comment by Monte9** [comment]
PR #405 fixes this issue. Thanks @abdurrahmanekr! ;) 

This will be release in `v0.13.0`
