### ISSUE TITLE
Combine element with flux for navigation

### ISSUE THREAD

**Issue by yovierayz** [react-native-training/react-native-elements#264]
I'm new in React.
Can i added event onPress, l.nav = "Actions.pricing" to navigate using flux? i'm failed when try it.

//AppRootContainer
`<List containerStyle={{ marginBottom: 20 }}>
            {
              list.map((l, i) => (
                <ListItem
                  hideChevron={true}
                  onPress={() => {l.nav}}
                  key={i}
                  title={l.name}
                />
              ))
            }
          </List>`

//Main App
`<Router>
        <Scene key="root">
          <Scene key="main" component={Drawer} initial={true} hideNavBar={true} />
          <Scene key="pricing" component={Pricing} hideNavBar={false} />
        </Scene>
      </Router>`

Normaly, i'm build simple apps and just called `<Text onPress={Actions.pageTwo}>This is PageOne!</Text>` can navigate to pageTwo.

When first run, success to load Drawer = (AppRootContainer) and running smoothly like Hackanton apps.
But when i clicked sidemenu, apps not navigate to pricing page.

Thanks for help :)

**Comment by binoy14** [comment]
@yovierayz Is `l.nav = "Actions.pricing"` set as a string? that would not work because you are just calling a string. I would suggest creating a new function and call the Action.pricing in that function.

**Comment by binoy14** [comment]
@yovierayz Closing this issue since it doesn't sound like it as a bug with the library. If you are still having an issue feel free to open it back.
