### ISSUE TITLE
Side menu seems slow on devices

### ISSUE THREAD

**Issue by danielbenedykt** [react-native-training/react-native-elements#271]
I implemented Side Menu from here and also looked at the hackaton project.
After implementing side menu, I see a big delay between the touch and the actual animation.

I am new to React Native, so is this always the case for React Native, its a problem on something I did or it's a problem on the react-native-elements ?
My UI was very simple, other than having the side menu, I just included a TEXT

**Comment by binoy14** [comment]
@danielbenedykt check out https://github.com/react-native-training/react-native-hackathon-starter and see if your having the same issue there as well.

**Comment by binoy14** [comment]
@danielbenedykt Closing this issue since we use https://github.com/react-native-community/react-native-side-menu and it would be best suited to report it there. If you are still having an issue with this library, feel free to open this again
