### ISSUE TITLE
List, ListItem: Double borders and borders too thick

### ISSUE THREAD

**Issue by cmaas** [react-native-training/react-native-elements#277]
Two issues with lists (tested on iOS only, iPhone 7):

1. Border width is specified as 1. This is too big. Actual lines in iOS are **1px @2x**, but since React Native calculates at @1x, it has to be set to 0.5 The screenshot below shows my change and how it'd be correct. It might require a bit of a color tweak, because with a 1px line, the subtle grey can hardly be seen.

2. The last ListItem also has a bottom border, which gives the whole thing a double border on the bottom, but not on top. Looks slightly unclean. In the screenshot, this effect is even a bit less, because the screenshot shows my changed 0.5 border width from LineItem. Out of the box, the double lines are spotted easily and it looks blurry and unclean.

![list-borders](https://cloud.githubusercontent.com/assets/6094364/24623755/d71dc7c0-18a9-11e7-92cc-31b79971a191.png)

Fix: Set borderWidths to 0.5 and don't add a borderBottom on last child of ListItem

**Comment by Monte9** [comment]
@cmaas this is great feedback! Seems like a quick fix and it will result in more visual polish. I like it. 

I'll work on it and tag you on the PR. Stay tuned.

**Comment by cmaas** [comment]
@Monte9 Check this out, there's a helper that specifies the minimum width per platform called `hairlineWidth`: https://facebook.github.io/react-native/docs/stylesheet.html#hairlinewidth
Example:
```
{
    borderBottomColor: '#bbb',
    borderBottomWidth: StyleSheet.hairlineWidth
}
```

**Comment by JLLLinn** [comment]
Please add this, I'm eager to use the listitem and this is the only thing that holding me back

**Comment by Monte9** [comment]
@JLLLinn Sorry to hear that. I'll fix this asap.

**Comment by Monte9** [comment]
[This commit](https://github.com/react-native-training/react-native-elements/pull/404/commits/600e1c98d215b73202c6a78461b4628ce6b37378) fixes this. 

This should be released in `v0.12.3`

**Comment by hariprasadiit** [comment]
I'm seeing this issue with `v1.0.0-beta2`. tested it on iphone 5 emulator.

**Comment by Monte9** [comment]
Yes, the ListItem is yet to be updated for out v1.0 release. We have a working ListItem, we just need to merge the PR and release it soon. Please keep an eye on the upcoming releases.

**Comment by weitieda** [comment]
<img width="1134" alt="xnip2018-09-30_23-59-23" src="https://user-images.githubusercontent.com/35972055/46269113-e5c56b00-c50c-11e8-9e3b-6c50d9e73991.png">
Hi, is there any way I could change the first top line's thickness? Thanks

**Comment by iRoachie** [comment]
Hey @weitieda please create a new issue, and fill out the issue template
