### ISSUE TITLE
React Native's KeyboardAvoidingView not responding for FormInput 

### ISSUE THREAD

**Issue by KeabetsweFx** [react-native-training/react-native-elements#278]
I'm using multiple  FormInput  on the same page and when an input gains focus and the keyboard is triggered to slide up it covers my inputs. I've tried to handle this by using react native's KeyboardAvoidingView as my form container but the keyboard still covers my Inputs. What could be the reason for this, does it have anything to do with the  FormInput's  default styling or my container?

Below is my container's styling.

`.container: {
  flex: 1,
  padding: 20
}`

**Comment by binoy14** [comment]
Could you provide with a sample in https://snack.expo.io so it will be easier for us to see the problem

**Comment by martinezguillaume** [comment]
Same here... I tried to wrap all of my view inside a ScrollView, same...

**Comment by Monte9** [comment]
@KeabetsweFx please see @martinezguillaume's answer above.

**Comment by datsik34** [comment]
@martinezguillaume wait where in your code do you add these lines ?

**Comment by martinezguillaume** [comment]
@datsik34 It's more like that in JSX
```jsx
<KeyboardAvoidingView
  behavior="position"
  keyboardVerticalOffset={65}
>
...
</KeyboardAvoidingView>
```
