### ISSUE TITLE
Overriding Button with custom component

### ISSUE THREAD

**Issue by wjgilmore** [react-native-training/react-native-elements#279]
Hi,

I'm at wits' end here and so thought I'd ask for some expert advice. I'm using the excellent React Native Elements package along with [React Navigation](https://github.com/react-community/react-navigation). Everything is going great except I can't figure out how to override the Button component for use in the react-navigation StackNavigator nav bar. I've confirmed the problem isn't due to react-navigation, because I can manually override the button no problem; it's only when I use my custom component that the styles aren't applied.

The following code doesn't produce exactly the same result as that found in the attached screenshot because Expo doesn't support the react-native-vector-icons package so it won't render in the simulator. Even so hopefully it will be suffice:

https://snack.expo.io/Hy7ABNbpg

Thanks a million!
Jason

<img width="318" alt="for-github" src="https://cloud.githubusercontent.com/assets/161522/24663800/f64e1fe6-1926-11e7-8028-365d55fe6096.png">

**Comment by binoy14** [comment]
@wjgilmore Are you looking for replacing the Button component with something such as TouchableHighlight, TouchableOpacity, etc? take a look at the component prop on the button https://github.com/react-native-training/react-native-elements#button-props

**Comment by wjgilmore** [comment]
Oh aha @binoy14 thank you for pointing this out. I was under the impression this could *only* be set to TouchableHighlight or TouchableNativeFeedback based on the device (to be clear I understand this is automatically set, but didn't realize it could be set to other component types). Thank you so much!
