### ISSUE TITLE
How to refer to key of List, ListItem

### ISSUE THREAD

**Issue by manhhp** [react-native-training/react-native-elements#280]
Could you show me how to refer to key of ListItem? I dont know how to refer to key, pls give me example also. Thank you!

**Comment by binoy14** [comment]
@manhhp could you please elaborate on you do you mean by key of ListItem?

**Comment by manhhp** [comment]
@binoy14, i use list element to populate my users list. I want when click on listitem app will navigate to user details scene;

I try to pass my user ID on key props of ListItem and call it back on onPress event. But i dont know how to refer to it.

Or Are there anyway else ? Please help me

This is my code:

```
<List containerStyle={{marginBottom: 20}}>
        {
          list.map((l, i) => (
            <ListItem
              roundAvatar
              onPress={() => console.log(this.ListItem.key)}
              avatar={l.avatar}
              key={l._key}
              title={l.name}
              subtitle={l._key}
            />
          ))
         }
        </List>
```

**Comment by bozzmob** [comment]
Hi @manhhp, The list component supports `key` attribute by default. Please refer to the documentation for more details. Here is a quick example-

Using List with `map`
```
<List>
  {
    list.map((item, i) => (
      <ListItem
        key={i}
        title={item.title}
        leftIcon={{name: item.icon}}
      />
    ))
  }
</List>
```
or
Using `ListItem` for each row.
```
renderRow (rowData, sectionID) {
  return (
    <ListItem
      roundAvatar
      key={sectionID}
      title={rowData.name}
      subtitle={rowData.subtitle}
      avatar={{uri:rowData.avatar_url}}
    />
  )
}
```

Will be closing the issue, write back to us in case you need more information.
