### ISSUE TITLE
ListItem: Support number of lines for subtitle and title

### ISSUE THREAD

**Issue by carlobambo** [react-native-training/react-native-elements#292]
Right now this can be done by passing a Text element as title and subtitle, but doing so does not inherit the ListItem's title and subtitle style.

**Comment by binoy14** [comment]
@carlobambo Thanks for the suggestion

**Comment by carlobambo** [comment]
or maybe it would be more configurable if we support subtitleTextProps or titleTextProps?

**Comment by Monte9** [comment]
@carlobambo good idea. Would you like to submit a PR? Would gladly review & merge it.

**Comment by Monte9** [comment]
This has been fixed in the latest release. Please see [here](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L166)
