### ISSUE TITLE
Usage with create-react-native-app

### ISSUE THREAD

**Issue by telmen** [react-native-training/react-native-elements#296]
When I tried to use SocialIcon, I've faced the error which is FontAwesome is not system default font, it's not loaded with Font.loadAsync. I believe CRNA comes with @expo/vector-icons. Please tell me how to use this library with CRNA?

**Comment by telmen** [comment]
Okay, got it working by loading all font files in app root using Font.loadAsync({
          'FontAwesome': require('../node_modules/@expo/vector-icons/fonts/FontAwesome.ttf'),
})

**Comment by binoy14** [comment]
@telmen I tried it on latest release and I did not have to do that

**Comment by telmen** [comment]
Could you show me a version of CRNA, Expo?

**Comment by binoy14** [comment]
@telmen 

"exposdk": 15.0.0
"react-native-scripts": "0.0.27"
"create-react-native-app": 0.0.6
