### ISSUE TITLE
Allow passing a component to rightIcon/leftIcon in ListItem

### ISSUE THREAD

**Issue by karanjthakkar** [react-native-training/react-native-elements#301]
### Description

1. Explain what you did
- I'm using the ListItem component but want to able to use custom icons for my `leftIcon`/`rightIcon` chevrons

2. What you expected to happen
- I thought it would allow passing a React component

3. What actually happens
- ListItem only allows an object with type and/or name properties to define which icon to use amongst the one provided by react-native-vector-icons

### Also please include the version of `react-native-elements` that you are using.
All versions

### Solution
Modify the implementation of rightIcon and leftIcon to allow an object or a react component. Update the prop types to expect an object or a component. This shouldn't be breaking change as it would still default to expecting an object. If this is something that you would like to consider, I can send a PR for it.

**Comment by Monte9** [comment]
This sounds like a good idea. It's one thing I want use to do more in our codebase, which is to allow passing in components for props where it makes sense to do so. 

This should be fairly straightforward. It would be great if you could submit a PR for this. @binoy14 and I can help review it and get it merged in.

**Comment by binoy14** [comment]
This has been fixed and will be released in `0.12.0`
