### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by tristanpemble** [react-native-training/react-native-elements#302]
Do you plan to support TypeScript definitions with this project?

I'm currently working on building out my own definitions. If you'd like, when I am done, I can submit a pull request to include them as official definitions. This would mean, however, that they should be maintained with the project as it develops. Alternately, I can just submit them to DefinitelyTyped as third-party definitions.

**Comment by binoy14** [comment]
@tristanpemble we don't have an immediate plan to support it. If you would, please send a PR and we can merge it in. Thanks

**Comment by kenkistudio** [comment]
@tristanpemble i would also like to use the Typescript definition for my project. do you have one that you can share yet? Thanks.

**Comment by dabit3** [comment]
@tristanpemble This would be awesome!

**Comment by dabit3** [comment]
@tristanpemble I think having them as part of the definitely typed third party definition would actually make a lot of sense...

**Comment by tristanpemble** [comment]
Hi guys, I've been sidetracked on other projects, but when I get back on our mobile project I will continue working on them.

I agree leaving them third-party would be best if the maintainers of the project aren't planning to use TypeScript at all; it adds a burden to the project maintenance if you are trying to support definition files you don't use.

**Comment by andrewlinfoot** [comment]
@tristanpemble I am currently starting my first TypeScript project. I've got the bandwidth to work on this right now but since I'm new to TypeScript, I'm not exactly sure how to get started. Can you post a gist with what you have so far? I'll see if I can finish it off and submit a PR to DefinitelyTyped within the next week or so

**Comment by Monte9** [comment]
That's a good point @tristanpemble. I personally don't use TypeScript, but I would love to see what the typings would look like and try them out.

As @andrewlinfoot suggested, can you share with us how you think we can proceed with this project and I am sure we can get others to contribute as well.

**Comment by iRoachie** [comment]
@tristanpemble I can help on this. Submit to dt instead though

**Comment by zunder** [comment]
Is someone of you guys actively working on this one?

**Comment by iRoachie** [comment]
@zunder will start this weekend

**Comment by iRoachie** [comment]
Okay it's started, I added the Button component. Will add more as time goes on. Once the initial commit is merged, others can contribute

**Comment by iRoachie** [comment]
@Monte9 @binoy14 @dabit3 Can close this issue. I'll actively work on the typings

**Comment by iRoachie** [comment]
The status of the typings can be seen here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-elements/README.md

**Comment by Monte9** [comment]
Great work @iRoachie! Thanks for taking the lead on this. 

For someone that's interested in using the typed definitions, how would they do so? Also it would be helpful if you added a couple code snippets in your answer as well. 

Closing this issue as per @iRoachie's request. But feel free to use this issue to discussion anything related to typescript for RNE.

**Comment by iRoachie** [comment]
Sure thing @Monte9.

After installing`react-native-elements` you have 1 extra step to use it with typescript.

`npm i -D @types/react-native-elements` or `yarn add --dev @types/react-native-elements`

After that you're good to go and can use it as normal.

**Comment by ifiokjr** [comment]
Can we add the types directly into this project?

I can submit a PR for it.

**Comment by iRoachie** [comment]
Lol I guess we could. Me being maintainer and all

**Comment by awinograd** [comment]
@iRoachie @ifiokjr adding the types to this project has led to a divergence between the types in DefinitelyTyped and here locally. If this repo is planning on including types from here on out, do you know if it's possible to remove the package from DefinitelyTyped? That might help steer other users to contributing updates here

PS thanks for all of your help in creating these definitions. They've been super helpful!

**Comment by iRoachie** [comment]
You are correct! I have to submit the PR to DefinitelyTyped. I'll see if I can knock it out today

**Comment by awinograd** [comment]
Thanks @iRoachie! FWIW, there are a couple of updates to the DefinitelyTyped repo. Would be great to merge those in here too. I'm happy to submit a PR if you'd like

**Comment by iRoachie** [comment]
Sure @awinograd would appreciate if you make that PR
