### ISSUE TITLE
Support for react-navigation

### ISSUE THREAD

**Issue by nonameolsson** [react-native-training/react-native-elements#308]
Hi!

Does react-native-elements have support for react-navigation? A good example is [react-native-material-bottom-navigation](https://github.com/timomeh/react-native-material-bottom-navigation#usage-for-react-navigation) which has a nice API to use it with react-navigation.

I'm thinking of the [tabbar](https://react-native-training.github.io/react-native-elements/API/tabbar/) element.

**Comment by Monte9** [comment]
@nonameolsson this is a golden idea 🏅 imo. Thanks for bringing this up. 
Here are my thoughts:
1. RNE is more a component library. Hence we do not provide native navigation support for this library. Although we wanted to allow users to use some sort of basic tab navigator and hence are using `react-native-tab-navigator` as the `tabbar` element that you linked to. Seems like this repo now suggests users to migrate to `react-navigator`.
2. I really like ` react-native-material-bottom-navigation` although haven't used it before. I also like that it uses ` react-navigator`. Although I wonder what this component would look like on our repo. 
I think if we can abstract away `Usage for react-navigation` section on that repo and expose a standard set of props it would be pretty valuable on this repo. 

Would love to hear your thoughts on how you think we can use ` react-native-material-bottom-navigation` on this repo. I am open to moving away from the current `tabbar` that we have.

**Comment by nonameolsson** [comment]
Thanks!

1. Of course, and I think it should continue being a library with focus on components! :) I'm just not sure about how you "decide" how the layout of the component should be. It's a very good library which implements both some principles/ideas from material design. But at the same time it uses design elements from iOS.
The `tabbar` component uses `react-native-tab-navigator`. Just like you says, Expo recommends their users to switch over to `react-navigator`: 

> Note: We recommend you use React Navigation instead, which integrates tab navigators with other kinds of navigators.
 [source](https://github.com/expo/react-native-tab-navigator)

Could it be a solution to create a "new" `tabbar` component which has a good API to integrate with `react-navigation`?

2. I have used `react-native-material-bottom-navigation` in a project along with `react-navigation`. It works seamless. `react-native-material-bottom-navigation` is a stand-alone component. But it has an API for `react-navigation`. You can find more info in this issue [https://github.com/react-community/react-navigation/issues/509](https://github.com/react-community/react-navigation/issues/509).
As he says: `This package includes a Component to plug into react-navigation. It is as configurable as the standalone version.`. 

I think there are two questions here.
1. Should `react-native-elements` implement an API with `react-navigation`?
2. Should the `tabbar` component be replaced with something like `react-native-material-bottom-navigation`?

What do you think?

**Comment by Monte9** [comment]
> Should react-native-elements implement an API with react-navigation?

I don't think so. React Navigation has such a detailed API that it would almost be too trivial to write an abstract over it for RNE. Also since React Navigation is extensively used by so many people at this point, I think just pointing people towards it for a navigation solution as part of RNE is good enough. 

> Should the tabbar component be replaced with something like react-native-material-bottom-navigation?

Initially I wanted to deprecate & get rid of the `tabbar` & `SideMenu` components as React Navigation provides a good solution for both, but upon looking at `react-native-material-bottom-navigation` a bit more, I really like this idea. 

I wonder what @binoy14 thinks about this.

**Comment by Monte9** [comment]
As of [v0.15.0](https://github.com/react-native-training/react-native-elements/releases/tag/v0.15.0) we have deprecated support for SideMenu & TabBar component. 

This is from our release notes:
> SideMenu, Tabs, and Tab are navigational components but they weren't full navigation solutions. React Navigation is a full navigation library that has support for Drawers (SideMenu), Tabs, Modals and even Stacks. 

Hence going forward, we recommend using [react-navigation](https://reactnavigation.org/) for all the navigation in your react-native apps. Also if you are looking for examples on how to implement react-navigation please checkout our [/example](https://github.com/react-native-training/react-native-elements/tree/master/example) expo app for RNE that has a pretty complex navigation implementation in it.

**Comment by mbrucher** [comment]
Does this mean that contrary to `react-native-paper`, there is no integration with `react-native-elements` for common theme and a nice consistent bottom bar?

**Comment by iRoachie** [comment]
@mbrucher This was an old issue, we no longer have a bottom tab bar component any more.
