### ISSUE TITLE
Search in docs

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#309]
Hey!

I really like react-native-elements, and the new docs. I liked the readme style more personally, but I get the new page.

What (personally) really sucks though, is the hijacking of search. I want to search on-page, and now I can't. It's _really_ annoying.

**Comment by Monte9** [comment]
@RWOverdijk The new website has it's pros and cons. And I agree that searching for specific `props` or any keywords is not as convenient as before. I'd be open to ideas to improve this if possible. 

Did you have any potential solutions in mind to improve search?

**Comment by RWOverdijk** [comment]
@Monte9 Sorry, yes, I do. I should've mentioned it right away, I was juggling too many things at once.

I'd say, remove the capture of cmd+f (or just, page search). If the user wants to search, they can click the search bar. You can add a different shortkey that's not a browser default, like `cmd+/` (that's what gitter uses for formatting toggle).

**Comment by bozzmob** [comment]
Hi @RWOverdijk ,

Current Behavior : CMD+F or CTRL+F goes to the Website search.

2 options to consider-
1. The searchbar is really good, you can search for what you need in the webpage, it would still list the exact heading under which you'll find it.
2. In case you don't like the searchbar, please redo the action of CMD+F again, this would fire the browser's search toolbar. So, basically, just do CMD+F twice.

Let me know if you need anything more.

**Comment by Monte9** [comment]
@bozzmob I actually think is a good idea. 
> I'd say, remove the capture of cmd+f (or just, page search). If the user wants to search, they can click the search bar. You can add a different shortkey that's not a browser default, like cmd+/ (that's what gitter uses for formatting toggle).

Is there a way we can override the cmd+f mapping for mk-docs?

**Comment by bozzmob** [comment]
@Monte9 I did a quick check on the [js file](https://github.com/react-native-training/react-native-elements/blob/gh-pages/mkdocs/js/search.js). I couldn't find any event listener for CMD+F. Searched on google, wasn't helpful, neither was their issues tab. Will check more on this.

**Comment by Monte9** [comment]
@squidfunk is the author of mk-docs. Maybe he can pitch in on this? 
He helped us out earlier with this PR #281

**Comment by RWOverdijk** [comment]
Second cmd+f _did_ do the trick. I'd still turn around the logic, but knowing this makes it less annoying* for me to browse.

\* Obviously my opinion.

**Comment by squidfunk** [comment]
Hey there, sorry for replying so late. This is indeed a bug. Material is just capturing the "S" and "F" keys, but doesn't check if a meta key was pressed. I will fix it asap so the browser search is not hijacked.

Linked issue is https://github.com/squidfunk/mkdocs-material/issues/282

**Comment by squidfunk** [comment]
When you update to 1.5.5, <kbd>CMD</kbd>+<kbd>F</kbd> should bring up the browser search.

**Comment by binoy14** [comment]
@squidfunk thanks for looking into this!

**Comment by RWOverdijk** [comment]
Closing this as I assume docs get updated regularly. If I'm wrong and this is needed as a reminder it can be reopened :)

**Comment by squidfunk** [comment]
As long as you haven't pinned Material to 1.5.4, things should work on the next deployment, yes.

**Comment by Monte9** [comment]
@RWOverdijk this issue has been resolved in latest release. 

Thanks for your help @squidfunk 💯
