### ISSUE TITLE
Can't Compile Card Component Styles On Android Device

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [react-native-training/react-native-elements#311]
So I've been kind of pulling my hair out on this. I'm using Expo IDE to build and simulate my react-native app. I'm using react-native elements, specifically just Button and Card. The app, builds fine when I run it on in the Expo Client for iOS, but as soon as I try to run it on the Expo Client for Android, I get red screen errors all over the place. 

**The first error:**

"Invalid undefined 'fontFamily' of type 'object' supplied to 'StyleSheet.featuredTitle', expected 'string'.

I figured out this pertains to the stylesheets in Card (react-native-elements/containers/Card.js), for android its assigning 'fonts.android.black' to fontFamily in the android object, but 'fonts.android.black' returns: 

{ fontFamily: 'sans-serif' } // an object

This was an easy fix, just need to change the line in Card.js to 'fonts.android.black.fontFamily' so it returns just the string.

**The Second Error - And the one I can't solve**

"In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant."

This really didn't tell me jacksh*t in terms of where the error is coming from, but I found [this problem](http://stackoverflow.com/questions/37020404/error-when-creating-new-object-from-existing-one-using-in-this-environmen) on StackOverflow, which is saying that Stylesheet.create() needs to return a plain javascript object, and that Stylesheet.flatten() can be applied to the stylesheet arrays to do so...but it doesn't seem to work. 

So I'm stumped, any ideas on how to fix the card component for Android builds?

**Comment by nativedone** [comment]
Yeah, I had the same problem with `"Invalid undefined 'fontFamily' of type 'object' supplied to 'StyleSheet.featuredTitle', expected 'string'.`

I was already submitting a PR with the same solution that you mentioned. But, I saw that #307 will fix it :smile:

**Comment by binoy14** [comment]
@JohnAntonusMaximus we will release new version today which will fix the issue you are having. 

Regarding your second issue it's likely because your are trying to do an object.assign or spreading an object but what your are trying to assign is not an object so it errors out. Try to see if you are still having an issue with our latest release `v0.11.1`

**Comment by Monte9** [comment]
@JohnAntonusMaximus @nativedone just published `v0.11.1`. That should fix it. 

Let us know if you are still having trouble getting the `Card` to work.

**Comment by nativedone** [comment]
@Monte9 works like a charm! :1st_place_medal: 

thanks for such a quick response!

**Comment by Monte9** [comment]
Perfect! Happy to help! 😄

**Comment by JohnAntonusMaximus** [comment]
I fixed the issue by just hard-coding the android fonts into Card.js, but yes, latest version seems to work right out of the box. Great job guys, and awesome response time.
