### ISSUE TITLE
Icon width and height required

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#312]
Using <Icon /> from RN elements within a RN Text component (or RN elements Text component, same result) results in the following:

```jsx
<Text><Icon name='location-on' />{details.distance}km</Text>
```

> Views nested within a <Text> must have a width and height icon

**Comment by binoy14** [comment]
@RWOverdijk take a look here http://facebook.github.io/react-native/releases/0.43/docs/text.html#nested-views-ios-only since Icon uses a View as the outer component you need to define width and height, nothing we can do. However it is not a good idea to next an Icon inside text component because it won't work on Android. In your case you can change your code to the following

```
<Icon name='location-on' /><Text>{details.distance}km</Text>
```

**Comment by RWOverdijk** [comment]
@binoy14 It works with the [react-native-vector-icons component](https://github.com/oblador/react-native-vector-icons#icon-component).

**Comment by binoy14** [comment]
@RWOverdijk good point, they use text component. Maybe we can change our implementation to use Text instead of view

**Comment by RWOverdijk** [comment]
@binoy14 Or use their component (proxy)? I thought that already happened because it uses that component (I think).

**Comment by binoy14** [comment]
@RWOverdijk actually after looking as the code the reason there is a wrapper around is because we can provide different events such as onPress. To fix your problem you can actually pass a text component.

```
<Text><Icon name='location-on' component={Text} />{details.distance}km</Text>
```

**Comment by RWOverdijk** [comment]
@binoy14 I didn't need this specific implementation. I just thought I'd report the behavior :) It doesn't have to change for me personally.

**Comment by binoy14** [comment]
@RWOverdijk I see what you are saying. Thanks for reporting, really appreciate it.
