### ISSUE TITLE
[DOCS]: Links on the home page are broken

### ISSUE THREAD

**Issue by mguida22** [react-native-training/react-native-elements#314]
The new docs website looks great! On the [homepage](https://react-native-training.github.io/react-native-elements/) however, the links are all broken, pointing to the old README or markdown pages in the repo as opposed to the new site.

For example under component, `buttons` links to https://github.com/react-native-community/react-native-elements#buttons, as opposed to https://react-native-training.github.io/react-native-elements/API/buttons/

I'd be happy to submit a PR to fix it, but I'm not really sure where to start with editing the `gh-pages` branch. Is it generated?

**Comment by Monte9** [comment]
@mguida22 good catch. I'd be happy to merge the PR with the appropriate fixes. 

Here's the current deployment pipeline: All the pages on the website live in the `docs` folder. When a commit is made to master, Travis CI automatically pushes everything in the docs folder out to gh-pages and the changes go live on our website.

Also for the issue that you raised.. there is a simple fix. Just replace the repo's [readme](https://github.com/react-native-training/react-native-elements/blob/master/README.md) with the [index.md](https://github.com/react-native-training/react-native-elements/blob/master/docs/index.md) in the docs folder. That should take care of it. 

Let me know if any of that is confusing.

**Comment by mguida22** [comment]
That makes sense to me! I'll submit a PR for the changes today

**Comment by bozzmob** [comment]
Closed it as part of #315
