### ISSUE TITLE
Card: Title can no longer be Object

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#318]
### Description
<img width="487" alt="screenshot 2017-04-18 08 20 19" src="https://cloud.githubusercontent.com/assets/781745/25117319/dbeff5ac-2411-11e7-9255-904f4c1e2c7e.png">

Before updating to 0.11, I was on 0.10. My card used custom <Text /> components, so I could give my subtitle a max of two lines:

```jsx
class ActivitiesScreen extends React.Component {
  renderSubtitle(subtitle) {
    return <Text style={styles.description} numberOfLines={2}>{subtitle}</Text>;
  }

  renderItem
<img width="487" alt="screenshot 2017-04-18 08 20 19" src="https://cloud.githubusercontent.com/assets/781745/25117319/dbeff5ac-2411-11e7-9255-904f4c1e2c7e.png">
(rowData) {
    rowData = rowData.item;

    return (
      <TouchableOpacity onPress={() => this.activityPressed(rowData)}>
        <ListItem
          roundAvatar
          subtitle={this.renderSubtitle(rowData.short)}
          avatar={{uri: rowData.cover_image.location}}
        />
      </TouchableOpacity>
    );
  }
}
```

Now, title and subtitle are no longer accepting anything other than strings (I get warnings, and my numberOfLines gets ignored).

**Comment by tarang9211** [comment]
Hey @RWOverdijk thanks for creating this issue. I will have a look at this and get back to your shortly. From a quick glance, it does look the `featureSubtitle` is accepting only a string.

`  featuredSubtitle: PropTypes.string` <- source code proptypes

**Comment by RWOverdijk** [comment]
@tarang9211 Yeah, the screenshot is wrong, sorry. It was meant to be for title, title gives the same error.

**Comment by bozzmob** [comment]
Hi @RWOverdijk I checked up the history and in the recent release, it looks like @Monte9 had worked has done the changes as per history. Please can you comment?

BTW, @RWOverdijk the current props looks like this-
```
Card.propTypes = {
  children: PropTypes.any,
  flexDirection: PropTypes.string,
  containerStyle: View.propTypes.style,
  wrapperStyle: View.propTypes.style,
  title: PropTypes.string,
  titleStyle: Text.propTypes.style,
  featuredTitle: PropTypes.string,
  featuredTitleStyle: Text.propTypes.style,
  featuredSubtitle: PropTypes.string,
  featuredSubtitleStyle: Text.propTypes.style,
  dividerStyle: View.propTypes.style,
  image: Image.propTypes.source,
  imageStyle: View.propTypes.style,
  imageWrapperStyle: View.propTypes.style,
  fontFamily: PropTypes.string,
};
```

Sticking to these propTypes will resolve the issue. And speaking propType being a String, I feel its the right type. A title would in most cases be a String. Please can you share a scenario where Object would be needed?

**Comment by RWOverdijk** [comment]
@bozzmob Well, same as for subTitle, I want to limit it to two lines. So I'd like to pass in my own Text component. Unless I can solve it with the styles?

**Comment by tarang9211** [comment]
@RWOverdijk I think you should be able to limit it using styles. Let us know if you need more help, happy to do so!

**Comment by RWOverdijk** [comment]
@tarang9211 I would like help :) I don't know how to set the `numberOfLines={2}` through style.

**Comment by nonotest** [comment]
Title should be a string for sure but what about cases where you want to have something else on the first line, like a button? At the moment seems like the only way is to use absolute styles.
Maybe add a new prop like antd ? https://ant.design/components/card/
they have an "extra" prop to allow elements on the right side of the title.
there would definitely be use cases for this?
I dont mind sending a PR.

cheers,

**Comment by Monte9** [comment]
@nonotest I like this idea. And thanks for offering to send a PR for this. 😃 I will gladly review & merge it.

The above code sample looks good. Although could you attach a screenshot for what it looks like? (I imagine it's an edit & close button to the right of the title?)

Also I agree with @nonotest that a title should only be a string, although the subtitle should accept an object as well. So if anyone want to submit a PR with this fix, I would appreciate that.

**Comment by RWOverdijk** [comment]
I'll look into allowing a component. Only accepting text just isn't enough for a component like this I'm afraid.

**Comment by Monte9** [comment]
Closing this issue now. But if anyone (@RWOverdijk or @nonotest) wants to submit a PR to allow subtitle to be an object or a string, feel free to do so.

**Comment by nonotest** [comment]
Hello,
sorry been busy with other stuff.

this is what it could look like:

![card_example](https://user-images.githubusercontent.com/2551341/28240816-ca42fbda-69ba-11e7-9c7a-3add77663fd8.png)

maybe just have 2 new props that each accept a component eg

titleRightComponent
titleLeftComponent

?
I ll have more time next week to send something.
