### ISSUE TITLE
Adding an onPress for rightIcon on ListItem

### ISSUE THREAD

**Issue by jmancherje** [react-native-training/react-native-elements#324]
Is it possible to have a separate `onPress` for the rightIcon on a `ListItem`?

![image](https://cloud.githubusercontent.com/assets/13545128/25262209/51bee7b6-260b-11e7-932e-b53d58d39089.png)

In the example image above, I would like an `onPress` on the `close` icon on the right, and possibly a different `onPress` function on the body of the `ListItem`. Is this currently supported / possible? I went through all of the ListItem props and I didn't see anything I thought I could use for this.

Here is the code for the ListItem in the diagram.
```
    <ListItem
        title={ <Text>Some Title</Text> }
        subtitle={ <Text>And a subtitle</Text> }
        onPress={ () => { console.log('pressed anywhere on list item'); } }
        key={ index }
        rightIcon={{ name: 'close', style: { color: 'red' } }}
    />
```

If this functionality is not available, maybe this can be labeled a feature request.

Thank you!

**Comment by jmancherje** [comment]
Any work around would be greatly appreciated as well.

**Comment by Monte9** [comment]
@jmancherje I think that could be valuable to the others as well. Thanks for suggesting it. 

I'll submit a PR for this soon. Stay tuned.

**Comment by karanguptak9** [comment]
@jmancherje #374 fixes this issue.

**Comment by Monte9** [comment]
This fix will be released in `v0.12.3`

**Comment by npbjr** [comment]
your fixes not working, 
`deleteItem = () =>{
		console.log("delete item")
	}
	keyExtractor = (item, index) => index.toString()
	renderItem = ({ item }) => (
		  <ListItem
		  	containerStyle={styles.list_style}
		    title={item.name}
		    subtitle={item.subtitle}
		    onPressRightIcon={this.deleteItem}
		    rightSubtitle={item.price + ' php'}
		    rightIcon={{ name: 'delete' }}
		    // rightAvatar={{ source: { uri: item.avatar_url } }}
		  />
		)`

**Comment by fedecaccia** [comment]
Any update? How do we use the "fix"?

**Comment by iRoachie** [comment]
@fedecaccia 

```jsx
<ListItem 
  rightIcon={{ 
    name: 'edit', 
    onPress: () => { console.log('my right press') } 
  }} 
/>
```

**Comment by FaizyQadri** [comment]
this code is not showing icon in android
