### ISSUE TITLE
Avatar Center

### ISSUE THREAD

**Issue by ilrein** [react-native-training/react-native-elements#327]
I really like the ```<Avatar />``` component, but I cannot get it to center within a View. I've tried the following style changes:

```
              containerStyle={{
                justifyContent: 'center',
                alignItems: 'center',
              }}
              avatarStyle={{
                justifyContent: 'center',
                alignItems: 'center',
              }}
              outerContainerStyle={{
                justifyContent: 'center',
                alignItems: 'center',
              }}
```

But still, cannot get the darn Avatar to take the center of it's parent. How can one properly center the Avatar component?

**Comment by Monte9** [comment]
@ilrein use `position: 'absolute'` for now.

**Comment by ilrein** [comment]
@Monte9 position absolute worked, but I had to manually try different Left/Right combinations before I found a sweet spot for xlarge. I'm not sure how reliable this code would be on different simulators and whatnot, but it'll do for now.

**Comment by richa-dua** [comment]
Has this been fixed? Can I position it to right end after hiding chevron?

**Comment by Monte9** [comment]
@richa-dua the `Avatar` component is still using `absolute` styles. Will def be fixed in `v1.0` coming out in the next couple months. Stay tuned.

**Comment by camux** [comment]
I fixed on this way:

`        <View style={styles.image_view}>
          <Avatar
            large
            rounded
            source={{uri: 'my_image'}}
          </Avatar>
        </View>`

`  image_view: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },`

**Comment by mayankpandav** [comment]
` <View style={styles.image_view}>
            <Avatar
              xlarge
              rounded
              source={{
                uri:
                  'https://s.gravatar.com/avatar/72b32254e2234eaeae74a29244ee3dfb?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fim.png',
              }}
              showEditButton
            />
             </View>`
` const styles = StyleSheet.create({
    image_view: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
});`
