### ISSUE TITLE
npm install: "sh: opencollective-postinstall: command not found"

### ISSUE THREAD

**Issue by peternann** [react-native-training/react-native-elements#335]
Ran "npm i react-native-elements --save" on a Mac for installation.

Got the output shown below. Should I be concerned?

`$ npm i react-native-elements --save

> react-native-elements@0.11.2 postinstall /Users/peter/DEV/ShoppingRocket/ReactNativeApp/node_modules/react-native-elements
> opencollective-postinstall || exit 0

sh: opencollective-postinstall: command not found
ShoppingRocketRN@0.0.1 /Users/peter/DEV/ShoppingRocket/ReactNativeApp
└─┬ react-native-elements@0.11.2 
  ├── react-native-side-menu@0.20.1 
  └─┬ react-native-tab-navigator@0.3.3 
    └── immutable@3.8.1 
`

**Comment by Monte9** [comment]
@xdamman possible fixes?

**Comment by xdamman** [comment]
Thanks for the heads up. Yeah been working on a new version to avoid this error (that is not impacting but it doesn't look good, we can do better!). Been running around but I'll file a PR by end of the week.

**Comment by xdamman** [comment]
If you need a quick way to solve this with the current version, just move the opencollective-postinstall from devDependencies to dependencies.

**Comment by cyclops24** [comment]
I have this issue too. Why this happens?

**Comment by xdamman** [comment]
On it. I'll submit a fix when I'm at a computer later today.

**Comment by Monte9** [comment]
PR #358 addresses this issue. 

Should be fixed in the next release `v0.11.3`

**Comment by jfilter** [comment]
I had this bug while upgrading from v0.13.0 to v0.15.0 with `npm install react-native-elements@latest` but removing & reinstalling solved it.
