### ISSUE TITLE
Avatar: Indicator while network image is fetched?

### ISSUE THREAD

**Issue by joncursi** [react-native-training/react-native-elements#336]
Would be great if the Avatar component implemented [react-native-image-progress](https://github.com/oblador/react-native-image-progress) under the hood to show a loading indicator while networked images are fetched. react-native-image-progress is a drop-in replacement for the react-native core `<Image />` component (API is the same, plus a few additional props: https://github.com/oblador/react-native-image-progress#properties). The default indicator is `ActivityIndicator`; using this will not cause any additional dependencies on ReactART. We'd just get the default spinner for free.

**Comment by tarang9211** [comment]
@joncursi Thanks for this issue and giving us some feedback. We will be aiming to support this feature in the next release.

**Comment by binoy14** [comment]
@joncursi As @tarang9211 mentioned we are working on new feature in which you can pass in custom image component to any component that uses Image. This would be useful in cases like this and also help us to keep our dependencies on third part libraries less.

**Comment by joncursi** [comment]
That sounds like a great solution. Where can I track progress?

**Comment by binoy14** [comment]
@tarang9211 on working on PR #342 there is not there much currently but feel free to chime in and provide feedback

**Comment by Monte9** [comment]
Related Feature request #334

**Comment by martinezguillaume** [comment]
😯 I think it can be a good thing to have placeholder component for image where it’s loading, we could try to implemented https://github.com/expo/react-native-fade-in-image with a placeholder and placeholderStyle props (and a beautiful fade in when it’s loaded) @Monte9

**Comment by iRoachie** [comment]
It’s something I always end up making in my apps so I think it’d be great to have it as a util

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/f8af41c1959625c1d3679a88ad9437059abe39aa. Will be available in `beta6`

**Comment by iRoachie** [comment]
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!

**Comment by SiSa68** [comment]
@iRoachie I'm using placeholder but after finish loading my source image, the placeholder is still there on back of my PNG image!
Is there any way to remove it after the image appears?

**Comment by SiSa68** [comment]
@iRoachie Thanks for your response. Is there any definite time for the release date of next version?

**Comment by iRoachie** [comment]
This Sunday (Saturday night)!

**Comment by SiSa68** [comment]
Good news!
