### ISSUE TITLE
Side menu with react navigation

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#338]
~~Using the side menu with react navigation, puts a weird shadow around the content and over the navigation bar. Are there any working examples available?~~

**Update**

The shadow thing was a bug, being my own stupidity. Now the **real issue** is the lack of a shadow on the left side of the navigation:

<img width="459" alt="screenshot 2017-04-25 20 32 21" src="https://cloud.githubusercontent.com/assets/781745/25401560/4e588d5e-29f6-11e7-8206-f86a4a56e978.png">

**Update**

~~It gets weirder when I navigate. Anytime I navigate the sidebar just pops open, as to say "did you mean, me?".~~

Another case of me being stupid.

**Comment by tarang9211** [comment]
@RWOverdijk Seems like you figured it out? Can we close this issue?

**Comment by RWOverdijk** [comment]
@tarang9211 The lack of shadow on the nav bar is the only remaining issue here. The rest was just my own fault. Any ideas?

**Comment by tarang9211** [comment]
@RWOverdijk Could you provide some sample code? I can try mocking it up real quick with that.

**Comment by RWOverdijk** [comment]
@tarang9211 I don't have the time for that now, but it's just a StackNavigator (simple) with an initial page, wrapping it in a SideMenu. Should give you the above ^

**Comment by binoy14** [comment]
@RWOverdijk Sorry that your having this issue but we are actually using sidemenu provided by https://github.com/react-native-community/react-native-side-menu I think this issue best suits there.

**Comment by RWOverdijk** [comment]
https://github.com/react-native-community/react-native-side-menu/issues/277

**Comment by Monte9** [comment]
> Using the side menu with react navigation

@RWOverdijk why not just use `DrawerNavigation` from `react-navigation` instead. 

Also, we will be removing the dependencies to `react-native-side-menu` & `react-native-tab-navigator` in the future releases and will just point users to react-navigation instead.

/cc @binoy14 ^^

**Comment by RWOverdijk** [comment]
@Monte9 That's... Alrighty then. Thanks for the info.
