### ISSUE TITLE
react native elements for web

### ISSUE THREAD

**Issue by foobar8675** [react-native-training/react-native-elements#348]
Not an issue, more a question. I really like this library, and am now getting into react web. Is there a web equivalent of react-native-elements?

**Comment by binoy14** [comment]
@foobar8675 we don't officially support it but in theory you should be able to use with react-native-web but not with reactjs

**Comment by MichelDiz** [comment]
I'd like to know that too. I am studying about PWA and would like to find an equilibrating Lib to react-native-elements. That get close to the general concept and immerse the idea that PWA is an app "native" in fact. Visually.

I've been researching several libs and not one I like like this one.

I think react-native-web just works for RN components, not third ones. If so, how?

Cheers

**Comment by xavier-villelegier** [comment]
Hey @MichelDiz, some people uses RNE for web builds. Here are some issues/PR you might check

#759 
#960 
#882 
#874 
#110

**Comment by MichelDiz** [comment]
@xavier-villelegier  Take a look https://pastebin.com/tEdXezxC

I am still analyzing your references. As far as I've seen, I've only seen examples working are with Expo. PWA can not be made with Expo as far as I know (I have not yet seen how to do it this way).

I'm using NextJS (ReactJS) and Apollo (graphql).

**Comment by jacklinton** [comment]
I don't think the fact that expo is being used should make any difference. Expo is what is driving the actual native app and has nothing to do with the browser portion of the app. In my experience, everything I've used in the 0.19.1 version of the build has worked fine with react native web. Any Vector Icons you're using will have to be imported as per the instructions on the Vector Icons for web instructions.

Have you given it a try?

**Comment by MichelDiz** [comment]
@jacklinton yeah, sorry about that, I tested a PWA example and added Expo. Works.

Yes I tested react-native-elements directly and using react-native-web with this example https://github.com/Gregor1971/rne-cross-platform-example works nicely.

As you see here https://github.com/zeit/next.js/issues/858#issuecomment-380598376 my issue is actually with Next JS and their Webpack/Babel behave.

More details: https://spectrum.chat/thread/e055ef10-ea2f-4de6-8041-b4a2ca2f5e39

**Comment by xavier-villelegier** [comment]
@jacklinton @MichelDiz Glad to hear you're finally using RNE for the web ! Feel free to give your feedback about your experience. It could be cool to know which components work fine on the web, why others don't work, and what can be done to fix them. Also, are you using @Gregor1971's fork or the official repo ? Also feel free to [reach us on slack](https://reactnativetraining.herokuapp.com/)
