### ISSUE TITLE
bind list item onpress

### ISSUE THREAD

**Issue by JWDobken** [react-native-training/react-native-elements#349]
Relatively new to React Native; and in the following example code I want to create a list with a bound `onPress` function. Unfortunately, pressing an item will always print the last item, which is "Suze" in this case.

    import { List, ListItem } from 'react-native-elements';
    ...

    constructor(props) {
      super(props);
      this.renderPerson = this.renderPerson.bind(this);
      this.renderPeople = this.renderPeople.bind(this);
    }

    onPress(name){
      console.log(name);
    }

    renderPerson(person) {
      return (< ListItem
        key={person._id}
        title={person.name}
        onPress={() => this.onPress(person.name)}
      />)
    }

    renderPeople = () => {
      people =  [{"_id": 1, "name": "Eric"},
                 {"_id":2, "name": "Paul"},
                 {"_id":3, "name": "Suze"}]
      return people.map((p) => (
        this.renderPerson(p)
      ))
    }

    render() {
      return (
        <List>
          {this.renderPeople()}
        </List>
      )
    }

**Comment by nonameolsson** [comment]
How did you solve this? I'm experiencing the same problem.

**Comment by binoy14** [comment]
@nonameolsson you can convert on press to use arrow function which binds it to this `onPress = (person) => { }` or bind onPress. Let me know if you need more help

**Comment by nonameolsson** [comment]
@binoy14 Great, thanks!

**Comment by paulohenriquesg** [comment]
@binoy14 I still didn't get this to work. Can you, please, expand a little on your answer?

Thank you!

**Comment by nonameolsson** [comment]
I think this is how you should do. I can't promise it will work because I haven't tried your code.
```javascriptimport { List, ListItem } from 'react-native-elements';
...

constructor(props) {
  super(props);
  this.renderPerson = this.renderPerson.bind(this);
  this.renderPeople = this.renderPeople.bind(this);
}

onPress(name){
  console.log(name);
}

renderPerson(person) {
  return (< ListItem
    key={person._id}
    title={person.name}
    onPress={() => this.onPress(person.name)}
  />)
}


renderPeople = () => {
  people =  [{"_id": 1, "name": "Eric"},
             {"_id":2, "name": "Paul"},
             {"_id":3, "name": "Suze"}]
  return people.map((p) => (
    this.renderPerson(p)
  ))
}

render() {
  return (
    <List>
      {this.renderPeople()}
    </List>
  )
}
```

**Comment by phixtalk** [comment]
@binoy14  and @nonameolsson , you guys may not know it, but i have battled with this same issue for days now. Your code just made my night... thanks a million

**Comment by nonameolsson** [comment]
@phixtalk I'm glad we could help! :)

**Comment by phixtalk** [comment]
thanks once again

**Comment by cihadturhan** [comment]
Sorry for resurrecting this but as far as I know

`onPress={() => this.onPress(person.name)}`

will create a new arrow function instance for every list item you create in each render. Therefore, this approach is not very welcome in react community in performance-wise. This is not a big deal for few rows, but if you have hundred of rows being refreshed, this could be a problem.

I wonder if there is a solution without creating arrow function for every render. Thanks

**Comment by kyler-hyuna** [comment]
@cihadturhan You can use the new [class properties syntax](https://babeljs.io/docs/plugins/transform-class-properties/). It has the correct scope so `this` works, and the function is only created once since it's a property you're referencing.

```js
class LoggingButton extends React.Component {
  // This syntax ensures `this` is bound within handleClick.
  // Warning: this is *experimental* syntax.
  handleClick = () => {
    console.log('this is:', this);
  }

  render() {
    return (
      <button onClick={this.handleClick}>
        Click me
      </button>
    );
  }
}
```

**Comment by iRoachie** [comment]
@cihadturhan You can use the new [class properties syntax](https://babeljs.io/docs/plugins/transform-class-properties/). It has the correct scope so `this` works, and the function is only created once since it's a property you're referencing.

```js
class LoggingButton extends React.Component {
  // This syntax ensures `this` is bound within handleClick.
  // Warning: this is *experimental* syntax.
  handleClick = () => {
    console.log('this is:', this);
  }

  render() {
    return (
      <button onClick={this.handleClick}>
        Click me
      </button>
    );
  }
}
```

**Comment by hakuj** [comment]
@nonameolsson your code worked absolutely fine..thanks you

**Comment by rodrigobdz** [comment]
@iRoachie How would you pass an argument to the `onClick` function?

**Comment by iRoachie** [comment]
@rodrigobdz Recommend you take a look at the guide from the reactjs website https://reactjs.org/docs/faq-functions.html

**Comment by Melanie918** [comment]
Let me ask some questions
How can I build the react native UI element list item and list?
Pls provide the sample code

**Comment by iRoachie** [comment]
@Melanie918 What example are you referring to?

**Comment by niraj002** [comment]
@Melanie918  Refer https://react-native-training.github.io/react-native-elements/docs/listitem.html
You will get all the examples

**Comment by CyxouD** [comment]
@iRoachie this is not the solution in @cihadturhan case, when you need to pass some data `onPress`: you still need to create a new arrow function

**Comment by FDiskas** [comment]
Do not use lambda functions like `onPress={() => this.onPress(person.name)}` bad performance on big list.
