### ISSUE TITLE
Make rounded Button (like large Social Icon)

### ISSUE THREAD

**Issue by camillo777** [react-native-training/react-native-elements#350]
Make a rounded button (like large social icon) same size so that I can stack social icons and custom buttons of the same aspect, style and size.

**Comment by binoy14** [comment]
@camillo777 you should be able to use props in the button dedicated for styling to achieve this. I would be open to adding that as an available prop. Wondering what @Monte9 thinks

**Comment by filiphosko** [comment]
@binoy14 I agree with @camillo777, it would be nice to have these common button designs configurable through props, for example like [this](https://docs.nativebase.io/Components.html#button-outline-headref). We could add rounded, outline and transparent button options. This is something I have on my todo list for a while, so maybe I could look at it.

**Comment by binoy14** [comment]
@filiphosko go for it

**Comment by Monte9** [comment]
Thanks @filiphosko for the PR! 💯 

The PR has been merged and will be released in `v0.12.3`
