### ISSUE TITLE
Peer Dependency react-native-vector-icons@~4.0.0 breaks IOs builds

### ISSUE THREAD

**Issue by fmoraw** [react-native-training/react-native-elements#353]
1. Since react-native > 40 iOS native headers moved
See https://github.com/facebook/react-native/releases/tag/v0.40.0
2. The peer-dependency breaks IOs builds 

The solution could be updating react-native-vector-icons to 0.4.1 if it doesn't break react-native-elements@0.11.2

[Pull Request](https://github.com/react-native-training/react-native-elements/pull/354)

**Comment by TheJare** [comment]
Any ideas how to fix the build after it's been broken? I tried to fix it by installing 4.0.0 manually and tried to link but the react native build still breaks with linker error related to tvOS. I think whatever changes 4.1.0 did to the xcode project are kept even after rolling back to 4.0.0 :(

**Comment by fmoraw** [comment]
Solution fix vector icons to 0.4.0! Can be closed.

**Comment by binoy14** [comment]
Closing this in favor of #356
