### ISSUE TITLE
Disable ListItem

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-training/react-native-elements#355]
Hey! For the ListItem, it would be nice if it could be disabled. I can do it myself, by checking (and I do). I just thought I'd put this out there.

**Comment by Monte9** [comment]
@RWOverdijk that's a good idea. Should be fairly straightforward especially since you are already doing it for your use case. Would you like a submit a PR for this?

**Comment by RWOverdijk** [comment]
@Monte9 Would that include some sort of style change? `disabledStyle` or something?

**Comment by Monte9** [comment]
yup. So one possible way would be to have a `disabled` prop that would apply some defauly disabled styling to the `ListItem`. In addition you would expose the `disabledStyle` prop to allow the user to add custom styles when it's disabled.

**Comment by iRoachie** [comment]
Implemented in v18.0.0
