### ISSUE TITLE
CheckBox cannot trigger onIconPress event when use iconRight prop.

### ISSUE THREAD

**Issue by bondan23** [react-native-training/react-native-elements#357]
### Description
I currently use react-native-elements version 0.11.2, and facing issue on CheckBox usage

1. Checkbox iconRight cannot bind a funciton onIconPress.

### Reproduction Steps and Sample Code
This onIconPress is working fine when i don't use iconRight props

`<CheckBox
                center
                title='Click Here'
                iconType='material'
                uncheckedIcon='check-box-outline-blank'
                checkedIcon='check-box'
                checked={this.state.checked}
                onIconPress={this._onCheck.bind(this)}
              />`

otherwise if i use iconRight props like so 

`<CheckBox
                center
                title='Click Here'
                iconRight={true}
                iconType='material'
                uncheckedIcon='check-box-outline-blank'
                checkedIcon='check-box'
                checked={this.state.checked}
                onIconPress={this._onCheck.bind(this)}
              />`

the event onIconPress is not trigger anything.

### Solution

After i looking the checkbox folder in src, i found the issue , there isn't any onPress and onLongPress props on the icon when iconRight props is set to true , like so 

iconRight == true

`{iconRight &&
          <Icon
            color={checked ? checkedColor : uncheckedColor}
            name={iconName}
            size={24}
          />}`

iconRight == false

`{!iconRight &&
          <Icon
            color={checked ? checkedColor : uncheckedColor}
            name={iconName}
            size={24}
            onLongPress={onLongIconPress}
            onPress={onIconPress}
          />}
        <Text
          style={[
            styles.text,
            textStyle && textStyle,
            fontFamily && { fontFamily },
          ]}
        >
          {checked ? checkedTitle || title : title}
        </Text>
        `

**Comment by Monte9** [comment]
PR #379 fixes this. 

This should be released in `v0.12.3`
