### ISSUE TITLE
[Avatar] Copy-paste example code gives me weird results.

### ISSUE THREAD

**Issue by lsps9150414** [react-native-training/react-native-elements#359]
**My code:**
```javascript
import React, {
  Component,
  PropTypes,
} from 'react';

import {
  View,
  Text,
} from 'react-native';
import { Avatar } from 'react-native-elements';

const propTypes = {
  navigation: PropTypes.object.isRequired,
};

const defaultProps = {};

export default class Connection extends Component {

  render() {
    return (
      <View>
        <Text>Connection</Text>
        <Avatar
          large
          icon={{ name: 'person' }}
          onPress={() => console.log("Works!")}
          activeOpacity={0.7}
        />
        <Avatar
          large
          title="LW"
          onPress={() => console.log("Works!")}
          activeOpacity={0.7}
        />
      </View>
    );
  }

}

Connection.propTypes = propTypes;
Connection.defaultProps = defaultProps;
```

**What I get on iOS:**
![simulator screen shot 2017 5 8 3 00 05](https://cloud.githubusercontent.com/assets/5022617/25784084/76ad0c5a-339a-11e7-8b79-ee9863361a6a.png)

**What I get on Android:**
![screenshot_20170508-025954](https://cloud.githubusercontent.com/assets/5022617/25784108/a56145e8-339a-11e7-9c71-785d81d27097.png)

**Suggestions:**
Guessing the problem is caused by the use of absolute positioning. Perhaps better to avoid absolute positioning and use flex layout instead?

**Comment by binoy14** [comment]
@lsps9150414 yes we aware of this issue looking at solution to fix it so it works separately as well as in the list component. Thanks for reporting :)

**Comment by lsps9150414** [comment]
@binoy14 I've also created an `Avatar` component with configurable edit button and status indicator. No sure if it helps :)
https://github.com/lsps9150414/react-native-ui-toolbox/blob/master/src/Avatar.js

**Comment by Monte9** [comment]
@lsps9150414 yes, it helps for sure! And I love how you have extended `Avatar.js` building function on top of it, as opposed to starting from scratch (which most people do). 

Would you be kind enough to submit a PR? If we are able to merge that in RNE, I am sure lots of people could find your code useful. 💯 Let me know. 

`react-native-ui-toolbox` sounds really cool. I would love to talk to you more about it. Can you please join our slack? https://reactnativetraining.herokuapp.com/> 

DM me once's your in> @monte9. See you on the other side. 😄

**Comment by lsps9150414** [comment]
@Monte9 Cool thanks for the invitation :D

I have submit the PR https://github.com/react-native-training/react-native-elements/pull/360

**Comment by binoy14** [comment]
Closing this, further discussions in the PR
