### ISSUE TITLE
[FormInput] How to change the default color when it was focused?

### ISSUE THREAD

**Issue by ElonXun** [react-native-training/react-native-elements#363]
### Description

How to  change the default color when it was focused?

**Comment by binoy14** [comment]
@ElonXun not 100% sure what you mean but you can change the style of the forminput using `inputStyle` prop. You can also pass all that the TextInput from react native has to the FormInput. 

Closing this as it sounds more like a question. Feel free to reach out to us if you need more help

**Comment by ElonXun** [comment]
thx i have solved

**Comment by Monte9** [comment]
@ElonXun can you post a working example of your solution? Might be useful to others who are trying to do a similar thing. Thanks.

**Comment by akajack** [comment]
I have the same problem. How did you solve it?
