### ISSUE TITLE
Missing border on button group

### ISSUE THREAD

**Issue by JaysonMandani** [react-native-training/react-native-elements#364]
![image](https://cloud.githubusercontent.com/assets/1963153/25942528/a99f0db6-366f-11e7-88df-37192c2133e4.png)

**Comment by binoy14** [comment]
@JaysonMandani Can you provide code snipped or [snack](https://snack.expo.io) so we can also reproduce it?

**Comment by JaysonMandani** [comment]
```
import React, { Component } from 'react'
import {
  Text,
  View,
	StyleSheet,
  Dimensions,
	Platform,
	KeyboardAvoidingView,
	Image,
	TextInput,
	TouchableOpacity
} from 'react-native'

import { ButtonGroup } from 'react-native-elements';

export default class SignUpScreen extends Component {
	constructor(props) {
		super(props);
		this.state = {
		}
	}

  render() {
    const component1 = () => <Text>Hello</Text>
    const component2 = () => <Text>World</Text>
    const component3 = () => <Text>World</Text>
    const component4 = () => <Text>World</Text>

    const buttons = [{ element: component1 }, { element: component2 }, { element: component3 }, { element: component4 }]
    return (
			<View style={styles.imageContainer}>
        <ButtonGroup
          innerBorderStyle={{color: '#000'}}
          buttons={buttons}
          containerStyle={{backgroundColor: 'transparent', borderColor: '#000'}}
          onPress={this._updateIndex}
          />
			</View>
    );
  }
}
```
"dependencies": {
    "react": "^16.0.0-alpha.6",
    "react-native": "^0.44.0",
    "react-native-elements": "^0.11.2"
  }

**Comment by binoy14** [comment]
@JaysonMandani Seems like a bug, https://snack.expo.io/BkOQMK7eZ Thanks for reporting

**Comment by martinezguillaume** [comment]
It seems that this bug is only on Android. The border between the first and the second button is absent. I have no problem on iOS.

**Comment by Monte9** [comment]
@binoy14 @martinezguillaume any ideas on what might be causing it? Possible fixes?

**Comment by binoy14** [comment]
@martinezguillaume See the snack demo it's actually only happening on iOS and not on Android. I will try to look at this and fix it.

**Comment by martinezguillaume** [comment]
For me, it's working on iOS and not working on Android ahaha, don't know

**Comment by binoy14** [comment]
In any case it's a bug that needs to be squashed. If anyone has the solution feel free to send a PR!

**Comment by martinezguillaume** [comment]
It seems that it's a react-native bug, see this [issue](https://github.com/facebook/react-native/issues/8236). We can workaround this if we set the left border of the second button (the second button will have 2 borders, left & right). We can't specified a border radius and a border at the same time for now... I can do the PR with the workaround for now if you are okay with this idea.

**Comment by Monte9** [comment]
@martinezguillaume sounds good to me. If it works for your use case, chances are other people can benefit from it as well.

**Comment by martinezguillaume** [comment]
No problem, I’ll do it tomorrow !

**Comment by JaysonMandani** [comment]
My only solution for button group is to create my own lol :D Hope this issue will close soon.
