### ISSUE TITLE
Could this library distribute a minified file?

### ISSUE THREAD

**Issue by sufuf3** [react-native-training/react-native-elements#375]
Hi, 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We hosted this library.

But the file is now non-minified in new releases.
Would you provide it a minified file under `build`?
Then CDNJS can use auto-update to get this library new release version automatically.

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#10418

**Comment by binoy14** [comment]
@sufuf3 Will fix it in the next release. Thanks for pointing that out

**Comment by sufuf3** [comment]
Thank you!
Would you provide the minified files in current version (v0.12.0) ?

**Comment by binoy14** [comment]
@sufuf3 Fixed a bug where the file bundle was not getting minified

**Comment by sufuf3** [comment]
@binoy14 Thanks.
Could you help minify the file bundle which from npm > v0.12.0 ?

**Comment by Monte9** [comment]
@binoy14 thoughts on the above request?

**Comment by binoy14** [comment]
@sufuf3 Not sure how it would be possible since master branch holds the minified files and we can't commit for something back in time. Any ideas how to do it?

**Comment by sufuf3** [comment]
Hi @binoy14 ,
If add the versions>0.12.0 from npm to GitHub, then there are v0.12.1 and v0.12.2 in GitHub repo. 
And let me manually add these versions from GitHub to CDNJS.
When new versions releases from npm with minified `bundle.js`, CDNJS can auto-update the version.
I don't know is it a good idea?
But I think I can do this.

If you have any suggestions, please let me know.
Thank you.

**Comment by Monte9** [comment]
@sufuf3 what's the status on this? Can this issue be closed?

**Comment by binoy14** [comment]
@sufuf3 Not sure what can I do to help?

**Comment by sufuf3** [comment]
I saw  v0.12.1 and v0.12.2 release from npm but these versions do not release from GitHub.
Could you help to add  v0.12.1 and v0.12.2 to GitHub repo?
Thank you.

**Comment by Monte9** [comment]
Looks like the latest version `v0.14.0` is on cdnjs [here](https://cdnjs.com/libraries/react-native-elements). 

Closing this issue now. Please open again if future versions are not distributed automatically.

**Comment by sufuf3** [comment]
Thank you.
