### ISSUE TITLE
Can I use ListItem components then change the color like the picture?

### ISSUE THREAD

**Issue by tsaohucn** [react-native-training/react-native-elements#376]
Can I use ListItem components then change the color like the picture below by props?

<img width="318" alt="2017-05-15 6 47 27" src="https://cloud.githubusercontent.com/assets/6713879/26054450/2eb2fcf6-399f-11e7-8032-40298e0a4906.png">

**Comment by binoy14** [comment]
@tsaohucn yes you can take a look here https://snack.expo.io/r1eCjuUWW closing this since its not an issue. Feel free to reach out if you still need more help
