### ISSUE TITLE
Missing: sample for FormValidationMessage

### ISSUE THREAD

**Issue by mleduque** [react-native-training/react-native-elements#377]
The "forms" page contains code samples for FormInput and FormLabel but nothing showing how to use FormValidationMessage.
All there is is a screenshot.

For example, how do I set things up if I want to check the content is a number? How do I link the FormValidationMesage to the FormInput? How do I provide the validation function?

**Comment by martinezguillaume** [comment]
The ```FormValidationMessage``` is just a styled text. You have to implement for now the logic of errors. Basically, if you have an error, display the ```FormValidationMesage```, if not, display nothing

**Comment by Monte9** [comment]
@martinezguillaume thanks for pitching in. Could you by any chance provide a simple working example of what you have described above.. something that can help beginner users use as a reference to implement formValidation with the FormInput & FormLabel components?

**Comment by martinezguillaume** [comment]
Yes no problem ! I put that in this issue ?

**Comment by Monte9** [comment]
Sure. Let's put it here for now.. and then eventually we could move it to the docs as well.

**Comment by martinezguillaume** [comment]
We can imagine this component :

```js
<View>
  <FormLabel>  
    {label}
  </FormLabel>

  <FormInput ...propsFromTextInput />

  <FormValidationMessage>
    {errorMessage}
  </FormValidationMessage>
</View>
```

When you have an error in your form, just fill the `errorMessage` with your error message.

#### Example
```js
errorMessage = null;
label = 'Email';
```
![image](https://cloud.githubusercontent.com/assets/17292331/26821863/4243dcbc-4aa8-11e7-9720-15faf9fc01df.png)

```
errorMessage = 'This field may not be blank';
label = 'Email';
```
![image](https://cloud.githubusercontent.com/assets/17292331/26821874/4fceccfc-4aa8-11e7-9194-5a60e62b45ea.png)

#### Enhancement

We can imagine a component wrapping `FormLabel`, `FormInput` and `FormValidationMessage` with the props `errorMessage`, `label` and all the props from `TextInput` from react-native. Like this :
```js
const Input = props => {
  const {
    errorMessage,
    label,
    labelStyle,
  } = props;
  return <View>
    // Display label if it's specified
    {label &&
      <FormLabel
        labelStyle={labelStyle}
      >  
        {label}
      </FormLabel>
    }
    <FormInput {...props} />
    // Display error message if it's specified (errorMessage is a simple string)
    {errorMessage &&
      <FormValidationMessage>
        {errorMessage}
      </FormValidationMessage>
    }
  </View>;
}
```

 👊🏼👩🏻‍🚀

**Comment by Monte9** [comment]
Closing this issue as @martinezguillaume has provided pretty useful examples for using FormValidation. Thanks @martinezguillaume!

If anyone wants to submit a PR to update the docs or if you want to work on the enhancements suggested by @martinezguillaume, please feel free to submit a PR.

**Comment by martinezguillaume** [comment]
@Monte9 I'll update the docs and see what I can do for the animations !

**Comment by Monte9** [comment]
@martinezguillaume I appreciate that. 👍 Also fyi, we have an open collective and funds from that are going straight to the contributors. 😉
