### ISSUE TITLE
ListView in list Header

### ISSUE THREAD

**Issue by hari-mohan-choudhary** [react-native-training/react-native-elements#378]
Hello I am using listView but not have there header. How can add header in listView ?

**Comment by powercoder23** [comment]
Hi Hari,
ListView is react-native's component and here in this repository we have  List and ListItem, i don't find this as an issue to this repository but still the answer to your question would be the below link has an step by step guide

[https://medium.com/differential/react-native-basics-how-to-use-the-listview-component-a0ec44cf1fe8](url)

Hope this Helps!
Thanks,
Dhiraj

**Comment by binoy14** [comment]
Hi @hari-mohan-choudhary If you have more questions join our slack channel and you can ask anyone there. @powercoder23 Thanks for pitching in

**Comment by hari-mohan-choudhary** [comment]
thanks @powercoder23
