### ISSUE TITLE
TouchableNativeFeedback.Ripple not a function error on Button component with buttonRadius

### ISSUE THREAD

**Issue by madhutv** [react-native-training/react-native-elements#381]
"TouchableNativeFeedback.Ripple not a function" error on Button component with buttonRadius (on ios). Below is the sample code.

      `< Button
             title="Done"
             borderRadius={10}
       />`
   
Looks like this is occurring in 0.12.1

I am working mainly on ios so, working around this by passing a dummy background prop like so:
```
< Button
      title="Done"
      borderRadius={10}
      background=' ' />
```

**Comment by filiphosko** [comment]
@ madhutv Yep, I stumbled upon this too while working on the Button component. There should be a platform check for Android, we'll have to patch it up. I submitted a fix here https://github.com/react-native-training/react-native-elements/pull/383.

@binoy14 @Monte9 Could you look at this?

**Comment by wilomgfx** [comment]
If you put the background property, it crashes on Android :p

**Comment by filiphosko** [comment]
This is now fixed in master.

**Comment by madhutv** [comment]
Thank you. Tested with 0.12.2 and works fine :-). Will close this item

**Comment by Monte9** [comment]
@madhutv Glad to hear! 🎉 

@filiphosko great job! 👏  Appreciate your help!
