### ISSUE TITLE
Rating value

### ISSUE THREAD

**Issue by boomfly** [react-native-training/react-native-elements#388]
How to set rating value?

**Comment by binoy14** [comment]
@boomfly Did using `ratingValue` not work?

cc @Monte9 
Ref: https://github.com/react-native-training/react-native-elements/blob/master/docs/API/rating.md#rating-props

**Comment by neo125874** [comment]
+1, how to just display the value and disable the touchable

**Comment by binoy14** [comment]
Not sure, @monte9 would know that. You can join our slack to get answer quickly https://reactnativetraining.herokuapp.com/

**Comment by Monte9** [comment]
@boomfly @neo125874 

> how to just display the value and disable the touchable
Currently, this is not supported. I had planned to implement that feature in an upcoming release. 

Although @leonfeng has submitted a PR with some enhancements to the Rating component that will provide this functionality. I will review the PR and it will be available to use in the next release `v0.12.4`

/cc @leonfeng

**Comment by pdoggi** [comment]
@boomfly @neo125874 

One way to set the rating before the PR from @leonfeng is released is to use the built in [`setCurrentRating(value)` function](https://github.com/react-native-training/react-native-elements/blob/master/src/rating/Rating.js#L177). [Add a ref to the element](https://facebook.github.io/react/docs/refs-and-the-dom.html) and directly call `setCurrentRating` on the rating element. 

I typically don't directly manipulate elements like this, as it's better to store it in the state and let React do it's magic, but sometimes, you just need to get things to work and this worked for me. Hope that helps!

**Comment by shivamgupta211** [comment]
use startingValue={<your initial rating value to show>}
ex :
<Rating    type="star"  fractions={1}  startingValue={3} ratingBackgroundColor="rgba(103,119,143,1)" style={{backgroundColor:'#000'}} readonly  imageSize={20}  style={{ paddingVertical: 10 }}/>

**Comment by badarshahzad** [comment]
Hi, can you tell me how to get the rating value of Star? Does there any function like onChangeValue?

**Comment by badarshahzad** [comment]
I sovled my issue I got the start value this way: 
```
onFinishRating={(value) => {
                console.log(value)
                
              }}
```
