### ISSUE TITLE
SearchBar clear icon first closes the keyboard drawer on iOS, takes a minimum of two presses to clear text

### ISSUE THREAD

**Issue by gregblass** [react-native-training/react-native-elements#389]
If you test out the search bar clear icon on an actual iOS device (using 0.12.0), the clear icon is painfully difficult to actually press. It will typically take me 3+ tries to get it to actually press it (the first time closing the keyboard input but not clearing the text, sometimes bringing up the paste menu, etc).

The first press is impossible to clear the text, as it will just close the keyboard drawer first. Then you really have to try to hit the little button as dead on as you can to get it to actually work.

If you're clicking with a mouse on the iOS simulator, and you can get it directly on the button, it works. I'm going to try giving it more padding.

**Comment by gregblass** [comment]
It looks like the TextInput element has this all built in: https://facebook.github.io/react-native/docs/textinput.html#clearbuttonmode

**Comment by gregblass** [comment]
I could see why you would implement your own though if the goal is cross-platform elements.

**Comment by gregblass** [comment]
In the end I think its cleaner and just makes more sense for me to implement my own search bar. But, you may still want to look at this one.

**Comment by binoy14** [comment]
@gregblass You bring up good points. 

1. Yes we implemented ourself because of achieving the goal of cross platform. 
2. Closing the keyboard drawer is probably something we can look into fixing and feel free to submit a PR if you think you figured it out.
3. SearchBar inherits all props from native TextInput so you can pass the clearButtonMode prop and it would work for your case.

I am keeping this open for anyone to figure out the clear icon closing the keyboard issue

**Comment by gregblass** [comment]
I would say that you shouldn't make the clear icon available at all on iOS, and make it documented that you need to use the built in clear button with the text input. Otherwise it barely works

**Comment by martinezguillaume** [comment]
Hi ! I'm using the SearchBar component with the clear button, and it works good. It didn't close the keyboard !

**Comment by Monte9** [comment]
@martinezguillaume @binoy14 any ideas on how to address the "close the keyboard when clearn icon pressed"? Is this something that iOS does out of the box?

**Comment by Monte9** [comment]
related issue #426
