### ISSUE TITLE
Adding rightTitle hides the leftIcon partially

### ISSUE THREAD

**Issue by ganeshub** [react-native-training/react-native-elements#390]
Adding rightTitle hides the leftIcon

```
        <List>
          {
            this.state.items.map((l, i) => (
              <ListItem
                key={i}
                leftIcon={{ name: 'user-circle-o', type: 'font-awesome', style: {color: 'blue'} }}
                title={l.name}
                titleStyle={{color: 'red'}}
                subtitle={l.lastMessage}
                rightTitle={l.date}
                rightTitleStyle={{color: 'green'}}
              />
            ))
          }
        </List>

```
![screenshot at 2017-05-20 10 51 35](https://cloud.githubusercontent.com/assets/8176512/26273296/b4fad640-3d4a-11e7-8288-69d13422cd69.png)

**Comment by Monte9** [comment]
Most likely bug with flex & iconHeight conflicting. Thanks for reporting it @ganeshub 

We will push a fix for it in our next release `v0.13`. Stay tuned.

**Comment by Monte9** [comment]
@ganeshub I have fixed this on the `next` branch. 

![screenshot_20170607-140306](https://user-images.githubusercontent.com/7840686/26901341-5bb4f61c-4b8a-11e7-80ba-d5de67c4f15d.jpg)

This will be released in `v0.13`.

**Comment by ganeshub** [comment]
Thanks a ton @Monte9 , It works correctly in v0.13 :)

**Comment by SubhaPrince** [comment]
Badge getting hide after adding rightTitle

**Comment by Monte9** [comment]
@SubhaPrince can you add a screenshot for reference? Also recreating it on https://snack.expo.io/ would be ideal.
