### ISSUE TITLE
make the button float/fixed when when scrolling

### ISSUE THREAD

**Issue by saeropark** [react-native-training/react-native-elements#391]
hi,
how do i make the button float on the screen or have it fixed at the bottom when i am scrolling on the current page?

**Comment by xavier-villelegier** [comment]
Hey,

Your `Button` must be **outside** of your scrolling view, and must be rendered **after** it to be above.
For example if you have a `List` as a scrolling view:

```js
import { Button, List } from 'react-native-elements'

<View>
  <List
    …/>
  <Button
    containerViewStyle={ styles.floatButton }
    …/>
</View>
```

And `styles.floatButton` must look like this:

```js
const styles = StyleSheet.create({
  floatButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
});
```

This will give you a floating button at the bottom right.

**Comment by binoy14** [comment]
Closing this since it's not really an issue. If you still need help let us know. 

Thank you @xavier-villelegier for the answer
