### ISSUE TITLE
Tile onPress doesn't work?

### ISSUE THREAD

**Issue by saeropark** [react-native-training/react-native-elements#395]
I tried
<Tile onPress={()=>this.handlePress(obj)}
..
/>

it doesnt work?
an overlay grey box will appear whenever i tap but no action when press. is this a bug?

**Comment by dabit3** [comment]
Hey @saeropark thanks for the issue. It looks like we are not passing onPress to the Tile. I'll file this as a bug and get a fix in asap, or you are welcome to do so yourself.

**Comment by binoy14** [comment]
This has been merged. Will be out in the next release. Thanks @dabit3 for quick fix

**Comment by saeropark** [comment]
Thank you!

**Comment by williamwlchan** [comment]
Thanks! Any recommendations if I would like to do onPress? Is TouchableWithoutFeedback workable by wrapping the tile tag?
