### ISSUE TITLE
Feature Request: Specify number of lines in ListItem

### ISSUE THREAD

**Issue by mazing** [react-native-training/react-native-elements#397]
React Native supports `numberOfLines` property to `Text` components, but it is not possible to set this property with `ListItem` in `react-native-elements`.

**Comment by Monte9** [comment]
@mazing that's a good point. I think it should be an easy addition. 

Could you submit a PR for it? I will gladly review and merge it.

**Comment by Monte9** [comment]
ListItem now supports `numberOfLines` in the title and subtitle prop. Please see https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L140
