### ISSUE TITLE
I got one problem when i initial elements on index.android.js

### ISSUE THREAD

**Issue by hashemirafsan** [react-native-training/react-native-elements#398]
/Users/rafsan/Projects/android/chatters/node_modules/react-native-elements/src/rating/images/heart.png: Unexpected character '�' (1:0)

can any one help me out ?

**Comment by nguyendhse** [comment]
Do you try to stop server and run `npm start` or `yarn start` ?

**Comment by hashemirafsan** [comment]
yeah

**Comment by filiphosko** [comment]
Hi, I tested it and I can't reproduce your issue. This is usually a packager problem, it can happen when the packager server is running and you add some image asset to your project. Do you still have this issue?

**Comment by binoy14** [comment]
Closing this as it can't be reproduced. Feel free to ask for help if you still having this issue
