### ISSUE TITLE
Tile onPress not working

### ISSUE THREAD

**Issue by williamwlchan** [react-native-training/react-native-elements#408]
Hi,

#395 states that the onPress prop is currently not working for the Tile component. However this does not work even though I use TouchableOpacity

	render() {
		const { name, cover } = this.props.country;
		return (
			<TouchableOpacity onPress={() => console.log('touched')}>
				<View>
					<Tile
						featured
						imageSrc={{ uri: cover }}
						title={name}
						height={SCREEN_WIDTH * 0.5}
					/>
				</View>
			</TouchableOpacity>
		);

But if I do not use the Tile component. The onPress works.

	render() {
		const { name, cover } = this.props.country;
		return (
			<TouchableOpacity onPress={() => console.log('touched')}>
				<View>
					<Text>{name}</Text>
				</View>
			</TouchableOpacity>
		);
	}

Any ideas? 

Thanks.

**Comment by williamwlchan** [comment]
Issue can be closed as I saw that #395  was fixed. Thanks.

**Comment by guofoo** [comment]
any idea which release this bugfix will be released in?

**Comment by Monte9** [comment]
@guofoo it will be release in `v0.13.0`. This release is coming up by tomr latest.
