### ISSUE TITLE
View.propTypes has been deprecated

### ISSUE THREAD

**Issue by tsanak** [react-native-training/react-native-elements#413]
I'm using 
- React Native 0.44
- React Native Elements 0.12.2 

and I'm getting the warning "View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead." when using the Button component.

**Comment by binoy14** [comment]
@tsanak We are aware of this issue and it's a tricky one to solve it right. The ViewPropTypes package is not available on older version of react native and hence it would crash. And going forward View.propTypes will not work so it will cause errors. We are trying to find a better way to fix this. Any suggestions welcomed.

**Comment by limoncello** [comment]
Can anybody shine a light on this issues and show how to use _proptypes_ right, since `View.propTypes` got deprecated?

**Comment by namphuongtran** [comment]
I had same error when used react native "react": "16.0.0-alpha.12", "react-native": "0.46.2", 
Hope it will be fix ASAP

**Comment by iRoachie** [comment]
@binoy14 If this is still open. We could use a polyfill sort of approach where we use ViewPropTypes if it's available, and fallback to View.propTypes if not. I did a similar fix for BackHandler in another repo https://github.com/xotahal/react-native-material-ui/pull/143/files

**Comment by binoy14** [comment]
It has been fixed and merged in the next branch. You can try running next branch and let me know if it it's still an issue

**Comment by namphuongtran** [comment]
hi @binoy14 ,
how can i get next branch to try running?
Thanks

**Comment by iRoachie** [comment]
@namphuongtran You can install it directly with npm.
`npm install --save https://github.com/react-native-training/react-native-elements.git\#next`
`yarn add  https://github.com/react-native-training/react-native-elements.git\#next`

**Comment by namphuongtran** [comment]
Thank @iRoachie ,
i had tried to install as you wrote, but i got this error like picture bellow
![screenhunter_01 jul 17 09 45](https://user-images.githubusercontent.com/12570413/28254224-022f6860-6ad5-11e7-912a-9b7cb20ad2df.gif)

**Comment by binoy14** [comment]
@namphuongtran try `yarn add git://github.com/react-native-training/react-native-elements.git#next` or `npm install git://github.com/react-native-training/react-native-elements.git#next` or you can simply replace the version in your package.json and replace it with `git://github.com/react-native-training/react-native-elements.git#next`

**Comment by namphuongtran** [comment]
Hi @binoy14 ,
i had installed next version like your instruction but i still have error like before
![screenhunter_04 jul 18 12 03](https://user-images.githubusercontent.com/12570413/28303500-bfb0b45a-6bbd-11e7-94e1-eaac3fbc2977.gif)
![screenhunter_03 jul 18 12 02](https://user-images.githubusercontent.com/12570413/28303501-bfb247b6-6bbd-11e7-935f-f2c88c178894.gif)

**Comment by namphuongtran** [comment]
![screenhunter_05 jul 18 13 32](https://user-images.githubusercontent.com/12570413/28303525-d991e4ca-6bbd-11e7-82e7-4d813a3b4b43.gif)
This is my config in pakage.json file.

**Comment by iRoachie** [comment]
@namphuongtran The warnings will still show. Even though we deprecated the Tabs component, we're still referencing it as an dependency for our package. We don't want to remove a component someone might be using in production so deprecating is a way of giving them a notice. In a future release we'll remove it completely, so we won't have that problem.

**Comment by namphuongtran** [comment]
Thank @iRoachie ,

**Comment by namphuongtran** [comment]
Hi @iRoachie ,
as i know react native elements just release new version "react-native-elements": "^0.15.0"? is it right?

**Comment by binoy14** [comment]
@namphuongtran Yes, there was a release last night

Closing this as it will be fixed in future release and it's not really an issue with RNE.
