### ISSUE TITLE
SwipeDeck doesn't work correctly on Android

### ISSUE THREAD

**Issue by ahjorth** [react-native-training/react-native-elements#418]
### Description

1. Explain what you did
**Added Swipedeck to my application, also tried it on the react-native-elements-app on expo**
2. What you expected to happen
**I expected the top card to be swiped away and the card behind to replace it**
3. What actually happens
**A card in the stack BEHIND the first card is swiped away. Or it might be that the top card DOES get swiped, but the top card is shown further back in the stack than it's supposed to**

## More details to perhaps help debug

On the react-native-elements-app on expo, where the swipedeck has the cards of all the celebrities, the first celebrity is *Emma, 29*

When swiping, the card that moves is a card with the celebrity *Amanda, 28*, which I believe **should** be the first celebrity.

After *Amanda* is swiped away, on rerender, *Scarlett, 25* shows up

**Comment by Monte9** [comment]
@ahjorth thanks for creating an issue about this. This is def a bug that we are aware of, but haven't looked into fixing it yet. 

The thing is it happens only on Android, and I suspect it has something to do with the `elevation` style property on Android. 

Do you have any ideas for how we could fix this?

**Comment by Babazon** [comment]
Monte, Stephen Grider fixed this in the course where he built this component by reversing the array.

`    return Platform.OS === 'android' ? deck : deck.reverse();` in the SwipeDeck component's render return statement. 

But can you tell me how you got swiping to work on Android? Currently nothing happens when I try to swipe on Android, whereas it works smoothly on IOS.

**Comment by wuyunqiang** [comment]
SwipeDeck/renderCards change code to 
 <Animated.View key={item.id} style={[styles.cardStyle, {zIndex: 0}]}>
            {this.props.renderCard(item)}
  </Animated.View>
will be OK.

**Comment by Bersam** [comment]
There's another bug, when i set marginTop to swipedeck's cards, anything in top of wipedeck is untouchable. actually, if try swipe there, card will be change, it might be something with swipedeck container. I've used sample code on docs.

**Comment by iRoachie** [comment]
Hey guys we deprecated the SwipeDeck component in the [last release](https://github.com/react-native-training/react-native-elements/releases/tag/v0.15.0) and now it's development is happening in another repo. I suggest you open the issue at that repo instead so it can be tracked and added in. https://github.com/Monte9/react-native-tinder-cards

**Comment by flimawan** [comment]
just add a little elevation to styles.cardStyle, and the first card should be shown first
