### ISSUE TITLE
Make customizable icon size in Checkbox

### ISSUE THREAD

**Issue by magneticz** [react-native-training/react-native-elements#419]
### Description
I am using Checkbox component, and it is pretty handy that i can customize all parts, icons, colors, text style, but i can't customize size of the icon, and it seems hardcoded to 24. So, when i have smaller text, the icon looks huge. 

### Solution
Maybe we can add size parameter, like color parameter. Or even add iconStyle for more flexibility. I can create PR request, if you agree.

**Comment by binoy14** [comment]
I agree, having the ability to customize would be very helpful. Please feel free to send a PR if you have fixed it already.

**Comment by iRoachie** [comment]
@Monte9 I think we can change how this works for v1 however it'll be a breaking change. Instead the `checkedIcon` and `uncheckedIcon` could take in an icon object which has `type, name, color, size, style` like the other icon props from rn-vector-icons.

**Comment by Monte9** [comment]
@iRoachie agreed. There's def a much better way to handle the checkbox component.

For now, @magneticz I have added the fix for the issue. I have added a `size` prop for checkbox that defaults to `24`

This will be released with `v0.16.0` in the next week or so. Keep an eye out for it.

**Comment by brunzero** [comment]
@Monte9 hey there. is it possible to update the docs to include this new prop?

**Comment by iRoachie** [comment]
@brunzero Added in https://github.com/react-native-training/react-native-elements/commit/06bd43c77f085b7ce86afd2c11f06faaab1e5677. Available in next release.

**Comment by kallayyash** [comment]
i did like these its worked for me 

  <View style={[componentstyles.checkboxContainer, this.props.style]}>
                <TouchableOpacity onPress={this.props.onPress}>
                     {this.props.checked ? (
                    <Icon
                        name={this.props.checked ? "checkbox-marked" : "checkbox-blank-outline"}
                        type="material-community"
                        color={this.props.iconColor}
                        size={this.props.iconSize}
                        iconStyle={{color:'rgb(15,113,184)'}}
                    /> 
                    ) : (
                    <Icon
                        name={this.props.checked ? "checkbox-marked" : "checkbox-blank-outline"}
                        type="material-community"
                        color={this.props.iconColor}
                        size={this.props.iconSize}
                        iconStyle={{color:'#797979'}}
                    /> 
                    )}
                </TouchableOpacity>
                {this.props.labelComponent}
            </View>
