### ISSUE TITLE
"react-native-vector-icons" dependency

### ISSUE THREAD

**Issue by RinkaDink** [react-native-training/react-native-elements#420]
Hi, 

Not sure this is the right platform to ask this question but...

I would like to use this framework for my react-native project. The issue is that my react-native code will live inside an on going native app (Meaning I will have a react-native features inside a native app) and that is why I do not want to make any native code change or add any native dependencies.

The question is, do I need the "react-native-vector-icons" (which needs to be linked) or this project can work without it? (assuming I do not use any of the icon in the project)

thanks, 
Itay

**Comment by binoy14** [comment]
In theory it would work without vector icons, not 100% sure tho. But any component that uses an icon you will get an exception. Not all components use icons, but many do. You can look thru the docs and see which components use an icon and see if you need those components or not.

**Comment by RinkaDink** [comment]
cool,
Thanks for the answer...

I wonder if in those places where you require to use an icon, you can use your own custom icon.

**Comment by binoy14** [comment]
Not at the moment, since we require the Icon from react-native-vector-icons. Are you okay if I close this ?

**Comment by RinkaDink** [comment]
Yes, you can close this issue..
