### ISSUE TITLE
string refs considered legacy

### ISSUE THREAD

**Issue by Jorijn** [react-native-training/react-native-elements#421]
I'm using react-native 0.45.0 and react-native-elements 0.12.2. The official React documentation state string refs as legacy. My eslint is going bonkers over needing to use string refs in the form elements.

What is your point of view on this, can we expect callback refs soon?

**Comment by binoy14** [comment]
Thanks for reporting this. We are trying to change all string refs to function refs, we started doing it in few components but haven't gotten to all of them. If you have some bandwidth, feel free to send a PR

**Comment by Monte9** [comment]
See PR #362 for ongoing work on this issue.

**Comment by Nickman87** [comment]
@Jorijn What components are you referring to? Are there other besides TextInput and SearchBox?

**Comment by Monte9** [comment]
Please follow the discussion on #362 or #392
