### ISSUE TITLE
"Card with divider" example

### ISSUE THREAD

**Issue by gsklee** [react-native-training/react-native-elements#422]
https://react-native-training.github.io/react-native-elements/API/card/

The "Card with divider" example is currently missing.

**Comment by Monte9** [comment]
Yup, you are right. Thanks for pointing this out. 

Will add this soon.

**Comment by Monte9** [comment]
@gsklee I added this on the docs here: https://github.com/react-native-training/react-native-elements/pull/438/commits/68261c1b03bace071e5abbd485cd76ae651008ba
