### ISSUE TITLE
ListItem prop titleNumberOfLines has no effect

### ISSUE THREAD

**Issue by peacechen** [react-native-training/react-native-elements#424]
### Description

Setting the ListItem prop `titleNumberOfLines` doesn't restrict the title to one line.  It's also supposed to place ellipses at the tail after truncation (default behavior for RN Text component).

Also please include the version of `react-native-elements` that you are using: **0.12.2**

### Reproduction Steps and Sample Code
```
<ListItem
	title={name}
	titleStyle={[s.f5]}
	titleNumberOfLines={1}
	subtitle={mySubtitle}
	subtitleStyle={[s.f6, s.i, styles.blue]}
	avatar={ {uri: myImage} }
	avatarStyle={[{width:avatarSize, height:avatarSize}, s.asc]}
	roundAvatar
	hideChevron={true}
	underlayColor={'transparent'}
/>
```
\* `s.` is from the convenient styling library react-native-tachyons.  It produces the equivalent of `fontSize` for f5, etc.

**Comment by Monte9** [comment]
@peacechen I looked at the src and it looks like it's handling the prop correctly. Can update RNE to  `v0.15.0` and try again as we only maintain the latest version.

If you are still having issues on `RNE@latest`, I'd be happy to add a fix for it. Lmk.

**Comment by M-Jas** [comment]
Updating did the trick thanks @Monte9
