### ISSUE TITLE
SearchBar's clearIcon is too small. Provide prop to customize it? 

### ISSUE THREAD

**Issue by lsps9150414** [react-native-training/react-native-elements#426]
### Description
The default `clearIcon` is too small to be accurately pressed on devices with smaller screen (e.g. iPhone 5).

### Solution
Either provide a prop to customize the touchable size or simply make the touchable area bigger.

Currently the touchable area is on the icon itself not the container so the height and width of the touchable area is the same as the icon size. It would be better to make the container touchable so that we can make the touchable area bigger but have the icon remain small.

**Comment by sdotson** [comment]
I'll take a crack at this.

**Comment by iRoachie** [comment]
Any updates on this @sdotson. Just curious if you're already working on something.

**Comment by sdotson** [comment]
@iRoachie , Feel free to go for it! I'd recommend taking a look at my closed PR for some background information.

**Comment by Monte9** [comment]
@xavier-villelegier can you address this as part of your `SearcBar v1` refactor? Thanks.
