### ISSUE TITLE
react-native-elements@0.13.0 didn't support react-native-vector-icons@4.2.0

### ISSUE THREAD

**Issue by pyyzcwg2833** [react-native-training/react-native-elements#428]
When I try to install this package with `npm i react-native-vector-icons --save && react-native link react-native-vector-icons`,  it reported an error with `npm WARN react-native-elements@0.13.0 requires a peer of react-native-vector-icons@~4.1.1 but none was installed`.
Of course, I have installed `react-native-vector-icons@4.2.0`, but I hope that this package will support `react-native-vector-icons@latest` in the near future

**Comment by artyomtrityak** [comment]
i don't see any breaking changes made for https://github.com/oblador/react-native-vector-icons/releases/tag/v4.2.0 release that might affect this repo, any real issues have been found except error?

**Comment by Monte9** [comment]
@pyyzcwg2833 @artyomtrityak I have updated the package version to support `react-native-vector-icon@4.2.0`.

Here's the [commit](https://github.com/react-native-training/react-native-elements/pull/438/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) and this exists on the `next` branch.

This should be out in `v0.14.0` coming out within the next few days.
