### ISSUE TITLE
FormInput Component does not have a focus() prop

### ISSUE THREAD

**Issue by jasan-s** [react-native-training/react-native-elements#429]
I am using v0.12.2 and was trying to implement  focus to the next TextInput field. IF I use the standard Textinput from react-native the focus() prop is available through the refs, but using formInput it is not. Am I missing something here?

**Comment by filiphosko** [comment]
@jasan-s If you want to get the ref for the input, you have to use the textInputRef prop. You can check the inner workings of the component [here](https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormInput.js). The API for this component is not ideal and is going to change, you can follow the discussion here https://github.com/react-native-training/react-native-elements/pull/362.

**Comment by filiphosko** [comment]
I'm closing this for now, if you'll have further questions or this solution isn't sufficient for you, we can reopen later.
