### ISSUE TITLE
react-native-elements@0.13.0 Rating.js Requires Missing Files

### ISSUE THREAD

**Issue by junctioniv** [react-native-training/react-native-elements#430]
I updated my version of react-native-elements@0.13.0 to get the fix for the Selection color bug (  #331  ) but now I started getting an Error 

> Unable to resolve module `./images/star.png` for `...\app\node-modules\react-native-elements\src\rating\Rating.js`: Directory `...\app\node-modules\react-native-elements\src\rating\images\star.png` doesn't exist.

When navigating to that directory the `images` directory does not exist. The `images` directory is in the source though as it apears [here](https://github.com/react-native-training/react-native-elements/tree/master/src/rating). Any idea why this would be missing when I updated through npm?

**Comment by Monte9** [comment]
@junctioniv this is really strange. We are using the Rating component in our example app with expo and I haven't run into this issue. 

I'll try to reproduce this on a new react-native project. In the meantime, let's me know if this is still an issue for you or if you found a workaround for it.

**Comment by junctioniv** [comment]
@Monte9 I think this may be fixed. I was able to work around it by adding those files manually but I have since had to completely had to delete my `node_modules` directory and do a fresh npm install for a separate issue and I did not have to re-add this missing directory.

Not sure what caused it in the first place. Possibly a npm issue.

**Comment by Monte9** [comment]
Yeah, I suspected it to be an npm upgrade issue. Glad you were able to resolve it by reinstalling your  npm modules.

**Comment by ckeeney** [comment]
I am getting this error on version `0.16.0`.  I am using Ignite boiler plate.  I already tried deleting `./node_modules` and re-running `yarn`.

**Comment by ckeeney** [comment]
In my code, I had 
```js
import { FormInput } from 'react-native-elements'
```

This would import the `FormInput` component from [index.js](https://github.com/react-native-training/react-native-elements/blob/master/src/index.js#L49) of this repository.

However, to get to that line it had to run 
```js
import Rating from './rating/Rating';
```

on [line 19](https://github.com/react-native-training/react-native-elements/blob/master/src/index.js#L19).

Changing my import to 
```js
import { FormInput } from 'react-native-elements/src/form/FormInput'
```
imports the component without running any code related to the `Rating` component, and the problem went away for me here.

**Comment by remcorakers** [comment]
I also have the same issue, with `0.16.0` using create react native app. The images folder in `/src/rating` is not created. Suggestion of @ckeeney works, although its a work around that might break with future upgrades.

**Comment by remcorakers** [comment]
Removing the `.yarnclean` file and removing and adding `react-native-elements` solved the issue. The images folder is now present again.

**Comment by Monte9** [comment]
Thanks for reporting back on the fix @remcorakers! So from what I understand, this is not a problem with RNE, but rather yarn no installing the dependencies correctly. 

Glad you figured it out! 😄
