### ISSUE TITLE
Passing empty strings strings to ListItem via the title and subtitle props

### ISSUE THREAD

**Issue by Solbrim** [react-native-training/react-native-elements#431]
Passing empty strings through the title or subtitle props of ListItem results in a RawText needs to be wrapped in a Text view error. Looks like empty strings are falsy, so ListItem attempts to wrap said strings in a View, instead of Text, given:

            {subtitle &&
              (typeof subtitle === 'string' || typeof subtitle === 'number')

**Comment by peteroid** [comment]
Seems this also affects the <Card /> component. Passing empty string to the title props will throw the `RawText "" must be wrapped ...` error
