### ISSUE TITLE
Error when passing both borderRadius AND backgroundColor to a <Button>

### ISSUE THREAD

**Issue by MilanThomas** [react-native-training/react-native-elements#433]
When using **borderRadius and backgroundColor** props on a <Button> component, I get the following error on **Android** (sorry, I can't attach a screenshot) : 

### "Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView."
The last call of the stack is : `updateViewProp, ViewManagersPropertyCache.java:90`

1. Using Expo version 17.0.0 and react-native-elements version 0.12.2, I created a `<Button>` component and gave it a bunch of props, especially : **backgroundColor and  borderRadius**.
2. I expected to see a button show up in my app with rounded corners and a background color of my choice (which by the way works like a charm on IOS).
3. Instead, I get the error mentioned above.

### Solution

I managed to make it work by removing the borderRadius prop and setting it in the buttonStyle styles.
It lead me to think that the **combination** of the borderRadius and backgroundColor props was the issue. After looking briefly at the source, I noticed this piece of code that could explain the described behavior.

```
if (Platform.OS === 'android' && (borderRadius && !attributes.background)) {
  attributes.background = TouchableNativeFeedback.Ripple(
    'ThemeAttrAndroid',
    true
  );
}
```

### Code used

While I couldn't reproduce the issue on Snack, I tried setting up a simple `<Button>` in my App, which again ended up in an error.

```
...
  <Button
    title="My button
    large
    fontSize={18}
    backgroundColor="#333333"
    borderRadius={50} // <- Removing this prop
    containerViewStyle={styles.buttonContainer}
    buttonStyle={styles.button}
    textStyle={styles.buttonText}
    onPress={this.onPress}
  />
...

const styles = StyleSheet.create({
  buttonContainer: {
    borderRadius: 50
  },
  button: {
    borderColor: '#666666',
    borderBottomWidth: 4,
    borderRadius: 50 // <- And adding the style here seems to resolve the issue
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600'
  },
});
...
```

**Comment by filiphosko** [comment]
@MilanThomas The problem you encountered is related to this issue https://github.com/react-native-community/react-native-linear-gradient/issues/84.

When you are on Android and you provide a borderRadius prop, it will try to use native ripple on the button (TouchableNativeFeedback). When you use buttonStyle, it will just style the inner View (not the touchable itself). I'll try to look for some solution. Could you also post your ```package.json```?

**Comment by MilanThomas** [comment]
@filiphosko Thanks for the quick answer. This make sense since I can tell the feedback effect remains squared when I press the Button.

I'm using Android 4.4, API version 19.

And here is my package.json.

```
{
  "name": "app",
  "version": "0.0.0",
  "description": "App",
  "author": "MilanThomas",
  "private": true,
  "main": "main.js",
  "dependencies": {
    "expo": "17.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
    "react-native-elements": "^0.12.2",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  }
}
```

**Comment by filiphosko** [comment]
@MilanThomas I see your API version is 19 and that's most likely the problem since this bug is present while using API version < 23. If you could upgrade your API version to at least v23 I guess you would get rid of this error.

**Comment by filiphosko** [comment]
I'm closing this issue since it's not directly related to this repository.

**Comment by jpca999** [comment]
I get the same error message.

**Comment by Monte9** [comment]
@jpca999 if you are seeing the same error you can either:
- upgrade your API to 23 (as suggested by @filiphosko)
- `remove the borderRadius prop and setting it in the buttonStyle styles.` (as suggested by @MilanThomas
