### ISSUE TITLE
UNMET PEER DEPENDENCY react-native-vector-icons@4.2.0

### ISSUE THREAD

**Issue by heron2014** [react-native-training/react-native-elements#434]
Hi there,

<img width="496" alt="screen shot 2017-06-20 at 08 10 08" src="https://user-images.githubusercontent.com/8476884/27320894-05670fce-5590-11e7-9ac2-19e8a6a3c41d.png">

Would it be possible to update peer dependencies to met the current version of ```react-native-vector-icons```? unless there is another way to get rid off this warning? 

Thanks.

**Comment by Monte9** [comment]
@heron2014 we are working on this. Should be updated in the next release within the end of the week.

**Comment by heron2014** [comment]
Great, thanks @Monte9

**Comment by Brhernann** [comment]
Nice!

**Comment by szymonsitko** [comment]
Also had the same problem, but I managed to fix it. If you follow the installation guide, before you get to step 2 (following tutorial from the official <a href="https://github.com/react-native-training/react-native-elements/blob/master/default_installation.md">repo</a>), install react-native-vector-icons@4.2.0, if still complains install @4.1.1 and finally react-native-elements. It worked for me with no further issues.

**Comment by Monte9** [comment]
@heron2014 I have update the package version to support `react-native-vector-icon@4.2.0`.

Here's the [commit](https://github.com/react-native-training/react-native-elements/pull/438/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) and this exists on the `next` branch. 

This should be out in `v0.14.0` coming out within the next few days.

**Comment by followthekoden** [comment]
I believe I'm having this same problem again. on version 0.19.1

**Comment by ZardozSpeaks** [comment]
Would it be possible to get this issue re-opened @Monte9 I am also experiencing this problem on 0.19.1

**Comment by iRoachie** [comment]
@ZardozSpeaks it’s been fixed in 
https://github.com/react-native-training/react-native-elements/commit/83f1bc8b3c29c385500e06cdbd2350827dd931a1 It’ll be live in 1.0.0
