### ISSUE TITLE
Header doc image issue

### ISSUE THREAD

**Issue by mnlbox** [react-native-training/react-native-elements#435]
Hi guys,
Header component doc page image not loading successfully:
https://react-native-training.github.io/react-native-elements/API/header/
I check and https://react-native-training.github.io/react-native-elements/docs/images/header.png return error 404 but it's image exist in https://github.com/react-native-training/react-native-elements/blob/master/docs/images/header.png What is the problem?
Any other docs page load well for me.

**Comment by filiphosko** [comment]
@mnlbox Hi, thanks for pointing this out. The correct url should be probably this one https://raw.githubusercontent.com/react-native-training/react-native-elements/master/docs/images/header.png. I'll fix it.

**Comment by mnlbox** [comment]
@filiphosko Thanks for your attention man. 😉

**Comment by Monte9** [comment]
Thanks for the fixes @filiphosko! 👏 

The PR has been merged, and it should updated with the next release soon.
