### ISSUE TITLE
TypeError: expected dynamic type `double', but had type `null' (constructing arguments for UiManager.dispatchViewManagerCommand at argument index 0) 

### ISSUE THREAD

**Issue by mikhail709** [react-native-training/react-native-elements#442]
Hi. I try to implement simple LoginScreen with two FormInputs, LogIn button and Forgot password button. Navigation between the screens is implemented with the help of "react-navigation": "1.0.0-beta.11". So, when I click on Forgot password at my LoginScreen and then turn back to the LoginScreen and then click on any of the input fields - TypeError: expected dynamic type double', but had typenull' (constructing arguments for UiManager.dispatchViewManagerCommand at argument index 0) appears.
It seems that findNodeHandle returns null. But how to fix this issue??

React Native version: 0.44
React version: 16.0.0-alpha.6
Platform: Android

**Comment by dabit3** [comment]
Just out of curiosity, have you tried testing this just using a regular TextInput to make sure that the library is causing the issue? In the meantime, I'll see if I can run down the issues.

**Comment by Monte9** [comment]
This doesn't seem directly related to RNE. Please try to reproduce this with a TextInput from React Native and reopen this if it's caused only by using FromInput from RNE.

**Comment by jose920405** [comment]
I have the same problem

![screenshot_2017-08-31-09-57-02_1024](https://user-images.githubusercontent.com/12536184/29930031-de733894-8e32-11e7-96c7-ff67c2c3b3ab.png)

**Comment by thangkho** [comment]
@mikhail709 
Have you done it yet? I have same error.

**Comment by qiuwanfujoe** [comment]
i meet this issue too
