### ISSUE TITLE
List Rendering Bug on iOS

### ISSUE THREAD

**Issue by junctioniv** [react-native-training/react-native-elements#443]
### Description

I updated from react-native-elements@0.12.2 to react-native-elements@0.12.3 and ran into a rendering issues with `List` components in ios via expo, All the list components in my app are rendering fine on android but on ios the first and last component are rendering with a shadow at the top and bottom of the list respectively. I am running the newest release of expo which is using react-native@0.44.0.

### Reproduction Steps and Sample Code

I opened the react-native-elements demo app on expo on both Android and ios and was able to reproduce the same results.

### Solution

I am currently able to work around this by setting the `containerStyle` of the list to include the following:
`containerStyle={{ borderTopWidth: 0, ....}` but this also gets rid of the top border.

**Comment by phodal** [comment]
same issue, and it seems in big screen will should this, like iPhone 7 plus.

**Comment by junctioniv** [comment]
Forgot to mention that this was happening to me on an iPhone 7 plus as well.

**Comment by tourze** [comment]
I have same issue on my iphone 7s plus. I assign the containerStyle to ListItem: 
   containerStyle={{
        backgroundColor: '#fff',
      }}
and then everything is ok.

**Comment by binoy14** [comment]
Can someone post a screenshot so whoever is trying to fix it knows what exactly is happening

**Comment by alphasp** [comment]
![img_0229](https://user-images.githubusercontent.com/2891447/27855176-070a592c-619c-11e7-9b20-f748a151d14d.jpg)

**Comment by phodal** [comment]
And, this bug can show in iOS simulator

**Comment by Monte9** [comment]
@alphasp's fix for this has been merged and will be released in `v0.14.0` soon. 

Please feel free to reopen id this is still an issue on `v0.14.0`
