### ISSUE TITLE
Unknown Vertical Gap in Card with List Child

### ISSUE THREAD

**Issue by MyTotoro** [react-native-training/react-native-elements#445]
### Description

I'm using a Card to wrap a List/Flatlist, I noticed a 'gap' so I add a blue background to see what was contributing to it, I'm not sure how to get rid of this gap

```
package-lock.json:
"react-native-elements": {
"version": "0.13.0",
```
### Reproduction Steps and Sample Code

![screen shot 2017-06-22 at 11 49 20 pm](https://user-images.githubusercontent.com/3621921/27466043-a63706a4-57a5-11e7-8fc7-2ac0312d3e25.png)

```
<Card
  containerStyle={styles.infoContainer}
  wrapperStyle={styles.listContainer} >
    <DataScreen />
</Card>

infoContainer: {
    position: 'absolute',
    backgroundColor: 'blue',
    flex: 1,
    left: wp(4),
    width: wp(92),
    top: hp(37),
    height: hp(55),
    padding: 0,
    margin: 0
  },

listContainer: {
    flex: 1,
    padding: 0,
    margin: 0
    borderTopWidth: 0,
    borderBottomWidth: 0
  },

<List
  containerStyle={{ borderTopWidth: 0, borderBottomWidth: 0 }}>
  <FlatList
    data={this.state.data}
    renderItem={({ item }) => (
      <ListItem
        roundAvatar
        title={`${item.name.first} ${item.name.last}`}
        subtitle={item.email}
        avatar={{ uri: item.picture.thumbnail }}
        containerStyle={{ borderBottomWidth: 0 }}
      />
    )}
    keyExtractor={item => item.email}
    ItemSeparatorComponent={this.renderSeparator}
    ListHeaderComponent={this.renderHeader}
    ListFooterComponent={this.renderFooter}
    onRefresh={this.handleRefresh}
    refreshing={this.state.refreshing}
    onEndReached={this.handleLoadMore}
    onEndReachedThreshold={50}
  />
</List>
```

The List/FlatList implementation is just copied from 
[https://medium.com/react-native-development/how-to-use-the-flatlist-component-react-native-basics-92c482816fe6](url)

### Solution

No gap? No padding?

**Comment by Monte9** [comment]
@MyTotoro yeah, this is a weird one. I briefly looked at the code for `Card.js` and don't see anything that could be causing it. 

In order to help us get to the bottom of this, can you please replicate this using [Snack](https://snack.expo.io/)? Thanks.

**Comment by MyTotoro** [comment]
@Monte9 

I fixed it by playing around with it:

```
<List
        containerStyle={{ marginTop: 0, borderTopWidth: 0, borderBottomWidth: 0 }}>
        <FlatList
          data={this.state.data}
```

This will remove the gap, I have confused why I can't set `margin: 0` and be done with it

**Comment by iRoachie** [comment]
@Monte9 @MyTotoro While running tests, I don't think this is an actual bug. It looks like the container style for the `List` component which has a default `marginTop: 20`. That's why it appears like it has a huge gap at the top. 

Closing this as solved, however feel free to reopen if you run into it again.

**Comment by DIvu22** [comment]
@Monte9  thanks!! you saved my time
