### ISSUE TITLE
I wanna use Grid, Row and Col but  I get this error :   RawText "" must be wrapped in a n explicit <Text> component 

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements#450]
Pls guide, Im new to this... 

return (
      <TouchableWithoutFeedback onPress={this.onRowPress.bind(this)} style={styles.mainView} >
        <View >
            <Grid>
                <Row size={3}>  {jobtitle} </Row>
                <Row size={1}> {company} </Row>
            </Grid>
      </View>
      </TouchableWithoutFeedback>

Even this doesnt work 

      <TouchableWithoutFeedback onPress={this.onRowPress.bind(this)} style={styles.mainView} >
        <View >
            <Grid>
                <Row size={3}> <Text> {jobtitle} </Text> </Row>
                <Row size={1}>  <Text> {company}  </Text> </Row>
            </Grid>
      </View>

fULL FILE 

import React, { Component } from 'react';
import { Text, ListView, TouchableWithoutFeedback, View } from 'react-native';
import { CardSection } from './common';
// import { Actions } from 'react-native-router-flux';

import {Grid, Col, Row} from 'react-native-elements';

class CompItem extends Component {

  onRowPress(){
    // Actions.employeeEdit({ employee: this.props.employee });
  }
  render(){
    const { jobtitle, company, country, formattedLocation } = this.props.employee;
    // console.log('8- ListItem ', this.props.employee);

    return (

      <TouchableWithoutFeedback onPress={this.onRowPress.bind(this)} style={styles.mainView} >
        <View >
            <Grid>
                <Row size={3}> <Text> {jobtitle} </Text> </Row>
                <Row size={1}>  <Text> {company}  </Text> </Row>
            </Grid>
      </View>
      </TouchableWithoutFeedback>

    );
  }
}

const styles = {
  titleStyle: {
    fontSize: 18,
    paddingLeft: 15
  },
  mainView: {
    marginTop: 50
  }
}

export default CompItem;

### Description

1. Explain what you did
2. What you expected to happen
3. What actually happens

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by binoy14** [comment]
@jpca999 just curious why wrap the grid in a TouchableWithoutFeedback? The grid has an onPress event

**Comment by filiphosko** [comment]
@jpca999 Hi, this happens because you have some whitespace characters there that are messing with JSX. You have to remove the spaces between your ```Text``` tags and ```Row``` tags. The whitespace characters are text and they are passed like that (as children) to ```Row``` which is a ```View```. Generally it is a good idea to format your code well, preferably using Eslint or maybe Prettier. So your 'grid code' should look like this:
```jsx
<View>
  <Grid>
    <Row size={3}>
      <Text>{jobtitle}</Text>
    </Row>
    <Row size={1}>
      <Text>{company}</Text>
    </Row>
  </Grid>
</View>
```
