### ISSUE TITLE
where can I find the whole list of icons ?

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements#451]
Like here 

  {
    title: 'Appointments',
    icon: 'av-timer'
  },
  {
    title: 'Trips',
    icon: 'flight-takeoff'
  }
];

I've added the react-native-elements library inside my component. 
I wanna use the more icons like  filght-takeoff  and more  where is the whole list of it ?

**Comment by binoy14** [comment]
@jpca999 https://oblador.github.io/react-native-vector-icons/ I am closing this since it's not really an issue

**Comment by jpca999** [comment]
It's an issue for me. Why the heck would you close it without pointing me to right direction.

I couldn't understand or locate where the icons are located that's why I asked you... pls answer me, I'm new to react thing.

**Comment by Monte9** [comment]
@jpca999 the link @binoy14 point you to is the right answer. 

For instance, if you search for `flight-takeoff` on the website, you will get the exact type `MaterialIcons` of the icon as well.

**Comment by JustinReport** [comment]
Icon color not enough to change on navigation bar. I tried to change icon color in navigation bar, it not enough like native iOS. But it is possible for other.

**Comment by Calsowah** [comment]
Try changing the color in style. For example,` <Icon type='MaterialIcons' name='create' style = {{color: 'white'}} />`

**Comment by iRoachie** [comment]
@HelpPal please create a new issue.
