### ISSUE TITLE
Use Checkbox In list view

### ISSUE THREAD

**Issue by ChanduB4** [react-native-training/react-native-elements#454]
Hi 

I want to use Checkbox in this listitem please help me

Thanks

**Comment by binoy14** [comment]
@ChanduB4 Take a look at the snack demo https://snack.expo.io/ryqjME_VW hope that helps.

Let me know if I can close this issue

**Comment by Monte9** [comment]
@binoy14 Great use of Snack to demo this use case. 💯

**Comment by fazeelzama20** [comment]
@binoy14 checkbox is used in list, it is showing correctly, but when i check one checkbox all of them are getting selected. can you please help?

**Comment by xavier-villelegier** [comment]
Hey @fazeelzama20, have a look at [this](https://github.com/react-native-training/react-native-elements/issues/603#issuecomment-329986069), it might help 👍

**Comment by KunalPaul** [comment]
if you are using list view than have a look to this

state={
Check:[]
}

componentWillMount() {
var my_check = []
array.forEach((folder) => {
my_check.push(false)
})
this.setState({
Check:my_check
})
}

than in your render do something like this
<ListView
dataSource={Folder.cloneWithRows(this.state.folder)}
renderRow={(rowData,rowID) =>
<CheckBox
label='All'
labelBefore={true}
checked={this.state.Check[rowID]}
onChange={(checked) => {
this.setState({
Check:!this.state.Check[rowID]
})
}}
/>
