### ISSUE TITLE
Button ripple location when pressing on text

### ISSUE THREAD

**Issue by desjarlaisdumaishugo** [react-native-training/react-native-elements#456]
Pressing on the text or the icon of the button produces the ripple centered from top-left corner, while pressing anywhere else on the button produces the correct ripple. Button from react-native though, produces the correct ripple regardless of where the press happens.

![react-native-elements-button-ripple-bug](https://user-images.githubusercontent.com/29261591/27692387-92386c6a-5cb4-11e7-882a-0755e0bd0090.gif)

**Comment by binoy14** [comment]
@desjarlaisdumaishugo Thanks for reporting

**Comment by iRoachie** [comment]
Fixed! Will be available in 0.17

**Comment by iRoachie** [comment]
Fixed in 0.17, which is now live!

**Comment by mariovillamizar** [comment]
@iRoachie @binoy14 @desjarlaisdumaishugo  Is it still present in 4.0.0-rc.6?

https://user-images.githubusercontent.com/10704258/188900597-2c561094-7d8b-4b1d-8960-effbcd19e5ca.mov

It seems like the center of the ripple is after the title.

**Comment by mariovillamizar** [comment]
UPDATE:
I just confirmed it's something with the title. See this:


https://user-images.githubusercontent.com/10704258/188902322-0eb9e9f4-4cd1-48cd-be62-1a306953e0e5.mov
