### ISSUE TITLE
Searchbar need add event onEndEditing

### ISSUE THREAD

**Issue by phamhuyhoang95** [react-native-training/react-native-elements#459]
Hi !
I am trying to make search method work my app but I only see an onChangeText event from Searchbar document. I want to handle the event when user complete enter text in Searchbar. Can you implement something like onEndEditing?

**Comment by binoy14** [comment]
@phamhuyhoang95 All the TextInput native props are supported. This already works, take a look here at the snack demo https://snack.expo.io/BJLrZNu4Z 

Let me know if I can close this issue

**Comment by phamhuyhoang95** [comment]
Thank you. I will close issue
