### ISSUE TITLE
SocialIcon - OnPress not working on Android

### ISSUE THREAD

**Issue by batical** [react-native-training/react-native-elements#460]
### Description
Starting to learn React-native by converting on of my app for fun. Just to say I could have miss lots of thing
1. Explain what you did
SocialIcon Facbook with onPress action
`<SocialIcon
          title={I18n.t('login_facebook')}
          button
          raised
          type="facebook"
          style={{ width: 300, height: 40 }}
          onPress={this.loginWithFacebook}
        />`
2. What you expected to happen
IOS : the function is called
Android : the function ths.loginWithFacebook is called
3. What actually happens
iOS : Working
Android : nothing happen and the following message in the console

> please attach method to this component

Also please include the version of `react-native-elements` that you are using.
"react-native-elements": "^0.13.0",

### WorkAround
iOS : none because it is working
Android : had to implement both onPress and onLongPress 
Tests on device S4 with Android 5

**Comment by binoy14** [comment]
@batical Take a look at this snack demo. It seems like it's working for both android and iOS, https://snack.expo.io/ByQuAX_V-

Do you think something else is causing this issue?

**Comment by YulianD** [comment]
I have the same problem, in expo normal runs, but when I start it on my Smarthphone does not call the function and also sell this message in the console `please attach method to this component`

**Comment by Monte9** [comment]
That's really weird @YulianD! Thanks for reporting it. 

I suspect it has little to do with RNE, but might be a more broaded (`Debug JS Remotely option` -> function not getting called issue)

**Comment by zygama** [comment]
Hello, 
sometimes (often) these days i have this error too, for some weird reasons if I press a lot of time the function associated to onPress is launched but not anytime :/ 

Here is how i call SocialIcon, my function associated to onPress is an arrow function: 
`      <SocialIcon
        title = {
          this.state.userIsAlreadyConnected ?
          I18n.t('login.button_fb_logout') : I18n.t('login.button_fb_login') }
        button
        type = 'facebook'
        style = {{ width: 300, height: 40 }}
        onPress = {this.logInOrLogOutFromFacebook}
      />`

**Comment by nmerchant** [comment]
Can confirm this is happening only when `Debug JS Remotely` is enabled.  Disabling it and the function gets called without issue.
