### ISSUE TITLE
unable to add searchBar in my component 

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements#462]
The list Items works great but the moment i dad search inside the item i get the error. 
Heres a part of my code. 

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  Button,
  View
} from 'react-native';

import { SearchBar } from 'react-native-elements';

import { List, ListItem, Divider } from 'react-native-elements'

// import { SideMenu, List, ListItem } from 'react-native-elements';

class FollowupScreen extends Component {

    static navigationOptions = {
      title: 'Follow UP'
    };

    render() {
      const { navigate } = this.props.navigation;
      return (
        <View>
            <List>

              <ListItem
              <View>
                <SearchBar
                  lightTheme
                  onChangeText={someMethod}
                  placeholder='Type Here...'
                   />
               </View>
                 />

                  <ListItem
                      onPress={() => navigate('allProperties')}
                      title="All Properties"
                      leftIcon={{name: 'flight-takeoff'}}
                      color="rgba(0,122,255,1)"
                  />

2) I also tried this but still getting error. 

    render() {
      const { navigate } = this.props.navigation;
      return (
        <View>

          <SearchBar
            lightTheme
            onChangeText={}
            placeholder='Type Here...'
             />

![image](https://user-images.githubusercontent.com/1026325/27809178-65284a0a-601b-11e7-88d5-ad386dd81c3c.png)

**Comment by binoy14** [comment]
@jpca999 You need to wrap the Search bar in the title prop, not sure if it's just a typo here but check the snack demo. https://snack.expo.io/Skm3w_OV-

Let me know if I can help with anything else

**Comment by Monte9** [comment]
Please see @binoy14's answer above. Also [here](https://react-native-training.github.io/react-native-elements/API/lists/) are the docs if you are curious to know more about the props for List & ListItems.
