### ISSUE TITLE
[Docs] Missing header image

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#467]
Missing image for the Header component on the docs website. 
https://react-native-training.github.io/react-native-elements/API/header/

![screen shot 2017-07-05 at 1 58 46 pm](https://user-images.githubusercontent.com/5962998/27877808-159fc772-618a-11e7-8c4b-95aef504ce6d.png)

**Comment by binoy14** [comment]
@iRoachie Thanks for reporting, this has been fixed and will be released in the next release `0.14.0`

**Comment by iRoachie** [comment]
Glad I could help 🎉
