### ISSUE TITLE
i cannot find various react-native icons  at one place ?

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements#468]
I have to literary jump so many hoops to get these icons 

name='ring-volume'
&      name='flight-takeoff'

    <Icon
        raised
        name='flight-takeoff'
        color='#3F51B5'
       />

    <Icon
        raised
        name=''
        color='#3F51B5'
       />

![icons_-_react_native_elements_ui_toolkit_and_itunes_and_followupscreen_js_ ___movies_dev_react-native-advanced_jobs-x-15_and_glass](https://user-images.githubusercontent.com/1026325/27880263-60601c64-6192-11e7-8af8-dbdc6d54433a.jpg)

### Description

1. Explain what you did
2. What you expected to happen
3. What actually happens

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by btav** [comment]
@jpca999 react-native-elements uses a vector icon package named [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). You can view all the available icons using the following site. https://oblador.github.io/react-native-vector-icons/

**Comment by Monte9** [comment]
@jpca999 Please check older issues before opening new ones. https://github.com/react-native-training/react-native-elements/issues/451#issuecomment-311539053

Also thanks @btav for the right answer!

**Comment by doanhuudung** [comment]
YOu can find ref here

https://material.io/tools/icons/?style=baseline
