### ISSUE TITLE
<Image>with children is deprecated in <Tile>

### ISSUE THREAD

**Issue by rjpounder** [react-native-training/react-native-elements#471]
### Description

There is an issue with new react native throwing out warnings for <Image> having children being deprecated, using the latest react-native-elements AFAIK. I found it in Tils.js, didn't delve any deeper but I'm sure there will be others.

### Solution

Suggests to use ImageBackground

### Edit

Just to clarify, https://github.com/react-native-training/react-native-elements/blob/master/src/tile/Tile.js , this is a problem in the master :()

**Comment by binoy14** [comment]
@rjpounder what version of react native was this introduced. I tried searching for your suggestion in the docs but couldn't find anything. Can you maybe provide some links with the resources, that would be a great help.

**Comment by rjpounder** [comment]
https://github.com/facebook/react-native/commit/9637dd4a1b78d5f6da510b1b4ad10d45d67badbf

**Comment by duclt47** [comment]
you can show ImageBackground component ?
