### ISSUE TITLE
Ripple on the Button

### ISSUE THREAD

**Issue by maheshgupta** [react-native-training/react-native-elements#474]
Hi, Im trying to use the Button, but the Ripple is not restricted to the button and the ripple is crossing the button. Please find the attached image and let me know if there is any setting required.
![screenshot-1499575070372](https://user-images.githubusercontent.com/1017914/27991280-1e688542-6437-11e7-84ee-a429e6b0a792.jpg)

Thanks

**Comment by xavier-villelegier** [comment]
@maheshgupta It is probably a styling issue, can you reproduce this on https://snack.expo.io/ or post your code here ?

**Comment by filippofilip95** [comment]
I had same behavior, then i checked Button docs https://react-native-training.github.io/react-native-elements/API/buttons/.
**borderRadius note** 
> adds border radius to button (optional) (Note: if you set this, don't forget to also set borderRadius to containerViewStyle prop, otherwise unexpected behaviour might occur)

Example and workaround: https://snack.expo.io/SJqXQK-u-

**Comment by maheshgupta** [comment]
@filippofilip.. Thanks for the help.

**Comment by steven-ferrer** [comment]
I experienced the same behavior as described in the issue.

I fixed it on my end by setting the height of the button:

`<Button title='Yey!' buttonStyle={{ height: 45 }}/>`
