### ISSUE TITLE
Missing images in docs

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#476]
Header - https://react-native-training.github.io/react-native-elements/API/header/
Slider - https://react-native-training.github.io/react-native-elements/API/slider/
Swipedeck - https://react-native-training.github.io/react-native-elements/API/swipedeck/

**Comment by Monte9** [comment]
@iRoachie check again! 😉 

Yeah, this was fixed by @filiphosko in the previous release. See this https://github.com/react-native-training/react-native-elements/commit/edd7b4d2df34db0c43f308f5a8dc066d1033aa6b

Thanks for the issue tho. 👏

**Comment by iRoachie** [comment]
My bad! 😆 will check releases next ime
