### ISSUE TITLE
badge styling  not working  

### ISSUE THREAD

**Issue by yash2code** [react-native-training/react-native-elements#478]
In the docs badge example is not working in sense of styling

**Comment by binoy14** [comment]
@yash2code could you please provide more information what exactly is not working. Screenshots will be very helpful

**Comment by keith527** [comment]
I meet the same problem.
```

    render(){

        return(
        <ScrollView style={{marginTop:50}}>

        <Badge
            value={3}
            textStyle={{ color: 'orange' }}
        />
        <Badge containerStyle={{ backgroundColor: 'violet'}}>
            <Text>User 1</Text>
        </Badge>

        <Badge onPress={() => {console.log('pressed')}} value="5" />

        <Badge component={TouchableNative} value={10} />

        </ScrollView>
        )

    }
```

but the result is:
<img width="321" alt="2017-07-11 2 33 12" src="https://user-images.githubusercontent.com/10461842/28053929-9eee2130-6645-11e7-80be-ad04ddb17e2d.png">

**Comment by yash2code** [comment]
![whatsapp image 2017-07-11 at 12 08 21](https://user-images.githubusercontent.com/20199248/28054289-f9486226-6631-11e7-8a36-865be9a63d10.jpeg)

here is my code: 

```javascript
<ListItem
                      badge={{ value: 3, badgeTextStyle: { color: 'red' }, badgeContainerStyle: { paddingLeft:0, marginTop: 10, color:'orange' } }}
                      roundAvatar
                      title={`${item.name.first} ${item.name.last}`}
                      titleStyle={{ paddingLeft:50 }}
                      switchButton={true}
                      subtitle={item.email}
                      subtitleStyle={{ paddingLeft:50 }}
                      leftIcon={
                        <TouchableOpacity onPress ={ () => this._showModal()  }>
                        <Avatar
                        large
                       // onPress ={ () => this._showModal()  }
                        rounded
                        source={{ uri: item.picture.thumbnail }} 
                       containerStyle={{ flex:4, marginLeft:0 }}
                         />
                         </TouchableOpacity>
                             }
                    
                      containerStyle={{borderBottomWidth: 0, padding:0, paddingLeft:0 }}
                    />
```

**Comment by cubehouse** [comment]
Looking through the commit history, I found this change: https://github.com/react-native-training/react-native-elements/commit/45b02f92691f8db78ce4f00c1ccc760cdd72bbb6

The documentation for the Badge component was updated, but not for the ListItem.

To fix this, replace "badgeContainerStyle" with "containerStyle" and "badgeTextStyle" with "textStyle".

I'll pull request with a documentation fix when I get a sec.

**Comment by binoy14** [comment]
Thanks @cubehouse for the fix, hopefully this helps. Closing this but if you still have an issue feel free to open it again.

**Comment by PavelPolyakov** [comment]
I don't get it as well, how to display `Badge` with normal, not `100%` width? Just copied the code from the freshest documentation and I receive this:
![image](https://user-images.githubusercontent.com/839290/43609416-35d2b806-96a4-11e8-98fb-52ea5b955ac3.png)
while I want to receive this:
![image](https://user-images.githubusercontent.com/839290/43609421-3da1e58e-96a4-11e8-84d5-d62d343ee668.png)
