### ISSUE TITLE
[FormInput] font size is changing

### ISSUE THREAD

**Issue by anishclarion** [react-native-training/react-native-elements#480]
When we are changing the font size in the android/ios devices it is changing the element font size in our app, is there any way to prevent that, I have used Text.defaultProps.allowFontScaling=false; but it is not working on FormInput components.

**Comment by anishclarion** [comment]
Please suggest some solution.

**Comment by binoy14** [comment]
Cc @monte9 any ideas?

**Comment by anishtr4** [comment]
Guys any solution ?

**Comment by iRoachie** [comment]
@binoy14 @anishtr4 I don't think there's an easy way to get around this. The problem is that we use a normalize function https://github.com/react-native-training/react-native-elements/blob/master/src/helpers/normalizeText.js to smartly calculate the font size based on screen size and pixel density

**Comment by anishtr4** [comment]
@iRoachie  Is there any way to remove/prevent this for a specific input/Form fields ?

**Comment by iRoachie** [comment]
@anishtr4 I'm thinking around making a `normalizeFontSize` prop, in which you can set to false.

**Comment by anishtr4** [comment]
@iRoachie I will be great if you can add this feature ASAP, As we are in a critical condition :(

**Comment by iRoachie** [comment]
@anishtr4 You can try it out now on the next branch. Change your package.json to use 
`"react-native-elements": "https://github.com/react-native-training/react-native-elements.git#next"`

Set the `normalizeFontSize={false}`

**Comment by anishtr4** [comment]
@iRoachie  Thank you , I will try it out, Hope you will not remove the branch in future.

**Comment by iRoachie** [comment]
@anishtr4 If it works, then it'll be merge into the main branch for everyone to use

**Comment by anishtr4** [comment]
@iRoachie  Will let you know by EOD .

**Comment by Monte9** [comment]
@anishtr4 any updates?

**Comment by Monte9** [comment]
We released `v0.16` since author's last reply. If this is still an issue, feel free to report it or reopen this issue.

**Comment by idws** [comment]
is there any updates about this issue?

**Comment by Monte9** [comment]
@idws yes, this has been merged into master and is available to use. As @iRoachie described, just pass in `normalizeFontSize={false}` and it should work. 

Keep in mind that as of now, this is experimental and has only been supports the `FormInput` component
