### ISSUE TITLE
<Tile> onPress fired with a loooooong delay (after 3 or 4 second)

### ISSUE THREAD

**Issue by mnlbox** [react-native-training/react-native-elements#481]
I try render list of Tile components with a simple `map` like this:
```
renderTileList() {
        return this.state.magazineArchive.map((item,index) => {
            return (
                <Tile
                    key={index}
                    height={200}
                    width={width - 20}
                    icon={{name: 'newspaper-o', color: 'white', type: 'font-awesome'}}
                    imageSrc={{uri: item.ImageUrl}}
                    title={item.title}
                    titleStyle={[styles.englishText, {fontSize: 30}]}
                    featured
                    activeOpacity={0.7}
                    caption={item.subTitle}
                    captionStyle={[styles.englishText, {fontSize: 20}]}
                    onPress={() => {
                        console.warn("item.id = " + item.id);
                        // and then change page
                    }}
                />
            );
        });
    }
```
But onPress fired with a loooooong delay (after 3 or 4 second)
Please see delay between when I tap on Tile and when you see `console.warn("item.id = " + item.id);` output in below gif:
![tilepressdelay](https://user-images.githubusercontent.com/25859075/28109774-7e1330c0-6705-11e7-8db9-79cce5aa6fb5.gif)

And also this is my packages version:

```
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-elements": "^0.13.0",
```

**Comment by mnlbox** [comment]
Maybe related to #395 , #408

**Comment by mnlbox** [comment]
I found a very interesting note: If I start "Remote JS Debugging" long delay gone. Why this happens? How to fix this completely?

**Comment by mnlbox** [comment]
@Monte9 have you any suggestion?

**Comment by binoy14** [comment]
@mnlbox how many times do you have in the map? I will try to recreate it with similar number

**Comment by Monte9** [comment]
@mnlbox yes, you are right. This occurs when you turn on remote debugging. 

The effect is most prominent on Android. And I have run into this myself, especially when doing animations. This is more of a React Native framework issue than RNE.

**Comment by kanteankit** [comment]
@Monte9  Hi I am using react-native-elements ^1.0.0-beta2 and I am facing this problem with Button element. Even after building the app using 'exp build:android' and creating an apk of the app, this issue persists. The onPress event is fired after a long delay.
The remote JS debugging thing that @mnlbox is also happening.

**Comment by Monte9** [comment]
Hey @kanteankit! Can you please open a new issue for it. Thanks

**Comment by kanteankit** [comment]
Hi @Monte9 Already created it. #907
