### ISSUE TITLE
Updates dependencies for deprecated prop-types

### ISSUE THREAD

**Issue by DrPandemic** [react-native-training/react-native-elements#486]
### Description
1. Trying the new react.16.x.alpha.
2. Be able to run my tests.
3. Some packages used by `react-native-elements` throw errors. I'm using `^0.14.0`.

### Reproduction Steps and Sample Code
I'm using a `List` and `ListItem` in a component and I receive this error when importing it. I'm not sure the link between the `List` and the tab...
```
at Object.<anonymous> (node_modules/react-native-side-menu/index.js:243:29)
at Object.<anonymous> (node_modules/react-native-elements/src/sidemenu/SideMenu.js:1:172)
at Object.<anonymous> (node_modules/react-native-elements/src/index.js:14:15)
```
or
```
at Object.<anonymous> (node_modules/react-native-tab-navigator/StaticContainer.js:19:114)
at Object.<anonymous> (node_modules/react-native-tab-navigator/TabNavigator.js:14:22)
at Object.<anonymous> (node_modules/react-native-elements/src/tabs/Tabs.js:1:176)
```

### Solution
I had 2 errors related to packages having issues with prop-types. So far, I was able to identify `react-native-tab-navigator` and `react-native-side-menu`.

For `react-native-tab-navigator` there's this [opened PR](https://github.com/happypancake/react-native-tab-navigator/pull/152) that's fixing it. For `react-native-side-menu`, there's already [a commit](https://github.com/react-native-community/react-native-side-menu/commit/173accea508cfff72261c6a5e2c77abdd5444a85) that's fixing it, but it's currently part of a release.

**Comment by flaviocarvalho** [comment]
I'm getting the same errors.

**Comment by Monte9** [comment]
@DrPandemic @flaviocarvalho the version for Side Menu has been updated on the latest release `v0.16.0`. 

But as for `tab-navigator` please use @luugiathuy's fork as he suggested above. Thanks for the fix @luugiathuy's

Also fyi, both of these components are deprecated as of `v0.15.0` in favor of using `react-navigation`.
