### ISSUE TITLE
React Native: Usage ListItem has an error 10534 Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled.

### ISSUE THREAD

**Issue by namphuongtran** [react-native-training/react-native-elements#487]
Hi, I use React Native Element lib, when i create a list view usage List and ListItem component i got an error some time such as: 10534 Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled.
This error occur when i click to List Item. Thus i research on internet i saw this issue is the same "https://github.com/facebook/react-native/issues/11989". i go to react native element lib and read code i see the libs still use TouchableHighlight. Could you change TouchableHighlight to TouchableOpacity in lib?
Thanks!
Anyone get same error like me?

**Comment by pewh** [comment]
I have same issue, but on Button. I throw an error on my Sony Ultra Z (Lollipop), but it's work on other android device like Jelly Bean & Nougat. I didn't have any clue :/

**Comment by Monte9** [comment]
@namphuongtran @pewh this is strange. I don't think this is related to RNE per say but might be one-off's coming from the `Touchable***` components in React Native. 

Is this still an issue? Or were you able to find a solution to this?

**Comment by Devikaelangovan** [comment]
I am also facing the same issue

**Comment by Monte9** [comment]
This seems to only happen in some specific Android devices with remote debugging on. This solution looks promising: https://github.com/facebook/react-native/issues/11989#issuecomment-314111441

This does not seem to be coming directly from RNE. Please follow [this thread](https://github.com/facebook/react-native/issues/11989#issuecomment-314111441) on the RN repo for the lastest on this issue.

**Comment by gino8080** [comment]
Solved using [React Native debugger](https://github.com/jhen0409/react-native-debugger) instead of plain Chrome window

**Comment by donni106** [comment]
@gino8080 this also happens with React Native Debugger

**Comment by tuananhcwrs** [comment]
Hello,

I've got the same issue.

And as far as I understand, people keep saying that it is only a "DEBUG" issue. Means it does not happen in production.

However I am facing a problem that my app randomly crashes, so I am trying to see if it is one of the root cause. Means not just only a DEBUG issue?

Any advice?
