### ISSUE TITLE
Couple of issues in button

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [react-native-training/react-native-elements#493]
Hi I am new to React-Native, I was trying to do

1.  Stretch the button to available space using flex.
  The button is not getting stretched no matter what I do, I tried using `alignSelf:'stretch'` `flexDirection:'row'` none works.
2. Adding a vector facebook icon to the button using vector name: 'facebook'.
3. Adding a radius to the button which is in the raised state.
  When I add a raised prop and radius style to the button it gives me a transparent rectangle shape below the button.

Here is the code I was using:

```
import React, { Component } from 'react';
import { StyleSheet, Text, View, Image, TextInput } from 'react-native';
import { Button, SocialIcon } from 'react-native-elements';

class Login extends Component {
  constructor() {
    super();
    this.state = {
      email: '',
      password: ''
    }
  }

  render(){
    return (
      <View style={styles.container}>

        <Image
          style={styles.logoContainer}
          source={ require('../img/login.png') }
        />
        <TextInput
          style={[styles.textInputStyle, { marginTop: 40 }]}
          placeholder="Email"
          onChangeText={(email) => this.setState({email})}
        />
        <View style={[styles.dividerColor, { marginBottom: 25 }]} />
        <TextInput
          style={styles.textInputStyle}
          placeholder="Password"
          onChangeText={(password) => this.setState({password})}
        />

        <View style={[styles.dividerColor, { marginBottom: 30 }]} />

        <Button
          large
          buttonStyle={styles.loginButtonStyle}
          backgroundColor='#EA4265'
          title='Login' />

        <Button
          large
          iconLeft
          icon={{name: 'facebook'}}
          title='LARGE WITH RIGHT ICON' />

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#e4e4e4",
    borderRadius:5,
    margin: 20,
    justifyContent: 'center',
    alignContent: 'center',
    flexDirection: 'column',
    alignItems: 'center'
  },
  textInputStyle: {
    height: 40,
    marginLeft: 15,
    marginRight: 15
  },
  dividerColor: {
    alignSelf: 'stretch',
    height: 1 ,
    backgroundColor: '#e4e4e4',
    marginLeft: 15,
    marginRight: 15
  },
  loginButtonStyle: {
    borderRadius: 5,
    flexDirection: 'row',
    alignSelf: 'stretch'
  }
});

export default Login;

```
Tested device:

Iphone 7 iOS 10.3 (Simulator)

react-native-elements version: 0.14.0

Can anyone please help me with it?

**Comment by iRoachie** [comment]
Hey @jeffreyrajanofficial Thanks for the report. 

1. If you want the want to change the width of the button you have the use the `containerViewStyle` prop instead of buttonStyle. 

2. The `icon` prop takes in an object of `name, type, color, size`. By default if you don't specify the `type` then it'll default to a MaterialIcon and there isn't a "Facebook"  Material icon. [Here's a list](https://oblador.github.io/react-native-vector-icons/) of all the icons we allow.

Font Awesome has a facebook icon. `icon={{name: 'facebook', type: 'font-awesome'}}`

3. This one is a bug, and it'll be fixed in the next release

**Comment by jeffreyrajanofficial** [comment]
Thanks @iRoachie  :)
