### ISSUE TITLE
SwipeDeck suggestion

### ISSUE THREAD

**Issue by nonotest** [react-native-training/react-native-elements#496]
Hello, 

the other popular swipe deck component (https://github.com/meteor-factory/react-native-tinder-swipe-cards) has this really useful feature called "loop".

it works great if you want to keep looping through the cards when you are done looking at the cards in current deck.

should simply be a matter of something like (not tested)

```
onSwipeComplete(direction) {
    const { onSwipeRight, onSwipeLeft, data, loop } = this.props;
    const item = data[this.state.index];

    direction === 'right' ? onSwipeRight(item) : onSwipeLeft(item);
    this.state.position.setValue({ x: 0, y: 0 });
    this.setState((prevState) => {
      const nextIndex = prevState.index++;
      if (loop && nextIndex >= this.props.data.length) {
        return {
          index: 0
        }
      } else {
        return {
          index: nextIndex
        }
      }
   })
  }
```

i can submit a pr if interested, or just copy and test this code

**Comment by iRoachie** [comment]
Hey @nonotest we deprecated the SwipeDeck component in the [last release](https://github.com/react-native-training/react-native-elements/releases/tag/v0.15.0) and now it's development is happening in another repo. I suggest you open the issue at that repo instead so it can be added in. https://github.com/Monte9/react-native-tinder-cards

**Comment by nonotest** [comment]
Ahh gotcha didn't see the deprecation.
