### ISSUE TITLE
Form Label font wont change

### ISSUE THREAD

**Issue by yeknava** [react-native-training/react-native-elements#498]
### Description

1. Explain what you did
Add fontFamily prop to FormLabel component
```JSX
<FormLabel labelStyle={styles.label} fontFamily='myfont'>{this.props.label}</FormLabel>
```
2. What you expected to happen
Label fonts change
3. What actually happens
Nothing happened, i tried with both bold and light fonts. my font is ttf format and it is working on other RN components, its even work on FormValidationMessage.

RN 46.2, RE 0.14, Android 7

**Comment by iRoachie** [comment]
@yeknava Hey could you tell me what font you were trying to apply? I can't reproduce this locally. Where you using create-react-app or normal react-native init?

**Comment by yeknava** [comment]
@iRoachie hey, its a unicode compatible font (persian font) and yes i used react-native init.
again as i said my font works well with FormValidationMessage.

**Comment by iRoachie** [comment]
@yeknava Can you upload your project to GitHub so I could take a look? I just did some tests on FormLabel and the font family changes.

**Comment by yeknava** [comment]
@iRoachie i found the bug. after i removed [this line](https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormLabel.js#L57) everything works.
btw, a hackish solution that also works is:
```jsx
<FormLabel
	labelStyle={{fontWeight: '300'}} fontFamily='myfont'>{this.props.label}</FormLabel>
```

**Comment by binoy14** [comment]
@yeknava The reason for that is probably because the font you are using does not support the fontWeight option and due to that reason it is not changing. You don't want to edit node_modules as it will get reverted on running npm install, rather I would suggest labelStyle prop everywhere you are using FormLabel. Hope that helps

**Comment by yeknava** [comment]
@binoy14 yes i think so, btw i tried with roboto and droid sans fonts too but neither work. thank you yes i use fontWeight option in label style as primary solution.

**Comment by binoy14** [comment]
@yeknava I tried with robot and other fonts and it seemed to work on both Android and iOS

**Comment by yeknava** [comment]
@binoy14 maybe it just happens on my setup (RN 46.2, RE 0.14, Android 7)

**Comment by palakvc** [comment]
Same issue I'm facing.

I try to load Merriweather-Bold as Form Label but not working where It's working well with Form Input

**Comment by iRoachie** [comment]
Please create a new issue and follow the issue template.
