### ISSUE TITLE
SearchBar observations

### ISSUE THREAD

**Issue by arunreddyj** [react-native-training/react-native-elements#501]
1. SearchBar "clearIcon" is shown by default. Even though there is no search text. in iOS, clearIcon should be shown only if there is search text to clear ( Thats the behavior in all apps )
2. Is there a way to center align search icon & place holder text? And on focus, move the alignment to left. That seems to be the pattern in all iOS apps.

Version: 0.13.0

**Comment by iRoachie** [comment]
This sounds like a cool idea to implement, should it only behave this way on iOS or on android as well?

**Comment by Monte9** [comment]
@arunreddyj good observations. You will be happy to know that for our `1.0` release, we are going to be focusing on platform specific details as to make this library "more" production ready. 

I am going to be rewriting the `Search` components soon and i'll keep these details on mind for sure. 

Closing this issue as I don't think these enhancements are going to be merged into any `v0.xx.0`, but I'll be sure to add them on `v1.0` which will be out by mid-September.
