### ISSUE TITLE
 View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

### ISSUE THREAD

**Issue by ShailajaV** [react-native-training/react-native-elements#502]
I am using the following versions in my app
"react": "^16.0.0-alpha.12",
"react-native": "^0.46.2",
"react-native-elements": "^0.14.0"

After i install react-native-elements i.e. npm install --save react-native-elements getting following errors.
Error1: 
 **View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.**

This error is coming from below the line 
**react-native-elements\src\badge\badge.js:56**.

Error2:

**PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead.**

This error is coming from the below line
**\node_modules\react-native-elements\node_modules\react-native-side-menu\index.js:243**

For this issue, I would suggest use latest version of react-native-side-menu@1.0.2  mostly issue might resolve.

Could you please help me on this.

**Comment by iRoachie** [comment]
Hey @ShailajaV thanks for filing an issue. We have it fixed and it'll be shipping in the next release.

**Comment by peacechen** [comment]
Also getting this from TabNavigator.

Tabs.js line 3:
```import TabNavigator from 'react-native-tab-navigator';```

react-native-tab-navigator -- Tab.js:
```
'use strict';
import React, {
  PropTypes,
} from 'react';
import {
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

import Layout from './Layout';

export default class Tab extends React.Component {
  static propTypes = {
    testID : PropTypes.string,
    title: PropTypes.string,
    titleStyle: Text.propTypes.style,
    badge: PropTypes.element,
    onPress: PropTypes.func,
    hidesTabTouch: PropTypes.bool,
    allowFontScaling: PropTypes.bool,
    style: View.propTypes.style,
  };
```

**Comment by iRoachie** [comment]
@peacechen The warnings will still show. Even though we deprecated the Tab, Tabs component, we're still referencing it as an dependency for our package. We don't want to remove a component someone might be using in production so deprecating is a way of giving them a notice. In a future release we'll remove it completely, so we won't have that problem.

**Comment by peacechen** [comment]
Since react-native-tabs-navigator has [updated ViewPropTypes in the 0.3.4 release](https://github.com/happypancake/react-native-tab-navigator/pull/152), would you mind updating the dependency to that version?  I still find TabNavigator useful within a route and hope it remains in react-native-elements.  `react-navigation` doesn't obsolete it since they can be complementary.

**Comment by iRoachie** [comment]
Yea, it only was released this morning. I'll do it later today

**Comment by peacechen** [comment]
What are your thoughts on keeping Tabs in RNE?

> YellowBox.js:76 Warning: Tabs has been deprecated and will be removed in a future version of React Native Elements. For a complete navigation solution that includes Tabs as well as many other features, be sure to check out react-navigation (https://reactnavigation.org) and it's TabRouter.

TBH, `react-navigation` is a convoluted mess and difficult to migrate to.  In my use case all I need is a simple tab selector within an existing route.  Using react-navigation's TabNavigator would entail embedding a router within a router, adding even more complexity to `react-navigation`.

**Comment by iRoachie** [comment]
Nothings wrong with wanting a simple tab selector, in your case you probably don’t even need a library to do that. You can still install react-native-tab-navigator and use it standalone if you want. However react-navigation is a much better all round solution for navigation, especially when padding data between screens.
