### ISSUE TITLE
Can't install react-native-vector-icons@4.2.0

### ISSUE THREAD

**Issue by MichaelSzer** [react-native-training/react-native-elements#506]
UNMET PEER DEPENDENCY react-native-vector-icons@4.2.0

**Comment by binoy14** [comment]
@MichaelSzer did you run npm install react-native-vector-icons and react-native link react-native-vector-icons? Unmet peer dependency doesn't necessarily mean you were not able to install it.

**Comment by MichaelSzer** [comment]
Yes, I have noticed that. Despite the warnings, it works. Thanks!
