### ISSUE TITLE
ListItem TextInput placeholder support

### ISSUE THREAD

**Issue by lax1n** [react-native-training/react-native-elements#509]
### TextInput in ListItem should support placeholders

Using `"react-native-elements": "^0.14.0"`

1. Tried adding a placeholder to a `ListItem` with `textInput={true}`
2. Expected a placeholder to appear on the right side in the list item.
3. No placeholder appears.

### Reproduction Steps and Sample Code

Following the already established naming convention I attempted to add a placeholder to the `ListItem`:
`<ListItem title='ListItem with Placeholder' textInput={true} textInputPlaceholder='Placeholders are helpful' />`

I've gone through the source code and it appears this is simply a missing feature as `TextInput` does actually support placeholders.

### Solution

UPDATE: Created a PR #512 which should solve this issue.

https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js

Between line 194 and 211 adding a line such as `placeholder={textInputPlaceholder}` as well as adding `textInputPlaceholder` to the propTypes and props lists.

**Comment by Monte9** [comment]
This has been fixed and will be part of the `v0.16.0` release. Thanks @lax1n for the issue & the fix. 👍
