### ISSUE TITLE
Add Ability disable SelectedIndex in ButtonGroup

### ISSUE THREAD

**Issue by acahir** [react-native-training/react-native-elements#510]
### Description

Add a bool prop to disable the Touchable container for the currently selected button.

This allows for a more accurate reproduction of SegmentedControlIOS highlighting during onPress and avoids possibly unnecessary reloads.

Pull Request to follow.

v0.15.0

### Solution

PR to Follow

**Comment by Monte9** [comment]
@acahir thanks for the issue followed by a PR for it too. 👏 

Closing this now as it's been merged into `next` and will be release with `v0.16.0` in the next week.
