### ISSUE TITLE
Add ButtonGroup option to ListItem

### ISSUE THREAD

**Issue by acahir** [react-native-training/react-native-elements#513]
### Description

Extend ListItem with option to include a ButtonGroup on right side, modeled after Switch. Useful for quick 2-3 option selections instead of opening action menu or a new screen. 

Example image:
![listitem buttongroup](https://user-images.githubusercontent.com/1418251/28492432-beb3f744-6ed1-11e7-8d97-0c89709a1878.png)

Wondering if this functionality is desired for inclusion, if so will submit PR.

Created against v0.15.0

### Sample Code

Example code for iOS style ListItem with ButtonGroup:

    <ListItem
      containerStyle = {{paddingTop: 2, paddingBottom: 2}}
      wrapperStyle = {{marginLeft: 5}}
      title = "ListItem with ButtonGroup"
      subtitle = "Subtitle Example"
      titleNumberOfLines={0}
      buttonGroup
      buttonGroupButtons = {['Yes', 'No']}
      buttonGroupContainerStyle = {{marginRight: 0, marginLeft: 0, height: 30, width: 66, backgroundColor: 'white', borderColor: '#007aff', borderRadius: 5}}
      buttonGroupContainerBorderRadius = {3}
      buttonGroupTextStyle = {{color: '#007aff'}}
      buttonGroupButtonStyle = {{width: 32}}
      buttonGroupSelectedBackgroundColor = {'#007aff'}
      buttonGroupSelectedTextStyle = {{color: 'white'}}
      buttonGroupInnerBorderStyle = {{color: '#0071ff'}}
      buttonGroupComponent = {TouchableHighlight}
      buttonGroupActiveOpacity = {0.9}
      buttonGroupUnderlayColor = {'#D9EBFF'}
      buttonGroupDisableSelected
      buttonGroupSelectedIndex = {selectedIndex}
      onButtonGroupChange = {onButtonGroupChange}
      hideChevron
    />

### Solution

Already completed a functional solution. Like with textInput there are a significant number of props to include for full functionality. 

Wanted to see if this functionality is desired before submitting a PR.

**Comment by binoy14** [comment]
Adding the Full buttonGroup api as props is not a good idea, Instead having a prop such as rightComponent where you can pass in a custom component is more extendable.

With just button group
```
<ListItem
  rightComponent={<ButtonGroup {...} />}
/>
```

With button group and a badge

```
<ListItem
  rightComponent={
    <View>
      <ButtonGroup {...} />
      <Badge {...} />
    </View>
  }
/>
```

Doing this is more extendable and more maintainable. I believe @Monte9 is working on rewriting the ListItem component. Coordinate with him on this

**Comment by iRoachie** [comment]
Planned for v1 @binoy14

**Comment by acahir** [comment]
Yea seemed like there might be a better solution, that's why I asked vs just submitting a PR. The props list is already quite long. Thanks for the response, and all the work on the module.

@Monte9 Not sure what the current status is, but let me know if there's something I could help with.

**Comment by iRoachie** [comment]
@acahir No one has started on it as yet, so you're free to chime in.

**Comment by acahir** [comment]
Started looking at this...if going that way then Switch, Chevron could (should?) be implemented in the same way to be consistent. 

Question then becomes what balance between ease of implementing functionalities and extendability. i.e. Currently adding a switch or chevron are very simple, but creating/styling components to work will never be as straightforward. 

What I'd propose would be create the extendable framework but also include a few common defaults for easy implementations.

**Comment by Monte9** [comment]
@acahir that's a good idea. Def agree that there should be a balance between ease of use & extendability. It's good to know that you are already thinking along those lines. 😉 

So in case you are not aware, we are working on RNE 1.0 and you can checkout all the lastest work for it on the `v1` branch. 

The `ListItem` component will def be going through a big refactor and it's ok to change the API for it in order to clean up the component and make it more functional. Seem like this might be something you would be interested in, to have the freedom to make changes, and also improve the ListItem component with ButtonGroup & other enhancements. 

I'd love it collaborate with you on this if you have the time + are interested in doing this. Let me know. Also there are Open Collective $$ to helping with RNE. So your efforts will be rewarded as well.

**Comment by xavier-villelegier** [comment]
@acahir `v1.0.0-beta4` is out with a rewritten `ListItem` 🎉
Check out [the docs](https://react-native-training.github.io/react-native-elements/docs/listitem.html) and [the release notes](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta4)
