### ISSUE TITLE
Header component rendering properly?

### ISSUE THREAD

**Issue by abartolo** [react-native-training/react-native-elements#515]
### Description
Hello,

I am using ReactNavigation to handle the navigation of my app. For certain screen I need to make a custom header as Drawer Navigation does not render a header with a menu icon. In order to handle that I planned on using React-Native-Elements Header component to fit this missing feature I need.

However when I add the following component it does not push the content below it down. Instead content is laying over the header.

Am I doing something wrong?
**Code**
`
 <View>
`

`
            <Header
                statusBarProps={{ barStyle: 'light-content' }}
                centerComponent={{ text: 'Dashboard', style: { color: '#fff' } }}
                outerContainerStyles={{ backgroundColor: '#324C66' }}
            />
`

`               
<PricingCard
                    color='#4f9deb'
                    title='Dashboard'
                    price='$0'
                    info={['1 User', 'Basic Support', 'All Core Features']}
                    button={{ title: 'GO TO LOGIN', icon: 'flight-takeoff' }}
                    onButtonPress={() => this.toLogin()}
                />
`

`               <Button
                    raised
                    icon={{ name: 'cached' }}
                    title='Open Navigation'
                    onPress={() => this.openNav()}
                />
`

`
            </View>
`
**Issue Image**
![image](https://user-images.githubusercontent.com/5394228/28493679-03505de0-6ee9-11e7-8cef-a82891f96b80.png)

Version of `react-native-elements` that you are using: ^0.14.0

**Comment by Ranlevi** [comment]
Same issue here. I try to place a text below the header - but it ends up above it. This is the code:

`  <View>
        <Header 
          backgroundColor={'green'}
          leftComponent={<Icon 
                            name="menu" 
                            color="blue" 
                            onPress= {()=> this.props.navigation.navigate('PodcastsRoute')} 
                          />
                        }
          centerComponent={{ text: 'Episodes', style: { color: 'blue' } }} 
          rightComponent={{ icon: 'home', color: '#fff' }}
        />
        <Text>JJ</Text>
        </View>
`

**Comment by iRoachie** [comment]
@Ranlevi Hey! You don't need to use RNE Header to display a menu button with react navigation. You can actually pass in your icon in the headerRight property

```js
Dashboard: {
      screen: Dashboard,
      navigationOptions: ({ navigation }) => ({
        title: 'Dashboard',
        headerLeft: (
          <NavButton
            onPress={() => navigation.navigate('DrawerOpen')}
            iconName="menu"
          />
        ),
      }),
    },
}
```

**Comment by iRoachie** [comment]
In my example above `NavButton` is just a custom component I made with a `<TouchableOpacity>` with an `<Icon>` inside

**Comment by Ranlevi** [comment]
@iRoachie Thanks! I'll try it out :-)

**Comment by abartolo** [comment]
@iRoachie Thanks for the reply. I tried adding an icon to render for the headerLeft but it did not work. I don't think headerLeft is a valid option within a drawer navigation stack. Please find the code below.

In regards to why the header component isn't pusing content down, is there something I am missing or is that how it is supposed to work?

```javascript
const TeamsNavigator = StackNavigator(
    {
        Teams: { screen: TeamsPage },
        EditTeam: { screen: EditTeamPage },
    }, {
        headerMode: "screen",
        mode: "card",
    }
);
const MainSceenNavigator = DrawerNavigator({
    Dashboard: {
        screen: DashboardPage,
        navigationOptions: ({ navigation }) => ({
            title: 'Dashboard',
            headerLeft: (
                <Icon
                    name={'menu'}
                    color={'#ffffff'}
                    underlayColor={'#324C66'}
                    onPress={() => this.openDrawer()} />
            ),
        }),
    },
    Teams: {
        screen: TeamsNavigator
    },
    Account: {
        screen: AccountPage
    }
});
const App = StackNavigator(
    {
        Login: {
            screen: LoginPage
        },
        Dashboard: {
            screen: MainSceenNavigator
        }
    }, {
        headerMode: "none",
        mode: "card",
        initialRouteName: "Dashboard"
    }
);

**Comment by iRoachie** [comment]
Sorry I guess I wasn't being clear. For this to work Dashboard has to be in a StackNavigator.

So setup your drawer like normal
```js
import Dashboard from '../pages/Dashboard'
import Campaigns from '../pages/Campaigns'
import Billing from '../pages/Billing'
import Support from '../pages/Support'
import Account from '../pages/Account'


export default DrawerNavigator(
  {
    Dashboard: {
      screen: Dashboard,
    },
    Campaigns: {
      screen: Campaigns,
    },
    Billing: {
      screen: Billing,
    },
    Support: {
      screen: Support,
    },
    Account: {
      screen: Account,
    },
  },
}
```

Then in my `Dashboard` file

```jsx
export default StackNavigator(
  {
    Dashboard: {
      screen: Dashboard,
      navigationOptions: ({ navigation }: NavigationScreenConfigProps) => ({
        title: 'Dashboard',
        headerLeft: (
          <NavButton
            onPress={() => navigation.navigate('DrawerOpen')}
            iconName="menu"
          />
        ),
      }),
    },
  },
  {
    navigationOptions: Theme.navigationOptions,
  }
)
```

**Comment by abartolo** [comment]
@iRoachie Thanks for the detailed explanation. I rearranged my navigation to go Stack>Drawer(Inside all stacks) and it worked perfectly. Now I just have to make the headerLeft Menu button look stylish.

Thanks again for the help I appreciate it.

**Comment by iRoachie** [comment]
Sure thing mate! Enjoy!
