### ISSUE TITLE
Rating background color doesn't work properly. [bug]

### ISSUE THREAD

**Issue by mr-bat** [react-native-training/react-native-elements#517]
when using background color in rating component it only fills inside of the pictures with the provided color and so, the real background (surrounding of the pictures) would be unchanged.

This case happened to me in the code below
`<Ratin
  type='custom'
  ratingBackgroundColor='red'
  showRating
  imageSize={30}
  onFinishRating={this.ratingCompleted}
  style={{ paddingVertical: 10 }}
/>`
I want to use the default picture (stars), but with custom background color but only the inside of the stars would be red.
[demo](http://uploads.im/09hyN.png)
react-native-elements v0.15.0

**Comment by iRoachie** [comment]
Hey @mr-bat You can use the `style` prop and set the background color there.

```jsx
<Rating type='custom' ratingBackgroundColor='red' showRating imageSize={30} style={{ paddingVertical: 10, backgroundColor: 'pink' }} />

```

**Comment by mr-bat** [comment]
actually, it doesn't solve the problem. because the module creates copies of an image which has a transparent center (in this case the stars). I solved my problem with merely creating another image from the resources and changed the surroundings of the star!

**Comment by Monte9** [comment]
@mr-bat that's the right way to do it. Good job figuring it out. 👏 

When I wrote the `Rating` component initially, this was kind of a hack that I had to come up with. And I didn't think anyone would need to override it other than advanced users. So I am glad you figure it out.

**Comment by MaxInMoon** [comment]
@mr-bat can you provide an example??

**Comment by mr-bat** [comment]
![staremptycurved](https://user-images.githubusercontent.com/16259723/37649313-9ab3556e-2c46-11e8-82a1-5238ab11c717.png)

This is what I came up with.

**Comment by mathewtd87** [comment]
I don't see how changing the color from the default white around the stars is only something advanced users would need.
Is this still unchangeable??

**Comment by lyahyaoui** [comment]
I don't understand why this bug is closed without giving any solution to the probleme !!! Neither Background color or text color are working ! such a garbage component!!!
