### ISSUE TITLE
Button raised creates card like view below button - Android

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [react-native-training/react-native-elements#518]
Hi I am using the latest version of react-native-elements (0.15.0), I tried to add raised props to the button it works perfectly in iOS but when it comes to android it creates a card like view behind the button. Here's the code I am using 

```
<Button
   large
   raised
   fontWeight='bold'
   buttonStyle={styles.loginButtonStyle}
   backgroundColor='#EA4265'
   onPress={() => this.props.navigation.navigate('home')}
   title='Login' />
```
The result I am getting in Android device

<img width="396" alt="screen shot 2017-07-23 at 7 43 47 pm" src="https://user-images.githubusercontent.com/16349497/28500085-708a790c-6fe0-11e7-91fe-6a0307795d95.png">

**Button style**

```
loginButtonStyle: {
    borderRadius: 5,
    marginRight: 20,
    marginLeft: 20
  }
```
Tested device 

iPhone 7 - works perfectly
Samsung s5 - getting the result like the above image

**Comment by xavier-villelegier** [comment]
Hey @jeffreyrajanofficial, if you test on Expo Snack, it is the opposite, it works on Android but not iOS 🤔 [see here](https://snack.expo.io/rkcKwNzIW)

But I managed to have a clean button on both platform by doing
```jsx
<Button
  large
  raised
  fontWeight='bold'
  buttonStyle={{borderRadius: 5}}
  containerViewStyle={styles.loginButtonStyle}
  backgroundColor='#EA4265'
  title='Login' />
```

**Comment by jeffreyrajanofficial** [comment]
Thanks @xavier-villelegier the example you have given here is working :)
