### ISSUE TITLE
SearchBar onChange not triggered once clicking on clearIcon

### ISSUE THREAD

**Issue by yghanem** [react-native-training/react-native-elements#525]
I added a SearchBar to a listView following the direction stated in the documentation

<SearchBar
        lightTheme
        textInputRef='searchActivity'
        onChangeText={this._searchActivity}
        clearIcon={this.state.searchClearIcon}
        placeholder='Search Activity...' />

onChange works if I am typing and deleting text using the keyboard, and if I click on the clearIcon the text gets cleared but the onChange functions doesn't get triggered. What is it that I am missing?

The following are the dependencies versions I am using

"dependencies": {
    "expo": "16.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-18.0.1.tar.gz",
    "react-native-elements": "^0.11.2",
    "react-navigation": "^1.0.0-beta.9"
  }

**Comment by iRoachie** [comment]
@yghanem Fixed in https://github.com/react-native-training/react-native-elements/pull/529/commits/d052d82ad5f7bf0dbc933ddff87e7bfd0d5a7b58#diff-62ae4c6f9cd461a92555a3324e6b6ec3. Will be available in next release

**Comment by iRoachie** [comment]
Feel free to repopen is issue, persists after version release
