### ISSUE TITLE
Switch react-native-vector-icons to peerDependency

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#526]
References https://github.com/react-native-training/react-native-elements/commit/681e9a344fe5f4889fb4f4931b6561ed9faf28c4#commitcomment-23316865

Also update installation docs

**Comment by Monte9** [comment]
@iRoachie I have added it as a peerDependency back again. [This is the commit that adds it.](https://github.com/react-native-training/react-native-elements/commit/7cd1af211ae823e429b0a8de0c31faa2f52436b7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

[peerDependency](https://yarnpkg.com/lang/en/docs/dependency-types/#toc-peerdependencies)

Also there is no need to update the docs as they are already up to date: https://react-native-training.github.io/react-native-elements/Installation/default_installation/

Closing this issue as this has been fixed on `next` and will be released with `0.16.0` soon.
