### ISSUE TITLE
CheckBox title propType should be PropTypes.any instead of PropTypes.string

### ISSUE THREAD

**Issue by j-francisco** [react-native-training/react-native-elements#527]
### Description

When using nested Text components for the title prop of CheckBox, I get a PropTypes warning because it expects only a string. The underlying TextElement component allows its children to be PropTypes.any, so shouldn't the CheckBox allow title to be PropTypes.any also?

I'm using version 0.12.2, although looking at the code this seems to apply still on the master branch.

### Reproduction Steps and Sample Code

```
const title = (
  <Text>
    <Text>By checking this box you agree to the </Text>
    <Text onPress={this.linkToTerms}>Terms and Conditions</Text>
  </Text>
);

<CheckBox title={title} ...otherProps />
```

### Solution
As long as I'm not missing something, I think you could just change the propType of `title` and `checkedTitle` to `PropTypes.any`.

**Comment by iRoachie** [comment]
@j-francisco Fixed in next release

**Comment by Monte9** [comment]
@iRoachie changing the props validation without handling the prop the right way in the render method is a bad idea. 

Please swing back to this before v0.16.0 to fix it or revert the changes and reopen the issue. Willing to help if needed.

**Comment by iRoachie** [comment]
@Monte9 Does this work better? https://github.com/react-native-training/react-native-elements/commit/771a00dbd500771aec08edeb2309d6e20472fe19

**Comment by Monte9** [comment]
@iRoachie yup. Thanks for the fix. 😉
