### ISSUE TITLE
Text not compatible with certain fonts

### ISSUE THREAD

**Issue by PolGuixe** [react-native-training/react-native-elements#528]
### Description

1. Explain what you did
Used `<Text h4 style={titleStyle}>{title}</Text> `

`titleStyle` contained a custom font `fontFamily: 'Chela One'`

2. What you expected to happen
I expected the custom font family to be applied.

3. What actually happens
The custom font family wasn't applied.

_react-native-elements version:0.15.0 _ 

### Solution

I managed to solve it removing the `h4` prop. 

I guess the problem is with  the bold style:

```
  bold: {
    ...Platform.select({
      android: {
        ...fonts.android.bold,
      },
    }),
  },
```

The font I was trying to use doesn't have a bold optin. Hence is wasn't working.  

I am reporting this because I lost a lot of hours trying to figure it out and may be it can be useful for someone else.  I don't know if it classifies as a bug.

**Comment by Monte9** [comment]
@PolGuixe thanks for the issue. And I appreciate the solution you posted after too for others to see. 

The `h4` prop is for default styling and I'd recommend using just a `<Text>` component when you need a custom font or styling.
