### ISSUE TITLE
ButtonGroup selectedBackgroundColor not working

### ISSUE THREAD

**Issue by barrymichaeldoyle** [react-native-training/react-native-elements#531]
On the ButtonGroup, element I'm finding that the `selectedBackgroundColor` isn't working.

I've tried implementing it like this `selectedBackgroundColor={'#2169F3'}` and like this `selectedBackgroundColor="#2169F3"` and it won't work.

Is this a known issue? Or am I implementing it wrong? I am making use of `buttonStyle` as well but that shouldn't overwrite it.

**Comment by Monte9** [comment]
@barrymichaeldoyle not aware of this issue. Seems like passing a string for the `selectedBackgroundColor` prop is right. 

Can you recreate this using a [Snack](https://snack.expo.io/) demo and I'd be more than happy to help look into this further. Thanks.

**Comment by iRoachie** [comment]
Hey @barrymichaeldoyle I created a simple snack demo showing how to use `selectedBackgroundColor` https://snack.expo.io/BywimTxi-. Let me know if the issue still persists for you.

**Comment by Monte9** [comment]
@barrymichaeldoyle please check out the Snack demo that @iRoachie put together above ^^. It demonstrates how to use the `selectedBackgroundColor` for the `ButtonGroup` component.

In short, here's how you would use it:

```js
<ButtonGroup
  selectedBackgroundColor="pink"
  ..
/>
```

**Comment by Monte9** [comment]
Also @iRoachie I have added to the snack demo on the docs as well here: https://github.com/react-native-training/react-native-elements/commit/6328d6a3ee0d089481a0a664a3f0ab1e3103155a

That's something we should start doing more off. I know @xavier-villelegier creates a lot of snack demos's for issues, if we can add those all to the relevant component doc that would be great. 💯

**Comment by iRoachie** [comment]
That's a brilliant idea! I just wish expo wouldn't take 5 mins to start 😆
