### ISSUE TITLE
Raised Button With Border Radius - Android API 23

### ISSUE THREAD

**Issue by KyleScharnhorst** [react-native-training/react-native-elements#535]
Wanted to have a raised button that also had a border radius.

Here is the result:
![radiusbuttonraised](https://user-images.githubusercontent.com/9146614/28920112-48c724c4-7805-11e7-9d41-de274a2eaac9.PNG)

[Snack Expo Link](https://snack.expo.io/SyIlMcePZ)

Version of `react-native-elements`: 0.15.0

Is there something that I'm missing or is this a bug, can anyone confirm?

**Comment by xavier-villelegier** [comment]
Hey @KyleScharnhorst 
You can add `containerViewStyle={{borderRadius: 20}}` to have a clean button.
This is not really a bug, but it's true that the borderRadius should also be applied to the view wrapping the button [here](https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L130).

**Comment by sujit13666** [comment]
Hi @xavier-villelegier , I am facing same problem with **0.15.0**. `containerViewStyle` seems not to work.

`<Button containerViewStyle={{borderRadius:25}} buttonStyle={{width:145,height:45,borderRadius:25}} textStyle={style.buttonTextStyle} onPress={onPress} title={text}/>`

![signin](https://user-images.githubusercontent.com/5456641/28961336-c522377e-7923-11e7-9b31-8a6a4680c1b8.jpg)

**Comment by xavier-villelegier** [comment]
@sujit13666 Mmh that's not really the same issue. The border radius of the `TouchableHighlight` on Android is a bit more complicated to handle. Try the following:

```jsx
<Button
  borderRadius={25}
  containerViewStyle={{borderRadius:25}}
  buttonStyle={{width:145,height:45,borderRadius:25}}
  textStyle={style.buttonTextStyle}
  onPress={onPress}
  title={text}/>
```

**Comment by sujit13666** [comment]
That's just working like a charm. @xavier-villelegier 

> The border radius of the `TouchableHighlight `on Android is a bit more complicated to handle

Totally agree with you. Otherwise `borderRadius` would not be needed twice (as `borderRadius` itself and in `containerViewStyle`)

**Comment by xavier-villelegier** [comment]
Yeah for sure. The `borderRadius` props should be applied to the `containerViewStyle` and `buttonStyle` automatically. This will probably be handled in a better way in the `v1` ! But feel free
 to open a PR if you want this to be more intuitive in the `v0.16`✌️

**Comment by Monte9** [comment]
The PR has been merged. This will be fixed in the `v0.17` release in the next day or two.

**Comment by phantoxe** [comment]
@xavier-villelegier can u help me a litle bit? I am using your button code sample... and my FONT AWESOME ICON is not showing up. Appears a litle box with X in the place of icon. can u help me?

**Comment by xavier-villelegier** [comment]
@phantoxe FontAwesome should work if you do the same as [this snack demo](https://snack.expo.io/Sk-yqN62-). If it still doesn't work, make sure you have linked with `react-native-vector-icons` as it is specified [here](https://github.com/react-native-training/react-native-elements/blob/master/default_installation.md#step-1-install-react-native-vector-icons)

**Comment by phantoxe** [comment]
@xavier-villelegier this LINK was the problem man... my friend... i have one more question if u can help me check the image below... i want put a litle marginTop in my button... but now it is showing up a whitebackground weird... Do you know whay? Thanks buddy

containerViewStyle={{borderRadius:25, marginTop:10}}
buttonStyle={{borderRadius:25, marginTop:10}} 


![whatsapp image 2017-10-12 at 15 53 54](https://user-images.githubusercontent.com/29681268/31514006-a08875f8-af66-11e7-9561-73729b036cf3.jpeg)

**Comment by xavier-villelegier** [comment]
@phantoxe You're applying a `marginTop` on the container **plus** a `marginTop` on the button which is already inside the container. A margin on the outer component (the container) should be enough. Try doing this

```
containerViewStyle={{borderRadius:25, marginTop:10}}
buttonStyle={{borderRadius:25}}
```

**Comment by alainib** [comment]
> 
> 
> @sujit13666 Mmh that's not really the same issue. The border radius of the `TouchableHighlight` on Android is a bit more complicated to handle. Try the following:
> 
> ```js-jsx
> <Button
>   borderRadius={25}
>   containerViewStyle={{borderRadius:25}}
>   buttonStyle={{width:145,height:45,borderRadius:25}}
>   textStyle={style.buttonTextStyle}
>   onPress={onPress}
>   title={text}/>
> ```
your exact same code doesn't work for me with last react-native-elements@1.1.0

**Comment by mrgigabyte** [comment]
This is still not working in my case. I'm using react-native-elements@2.0.4 
```
<Button
                icon={
                  <Icon
                    name="plus"
                    size={15}
                    color="white"
                  />
                }
                borderRadius={100}
                titleStyle={{ fontWeight: '700' }}
                raised={true}
                buttonStyle={{ 
                  width:50,
                  height:50,
                  backgroundColor: 'rgba(92, 99,216, 1)',
                  borderColor: 'transparent',
                  borderWidth: 0,
                  borderRadius: 100,
                  paddingVertical: 10,
                }}
                containerStyle={{backgroundColor:"grey", width: 50, height: 50, borderRadius:100}}
              />
```

**Comment by mrgigabyte** [comment]
> > @sujit13666 Mmh that's not really the same issue. The border radius of the `TouchableHighlight` on Android is a bit more complicated to handle. Try the following:
> > ```
> > <Button
> >   borderRadius={25}
> >   containerViewStyle={{borderRadius:25}}
> >   buttonStyle={{width:145,height:45,borderRadius:25}}
> >   textStyle={style.buttonTextStyle}
> >   onPress={onPress}
> >   title={text}/>
> > ```
> 
> your exact same code doesn't work for me with last react-native-elements@1.1.0

I was facing the similar problem. [This worked for me](https://github.com/react-native-elements/react-native-elements/issues/1102#issuecomment-380787491)

I am using **react-native-elements@2.0.4**
Let's hope the resolve this bug in the next version
