### ISSUE TITLE
ListItem textInput doesn't show up

### ISSUE THREAD

**Issue by anicoa** [react-native-training/react-native-elements#538]
### Description

I want to use ListItem with `textInput={true}` in my project but i can't get the input-field to show up. Not sure if it's my lack of knowledge or some other problem. Title is shown as expected. Chevron ist also there. Doesn't work with `hideChevron={true}` also.

### Reproduction Steps and Sample Code

Initialize new project
`react-native init AwesomeProject`

Install react-native-elements and react-native-vector-icons
```
npm --save install react-native-elements
npm install --save react-native-vector-icons
react-native link
```

Insert List/ListItem 

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import { List, ListItem } from 'react-native-elements';

export default class AwesomeProject extends Component {
  render() {
    return (
      <View>
        <List>
          <ListItem title='ListItem with Placeholder' textInput={true} />
        </List>
      </View>
    );
  }
}

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);
```

Used versions
```
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-elements": "^0.15.0",
    "react-native-vector-icons": "^4.3.0"
```

### Solution

none so far. Would be very kind if someone could test/confirm or point me into the right direction.

**Comment by uffou** [comment]
Having the same problem ListItem textInput is not working :( 
```
<List>
				<ListItem
					title='Title'
					textInput={true}
					textInputValue={this.state.title}
					textInputOnChangeText={(title) => this.setState({title})}
					textInputReturnKeyType={'done'}
				/>
		  	</List>
```

**Comment by Monte9** [comment]
@anicoa @uffou hmm.. sorry about that. Someone from RNE can help you resolve this soon.

**Comment by Smashbandit** [comment]
I'd love to see this get resolved as well :) I'm having the same issue.

**Comment by Monte9** [comment]
kk. I'll look into this tonight! Will update you guys soon!

**Comment by martinezguillaume** [comment]
Are you on Android or iOS or both ? For me, the textinput shows up in iOS in the future version of react-native-elements

**Comment by martinezguillaume** [comment]
In v16, it works on iOS. This [pr](https://github.com/react-native-training/react-native-elements/pull/565) fix it on Android

**Comment by iRoachie** [comment]
Thanks @martinezguillaume will review it later

**Comment by iRoachie** [comment]
Merged in https://github.com/react-native-training/react-native-elements/pull/565#pullrequestreview-58050170. Will be available in 0.17

**Comment by Smashbandit** [comment]
Thanks guys!

**Comment by iRoachie** [comment]
Fixed in 0.17, which is now live!

**Comment by mukeshkamboj** [comment]
Still not working for Android :-(. Please suggest.

**Comment by iRoachie** [comment]
@mukeshkamboj It works perfectly. See example here https://snack.expo.io/B1YOBx_o-. The only thing is that the backgroundColor is transparent so it looks like it's not there

**Comment by mukeshkamboj** [comment]
@iRoachie Could you please share the package.json?

**Comment by mukeshkamboj** [comment]
@iRoachie 

Thanks for your active response. I solved it with steps mentioned in this [link](https://github.com/oblador/react-native-vector-icons#android).

**Comment by raduflp** [comment]
for me the issue persisted on Android for v0.17.0, the InputValue was not displayed and with `hideChevron={true}` the ListItem height was smaller than the rest.  Adding `textInputStyle={{ paddingTop: 0, paddingBottom: 0, marginVertical: 3.5}}` solved the issue for me

**Comment by bimix** [comment]
You can use this:
input={}
