### ISSUE TITLE
Getting Warning when using SideMenu

### ISSUE THREAD

**Issue by MALHARIHALGEKAR** [react-native-training/react-native-elements#542]
Warning: SideMenu has been deprecated and will be removed in a future version of React Native Elements. For a complete navigation solution that includes SideMenu(Drawer) as well as many other features, be sure to check out react-navigation (https://reactnavigation.org) and it's DrawerNavigator.

react-native-cli: 2.0.1
react-native: 0.43.3

Please, any help I am not understanding why I am getting this warning.
Thanks

**Comment by Monte9** [comment]
@MALHARIHALGEKAR `ReactNavigation` is a navigation library that is rapidly become the default navigation solution for React Native apps. Hence we decided to deprecate our dependency on the SideMenu component and recomment users to start using the sidemenu that comes with react-navigation. 

This is from our [release notes for v0.15.0](https://github.com/react-native-training/react-native-elements/releases/tag/v0.15.0):
"SideMenu, Tabs, and Tab are navigational components but they weren't full navigation solutions. React Navigation is a full navigation library that has support for Drawers (SideMenu), Tabs, Modals and even Stacks. We definitely recommend checking it out." 

Also if you wondering how to get started with react-navigation, take a look at our `/example` app [here](https://github.com/react-native-training/react-native-elements/tree/master/example). The app has a full-fledged implementation of Drawer, Tabs and Stacks. 

Hope this helps. :)
