### ISSUE TITLE
cant find the list of icons that i can use... 

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements#543]
I know this is weird, but ive been using your library but can't figure out where can i find the list of icons ?

Ive used the icons in the following way but i don tknow from where is the list of icons coming ?

  static navigationOptions = {
    title: 'DeckSc',
    tabBarIcon:  ({ tintColor }) => {
        return <Icon name="description" size={30} color={tintColor} />;
    }
  }

===>>>>   But  from where is the list of icons coming ?

Example , on expo they tell you can search and fin d the icons on this , page.  https://expo.github.io/vector-icons/

Where is that thing in your case ?

![image](https://user-images.githubusercontent.com/1026325/29040704-06aa6d36-7b7e-11e7-9c49-645af2486a6e.png)

==============- ================ - ====================

Now in my another code, Im getitting the settings icon,, but where is it comign from ?
wheres the URL so i can see other icons that i can use....    

class SettingsScreen extends Component {
  static navigationOptions = {
    title: 'Settings',
    tabBarIcon:  ({ tintColor }) => {
        return <Icon name="settings" size={30} color={tintColor} />;
    }
  }

**Comment by xavier-villelegier** [comment]
Hey @jpca999, React Native Elements is using the `react-native-vector-icons` package, you can find the list of available icons [here](https://oblador.github.io/react-native-vector-icons/). These are the same as Expo. 😊

**Comment by Monte9** [comment]
@xavier-villelegier thanks for the answer! 👍 

@jpca999 please see the previous issues before opening new ones. This q has been asked and answered multiple times before. Here for instance: https://github.com/react-native-training/react-native-elements/issues/451#issuecomment-311539053

**Comment by jpca999** [comment]
How can I update the docs ?

**Comment by Monte9** [comment]
@jpca999 that's a good question. All the docs live under the `/docs/API` folder. 

So if you want to update the docs for Icons, see this file: https://github.com/react-native-training/react-native-elements/blob/master/docs/API/icons.md

Once you know what you want to change, follow the [contributing guide here](https://github.com/react-native-training/react-native-elements/blob/master/.github/CONTRIBUTING.MD) and submit a PR with your changes. I'd be happy to review them. 😀
