### ISSUE TITLE
Checkbox selected per checkbox 

### ISSUE THREAD

**Issue by AlmogRnD** [react-native-training/react-native-elements#545]
I'm creating a number of checkbox via a for loop and wanted to know how I can set the selected stated per checkbox

Here is my code
```
render() {
        // Gets tags from props
        const tags = this.props.tags;

        // Creates tag
        const tagItems = tags.map((tag) => {
            return(
                <CheckBox
                    key={tag}
                    center
                    title={tag}
                    iconRight
                    iconType='material'
                    checkedIcon='clear'
                    uncheckedIcon='add'
                    checkedColor='red'
                    checked={false}
                    //onPress={this._toggle.bind(this)}
                    onPress={(event) => this._toggle(event, tag)}
                />
            )});

        return (
            <View>
                {tagItems}
            </View>
        )
    }
```

```
_toggle(event, buttonId) {

        //this.setState({checked: !this.state.checked});
        console.log(buttonId)
        //console.log(this)


    }
```

**Comment by Monte9** [comment]
@AlmogRnD that's a good question. The way I think about it is.. if a component needs its own state, then it makes sense to map over a custom implementation of the component which knows how to handle its own state. I implemented this in the example app here and have a working demo you can play with [here](https://github.com/react-native-training/react-native-elements/commit/45a3fcdb1f955ca4eb71dbdd1e8dd61861b3fe34#diff-324fbd9b50ed12140515855124160bf0R6)

Here is how I did it:
```
import { CheckBox } from 'react-native-elements';

class CustomCheckbox extends Component {
  constructor() {
    super();

    this.state = {
      checked: false
    };
  }

  render() {
    const { tag } = this.props;
    const { checked } = this.state;

    return (
      <CheckBox
        key={tag}
        center
        title={tag}
        iconRight
        iconType='material'
        checkedIcon='clear'
        uncheckedIcon='add'
        checkedColor='red'
        checked={checked}
        onPress={() => this.setState({checked: !checked})}
      />
    );
  }
}

renderTags() {
    return ['One', 'Two', 'Three', 'Four'].map((tag, index) => {
      return <CustomCheckbox key={index} tag={tag} />;
    });
  }
```

Hope this helps. Let me know if you have trouble with this.

**Comment by AlmogRnD** [comment]
@Monte9 the issue is that while it does need its own state, the check boxes need to be together under one component so it's easy to know which ones were selected, think of it as tags and a user can select a couple different ones. Ideally, there would be a checkbook group this is how I would have done it in web

**Comment by Monte9** [comment]
> the check boxes need to be together under one component so it's easy to know which ones were selected
This sounds like a good use case for using callbacks. Basically the idea would be that when a `CustomCheckbox` is selected, you would invoke the callback on the parent and that way be able to keep track of which checkbox is selected using the tag/index.

Let me know if this is too confusing or if you need an example on how to do this. Also maybe @xavier-villelegier has another approach to doing this?

**Comment by AlmogRnD** [comment]
@Monte9 could use a little help with this and how I would it 
Right now I have the following structure 
 
- Component TagGroups 
 - Component Tags

TagGroups 
```
return (
            <View>
                {this.state.indeterminate &&
                <Progress.Circle
                    style={styles.progressContainer}
                    progress={this.state.progress}
                    indeterminate={this.state.indeterminate}
                />
                }

                {!isEmptyProjectTags &&
                <View>
                    {this._renderTagGroups()}
                </View>
                }

                {isEmptyProjectTags &&
                <View>
                    <Text>No tags</Text>
                </View>
                }
            </View>
        )

// Render tag groups
    _renderTagGroups() {

        // Gets the tags groups
        const tagGroups = store.getState().selectedProject.project.tagGroups;

        for (var i = 0, len = tagGroups.length; i < len; i++) {
            return(
                <View>
                    <View key={i}>
                        <Text>{tagGroups[i].name}</Text>
                        <Tag tags={tagGroups[i].tags}/>
                    </View>
                </View>
            );
        }
    }
```

Tags 
```
render() {
        // Gets tags from props
        const tags = this.props.tags;

        const { checked } = this.state;

        // Creates tag
        const tagItems = tags.map((tag) => {
            return(
                <CheckBox
                    key={tag}
                    center
                    title={tag}
                    iconRight
                    iconType='material'
                    checkedIcon='clear'
                    uncheckedIcon='add'
                    checkedColor='red'
                    //checked={this.state.checked}
                    //onPress={this._toggle.bind(this)}
                    onPress={(event) => this._toggle(event, tag)} //!checked
                    //onChange={(checked) => this._checkStudent(student, !checked)}

                    //onChange={(checked) => this._checkStudent(student, !checked)}
                    //checked={student.checked}
                />
            )});

        return (
            <View>
                {tagItems}
            </View>
        )
    }
```

**Comment by Monte9** [comment]
Couple things:
1. The code makes sense, although it's hard to tell what you are trying to achieve without some sort of UI representation. Can you add a screenshot so I get a better sense of how it's supposed to "behave"
2. We are experimenting with "Paid Feature request" here at RNE. So basically a dev can implement the entire feature for you and share the completed code with you. If this sounds interesting, let me know. We can even do this one for free. ;)

**Comment by AlmogRnD** [comment]
@Monte9 I might be interested in that down the line, there is a lot of work that I need with components would need to understand how this would work.  

Right now if you can help or point me in the right direction that would be great 

Here is a screenshot of the design version 
<img width="551" alt="screen shot 2017-08-08 at 12 51 56 am" src="https://user-images.githubusercontent.com/169507/29061802-30aab6b2-7bd4-11e7-8bd1-162e83cbef12.png">

As you can see we have a group of tags that is the tag group component 

and it renders the tags current version working 

<img width="364" alt="screen shot 2017-08-08 at 12 55 39 am" src="https://user-images.githubusercontent.com/169507/29061843-5293df56-7bd4-11e7-9f50-56d5c1825d5b.png">

**Comment by Monte9** [comment]
Ok, that's helpful. And so from what I understand you want to implement it in such a way that the `TagGroups` component is aware of all the tags that are selected within it's own group correct?

**Comment by AlmogRnD** [comment]
Yea, that is the main concern I had with callbacks I was worried it would be nested too deep and create an issue. 

 A user uploads a photo and selects tags for that photo, the tag group component is inside the photo upload component 

But worst case I can just updated the selected tags in my redux store

**Comment by Monte9** [comment]
@AlmogRnD yeah that makes sense. Ok, so do you have a fair understanding of what you need to do and how you would do it using callbacks?

If not, I can implement something similar on the `/example` app by tomr if that helps you. let me know.

**Comment by AlmogRnD** [comment]
@Monte9 I have it working based on the first example code you sent me, I just need to understand the best way for the callbacks/props as you suggested 

yes "how you would do it using callbacks?" what I'm not sure on

**Comment by Monte9** [comment]
@AlmogRnD you will be happy to know that I already implemented a simple use case demonstrating the use of callback in reference to Tags & TagGroups. Here's is what it looks like:
<img width="365" alt="screen shot 2017-08-08 at 1 52 37 am" src="https://user-images.githubusercontent.com/7840686/29064019-8a234670-7bdc-11e7-988a-b6ff8fcb1873.png">

**Comment by AlmogRnD** [comment]
Ok can you send the code, thats just an image

**Comment by AlmogRnD** [comment]
Also how would I handle the onpress event with the state change 

if  do this 
` onPress={this._selectedTag()}`

but then I can't handle the state change 
`onPress={() => this.setState({checked: !checked})}`

**Comment by Monte9** [comment]
Yes you can. Just put the ` this.setState({checked: !checked})` inside your `_selectedTag()` function.

**Comment by AlmogRnD** [comment]
Unless I'm doing it wrong but that crashes the app and I get the following error 
<img width="1327" alt="screen shot 2017-08-08 at 2 06 53 am" src="https://user-images.githubusercontent.com/169507/29064589-49c7b104-7bde-11e7-8a05-88e219218e54.png">

**Comment by Monte9** [comment]
@AlmogRnD please join our Slack channel and someone can help you resolve that. 

https://reactnativetraining.herokuapp.com/

**Comment by AlmogRnD** [comment]
@Monte9 ok I got got this is the use correct use case 

onPress={() => {
                    this.setState({checked: !checked})
                    this._selectedTag()
                }}

**Comment by AlmogRnD** [comment]
@Monte9 when you have a chance can you send me an email to almog@constructioncloud.com.au were looking at hiring a freelancer react native developer to develop a couple custom components for us. Thanks, Almog

**Comment by Monte9** [comment]
Thanks for reaching out @AlmogRnD! I have sent you an email.

**Comment by badarshahzad** [comment]
What wonderful chat... I (junior) learn lot of stuff from your healthy conversation thank you... :+1:  :wave:

**Comment by Biplovkumar** [comment]
```
      import { CheckBox } from 'react-native-elements'         
               
                <View style={{ marginTop: 15 }}>

                  <CheckBox
                    key={tag}
                    textStyle={{ flexWrap: 'wrap',fontFamily:'light', fontSize: Fonts.size.h4, color: 'rgba(255,255,255,0.7)', fontWeight: '400' }}
                    containerStyle={{  backgroundColor:  'transparent', flexDirection: 'row', borderColor: 'transparent' }}
                    title={tag}
                    uncheckedColor='white'
                    checkedColor='white'
                    iconType='material-community'
                    checkedIcon='checkbox-marked-outline'
                    uncheckedIcon='checkbox-blank-outline'
                    checked={this.state.checked}
                    onPress={() => this.setState({checked: !this.state.checked})}
                  />

                </View>``



It works fine but showing White background.
How can remove it ??
My background color is gradient so its look odd in app.

and this chat is really helpful for me.

**Comment by iRoachie** [comment]
@Biplovkumar as you can see by this example https://snack.expo.io/@roach_iam/mature-truffle, there's no white background

**Comment by Biplovkumar** [comment]
Thanku sir
