### ISSUE TITLE
Icons support for custom SVG or TTF.

### ISSUE THREAD

**Issue by aprofromindia** [react-native-training/react-native-elements#549]
### Description

1. I tried to create a custom TTF from some custom SVG using the website https://glyphter.com/ or https://icomoon.io/app/#/select
2. to work successfully like other types
3. Error received - _Warning: Failed prop type: Invalid prop name of value 'free-riding' supplied to Icon, expected one of [...]_ 

### Reproduction Steps and Sample Code

package.json below : -

`"dependencies": {
    "elements": "^0.6.0",
    "react": "^16.0.0-alpha.12",
    "react-hot-loader": "^3.0.0-beta.7",
    "react-native": "^0.47.0",
    "react-native-elements": "^0.15.0",
    "react-native-global-props": "^1.1.1",
    "react-native-i18n": "^2.0.4",
    "react-native-svg-uri": "^1.2.0",
    "react-native-svg": "^5.4.1",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-promise": "^0.5.3"
  },`

Source code below: -

`<Icon
          type="fat-map"
          name="act-free-riding" />`

### Solution

Any ideas or pointers to the right direction would be most appreciated.

**Comment by iRoachie** [comment]
Can you show how you used it with one of our components?

**Comment by aprofromindia** [comment]
Icon code added as requested.

**Comment by iRoachie** [comment]
Does the icon work though? Or is it only the warning that shows?

**Comment by olasfar** [comment]
Hey guys,

If I'm not mistaken RNE doesn't support custom icons regarding https://github.com/react-native-training/react-native-elements/blob/910c77106abbec24550c64e073608ce717f4e1b1/src/icons/Icon.js#L38-L42 and https://github.com/react-native-training/react-native-elements/blob/master/src/helpers/getIconType.js#L35-L36

How could we integrate our custom icons with RNE ?

Thx in advance,

**Comment by Monte9** [comment]
@aprofromindia @olasfar Yes, using custom fonts is def a use case we want to support. 

There is this PR https://github.com/react-native-training/react-native-elements/pull/546 which will allow for this. We plan to merge this into RNE soon and should be available to use in the next release. 

Hope this helps. Also if this issue is a blocker or something you need asap, we can even do a release sooner. Let me know.

**Comment by aprofromindia** [comment]
@Monte9 - any idea when this might happen please?

**Comment by iRoachie** [comment]
@aprofromindia The author of the PR just needs to add an example of it being used. After that we can merge

**Comment by iRoachie** [comment]
Release in 0.17

**Comment by chrise86** [comment]
I'm having difficulty getting this to work. I have this in my `package.json`:
```
"rnpm": {
  "assets": [
    "./app/assets/fonts"
  ]
}
```
The font file for `icomoon` live in `app/assets/fonts/icomoon`. I have also manually added the `ttf` to the resources in Xcode.

Then I am using:
```
import { registerCustomIconType } from 'react-native-elements'
import { createIconSetFromIcoMoon } from 'react-native-vector-icons'
import icoMoonConfig from 'assets/fonts/icomoon/config.json'

registerCustomIconType('icomoon', createIconSetFromIcoMoon(icoMoonConfig))
```
However, when using:
```
<Icon
  type='icomoon'
  name='icon-name'
/>
```
I get:
```
Unrecognized font family 'icomoon'
```
