### ISSUE TITLE
ButtonGroup how to remove the borderRadius

### ISSUE THREAD

**Issue by CrazyWr** [react-native-training/react-native-elements#554]
#![image](https://user-images.githubusercontent.com/19635808/29348492-c09ebbb6-8286-11e7-87f7-32c8a64c6ea2.png)
![image](https://user-images.githubusercontent.com/19635808/29348542-0ea73aa4-8287-11e7-8419-eed65298bbad.png)

how to remove the borderRadius, ` borderRadius: 0` is not work

![image](https://user-images.githubusercontent.com/19635808/29348788-9f696cbe-8288-11e7-995a-93bf23b56c4a.png)

`react-native-elements    ^0.15.0`

**Comment by CrazyWr** [comment]
![image](https://user-images.githubusercontent.com/19635808/29348939-980571e2-8289-11e7-9fb4-27a888781f29.png)
ok, `containerBorderRadius={0}` fix it. but documents doesn't contain it

**Comment by Monte9** [comment]
@CrazyWr that's a good catch. And thanks for posting the solution as well.
I have updated `containerBorderRadius` props on the docs [here](https://github.com/react-native-training/react-native-elements/commit/cb81deda66ecabd87bde43b94922f29ec1c38bd9) and it will be updated in the next release.
