### ISSUE TITLE
[Buttongroup]How to use onPress to navigate different pages?

### ISSUE THREAD

**Issue by dx51job** [react-native-training/react-native-elements#563]
Hi,
    I'd like to use Buttongroup onPress to navigate different pages, looking for help!!!
    **onPress={this.updateIndex}
    onPress={selectedIndex ? () => navigation.navigate('Page0') :  () => navigation.navigate('Page1')}** 
    I've tried to combine them,but it doesn't work properly......

**Comment by dx51job** [comment]
I've solved this issue on my own. 
Add as below in updateIndex(selectedIndex) function
 selectedIndex?navigation.navigate('Page0'):navigation.navigate('Page1') ;

**Comment by RyanTG** [comment]
I know this is ancient, but just in case anyone else finds this here is what worked for me:

````
constructor () {
  super()
  this.state = {
    selectedIndex: 2
  }
  this.updateIndex = this.updateIndex.bind(this)
}
updateIndex (selectedIndex) {
  selectedIndex ? this.props.navigation.navigate('HelloScreen') : this.props.navigation.navigate('WorldScreen')
}

const component1 = () => <Text>Hello</Text>
const component2 = () => <Text>World</Text>

render () {
  const buttons = [{ element: component1 }, { element: component2 }]
  const { selectedIndex } = this.state
  return (
    <ButtonGroup
      onPress={this.updateIndex}
      selectedIndex={selectedIndex}
      buttons={buttons}
      containerStyle={{height: 100}} />
  )
}
````
