### ISSUE TITLE
Display custom images in Icon elements

### ISSUE THREAD

**Issue by aprofromindia** [react-native-training/react-native-elements#567]
Description

I tried to include a custom image tag within an Icon tag and expect it to work.

Error received - Shows a blank white Icon with no image inbetween.

Reproduction Steps and Sample Code

package.json below : -

`"dependencies": { "elements": "^0.6.0", "react": "^16.0.0-alpha.12", "react-hot-loader": "^3.0.0-beta.7", "react-native": "^0.47.0", "react-native-elements": "^0.15.0", "react-native-global-props": "^1.1.1", "react-native-i18n": "^2.0.4", "react-native-vector-icons": "^4.3.0", "react-navigation": "^1.0.0-beta.11", "react-redux": "^5.0.5", "redux": "^3.7.2", "redux-promise": "^0.5.3" },`

Source code below: -

`<Icon>
  <Image
              style={{ width: 50, height: 50 }}
              source={{
                uri: 'https://facebook.github.io/react/img/logo_og.png',
              }} />
</Icon>`

Solution

Any ideas or pointers to the right direction would be most appreciated.

**Comment by iRoachie** [comment]
What are you trying to accomplish here? The Icon component doesn’t take any children, so they won’t be rendered. Any reason you need to nest an image inside the Icon component ??

**Comment by iRoachie** [comment]
Dup of https://github.com/react-native-training/react-native-elements/issues/578
