### ISSUE TITLE
Header element does not working correctly on Android

### ISSUE THREAD

**Issue by viniciuscarneiro** [react-native-training/react-native-elements#568]
Hi there, I am trying to use the <Header> element but on android the onPress does not working in IOS the onPress is working correctly 

My code:

```

import React , { PropTypes, Component } from 'react';
import { View, Text, TouchableHighlight } from 'react-native';
import { Header, Avatar, Icon } from 'react-native-elements';

export class Signup extends React.Component {
  constructor(props) {
    super(props);
    this.goToProfileDetail = this.goToProfileDetail.bind(this);
  }

  static propTypes = {
    navigator: PropTypes.object
  };

  goToProfileDetail() {
    this.props.navigator.push({
                         passProps: { promotitle : "Promoção Pizza G" }, 
                         screen: 'food.ProfileDetails',
                         title: 'Configurações',

    });
  }

  render() {
    return (
      <View style={{flex: 1, backgroundColor:'#fff'}}>
        <Header
          innerContainerStyles={{flexDirection: 'row'}}
          backgroundColor='#f40057'
          leftComponent={<Avatar
                            small
                            rounded
                            source={{uri: "http://www.usanetwork.com/sites/usanetwork/files/styles/629x720/public/2016/07/mrrobot_s2_cast_rami-malek2.jpg"}}
                            onPress={() => this.goToProfileDetail()}
                            activeOpacity={0.7}
                          />}
          centerComponent={ <View style={{alignItems: 'center'}}>
                              <Text style={{justifyContent: 'center', color: '#fff', alignContent:'center'}}>Eliot Alderson</Text>
                              <Text style={{justifyContent: 'center', color: '#fff'}}>eliot@food.com.br</Text>
                            </View>}
          rightComponent={<Icon name={'settings-applications'} color={'#fff'} onPress={() => this.goToProfileDetail()}/>}
        />
      </View>  
    );
  }
}

```
My versions:

```

"dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-elements": "^0.14.0",
    "react-native-navigation": "^1.1.188",
    "react-native-vector-icons": "^4.3.0"
  }


```
Could you help me?

**Comment by filiphosko** [comment]
Hi @viniciuscarneiro, I don't know how this can be related to the Header element, more probably it's an issue with Avatar/Icon components (I don't know which onPress do you mean).

BTW, when you have custom Header items/elements like that, you can pass them as children too (the API allows it):
```jsx
render() {
    return (
      <View style={{flex: 1, backgroundColor:'#fff'}}>
        <Header
          innerContainerStyles={{flexDirection: 'row'}}
          backgroundColor='#f40057'
        >
          <Avatar
            small
            rounded
            source={{uri: "http://www.usanetwork.com/sites/usanetwork/files/styles/629x720/public/2016/07/mrrobot_s2_cast_rami-malek2.jpg"}}
            onPress={() => this.goToProfileDetail()}
            activeOpacity={0.7}
          />
          <View style={{alignItems: 'center'}}>
            <Text style={{justifyContent: 'center', color: '#fff', alignContent:'center'}}>Eliot Alderson</Text>
            <Text style={{justifyContent: 'center', color: '#fff'}}>eliot@food.com.br</Text>
          </View>
          <Icon
            name={'settings-applications'}
            color={'#fff'}
            onPress={() => this.goToProfileDetail()}
          />
        </Header>
      </View>  
    );
  }
```

**Comment by viniciuscarneiro** [comment]
Hi @filiphosko, thank you for the answer,  I think it is related to the Header element because any onPress on elements inside the Header does not work on Android, I tried your way it keep working only in IOS

**Comment by filiphosko** [comment]
It's strange, I can look at it when I'll have time and try to reproduce it in Expo Snack.

**Comment by qwert666** [comment]
@viniciuscarneiro had similar case but with ios had to wrap the Header component around an extra View component
``` 
<View style={{flex: 1, backgroundColor:'#fff'}}>
     <View style={{flex: 0.2}}>
        <Header
          innerContainerStyles={{flexDirection: 'row'}}
          backgroundColor='#f40057'
        >
     </View>
    ...
```

**Comment by eightyfive** [comment]
I struggled quite a bit on this as well... In my case, this was an absolute positioning issue.

Adding `zIndex` to `Header` component did the trick:
```
<Header outerContainerStyles={{ zIndex: 1 }}>
   ...
</Header>
```

Interesting to note that my "body/content" component just under the `Header` had `style={{ marginTop: 70 }}` set in order to give some room to `Header` component (and thus allowing the `press` events on Header buttons), but still, it did not work unless I added `{{ zIndex: 1 }}` to `Header`.

Hope this helps.

**Comment by LJCoetzee** [comment]
As @eightyfive mentioned, adding a zIndex to your header's style works! At least it solved our issue on Android.

**Comment by Monte9** [comment]
Thanks for posting the solution @eightyfive! 👏 

@viniciuscarneiro hope this solves your issue.

**Comment by filiphosko** [comment]
@viniciuscarneiro @eightyfive Guys, I'm sorry but I can't reproduce this in Snack (Android emulator). Here is my code:

```jsx
 export default class App extends Component {
  state = {
    text: 'Waiting for the buttons to be pressed...'
  };
  
  changeText(newText) {
    this.setState({ text: newText });
  }
  
  render() {
    return (
      <View style={{ flex: 1 }}>
        <Header
          leftComponent={<Icon name="home" onPress={() => this.changeText('Left onPress works')} />}
          centerComponent={<Text>Wassap</Text>}
          rightComponent={<Icon name="phone" onPress={() => this.changeText('Right onPress works')} />}
        />
        <View style={{ marginTop: 70 }}>
          <Text style={{ textAlign: 'center' }}>{this.state.text}</Text>
        </View>
      </View>
    );
  }
}
```

Feel free to try it here https://snack.expo.io and let me know how it went. Thanks!

**Comment by eightyfive** [comment]
Hi @filiphosko, thanks for trying, in my case I wouldn't really bother since my use case is very specific.

Cheers.

**Comment by iRoachie** [comment]
A better fix will be made for the Header in an upcoming release.

**Comment by filiphosko** [comment]
I'm curious ;) BTW applying zIndex would work in case when the absolute positioned Header is covered by something, in that case I don't think it's a problem of the component.

**Comment by iRoachie** [comment]
It's still a problem. Because a header component should flow with the elements on the page, instead of being absolute positioned. Right now if you just add a header to a page; the other elements overlap it. Out of the box that should be the case.

**Comment by filiphosko** [comment]
The primary idea for the Header component was that this component has only one place to be - to the top (as a Navigation Bar). Another component like that (although not a "true" RN component) is the StatusBar - it's always the first element on the page and other components go underneath it (you can say it is absolutely positioned). People just know how to work around it and they offset their views by the height of the StatusBar. The same behavior was expected for the Header. Second reason was that you can place it anywhere in the component stack and it will always go to the top (so it will always be a "Header" of the page no matter what).

Of course I agree with refactoring it, I was hoping somebody would do it a lot sooner. This component was primarily made to simplify prototyping, not to be used as a production component (I still think it shouldn't be used that way). This implementation has it's reasons, but as I see from the issues people (99.9% of them beginners) just don't know how to integrate it properly (maybe because it's not stated in the docs), so probably it would be better to change the API for a "more natural way of doing things". It would be a breaking change tho.

**Comment by iRoachie** [comment]
This is not a convention. All the other UI libraries for react-native, their toolbars/headers flow with the page so it's a really weird when persons come to RNE and it functions differently.

Definitely adding this to the backlog

**Comment by eightyfive** [comment]
I think misunderstanding comes from the fact that React Native marginTop does not seem to behave the way it does in CSS.

In CSS padding-top on next component after Header would overlap it, margin-top would not. In RN it seems that they're are no diff between the two (both overlap Header).

Note: I did not back up this theory with thorough testing/trials.

**Comment by iRoachie** [comment]
@eightyfive React native has the same box model as the web. Adding padding and margin would not change the fact that we are interacting with **statically positioned component(content)** and an **absolutely positioned component(header)**.

**Comment by tanveerbyn** [comment]
hey guys I have a query .. I have a cart icon which is on many screen's and in that it has a label that showing cart items count when I update my data on that screen which is updated it can be update but on another screen it count cannot
updating plz help me and dot suggest me for redux coz this bit complex
