### ISSUE TITLE
Could <Tile> component 'title' property be clipped?

### ISSUE THREAD

**Issue by HOUCe** [react-native-training/react-native-elements#570]
### Could <Tile> component 'title' property be clipped?

1. I want <Tile> component 'title' be showed in ONE line (no wrap)
2. When 'title' is to long, I want to it be clipped and displaying an ellipsis in tail.
3. How can I reach that? Just like text-overflow: ellipsis in CSS3

**Comment by HOUCe** [comment]
### Already resolved
Please close this issue.

**Comment by iRoachie** [comment]
Thanks

**Comment by Monte9** [comment]
@HOUCe mind sharing your solution with us? It might benefit someone else trying to do that same. Thanks.

**Comment by Monte9** [comment]
Ah thanks for the fix @HOUCe! Here's the PR that fixes it: https://github.com/react-native-training/react-native-elements/pull/573

It adds a `titleNumberOfLines` prop to the Tile component.
