### ISSUE TITLE
issue with prop types in react 16 and react-native v0.47

### ISSUE THREAD

**Issue by mgenov** [react-native-training/react-native-elements#571]
### Description
When I import the library in project with react-native version v0.47 I'm encountering an issue with PropTypes as they are no longer part of React 16 internally and are moved into a separate package. 

Tested Version: react-native-elements: v0.16.0

### Solution
I've checked that react-native-elements depends on react-native-tab-navigator and it used the old prop types from the React package. Recently the react-native-tab-navigator was updated to use the new PropTypes package with https://github.com/happypancake/react-native-tab-navigator/pull/152
which means that the dependency of react-native-tab-navigator need to be updated to v0.3.4 to be compatible with latest react-native.

**Comment by iRoachie** [comment]
Closing as dup of #564
