### ISSUE TITLE
Searchbar does not behave properly with Flatlist

### ISSUE THREAD

**Issue by EnriqueDev** [react-native-training/react-native-elements#580]
### Description

1. Explain what you did
 Using ListView with the search bar:

![simulator screen shot 30 ago 2017 11 29 59](https://user-images.githubusercontent.com/25365731/29868376-93ad27b4-8d76-11e7-9633-3cd62113c558.png)

2. What you expected to happen
Searchbar should be on top when the list scrolls up.

3. What actually happens

Part of the component does not stays on top.

![simulator screen shot 30 ago 2017 11 23 26](https://user-images.githubusercontent.com/25365731/29868281-45cd3926-8d76-11e7-8a99-76263f429a03.png)

react-native-elements: ^0.16.0

**Comment by xavier-villelegier** [comment]
@EnriqueDev I think it is just a matter of styling. On [this demo](https://snack.expo.io/H1PsAvUqW) it works as expected. Can you give a little bit more context ? Maybe a simple `containerStyle={{ marginBottom: 8 }}` would do the job ?

**Comment by Monte9** [comment]
Agree with @xavier-villelegier! This can be solved by adding a margin on the bottom of the SearchBar or by also putting the search bar in the scrollView itself. This issue doesn't directly relate to RNE.

Thanks @xavier-villelegier for putting the snack demo together. 👏
