### ISSUE TITLE
Generic question : good fit for an attempt at a multiplatform-1 codebase app ?

### ISSUE THREAD

**Issue by fabm22** [react-native-training/react-native-elements#582]
### Description

Sorry if too generic, but I have two points of doubts that I d like someone to confirm or not for a project I'm looking for.

1) Android+iOS only : 
Would like to know if this is the best bet to aim at ONE codebase for both Android et iOS apps, including as much as possible the code for the views and visual components..?
Is it actually a goal of this project ?

2) ..web also, so Android+iOS+Web : 
in the case this is indeed a good fit for Andro+iOS, if one has to also support even a tone down web presentation of the app (first classes are android+ios. Web is just a requirement),  am I totally left in the wild for this case regarding the views and visual components code ?
Any hopes to reuse the code or is it just impossible ?
Is there maybe some themed react components to try and aim at same look and feel ? 

Thanks a lot for any clarification

**Comment by iRoachie** [comment]
Hey @fabm22 sorry for the late response. RNE is perfect to use for android and ios. Currently, right now all our components display the same way on ios and android.

We don't currently support web right now, but it's something that we have on our roadmap.

**Comment by fabm22** [comment]
Thanks for your answer (and sorry for my late one too). 

So I get that for point 1. RNE is indeed a perfect fit.

For point 2 of using also the same codebase on web, my best bet, if using RNE for native side is to NOT use RNE for the ui templates side of the code and replace it with something else. 
-> So maybe you know of some react web ui library which would maybe follow similar principles as RNE follows when it comes  for the components available or the way they are naming. I mean, maybe RNE was inspired by some other (web/ui) libraries when it comes to which types of Components to support etc. ?

Thanks for feedback.

**Comment by iRoachie** [comment]
I work with react web at work too, so I can recommend [material-ui](https://material-ui-next.com) as we use it heavily at work. There are some other libs out there too that have built in react components
