### ISSUE TITLE
Small button

### ISSUE THREAD

**Issue by Vishal0203** [react-native-training/react-native-elements#583]
Documentation examples don't show how to get a small button. However, the image shows small buttons. Am I missing some thing here?

**Comment by iRoachie** [comment]
Small is the default button size @Vishal0203

**Comment by iRoachie** [comment]
https://snack.expo.io/BkeOt2SFb

**Comment by Vishal0203** [comment]
That's the default size I have. Looks too large than the one shown on this link [https://react-native-training.github.io/react-native-elements/API/buttons/](https://react-native-training.github.io/react-native-elements/API/buttons/)

<img width="372" alt="screen shot 2017-08-31 at 10 01 52 pm" src="https://user-images.githubusercontent.com/8856973/29934242-0aec6962-8e98-11e7-92fa-e2f96b079136.png">

**Comment by iRoachie** [comment]
That image isn't necessarily to scale. You can check how they compare in the example app, https://expo.io/@monte9/react-native-elements-app

**Comment by xavier-villelegier** [comment]
@Vishal0203 Did you manage to do what you want ? If the small button is still too big for you, you can override the padding [like this](https://snack.expo.io/r1-PLdIc-) (Thanks @iRoachie for the snack template haha)
