### ISSUE TITLE
Twemoji support? [Feature Request]

### ISSUE THREAD

**Issue by j2l** [react-native-training/react-native-elements#585]
I found myself needing emoji I can only find in Twitter emoji.
Would it be possible to add them?

Main source is [here](https://github.com/twitter/twemoji), license is CC-BY 4.0 in source or about page.
There are [2 recent projects ](https://github.com/search?utf8=%E2%9C%93&q=twemoji+react+native&type=)for react native.

**Comment by iRoachie** [comment]
Closing this an inactive.
