### ISSUE TITLE
How to set <Button> 100% width?

### ISSUE THREAD

**Issue by pacozaa** [react-native-training/react-native-elements#587]
How to set <Button> 100% width?

it seems like Button can not set to 100% width. Even I set marginHorizontal to 0. Even other element that apply the same style already 100%.  Looks like something prevent Button to have 100% width.

**Comment by iRoachie** [comment]
It's pretty simple once you know :P. The prop you're looking for is `containerViewStyle`.

Here's a snack demo showing it in action. https://snack.expo.io/S1PWQqkcZ

**Comment by pacozaa** [comment]
It works! Looks like `containerViewStyle` is an important attribute but it is pushed to the last item in the document. You may consider change the order of it to higher order. I didn't notice it at the first look. 

All the Best,
Sarin

**Comment by iRoachie** [comment]
@pacozaa glad I could help. If you think there’s a better way we can order the properties then I’ll be more than happy to accept a pull request.

**Comment by pacozaa** [comment]
@iRoachie #592 There you go 👍

**Comment by samvictor** [comment]
Make sure the View around the button doesn't have it's 'alignItems'  style set. That messed me up for a while.

**Comment by AndyCrisan** [comment]
<Button
                        containerViewStyle={{marginLeft:-10,marginRight:null,width:"105%"}}
                        buttonStyle={{width:"100%"}}
                        textStyle={{}}
                        onPress={() => )}
                        title="title"
                    >
                    </Button>

**Comment by skptricks** [comment]
Refer this post : https://www.skptricks.com/2018/07/how-customize-button-in-react-native.html

**Comment by hodgef** [comment]
For people Googling this issue due to the incomplete docs, here's what I've used.

For full width **with** the included button margins
```
<Button
  title="Title"
  onPress={() => {}}
  containerViewStyle={{
    alignSelf: 'stretch',
  }}
/>
```

For full width **without** the included button margins.
```
import { Dimensions } from 'react-native';

<Button
  title="Continue"
  onPress={() => {}}
  containerViewStyle={{
    width: Dimensions.get('window').width + 10,
    marginLeft:-10,
  }}
/>
``

**Comment by iRoachie** [comment]
@hodgef You could just do this:
```jsx
<Button title="Hey" containerViewStyle={{width: '100%', marginLeft: 0, marginRight: 0}}/>
```

**Comment by hodgef** [comment]
@iRoachie, just tried your snippet and it doesn't work unfortunately. The button displays like "display:inline-block". "width: 100%" seems to be ignored.

`marginLeft: 0` indeed removes the margin and is way better than `marginLeft: -10`. Thanks for that!

**Comment by iRoachie** [comment]
Did you actually look at the example snack?

![img_77bd70e953a9-1](https://user-images.githubusercontent.com/5962998/43844278-5551163a-9af7-11e8-8884-3cf81870fc54.jpeg)

**Comment by hodgef** [comment]
@iRoachie Indeed your snack works. Here's another one where I'm finding the issue (Notice the "hey" button)

https://snack.expo.io/r1WOmFOB7

Thanks for your help

**Comment by iRoachie** [comment]
The parent `View` of the Button doesn't have a width. `width: 100%` takes up the full space of the parent.

You actually just need to set a width on the parent View.
```
<View style={{
              alignItems: "center",
              width: '100%',
              marginHorizontal: 20,

            }}>
```

https://snack.expo.io/Sk1N4tuHm

**Comment by hodgef** [comment]
Excellent, you are correct. Thank you for your time!

**Comment by skptricks** [comment]
Reference : How To Customize Button In React Native
<https://www.skptricks.com/2018/07/how-customize-button-in-react-native.html>

**Comment by Kumar2106** [comment]
> @hodgef You could just do this:
> 
> ```js
> <Button title="Hey" containerViewStyle={{width: '100%', marginLeft: 0, marginRight: 0}}/>
> ```
> 
> https://snack.expo.io/B1FFgtdBX

Hi i have tried that solution but whenever i am saving the file, the app just stop running.
