### ISSUE TITLE
How to put badge in the left side in list item ?

### ISSUE THREAD

**Issue by Alireza-Ta** [react-native-training/react-native-elements#588]
I'm trying to put badge in the left side of a list item and playing for a while with flex-box in containerStyle but it did not work btw i'm not good at styling in RN!

Any help is appreciated.

**Comment by iRoachie** [comment]
Yes you can! You can use the `wrapperStyle` prop to change the direction in which the items are laid out. Finally set the `rightIcon` to an empty view to hide the `>`.

Here's a demo https://snack.expo.io/r1Fzwwfcb

**Comment by Alireza-Ta** [comment]
@iRoachie Thanks, It did the trick.
I'm not aware about row-reverse option!
