### ISSUE TITLE
Enable reverse Icon with ListItem

### ISSUE THREAD

**Issue by gunnarblom** [react-native-training/react-native-elements#589]
Could you enable to use reverse icons with the ListItem? (i.e. pass through that prop from ListItem to the Icon.

**Comment by iRoachie** [comment]
Could you be a bit clearer by what you mean reverse?

**Comment by gunnarblom** [comment]
The `<Icon>` element has a `reverse` prop. From the docs:

```jsx
<Icon
    reverse
    name='ios-american-football'
    type='ionicon'
    color='#517fa4'
/>
```

It would be awesome if that prop would pass through when using `<ListItem>`. E.g:

```jsx
<ListItem
    key={i}
    title={item.title}
    leftIcon={{name: item.icon, reverse}}
/>
```

Just need to change on this element:

https://github.com/react-native-training/react-native-elements/blob/32bf779930f928bf2a22658dcb9ca729535610d1/src/list/ListItem.js#L120

To:

```jsx
<View>
    <Icon
        type={leftIcon.type}
        iconStyle={[styles.icon, leftIcon.style && leftIcon.style]}
        name={leftIcon.name}
        color={leftIcon.color || colors.grey4}
        size={leftIcon.size || 24}
        reverse={leftIcon.reverse || false} <--- ### Add this guy
    />
</View>
```

**Comment by xavier-villelegier** [comment]
@gunnarblom In the future of RNE, the props of the `Icon` component won't be exposed through the `ListItem`, for simplicity and modularity. To follow these principles, I advise you to do this:

```jsx
<ListItem
    key={i}
    title={item.title}
    leftIcon={<Icon
      reverse
      name='ios-american-football'
      type='ionicon'
      color='#517fa4'
    />}
/>
```

As RNE already supports that, you will be prepared for future breaking changes about the exposed `Icon` props

**Comment by Monte9** [comment]
That's a great example @xavier-villelegier! 💯 Thanks for providing a good solution to the issue.
