### ISSUE TITLE
custom rightIcon based on logic

### ISSUE THREAD

**Issue by milon87** [react-native-training/react-native-elements#590]
Here is my list:
         ` <ListItem
                rightIcon={}
                containerStyle={{borderBottomWidth:0}}
              />
`
I have two types of right Icon based on logic. how can I put that?
(error image or ok image in the right side icon) 

any idea? TIA

**Comment by btav** [comment]
@milon87 have you tried something like the following?

```
  <ListItem leftIcon={{ name: isError ? imageOne : imageTwo }} />
```

**Comment by milon87** [comment]
@btav  yes but not working.
btw Thanks for your try.

**Comment by milon87** [comment]
yes working thanks.

**Comment by AvijitDutta95** [comment]
How can i hide rightIcon??? 
any suggestion please!

**Comment by iRoachie** [comment]
@AvijitDutta95 set the rightIcon prop to an empty View

**Comment by milon87** [comment]
hideChevron={true} make your right icon disappear
