### ISSUE TITLE
How to change background color on checked checkboxes 

### ISSUE THREAD

**Issue by AlmogRnD** [react-native-training/react-native-elements#591]
I can change the checked icon color but how can I change the background color for the checked box when it's checked?

**Comment by milon87** [comment]
have you tried checkedColor property?

**Comment by AlmogRnD** [comment]
@milon87 the checkedColor property changes the color for the checked icon, I would like to change the background color for the entire checkbox

**Comment by iRoachie** [comment]
You can use the `containerViewStyle` prop. Here you go @AlmogRnD https://snack.expo.io/B1-5mTNcZ

**Comment by AlmogRnD** [comment]
@iRoachie this is perfect thanks, I'm closing this

**Comment by badarshahzad** [comment]
is there any way to remove the container as I need just the check box as a radio button. I want to hide or remove the container shadow and border. Is there way to disable properties of checkbox?

**Comment by xavier-villelegier** [comment]
@badarshahzad You can use the `v1.0.0-beta5`. When there is no title, you won't have any container around the checkbox

**Comment by badarshahzad** [comment]
thank you @xavier-villelegier

**Comment by iRoachie** [comment]
You can just remove `padding` and `margin` on the `containerStyle` https://snack.expo.io/SkXeIJGB7
