### ISSUE TITLE
does it support expandable list?

### ISSUE THREAD

**Issue by milon87** [react-native-training/react-native-elements#593]
Actually, it is a feature request for the expandable list facility

"react-native-elements": "^0.15.0"

**Comment by iRoachie** [comment]
Could you explain what you mean by expandable list?

**Comment by milon87** [comment]
something like this. If a user clicks on an item, then it's expanded item will be shown.

![expandable_image](https://user-images.githubusercontent.com/3435314/30688031-e2ca7f30-9ede-11e7-831c-8bd0c8698ded.png)

**Comment by iRoachie** [comment]
We don't offer that functionality built-in. However, you can try [react-native-collapsible](https://github.com/oblador/react-native-collapsible) which does that exact behaviour.

**Comment by leonardo2204** [comment]
I know this is an old thread, but I need the same functionality on a <ListItem>.
Does it make sense to have a <ExpandableListItem> alike?
I mean, the library you provided is great, but it's an overkill to add a library just to expand a <ListItem>.
What do you think?

I'm more than happy to drop a PR with this feature if you think it makes sense!

Thanks

**Comment by iRoachie** [comment]
@leonardo2204 The logic for a collapsible component is pretty complex. I know because i manage the react-native-collapsible library. They're a lot of quirks especially with items that change dimensions while collapsed. I wouldn't really want to bring those types of issues in react-native-elements.
