### ISSUE TITLE
How to show badges in ListItem on condition bases! Help Needed

### ISSUE THREAD

**Issue by AvijitDutta95** [react-native-training/react-native-elements#594]
### Description

Is there any way to show badges on ListItem on condition bases! 
Like: If value > 0 ? I need to show badges on ListItem : if it is not then badges are not displayed

Any idea please! Help wanted

**Comment by Monte9** [comment]
Here is a related issue: https://github.com/react-native-training/react-native-elements/issues/590
Hope this helps.

**Comment by davekedar** [comment]
I have the same problem but turnery operator doesn't work please help @AvijitDutta95 @Monte9
