### ISSUE TITLE
How to make lines appear between button in Button Group?

### ISSUE THREAD

**Issue by pacozaa** [react-native-training/react-native-elements#595]
As in a document 
https://github.com/react-native-training/react-native-elements/blob/master/docs/API/button_group.md

The sample image looks nice and also has lines between each button in Button Group. But when I apply sample code from document itself. The border line between each button doesn't appear. How to make them appear?

Best,
Sarin

**Comment by pacozaa** [comment]
My progress of trying using `buttonStyle` property
![21741272_10212809829834675_4438157794602461731_o](https://user-images.githubusercontent.com/3154089/30357988-d9eebc1a-986b-11e7-92c7-1488293948bb.jpg)

There is still a gap between them. How to get rid off it? 

Best,
Sarin

**Comment by pacozaa** [comment]
Well I find a work around solution. Just set `backgroundColor` in `containerStyle` same as `borderColor` in `buttonStyle`. I am not sure if that is a best solution :)

**Comment by martinezguillaume** [comment]
Hi, this a well-know bug from react-native, more infos here: https://github.com/react-native-training/react-native-elements/issues/364. It'll be fix when react-native will fix the problem
