### ISSUE TITLE
FormInput RTL text while typing is not properly shown on screen

### ISSUE THREAD

**Issue by agent3bood** [react-native-training/react-native-elements#596]
### Description

1. Explain what you did
import FormInput and add it to a card,
when entering English text all is well, but when entering Arabic (rtl) text the text is rendered off the screen from the right.

2. What you expected to happen
the text should start appearing from the right edge of the FormInput
3. What actually happens
the text is not properly rendering while typing

Also please include the version of `react-native-elements` that you are using.
"react-native-elements": "^0.16.0",

### link.
https://snack.expo.io/HyjnRUI5-

### Solution
this is the best I could do to solve the issue
`inputStyle={{ textAlign: 'left' }}`

**Comment by Monte9** [comment]
@agent3bood RNE doesn't support RTL yet. Please follow the discussion here: https://github.com/react-native-training/react-native-elements/issues/505
