### ISSUE TITLE
please attach method to this component

### ISSUE THREAD

**Issue by gtaylor44** [react-native-training/react-native-elements#599]
While using the social icons, I encountered the following warning after attaching an onPress handler:

'please attach method to this component'

Is there a button version of this:
```
          <SocialIcon
            title='Sign in with Facebook'
            button
            type='facebook' />
          </View>
```

Or are we expected to wrap it like so:

```
        <TouchableWithoutFeedback onPress={this.facebookLogin}>
          <View>
          <SocialIcon
            title='Sign in with Facebook'
            button
            type='facebook' />
          </View>
        </TouchableWithoutFeedback>
```

**Comment by martinezguillaume** [comment]
In your example, you didn't provide any `onPress` prop, you need to do: 
```jsx
          <SocialIcon
            onPress={this.facebookLogin} // add this
            title='Sign in with Facebook'
            button
            type='facebook'
          />
```

**Comment by gtaylor44** [comment]
Yes, I missed that out of the example. That is what caused the aforementioned warning. Does or should SocialIcon have a role as a button?

**Comment by iRoachie** [comment]
@gtaylor44 You can check out the full properties here https://react-native-training.github.io/react-native-elements/API/social_icons/

**Comment by gtaylor44** [comment]
Hmm.. ok, interesting.
