### ISSUE TITLE
ListItem rightIcon only displays default icon

### ISSUE THREAD

**Issue by MrHubble** [react-native-training/react-native-elements#602]
I'm trying to use a different icon for `rightIcon`:

````js
<List>
  <ListItem
    title="Test"
    rigthIcon={{ name: 'done' }}
    leftIcon={{ name: 'done' }}
    />
</List>
````

I would expect to see the `done` icon the same as the `leftIcon` in my example, however, I think the default `chevron-right` is being displayed:

<img width="283" alt="screen shot 2017-09-15 at 5 57 57 pm" src="https://user-images.githubusercontent.com/2251631/30473008-189e7482-9a42-11e7-88cd-fb8dda9b2b93.png">

I was originally getting this problem on version 0.12.2. The problem still exists after upgrading to 0.16.0

The code difference between `rightIcon` and `leftIcon` is:

<img width="966" alt="screen shot 2017-09-15 at 6 23 04 pm" src="https://user-images.githubusercontent.com/2251631/30473325-68cf948a-9a43-11e7-817f-5e4b46a1ab17.png">

I'm making the **assumption** (I haven't worked out how to test this yet) that the `rightIcon.name` value is not being passed correctly. I see at the top of `react-native-elements/src/list/ListItem.js` we have:

````js
const {
  //I've omitted other values for example
   rightIcon,
   ...attributes
} = props;
````

but I'm not sure where and how these props are passed.

**Comment by xavier-villelegier** [comment]
Hey @MrHubble, try the following:
```jsx
<ListItem
  title={'Item 1'}
  rightIcon={<Icon name={'done'} size={20}/>}
/>
```

Result:
![img_bd058cdd7e58-1](https://user-images.githubusercontent.com/17592779/30477796-cd19d75a-9a0e-11e7-928c-e5479c2f5b4a.jpeg)


You must pass a component, not an object. I also advise you to do that for the left icons for [these reasons](https://github.com/react-native-training/react-native-elements/issues/589#issuecomment-329104669) 👍

**Comment by MrHubble** [comment]
aarrgghh, I lost so much time to a silly typo 😳 I really wish Github would allow us to delete embarrassing issues like this.

I'm now using the component as per your suggestion.

Thanks for taking the time to help. It's greatly appreciated.

**Comment by MrHubble** [comment]
@xavier-villelegier it might be worth mentioning that I could only get `onPressRightIcon` working with passing an object (`rightIcon={{ name: 'done' }}`).

I could **not** get `onPressRightIcon` working with passing a component (`rightIcon={<Icon name={'done'} size={20}/>}`).

**Comment by xavier-villelegier** [comment]
@MrHubble Yes obviously. By passing a component you **fully** control what is rendered as an Icon, the `ListItem` doesn't alter the component you pass. You have to specify the `onPress` on the `Icon` itself:

```jsx
<ListItem
  title={'Item 1'}
  rightIcon={
    <Icon
      name={'done'}
      size={20}
      onPress={() => console.log('Pressed !')}
    />
  }
/>
```

**Comment by MrHubble** [comment]
That makes complete sense. I'm not sure my brain is doing it's job. Time to step away from the keyboard.

**Comment by xavier-villelegier** [comment]
@MrHubble Haha np man. Take the time to understand the code of the `ListItem` and discover what happens [behind the scenes](https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L218) when you pass a component.
This can be non-intuitive at first sight but by doing that you really split the logic and use the component philosophy of React. 🙌

**Comment by Daveyjonez** [comment]
Is there a simple demo of toggling which `rightIcon` appears by using `onPress()` and updating it in the array that `ListItem` pulls from?

**Comment by iRoachie** [comment]
@Daveyjonez which version of react-native-elements you'll like the demo for?

**Comment by Daveyjonez** [comment]
Im running version `"^0.19.1"`

**Comment by xavier-villelegier** [comment]
@Daveyjonez [Is this](https://snack.expo.io/HJ7gzAw3G) what you're looking for ? Can you be more precise ?
