### ISSUE TITLE
How do you toggle with CheckBox? API documentations and example code doesn't show how to. 

### ISSUE THREAD

**Issue by francisngo** [react-native-training/react-native-elements#603]
### Description
I would like to have a list of checkboxes that when selected, will toggle as checked and submit the form afterwards. 

1. Explain what you did
Installed react-native-elements
2. What you expected to happen
When user clicks on button, it is checked or unchecks. 
3. What actually happens
Nothing happens when checkbox is clicked. It either is all selected or none at all.

Also please include the version of `react-native-elements` that you are using.
react-native-elements --version 0.16.0

### Reproduction Steps and Sample Code

```
constructor (props) {
    super(props);
    this.state = {
      checked: false
    };

    this.toggle = this.toggle.bind(this);
  }

  toggle() {
    this.setState({checked: !this.state.checked});
  }

<CheckBox
    center
    style={{backgroundColor: '#eaeaea'}}
    onPress={this.toggle()} || onIconPress={this.toggle()}
    checked={this.state.checked}
/>
```

Could you provide an example in the documentations on how you might toggle checkboxes?

**Comment by iRoachie** [comment]
CheckBox is a controlled component. Which means it's external state is update through updating the props. You have to manage your own state for the checked property.

Example snack here https://snack.expo.io/BkCWHXqqZ

You can read about controlled components here https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by francisngo** [comment]
Is there something I am missing? Because I have a very similar format but when I am clicking I am not getting any response. Do I need to add some sort of vector icons for the checks? 

Here is the whole component: 

```
import React, { Component } from 'react';
import { StyleSheet, View, Text, Image, FlatList, TouchableOpacity, ScrollView, Button } from 'react-native';
import { CheckBox, FormLabel, FormInput } from 'react-native-elements';

export default class InterestByCity extends Component {
  constructor (props) {
    super(props);
    this.state = {
      checked: false
    };
  }

  render() {
    let city = this.props.navigation.state.params.interests.city;
    let interests = this.props.navigation.state.params.interests[0].interests;
    return (
      <View>
        <ScrollView>
          <FlatList
            data={interests}
            keyExtractor={(interest, index) => index }
            renderItem={ ({ item }) =>
            <View style={{flex: 1, flexDirection: 'row'}}>
              <View style={{width: 100, height: 100}}>
                <Image
                  style={{width: 100, height: 100}}
                  source={{ uri: item.image_url}}
                />
              </View>
              <View style={{width: 200, marginLeft: 10}}>
                <Text style={{fontWeight: 'bold'}}>{item.name}</Text>
                <Text>{item.location.address1}</Text>
                <Text>{item.location.city} {item.location.state}, {item.location.zip_code}</Text>
                <Text>Rating: {item.rating}</Text>
                <Text>Category: {item.categories[0].title}</Text>
              </View>
              <View style={{
                flex: 1,
                justifyContent: 'center',
                alignItems: 'center',
                width: 50
              }}>
                <CheckBox
                  center
                  style={{backgroundColor: '#eaeaea'}}
                  checked={this.state.checked}
                  onPress={() => this.setState({
                    checked: !this.state.checked
                    })
                  }
                />
              </View>
            </View>
            }
          />
        </ScrollView>
      </View>
    )
  }
}

```

**Comment by francisngo** [comment]
It seems if I put the checkbox outside the FlatList, I am able to check it. But as I am mapping through each data, I am creating a new checkbox along with it. And it's causing the issue.

**Comment by iRoachie** [comment]
@francisngo You have to use multiple state variables. If you use `this.state.checked` for all your items, then if you change it; it's going to update all of them. This is more an architecture question than a problem with RNE, however, I'll still help.

Basically you need a unique value in your state for each checkbox. Since our list is coming through the props; in our constructor we can create the variables we need. Let's make `checked` an array. You can use a for loop to create an array the size of `interests`. Each position in the array will represent if the `interest` is checked or not. Next we can assign each position in our `renderItem` prop.

I'll leave you to figure out the rest! 
Here's a hint! `renderItem={ ({ item })` also has an index parameter! `renderItem={ ({ item, index })`

**Comment by fazeelzama20** [comment]
@iRoachie Hello, I am facing the same issue of checking one checkbox and all checkbox are getting selected in List. I have also read what you have said, i have created one array but i am not getting how to use for loop for checked[], here is my code, can you please help? forgive me if i am asking silly question.

`constructor(props){
          super(props);
          this.state={
            checked: [],
            isLoading: true,
            isLoadingFlatList: true,
            language: 'Actual'
        }
      }
 getFlatList(){
return( 
      <ScrollView>
                    <List containerStyle={{marginBottom: 20}}>
                        {
                            list.map((l, i) => (
                            <ListItem
                                key={i}
                                title={
                                    <CheckBox
                                        title={l.Text}
                                        onPress={this.press.bind(this, i,l.Text)}
                                        checked={this.state.checked}
                                    />}
                            />
                            ))
                        }
                    </List>
                </ScrollView>
            );
        }`

**Comment by iRoachie** [comment]
Hey @fazeelzama20, here's an example with FlatList https://snack.expo.io/ryQrlh54G. Remember to use the `extraData` prop in FlatList, as items in a FlatList are PureComponents

**Comment by rendy14s** [comment]
hai @iRoachie 

I have been see this https://snack.expo.io/ryL_6-DIG  or in your ( https://snack.expo.io/ryQrlh54G )
and implemented in my project is work 100% awesome, thanks.. 👍 

But i have problem this. how can i set checkbox is default `checked={true}` so the checkbox is default is true, the checkbox any have pict "cheklist" if true default. where the put value is true is value default its. in m checkbox ?


Regards 👍

**Comment by iRoachie** [comment]
Hey @rendy14s, could you explain a little more? I'm still a bit confused about what you're trying to achieve.

**Comment by rendy14s** [comment]
Hai @iRoachie

The checkbox value of checked is false. So First page load, the checkbox is uncheked. 


How can its set the value is true? So the first page load condition of checkbox is checked/checklist.

**Comment by iRoachie** [comment]
@rendy14s For it to be default true, just have it in the state array. https://snack.expo.io/H1L0d4DLz. In this example 'chickenwww' and 'rice' are initially checked

**Comment by rendy14s** [comment]
Hai @iRoachie

Oohhh i see..
Let me try.

Thanks before (:

**Comment by KunalPaul** [comment]
if you are using list view than have a look to this 

 state={
        Check:[]
    }

 componentWillMount() {
        var my_check = []
        array.forEach((folder) => {
            my_check.push(false)
        })
        this.setState({
            Check:my_check
        })
    }

than in your render do something like this
 <ListView
                    dataSource={Folder.cloneWithRows(this.state.folder)}
                    renderRow={(rowData,rowID) => 
                                                    <CheckBox
                                                        label='All'
                                                        labelBefore={true}
                                                        checked={this.state.Check[rowID]}
                                                        onChange={(checked) => {
                                                            this.setState({
                                                                Check:!this.state.Check[rowID]
                                                            })
                                                        }}
                                                        />
                                             
                                            </View>
                            }
                />

**Comment by xavier-villelegier** [comment]
@ZaneAspeling I think you should check [this Snack](https://snack.expo.io/ryQrlh54G) posted above

**Comment by iRoachie** [comment]
Hey @davekedar, would appreciate if you could create a new issue and link it to this one. Please don't forget to list what version of react-native-elements you are using, since component behaviour changes between versions.
