### ISSUE TITLE
ListItem does not look like an iOS ListItem

### ISSUE THREAD

**Issue by johot** [react-native-training/react-native-elements#605]
The ListItem component looks very different from the "real" iOS version. In iOS the separator line for example has an indent. Also the chevron is not pixel perfect to the iOS version.

Is this anything you guys are looking into? I would expect everything to be pixel perfect to the real iOS versions.

Thanks!

**Comment by iRoachie** [comment]
What’s your thoughts on this @Monte9 @xavier-villelegier @martinezguillaume.  I’m sure it’s an easy task. Just wondering if it’s intentionally styled this way

**Comment by johot** [comment]
Nice to see this getting labeled @Monte9 !

I am kind of new to react-native (coming from Xamarin) and immediately got frustrated when I didn't find any good way of making a regular ListItem (UITableViewCell) that looks _exactly_ like the iOS one (for use with new `FlatList`). The library that comes closest in terms of "looking right" is currently NativeBase but their ListItem had a lot of bugs and I like the API + documentation of react-elements more.

Anyway I think it would be really good for react-elements to be able to say "We have the most pixel perfect recreations of the iOS + Android components" :)

One nice goal would be to be able to recreate the iOS settings app perfectly.

**Comment by Monte9** [comment]
@johot I completely agree. I also think that this is a High Priority issue as we have been talking about getting this done for RNE for a while now but have not gotten to it yet. 

Let's try to use this issue to accelerate this into the next release. For starters.. can you link to a few of the apple guidelines and req for what a pixel perfect iOS ListItem is supposed to look like?

Also FYI, $50 from open collective to whoever wants to take this on and submit a PR for it.

**Comment by johot** [comment]
@Monte9 Great to hear you want this as much as I do ;) 

I'm up for the task! I might be able to create a PR for you, but I can also post my research here in case I don't have time to fix it myself. I will focus on making it look exactly like the native UITableViewCell so my focus will only be iOS for now.

One quick question before I get started, the `chevron-right` icon that we use now where does it come from? I guess the original iPhone chevron icon can't easily be extracted?

I'll keep posting my findings!

**Comment by iRoachie** [comment]
For reference there's https://github.com/aksonov/react-native-tableview, that uses the *actual* UITableViewCell

**Comment by xavier-villelegier** [comment]
Some useful documentations too:

Apple guideline about table views [here](https://developer.apple.com/ios/human-interface-guidelines/views/tables/) (quite abstract but gives some standards)
Google Material Design guideline about listing [here](https://developer.apple.com/ios/human-interface-guidelines/views/tables/)

**Comment by Monte9** [comment]
![iOS Settings](http://cdn.iphonehacks.com/wp-content/uploads/2017/06/iOS-10-vs-iOS-11-Settings.jpeg)

![Android Settings](https://img.gadgethacks.com/img/41/09/63625715036668/0/27-cool-new-features-changes-android-8-0-oreo.w1456.jpg)

Using the above images as references, let's make RNE as pixel perfect per platform as possible using the `ListItem` and `SearchBar` components.

**Comment by johot** [comment]
I've taken full resolution screenshots from my iPhone for reference measuring stuff in Paint.net now :)

The right settings image look very different? Different iOS versions? Never seen one with that large heading before?

My initial findings are that the `ListItem` that comes with react-native-elements are too large, have the wrong text color (it's gray but should be black) and the offset of the line and text are wrong. Working on finding the correct values now.

RNE vs iOS original:
![image](https://user-images.githubusercontent.com/17697920/30560022-e0ed01da-9cb6-11e7-902f-c08b84c5a117.png)

**Comment by Monte9** [comment]
Yes, the image on the right is of iOS 11. That's why you see an extra heading on top.

Awesome. Good findings. Way to go! Glad we are working on this issue with full steam ahead. Two of the other RNE core contributors @iRoachie and @xavier-villelegier are also going to be working on this so we have a lot of resources to get this completed soon.

**Comment by johot** [comment]
Ok, cool! Apple changing details every release will be a challenge but I think we should optimize for the latest iOS version(s). I have no idea if react-native-elements supports the accessibility settings now, I know some people will have larger text and so on, maybe a later problem. It looks like the iOS version has a larger font? Is that an accessibility thing or just that they changed the default... hmm.

Btw. how should we handle the indented line? It should only appear when in a group, so the top and bottom rows for example should go all the way. Does a concept for this exist now?

**Comment by Monte9** [comment]
@johot can you join our slack channel? We are having this same iOS 11 vs iOS 10 discussion among the core contributors.

Might be easier for you to join our slack and jump in on the conversation there. We can even discuss the details for the ListItem there. 

Here's a link to join: https://reactnativetraining.herokuapp.com/

**Comment by johot** [comment]
Will do!

**Comment by martinezguillaume** [comment]
I know a little bit about google design, I can do it for Android if you want ! (Pixel perfect of course)

**Comment by Monte9** [comment]
@martinezguillaume OMG!! Yes, please!! ❤️

**Comment by jarrx** [comment]
Any progress on this?

**Comment by xavier-villelegier** [comment]
@jarrx Have a look at #945 👍

**Comment by xavier-villelegier** [comment]
@jarrx We released `v1.0.0-beta4` with a rewritten `ListItem` ! 🔥
It is now closer to the iOS style.
Check out [the docs](https://react-native-training.github.io/react-native-elements/docs/listitem.html) and [the release notes](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta4) (the `ListItem` is not updated yet though)

Also thanks to @johot who helped us to specify this new `ListItem`.

**Comment by johot** [comment]
Wow great job guys! Sorry I havent had more hands on time with this but really glad the specifications helped! Looking forward to trying out the beta when I have time again and big congratulations for making this release!
