### ISSUE TITLE
Header leftComponent, how to trigger onPress?

### ISSUE THREAD

**Issue by eightyfive** [react-native-training/react-native-elements#606]
I'm wondering how to trigger an `onPress` event with the shortcut to set icons on Header component:
```
<Header
  leftComponent={{ icon: 'menu', color: '#fff' }}
  centerComponent={{ text: 'MY TITLE', style: { color: '#fff' } }} 
  rightComponent={{ icon: 'home', color: '#fff' }}
/>
```

I mean I don't see the use case where you would like to show an icon in the Header, without wanting to trigger some kind of action linked to it (`onPress`).

I understand passing a proper React component as `left/rightComponent` works, but I wonder what's the `icon` shortcut for?

**Comment by iRoachie** [comment]
Hey there @eightyfive. The properties of the components get passed directly down to the buttons underneath. Which means we can pass in `onPress` as a property like so:

```jsx
leftComponent={{
   icon: 'menu',
   color: '#fff',
   onPress: () => alert('ea'),
}}
```

See example here https://snack.expo.io/B1gcxU6cZ

**Comment by eightyfive** [comment]
That makes sense. Thanks!

**Comment by malikgenius** [comment]
Great Thanks, should have been added to original example, wasted an hour by trying to add button property into it, sorry i am new to RN. anyways great job elements guys .. you rock.

**Comment by davidhernandeze** [comment]
Hi, i need to call a component's function from the leftIcon onPress() event, how can i do that?

**Comment by mohak1990** [comment]
Need to execute function on call back arrow icon for Android.
