### ISSUE TITLE
Avatar cropped on ListItem onPress

### ISSUE THREAD

**Issue by AvijitDutta95** [react-native-training/react-native-elements#612]
### Description

When ListItem pressed Avatar icon get cropped, i can't understand what is problem over there. Basically i just set an Avatar for profile picture view and a text for name view. When its render first time its looks fine.

Code for ListItem render:

```
<ListItem
     containerStyle={{height: 70, backgroundColor: '#fff'}}
     title={<View style={{marginLeft: 25, marginTop: 8}}>
              <Text style={{fontSize: 18,color: '#2c3e50',fontFamily:'BalooBhai-
                           Regular'}}>
                  {makeFirstLetterCapitalFormat(item.userName)}
              </Text>
             </View>
            }
            rightIcon={<View style={{marginTop: 20}}>
                        <Image style={{width: 10, height: 14}}
                           source={require(`../icons/hdpi/menu.png`)}/>
                       </View>}
            avatar={<Avatar rounded medium
                        icon={{name: 'user', type: 'font-awesome'}}/>}
            onPress={() => this.onDetailsPress(item)}
   />
```

First time view:

![capture3](https://user-images.githubusercontent.com/26165120/30683218-24dc9116-9eca-11e7-8355-15de364e9c6f.PNG)

After onPress: 

![capture2](https://user-images.githubusercontent.com/26165120/30683227-2eaf2fc8-9eca-11e7-924e-d296c09cdcb1.PNG)

Please help me, i post this problem in stackoverflow also but no one responsed.

**Comment by xavier-villelegier** [comment]
Hey @AvijitDutta95, is it on iOS or Android (or both) ? Which version of `react-native-elements` are you using ?

**Comment by AvijitDutta95** [comment]
@xavier-villelegier , this is only on Android (I implement it later on iOS).
and "react-native-elements": "^0.16.0",

**Comment by xavier-villelegier** [comment]
@AvijitDutta95 What if you put `wrapperStyle={{ height: 70 }}` in your `ListItem` props ? You'll then have to change a bit the text position, but I think it solves cropped Avatar.

Btw RNE `0.17.0` was released this week 👌

**Comment by AvijitDutta95** [comment]
Thanks @xavier-villelegier , for your help, now it's works perfectly  👍
