### ISSUE TITLE
underlayColor does not respect borderRadius

### ISSUE THREAD

**Issue by h-marvin** [react-native-training/react-native-elements#613]
### Description

1. Explain what you did
Added a button with properties `borderRadius` set. I've also set the `borderRadius` on `containerViewStyle` and `buttonStyle`.

2. What you expected to happen
I expected the border radius to be applied, since the underlayColor property is pretty much useless otherwise when using in combination with a rounded button.

3. What actually happens
A rectangular container is being underlayed, meaning the border radius is being ignored.

I was running version 15 first, tried upgrading to 17 after, but that didn't resolve the issue.

### Reproduction Steps and Sample Code

```
<View style={{backgroundColor: "black"}}>
          <Button
            onPress={this.doSomething}
            disabled={false}
            title="UnderlayColorButton"
            buttonStyle={{height: 60, borderRadius: 50, backgroundColor: "white"}}
            underlayColor="red"
            borderRadius={50}
            textStyle={{color: "blue"}}
            containerViewStyle={{borderRadius: 50}}
          />
</View>
```

**Button:**
<img width="212" alt="default" src="https://user-images.githubusercontent.com/1161971/30722849-54c94392-9f01-11e7-99b2-87b6bca84aef.png">

**Button while being pressed with active underlay color:**
![active](https://user-images.githubusercontent.com/1161971/30722850-584d0724-9f01-11e7-8d13-8f82368500d6.png)

**Comment by xavier-villelegier** [comment]
Hey @h-marvin ✌️,

### Solution
The props you passed which are not in the documentation are passed to the `TouchableOpacity` component. This means that you can add a `style` props that will be passed.

Try to add this:

```jsx
<Button
  …
  style={{ borderRadius: 50 }}
  …
/>
```

### Result
![img_eefb7b794bdf-1](https://user-images.githubusercontent.com/17592779/30734564-ff2ae168-9f7b-11e7-9cef-48cf408583f0.jpeg)

### Snack demo
[Here it is](https://snack.expo.io/H1mxfHMib)

**Comment by h-marvin** [comment]
Thanks man! Much appreciated. 👌
