### ISSUE TITLE
Title is not positioned below image as in docs example image – Card Component

### ISSUE THREAD

**Issue by hellomarcoliver** [react-native-training/react-native-elements#618]
The title prop does not position itself below the image in the card component. This is unexpected and does not compare to the result shown in the official documentation: https://react-native-training.github.io/react-native-elements/API/card/

**My code:**
```
<Card
        key={argument1.id} 
        image={{ uri: argument1.uri }}
        title={argument1.text}
      >
        <Text style={{ marginBottom: 10 }}>
          Here we can add some image subtitles. Was far as it goes.
          The lines get pushed down.
        </Text>
        <Button
          icon={{ name: 'code' }}
          backgroundColor="red"
          title="View Now"
        />
      </Card>
```

**Results in:**
Title to be center on top of image

**Version**
0.17.0

**Comment by xavier-villelegier** [comment]
@hellomarcoliver Nice catch, I think the documentation is not up to date. 🤔

The title is supposed to appear on top of the card according to [the Card implementation](https://github.com/react-native-training/react-native-elements/blob/1f06e20e7742b87be696cf3921979afdfdd87315/src/card/Card.js#L55). You also have `featuredTitle` and `featuredSubtitle` to display some text above the image, but the only things rendered below the image are the children. This means that if you want to have a title below the image you have to do it yourself [like this](https://snack.expo.io/HJx5BSHs-).

**Comment by hellomarcoliver** [comment]
Thanks for the quick response, Xavier.
