### ISSUE TITLE
Unable to resolve module @expo/react-native-vector-icons/Materiallcons

### ISSUE THREAD

**Issue by sw-yx** [react-native-training/react-native-elements#620]
### Description

1. Explain what you did

I ejected a CRNA project that had react-native-elements installed ([this project](https://github.com/sw-yx/crossbones#npm-run-eject)), npm installed and linked react native vector icons and then ran it with `react-native run-ios`.

2. What you expected to happen

it should launch nicely in ios simulator

3. What actually happens

error as follows:

```
error: bundling failed: "Unable to resolve module `@expo/vector-icons/MaterialIcons` from `/Users/swyx/Desktop/webdev/fullstacksr/podcastRN/crossbones/node_modules/react-native-elements/src/buttons/Button.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."
```

Also please include the version of `react-native-elements` that you are using.

```
    "axios": "^0.16.2",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.0",
    "react-native-elements": "^0.17.0",
    "react-native-vector-icons": "^4.4.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-persist": "^4.10.0",
    "redux-thunk": "^2.2.0"
```

### Reproduction Steps and Sample Code

I can reproduce on my machine

---

# Extra notes

I know this looks similar to #412  but this one has "@expo" in front of it.. did you change the signature and accidentally leave in the reference to expo recently? I cant figure out why else this would be happening.. please help.

**Comment by xavier-villelegier** [comment]
@sw-yx Mmh yeah that's weird, as you can see [here](https://github.com/react-native-training/react-native-elements/blob/32bf779930f928bf2a22658dcb9ca729535610d1/src/buttons/Button.js#L14) we're not using `expo/vector-icons` in the `Button.js` file pointed out by the error.

Can you go to
```
/Users/swyx/Desktop/webdev/fullstacksr/podcastRN/crossbones/node_modules/react-native-elements/src/buttons/Button.js
```

and tell us if there is any reference to `expo` in this file ?

**Comment by sw-yx** [comment]
Hi Xavier, thanks so much for responding!!

no, there is no reference to `expo` there at all. i have uploaded this project [here](https://github.com/sw-yx/debugReactNativeElementsEjectedExpoBug) and this is ejected from my CRNA project [here](https://github.com/sw-yx/crossbones). I can replicate this when I eject from CRNA. 

Any other ideas I can look into for you? I am getting this error when I run `react-native run-ios` on my ejected app, that is the right procedure right? I needed to eject because i need to use react-native-fs and react-native-sound.

**Comment by xavier-villelegier** [comment]
Maybe try to clean install all your modules 🤔

In your root dir:
```
rm -rf node_modules yarn.lock package-lock.json && npm i
```

If this doesn't work, try adding the module it is complaining about, but I feel like it is a bit dirty to add a module which you can't find any references of in your code... `npm install @expo/vector-icons --save`

**Comment by sw-yx** [comment]
hmm ok. i thought this might be a more germane problem to RNElements but it seems you are confident that this is ejectable without any expo references. thank you.

**Comment by xavier-villelegier** [comment]
@sw-yx I have an ejected app running with RNE, but I kept ExpoKit. I think you've chosen the "I'd like a regular React Native project" during the detaching.

But yes you can use RNE without using Expo, so I'm quite confused that you get an error about that 🤔 If you have more clues do not hesitate !

**Comment by sw-yx** [comment]
give me a day to doublecheck and ill close the issue.

**Comment by foobar8675** [comment]
i am getting the same error using `react-native init`

**Comment by sw-yx** [comment]
funny how cleaning node modules is often the first answer on stackoverflow and github and also doesnt fix the issue 90% of the time...

i never fixed this and just ended up using something else instead. sorry i forgot to close the issue.

**Comment by iRoachie** [comment]
@sw-yx Sorry you didn't get it fixed. Mobile development is hard, in the fact that almost the entire developer experience is dependent upon if the local environment is set up just right. We couldn't replicate the issue with either expo or react-native-cli, so it's pretty hard to find the problem. 

Happy coding ✌🏽

**Comment by sw-yx** [comment]
no worries at all, thats why you guys exist!!

**Comment by xavier-villelegier** [comment]
I just git the issue on the `example` app of RNE and `npm install @expo/vector-icons --save-dev` did the trick for me, a bit late but can be useful for others !

**Comment by sw-yx** [comment]
i know i will return to this in the future so this is very handy for my future self, thanks xavier

**Comment by christianmarth** [comment]
Confim `npm install @expo/vector-icons --save-dev` fixes this issue for me as well...

**Comment by js1599** [comment]
Confim npm install @expo/vector-icons --save-dev fixes this issue for me as well... <-- Just confirming that it still does work

**Comment by wmlutz** [comment]
`npm install @expo/vector-icons --save-dev` doesn't fix the issue for me. And got the same problem @foobar8675 got. Started with an ejected CRNA app - tried `react-native init` with the same issue. Anyone figure this out yet?

**Comment by nehabhamare** [comment]
For me also, `npm install @expo/vector-icon --save-dev` does not help! I have this error in simulator:

![screen shot 2018-01-04 at 12 45 12](https://user-images.githubusercontent.com/21045231/34562251-c97a57a0-f14d-11e7-990e-a006a2413096.png)

If anyone has found a solution, please guide me! Thanks in advance!

**Comment by aschmid** [comment]
same issue here. i tried everything i could and i still get this error.

**Comment by LuckySambial** [comment]
same issue and I got this issue in every project
npm install @expo/vector-icons --save-dev didn't work :(

**Comment by LuckySambial** [comment]
I have solution for this, anyone interested @aschmid @nehabhamare @foobar8675  ?

**Comment by xavier-villelegier** [comment]
@aschmid @nehabhamare @foobar8675 @LuckySambial @wmlutz 
Oookay guys, so. I've tried to install RNE from scratch wit both vanilla and Expo react native projects. Here are the steps for me to make them work.

## Solution 1: Using `react-native-init`

1. Delete everything to be sure

`rm -rf node_modules yarn.lock packages-lock.json`

2. Install React Native Elements

`npm install react-native-elements --save`

> Do not forget to reinstall your node modules by running `npm install` or `yarn install`.

3. Install react-native-vector-icons

`npm install react-native-vector-icons --save`

4. Link react-native-vector-icons

`react-native link react-native-vector-icons`

I encountered some red screen of death during the process. Bunch of commands that helped me:

"Unrecognized font …" -> `rm -rf ios/build` (Didn't test on Android tho, should be the same logic with gradle build)

"Unable to resolve module …" -> `rm -rf node_modules && npm i && npm link react-native-elements` (Always remember the linking)

"Unable to resolve module …" -> `npm start -- --reset-cache`

## Solution 2: Using an Expo app (CRNA or Expo XDE)

1. Delete everything to be sure

`rm -rf node_modules yarn.lock packages-lock.json`

2. Install React Native Elements

`npm install react-native-elements --save`

> Do not forget to reinstall your node modules by running `npm install` or `yarn install`.

3. Install `@expo/vector-icons`

I personnaly didn't have to run this step, but for whatever reason this solves the issue for some of you so…

`npm install @expo/vector-icons --save`

## Solution 3: Using a detached `create-react-native-app` app

- If you choose a regular React Native project, use "Solution 1"
- If you choose to use Expo SDK (ExpoKit), use "Solution 2"

## Conclusion

After all these steps, in every cases, I have been able to run a simple code like this example

```jsx
import { Icon } from 'react-native-elements'

…

<Icon
  type="feather"
  name="activity"
/>
```

**Comment by iRoachie** [comment]
Amazing @xavier-villelegier can you put this in the docs somewhere?

**Comment by aschmid** [comment]
@xavier-villelegier thanks for this. unfortunately none of your solutions worked for me.
after a hours of banging my head against this what worked for was:

- clone the project from scratch
- setup a fresh node environment via nvm (i used v8.9.4)
- `rm -rf ios/build` (if pushed to the repo)
- `npm install react-native-cli -g`
- `npm install`
- `react-native run-ios`

**Comment by xavier-villelegier** [comment]
@aschmid Yea as specified in Solution 1, removing `ios/build` helped me too. A fresh install is always a good idea in desperate cases haha. I don't think that you needed to reinstall `react-native-cli` though, unless you needed to update it.

**Comment by aschmid** [comment]
@xavier-villelegier i had to reinstall the `react-native-cli` because i setup a completely new node env. but yes i agree that if would have used an existing one i wouldn't have to do that.

**Comment by RijaAdrian** [comment]
It doenst resolve my issue, I got the same and then I installed @expo/vector-icons BUT IT ASK ME TO INSTALL EXPO. I had create my project using react-native cli

**Comment by sw-yx** [comment]
I think this issue Is no longer helpful. I suggest we lock it and have people submit more descriptive error messages.

**Comment by iRoachie** [comment]
For any further questions please submit a new issue. Thanks!
