### ISSUE TITLE
Cannot add multiple children to header

### ISSUE THREAD

**Issue by MatthewG0** [react-native-training/react-native-elements#622]
### Description

According to the [documentation](https://react-native-training.github.io/react-native-elements/API/header/#header-with-custom-components-passed-in-as-children) you can add components passed in as children.

```
<Header>
  <MyCustomLeftComponent />
  <MyCustomCenterComponent />
  <MyCustomRightComponent />
</Header>
```

However this results in an error: 

>  Invalid prop children of type array supplied to Header, expected a single React Element.

This is because [in the code](https://github.com/react-native-training/react-native-elements/blob/master/src/header/Header.js) the `propType` of `children` is defined as `element` which requires only a single child.

### Solution

If this is not possible the documentation should be updated.  Otherwise the `propType` should be updated to accept multiple children.

**Comment by iRoachie** [comment]
Thanks for reporting @MatthewG0, will be in next release. Feel free to try out the next branch in the meantime

**Comment by iRoachie** [comment]
Fixed in v18.0.0

**Comment by omidfi** [comment]
I'm having a similar issue, at least by its looks :) 
Great project by the way, thanks a a lot :) 
```
Warning: Failed prop type: Invalid prop `children` of value `[object Object],[object Object],[object Object]` supplied to `Header`, expected one of [null,null].
```

With this: 

```   
     <Header>
          <Icon
            name="help"
            color="#ffffff"
            onPress={() => this._setModalVisible(true)}
          />
          <Text style={{ color: '#ffffff' }}>Bonobo Budget </Text>
          <Text>hello</Text>
        </Header>
```
Using version 0.18.2

**Comment by arainyu** [comment]
@omidfi  I have the same issue in v0.18.5

**Comment by xavier-villelegier** [comment]
@omidfi @arainyu Oops, you're right guys.
This has just been fixed again in https://github.com/react-native-training/react-native-elements/commit/1cf5896e510ca62ce917a962970773df386e8379.

You can check if it works by putting this in your `package.json`
```
"react-native-elements": "git://github.com/react-native-training/react-native-elements.git#next",
```

Should be in the `v0.19.0` 👍

**Comment by xavier-villelegier** [comment]
`v0.19.0` is out 🤙
