### ISSUE TITLE
How to set Forminput multiline?

### ISSUE THREAD

**Issue by pacozaa** [react-native-training/react-native-elements#623]
I am trying to create textarea ui from Forminput multiline like this
```javascript
<FormInput
   style={{
     multiline: true,
     numberOfLines: 4
   }}
/>
```

It's not working

**Comment by bulby97** [comment]
<FormInput multiline />

**Comment by iRoachie** [comment]
@pacozaa `multiline` and `numberOfLines` aren't from the style object. They are props of the [`TextInput` component](http://facebook.github.io/react-native/releases/0.48/docs/textinput.html#props). 

Therefore you'll need to pass them in like @bulby97 suggested.

**Comment by pacozaa** [comment]
Thank you @iRoachie @bulby97 
It wokrs :)

One more question,
How to get rid off an input line?

I try this, it doesn't work

```javascript
inputStyle={{                
 borderWidth: 0
}}
```

**Comment by bulby97** [comment]
containerStyle={{ 
  borderBottomWidth: 0 
}}

**Comment by pacozaa** [comment]
@bulby97 doesn't work

**Comment by bulby97** [comment]
Are you sure ? 

```
<FormInput
   onChangeText={changeNote}
   inputStyle={{ width: '100%', color: 'black' }}
   containerStyle={{ borderBottomWidth: 0 }}
   value={note}
   multiline
        />
```

This removes the bottom line

**Comment by iRoachie** [comment]
You’ll need to use the underlineColorAndroid prop on Android to hide the line

**Comment by pacozaa** [comment]
@bulby97  I am sure but now I know why
 https://github.com/react-native-training/react-native-elements/blob/1f06e20e7742b87be696cf3921979afdfdd87315/src/form/FormInput.js#L142

is indicated for iOS only and I am working on android.

@iRoachie This works for me. Thank you
```javascript
<FormInput
   multiline
   underlineColorAndroid = {0}
 />
```
