### ISSUE TITLE
FormInput multiline exceeds size

### ISSUE THREAD

**Issue by bulby97** [react-native-training/react-native-elements#624]
I have the following: 

```
<Box>
    <FormLabel>Contenu de la note - {title} </FormLabel>
    <FormInput
          onChangeText={changeNote}
          multiline
     />
</Box>
```

But for an unknown reason, the content exceeds the container.

![image](https://user-images.githubusercontent.com/3509412/30862655-1708b7aa-a2cf-11e7-846b-06480fb2c93f.png)

**Comment by iRoachie** [comment]
@bulby97 The formInput by default takes the width of the screen.

https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormInput.js#L16

https://github.com/react-native-training/react-native-elements/blob/master/src/form/FormInput.js#L156

To override this behaviour you can pass in your own `inputStyle` with a `width: '100%'`

**Comment by bulby97** [comment]
Awesome thank you !
But it's a weird behaviour imho

**Comment by iRoachie** [comment]
Yea it is. Hopefully, in the future, it can be changed but right now percentages are only allowed in react-native v0.43 and above. So if we change it right now it'll break the code for others still on those versions. It will happen eventually though.

@Monte9 @xavier-villelegier

**Comment by Monte9** [comment]
Yeah, I rewrote `FormInput` -> `Input` component in v1. So it should def much better once that's out.
