### ISSUE TITLE
Buttons can't render, Ripple drawable is not availabile on android API <21 

### ISSUE THREAD

**Issue by osiloke** [react-native-training/react-native-elements#625]
### Description

1. Explain what you did
I used the button component in an android os < API 21
2. What you expected to happen
my app should run :)
3. What actually happens
app crashed complaining about Ripple not available in API < 21

Also please include the version of `react-native-elements` that you are using.
I'm using the master version, Latest commit 1f06e20

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.
Update this line
https://github.com/react-native-training/react-native-elements/blob/cd3c2f053fd7ef7bbc1a449082a3a4d5db498924/src/buttons/Button.js#L127
to 
```
 if (Platform.OS === 'android' && Platform.Version >= 21 && (borderRadius &&...

```

**Comment by iRoachie** [comment]
Dup of #597
