### ISSUE TITLE
readonly not working on rating components?

### ISSUE THREAD

**Issue by Alewis103** [react-native-training/react-native-elements#626]
Hey, so I noticed that on the rating component in RN elements the readonly prop doesn't work is there something I'm doing wrong. In other words, I'm still allowed to alter the rating even though I  set the readonly prop to true.  I provided a snack link below

https://snack.expo.io/r1b3qhKob

**Comment by martinezguillaume** [comment]
In the new version 0.17.0, `readonly` prop works. Verify your react-native-elements version !

**Comment by Alewis103** [comment]
You hit the nail on the head with this, thank you !

**Comment by badarshahzad** [comment]
I am using ^0.19.1 facing the same issue but I run your code [here ](https://snack.expo.io/rJldqHqjZ) in which you are using 0.17.0 as you mentioned in commit.
I am using the latest version I think should face this issue could you please open this issue again. To open new issue will not good I think.

**Comment by iRoachie** [comment]
@badarshahzad The prop works as well in 0.19.1, here's the same snack using 0.19.1 https://snack.expo.io/HJ3ZCeRQX

**Comment by badarshahzad** [comment]
But honestly readonly property is not working for my version. Let me give a minute I send you snippet and with giff. I think it clear give you glimpse of what is going on my cell phone. :+1:

**Comment by badarshahzad** [comment]
@iRoachie  Sorry for being late to share the problem video. Can you please watch this video? I am still facing the same error.

**Comment by badarshahzad** [comment]
Thank you @iRoachie this all due to write variable names in camel case :+1: :rofl:
