### ISSUE TITLE
FormInput multiline not expand in Android

### ISSUE THREAD

**Issue by wayne1203** [react-native-training/react-native-elements#627]
I'm using 0.17.0.
It's work normally in iOS but Android I got some problem with it.
It will not expand the height of Input area when I enter new line.

I entered 3 lines in the input area, but I got 2 lines only.
![screenshot_2017-09-28-17-57-09](https://user-images.githubusercontent.com/8578341/30960841-d6199b5c-a476-11e7-8393-bb3ace36121c.png)

And here is my code..
```
<FormInput
	containerStyle={styles.textArea}
	multiline={true}
	underlineColorAndroid = {0}
	blurOnSubmit={false}
	onChangeText={(text) => {
		this.text = text;
	}}
	placeholder={Locale.input + "..."}
/>
// Style
textArea: {
	flex: 1,
	marginLeft: 10,
	marginRight: 10
}
```

**Comment by martinezguillaume** [comment]
Thanks for the report, I'll check that 😘

**Comment by iRoachie** [comment]
Closing this as external, as there's no way for us to act on this.
