### ISSUE TITLE
How ignore Deprecation warning

### ISSUE THREAD

**Issue by jose920405** [react-native-training/react-native-elements#629]
I'm using `Side menu` because `DrawerNavigator` inside `react-navigation` don't have the functionality that i needed. But the warnings are really annoying. I wish I could hide them, is it possible?

![simulator_screen_shot_sep_29__2017__14 31 07](https://user-images.githubusercontent.com/12536184/31032757-ede9a798-a522-11e7-9451-ff76e803135f.png)

**Comment by Monte9** [comment]
@jose920405 you can just add `console.disableYellowBox = true;` to your index.ios.js /index.android.js file and it should ignore all the yellowBox warnings.

<img width="821" alt="screen shot 2017-09-29 at 1 35 30 pm" src="https://user-images.githubusercontent.com/7840686/31035009-408e2a26-a51b-11e7-8cb3-49d78df37e04.png">

Although be advised that RNE is going to be removing the `Side menu` component in the 1.0 release. So if you continue to use it, you will have to install Side menu from it's own package here: https://github.com/react-native-community/react-native-side-menu. Hope this helps.
