### ISSUE TITLE
Button.js sources for assign must be an object

### ISSUE THREAD

**Issue by LoganArnett** [react-native-training/react-native-elements#630]
### Description

1. Upgrading dependencies in app
2. Everything to continue to work
3. Now have error: "In this environment the sources for assign MUST be an object."

The stack trace points to `Button.js:98:6`

Current `package.json`
```json
"react": "^16.0.0-alpha.12",
"react-native": "^0.48.4",
"react-native-elements": "^0.17.0",
"react-native-vector-icons": "^4.4.0",
```

Not sure how to approach this

**Comment by ianlenehan** [comment]
I dropped back to v0.16.0 which stopped the error. I don't know if it's related to `iconRight` needing to be an object, which is mentioned as a breaking change. I'd try that but I'm not sure what that's supposed to look like.

**Comment by chengsieuly** [comment]
source code snippet for button.jsx
```
let rightIconElement;
  if (iconRight || rightIcon) {
    if (!rightIcon) {
      rightIcon = iconRight;
    }
    let Icon;
    if (iconComponent) {
      Icon = iconComponent;
    } else if (!rightIcon.type) {
      Icon = MaterialIcon;
    } else {
      Icon = getIconType(rightIcon.type);
    }
    rightIconElement = (
      <Icon
        {...rightIcon} // <-- the key/values of rightIcon eventually becomes props
        color={rightIcon.color || 'white'}
        size={rightIcon.size || (large ? 26 : 18)}
        style={[styles.iconRight, rightIcon.style && rightIcon.style]}
      />
    );
  }
```

Based on the logic for composing the right icon, `rightIcon` or `iconRight` needs to be an object. Under the hood, it's trying to assign the Icon object with extra key/values so you will receive that error if you try to destructure let's say a string. So, if you upgrade to latest and use object instead, and you see your icon render and receive no error, that is a sign that you are using the button prop correctly =)

**Comment by LoganArnett** [comment]
Interesting, I also was able to drop back to xcode 8 and it worked without making any other changes, not sure why

**Comment by iamthuypham** [comment]
In case someone runs into this issue.

I think that the [document](https://react-native-training.github.io/react-native-elements/docs/button.html) for Button is quite outdated.

Also, there is no `arrow-right` icon in `./glyphmaps/MaterialIcons.json` :rofl: , so there should be an appropriate error message such as `Can not find arrow-back in Material Icon list`

Here is a working code I used.
```
<Button
  iconRight= {{
      name='arrow-back', 
      size: 50,
      color: 'red'
  }}
  title='BUTTON WITH RIGHT ICON'
/>
```

"react-native-elements": "^0.19.1",
"react-native-vector-icons": "5.8.0",

**Comment by iRoachie** [comment]
Hey @iamthuypham thanks for bringing that up. Would you willing to make a PR that updates the docs.

**Comment by iamthuypham** [comment]
@iRoachie

**Comment by iRoachie** [comment]
Sure @iamthuypham, if there's any changes you think we should make, I'd be glad to hear about them
