### ISSUE TITLE
ListItem textInputAutoCapitalize wrong propType

### ISSUE THREAD

**Issue by raduflp** [react-native-training/react-native-elements#631]
ListItem textInputAutoCapitalize has a propType inconsistent with [TextInput autoCapitalize](https://facebook.github.io/react-native/docs/textinput.html#autocapitalize)

if you pass a bool value to textInputAutoCapitalize  => TextInput throws a warning
if you pass a string value to textInputAutoCapitalize  => ListItem throws a warning

in ListItem.propTypes we should have 
`textInputAutoCapitalize: PropTypes.oneOf([ 'none', 'sentences', 'words', 'characters' ]),`

**Comment by iRoachie** [comment]
Fixed in v18.0.0

**Comment by mo22** [comment]
Hi, index.d.ts should be updated as well.

**Comment by iRoachie** [comment]
Thanks @mo22 fixed in https://github.com/react-native-training/react-native-elements/commit/11452143d64b94f95b6f8394c2a887d492669843
