### ISSUE TITLE
No such file or directory...opencollective.js

### ISSUE THREAD

**Issue by RockinRonE** [react-native-training/react-native-elements#633]
### Description

In a new Expo project I installed react native elements like so `npm i --save react-native-elements` and the installation failed. 

![screen shot 2017-10-02 at 9 49 10 am](https://user-images.githubusercontent.com/8163241/31083381-2a1c6332-a757-11e7-8772-f50846b62a6b.png)

It's a new project, so I'm not sure what would be causing this.

**Comment by iRoachie** [comment]
@xavier-villelegier Can you check this out?

**Comment by prabhu** [comment]
I am happy to donate $100 or £100 today if you can remove that useless open collective message and avoid breaking every users of your library.

**Comment by iRoachie** [comment]
Will look into this immediately

**Comment by iRoachie** [comment]
Update guys. A temporary fix was made. Just waiting on the core maintainer to publish a new version in about 15-20 minutes. In the meantime, you can use the version directly from master.

`npm i https://github.com/react-native-training/react-native-elements.git --save`

**Comment by pirosoft** [comment]
with npm i https://github.com/react-native-training/react-native-elements.git --save
give me the same error
![cattura](https://user-images.githubusercontent.com/3637374/31086330-d77081b6-a799-11e7-9d4d-a7a0151d1d3c.JPG)

**Comment by prabhu** [comment]
Can you use 1.0.3 and remove the caret symbol in package.json please.

**Comment by iRoachie** [comment]
That's likely a local cache issue @pirosoft I just made a new project and run the above command. Try removing your node_modules, package.lock, yarn.lock and try again

**Comment by prabhu** [comment]
They have [unpublished](https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-333577821) 1.0.4. This drama is now over unless opencollective pushes another broken build. In any case, it goes to show how vulnerable all major packages including storybook and yours are. Why are these not optionalDependencies?

**Comment by iRoachie** [comment]
Sorry guys had to experience this. Will look into the future at better ways of dealing with external dependencies. 

Closing this as external and resolved with the unpublish of 1.0.4 of opencollective.

**Comment by pirosoft** [comment]
my packahe.json file:
{
  "name": "swipe",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"
  }
}

i remove  node_modules, "npm cache clear" after "npm install" and "npm i https://github.com/react-native-training/react-native-elements.git --save" this resolve the problem of npm installation.
But if a try to open app from Expo give me a problem (blue screen with connection error on emulator) i uninstall e reinstall the 0.16.0 version and this resolve the problem, i don't know why

**Comment by iRoachie** [comment]
@pirosoft The problem was with the opencollective dependency that we were using. The owner of the library has then since removed the bugged version of the library, so everything should be as normal now.

For more information, you can follow the issue [here](https://github.com/opencollective/opencollective-cli/issues/3#issuecomment-333577821)

**Comment by Monte9** [comment]
@iRoachie thanks for jumping on this and helping triage it quickly. 💯 

@prabhu feel free to donate at our open collective here: https://opencollective.com/react-native-elements
