### ISSUE TITLE
Disabled FormInput

### ISSUE THREAD

**Issue by ckim16** [react-native-training/react-native-elements#638]
Hi,

Is there a way to disable `FormInput`? I don't think I see it in the docs. If there is not, would it be a good idea to have that implementation?

Currently, I set `value` in `FormInput` props but I am still able to delete it and the value gets reset to original value.

Just a little thought that I believe it will help improve this library...

**Comment by xavier-villelegier** [comment]
Hey @ckim16 👋
All the props you pass to `FormInput` are passed to the `TextInput` of React Native.
You can use the [`editable`](https://facebook.github.io/react-native/docs/textinput.html#editable) props to simulate a disabled `FormInput`.
Here is [a quick example](https://snack.expo.io/HJ6yEVM2Z) that can be improved playing with styles.

**Comment by Monte9** [comment]
That's a good example.

Thanks for putting together the snack demo @xavier-villelegier! 👍
