### ISSUE TITLE
Centered an icon for a button component

### ISSUE THREAD

**Issue by ckim16** [react-native-training/react-native-elements#639]
Hi all,

First of all, I was going through the docs to figure out how to center an icon inside of a button without a title and, to me, this seems kind of confusing.
<img width="731" alt="screen shot 2017-10-03 at 4 52 27 pm" src="https://user-images.githubusercontent.com/15335445/31154367-7be7b716-a85b-11e7-8380-fe2061acfed7.png">
So when I was looking at the `title` props, default is `none` but in the description it says `(required)`. My button component still works without a `title` prop but I cannot center my icon inside of the button. 

```
export default class SomeClass extends Component {
	render() {
		return (
			<View>
				<FormLabel>USER</FormLabel>
				<Button
					buttonStyle={styles.button}
					icon={{name: 'user', type: 'font-awesome'}}
				/>
			</View>
		);
	}
}

const { width, height } = Dimensions.get('window');
const styles = StyleSheet.create({
	button: {
		width: width - 320,
		alignSelf: 'flex-end',
		borderRadius: 3
	}
});
```
I tried adding `style` inside of `icon` prop in the `Button` that still did not work.

Does anyone have thoughts or advices for this issue?

Thanks

**Comment by xavier-villelegier** [comment]
Hi @ckim16, why not using the [Icon component](https://react-native-training.github.io/react-native-elements/API/icons/) if you don't need any `title` ?

**Comment by ckim16** [comment]
@xavier-villelegier Yes, this is exactly what I need. I really appreciate it. But still, the docs say that an icon inside of a button component can be centered if there is no title and I was stuck with that part. Respectfully, that may need to be reviewed.
<img width="690" alt="screen shot 2017-10-04 at 9 04 52 am" src="https://user-images.githubusercontent.com/15335445/31186302-215b68f0-a8e3-11e7-8541-a7a11394ec6e.png">

**Comment by xavier-villelegier** [comment]
Yep you're right, this is confusing. In the `v1` the `Button` will be much more simple and hopefully the documentation too !

**Comment by iMaciah** [comment]
What will be the future of this issue?

Centering an icon when there's no text in the button makes sense, sure you can still use an icon and colored a view behind it. I just think centering would be simpler.

**Comment by xavier-villelegier** [comment]
Just FYI, in the `v1.0.0-beta4` Button, the icon should be centered if you provide `title={null}` or `title=""`
