### ISSUE TITLE
White square on Header icon press

### ISSUE THREAD

**Issue by OrDuan** [react-native-training/react-native-elements#640]
### Description

1. Explain what you did  
**I'm using the `Header` component with an icon on the right on android, when pressing(without releasing the button's icon becomes a white square.**

![imageedit_3_7874997321](https://user-images.githubusercontent.com/5006049/31166709-4bea68c2-a8f8-11e7-9ba1-30d7f2e35054.jpg)

2. What you expected to happen - **The icon shouldn't change on pressing**

Also please include the version of `react-native-elements` that you are using. 
**react-native-elements 0.16.0**
**react-native 0.48.1**

### Reproduction Steps and Sample Code

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.
```
      <View>
        <Header
          outerContainerStyles={styles.topMenu}
          centerComponent={{text: 'Events', style: {color: '#fff', fontWeight: 'bold', fontSize: 18}}}
          rightComponent={{icon: 'search', color: '#fff', onPress: this.toggleFiltersBox}}
        />
      </View>
const styles = StyleSheet.create({
    topMenu: {
    height: 53,
    backgroundColor: '#64b5f6',
  },
)}
```
### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.
**Nope**

**Comment by xavier-villelegier** [comment]
Hey @OrDuan 
You need to set the `underlayColor` of the touchable view used behind the scenes

You can do this:
- using an object as you did:

```jsx
<View>
    <Header
      outerContainerStyles={styles.topMenu}
      centerComponent={{
        text: 'Events',
        style: {color: '#fff', fontWeight: 'bold', fontSize: 18}
      }}
      rightComponent={{
          icon: 'search',
          color: '#fff',
          onPress: this.toggleFiltersBox,
          underlayColor: '#64b5f6' // <-- this does the magic
      }}
    />
</View>
```
- or using the `Icon` component`, which is the way RNE is going to prioritize in the future:

```jsx
<View>
  <Header
    outerContainerStyles={styles.topMenu}
    centerComponent={{
      text: 'Events',
      style: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
    }}
    rightComponent={
      <Icon
        name="search"
        color='#fff'
        onPress={this.toggleFiltersBox}
        underlayColor={'#64b5f6'}
      />
    }
  />
</View>
```

Here is a [snack demo](https://snack.expo.io/r1rkkaQnW) ✌️

**Comment by Monte9** [comment]
Thanks for the detailed explanation @xavier-villelegier! 💯 

@OrDuan hope this helps.

**Comment by milon87** [comment]
headerRight:
            <TouchableOpacity  onPress={() => navigation.navigate("DrawerOpen")}>
                <Icon
                    containerStyle={{paddingRight: 16}}
                    name="filter-list"
                    size={30}
                    color="white"/>
            </TouchableOpacity>,

**Comment by rashikaranpuria** [comment]
Can we make the underlay circular or add padding to the underlay?

**Comment by ManuelTFviajez** [comment]
The solution mentioned above will work unless an **onPress** callback is defined for the wrapped Icon component:
`<Icon
            name="ccw"
            type="entypo"
            size={standardHeaderIconSize}
            iconStyle={{ color: '#FFFFFF' }}
            onPress={() => {}}
            underlayColor="rgba(255,255,255,0)"
          />`
In this case, a white underlay color is created and overwrites the one defined in the Touchable wrapper.
**Solution**: as in the snippet above, just define a transparent underlayColor everytime you define an onPress callback on the Icon.
