### ISSUE TITLE
Add support for Telegram social icon

### ISSUE THREAD

**Issue by NimaSoroush** [react-native-training/react-native-elements#644]
Would that be possible to add support for [Telegram](https://telegram.org/) as social network icon?

**Comment by iRoachie** [comment]
Hey @NimaSoroush our icons come from the react-native-vector-icons package. If there's an icon you want that they don't have, feel free to reach out at their repo.

**Comment by NimaSoroush** [comment]
Awesome, I should have figured it out by myself. Thanks @iRoachie, will raise it with them
