### ISSUE TITLE
SearchBar inside header title

### ISSUE THREAD

**Issue by agent3bood** [react-native-training/react-native-elements#645]
### Description
I want to add SearchBar component as a headerTitle for react-navigation

1. Explain what you did
see snack
2. What you expected to happen
Search bar will take full width of the header
3. What actually happens
SearchBar is shrinked even if I change the width in headerTitle or headerStyle

Also please include the version of `react-native-elements` that you are using.
"react-native-elements": "^0.16.0",

### Reproduction Steps and Sample Code
https://snack.expo.io/SkoH8l5hW

**Comment by agent3bood** [comment]
Also same problem when using it with Header component
https://snack.expo.io/BJlnvx52b

**Comment by xavier-villelegier** [comment]
@agent3bood Sorry for the delay. You can use the `header` props from `react-navigation`.
You can have a look at [this example](https://snack.expo.io/H16d0uipb).

**Comment by Monte9** [comment]
Thanks for putting together the snack @xavier-villelegier! It's great that you can just embed it into the header in `react-navigation`.
Hope this helps you @agent3bood.

I have already added your snack demo [here](https://github.com/react-native-training/react-native-elements/issues/681#issue-269800636). In the future, let's try to update that list as you create more snack demos for issues. thanks.

**Comment by agent3bood** [comment]
Thanks all for the effort to help. 
What I wanted is to put the search bar in the header title, so the header will have its right and left components(back button and menu button).

**Comment by xavier-villelegier** [comment]
@agent3bood it is just a matter of styling then. Check [this demo](https://snack.expo.io/S1QfebsCZ).

**Comment by sixmoraltales** [comment]
@xavier-villelegier Thanks for this example. Seems to work UI wise, however, because the searchBar is in the navigation header, onChangeText no longer has access to my class methods via "this". Any suggestions for how to get around the fact that navigationOptions has no access to the class context? (note: I am using native-base instead of react-native-elements)

**Comment by TobalOW** [comment]
Hi guys!, how you handle the text input inside the header ?
