### ISSUE TITLE
My button icons are not showing up. What appears is a small box with an X in the middle.

### ISSUE THREAD

**Issue by phantoxe** [react-native-training/react-native-elements#652]
import { Button } from 'react-native-elements'

<Button
  raised
  icon={{name: 'cached'}}
  title='BUTTON WITH ICON' />

It is very simple right? Can u help me?

Thanks folks

**Comment by iRoachie** [comment]
No problem here.
![simulator screen shot - iphone 6 - 2017-10-12 at 14 38 03](https://user-images.githubusercontent.com/5962998/31513042-f8b7dc8e-af5a-11e7-8fea-dc07723fbdf4.png)

Make sure you link react-native-vector-icons if you're on the default react-native-cli project.  https://github.com/react-native-training/react-native-elements/blob/master/default_installation.md

**Comment by phantoxe** [comment]
I already install the icon-vectors... 

@iRoachie i need import something in my file? Thanks for your attetion?

**Comment by iRoachie** [comment]
Okay did you **link** it as well? `react-native link react-native-vector-icons`.

After doing that you have to rebuild the app. `react-native run-ios` or `react-native run-android`

**Comment by phantoxe** [comment]
@iRoachie thanks man... works perfect... and i have one more question if you can help me... check the image below... i want put a marginTop in my button... but now it is showing up the WHITE BACKGROUND... weird... :-( 

containerViewStyle={{borderRadius:25, marginTop:10}}
buttonStyle={{borderRadius:25, marginTop:10}} 

How can i do this? without this background wierd...

![whatsapp image 2017-10-12 at 15 53 54](https://user-images.githubusercontent.com/29681268/31513819-db5320ee-af65-11e7-82b4-a383277962a3.jpeg)

**Comment by iRoachie** [comment]
What version of react-native-elements are you on?

**Comment by arctushar** [comment]
Android module react-native-vector-icons is already linked

but still not showing

**Comment by DeaVenditama** [comment]
thanks @iRoachie , your suggestion to rebuild the app works for me, .. its really helpfull for someone who started using react native elements

**Comment by iRoachie** [comment]
@DeaVenditama Glad I could help! :)
