### ISSUE TITLE
How Can i Change the FormLabel color?

### ISSUE THREAD

**Issue by phantoxe** [react-native-training/react-native-elements#653]
Hi Folks... i put this Style in my FormLabel... but is not working...

<FormLabel
              containerViewStyle={{color: '#fff'}}
              labelStyle={{color: '#fff'}}
              >E-mail            
              </FormLabel>

I received a WARNING message "Failed prop.type: Invalid props.style.key" color supplied to View...

What i did wrong please?

**Comment by DaveCole** [comment]
Use labelStyle only and not containerViewStyle.
