### ISSUE TITLE
Pesky white line below <Header />

### ISSUE THREAD

**Issue by igorbrandao** [react-native-training/react-native-elements#654]
#### _What I did?_

Used the `<Header>` component with the following:

**PROPS**:
```Javascript
<Header
  outerContainerStyles={styles.headerOuterContainer}
  innerContainerStyles={styles.headerInnerContainer}
  leftComponent={<ReturnButton style={styles.leftButton} />}
  centerComponent={{ text: '', style: styles.headerTitle }}
  rightComponent={<AddButton style={styles.rightButton} />}
/>
```

**STYLES**:
```Javascript
styles: {
  headerOuterContainer: {
    padding: 0,
    backgroundColor: '#03A9F4'
  },
  headerInnerContainer: {
    justifyContent: 'space-between'
  },
  headerTitle: {
    bottom: 10,
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: 'bold',
    position: 'relative'
  },
  headerLeftButton: {
    right: 10,
    paddingLeft: 10,
    position: 'relative',
    backgroundColor: '#03A9F4'
  },
  headerRightButton: {
    left: 10,
    paddingRight: 10,
    position: 'relative'
    backgroundColor: '#03A9F4'
  }
}
```

#### _What I expected to happen?_

The component to have the styles I defined and be like the screenshot in the [docs](https://react-native-training.github.io/react-native-elements/API/header/)

#### _What actually happens_

This white line appears underneath the component:

![issue](https://user-images.githubusercontent.com/7023619/31559783-46317dda-b028-11e7-855b-73634607c91b.jpeg)

I tried inspecting the element to see from were this thing was coming from but had no success. Using `"react-native-elements": "^0.16.0"`

### Reproduction Steps and Sample Code

It's a simple enough problem, so I suppose my snippets and screenshot above will suffice the purpose of tracking down this quirk.

### Solution

Either:
1. Remove it completely from the component or
2. Make this guy customizable through props.

Thanks in advance! 😄

**Comment by seltsamonkel** [comment]
That looks like the border of the outer container.
Could you try setting the borderBottomWidth:0 for headerOuterContainer?

**Comment by igorbrandao** [comment]
Yes, it worked! The solution was so simple/obvious... I guess I didn't try `borderBottomWidth` because I couldn't see in it the element inspector, so I thought it was some `:after` or a divider of some kind...

Thank you.

**Comment by davigmacode** [comment]
Setting borderBottomWidth:0 to headerOuterContainer, not work for me.
using "react-native-elements": "^0.19.0",

**Comment by xavier-villelegier** [comment]
@davigmacode Feel free to open a new issue with updated screenshots if you still have this issue

**Comment by daviscabral** [comment]
@davigmacode Not sure but I understood that you used a `headerOuterContainer` prop - that is not existent - I believe you have to use `outerContainerStyles`. The suggestion was about the style name - that is like that.
