### ISSUE TITLE
Slider is laggy

### ISSUE THREAD

**Issue by edisonywh** [react-native-training/react-native-elements#656]
### Description

**1. Explain what you did**

Implemented a slider to set a value.

**2. What you expected to happen**

Expect it to work perfectly (smoothly, value changes)

**3. What actually happens**

Value does change, but it's super laggy.

### Steps I took:

- Tested out on both iOS 11 and Android 8.0, and the slider is lagging.
- I tried out a couple other libraries for the slider
- Switched to production mode on Expo, still lags.

**react-native-elements version: ^0.16.0**

### Reproduction Steps and Sample Code

I used CRNA to create my app, so it's currently running on Expo.

```
<Slider
minimumValue={1}
maximumValue={50}
minimumTrackTintColor={"#C6C6C4"}
maximumTrackTintColor={"#C6C6C4"}
step={1}
value={this.state.value}
// BUG: This causes the lagginess
// onValueChange={(value) => this.setState({value})}
trackStyle={styles.trackStyle}
thumbStyle={styles.thumbStyle}
/>
```

### Solution
I have a temporary solution, that is to use **onSlidingComplete** instead of onValueChange. It works, but it just doesn't update real time anymore, and I'm just wondering if there's a better way.

### Culprit
Found out that the culprit was the fact that the slider has to change its value _as it moves_.

I'm still currently in the process of fixing it, but I feel like this is probably my fault for not understanding react-native well enough. Appreciate any resources that anyone can point to!

**Comment by ujeenator** [comment]
I'm reducing amount of update with timer

`       onValueChange={value => {
            clearTimeout(this.sliderTimeoutId)
            this.sliderTimeoutId = setTimeout(() => {
              this.setState({value})
            }, 20)
          }}`

**Comment by Norfeldt** [comment]
@xavier-villelegier `debouncing` workings, but I can't get your code suggestion to work. I have to declare it in the constructor.

```
...
import { debounce } from lodash
...
  constructor(props){
    super(props)
    ...
    this.debounceUpdate = debounce( this.updateValue, 20 )
  }

  updateValue(value) {
    this.setState({ value })
  }

  ...
  render() {
    ...
    return (
      ...
      <Slider
        ...
        value={this.state.value}
        onValueChange={(value) => this.debounceUpdate(value)}
      />
    ...
  )}
```

**Comment by Nehal-29** [comment]
Slider's pointer directly jumps to next value . It doesn't move. Above solutions also are not working.

**Comment by hery** [comment]
@ujeenator's solution is great! `20` ms still laggy but `100` ms does it for me!

**Comment by rajatgng** [comment]
but it is not changing the state value

**Comment by JensKolb** [comment]
I have found a different solution that also updates in real time in expo debugging:

```javascript
constructor(props){
    ...
    this.state = {
      ...
      sliderValue: YOUR_INITIAL_VALUE,
      overrideSlider: true,
    }
  }

  ...

  onValueChange(value) {
    this.setState({ 
      sliderValue: value,
      overrideSlider: false,
    })
  }
  
  onSlidingComplete(value) {
    this.setState({ 
      sliderValue: value,
      overrideSlider: true,
    })
  }
  ...
  render() {
    ...
    return (
      ...
      <Slider
        ...
        value={this.state.overrideSlider && this.state.sliderValue}
        onValueChange={(value) => this.onValueChange(value)}
        onSlidingComplete={(value) => this.onSlidingComplete(value)}
      />
    ...
  )}
```

I don't get why we have to find those workarounds ourselves though, this should be standard behaviour.

**Comment by rajatgng** [comment]
@JensKolb It not working....same issue slider is still laggy

**Comment by JensKolb** [comment]
> @JensKolb It not working....same issue slider is still laggy

I noticed too late that this thread is about the react-native-elements slider, while I was using the standard react-native slider. But I'll leave my reply as this is the only thread about this topic.

**Comment by rajatgng** [comment]
whatever the slider I use it have the same problem...I tried standard slider, react-native-elements slider and react-native-slider too but all having the same problem.

**Comment by pedrocarlos-ti** [comment]
works here, thanks @ujeenator.

**Comment by radughitescu** [comment]
I've fixed this by creating another functional component for the slider and the slider state is handled within that component.
Also i've implemented the onSlidingComplete improvement

```
const [value, setValue] = useState(0.2)
const [previewValue, setPreviewValue] = useState(0.2)

render() {
  return (
    <View>
      <Slider
        value={value}
        onValueChange={value => setPreviewValue(value)}
        onSlidingComplete={value => setValue(value)}
      />
      <Text>
        Value: {previewValue}
      </Text>
    </View>
  );
}
```

**Comment by leonardoprimieri** [comment]
> const [value, setValue] = useState(0.2)
> const [previewValue, setPreviewValue] = useState(0.2)

you're genius!!
