### ISSUE TITLE
the top part of the image that i loaded for the Card is missing

### ISSUE THREAD

**Issue by golestanirad** [react-native-training/react-native-elements#657]
please have a look at 
https://stackoverflow.com/questions/46775797/the-top-part-of-the-image-that-i-loaded-for-the-card-is-missing

p.s.
this is my package.json:

```
{
  "name": "swipe",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz",
    "react-native-elements": "^0.17.0"
  },
  "devDependencies": {
    "eslint-config-rallycoding": "^3.2.0"
  }
}

```

**Comment by xavier-villelegier** [comment]
@golestanirad This is not a `react-native-elements` issue. The `Image` component of React Native doesn't handle automatic sizing, as it is specified [in the RN doc](https://facebook.github.io/react-native/docs/images.html#why-not-automatically-size-everything) 😕
You can still update the height dynamically once the Image is loaded with
```
 Image.getSize('http://imgs.abduzeedo.com/files/paul0v2/unsplash/unsplash-04.jpg', (width, height) => {this.setState({width, height})})
```
You then have to do some mathematical stuff to find the ratio you want...

**Comment by xavier-villelegier** [comment]
@golestanirad Feel free to reopen this issue if you think that the RNE `Card` causes some issues with the `Image`.
