### ISSUE TITLE
ListItem rightIcons render chinese character instead of icons

### ISSUE THREAD

**Issue by spyworldxp** [react-native-training/react-native-elements#658]
### Description
`react-native-elements` v0.17

The right icons become like chinese character. Even I try apply ionic icons,  it will show other similar chinese character.

![missing](http://storage.imclement.com/react-native/galaxy-missing-icons.png)

This is my sample code.
```
import React, { Component } from 'react';
import { View,ListView } from 'react-native';
import {List, ListItem,SearchBar,Icon} from "react-native-elements";

export default class App extends Component {
  render() {
    let ds = new ListView.DataSource({
            rowHasChanged: (r1, r2) => r1 !== r2
        });
        ds = ds.cloneWithRows([1,2,3,4,5])
    return (
      <View style={{flex: 1}}>
      <ListView
        renderRow={() =>
           <ListItem
             title={'This is the title'}
             onPress={() => {}}
             />
         } 
         dataSource={ds}/>
      </View>
    );
  }
}
```

**Comment by xavier-villelegier** [comment]
@spyworldxp If you don't use Expo, please make sure you have linked `react-native-vector-icons` as it is specified [here](https://github.com/react-native-training/react-native-elements/blob/master/default_installation.md).

**Comment by spyworldxp** [comment]
@xavier-villelegier I should recompile the APK first. This will solve my problem.
