### ISSUE TITLE
Help Wanted Styling Card

### ISSUE THREAD

**Issue by tcaraccia** [react-native-training/react-native-elements#660]
I cannot get card component header to cover full card width.

Im trying to achieve something like this, meaning the light green covering the full cards with.
![img_91ae7054b012-1](https://user-images.githubusercontent.com/2538504/31744781-a300f90c-b436-11e7-8574-3982b1b336cf.jpeg)

**Comment by xavier-villelegier** [comment]
Hey @tcaraccia !
[Here is](https://snack.expo.io/HkL1CABpb) a simple example. Let me know if it fits to your use case. ✌️

**Comment by tcaraccia** [comment]
Works like a charm! Thanks so much
