### ISSUE TITLE
ListItem rightTitle propType should be PropTypes.any(or object) instead of PropTypes.string

### ISSUE THREAD

**Issue by ogelacinyc** [react-native-training/react-native-elements#663]
### Description

I'm not a expert of React and RN, so It could be my mistake.  

If it isn't a bug or a issue, close this issue please.

When using nested Text components for the rightTitle prop of ListItem, I get a PropTypes warning because it expects only a string. The underlying TextElement component allows its children to be PropTypes.any, so shouldn't the ListItem allow rightTitle to be PropTypes.any also?

I'm using version 0.17.0

### Reproduction Steps and Sample Code
```

const rightTitle = (
    <View width={50} height={20}>
        <Text>{Title}</Text>
        <Text>{Subtitle}</Text>
    </View>
)
<ListItem ... otherProps rightTitle={rightTitle} />

```
### Solution

it could just change the propType of rightTitle to PropTypes.any in ListItem.js.

**Comment by martinezguillaume** [comment]
rightTitle is already wrap in a `Text` styled component. In react-native you can't wrap a `View` in a `Text` but it's true if you wan't to wrap a `Text` in a `Text` component, you can do it in react-native ([docs](https://facebook.github.io/react-native/docs/text.html)). So maybe we can set rightTitle to `PropTypes.node`, need advice on this one.

If you just want to specify width or height (like your example above) or something else, you can just use this props `rightTitleStyle` to declare your rightTitle style like this: 
```jsx
rightTitleStyle={{
  width: 50,
  height: 20,
}}
```

**Comment by ogelacinyc** [comment]
@martinezguillaume thank you for your explanation. but I need two title like title and subtitle.
my example wasn't appropriated.

**Comment by iRoachie** [comment]
Hey @ogelacinyc for this particular issue, we're gonna push this back to our v1 release which has a complete rewrite of the list item component.

**Comment by wkwyatt** [comment]
@iRoachie not sure what you mean by that comment, but is this a feature that exist or that will be added?

**Comment by iRoachie** [comment]
It's a feature that should be added in `v1` of our library. Right now the `ListItem` component is being completely rewritten to be more flexible. Can see the progress [here](https://github.com/react-native-training/react-native-elements/pull/945).

Should be released with `beta4` https://github.com/react-native-training/react-native-elements/pull/945

**Comment by wkwyatt** [comment]
@iRoachie so right now there is no way to have subtitle on the right side of the ListItem?

**Comment by Monte9** [comment]
Looks good. Thanks for sharing the code snippet @wkwyatt ! 👍
