### ISSUE TITLE
List View doesn't show List Item properly

### ISSUE THREAD

**Issue by ignatiusbill** [react-native-training/react-native-elements#664]
### Description

1. Explain what you did

I have an array of Strings like this
```
const list = [
"abc",
"def",
"bla bla bla",
...
];
```

and render it like so
```
    return <List>
        {
          list.map((item, i) => (
            <ListItem
              key={i}
              title={item}
            />
          ))
        }
      </List>;
```
Note: the above code is wrapped around View tags.

2. What you expected to happen

I expected the code to show a list view with the titles on there.

3. What actually happens

[Screenshot of what actually happens.](https://lh4.googleusercontent.com/9lsblTezlq9VQ5ckxuOaKuw3C_uUFvCJDwSh9hAuYkRgOXF-3hHLkRcTpT7u9N4ysutMorvUaf4kYg=s600) You can ignore the "Hello there" string. The list view is being rendered, but it seems like it doesn't show its inside (you can see there's 2 small grey lines on the screen).

I'm using react-native-elements@^0.17.0.

### Reproduction Steps and Sample Code

Snack Expo link: https://snack.expo.io/r1jR68vpb

**Comment by iRoachie** [comment]
Remove the `alignItems: 'center'`, and `justifyContent: 'center'` on the container style

**Comment by ignatiusbill** [comment]
That fixed it. Thanks @iRoachie !
