### ISSUE TITLE
SelectionColor for for Search somehow made it back into master

### ISSUE THREAD

**Issue by Joshuabaker2** [react-native-training/react-native-elements#665]
There was a bug fix a while back https://github.com/react-native-training/react-native-elements/commit/3a8eea8ee3a20a51d7820ee57665d189a4e31642 that solved the issue of Expo having specific settings for the SearchInput which would cause issues when trying to use the SearchBar component on Android. There was a regression somewhere along the way that caused it to be re-introduced into the code, so this issue is just bringing that to light (PR incoming).

**Comment by iRoachie** [comment]
Sorry about that! Merging back that in now

**Comment by iRoachie** [comment]
Fixed in v18.0.0
