### ISSUE TITLE
Tile: Warning: Failed prop type: Invalid props.style key 'resizeMode' supplied to 'View'

### ISSUE THREAD

**Issue by guofoo** [react-native-training/react-native-elements#668]
### Description

Using Tile component results in the following warning message every time. I did some search and found this #471. This fix is causing the warning message since react-native removed support 'resizeMode' in style around v0.46: [react-native issue #14915](https://github.com/facebook/react-native/issues/14915)
The fix is to move it to the new imageStyle prop.

Here's the warning message:

Warning: Failed prop type: Invalid props.style key `resizeMode` supplied to `View`.
Bad object: {
  "alignItems": "center",
  "justifyContent": "center",
  "resizeMode": "cover",
  "backgroundColor": "#ffffff",
  "flex": 2
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in View (at ImageBackground.js:68)
    in ImageBackground (at Tile.js:102)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TouchableOpacity.js:173)
    in TouchableOpacity (at Tile.js:97)
    in Tile (at Tile.js:49)
    in Tile (at Page.js:99)
    in RCTView (at View.js:113)
    in View (at Page.js:195)
    in RCTView (at View.js:113)
    in View (at Page.js:215)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:800)
    in ScrollView (at Page.js:276)
    in RCTView (at View.js:113)
    in View (at Page.js:275)
    in Page (at Navigation.js:232)
    in PageScreen (at SceneView.js:35)
    in SceneView (at CardStack.js:413)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:443)
    in RCTView (at View.js:113)
    in View (at CardStack.js:373)
    in RCTView (at View.js:113)
    in View (at CardStack.js:372)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:198)
    in NavigationContainer (at App.js:32)
    in App (created by AwakeInDevApp)
    in RCTView (at View.js:113)
    in View (created by AwakeInDevApp)
    in AwakeInDevApp (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:67
printWarning @ warning.js:33
warning @ warning.js:57
checkPropTypes @ checkPropTypes.js:52
validatePropTypes @ react.development.js:1736
createElement @ react.development.js:1789
render @ ImageBackground.js:68
(anonymous) @ ReactNativeStack-dev.js:1863
measureLifeCyclePerf @ ReactNativeStack-dev.js:1610
_renderValidatedComponentWithoutOwnerOrContext @ ReactNativeStack-dev.js:1862
_renderValidatedComponent @ ReactNativeStack-dev.js:1872
performInitialMount @ ReactNativeStack-dev.js:1696
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
mountChildren @ ReactNativeStack-dev.js:2871
initializeChildren @ ReactNativeStack-dev.js:2940
mountComponent @ ReactNativeStack-dev.js:2969
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
mountChildren @ ReactNativeStack-dev.js:2871
initializeChildren @ ReactNativeStack-dev.js:2940
mountComponent @ ReactNativeStack-dev.js:2969
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
mountChildren @ ReactNativeStack-dev.js:2871
initializeChildren @ ReactNativeStack-dev.js:2940
mountComponent @ ReactNativeStack-dev.js:2969
mountComponent @ ReactNativeStack-dev.js:1327
performInitialMount @ ReactNativeStack-dev.js:1703
mountComponent @ ReactNativeStack-dev.js:1655
mountComponent @ ReactNativeStack-dev.js:1327
updateChildren @ ReactNativeStack-dev.js:2723
_reconcilerUpdateChildren @ ReactNativeStack-dev.js:2857
_updateChildren @ ReactNativeStack-dev.js:2892
updateChildren @ ReactNativeStack-dev.js:2889
receiveComponent @ ReactNativeStack-dev.js:2955
receiveComponent @ ReactNativeStack-dev.js:1345
updateChildren @ ReactNativeStack-dev.js:2719
_reconcilerUpdateChildren @ ReactNativeStack-dev.js:2857
_updateChildren @ ReactNativeStack-dev.js:2892
updateChildren @ ReactNativeStack-dev.js:2889
receiveComponent @ ReactNativeStack-dev.js:2955
receiveComponent @ ReactNativeStack-dev.js:1345
_updateRenderedComponentWithNextElement @ ReactNativeStack-dev.js:1844
_updateRenderedComponent @ ReactNativeStack-dev.js:1840
_performComponentUpdate @ ReactNativeStack-dev.js:1823
updateComponent @ ReactNativeStack-dev.js:1804
receiveComponent @ ReactNativeStack-dev.js:1769
receiveComponent @ ReactNativeStack-dev.js:1345
updateChildren @ ReactNativeStack-dev.js:2719
_reconcilerUpdateChildren @ ReactNativeStack-dev.js:2857
_updateChildren @ ReactNativeStack-dev.js:2892
updateChildren @ ReactNativeStack-dev.js:2889
receiveComponent @ ReactNativeStack-dev.js:2955
receiveComponent @ ReactNativeStack-dev.js:1345
_updateRenderedComponentWithNextElement @ ReactNativeStack-dev.js:1844
_updateRenderedComponent @ ReactNativeStack-dev.js:1840
_performComponentUpdate @ ReactNativeStack-dev.js:1823
updateComponent @ ReactNativeStack-dev.js:1804
receiveComponent @ ReactNativeStack-dev.js:1769
receiveComponent @ ReactNativeStack-dev.js:1345
_updateRenderedComponentWithNextElement @ ReactNativeStack-dev.js:1844
_updateRenderedComponent @ ReactNativeStack-dev.js:1840
_performComponentUpdate @ ReactNativeStack-dev.js:1823
updateComponent @ ReactNativeStack-dev.js:1804
performUpdateIfNecessary @ ReactNativeStack-dev.js:1772
performUpdateIfNecessary @ ReactNativeStack-dev.js:1353
runBatchedUpdates @ ReactNativeStack-dev.js:1469
perform @ ReactNativeStack-dev.js:1382
perform @ ReactNativeStack-dev.js:1382
perform @ ReactNativeStack-dev.js:1451
flushBatchedUpdates @ ReactNativeStack-dev.js:1476
closeAll @ ReactNativeStack-dev.js:1412
perform @ ReactNativeStack-dev.js:1388
batchedUpdates @ ReactNativeStack-dev.js:2077
enqueueUpdate$1 @ ReactNativeStack-dev.js:1481
enqueueUpdate @ ReactNativeStack-dev.js:1510
enqueueSetState @ ReactNativeStack-dev.js:1556
ReactComponent.setState @ react.development.js:167
(anonymous) @ Page.js:268
tryCallOne @ core.js:37
(anonymous) @ core.js:123
(anonymous) @ JSTimers.js:295
_callTimer @ JSTimers.js:148
_callImmediatesPass @ JSTimers.js:196
callImmediates @ JSTimers.js:464
__callImmediates @ MessageQueue.js:282
(anonymous) @ MessageQueue.js:137
__guard @ MessageQueue.js:269
MessageQueue.flushedQueue @ MessageQueue.js:136
MessageQueue.callFunctionReturnFlushedQueue @ MessageQueue.js:111
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:73 Warning: Failed prop type: Invalid props.style key `resizeMode` supplied to `RCTView`.
Bad object: {
  "alignItems": "center",
  "justifyContent": "center",
  "resizeMode": "cover",
  "backgroundColor": "#ffffff",
  "flex": 2
}
Valid keys: [
  "display",
  "width",
  "height",
  "top",
  "left",
  "right",
  "bottom",
  "minWidth",
  "maxWidth",
  "minHeight",
  "maxHeight",
  "margin",
  "marginVertical",
  "marginHorizontal",
  "marginTop",
  "marginBottom",
  "marginLeft",
  "marginRight",
  "padding",
  "paddingVertical",
  "paddingHorizontal",
  "paddingTop",
  "paddingBottom",
  "paddingLeft",
  "paddingRight",
  "borderWidth",
  "borderTopWidth",
  "borderRightWidth",
  "borderBottomWidth",
  "borderLeftWidth",
  "position",
  "flexDirection",
  "flexWrap",
  "justifyContent",
  "alignItems",
  "alignSelf",
  "alignContent",
  "overflow",
  "flex",
  "flexGrow",
  "flexShrink",
  "flexBasis",
  "aspectRatio",
  "zIndex",
  "direction",
  "shadowColor",
  "shadowOffset",
  "shadowOpacity",
  "shadowRadius",
  "transform",
  "transformMatrix",
  "decomposedMatrix",
  "scaleX",
  "scaleY",
  "rotation",
  "translateX",
  "translateY",
  "backfaceVisibility",
  "backgroundColor",
  "borderColor",
  "borderTopColor",
  "borderRightColor",
  "borderBottomColor",
  "borderLeftColor",
  "borderRadius",
  "borderTopLeftRadius",
  "borderTopRightRadius",
  "borderBottomLeftRadius",
  "borderBottomRightRadius",
  "borderStyle",
  "opacity",
  "elevation"
]
    in RCTView (at View.js:113)
    in View (at ImageBackground.js:68)
    in ImageBackground (at Tile.js:102)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at TouchableOpacity.js:173)
    in TouchableOpacity (at Tile.js:97)
    in Tile (at Tile.js:49)
    in Tile (at Page.js:99)
    in RCTView (at View.js:113)
    in View (at Page.js:195)
    in RCTView (at View.js:113)
    in View (at Page.js:215)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:800)
    in ScrollView (at Page.js:276)
    in RCTView (at View.js:113)
    in View (at Page.js:275)
    in Page (at Navigation.js:232)
    in PageScreen (at SceneView.js:35)
    in SceneView (at CardStack.js:413)
    in RCTView (at View.js:113)
    in View (at AnimatedImplementation.js:1865)
    in AnimatedComponent (at Card.js:28)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:443)
    in RCTView (at View.js:113)
    in View (at CardStack.js:373)
    in RCTView (at View.js:113)
    in View (at CardStack.js:372)
    in CardStack (at CardStackTransitioner.js:110)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:192)
    in Transitioner (at CardStackTransitioner.js:60)
    in CardStackTransitioner (at StackNavigator.js:48)
    in Unknown (at createNavigator.js:36)
    in Navigator (at createNavigationContainer.js:198)
    in NavigationContainer (at App.js:32)
    in App (created by AwakeInDevApp)
    in RCTView (at View.js:113)
    in View (created by AwakeInDevApp)
    in AwakeInDevApp (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)

Using:
    "react-native": "^0.48.4",
    "react-native-elements": "^0.17.0",

### Reproduction Steps and Sample Code

https://snack.expo.io/By7_AqK6Z

Apparently snack hides the console warning messages so you won't see it. Use export to XDE to see the warning messages show up.

### Solution

Pull request: #669

**Comment by iRoachie** [comment]
Fixed in v18.0.0

**Comment by Jun711** [comment]
@iRoachie 
Just to inform that I see the same warning on v0.18.4. 
And, I use these components: `import {Tile, List, ListItem} from 'react-native-elements';`

```
"dependencies": {
		"react": "16.0.0",
		"react-native": "^0.50.4",
		"react-native-elements": "^0.18.4",
		"react-native-vector-icons": "^4.4.2",
		"react-navigation": "^1.0.0-beta.21"
	},
```

Thanks!

**Comment by iRoachie** [comment]
I didn't receive any error @Jun711. Feel free to open a separate issue with a code sample if you're still experiencing trouble

**Comment by Jun711** [comment]
@iRoachie thank you for the reply, I just opened another issue: https://github.com/react-native-training/react-native-elements/issues/740
