### ISSUE TITLE
Crash on Android production (no issue for debug)

### ISSUE THREAD

**Issue by magnusros** [react-native-training/react-native-elements#670]
View.propTypes.style need to change to ViewPropTypes.style

**Comment by iRoachie** [comment]
What file are you seeing this error from? We already changed all references to View.propTypes. What version of react-native-elements are you on?

**Comment by jayeszee** [comment]
![image](https://user-images.githubusercontent.com/10326244/32030712-b6acc6f4-b9b1-11e7-9fb5-fd11672e2998.png)
i believe your card file still uses it?

**Comment by jayeszee** [comment]
Also, it seems like your bundle still has references to it. 
![image](https://user-images.githubusercontent.com/10326244/32030754-0680671c-b9b2-11e7-8b76-61ce94b6a5a3.png)

**Comment by jayeszee** [comment]
@iRoachie https://github.com/react-native-training/react-native-elements/pull/676 I made a quick pr to account for this. I know your contributing guide expects it to be in the next branch but this is a pretty critical issue and we should push 0.17.1 at least before 18. Thanks

**Comment by iRoachie** [comment]
Fixed in v18.0.0

**Comment by iRoachie** [comment]
https://github.com/react-native-training/react-native-elements/commit/9676c7cd4346547d7eaba1f1948a171d03fae2f7 we removed it all together
