### ISSUE TITLE
Can't set styles for the text in groupButtons

### ISSUE THREAD

**Issue by 6axter82** [react-native-training/react-native-elements#672]
Hi, I am getting problems with setting the Text style of the groupButtons.
I am using react-native 0.49.3
and react-native-elements 0.17.0

```
render() {
	const component1 = () => <Text>A</Text>;
	const component2 = () => <Text>B</Text>;
	const buttons = [
		{ element: component1 },
		{ element: component2 },
	];
	return (
		<View style={styles.container}>
		   <ButtonGroup
	 		 buttons={buttons}
			 onPress={this._updateIndex}
			 selectedIndex={this.state.selectedIndex}
			 containerBorderRadius={25}
				
			 selectedBackgroundColor={colors.blue}  
			 textStyle={styles.buttonGroup_textStyle}
			 selectedTextStyle={styles.buttonGroup_selectedTextStyle}
			 containerStyle={styles.buttonGroup}
       		    />
		</View>
	);
}
```
....

```
const styles = StyleSheet.create({
	buttonGroup: {
		width: 200,
		height: 50,
		backgroundColor: 'white',
		alignSelf: "center",
		justifyContent: "center",
		borderRadius: 25,
		borderWidth: 4,
		borderColor: 'blue',
	},
	buttonGroup_textStyle: {
		color: 'green',
		fontFamily: 'Dosis-Regular',
		fontSize: 13,
	},
	buttonGroup_selectedTextStyle: {
		color: 'white',
	},
});
```
![screen shot 2017-10-24 at 17 23 58](https://user-images.githubusercontent.com/13738101/31952134-2971d710-b8e0-11e7-9e62-034a643eb37a.png)

If someone has a hint? I would really appreciate it a lot!

**Comment by iRoachie** [comment]
Hey @6axter82, the `textStyle` property only works if you pass in your buttons as an array of strings. e.g. `['Tab1' ,'Tab2]` https://react-native-training.github.io/react-native-elements/API/button_group/.

If you pass in your own components as in your example `<Text>`, then you have to provide your own styling to the components.

E.g `const component1 = () => <Text style={myTextStyle}>A</Text>;`

**Comment by 6axter82** [comment]
alright, I got it, thanks it works perfectly now.

**Comment by thanhluantl2304** [comment]
> Hey @6axter82, the `textStyle` property only works if you pass in your buttons as an array of strings. e.g. `['Tab1' ,'Tab2]` https://react-native-training.github.io/react-native-elements/API/button_group/.
> 
> If you pass in your own components as in your example `<Text>`, then you have to provide your own styling to the components.
> 
> E.g `const component1 = () => <Text style={myTextStyle}>A</Text>;`

what about style for selected button?
