### ISSUE TITLE
Button support children

### ISSUE THREAD

**Issue by ZeroSoulEater** [react-native-training/react-native-elements#673]
Button should display child components!

for example I made an component witch displays a rotating Icon and like to have it set as the value for a a time

**Comment by martinezguillaume** [comment]
The question is where to display it ? Before the left icon ? at the middle ? After the right icon ? Maybe if we specify children, we don't wan't to render anything (icons or text) in the button and just wan't to render the children alone. That can be a behavior... We need to discuss of that

**Comment by ZeroSoulEater** [comment]
I would say in the middle by default and if there is a Icon, Display it right to the left icon and left to the right icon?

**Comment by iRoachie** [comment]
Hey! @ZeroSoulEater Have you tried using `loading` prop on the button?

**Comment by Monte9** [comment]
@martinezguillaume RNE Button already supports the loading prop on the `v1` branch. 
Here's the code for reference: https://github.com/react-native-training/react-native-elements/blob/v1/example/v1/buttons/Button.js#L72

We are working on getting `v1` on `next` branch, so users can start using it. Stay tuned @ZeroSoulEater

**Comment by iRoachie** [comment]
This is live! You can use the new `Button` by using the beta of rne.
`npm install --save react-native-elements@beta`
