### ISSUE TITLE
Any idea to add icon inside avatar ?

### ISSUE THREAD

**Issue by Ali-Dalal** [react-native-training/react-native-elements#674]
Is there any idea how to add an icon to indicate that this avatar is editable ?
I tried to add <Icon> inside <Avatar> but nothing shown, The same flow works perfectly if I add an Icon inside image tage 

Cheers!!

**Comment by xavier-villelegier** [comment]
Hey @Ali-Dalal 
You could do something [like this](https://snack.expo.io/BkxNCrJCW).

**Result**
![image](https://user-images.githubusercontent.com/17592779/32051739-1dc66292-ba56-11e7-9c12-7d5a0219f96d.png)

The idea is just to add an `Icon` with `position: 'absolute'` styling 👍

**Comment by Ali-Dalal** [comment]
@xavier-villelegier 
Thank for your replay

I tried this approach. The problem is on different screen size, The icon won't set in the same position on every screen
