### ISSUE TITLE
Backer/Sponsor links don't work

### ISSUE THREAD

**Issue by ZeroSoulEater** [react-native-training/react-native-elements#678]
If try to click on a Backer/Sponsor link I get webpage with  `Internal Server Error` just for your information 👍

**Comment by xavier-villelegier** [comment]
Are you talking about this link ?
```
https://opencollective.com/react-native-elements/donate
```
It's working for me, maybe the `opencollective` website had some troubles. 🤔
Feel free to tell us if it happens again.

**Comment by xavier-villelegier** [comment]
Closing this as it seems to be working now. Feel free to reopen this if this is still an issue.
