### ISSUE TITLE
Issues with styled-components

### ISSUE THREAD

**Issue by machour** [react-native-training/react-native-elements#679]
This issue seems to affect a lot of the components provided by `react-native-elements`. Here's an example with `<ListItem />`:

If I use styled-components with a `<ListItem/>`, the default container style isn't used anymore.

Here's how the styled component is created:
```js
const StyledListItem = styled(ListItem).attrs({
  titleStyle: { /* ... */ },
})``;
```

Here's the result when using `<StyledListItem>` for my first element in the list:
<img width="357" alt="screen shot 2017-10-27 at 6 15 01 pm" src="https://user-images.githubusercontent.com/304450/32116564-6ce754e4-bb4b-11e7-90ac-ed874f853dbf.png">

As you may see, the bottom border defined as default is lost.

The problem is located here: https://github.com/react-native-training/react-native-elements/blob/master/src/list/ListItem.js#L97-L103

When using styled-components, `attributes` gets automatically passed this value:
```
{ style: [ 540, undefined ],
  innerRef: [Function],
  children: undefined }
```

so the default style gets overrided.

### Solution

An obvious solution would be to spread `attributes` first, then define your own props, as you definitely don't want them to be overridden (or do you?)

```js
    <Component
      {...attributes}
      onLongPress={onLongPress}
      onPress={onPress}
      underlayColor={underlayColor}
      style={[styles.container, containerStyle && containerStyle]}
    >
```

I'd happily work on a PR for this, but i'd like to make sure that it's not done on purpose on the first place.

**Comment by xavier-villelegier** [comment]
Hey @machour, I think you can open a PR to fix that, you solution looks good and simple to avoir overriding the `style` props by mistake (or by using `StyledComponent` like you do) 👍

**Comment by machour** [comment]
Hi @xavier-villelegier, #683 took care of spreading `attributes` before laying out computed props in all components.

**Comment by Monte9** [comment]
@machour just published `v0.18.1`. Please give it a shot and report back if you run into any other issues. ✌️ hope this helps.

**Comment by xavier-villelegier** [comment]
Fixed in `v0.18.1`.

**Comment by machour** [comment]
@Monte9 so far so good on GitPoint. Thank you all for this quick handling, such quick, much love ❤️

**Comment by Monte9** [comment]
RNE x GitPoint = 💯 
That's great! Happy to help! 😄
