### ISSUE TITLE
Can't change color of activity indicator in button element

### ISSUE THREAD

**Issue by DanielDziubecki** [react-native-training/react-native-elements#684]
Iv'e tried to change Activity Indicator color in button element but it looks like it doesnt work. I am using  react-native-elements@0.17.0 version. Without styling it works well.

https://snack.expo.io/BJqwUTBA-

**Comment by xavier-villelegier** [comment]
@DanielDziubecki Try to put `color='#16c5cc'` directly in the `Button` props

**Comment by DanielDziubecki** [comment]
It works. Thanks.
