### ISSUE TITLE
Default background color for Header

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#685]
References https://github.com/react-native-training/react-native-elements/issues/548#issuecomment-340806802

**Comment by iRoachie** [comment]
Lol any favorite color @xavier-villelegier ? :D

**Comment by xavier-villelegier** [comment]
Haha, let's put that in a sober pink 👌😂
`react-navigation` is using `#F7F7F7` for iOS, maybe we could use that too

**Comment by iRoachie** [comment]
Implemented in v18.0.0
