### ISSUE TITLE
Fix warnings on CI

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#686]
Fix errors surrounding PropTypes and React.createClass. Probably can be fixed by upgrading the test packages.

**Comment by iRoachie** [comment]
Fixed in https://github.com/react-native-training/react-native-elements/pull/838/commits/ad05179753d834cab47f51823c08db5b1bc9398e. Available in next release.

**Comment by Monte9** [comment]
Much needed. Thanks.

**Comment by xavier-villelegier** [comment]
Fixed in `v1.0.0-beta2` @iRoachie striked again 🚀
