### ISSUE TITLE
Getting starting with typescript intro

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#688]
Some docs explaining how someone would get started using react native with typescript

**Comment by QuantumInformation** [comment]
Any news on this? In a more general sense can ts be used in vanilla react native?

**Comment by iRoachie** [comment]
I actually forgot to write this section. Here's a start from Microsoft to get you started https://github.com/Microsoft/TypeScript-React-Native-Starter

**Comment by QuantumInformation** [comment]
Great thanks

**Comment by raduflp** [comment]
this seem to be a more up-to-date approach for anyone looking for TS support [https://github.com/ds300/react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer)

**Comment by iRoachie** [comment]
Yep @raduflp! I use that currently and it works great

**Comment by iRoachie** [comment]
Closing this as package now comes from npm with types included
