### ISSUE TITLE
Why deleted the tabs?

### ISSUE THREAD

**Issue by MackayBravo** [react-native-training/react-native-elements#692]
We have a project on these tabs. We wanted to see the documentation and it's not there

**Comment by iRoachie** [comment]
We explained our reasons for removing Tabs in the [release notes of v15.0.0](https://github.com/react-native-training/react-native-elements/releases/tag/v0.15.0).

If you still want to use it, the library is [react-native-tab-navigator](https://github.com/happypancake/react-native-tab-navigator). It was simply their package what we were using. You can check their readme for documentation.

**Comment by Monte9** [comment]
@MackayBravo really sorry about that. I know it's really frustrating when something as core as tabs is removed from a UI library. Although to be fair, as @iRoachie explained, we announced that we were going to deprecate it back in **RNE v0.15.0**. And we finally decided to remove it for **v0.18** as we are preparing for a bigger and better **v1.0 release**.

For what it's worth, RNE tabs was basically a wrapper around the `react-native-tab-navigator` API. So here's how you can continue using RNE tabs in v0.18

**Before:**
```
import { Tab, Tabs } from 'react-native-elements';

<Tabs>
  <Tab
    titleStyle={{fontWeight: 'bold', fontSize: 10}}
    selectedTitleStyle={{marginTop: -1, marginBottom: 6}}
    selected={selectedTab === 'feed'}
    title={selectedTab === 'feed' ? 'FEED' : null}
    renderIcon={() => <Icon containerStyle={{justifyContent: 'center', alignItems: 'center', marginTop: 12}} color={'#5e6977'} name='whatshot' size={33} />}
    renderSelectedIcon={() => <Icon color={'#6296f9'} name='whatshot' size={30} />}
    onPress={() => this.changeTab('feed')}>
      <Feed />
    </Tab>
    /* ... more tabs here */
</Tabs>
```

**After:**
```
import { TabNavigator as Tabs, TabNavigator.Item as Tab } from 'react-native-tab-navigator';

<Tabs>
  <Tab
    titleStyle={{fontWeight: 'bold', fontSize: 10}}
    selectedTitleStyle={{marginTop: -1, marginBottom: 6}}
    selected={selectedTab === 'feed'}
    title={selectedTab === 'feed' ? 'FEED' : null}
    renderIcon={() => <Icon containerStyle={{justifyContent: 'center', alignItems: 'center', marginTop: 12}} color={'#5e6977'} name='whatshot' size={33} />}
    renderSelectedIcon={() => <Icon color={'#6296f9'} name='whatshot' size={30} />}
    onPress={() => this.changeTab('feed')}>
      <Feed />
    </Tab>
    /* ... more tabs here */
</Tabs>
```

as you can see, you just need to install `react-native-tab-navigator` using:
`npm install react-native-tab-navigator --save`

and then replace the import statement with 
`import { TabNavigator as Tabs, TabNavigator.Item as Tab } from 'react-native-tab-navigator';`

The rest should just work as it. 🌮  Hope this helps.
