### ISSUE TITLE
Why did you remove Swipedeck 😡

### ISSUE THREAD

**Issue by abdennour** [react-native-training/react-native-elements#693]
# Issue : 

Where is this page ?  😠
https://github.com/react-native-training/react-native-elements/blob/master/docs/API/swipedeck.md
And where is this page ? 😡
https://react-native-training.github.io/react-native-elements/API/swipedeck/

# Solution : 

https://github.com/Monte9/react-native-tinder-cards

**Comment by Monte9** [comment]
@abdennour sorry about that. Yes, we decided that it would be better for a component like Swipedeck (which is very modular) to live in its own repo. This makes maintaining and developing the component easier. 

You are right, the `react-native-tinder-cards` repo is the right library to follow if you are looking to use Swipedeck component in the future. Please feel free to report an issue or submit a PR on that repo if you have any thoughts on it.
