### ISSUE TITLE
Improve Form Input Components

### ISSUE THREAD

**Issue by phillip055** [react-native-training/react-native-elements#696]
### Description

1. Explain what you did
Try to make text input only for numeric
2. What you expected to happen
Some easy way to set that
3. What actually happens
have to have numeric keyboard and also set on change

### Solution

Maybe accept another prop to see type?

**Comment by xavier-villelegier** [comment]
@phillip055 All the props passed to the RNE `FormInput` are passed to the `TextInput` input of RN. This means you case use the [`keyboardType` props](https://facebook.github.io/react-native/docs/textinput.html#keyboardtype), and set it to `numeric`, which works on both iOS and Android.

**Comment by phillip055** [comment]
it doesnt really strict user can still change keyboard? any suggestions to strictly have a type?

**Comment by xavier-villelegier** [comment]
@phillip055 Mmmh on iOS you can't use another keyboard
![image](https://user-images.githubusercontent.com/17592779/32609007-6fec10ea-c55e-11e7-9f20-905388e0188f.png)

If you really want to control what the user is typing you should add some logic in the `onChangeText` callback to check what the user typed. I think there is no other way to restrict the keyboard with react-native than through the `keyboardType` props

**Comment by abhi11verma** [comment]
Use this
    changeValue(value) {
        return new Text(value.replace(/[^0-9]/g, ''), this.text);
    }
