### ISSUE TITLE
Header doesn't render properly on screen rotation

### ISSUE THREAD

**Issue by denisdimitrov** [react-native-training/react-native-elements#701]
Since update 0.18.0 the header doesn't render properly on rotation from portrait to landscape and vice versa. This was working fine on 0.17.0.

### 0.17.0 
- - -
**Portrait**

![screenshot_1509957908](https://user-images.githubusercontent.com/18435853/32432540-aa328d0e-c2e0-11e7-8744-5f6b82a43e67.png)

**Landscape**

![screenshot_1509957912](https://user-images.githubusercontent.com/18435853/32432591-c78bd720-c2e0-11e7-8d1b-2a7ecdf6915a.png)

### 0.18.0 
- - - 
**Portrait**

![screenshot_1509957982](https://user-images.githubusercontent.com/18435853/32432616-e6437dc6-c2e0-11e7-8854-54730a632688.png)

**Landscape**

![screenshot_1509957985](https://user-images.githubusercontent.com/18435853/32432628-f0293006-c2e0-11e7-8541-15090dd6130b.png)

### Current fix

 ```javascript
outerContainerStyles={{ width: '100%' }}
```

### P.S. If you intentionally made it this way, feel free to close the issue.

**Comment by iRoachie** [comment]
Definitely isn’t suppose to be doing that. Do you mind sending a PR?

**Comment by denisdimitrov** [comment]
Sure, asap.
