### ISSUE TITLE
underlayColor cannot be configured

### ISSUE THREAD

**Issue by webraptor** [react-native-training/react-native-elements#702]
### Description
Upgraded to latest version "react-native-elements": "0.18.2"

### Expected to happen
underlayColor of socialIcons would be set to value passed by underlayColor attribute

### Actually happens
_underlayColor_ of socialIoncs is either _white_ if _light_: _true_ or set by colors[type] hardcoded value.

### Solution

Instead of `underlayColor={light ? 'white' : colors[type]}` and removed underlayColor from props, add back underlayColor to props and change code to `underlayColor={light ? underlayColor || 'white' : underlayColor  || colors[type]}`.

**Comment by xavier-villelegier** [comment]
@webraptor That was fixed on the `next` branch and the doc was updated.

**Comment by xavier-villelegier** [comment]
@webraptor `v0.18.3` was released with this fix 👍
