### ISSUE TITLE
'react-native-elements' not working

### ISSUE THREAD

**Issue by NiteshGarg2107** [react-native-training/react-native-elements#704]
I just install the  'react-native-elements "^0.18.2"' in my project.when I import any components in my class it show me error: -----/react-native-elements/src/helpers/getIconType.js: module doesn't exist.

**Comment by NunoCardoso** [comment]
I have this problem constantly. For some reason, it fails on importing FeatherIcon. 
I go to node_modules/react-native-elements/src/helpers and I remove any mention of FeatherIcon, and then it works.

**Comment by iRoachie** [comment]
Can you try running `npm i --save @expo/vector-icons`?

**Comment by michelmarcondes** [comment]
To solve this, I must run `npm i --save react-native-vector-icons@4.4.2`.
My App was using react-native-vector-icons@4.3.0 and elements using @4.4.2

**Comment by kay-es** [comment]
got the same problem with expo 22.0.0

**Comment by pulpdood** [comment]
Same problem with expo 21.0.0

**Comment by bexsoft** [comment]
Looks like running  `npm i --save @expo/vector-icons` solves the issue. Tried with expo 22.0.0 & react-native-elements 0.18.2
