### ISSUE TITLE
I used react-native elements

### ISSUE THREAD

**Issue by NiteshGarg2107** [react-native-training/react-native-elements#706]
### Description

1. Explain what you did
2. What you expected to happen
3. What actually happens

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by Monte9** [comment]
Thanks for using RNE @NiteshGarg2107 🙏
