### ISSUE TITLE
Make Header icon clickable.

### ISSUE THREAD

**Issue by NiteshGarg2107** [react-native-training/react-native-elements#707]
I used react-native element Header:
I want left and right component clickable.Is there any prop which give me the event when I touch or tap left and right component.
<Header
 leftComponent={{icon: 'menu', color: '#fff',style: {color: ''}}}
 centerComponent={{ text: this.props.title, style: { color: '#fff' } }}
 rightComponent={{ icon: 'home', color: '#fff' }}
/>

**Comment by xavier-villelegier** [comment]
@NiteshGarg2107 There are two ways of doing that.

### Using an object

```jsx
```
### Using a component

**Comment by boza** [comment]
@xavier-villelegier tried this and is not really working for some reason.

**Comment by xavier-villelegier** [comment]
@boza Can you please be more specific?
You can see that [this example](https://snack.expo.io/Bk3s0ackz) is working

**Comment by xavier-villelegier** [comment]
Closing this as it has been inactive for a month, feel free to ping if you still have this issue

**Comment by geminiyellow** [comment]
so why `onPress` is not in here [header.md](https://github.com/react-native-training/react-native-elements/blob/master/docs/header.md)

should update the docs.

**Comment by xavier-villelegier** [comment]
@geminiyellow You can see that there is
> `...props` for React Native Elements Icon component

In the docs for `leftComponent`, `centerComponent`, `rightComponent`. This means you can use any props of the `Icon`, including `onPress`. However, we should add more examples with more use cases 👍

**Comment by geminiyellow** [comment]
@xavier-villelegier thank you

**Comment by balwinder4264** [comment]
hey guys I am using navigation and try to make title clickable but i can not provide is to title in push navigation so it is not working when i am trying to access title through onNavigatorEvent

**Comment by xavier-villelegier** [comment]
@balwinder4264 Are you using React Native Elements ? Looks like your issue is only related to React Navigation.
