### ISSUE TITLE
tabBar?

### ISSUE THREAD

**Issue by callagga** [react-native-training/react-native-elements#708]
does react-native-elements have a tabBar?    If yes wondering where the doco for this is?

If no, any tips before closing this appreciated  (looking for a cross platform/universal react-native tabbar)

**Comment by xavier-villelegier** [comment]
Hey  @callagga! RNE had TabBars but they were removed in the `0.18.0`, you can see the reasons why [here](https://github.com/react-native-training/react-native-elements/issues/692#issuecomment-341778975).
As @Monte9 said in this issue, if you just want TabBars without any navigation around you can use `react-native-tab-navigator`, the one RNE was using too. If you want a full navigation solution, which obviously includes TabBars, [React Navigation](https://reactnavigation.org/) is the must have.
