### ISSUE TITLE
icon not showing

### ISSUE THREAD

**Issue by arctushar** [react-native-training/react-native-elements#710]
Icon not showing, no error showing, icon installation done.

`import { List, ListItem, SearchBar, Button,Avatar,Icon,SocialIcon} from "react-native-elements";`

	<SocialIcon
  title='Some Twitter Message'
  button
  type='twitter'
/>

Also in node_modules\react-native-vector-icons\Fonts I have FontAwesome and other fonts
Also Android module react-native-vector-icons is already linked

![emulator](https://user-images.githubusercontent.com/2739185/32695143-babae328-c77d-11e7-9a73-e59fec5f8d07.png)

**Comment by iRoachie** [comment]
Hey @arctushar this is usually a linking issue. Are you in a `react-native init` or `create-react-native-app` project?

**Comment by arctushar** [comment]
react-native init

**Comment by OmarMahili** [comment]
As @iRoachie said it's probably a linking issue. Try this command in your project root directory:

> react-native link

**Comment by xavier-villelegier** [comment]
Closing this as it has been inactive for a month, feel free to reopen it if it still doesn't work

**Comment by dorman99** [comment]
i have same problem here, pls re open it

**Comment by MaxInMoon** [comment]
same with SearchBar icons

**Comment by xavier-villelegier** [comment]
@dorman99 @MaxInMoon Be sure to have followed these instructions https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210

**Comment by MaxInMoon** [comment]
@xavier-villelegier thanks, my problem comes from the SearchBar component (#1019)

**Comment by aidooyaw1992** [comment]
this works, follow the tutorial below
https://github.com/oblador/react-native-vector-icons

**Comment by anvt96** [comment]
I can't fix it, although I follow this link https://github.com/oblador/react-native-vector-icons. Anyone can give me solutions, please.

**Comment by ivanjzr** [comment]
Me to, I followed steps properly from https://github.com/oblador/react-native-vector-icons
and nothing...

**Comment by josephbuchma** [comment]
Manual installation worked for me. Copy fonts you want to use into `android/app/src/main/assets/fonts` and reinstall app

**Comment by 7Million** [comment]
> 
> 
> As @iRoachie said it's probably a linking issue. Try this command in your project root directory:
> 
> > react-native link

This worked for me even though RN 0.60 now offers autolinking, you will have to manually do the linking because autolinking still has some issues.

**Comment by irwwwan** [comment]
If you are using RN 0.60, just link it manually because the fonts assets not automatically linked by jetifier.
`react-native link`

**Comment by krishan-kumar-mourya** [comment]
> If you are using RN 0.60, just link it manually because the fonts assets not automatically linked by jetifier.
> `react-native link`

This works, RN 0.60 or above links automatically but still for fonts assets you have to link them manually.

**Comment by siujay** [comment]
> As @iRoachie said it's probably a linking issue. Try this command in your project root directory:
> 
> > react-native link

Thankyou soo much, wasted whole day on this, just had to link as you said.

**Comment by qureshi90** [comment]
Open android/app/build.gradle and add the following:

`apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

This worked for me.

**Comment by AmitRathee729** [comment]
> `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`

Thank you so much, this worked for me

**Comment by JoaoVitorJJV** [comment]
> Open android/app/build.gradle and add the following:
> 
> `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`
> 
> This worked for me.

Worked for me

EDIT:

It worked perfectly for the build, but to release with RN 0.72 I needed to add an update patch in the ```node_modules/react-native-vector-icons/fonts.gradle``` file:

```diff
diff --git a/node_modules/react-native-vector-icons/fonts.gradle b/node_modules/react-native-vector-icons/fonts.gradle
index 5485fac..ef3ccb3 100644
--- a/node_modules/react-native-vector-icons/fonts.gradle
+++ b/node_modules/react-native-vector-icons/fonts.gradle
@@ -26,6 +26,10 @@ afterEvaluate {
 
     android.applicationVariants.all { def variant ->
         def targetName = variant.name.capitalize()
+        def lintVitalAnalyzeTask = tasks.findByName("lintVitalAnalyze${targetName}")
+        if (lintVitalAnalyzeTask) {
+            lintVitalAnalyzeTask.dependsOn(fontCopyTask)
+        }
         def generateAssetsTask = tasks.findByName("generate${targetName}Assets")
         generateAssetsTask.dependsOn(fontCopyTask)
     }
     

```

You can see more here: https://github.com/oblador/react-native-vector-icons/issues/1508#issuecomment-1604115239

**Comment by usmanabid94** [comment]
Icons are now being displayed on android but not being displayed on IOS files any one faced similar issue.

**Comment by mohcenesegouat** [comment]
> Open android/app/build.gradle and add the following:
> 
> `apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"`
> 
> This worked for me.

Thank you very much, it works for me as well! 👏👏
