### ISSUE TITLE
Select multiple when using ButtonGroup

### ISSUE THREAD

**Issue by jaschaio** [react-native-training/react-native-elements#713]
It seems that when I use the `ButtonGroup` component I can always only select one of the buttons.

Wouldn't a boolean property like `selectMultiple` make sense for cases where I don't want only a simple switch?

**Comment by ashtiani** [comment]
check this out #59

**Comment by jaschaio** [comment]
Thanks for that, I am using it now. Should I do another PR? Not really sure why the other one got closed.

**Comment by iRoachie** [comment]
Feel free to submit a PR! The last one was closed because the contributor went MIA.
