### ISSUE TITLE
support for toolbar with icons/buttons? 

### ISSUE THREAD

**Issue by callagga** [react-native-training/react-native-elements#715]
Info Request 

Would react-native-elements provide support for having a footer section at the bottom a particular screen, where you can then place buttons (similar to the appearance of buttons/icons in tabs)?  Any tips on which components within react-native-elements would be appreciated. 

Background - So basically similar to an IOS/XCode project where you can drag a "Toolbar" at the bottom of a screen and then drag/place "Bar Button Items" onto it.

**Comment by iRoachie** [comment]
Sounds like you're looking for a tab navigator. We don't have that component as itself cause it'd be pretty hard to maintain a navigation library. However you can check out the recommend navigation library for react-native which includes **tabs**, stack, and drawers. https://reactnavigation.org/docs/navigators/tab

Also check out their expo app so you can preview what it looks like on your screen. https://expo.io/@react-navigation/NavigationPlayground

**Comment by callagga** [comment]
ok - perhaps using a tab-navigator for that particular screen, but preventing it from operating as tabs, and intercepting... I'll check it out
