### ISSUE TITLE
TouchableOpacity not showing up on button

### ISSUE THREAD

**Issue by mikebski** [react-native-training/react-native-elements#717]
### Description

1. Explain what you did

I created a Button that I want to put an icon on:

```
import {Button, Avatar} from 'react-native-elements'
const diaperIcon = require('../shared/images/diaper.png')

const Diaper = ({}) => {
    return (
        <View>
            <Text>
                Diaper
            </Text>
            <Button title={"Diaper"} iconComponent={<TouchableOpacity> <Image style={styles.iconImage} source={diaperIcon}/></TouchableOpacity>}/>
            <Image style={styles.iconImage} source={diaperIcon}/>
            <Text>
                Avatar <Avatar source={diaperIcon}/>
            </Text>
            <TouchableOpacity><Image style={styles.iconImage} source={diaperIcon}/></TouchableOpacity>
        </View>
    )
}

export default Diaper
```

2. What you expected to happen

I expected the icon to show up on the image.  The image is valid, as shown by the `Avatar` and `Image` and `TouchableOpacity` that all show up properly

3. What actually happens

I see this:

![image](https://user-images.githubusercontent.com/4280588/33021847-3994b3a0-cdd1-11e7-8dec-28163f3efe10.png)

Also please include the version of `react-native-elements` that you are using.
 
>> "react-native-elements": "^0.18.2"

**Comment by xavier-villelegier** [comment]
@mikebski There is an `onPress` props on the Avatar, you can do the following:
```jsx
<Avatar
  source={diaperIcon}
  onPress={() => console.log('pressed')}
/>
```

Here is a [snack example](https://snack.expo.io/H1UbbOegG).

**Comment by mikebski** [comment]
That does work, however, I'd like an icon button like this:

![image](https://user-images.githubusercontent.com/4280588/33026413-5d7f0024-cdde-11e7-81c3-0fb0b34e308b.png)

Seems like I should be able to do that with a simple svg or png...

**Comment by xavier-villelegier** [comment]
@mikebski Oh okay, I think you should be able to do that then:

```jsx
 <Button
  iconComponent={Image}
  leftIcon={{
    style: {width: 20, height: 20},
    source: diaperIcon,
  }}
  title="hey"
/>
```

Have a look at [this example](https://snack.expo.io/rk10cOexM)

**Comment by mikebski** [comment]
That's it, I was trying to provide an instance to the IconComponent rather than a class.  Duh.
