### ISSUE TITLE
How to setup livesync for local development?

### ISSUE THREAD

**Issue by pavloko** [react-native-training/react-native-elements#719]
I was wondering how do main contributors to this library develop locally?

I searched documentation and couldn't find a clear way how to setup a development workflow.

What I'd like to have:
1. I run an example app in examples folder.
2. I make changes to the code in src, for example Button component. 
3. I get the changes synced in the emulator.

What I've tried/have in mind:
1. `npm link, npm link react-native-elements` --> doesn't work with React Native.
2. making changes in `example/node_modules`. Not ideal if you're making lots of changes in different files.
3. Another option might be setting up storybook.

Thanks and I really appreciate your input on these.

**Comment by iRoachie** [comment]
We haven't got a definitive method on this one yet. Currently right now just editing in node_modules, checking if worked then copy to cloned repo. Looking at using [Haul](https://github.com/callstack/haul) in the future since it supports symlinks. Definitely open to any feedback/ideas

**Comment by pavloko** [comment]
Hi, @iRoachie! Thanks for the reply. 

Yea, I've been looking into this and [Haul](https://github.com/callstack/haul) seems to be an option. I have a working example setup locally. There is another option which is using [Storybook](https://github.com/storybooks/storybook) as it's a bit more flexible and allows you to zoom in on specific component. For example, if the component you're developing is a few scenes deep in the example app, you'd need to click-through every time you want to see changes, which is not the case with storybook.

I personally think that for a component library like react-native-elements, storybook looks like a better choice for two reasons:
1. Better development experience. You don't need to navigate to a specific route where your component is located.
2. Provides actionable overview of the library at a glance, without requiring to search for components within routes.

The example app provides a good overview of components in context though.

**Comment by Monte9** [comment]
@pavloko that's a really good suggestion. I have heard good things about storybook, but haven't gotten a chance to try it yet. Totally onboard with using storybook for RNE. 

A have a couple noob q's for you:
1. Can you link to a couple examples for RN Storybooks? I looked around and couldn't any good references. The closest I got to finding a live example for RN related repo was RN Web here: https://necolas.github.io/react-native-web/storybook/

Also for RNE, since these are RN components, how would they be displayed on the web? We would need to use something like RN Web to even get it to display on the storybook right?

2. I tried setting it up and ran into a prob really quickly. Basically, I think I am missing some loader for RN because I got a ton of errors and each of them had to do with the react-native package in node_modules. For example:
```
ERROR in ./node_modules/react-native/Libraries/react-native/react-native.js
Module not found: Error: Can't resolve 'AppRegistry' in '/Users/montewithpillow/developer/open_source/react-native-elements/node_modules/react-native/Libraries/react-native'
 @ ./node_modules/react-native/Libraries/react-native/react-native.js 77:29-51
 @ ./stories/index.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true ./.storybook/config.js
```

Lastly, in terms of setting up the example app to work with storybook.. would they have to be in the same repo? Becuase rn, the way its setup is we have an example app in Expo that is self-contained within the `/example` directory. So with storybook, I assume this would have to change?

**Comment by pavloko** [comment]
Hi @Monte9! Sorry for the later reply. 

I've setup a small example [here](https://github.com/pavloko/react-native-library-starter).

Regarding the error you described. Are you trying to set it up in `example` Expo project or just in another RN project? 

Here is a [link](https://github.com/storybooks/storybook/blob/master/app/react-native/readme.md#create-react-native-app-crna) to Storybooks docs on how to set it up with CRNA. 

Also, I've just realized you'd still need to use haul-cli if you'd want to get livesync from the parent project. You can see it setup it my[ example repo](https://github.com/pavloko/react-native-library-starter).

**Comment by pavloko** [comment]
Just wanted to update, I see that currently react-native-elements is using Expo in the example folder. [Haul bundler](https://github.com/callstack/haul) currently doesn't support it, so we won't be able to get livesync there, but storybook should work fine. 

I can try to set it up in a separate brunch, if you'd like. 

Cheers!

**Comment by xavier-villelegier** [comment]
@pavloko Storybooks looks a solid solution, we should definitely give it a shot. For now I clone the RNE repo inside the `node_modules` of the example app. It works just fine and allows you to commit directly through `node_modules/react-native-elements`, but the storybook solution seems cleaner, for sure

**Comment by Monte9** [comment]
OK, we finally have a working solution. As @xavier-villelegier suggested, we ended up using git submodules as a way to make development easier between the `/example` app and `rne-core`. 

For the upcoming `v1` release, `/example` is going live on a standalone project here: https://github.com/react-native-training/react-native-elements-app/tree/v1#get-started

Here's how it works:
RNE is a submodule with the `react-native-elements-app` repo. Hence all you need to do is to clone the `elements-app` repo. Then `npm install`.

Then when you do `import { Button } from 'react-native-elements'`, the button component comes from your `node_modules/react-native-elements` which is actually a clone of this main repo. Hence you can make any changes you want inside that and you can even commit directly to this main repo from the `node_modules/react-native-elements` folder.

Give this a try and let me know what you think. So far, it's been super useful for me personally.

**Comment by iRoachie** [comment]
Closing this as resolved for now! If a better solution comes up we can definitely discuss it here
