### ISSUE TITLE
JSON value of type NSMutableDictionary cannot be converted to a valid URL (ListItem Avatar)

### ISSUE THREAD

**Issue by AlexisJamin** [react-native-training/react-native-elements#720]
Hello everyone,

I'm using ListItem and FlatList to render a list of users in my app. 

Here is my code : 
![capture d ecran 2017-11-21 a 16 04 58](https://user-images.githubusercontent.com/28752161/33079464-efc30032-ced5-11e7-9030-d3cd1d1fe05a.png)

Here is item.picture I'm using in the avatar prop : 
![capture d ecran 2017-11-21 a 16 07 41](https://user-images.githubusercontent.com/28752161/33079612-5d7231ca-ced6-11e7-8105-15ddecd51015.png)

Here is the bug I get : 
![image-1 jpg](https://user-images.githubusercontent.com/28752161/33079751-aefd458e-ced6-11e7-8d5e-740a58afb886.jpeg)

Any idea why avatar uri is not working ? It working perfectly fine with Image uri in the rest of my app.

I'm using : 
"react-native-elements": "^0.15.0",
"expo": "^22.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz",

Thanks a lot !

**Comment by xavier-villelegier** [comment]
@AlexisJamin As you can see [here](https://facebook.github.io/react-native/docs/image.html) the `uri` has to be an URL. Here you're passing `{ uri: item.picture }` and picture is an object, so you have this error telling you that it can not convert your object into a valid URL.

Using `picture.url` as the `uri` should do the job
```jsx
<ListItem
  …
  avatar={<Image source={{ uri: item.picture.url }} />}
  …
/>
```

**Comment by AlexisJamin** [comment]
thanks @xavier-villelegier for your reply ! 

I've tried it already, but I got : 

<img width="375" alt="image-1-1" src="https://user-images.githubusercontent.com/28752161/33135028-978fc450-cfa1-11e7-8ca9-b7d7b40a69dd.png">

I also tried image.picture.url() as it is suggested in Parse Server docs, I get : 

<img width="375" alt="image-1" src="https://user-images.githubusercontent.com/28752161/33135073-b0f3673a-cfa1-11e7-9332-efc017c22fd2.png">

This is really annoying -_-

Thanks again for your help !

**Comment by xavier-villelegier** [comment]
@AlexisJamin What if you do:

```jsx
<ListItem
  …
  avatar={{ uri: item.picture.url }}
/>
```

If you still have `undefined is not an object`, does your picture come from an API call? If so try to do `avatar={{ uri: image.picture && image.picture.url }}`

**Comment by AlexisJamin** [comment]
Thanks so much @xavier-villelegier ! 

avatar={{ uri: image.picture && image.picture.url }} worked ! 

PS : I added you on LinkedIn since you're also from Paris ! :)
