### ISSUE TITLE
Header width on landscape

### ISSUE THREAD

**Issue by piu130** [react-native-training/react-native-elements#721]
### Description

1. Explain what you did

I tried `<Header />`-component in landscape.

2. What you expected to happen

Header width should go over whole screen.

3. What actually happens

Header width does not change.

### Solution

[This](https://github.com/react-native-training/react-native-elements/blob/master/src/header/Header.js#L99) line should be `width: '100%`. Works also with `rightComponent` (is pushed to the right then). I can only verify this on android (emulator and phone). So no PR.

**Comment by xavier-villelegier** [comment]
Hey @piu130, there is a PR on the road (https://github.com/react-native-training/react-native-elements/pull/703) about that. It should be merged before the next release 👍

**Comment by xavier-villelegier** [comment]
@piu130 I'll let that open until the fix has been merged and released, to avoid others opening new issues about the same thing

**Comment by xavier-villelegier** [comment]
@piu130 Fixed in `v0.18.3`
