### ISSUE TITLE
<FlatList/> support for <List/>

### ISSUE THREAD

**Issue by kubido** [react-native-training/react-native-elements#722]
is there any reason why it's not support FlatList yet ?

**Comment by xavier-villelegier** [comment]
@kubido The `List` component is just a wrapper with some styling around the children. Actually, you can use it with everything you want, not just a list. So yes, you can use it with a `FlatList` doing the following:
```jsx
<List>
  <FlatList
    …
  />
</List>
```

**Comment by lijunle** [comment]
It could be better to use `<FlatList>` instead of `<ListView>` as the latter one is [deprecated](https://facebook.github.io/react-native/docs/listview.html) now.

**Comment by saladj** [comment]
@lijunle ListView is not used here. The List component is a just a View with some styling see: https://github.com/react-native-training/react-native-elements/tree/master/src/list

**Comment by pk936** [comment]
@lijunle  He is using <List> component not <ListView />
