### ISSUE TITLE
Featured Tile error - <Image> cannot have children

### ISSUE THREAD

**Issue by josephclawrence** [react-native-training/react-native-elements#723]
When I try to use a featured tile, I receive the following error (in my iOS simulator):

The <Image> component cannot contain children. If you want to render content on top of the image, consider using absolute positioning.

The issue is of course in FeaturedTile.js.

Is this a versioning issue, or something to be fixed? Are there any workarounds for now?

Thank you

**Comment by xavier-villelegier** [comment]
@josephclawrence Fixed in the `v0.18.3`, feel free to reopen this issue if you still have the issue 👌
