### ISSUE TITLE
Expo demo app needs update

### ISSUE THREAD

**Issue by mgscreativa** [react-native-training/react-native-elements#725]
Hi! Trying the expo demo app, I'm getting

>  "Error while loading: Experience: "@ monte9/react-native-elements-app" for platform "ios" and release channel "default" was not published recently enough to be used on this client. The author will need to publish a new version.." (code 400)

I'm using Expo client v2.1.3

**Comment by mgscreativa** [comment]
Sorry, I haven't seen the app repo...

**Comment by xavier-villelegier** [comment]
@Monte9 Could you run `exp publish` on the `master` branch? If this doesn't solve the issue then we'll need to update the demo app to Expo SDK 23 since they introduce release channels in the v23.

**Comment by mgscreativa** [comment]
Hi! @xavier-villelegier maybe you should post your suggestion here https://github.com/react-native-training/react-native-elements-app/issues/3

**Comment by xavier-villelegier** [comment]
@mgscreativa Fixed 👍
