### ISSUE TITLE
The official Expo demo app doesn't work in the latest iOS Expo (v2.1.3)

### ISSUE THREAD

**Issue by deden** [react-native-training/react-native-elements#727]
### The official Expo demo app doesn't work in the latest iOS Expo (v2.1.3)
Expo link : `exp://exp.host/@monte9/react-native-elements-app`
or https://expo.io/@monte9/react-native-elements-app

1. Explain what you did
Open official demo inside Expo client on iOS 10.

2. What you expected to happen
a working demo app.

3. What actually happens

Error page with message : 
There was a problem loading the experience.
`exp://exp.host/@monte9/react-native-elements-app`
"Error while loading: Experience exp://exp.host/@monte9/react-native-elements-app for platform "ios" and release channel "default" was not published recently enough to be used on this client. The author will need to publish a new version.." (code 400)

I also noticed that the latest build was 5 months ago.

**Comment by stephan-nordnes-eriksen** [comment]
I seem to have a similar issue on Android: `Uncaught error: Could not load exp://...`

**Comment by xavier-villelegier** [comment]
Hey guys this has been fixed, the example app is back on expo 🔥
