### ISSUE TITLE
How to set the `borderBottomColor` of `ListItem`

### ISSUE THREAD

**Issue by fengyun2** [react-native-training/react-native-elements#731]
I want to set the borderBottomColor of the ListItem, but check out the API and did not tell me.

"react-native-elements": "^0.18.2",

![image](https://user-images.githubusercontent.com/8147202/33226350-c70bdbde-d1c6-11e7-9d16-ee1ae8fac5e7.png)

**code:**

```js

const list2 = [
  {
    name:
      'Amy Farha Amy Farha Amy Farha Amy Farha Amy Farha Amy Farha Amy Farha Amy Farha',
    avatar_url:
      'https://s3.amazonaws.com/uifaces/faces/twitter/ladylexy/128.jpg',
    subtitle: 'Vice President'
  },
  {
    name: 'Chris Jackson',
    avatar_url:
      'https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg',
    subtitle: 'Vice Chairman'
  },
  {
    name: 'Amanda Martin',
    avatar_url: 'https://s3.amazonaws.com/uifaces/faces/twitter/brynn/128.jpg',
    subtitle: 'CEO'
  },
  {
    name: 'Christy Thomas',
    avatar_url:
      'https://s3.amazonaws.com/uifaces/faces/twitter/kfriedson/128.jpg',
    subtitle: 'Lead Developer'
  },
  {
    name: 'Melissa Jones',
    avatar_url:
      'https://s3.amazonaws.com/uifaces/faces/twitter/nuraika/128.jpg',
    subtitle: 'CTO'
  }
];

        <List containerStyle={{ marginBottom: 20, borderColor: '#eee' }}>
          {list2.map((item, index) => (
            <ListItem
              containerStyle={{ borderColor: '#eee' }}
              wrapperStyle={{ borderColor: '#eee' }}
              roundAvatar
              avatar={{ uri: item.avatar_url }}
              key={index}
              onPress={log()}
              title={item.name}
              subtitle={item.subtitle}
              titleNumberOfLines={1}
              badge={{
                value: 3,
                textStyle: { color: 'orange' },
                containerStyle: { marginTop: 0 }
              }}
            />
          ))}
        </List>
```

**Comment by xavier-villelegier** [comment]
Hey @fengyun2 
You can use the `containerStyle` props 👍
```jsx
<ListItem
  containerStyle={{ borderBottomColor: 'red' }}
  …
/>
```

**Comment by xavier-villelegier** [comment]
Closing this as it has been inactive for 1 month. @fengyun2 ping me if you still have this issue 😊

**Comment by mateen-hussain** [comment]
@xavier-villelegier Any idea how to split Avatar and Title in seperate lines? I tried apply flexDirection and JutifyContent, to containerStyle for ListItem but doesnt seem to do it.

```
containerStyle={{
        padding:20,
        flexDirection:'column',
        alignItems:'center',
        justifyContent: 'space-around',
        borderBottomColor: secondaryColor,
		    borderTopColor: secondaryColor,
      }}
```

**Comment by xavier-villelegier** [comment]
Hey @mateen-hussain, in the v1 beta there is a fresh new `ListItem` component with a `leftElement` props that lets you add generic component in the `ListItem` like this:

```jsx
<ListItem
  leftElement={
    <View>
      <Avatar source={{ uri: 'https://via.placeholder.com/150x150' }} />
      <Text>Test</Text>
    </View>
  }
/>
```

**Comment by yeomann** [comment]
I want to completely remove this line, but its not going away. 

`"react-native-elements": "^0.19.1"`
is this a bug?

<img width="947" alt="screenshot 2018-11-02 at 17 00 24" src="https://user-images.githubusercontent.com/5970751/47922924-da28e380-dec0-11e8-8a79-645e0fdae2d9.png">

**Comment by iRoachie** [comment]
@yeomann You are adding styles to the List but expect the ListItem inside to be affected?

**Comment by yeomann** [comment]
@iRoachie according to @xavier-villelegier  comment, yeah. but docs are little bit scattered as i see. i was thinking the same

**Comment by iRoachie** [comment]
In the comment by @xavier-villelegier he is using the `containerStyle` prop on the **ListItem** not he **List** like you did in your example.

**Comment by yeomann** [comment]
@iRoachie  did you read the question of @fengyun2 he was asking about color of **ListItem** and @xavier-villelegier  suggested to use `containerStyle` prop. This conversation is ain't gonna help as my problem is solved. so thanks for assisting.

**Comment by iRoachie** [comment]
![screen shot 2018-11-02 at 11 15 12 am](https://user-images.githubusercontent.com/5962998/47923731-974f1780-de90-11e8-9741-266a1bce781e.jpg)

I was referring to the example you made here, where you added the `containerStyle` on the <List /> element.

Both `<ListItem />` and `<List />` have `containerStyle` props. I see you updated your comment to use it correctly on the ListItem.

**Comment by xavier-villelegier** [comment]
@fengyun2 There is also an example with the answer showing it's on the `ListItem` 😅
<img width="802" alt="capture d ecran 2018-11-02 a 16 14 32" src="https://user-images.githubusercontent.com/17592779/47923763-90d59580-deba-11e8-82ff-f8cc950f88f1.png">

I edited my answer in case that wasn't clear. Glad you finally fixed it ! Happy coding 👍

**Comment by nihp** [comment]
Any one know how to move the chevron icon little bit left as I mentioned in the below screen shot
![screenshot 2018 12 14 at 11 35 47 am](https://user-images.githubusercontent.com/36992338/49986102-8962db00-ff94-11e8-907f-b94e51b760be.png)

**Comment by iRoachie** [comment]
@nihp can you create a new issue
