### ISSUE TITLE
LIstItem component TouchableHighlight onPress not working

### ISSUE THREAD

**Issue by mikebski** [react-native-training/react-native-elements#735]
Also posted here, but there is no SO tag for react-native-elements:

https://stackoverflow.com/questions/47491988/react-native-listitem-component-touchablehighlight-onpress-not-working

I have the following React Native ListItem and the onPress is not logging to the console:

 ```
    <ListItem
        rightIcon={{name: 'delete', style: {color: 'white'}}}
        component={TouchableHighlight}
        containerStyle={styles[item.foodType]}
        title={<Text style={styles[item.foodType]}>{item.amount}&nbsp;{item.foodType}&nbsp;
    <FormattedDateTime epoch={item.when}/></Text>}>
        onPress={() => console.log("Feeding", item) }
    </ListItem> 
```

Everything else works fine, list looks good, etc...  I have tried without the component definition, making the right icon onPress as well, and more.

Why do I not see the message?

**Comment by xavier-villelegier** [comment]
The default component is already a `TouchableHighlight`, so a simple `onPress` should do the job?
```jsx
<ListItem
  onPress={() => console.log('hey')}
  …
/>
```

**Comment by xavier-villelegier** [comment]
The closing tag was before the `onPress` props. (Cf Stackoverflow answer)
