### ISSUE TITLE
ListItem Switch Component doesn't stay switched on

### ISSUE THREAD

**Issue by evanmcd** [react-native-training/react-native-elements#737]
From the Snack that was referenced in #256, I'm seeing the switch reverting to off each time it is switched on.

Adding switchButton to my code and testing in the iOS simulator reproduced the same issue.

Steps to reproduce: 
1. Open https://snack.expo.io/SJPQNScUZ. Turn switch in row 2 on.
2. Switch should stay on
3. Switch turns off

Using RNE version 0.18.4

```
<List>
    <FlatList style={{width: viewportWidth}}
        data={this.state.contacts}
        ListHeaderComponent={this.renderContactListHeader}
        renderItem = {({item}) => renderListItem(item)}
        keyExtractor={item => item.id}
    />
</List>
```

```
renderListItem = (item) => {
    const li = <ListItem
        hideChevron
        switchButton
        title={`${item.firstName} ${item.lastName}`}
        subtitle={item.emails[0].email}
        onPress={() => handleContactPress(item)}
    />;
    return li;
}
```

**Comment by iRoachie** [comment]
Seems to be a bug in react native. The switch itself which we use under the hood doesn't update standalone either. https://snack.expo.io/SJgFuZtlz

**Comment by jnpdx** [comment]
Both the React Native `Switch` and this implementation within Elements rely on a stored state for the `Switch`.  You can reference the state of the Switch in this example by passing a value to the `switched` parameter.

See updated Snack: https://snack.expo.io/HkLp4-qef

Pertinent code:
```
<ListItem
            switchButton
            switched={this.state.switchState}
            hideChevron
            title=":) Here it is!"
            onSwitch={(value) => {
              this.setState(previousState => {
                return {...previousState,switchState: value}
              })
            }}
          />
```

**Comment by xavier-villelegier** [comment]
As it is specified [in the React Native Switch documentation](https://facebook.github.io/react-native/docs/switch.html#switch), the `Switch` component is a **controlled component**. This means that you have to handle by yourself the state of the component to reflect user actions, by using the `onValueChange` callback and updating an internal state. You'll then use this state as the `value` props of the `Switch` component 🙌
Thanks for the Snack @jnpdx !

**Comment by iRoachie** [comment]
My bad, just realized I attached the wrong variable in my snack :D

**Comment by xavier-villelegier** [comment]
@evanmcd Closing this as it has been inactive for 1 month! Let us know if you still have some troubles to make the switch work.

**Comment by evanmcd** [comment]
Sorry for the delay - I'm just getting back to this functionality in my app now. Appreciate the info @jnpdx. The example you provided works for me.
