### ISSUE TITLE
[Same as 668] Tile: Warning: Failed prop type: Invalid props.style key 'resizeMode' supplied to 'View'

### ISSUE THREAD

**Issue by Jun711** [react-native-training/react-native-elements#740]
### Description
I get the same warning as listed on this issue: https://github.com/react-native-training/react-native-elements/issues/668

```
Warning: Failed prop type: Invalid props.style key resizeMode supplied to View.
Bad object: {
"alignItems": "center",
"justifyContent": "center",
"resizeMode": "cover",
"backgroundColor": "#ffffff",
"flex": 2
}
...
```

Versions of the dependencies
```
"dependencies": {
	"react": "16.0.0",
	"react-native": "^0.50.4",
	"react-native-elements": "^0.18.4",
	"react-native-vector-icons": "^4.4.2",
	"react-navigation": "^1.0.0-beta.21"
},
```

### Reproduction Steps and Sample Code
You can clone my practice repo under that branch. I see the warning when I run it on an android simulator. 
https://github.com/Jun711/ReactNativePractice/tree/resizeModeWarning

**Comment by xavier-villelegier** [comment]
I've tested with a new project, I have the warning on RNE `0.17.0` but not anymore after `0.18.0`.
I can't open your project, for some reasons Expo doesn't find your `app.json`

```sh
╰─ exp start
[exp] Using project at ReactNativePractice-resizeModeWarning
[exp] Error: Missing app.json. See https://docs.expo.io/
[exp] Couldn't start project. Please fix the errors and restart the project.
```

**Comment by Jun711** [comment]
@xavier-villelegier I didn't test using Expo so I am not sure how to make it work on expo. 
What you can do is

git clone 
npm install
open up an android simulator
react-native start
react-native run-android

**Comment by iRoachie** [comment]
Yea the bug is here https://github.com/react-native-training/react-native-elements/blob/master/src/tile/Tile.js#L60. `resizeMode` is a prop not a style

**Comment by fsunset** [comment]
Hi guys, is there any suggestion for this one? Of we just have to wait they remove that line? Thanks a lot! :)

**Comment by iRoachie** [comment]
Hey @fsunset , usually we leave fixes like these open for newcomers to open source so they can get a chance to contribute. However if no one jumps on it then one of the maintainers will make the patch.

**Comment by fsunset** [comment]
@iRoachie - got you :) Ty!

**Comment by iRoachie** [comment]
There's a PR for this open https://github.com/react-native-training/react-native-elements/pull/763

**Comment by francisrod01** [comment]
The same problem here.
I make this modifications on my own, but still show this red warning.

**Comment by xavier-villelegier** [comment]
@francisrod01 [This modification](https://github.com/react-native-training/react-native-elements/pull/763/files#diff-e33ac247747fe67f5dc90e21ca11e001) should do the job. This will be in the next release

**Comment by francisrod01** [comment]
Thank you @xavier-villelegier !
I'm waiting for it! :)
