### ISSUE TITLE
Icoin not displaying

### ISSUE THREAD

**Issue by thanhppm** [react-native-training/react-native-elements#742]
Hi guy
In my project, icon not showing

I has create project with cli create-react-native-app AwesomeProject
and used react-native link
 but not avaialbe

**Comment by iRoachie** [comment]
Hey @thanhppm can you post some example code here so we can see what's causing the issue? Also list your react-native version and react-native-elements version

**Comment by xavier-villelegier** [comment]
Hey @thanhppm, closing this issue since we don't have enough information to help you, and it has been inactive for a month. Feel free to reopen it if you still can't see your icon.
