### ISSUE TITLE
SearchBar's TextInput gets cleared with showLoadingIcon prop.

### ISSUE THREAD

**Issue by kmorales13** [react-native-training/react-native-elements#743]
### Description

1. Explain what you did
_Tried to use the SearchBar component with the `showLoadingIcon` prop._
2. What you expected to happen
_`ActivityIndicator` should show and hide according to the value provided._
3. What actually happens
_`ActivityIndicator` works as expected, but the `TextInput` gets cleared afterwards._

Also please include the version of `react-native-elements` that you are using.
_Version 0.18.4_ _with RN 0.50.1_

### Reproduction Steps and Sample Code
_Just use a SearchBar component with showLoadingIcon prop._
https://snack.expo.io/HyFj7bseG

### Solution
_Found out that commenting the following code in `Search.js` (lines 86-88) fixes the problem, but I'm not really sure what causes it._

```
clearIcon && showLoadingIcon && { paddingRight: 50 },
((clearIcon && !showLoadingIcon) ||
(!clearIcon && showLoadingIcon)) && { paddingRight: 30 },
```

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by xavier-villelegier** [comment]
@kmorales13 Mmh [this demo](https://snack.expo.io/Hk8UK4neM) is working for me, let me know if it fits to your use case

**Comment by kmorales13** [comment]
@xavier-villelegier your demo shows the same behaviour, as soon as you stop typing, the `ActivityIndicator` is shown and the `TextInput` cleared, is this expected?

**Comment by xavier-villelegier** [comment]
@kmorales13 Mmh the `TextInput` isn't cleared for me
![nov-29-2017 19-16-34](https://user-images.githubusercontent.com/17592779/33391618-e77b8d08-d539-11e7-9a5f-f163017366a2.gif)

**Comment by kmorales13** [comment]
@xavier-villelegier Well, this is weird. This is what happens to me when I run your snack.
<img src="https://i.imgur.com/1O2bRpW.gif" height="500" />

**Comment by xavier-villelegier** [comment]
@kmorales13 Ah on Android! I have this behavior too.
I think that on Android you have to control the component, to avoid loosing the content of the `TextInput` at each `render`.
Check [this example](https://snack.expo.io/HkYpZt2lz) ✌️

**Comment by laurence-myers** [comment]
I have also run into this issue.

If setting the "value" prop is the official solution, can the documentation be updated to say this is required for Android?

**Comment by motogod** [comment]
Facing the same issue so comes to here.

In my case use chinese key board, so I have to use this:

value={Platform.OS === 'android' ? this.state.text : null}

Hope can be updated this by next version.
