### ISSUE TITLE
Number of lines in title for Card

### ISSUE THREAD

**Issue by 6axter82** [react-native-training/react-native-elements#744]
Hi,

I would like to set the Card's title to be no longer than 2 lines. Is there any way to do so?

**Comment by iRoachie** [comment]
Currently there's no way to do that right now. Adding a `titleNumberOfLines` prop would allow this behavior. If anyone is interested they can look at the `Tile` component that has this prop.

https://github.com/react-native-training/react-native-elements/blob/master/src/tile/Tile.js#L130

**Comment by 6axter82** [comment]
I did a pull request [https://github.com/react-native-training/react-native-elements/pull/746](url)

**Comment by xavier-villelegier** [comment]
@6axter82 Thanks for your PR, it has been merged in the `v0.18.5`! This release should be on npm in few hours 👌
