### ISSUE TITLE
Can we increase the spacing between list items? 

### ISSUE THREAD

**Issue by Ali-Dalal** [react-native-training/react-native-elements#745]
How to increase the spacing between list items? I tried to add marginBottom but it doesn't work

**Comment by iRoachie** [comment]
Hey @Ali-Dalal you can use the `containerStyle` prop to add a margin between items. I made a snack so you can see what it looks like. https://snack.expo.io/HyQT8Xhxz

**Comment by Ali-Dalal** [comment]
Thanks @iRoachie , Container style working fine.
