### ISSUE TITLE
Can't provide any custom styles for FormInput ex: textIndent does not work!!!!!

### ISSUE THREAD

**Issue by sathishjobs** [react-native-training/react-native-elements#747]

**Comment by iRoachie** [comment]
Hey @sathishjobs, as far as I know `textIndent` isn't a prop on the TextInput or the style object. Can you post a code example so we could see how you are using this?

**Comment by xavier-villelegier** [comment]
Closing this issue as it has been inactive for a month. Feel free to reopen it or ping me if this still occurs.
