### ISSUE TITLE
Vertical sliders

### ISSUE THREAD

**Issue by RolyMolnar** [react-native-training/react-native-elements#748]
Looked for a vertical slider everywhere but couldn't find one. Would it be possible to add a vertical orientation to your sliders?

**Comment by xavier-villelegier** [comment]
@RolyMolnar We added an `orientation` props to the Slider in the `v0.18.5`, which will be released on npm today. `orientation="vertical"` should do the job, but feel free to open issues if it doesn't work as expected!

**Comment by dileepbolisetti** [comment]
@xavier-villelegier  there is no npm version with 0.18.5 the latest i was able to install is 0.11.0 only give us info on how to update to new version thanks in advance
