### ISSUE TITLE
Styling issue with Card element after upgrading to RN 0.50

### ISSUE THREAD

**Issue by fsunset** [react-native-training/react-native-elements#749]
### Description

1. I have a ```Card``` element inside a ```FlatList```. I had this working last week, it has crashed AFTER an upgrade I did yesterday to React Native 0.50. I also Had to replace the wrapper element of the FlatList for a ```View```, I had a ```List```, but after I upgraded it showed a white background as well. With ```View``` it works as you can see on SS.

### Version:
```javascript
"react-native": "0.50.4",
"react-native-elements": "^0.18.4",
```

### Sample Code

```javascript
return(
      <View style={styles.list}>
        { this.state.loaded ?
          <FlatList
            data={this.state.data}
            renderItem={ ({item}) =>
              <TouchableWithoutFeedback
                onPress={
                  () => this.props.navigation.navigate('RecipeInfo', {'uri': item.recipe.uri})
                }
              >
                <View>
                  <Card
                    style={itemsUserStyles.card}
                    title={item.recipe.label}
                    titleStyle={itemsUserStyles.title}
                    image={{uri: item.recipe.image}}
                  >
                    <View style={[itemsUserStyles.recipeTagsContainer]}>
                      {
                        (item.recipe.dietLabels.concat(item.recipe.healthLabels)).map((tag, i) => {
                          return (
                            <Text
                              key={i}
                              style={itemsUserStyles.recipeTags}
                            >
                              {tag}
                            </Text>
                          )
                        })
                      }
                    </View>
                  </Card>
                </View>
              </TouchableWithoutFeedback>
            }
            keyExtractor={item => item.recipe.uri}
          />
          :
          <View style={styles.spinnerContainer}>
            <ActivityIndicator color="#ea4e3c" size={1} />
          </View>
        }
      </View>
    );
```

As you can see, I'm getting a default white background for ```Card``` element, which I cannot replace for transparent, it just doesn't work! I presume this is because I updated to RN 0.50. Since Last week I still used .49 and this didn't happen. 

![bildschirmfoto 2017-11-30 um 18 54 54](https://user-images.githubusercontent.com/1210507/33461633-52813ce8-d601-11e7-8161-ba04d5f52a57.png)

Thanks a lot for your time/help. 

- F

**Comment by xavier-villelegier** [comment]
@fsunset Could you just downgrade back to RN .49 to post a screen of what you want to achieve, and at the same time to check that it is really because of RN 0.50?
On Snack using SDK 23 (RN 0.50) I am able to use a transparent background with `Card`, check out [this example](https://snack.expo.io/SJoGziAlM)

**Comment by fsunset** [comment]
@xavier-villelegier - Thanks for your reply mate. I say this is a 0.50 based error because before I update my app it worked! I cannot set a transparent Bg-color for Card. even with inline styling, I had to replace my ```FlatList``` wrapper from ```List``` to ```View```, because otherwise the white background will also appear! 

Thanks for your time/help :)

Please take a look:

![bildschirmfoto 2017-12-03 um 16 15 34](https://user-images.githubusercontent.com/1210507/33531643-f44614f0-d85d-11e7-8991-390ae4f564e5.png)
![bildschirmfoto 2017-12-03 um 16 18 32](https://user-images.githubusercontent.com/1210507/33531644-f459b8fc-d85d-11e7-9559-4e7551cf6a8a.png)
![bildschirmfoto 2017-12-03 um 16 25 11](https://user-images.githubusercontent.com/1210507/33531645-f46ef5c8-d85d-11e7-8514-b9358630f283.png)

**Comment by iRoachie** [comment]
Hey @fsunset the prop for styling the container is called `containerStyle`. Can you try using that instead of `style`?

**Comment by fsunset** [comment]
cc @xavier-villelegier 

@iRoachie - yes sir! That's the fix for it. Closing this one. Thanks a lot for the time guys.

**Comment by xavier-villelegier** [comment]
@fsunset Did you check my example from the previous answer? I used `containerStyle` in it.
Btw it is strictly related to RNE, and not RN 0.50. You're not able to override the `style` props since RNE `v0.18.1`.
You can check [the docs of `Card`](https://react-native-training.github.io/react-native-elements/API/card/#card-props) to see all available props 🙌
