### ISSUE TITLE
ListItem: numberOfLines and ellipsis

### ISSUE THREAD

**Issue by kbrandwijk** [react-native-training/react-native-elements#754]
I'm showing the contents of a multiline text box in the subtitle of a ListItem. Now, I use numberOfLines to limit the amount of text that I'm showing in the ListItem. That works well.

However, I have no indication if the text is actually longer than the numberOfLines specified. Would it be possible to have an ellipsis added to the last line if the text is longer?

**Comment by xavier-villelegier** [comment]
@kbrandwijk By default when you use `numberOfLines` you have a "tail" ellipsis.
```jsx
<ListItem
  title="Test"
  subtitle="this is a really long subtitle this is a really long subtitle this is a really long subtitle this is a really long subtitle"
  subtitleNumberOfLines={2}
/>
```

**Result**
![image](https://user-images.githubusercontent.com/17592779/33545357-3517c5fc-d8de-11e7-8454-753b89273d3a.png)

You can check [this snack example](https://snack.expo.io/ryiDrqMZM) 👍

**Comment by paulddrix** [comment]
Hello, I have similar inquiry. I am building a chat app and the message bubble is a ListItem component. However, I want the numberOfLines to be infinite so that the text wraps. is there a way to do that or is it better to just add in a custom view for the title prop? Thank you for your time.

**Comment by kbrandwijk** [comment]
@xavier-villelegier That was not what I meant. If the text I am showing consist of three short lines, it will just show two lines, without any ellipsis anywhere.

**Comment by xavier-villelegier** [comment]
@kbrandwijk Oh okay I see what you mean. Unfortunately this is a RN issue as you can see [on this example](https://snack.expo.io/rJUTjCQMM) 😕

@paulddrix Just use `numberOfLines={null}` to disable its effect. Check out [this snack](https://snack.expo.io/ByCW6CQGz)

**Comment by kbrandwijk** [comment]
@xavier-villelegier I didn't realize that this was standard RN behavior from `Text.numberOfLines`. I will submit a FR on RN. As no action will be needed on `react-native-elements` once they implement that, feel free to close this issue.
