### ISSUE TITLE
[ts] Property 'text' does not exist on 'HeaderSubComponent'

### ISSUE THREAD

**Issue by kbrandwijk** [react-native-training/react-native-elements#758]
I just upgraded from `react-native-elements` 0.16.0 to 0.18.4 and I now get the above typings warning on `<Header centerComponent={{text: 'test'}}>`.

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/pull/751/commits/593c69d9479d245d795238dc0c24dac6d16c1de9. Will be available next release.

**Comment by xavier-villelegier** [comment]
@kbrandwijk `v0.18.5` available on npm with this fix 👌
