### ISSUE TITLE
Underlay Color always gray?

### ISSUE THREAD

**Issue by newfylox** [react-native-training/react-native-elements#765]
**react-native-elements 0.18.4**

Is it possible to change the color shadow effect when a button is pressed? I see that `underlayColor` is used for "*underlay color for button press*" but when I set a color (e.g. let's say **red**), it's still gray when I touch the button.

Is there something that I'm missing? Thanks!

**Comment by iRoachie** [comment]
I'm not sure I'm understanding you. Using the `underColor` prop doesn't work? https://snack.expo.io/rJDI5Pv-G

**Comment by newfylox** [comment]
You did understand well and yes I did use `underColor` prop. I just found that it's an Android issue because of you (thank you). With Snack you can see that it works on iOS but not on Android and I'm using Android at home. That's why I thought it didn't work.

Any hint about this issue?

**Comment by iRoachie** [comment]
We use different component on different platforms under the hood. On iOS we use `TouchableHighlight` and on android API > 21 `TouchableNativeFeedback`. `TouchableNativeFeedback` doesn't have a `underlayColor` prop :\

**Comment by newfylox** [comment]
`TouchableHighlight` seems to fit for both. I guess the reason using `TouchableNativeFeedback` is to optimize Android experience performance, right? Or any reason I don't know?

**Comment by iRoachie** [comment]
Native buttons on android usually have a ripple affect when pressed. `TouchableNativeFeedback` gives that effect

**Comment by newfylox** [comment]
Alright, thanks for the info. Maybe could be great to have an option to toggle between desired effects? Anyways, I'm glad to know I wasn't crazy about `underlayColor` property :wink:

**Comment by iRoachie** [comment]
Button has a `Component` prop where you can specify explicitly which one to use.

**Comment by newfylox** [comment]
Wow! It took me you to help me understand the importance of that property! Thank you so much!!!

**Comment by iRoachie** [comment]
Ha! Glad I could help mate
