### ISSUE TITLE
[ts] ListItem avatar type error

### ISSUE THREAD

**Issue by kbrandwijk** [react-native-training/react-native-elements#767]
Types of property 'avatar' are incompatible.
      Type 'Element' is not assignable to type 'string | ImageURISource'.
        Type 'Element' has no properties in common with type 'ImageURISource'.

**Comment by iRoachie** [comment]
Good find. An easy fix is to add `JSX.Element` to the avatar union https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L1019

**Comment by iRoachie** [comment]
Merged. Will be live in next release

**Comment by xavier-villelegier** [comment]
`v0.19.0` is now on npm 👍
