### ISSUE TITLE
When making a Button with an icon only, the icon is not centered

### ISSUE THREAD

**Issue by hendrul** [react-native-training/react-native-elements#771]
The icon component inside Button adds a marginRight: 15px, what makes the icon get uncentered... the only way I found to fix this is...
```js
<Button icon={{ name: 'filter-list', style: { marginRight: 0 } }}/>
```
![captura de pantalla 2017-12-08 a la s 1 20 10 p m](https://user-images.githubusercontent.com/1224275/33777281-8dacd8bc-dc1a-11e7-8ca8-cb0c7b8b7d2b.png)

**Comment by xavier-villelegier** [comment]
Hey @hendrul, I advise you to use the `Icon` component if you just need a clickable icon, as suggested in #639

**Comment by santoshzp** [comment]
same issue

**Comment by xavier-villelegier** [comment]
Closing this since the `Icon` component does the job.
We updated the `Button` component in the `v1.0.0-beta`, if this is really necessary we will fix it in the v1.

**Comment by mhsekhavat** [comment]
@xavier-villelegier Some features like `disabled` and `loading` props are not implemented in `Icon` but it is reasonable to have a button with only a centered icon.

**Comment by xavier-villelegier** [comment]
Just FYI, in the `v1.0.0-beta4` coming soon, the icon should be centered if you provide `title={null}` or `title=""`
