### ISSUE TITLE
Icon in Avatar doesn't work.

### ISSUE THREAD

**Issue by kk412027247** [react-native-training/react-native-elements#772]
### Description

Icon in Avatar doesn't work, 
but the Icon Component is work when independently.

appear Waring: 
Failed prop type: Invalid prop 'name' of value 'user' supplied to 'Icon',expected one of['3d-rotation ....]

I don't know what this means.
need some help.
Thank a lot.

### Code

```
import React from 'react';
import {View} from 'react-native';
import {Avatar,Icon} from 'react-native-elements';

export default ()=>(

//this works normally
  <View>
    <Icon
      name='rowing'
      containerStyle={{marginTop:115}}
    />

 //Doesn't work, and appears waring: Failed prop type: Invalid prop 'name' of value 'user' supplied to 'Icon'
    <Avatar
      small
      rounded
      icon={{name: 'user'}}
      onPress={() => console.log("Works!")}
      activeOpacity={0.7}
      containerStyle={{marginLeft: 20, marginTop: 115}}
    />
  </View>
);
```

### The screen
<img width="376" alt="2017-12-09 3 33 52" src="https://user-images.githubusercontent.com/30715186/33793671-79cbd816-dcf6-11e7-8e4c-e34bab67c8e7.png">

**Comment by xavier-villelegier** [comment]
@kk412027247 By default, RNE is using `MaterialIcons`. If you check the list of the available icons [here](https://expo.github.io/vector-icons/), you can see that `user` doesn't exist for `MaterialIcons`.

Two possibilities here:

**1. Use the good icon**
```jsx
<Avatar
  small
  rounded
  icon={{name: 'person'}}
  onPress={() => console.log("Works!")}
  activeOpacity={0.7}
  containerStyle={{marginLeft: 20, marginTop: 115}}
/>
```

**2. Specify another icon type**
```jsx
<Avatar
  small
  rounded
  icon={{name: 'user', type: 'font-awesome'}}
  onPress={() => console.log("Works!")}
  activeOpacity={0.7}
  containerStyle={{marginLeft: 20, marginTop: 115}}
/>
```

**Comment by kk412027247** [comment]
@xavier-villelegier 
Oh~,I see, thank you very much ❤️

**Comment by danilo525** [comment]
@xavier-villelegier Nice, it helped me too. Thank you!
