### ISSUE TITLE
Make npm package smaller

### ISSUE THREAD

**Issue by kbrandwijk** [react-native-training/react-native-elements#775]
Currently, the npm package contains everything from docs to examples and and anything in between. Would it be possible to `.npmignore` a lot of that stuff, and have only the actual components in the package?

**Comment by iRoachie** [comment]
cc @xavier-villelegier @Monte9 What do you guys think about this? Not sure if people refer to docs through node_modules

**Comment by Monte9** [comment]
Hmm.. I am not too concerned about it. We no longer have an example app in this repo and the docs are just `.md` files so it shouldn't be too big. 

@kbrandwijk are there any specific things you had in mind that would benefit from a reduced package size?

**Comment by kbrandwijk** [comment]
Well, the docs folder alone is 6,5 MB in my node_modules. For a mobile app, that's substantial.

**Comment by iRoachie** [comment]
Only source files are including in the build process for react-native, so it won't affect the app size of your generated apk/ipa

**Comment by kbrandwijk** [comment]
That's good to now. I'm using Expo, and I hope it's as smart as RN when deploying 😄

**Comment by iRoachie** [comment]
Ah yes! They use the same build system. Think as expo as a normal react-native application that has popular packages bundled in for you :D
