### ISSUE TITLE
List section (headers in lists) ? 

### ISSUE THREAD

**Issue by lax1n** [react-native-training/react-native-elements#777]
### Question:
So I've been looking through your documentation and can't seem to be able to find support for having section lists. Basically lists where I can set headers.

Example of what I'm looking for:
![5ofgo](https://user-images.githubusercontent.com/6804837/33905133-f368f602-df7d-11e7-8dfc-28965325e046.png)

If this already exists, I'd appreciate if somebody could point me in the right direction.

**Comment by xavier-villelegier** [comment]
@lax1n RNE doesn't provide this because React Native has a `SectionList` that does the job really well! Have a look at [the official documentation](https://facebook.github.io/react-native/docs/sectionlist.html) 👌

**Comment by xavier-villelegier** [comment]
@lax1n Mmh I don't think you need that much customisation to have something consistent. Moreover, `SectionList` has already implemented all the logic and I must admit that I don't really see the point of implementing something less efficient and less modular in RNE... 😕

Check out [this really simple snack example](https://snack.expo.io/B1pcavgMG) with a `SectionList`, there is just 3 styles and it almost looks like what you want! ✌️
![image](https://user-images.githubusercontent.com/17592779/34015538-0c02d230-e11f-11e7-94db-02be87bbeb01.png)

**Comment by xavier-villelegier** [comment]
Closing this since it has been inactive for 1 month.

**Comment by kenji-1996** [comment]
@xavier-villelegier Thank you so much for that section list example, I was trying all sorts of stuff to mix the great default component of section list with the nice listitem component from RNE <3
