### ISSUE TITLE
Is there any way to use FontAwesome icons in SearchBar for clearIcon

### ISSUE THREAD

**Issue by 6axter82** [react-native-training/react-native-elements#780]
If someone knows how, can you explain how please!

**Comment by xavier-villelegier** [comment]
Hey @6axter82, this is currently not possible, but thanks for reporting that, this should be in the next release!

**Comment by xavier-villelegier** [comment]
@6axter82 `v0.19.0` is out on npm !

**Comment by 6axter82** [comment]
This is awesome, thanks a lot!
