### ISSUE TITLE
CheckBox's fontFamily is not working

### ISSUE THREAD

**Issue by pacozaa** [react-native-training/react-native-elements#788]
### Description

1. I am trying to change fontFamily  of CheckBox
2. I expect fontFamily to change
3. but it doesn't change

then I take a look at the code and found

https://github.com/react-native-training/react-native-elements/blob/master/src/checkbox/CheckBox.js#L74

it looks suspicious. My assumption is that if you are set title(which is require), fontFamily won't effect the CheckBox but still not yet to find a solution.

All the best

**Comment by iRoachie** [comment]
Hey @pacozaa could you maybe send some example code? Here's an example using the checkbox's `fontFamily` prop and it works. Let me know if this is what you were looking for.

**Comment by nopedev** [comment]
```javascript
<CheckBox
          ...
          textStyle={{ 
              fontFamily: 'Montserrat',
              fontSize: 24,
              fontWeight: 'normal',
              color: 'red',
          }}
          ...
/>
```

At android this worked for me. 

I used ```Montserrat.ttf```, ```Montserrat_bold.ttf``` font from google fonts and added it to ```/android/app/src/main/assets/fonts```. You need to rename filenames of downloaded font files.
