### ISSUE TITLE
How can I get a value from FormInput? (Question)

### ISSUE THREAD

**Issue by hjbramos** [react-native-training/react-native-elements#789]
```
<FormInput
   ref={ref => (this.passInputRef = ref)}
   secureTextEntry
   placeholder=""
 />

 <Button
      title="Enter"
      onPress={() => {
         console.log(this.passInputRef);
         onSignIn().then(() => navigation.navigate("Home"));
      }}
 />
```

How can I get the value from this FormInput and send it to a function?

"react": "16.0.0",
"react-native": "0.51.0",
"react-native-elements": "^0.18.5",

**Comment by xavier-villelegier** [comment]
Hey, @hjbramos check out [this example](https://snack.expo.io/r1f9-5BMG), does it fit to your use case? 🤔

**Comment by hjbramos** [comment]
Hey @xavier-villelegier thanks for reply. Yes, this is work fine! I was using stateless function but using components/state is more appropriate for this case. Thanks a lot!
