### ISSUE TITLE
BouttonGroup Scratch in Ios but not Android.

### ISSUE THREAD

**Issue by karimraoudy** [react-native-training/react-native-elements#799]
Hello everyone , i'm using buttonGroup for my app everthing is working well expect  like you can see in the pictures there is some scratch that appear , i'm using EXPO and real Device , in my android device nothing appear only in my ios device (iphone 6).
expo :23.0.4 , RN: 0.50.3 👍 
 (https://user-images.githubusercontent.com/32100412/34413589-51707bb6-ebdc-11e7-9ec9-a8ccf1392d9e.jpg)
<code>
 <ButtonGroup
    selectedBackgroundColor="grey"
    onPress={this.distanceSelected}
    selectedIndex={this.state.indexdist}
    buttons={['MILES', 'KILOMETRES']}
    containerStyle={styles.bouttonContainerStyle} 
    selectedTextStyle={{color: '#fff'}}
    containerBorderRadius={15} />
</code>
<styles>
  bouttonContainerStyle:{
    height: 30,
    borderRadius:15,
    borderWidth:2,
    borderColor:'#fff',
    backgroundColor:'#fff'
  }
</styles>
Thank You so much for your help.

**Comment by xavier-villelegier** [comment]
Hi @karimraoudy, I've tested [this snack](https://snack.expo.io/SkmpR0uQG) on the simulator and on my own device, I don't have this issue 😕  I'm afraid this might be a React Native issue on the border styling… Did you try to play with the `borderWidth` or the `borderRadius` properties to see in which cases it occurs?

**Comment by karimraoudy** [comment]
thank You @xavier-villelegier  for your reply i'will try that.

**Comment by xavier-villelegier** [comment]
Closing this because it has been inactive for 1 month
