### ISSUE TITLE
How to make ListItem textInput fill all available space?

### ISSUE THREAD

**Issue by evilandfox** [react-native-training/react-native-elements#801]
Hello! ListItem textInput maximum width is only half of item width:
```
<ListItem
    title='Address'
    textInput={true}
    textInputValue={this.state.address}
    textInputOnChangeText={address => this.setState({address})}
    hideChevron={true}
/>
```
![photo5357560673846012065](https://user-images.githubusercontent.com/9137261/34476584-d8d4aba6-efb3-11e7-9077-a769b6c1f282.jpg)

How to make textInput width fill all available space like:
![photo5357560673846012063](https://user-images.githubusercontent.com/9137261/34476585-e08ee24e-efb3-11e7-9454-e8ce7f84cf23.jpg)
and truncate text only when it begin overflowing left title?
P.S.: Sorry for "adress" word) And for my English

**Comment by xavier-villelegier** [comment]
Hey @evilandfox, you're right, this is not well handled by the ListItem. Actually, the title has a `flex: 1`, so does the `TextInput`, so they are both taking half of the space. That shouldn't be the case if there is a `TextInput` (The title shouldn't have a `flex: 1` in this case). 😕

I think you can use this dirty fix as a workaround for now:
```jsx
<ListItem
  title='Address'
  textInput={true}
  textInputContainerStyle={{ flex: 3 }}
  hideChevron={true}
/>
```

This will give you this result:
![image](https://user-images.githubusercontent.com/17592779/34480905-6d984ff4-efaf-11e7-8c2b-a3ef4ad8f788.png)

**Comment by iRoachie** [comment]
Closing as inactive! If this workaround didn't work for you @evilandfox, feel free to ping me to reopen the issue. This should be handled a lot better with the `ListItem` component slated for [1.0.0-beta4](https://github.com/react-native-training/react-native-elements/milestone/2)

**Comment by ericmorgan1** [comment]
Hi,

Is there any workaround to turn the title off?
I am trying to use it with just a `leftIcon` and a text input, and there's still quite a large gap if a title isn't supplied.

I think not using a title is reasonable since we can use a `textInputPlaceholder`

Thanks!

**Comment by iRoachie** [comment]
Hey @ericmorgan1 can you create new issue? Be sure to specify your version of react-native-elements

**Comment by ericmorgan1** [comment]
@iRoachie  Thanks! #1272
