### ISSUE TITLE
FormInput margins could not be changed

### ISSUE THREAD

**Issue by AugustoAleGon** [react-native-training/react-native-elements#802]
### Description

1. Explain what you did
I am working with FormInput right now:
If I am using the component like:
```
<FormInput
        containerStyle={[styles.formContainerStyle, {marginLeft: 0, marginRight: 0}]}
        style={styles.formTextStyle}
        placeholder={placeholder}
        shake={error}
        onChangeText={(value) => input.onChange(value)}
        // input
        value={input.value}
        {...custom}
      />
```
2. What you expected to happen?
Remove all the margins that are surronded the form input.

3. What actually happens
Margins are still at the same default value. Any work around?

Also please include the version of `react-native-elements` that you are using.
Version:
 "react-native-elements": "^0.16.0",

### Reproduction Steps and Sample Code
Just copy and paste the code.

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by iRoachie** [comment]
Hey @AugustoAleGon, you should be able to use the `containerStyle` prop to change the default margin. Here's an example I made on snack.expo that shows the default margin as well as the margin removed.

**Comment by AugustoAleGon** [comment]
Yes! You are totally right. I passed it and it works. Thanks @iRoachie
