### ISSUE TITLE
[ts] ListItem keyboardType prop missing

### ISSUE THREAD

**Issue by raduflp** [react-native-training/react-native-elements#804]
in index.d.ts:1281 `textInputKeyboardType` prop is declared instead of the actual `keyboardType` prop implemented, 
Personally I find `textInputKeyboardType` to be have a more consistent naming, but I guess the future planned refactor of this component will take care of that

**Comment by iRoachie** [comment]
Hey @xavier-villelegier the easiest fix would be to change to change the typings, however I think the `keyboardType` in the source should be changed to `textInputKeyboardType` to match the other textInput props. What do you think?

**Comment by raduflp** [comment]
@iRoachie totally agree. 
At the same time having so many TextInput specific props as textInput* makes the ListItem component seam bloated. Personally I think that just exposing a single textInputProps prop (as descriped in v1 specs) on ListItem will make it more simple and more futureproof in case the TextInput api changes because you will not have to maintain the mapping between the props. This also applies to the Switch scenario. 
What do you think?

**Comment by iRoachie** [comment]
Yea I'm definitely with you on that one. Hopefully we can push out v1 beta early next month

**Comment by iRoachie** [comment]
Renamed prop in https://github.com/react-native-training/react-native-elements/commit/07e5c9c4573ddd4bf05978574a89ac38d12e5113. Should be available in next release
