### ISSUE TITLE
ListItem separator is being displaying different shades on ios

### ISSUE THREAD

**Issue by mateen-hussain** [react-native-training/react-native-elements#805]
### Description

The default ListItem separator is being displayed in varying shades of gray on ios. In below attached file the separator after the first, third, sixth items are slightly darker than others.

<img width="286" alt="screen shot 2018-01-05 at 15 43 19" src="https://user-images.githubusercontent.com/26531653/34616279-b0d96ee2-f22f-11e7-9fc9-adbafc458c28.png">

This works fine on android.

Also is there a way to change the color of these separator to a custom one ?

```"react": "^16.0.0-beta.5",
    "react-native": "^0.49.5",
    "react-native-elements": "^0.17.0",```

### Reproduction Steps and Sample Code

```
<View>
		<Text h4 style={styles.cardHeader}>Pick a slot</Text>
		<List >{
			slots.map(item => (
				<ListItem
					key={item}
					title={item}
					onPress={() => selectSlot(item)}
				/>))
		}
		</List>
	</View>
```

**Comment by xavier-villelegier** [comment]
Hey @mateen-hussain, this is related to the simulator. You can see that if you scroll slowly these shades of grey will change slightly. Try to grow your simulator, or to test on a real device, you shouldn't have this issue 👌

**Comment by mateen-hussain** [comment]
Thanks. How do I change its color.

**Comment by xavier-villelegier** [comment]
@mateen-hussain 
```jsx
<ListItem
  …
  containerStyle={{ borderBottomColor: 'red' }}
/>
```

**Comment by mateen-hussain** [comment]
Your suggestion changes the color of the List container not the border between the items
