### ISSUE TITLE
Checkbox: icon position

### ISSUE THREAD

**Issue by nahuelhds** [react-native-training/react-native-elements#806]
Hi. I'm wondering how can I align title to the left and icon to the right.

I'm not talking about `iconRight` property. What I'd like is to make something like `float: right` the icon in the row. So the title is floated left and the icon floated right.

I've made it work by combinig containerStyle and textStyle like so:

```
<CheckBox
      // ...
      iconRight
      containerStyle={{ alignItems: 'flex-end' }}
      textStyle={{ flex:1, flexDirection: 'column', alignSelf: 'center' }}
    />
```

But I'm wondering if there is not a better way to make the same

**Comment by nahuelhds** [comment]
I've just noticed I can do something better with ListItem and switchButton. Sorry for this

**Comment by krean93** [comment]
I am also trying to achieve the result you have described. Does anyone have a solution in harmony with RNE?

**Comment by nahuelhds** [comment]
@krean93 I recommend you give the [ListItem API a read](https://react-native-training.github.io/react-native-elements/API/lists/). You have a lot of props to combine in order to make almost every common UI case.
