### ISSUE TITLE
[TS] Text missing RN Text props

### ISSUE THREAD

**Issue by raduflp** [react-native-training/react-native-elements#807]
Text component is missing default RN Text props such as `numberOfLines`

**Comment by iRoachie** [comment]
Fixed in https://github.com/react-native-training/react-native-elements/pull/796/commits/5e9f4b7c63ce670fac2dca386ff3da840effcba5. Should be available in next release

**Comment by xavier-villelegier** [comment]
Available in the `v0.19.0` !
