### ISSUE TITLE
how to overwrite cards 

### ISSUE THREAD

**Issue by omarmok** [react-native-training/react-native-elements#809]
### Description

1. Explain what you did
2. What you expected to happen
3. What actually happens

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by iRoachie** [comment]
Hey @omarmok could you explain what you mean by overwrite?

**Comment by omarmok** [comment]
how can i overwrite css to elements

**Comment by iRoachie** [comment]
The Card component expose several style props that you can use to customize:
* `containerStyle`
* `wrapperStyle`
* `titleStyle`
* `featuredTitleStyle`
* `featuredSubtitleStyle`
* `dividerStyle`
* `imageStyle`
* `imageWrapperStyle`

You can check the other props on the docs site https://react-native-training.github.io/react-native-elements/API/card/

**Comment by omarmok** [comment]
thanks i will try
