### ISSUE TITLE
[TS] wrong type for IconObject.style 

### ISSUE THREAD

**Issue by raduflp** [react-native-training/react-native-elements#811]
currently IconObject type has defined `style?: StyleProp<ViewStyle>;` which is incorrect as it doesn't allow passing text specific styles such as fontSize.
Solution: change it to `style?: StyleProp<TextStyle>;`

**Comment by iRoachie** [comment]
Which line are you referring to?

**Comment by iRoachie** [comment]
You're right actually it's, supposed to be both according to the react-native-vector-icons typescript definitions 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fa5baf1733f49cf26228a4e509914572c1b74adf/types/react-native-vector-icons/Icon.d.ts#L65

**Comment by iRoachie** [comment]
Was fixed in https://github.com/react-native-training/react-native-elements/pull/851 and released in [v1.0.0-beta2](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta2)
