### ISSUE TITLE
Raised styles on Button are applied to wrong View

### ISSUE THREAD

**Issue by hhg2288** [react-native-training/react-native-elements#815]
### Description

1. Explain what you did:
When you have a button `raised` and with some type of spacing styling (margin or padding), the shadow created by the `raised` prop is attached to the wrong view inside the button.

2. What you expected to happen
The border generated from the `raised` prop should be in the "colored" button, not in that View that happens to be the Button Implementation wrapper.

3. What actually happens
example:
```
<Button
            title="button"
            raised
            buttonStyle={{ margin: 16 }}
          />
```
result:
![img_43c046e71b79-1](https://user-images.githubusercontent.com/725120/34900531-27875f82-f801-11e7-92ce-2cf5fbeb3b07.jpeg)

Also please include the version of `react-native-elements` that you are using.
**version: 0.19.0**

### Reproduction Steps and Sample Code

https://snack.expo.io/ryrxN0LVf

### Solution

I know how to fix it but I need some guide dealing with snapshots because the fix actually change the snapshots, so the fix did not pass..

I actually update the snapshot tests in my branch's fork. you can see it here: https://github.com/hhg2288/react-native-elements/commit/c8655012f0b70b3436bd564af0a581cd6c5e0fbf

I test it locally & It works correctly. If soeone can help reviewing this I can create the PR to fix it :)

UPDATE: PR -> https://github.com/react-native-training/react-native-elements/pull/816

**Comment by iRoachie** [comment]
All components in react-native-elements have a container element around them. In your example by adding a margin to the `buttonStyle` prop, you are essentially creating a gap between the container and the element itself. What you probably actually want is the `containerStyle` prop, in which then applying a margin would make more since as it's the container that interacts with other elements.

**Comment by steamedcotton** [comment]
I was having a similar issue and I think the prop name is `containerViewStyle` (not `containerStyle`).  Hope that helps.

**Comment by iRoachie** [comment]
Thanks made the typo update

**Comment by hhg2288** [comment]
@iRoachie oh ok!, so there is no fix then?
I'm assuming that if I'm using a `Button`, to change its styles, I need to add something to the `buttonStyle` prop, not to the `containerViewStyle` prop. In any case, those that shadow still needs to be applied to the container?

just let me know if I need to delete the issue & the PR :)

thanks for the answer :)

**Comment by hhg2288** [comment]
this is my humble opinion...

the fact that all the elements in this library has a container view around them, is an implementation detail. users may or may not need to know or care about it.

I see two solutions here:
1. we specify in de docs that if you want to use some kind of styling for separation (margin, padding or similar) within the `Button` component, you need to add this styles to the `containerViewStyle`
2. we change the `raised` styles to be applied to the actual Button component and not the wrapper.

either way, maybe it's a good Idea to make this clear in the docs. so let me know which one we can agree is the better so I can help with this :)

thanks for your time @iRoachie !

**Comment by hhg2288** [comment]
awesome!!

I just found that problem in my use case & I wanted to help solving it :)

hope we get a good solution I can implement & help with the project :)

**Comment by xavier-villelegier** [comment]
I think moving the raised effect to the `buttonStyle` as you did is fine, unless we can find a use case where we need to put a gap between the raised effect and the button

**Comment by iRoachie** [comment]
Alright then, updated the status to show. Gonna just check with head maintainer on if we're doing the v1 merge before accepting any new fixes

**Comment by hhg2288** [comment]
awesome!
thanks!

**Comment by iRoachie** [comment]
Closing as per https://github.com/react-native-training/react-native-elements/pull/816#issuecomment-359210663. If this is still a problem in v1 then ping me to reopen
