### ISSUE TITLE
Multiple avatars in the same ListItem element

### ISSUE THREAD

**Issue by ilkerceng** [react-native-training/react-native-elements#818]
Is it possible to put multiple avatars on the same ListItem? I also asked [this question](https://stackoverflow.com/questions/48245190/multiple-avatars-in-the-same-listitem-element) on stackoverflow.

**Comment by iRoachie** [comment]
This currently isn’t possible right, sorry there @ilkerceng. We’re revamping the ListItem component for our v1 release that has a much simpler API.

**Comment by xavier-villelegier** [comment]
@ilkerceng We released `v1.0.0-beta4` with a rewritten `ListItem`, you should be able to achieve this. Check out [the docs](https://react-native-training.github.io/react-native-elements/docs/listitem.html) and [the release notes](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta4)

**Comment by ilkerceng** [comment]
@xavier-villelegier thank you so much, thanks for the community :)
