### ISSUE TITLE
Cards not showing completely if used inside ScrollView

### ISSUE THREAD

**Issue by ShaikhKabeer** [react-native-training/react-native-elements#819]
Hello team,
I need multiple cards (approx. 5-6 Cards) in my app, so I added it on View and then applied ScrollView to whole cards. But the last card is not showing its contents completely. what could be the issue ? Please help

**Comment by iRoachie** [comment]
Could you paste your code here or create a snack on https://snack.expo.io?

**Comment by ShaikhKabeer** [comment]
Actually it's part of project so I can't completely expose the code but you just try to do like this.

<View style={{flex:1}}>
<ScrollView>
<Card>
<Text> ABC </Text>
<View style={{alignItems:'center',justifyContent:'center'}}>
...............Some component like table or chart
</View>
<Button />
</Card>

<Card>
<Text> DEF </Text>
<View style={{alignItems:'center',justifyContent:'center'}}>
...............Some component like table or chart
</View>
<Button />
</Card>

<Card>
<Text> GHI</Text>
<View style={{alignItems:'center',justifyContent:'center'}}>
...............Some component like table or chart
</View>
<Button />
</Card>

<Card>
<Text> JKL </Text>
<View style={{alignItems:'center',justifyContent:'center'}}>
...............Some component like table or chart
</View>
<Button />
</Card>

<Card>
<Text> MNO</Text>
<View style={{alignItems:'center',justifyContent:'center'}}>
...............Some component like table or chart
</View>
<Button />
</Card>
</ScrollView>
</View>



Actually it is not showing the last one card completely. It is hiding the button. Please help

**Comment by LouisJS** [comment]
Here is a working example (working with `0.19.0` and `1.0.0-beta`)

https://snack.expo.io/Bkg0-DNwSz

**Comment by Monte9** [comment]
Thanks for putting together a Snack demo @LouisJS! 👍 

Hope this helps you @ShaikhKabeer!
