### ISSUE TITLE
Is is possible to change rightIcon onPress?

### ISSUE THREAD

**Issue by momo1** [react-native-training/react-native-elements#823]
Hi,

I'm still fairly to RN so please let me know if I'm missing something. I have a list of audio files where the rightIcon is set to a 'play' icon. When the user clicks on it (onPressRightIcon) I would like to turn it into a 'stop' icon. It doesn't seem like the FlatList or ListItem re-render on setState (which makes sense I guess). Is there some way to achieve this?

Below is a simplified version of the code. 

```
 <ListItem
                key={file.id}
                title={"some title"}
                rightIcon={this.state.isPlaying ? {name: 'stop', type: 'font-awesome'} : {name: 'play', type: 'font-awesome'}}
                onPressRightIcon={() => {
                     //Toggle playing or stopped state with code that kind of looks like:
                     //setState({isPlaying: !this.state.isPlaying})
                }}
            />
```
Thanks!

**Comment by xavier-villelegier** [comment]
Hey @momo1, to let the FlatList know that it needs to be re-rendered, you have to use the `extraData` props. Try something like

```jsx
<FlatList
  …
  extraData={this.state}
/>
```

**Comment by momo1** [comment]
@xavier-villelegier  Sorry I didn't notice your reply in my email. This worked like a charm. Thank you!!
