### ISSUE TITLE
Need to tap twice to enter input for multiple textfields

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [react-native-training/react-native-elements#829]
I checked this from expo https://expo.io/@monte9/react-native-elements-app

**Comment by iRoachie** [comment]
Can confirm, only happens on first load.

**Comment by iRoachie** [comment]
Hey @SupriyaKalghatgi might be better to track this over on https://github.com/react-native-training/react-native-elements-app/issues/33. Since we split the example and the source into separate repos.
