### ISSUE TITLE
Status bar collides with header

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [react-native-training/react-native-elements#830]
Checked this from expo https://expo.io/@monte9/react-native-elements-app

**Comment by xavier-villelegier** [comment]
Thanks for reporting that @SupriyaKalghatgi ! 👌 This wasn't the case before but we just updated the app with the `v1.0.0-beta`, this introduces some bugs. Feel free to tell us if you find others !

**Comment by k3ithl1m** [comment]
I would like to help out with this issue. But I don't see the bug on my Iphone

**Comment by xavier-villelegier** [comment]
@k3ithl1m This appears only on Android on the `v1.0.0-beta`

**Comment by Monte9** [comment]
Thanks for reporting this issue @SupriyaKalghatgi! 

I have opened this issue on the example repo so it can be fixed on that repo.
