### ISSUE TITLE
Icons not load in offline

### ISSUE THREAD

**Issue by lahiruuk** [react-native-training/react-native-elements#833]
Is there a solution for icons to load in offline mode ?? When I launch app in online mode icons load normally, but I launch it in offline mode only  preloaded icons are showing. 
Is there a way to use expo vector icons with this ??

**Comment by iRoachie** [comment]
This is a limitation in expo itself, it doesn't support bundling of assets. The assets for the app are stored in a cdn, and downloaded to the user's phone on first run. So you need Internet for the first run.

You can read more about it in their [docs](https://docs.expo.io/versions/v24.0.0/introduction/why-not-expo.html#non-image-assets-are-not-bundled-inside-of-standalone-apps-sometimes-you-need-a-specific-asset-like-a-font-or-a-video-to-be-available-immediately-when-the-user-opens-the-app-this-is-supported-for-images-but-for-other-assets-they-will-automatically-load-from-our-cdn-the-first-time-your-app-starts-this-can-be-a-dealbreaker-for-some-projects-in-these-situations-the-only-option-available-to-you-right-now-is-caching-assets-when-your-app-loads-we-are-working-on-making-it-possible-to-bundle-all-assets-with-your-standalone-app).

**Comment by lahiruuk** [comment]
Ah!! ok I understand now, thanks for help (Y) .
