### ISSUE TITLE
Form Input with Icon. No Input Component for 0.19.0 ?

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#840]
### Description

I want to implement a screen similar to the 'Travel Leisure' one in the react native element on Expo (Login Section)

I've noticed in the GitHub repository, they are using the `Input` component which is not available anymore on react-native-elements `"^0.19.0` (?)`

### Reproduction Steps and Sample Code

https://snack.expo.io/B1AwF78HM

### Question

How could i add an icon from "expo/vector-icons" in my FormInput so it can be within the borderBottom line ?

Created an issue on https://stackoverflow.com/questions/48426476/add-an-icon-to-forminput-from-react-native-element

**Comment by xavier-villelegier** [comment]
Hey @LouisJS, this component is a refactored input by @Monte9, available in the `v1.0.0-beta` ! 

You can get it by doing `npm install --save react-native-elements@beta`.

Remember it is the first beta of the `v1.0.0`, so feel free to open an issue if you find something weird. There is no documentation about this new `Input`, you can check out the code to figure out how the API works ✌️

**Comment by LouisJS** [comment]
Thanks. It does work o/
