### ISSUE TITLE
Overlay missing

### ISSUE THREAD

**Issue by hmontes** [react-native-training/react-native-elements#843]
### Version
0.19.0

### Description

Overlay don't work.

### Code and Demo

https://snack.expo.io/HJmRFPvHf

I saw the github code and the component Overlay is in there. But in my node_modules/react-native-elements/src i can't see the "Overlay" component. It's a new feature? Because i can see the api documentation.

Thanks

**Comment by xavier-villelegier** [comment]
Hey @hmontes, the `Overlay` component will be in the `v1.0.0`.
You can now test the `v1.0.0-beta` by running `npm i --save react-native-elements@beta` 👌

**Comment by hmontes** [comment]
No. I can't because i have an issue with Button component (expo is required).

https://github.com/react-native-training/react-native-elements/issues/826

**Comment by iRoachie** [comment]
The issue with button was fixed(temporarily) as as a part of https://github.com/react-native-training/react-native-elements/commit/e0a4b6afda185c215fa9ad9fbfbc7f324c73cbbe#diff-a0a6368880417eca5ad26c484e9ded7aL131. Will be available in next beta release.

**Comment by xavier-villelegier** [comment]
@hmontes `v1.0.0-beta2` was released with a functional `Button` for non-expo users. You should now be able to update to use the `Overlay` component ✌️

**Comment by Punith13** [comment]
I tried to load Overly with beta2, getting an error i.e Check the render method of 'proxiedMethod'

**Comment by Monte9** [comment]
@Punith13 can you share a code snippet that you have? Also can you please try to recreate it with a snack demo? This will help us resolve the problem faster.
