### ISSUE TITLE
Use % in Input and SearchBars width

### ISSUE THREAD

**Issue by xavier-villelegier** [react-native-training/react-native-elements#861]
We should be using percentages in `Input` and `SearchBar`s width to avoid this weird behavior

![simulator screen shot - ipad pro 10 5-inch - 2018-01-28 at 17 56 35](https://user-images.githubusercontent.com/17592779/35487774-a4cdae44-047f-11e8-9b07-aa44e27be7c1.png)

**Comment by iRoachie** [comment]
Fixed in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
