### ISSUE TITLE
[1.0.0-beta] Button icons do not work: Objects are not valid as a React child (found: object with keys {name, type})

### ISSUE THREAD

**Issue by hilalh** [react-native-training/react-native-elements#868]
Hello, I am having a problem with button icons, more specifically:
I have added a button, and later on tried adding an icon to the button as described in the docs
```
        <Button 
        text={'Messenger'}
        icon={{name: 'fa-commenting-o', type: 'font-awesome' }}
        onPress={() => navigate('Messneger')} />
        <Button text='YouTube  📺' onPress={() => navigate('YouTube')} />
```
Unfortunately. the icon doesn't appear and instead I am getting this red screen:
![img_1691](https://user-images.githubusercontent.com/3894104/35528690-5926e95c-0537-11e8-92c3-76e092f4e6c8.PNG)

I am using: CRNA with "react-native-elements": "^1.0.0-beta", and, "@expo/vector-icons": "^6.2.2",

Here's a reproduction of the problem
https://snack.expo.io/H1DKeg6BG

Thanks.

**Comment by xavier-villelegier** [comment]
Hey @hilalh, the `Button` documentation is not updated yet, but will be soon.

You must pass a component to the `icon` props. You can use the `Icon` component from RNE for example, by doing this:

```jsx
<Button 
  text={'Messenger'}
  icon={ <Icon name="fa-commenting-o" type="font-awesome" /> }
  onPress={() => navigate('Messneger')}
/>
```

**Comment by hilalh** [comment]
@xavier-villelegier 
Thanks a lot that worked great!

**Comment by mateen-hussain** [comment]
@xavier-villelegier when is the new documentation about to be uploaded. My button is all messed up and needs styling

**Comment by xavier-villelegier** [comment]
@mateen-hussain We're going to do a doc release for the `Button` and the `Input` components today, I'll let you know

**Comment by iRoachie** [comment]
Docs released https://react-native-training.github.io/react-native-elements/API/buttons/ @mateen-hussain

**Comment by aledalgrande** [comment]
link broken ^^^

**Comment by iRoachie** [comment]
Thanks!
