### ISSUE TITLE
How to extend the size of subtitle

### ISSUE THREAD

**Issue by adriancuco** [react-native-training/react-native-elements#870]
### Description

I'd like to have a subtitle longer. I tried subtitleContainerStyle and containertStyle but no lucky.

I appears that the subtitle goes until the middle of screen, and then jump to another line.

I'd like to have it longer, almost until rightTitle.

I am using List, ListItem,Avatar.
"react-native-elements": "^0.19.0"
"react": "16.0.0",
 "react-native": "0.51.0"

Thanks a lot

PD: BTW, awesome job!!!!

**Comment by xavier-villelegier** [comment]
Hey @adriancuco 
The only way to do this for now is to do [like this snack](https://snack.expo.io/Hy2LFbRrz).

```jsx
<ListItem
  rightTitleContainerStyle={{ flex: 0 }} // Here is the magic
  title="Home is where the heart is. The dogs are going to sleep"
  subtitle="This is a very long subtitle that goes well beyond one line"
  rightTitle="Test"
/>
```

The `ListItem` should be refactored in the `v1.0.0`, it should be the default behaviour 👍

**Comment by adriancuco** [comment]
Hi Xavier,

Thanks a lot. I also realized that if I do not use the rightTitle, subtitle extends til the end. So I can wrap everything into the subtitle instead ;)
Regards

**Comment by samipshah100** [comment]
Hi @xavier-villelegier : thanks, i tried this but i would like to see subtitle be able to go underneath the right title. Is this possible?

**Comment by xavier-villelegier** [comment]
@samipshah100 I don't really see the use case for this but you cant trick by applying a `position: 'absolute'` to one of the two `contentContainerStyle` or `rightContentContainerStyle`.

```jsx
<ListItem
  subtitle="This is a very long subtitle that goes beyond one line hehe"
  contentContainerStyle={{ borderWidth: 1 }}
  rightContentContainerStyle={{ position: 'absolute', right: 16  }}
  rightTitle="Test"
/>
``` 
(The `borderWidth: 1` is just to let you see that the views are overlapping)

![image](https://user-images.githubusercontent.com/17592779/71811910-25ff8b80-3076-11ea-8d00-9235b9b722fc.png)
