### ISSUE TITLE
How to make a button like demo

### ISSUE THREAD

**Issue by Donhv** [react-native-training/react-native-elements#873]
Thanks for Lib!
I want custom button like demo but I can't find example. pls give me code to make button like: 
![screen shot 2018-02-01 at 5 09 56 pm](https://user-images.githubusercontent.com/16864971/35673133-35b0722a-0773-11e8-8fe6-f68e36063f84.png)

**Comment by xavier-villelegier** [comment]
Hey @Donhv ! You need to use the beta version of the`v1.0.0` (currently `beta2`) ✌️

```
npm install --save react-native-elements@beta
```

**On Expo:**
```jsx
<Button
  text="SIGNUP"
  ViewComponent={require('expo').LinearGradient}
  linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: [1, 0],
    end: [0.2, 0],
  }}
/>
```
**On React Native:**
You will need to install [`react-native-linear-gradient`](https://github.com/react-native-community/react-native-linear-gradient) package
```jsx
<Button
  text="SIGNUP"
  ViewComponent={require('react-native-linear-gradient').LinearGradient}
  linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: [1, 0],
    end: [0.2, 0],
  }}
/>
```

Hope this helps

**Comment by Donhv** [comment]
@xavier-villelegier  thanks u <3
but if I want color like : start('red') - mid('pink') - end('red') (start & end same color). how can I make?

**Comment by xavier-villelegier** [comment]
@Donhv Have a look at [this snack](https://snack.expo.io/ryuTb_lUf). You can play with `start`, `end`, and `locations` (Have a look at the LinearGradient documentation for more details)

**Comment by Donhv** [comment]
@xavier-villelegier when i use: `<Button
  text="SIGNUP"
  ViewComponent={require('react-native-linear-gradient').LinearGradient}
  linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: [1, 0],
    end: [0.2, 0],
  }}
/>`
App has crash.
When I change to:  start:1.0,
            end: 0.1
it is result: 
![untitled](https://user-images.githubusercontent.com/16864971/35682474-69e69a9a-0793-11e8-9872-5367cf30c0d5.png)
pls help me a code same demo 100% :(

**Comment by xavier-villelegier** [comment]
@Donhv The example I gave is exactly the one from the example app.

```jsx
<Button
  text="SIGNUP"
  ViewComponent={require('react-native-linear-gradient').LinearGradient}
  linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: [1, 0],
    end: [0.2, 0],
  }}
/>
```

If this doesn't work, you didn't install `react-native-linear-gradient` or forgot to `react-native link`. Please follow [these instructions](https://github.com/react-native-community/react-native-linear-gradient). And if you're using Expo, just use `require('expo').LinearGradient`.

**Comment by montao** [comment]
linearGradientProps crashes my app too...

**Comment by Monte9** [comment]
@montao are you using `expo`? or just `react-native init`? Either way, please follow the exact instructions that @xavier-villelegier posted above. 

https://github.com/react-native-training/react-native-elements/issues/873#issuecomment-362222183

**Comment by xavier-villelegier** [comment]
@Donhv @montao, My bad, my example was not working.

I've changed
```
require('react-native-linear-gradient').LinearGradient
```

into
```
require('react-native-linear-gradient').default
```

I just tested this, and it works fine. Let me know if you have other issues

**Comment by monkeykingblack** [comment]
@xavier-villelegier i got this issue when use 
```js
<Button
  text="SIGNUP"
  ViewComponent={require('react-native-linear-gradient').default}
  linearGradientProps={{
    colors: ['#FF9800', '#F44336'],
    start: [1, 0],
    end: [0.2, 0],
  }}
/>
```
![screenshot_2018-06-08-23-34-17-494_com iotcore](https://user-images.githubusercontent.com/29424003/41169907-9933d9ee-6b74-11e8-9ab1-a899f69b31a6.png)

**Comment by iRoachie** [comment]
@monkeykingblack Make sure you link the package after you install it.

```link
react-native link react-native-linear-gradient

# rebuild the app
react-native run-android
```

**Comment by monkeykingblack** [comment]
@iRoachie  still not working, same error
my package.json

```json
"dependencies": {
    "@babel/core": "^7.0.0-0",
    "babel-core": "^7.0.0-bridge.0",
    "eslint": "^4.0.0",
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.2.0",
    "react-navigation-redux-helpers": "^1.1.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
```
i sure that i install linear gradient correctly, i'm using for background already

**Comment by yeomann** [comment]
Hi the error is existing in Android only. I have test myself as well. on IOS it's working fine but above mentioned error as also provided ins screenshot is caused by ` start: [1, 0],
    end: [0.2, 0],` in linear gradient props. if you removed the starting and ending then error is fixed. I hope that this could help you to fix. please test and try on android. you will see the error yourself.

**Comment by yeomann** [comment]
Alright I believe I have fix for you guys, who ever still struggle with Start and End of gradient specially in android. where there's a error coming in red scree. Here's a fix for you.


Follow this pattern: Object of the following type: `{ x: number, y: number }`. For  Example: { x: 0.1, y: 0.1 } means that the gradient will start 10% from the top and 10% from the left.


```
	<Button
		title="Login"
		titleStyle={{ fontWeight: "700" }}
		icon={{ name: "user", type: "simple-line-icon" }}
		ViewComponent={LinearGradient}
		linearGradientProps={{
			colors: ["#FF9800", "#F44336"],
			start: { x: 5.0, y: 0.25 },
			end: { x: 10.5, y: 1.0 }
		}}
		//start={{x: 0.0, y: 0.25}} end={{x: 0.5, y: 1.0}}
		iconRight
		buttonStyle={buttonStyle}
         />

```
