### ISSUE TITLE
Can FormInput support ClearButton likes Search Bar's clearIcon?

### ISSUE THREAD

**Issue by RoysyLee** [react-native-training/react-native-elements#875]
### Description

1. Explain what you did
- I wanna make a ClearButton in FormInput likes Search Bar's clearIcon

2. What you expected to happen
- clear All Text In FormInput

Is it possible???

Also please include the version of `react-native-elements` that you are using.
 v : 0.19.0

**Comment by xavier-villelegier** [comment]
Hey @RoysyLee, all props you pass to the `Input` of RNE will be spreaded to the `TextInput` of React Native. Therefore, you can use the `clearButtonMode` props, have a look at the [official documentation](https://facebook.github.io/react-native/docs/textinput.html#clearbuttonmode)

**Comment by Kdoherty11** [comment]
@xavier-villelegier I'm also having an issue getting the clear button to show up. If I replace `<FormInput clearButtonMode='always' />` with `<TextInput clearButtonMode='always' />` I see the button. Otherwise, nothing is there. I'm using react-native-elements: 0.19.0 and RN: 0.53.0.

**Comment by xavier-villelegier** [comment]
@Kdoherty11k,

If you're using `v0.19.0`
```jsx
<FormInput clearButtonMode="always" placeholder="Test" inputStyle={{ width: '100%' }} />
```

If you're using `v1.0.0-beta2`
```jsx
<Input clearButtonMode="always" placeholder="Test" />
```

The `Input` was refactored and reworked for the `v1.0.0`, you don't need workaround like setting the `inputStyle` anymore 👍

**Comment by RoysyLee** [comment]
Solved it. Thank you!!
