### ISSUE TITLE
SearchBar missing functions

### ISSUE THREAD

**Issue by jskidd3** [react-native-training/react-native-elements#877]
`SearchBar` is missing methods (such as blur, clearText) in version `v1.0.0-beta2`.

![Screenshot](https://i.imgur.com/mGjQQc9.png)
![Screenshot2](https://i.imgur.com/hFRI7Jq.png)

Is there a way of working around this without having to revert to a previous version?

**Comment by iRoachie** [comment]
This is a bug that we need to fix. The method on the default search bar is `clearText` but on the platform specific ones it’s called `clear`. We should change all to have the same method name.

**Comment by jskidd3** [comment]
We were hoping to push an update to our app tomorrow using the beta version to make use of the new `Overlay` component. Do you have any rough idea of how long it will take for this to be fixed? Will help in any way if I can.

**Comment by iRoachie** [comment]
It probably won't be fixed by tomorrow. All PRs/Issues/Code changes are locked right now in preparation for the `react-native-web` addition, since making changes will create merge conflicts for it.

Right now if your are using `platform="ios"` or`platform="android`, you can use the `clear()` method. If using the default searchbar - `platform="default"` then use `clearText()`

**Comment by hhunaid** [comment]
For now I ended up doing 
```jsx
import AndroidSearchBar from "react-native-elements/src/searchbar/SearchBar-android";
```

This component has all the methods. Hope it points @jskidd3 in the right direction

**Comment by iRoachie** [comment]
@hhunaid That's the same as doing:
```jsx
import { SearchBar } from 'react-native-elements'

///
<SearchBar platform="android" />
```

**Comment by iRoachie** [comment]
You really shouldn't point to direct files in a package. Often they can change while external api remains the same

**Comment by hhunaid** [comment]
Its not the same in this case. SearchBar element doesn't have any functions exposed. And this is a temporary workaround until next beta, which will probably fix this.

**Comment by iRoachie** [comment]
Ah I understand now. Gotcha

**Comment by jskidd3** [comment]
@xavier-villelegier No problem! Thanks for the advice.

**Comment by iRoachie** [comment]
Fixes for this made in https://github.com/react-native-training/react-native-elements/pull/878. I'd leave this open until it's merged in

**Comment by priezz** [comment]
Same problem for `getRef()` function. It is very handy to get the input ref in order to change the text from the outside.

**Comment by iRoachie** [comment]
Live in [1.0.0-beta3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3)
