### ISSUE TITLE
Can not use Overlay

### ISSUE THREAD

**Issue by nandi-krisanu** [react-native-training/react-native-elements#881]
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

1. import { Button, Overlay } from 'react-native-elements'
2. Can use Button but When user Overlay it shows error. 

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by iRoachie** [comment]
What version are you on?

**Comment by benclum11** [comment]
@nandi-krisanu `Overlay` is in 1.0.0-beta so if you're still on the stable release then it's not going to work.

**Comment by nandi-krisanu** [comment]
I am using:
```
react-native-cli: 2.0
react-native: 0.51.0
```

**Comment by nandi-krisanu** [comment]
Also , react native elements version shows in package.json as

`    "react-native-elements": "^0.19.0"`

**Comment by iRoachie** [comment]
As @benclum11 said, the `Overlay` component is only available in the beta version so you won't be able to use it in `0.19.0`. To be able to use the `Overlay`, install the beta instead.

**npm**
`npm install --save react-native-elements@beta`

**yarn**
`yarn add react-native-elements@beta`

**Comment by xavier-villelegier** [comment]
Closing this as inactive, ping us if you still need help on that

**Comment by SirPhemmiey** [comment]
Hello guys..i am using the beta version @iRoachie suggested but the overlay isn't visible..I can't see it on myt screen. It's showing as a normal button

**Comment by joshconnell4** [comment]
they didn't specify importing options in the docs. import {Overlay} from 'react-native-elements.

**Comment by iRoachie** [comment]
Sorry about that @joshconnell4, do you mind making that small fix to the docs?

**Comment by TheGreatAndrew** [comment]
Is August already? Have anything improved? Cause I still can not use it now.

**Comment by xavier-villelegier** [comment]
@TheGreatAndrew Yes you can use it with `v1.0.0-beta5`. [Here is](https://snack.expo.io/Bkw1kOtB7) an example
