### ISSUE TITLE
create-react-app/react-native-web errors.

### ISSUE THREAD

**Issue by mini-eggs** [react-native-training/react-native-elements#882]
This is a precursor to a PR I'm planning to submit.

### Description

1. Explain what you did

Started a project with create-react-app. Installed react-native-web and react-native-elements.

2. What you expected to happen

To be able to use components within react-native-elements the same as I would within a project started with Expo.

3. What actually happens

I'm presented with a couple errors. Here's the first one:

```bash
Uncaught Error: Module parse failed: Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
|     textEllipsizeMode,
|     allowFontScaling,
|     ...attributes
|   } = props;
```

Here's a photo:

![Image of issue.](https://i.imgur.com/7h6R5sl.png)

After fixing this error there was a couple more I encountered, like the imports of react-native-vector-icons (imports es6 files). All Webpack related things. There is also an issue with building this library on Debian Testing due to the image-webpack-loader native dependencies.

Also please include the version of `react-native-elements` that you are using.

0.19.0

Another note: I linked the project locally, built, then attempted to import the file this libraries Webpack puts out, react-native-elements/build/bundle. There was different issues there.

### Reproduction Steps and Sample Code

```bash
creater-react-app tester && \
cd tester && \
npm install --save react-native-elements react-native-web react-native-vector-icons
```

Modify src/index.js

```javascript
import React from "react";
import ReactDOM from "react-dom";
import { Header } from "react-native-elements";

const App = () => (
  <Header
    leftComponent={{ icon: "menu", color: "#fff" }}
    centerComponent={{ text: "MY TITLE", style: { color: "#fff" } }}
    rightComponent={{ icon: "home", color: "#fff" }}
  />
);

ReactDOM.render(<App />, document.getElementById("root"));
```

```bash
npm start
```

### Solution

Modifying the build script, cleaning up some react-native-vector-icons imports, removing a dev dependency.

**Comment by iRoachie** [comment]
Did you look at the PR we already have open for react-native-web support? https://github.com/react-native-training/react-native-elements/pull/867.

**Comment by mini-eggs** [comment]
@iRoachie oh wow! Missed, never mind closing this.

**Comment by feezo** [comment]
### create-react-app/react-native-elements error
Started a project with create-react-app. 
Installed react-native: "^0.57.8",
react-native-elements: "^0.19.1" and react-native-vector-icons: "^6.1.0".
In order to be able to use components within react-native-elements in my google map API project.
When I run `npm start` in my project directory I get the error code pasted below. I've read through the the react-native-elements documentation but can't seem to find anything to help me resolve this issue

```./node_modules/react-native-elements/src/avatar/Avatar.js
 SyntaxError: D:\Location-Map\Neighborhood-Map-2-\location- 
 app\node_modules\react-native-elements\src\avatar\Avatar.js: Unexpected 
 token (92:8)

  90 | 
  91 |       return (
> 92 |         <TouchableHighlight
     |         ^
  93 |           style={[
  94 |             styles.editButton,
  95 |             editButtonSizeStyle,```

**Comment by Monte9** [comment]
@feezo I would recommend using the latest beta as some folks have reported that they are succesfully able to use RNE + RNW.

You can install it using `yarn add react-native-elements@beta`

**Comment by fBruzja** [comment]
@Monte9 Having the same problem, i applied your suggestion but it still gives the same error.

**Comment by fungilation** [comment]
I'm hitting the exact same error, while following https://react-native-training.github.io/react-native-elements/blog/2018/12/13/react-native-web.html. Using latest RNE@1.1.0

**Comment by aravind1078** [comment]
iam getting the same error as @feezo

**Comment by ArThoX** [comment]
iam also getting the same error as @feezo

**Comment by Monte9** [comment]
We are working on updating the docs & that blog post. For now, the solution should be in this issue. Please read through it thoroughly and let us know if you get stuck.

**Comment by bj97301** [comment]
@Monte9 getting the same error in v1.

**Comment by bj97301** [comment]
Has anyone been able to get v1.1.0 to work without strange hacks?

**Comment by maqui7295** [comment]
still having same issue on v1

**Comment by isabelbicalho** [comment]
I'm having this error too

**Comment by ngduc** [comment]
me too, I'm having the same issue with the latest version 1.2.0, beta didn't work also.

**Comment by iRoachie** [comment]
Consider checking the new guide in the docs https://react-native-training.github.io/react-native-elements/docs/web_usage.html
