### ISSUE TITLE
How to put Top Icon in Button

### ISSUE THREAD

**Issue by ranvirgorai** [react-native-training/react-native-elements#883]
### Description

1. Explain what you did
   Trying to use button where icon on top then, label should be on bottom used \n on label
2. What you expected to happen
    label test should be on the bottom
3. What actually happens
    but it is not coming on center

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by xavier-villelegier** [comment]
@ranvirgorai Is [this](https://snack.expo.io/rycjAkvUf) what you're trying to do ?

**Comment by api182** [comment]
@xavier-villelegier 

I too am after this, I've checked your snack example out but I see that the icon is small and slightly off-center to the left?

Is there the ability to add icon styling like being able to specify the size of the icon and setting margin around it etc..?

Then for some reason when using it in my app, the icon doesn't show..?

`import { Icon, Button } from 'react-native-elements';

<Button
                        large
                        icon={<Icon
                            name='list-ul'
                            type='font-awesome' />}
                        title="Timeline"
                        backgroundColor="#5e35b1"
                        containerViewStyle={{ width: 100 }}
                        buttonStyle={{ flexDirection: 'column' }}
                    />`

**Comment by xavier-villelegier** [comment]
@api182 My snack is using the new `Button` component from RNE `1.0.0-beta`. You can get it by doing
```
npm install --save react-native-elements@beta
```

The icon shouldn't be off-centered with this one.

**Comment by xavier-villelegier** [comment]
Closing this as inactive, ping us if you still need help on that 👍
