### ISSUE TITLE
BorderRadius is not working on Image of the Card

### ISSUE THREAD

**Issue by alvarogonjim** [react-native-training/react-native-elements#884]
### Description

I create a Card with a Image. I wanted to apply a borderRadius in the image (the image will be cropped with that borderRadius). The border is applied (you can see it with the color) but the image is not cropped as you can see in this picture. I tried to change the resizeMode and include the Card component inside of a View component with the BorderRadius also, but it doesn't work.

![screenshot_20180206-173946-01](https://user-images.githubusercontent.com/25668523/35871689-2aa778a6-0b65-11e8-9ecf-126b5180a6ba.jpeg)

"react": "16.2.0",
"react-native": "0.52.0",
"react-native-elements": "^0.19.0",

### Reproduction Steps and Sample Code
` <Card
      containerStyle = {{borderRadius: 10}}
      imageStyle	= {{
        borderWidth: 1,
        // Set border Hex Color Code Here.
        borderColor: '#F44336',
        // Set border Radius.
        borderRadius: 10
        }}
            image = {{uri: item.image}}>
            <Text style={{marginBottom: 10}}>
            {item.title}
            </Text>
      </Card>`

**Comment by xavier-villelegier** [comment]
Hey @alvarogonjim 🤙
The radius on a `Image` is always a bit tricky, there are a lot of issues about that on React Native. The best thing you can do is using `overflow: hidden` to hide the corners of the `Image` behind the radius of the container. Have a look at [this example](https://snack.expo.io/rJX-kHdIz)

**Comment by alvarogonjim** [comment]
Xavier you are a Pro!! it works perfectly. Thanks for your help.

**Comment by haripermadi** [comment]
Thank you Xavier, Its work

**Comment by mayconmesquita** [comment]
Congratz, Xavier! :+1:

**Comment by ugglr** [comment]
This helped me to solve the same problem! Thanks! 😊
