### ISSUE TITLE
Buttons don't show the given title

### ISSUE THREAD

**Issue by Jokerchris2000** [react-native-training/react-native-elements#887]
### Description

1. Explain what you did
Updated from RNE from to 1.0.0beta 2 to get the Overlay support but that broke my Button implementation. 

2. What you expected to happen
Work as expected and show the given title like in the last stable version

3. What actually happens
Buttons now only show "Welcome to React Native Elements" as the title and don't use the specified title. Behavior can be seen in this snack: https://snack.expo.io/rycjAkvUf

Also please include the version of `react-native-elements` that you are using.
1.0.0beta2

**Comment by iRoachie** [comment]
Hey! The `title` prop is now called `text`. Sorry about the confusion, we should be updating the docs later today

**Comment by iRoachie** [comment]
Docs updated! https://react-native-training.github.io/react-native-elements/API/buttons/

**Comment by Jokerchris2000** [comment]
Thank you for the quick response and the solution for the issue!
