### ISSUE TITLE
Allow custom icon as react component for Checkbox

### ISSUE THREAD

**Issue by ginsev** [react-native-training/react-native-elements#888]
### Description
Cannot use custom icon component into Checkbox component

**Comment by iRoachie** [comment]
What would be an example of a custom icon component?

**Comment by k3ithl1m** [comment]
Would it be something like replacing the checkbox with something like [this](https://www.flaticon.com/free-icon/success_149148#term=checkbox&page=1&position=3)

**Comment by iRoachie** [comment]
That’s an image. The checkbox uses react-native-vector-icons under the hood to provide the icon using the icon fonts from that package.

You can already customize it by passing in `checkedIcon` and `uncheckedIcon` props

**Comment by ginsev** [comment]
For `checkedIcon` and `uncheckedIcon` I would want to pass not just string but React Native Component.

**Comment by iRoachie** [comment]
Ah I understand now. That makes sense. Alright, sounds like a good feature to have.

**Comment by xavier-villelegier** [comment]
@ginsev We released `v1.0.0-beta4` today, and you should be able to use a custom component now ! Have a look at [the docs](https://react-native-training.github.io/react-native-elements/docs/checkbox.html)

**Comment by bubumaci** [comment]
Hi! I think the closing } tags might be missing here at both of the image sources. 
`source={require('../checked.png')**}** ` 

`<CheckBox
  checkedIcon={<Image source={require('../checked.png') />}
  uncheckedIcon={<Image source={require('../unchecked.png') />}
  checked={this.state.checked}
  onPress={() => this.setState({checked: !this.state.checked})}
/>`

**Comment by iRoachie** [comment]
Thanks @bubumaci for pointing that out. Would you willing to make a PR that fixes it?

**Comment by grofis** [comment]
After i added the closing } tags，like this:
`<CheckBox
                    checkedIcon={<Image source={ require('../../images/box_checked.png') } />}
                    uncheckedIcon={<Image source={require('../../images/box_unchecked.png')} />}
                    checked={this.state.checked}
                    onPress={() => this.setState({checked: !this.state.checked})}
                />`
It doesn't show check image, errors too.

**Comment by trancanh2202** [comment]
I added the closing tag => No thing to show. Someone can fix it.
![screen shot 2018-10-17 at 11 41 23 am](https://user-images.githubusercontent.com/42834870/47062722-d7ac6580-d201-11e8-87d6-f4654d79a4a5.png)

**Comment by iRoachie** [comment]
@trancanh2202 please create a new issue and fill out this issue template
