### ISSUE TITLE
[1.0.0-beta2] Input with Icon

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#889]
### Description

I'd like to implement an Input with an Icon.
https://snack.expo.io/SynHZsKUz

### Issue

No Icon is shown. Seems like it was working in `1.0.0-beta`
A complete review of the Input feature would be useful.

**Comment by xavier-villelegier** [comment]
Hey @LouisJS, in the `beta2` we introduced `leftIcon` and `rightIcon`.

```jsx
<Input
  leftIcon={
    <Icon
      type="feather"
      name="activity"
    />
  }
/>
```

**Comment by LouisJS** [comment]
Alright ! Thanks.
Although i don't know how i would've been able to find this informations by myself as it isn't mentioned in the actual docs or in the native-elements-app on Expo.

Problem solved !

**Comment by xavier-villelegier** [comment]
It is specified in the docs [here](https://react-native-training.github.io/react-native-elements/API/input/#input-props) 👍  We did a doc release yesterday but we forgot to update the examples (cc @iRoachie). It is still a beta, the documentation should be much more better for the official release, hope you understand !

**Comment by LouisJS** [comment]
Ok ! Great ! Happy that this issue was a little helpful then 😄

Also, something i've noticed by using the library.
Most of the time, components comes with default styling, and i've found no other solution than going into the code to see what those default styling are.

In your opinion, do you think that would be possible to explicit them in the doc in an elegant way ?

**Comment by xavier-villelegier** [comment]
Yea I agree that for now, the only way to fully understand the components is to check the code. On one hand, it is always good to check how the components you use work. But on the other hand, a library like RNE should be more explicit and more plug&play.

There is still a lot of work on the documentation, we're currently discussing about this and we're open to any suggestion.

The styling should be more simple in later betas of the v1 though, as we planned to introduced a theming feature 🎉
