### ISSUE TITLE
 Unable to resolve module `expo` from `D:\Project\IOtunes\node_modules\@expo\vector-icons`

### ISSUE THREAD

**Issue by RijaAdrian** [react-native-training/react-native-elements#890]
Someone could explain why does react-natives elements require to have expo/vector-icons in the modules map ?
I build my react application with react-native cli, so I didnt expect this issues.

Even installing it I find an error asking to install expo, which is not good because I do not use the software expo

It's been a week since I was stuck on it without really knowing why this error persists.

Thanks

**Comment by iRoachie** [comment]
What version of react-native-elements are you using?

**Comment by RijaAdrian** [comment]
Hi here is my dependencies: 
![issues](https://user-images.githubusercontent.com/17961600/35969851-45e52b7a-0cd9-11e8-8427-5493363baba3.PNG)

**Comment by xavier-villelegier** [comment]
@RijaAdrian Have a look at [this comment](https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210)

**Comment by RijaAdrian** [comment]
Yes but got the same issues :(

**Comment by RijaAdrian** [comment]
![expo](https://user-images.githubusercontent.com/17961600/36019301-defaef78-0d8f-11e8-809b-dc3e83b1d0b1.PNG)

**Comment by xavier-villelegier** [comment]
Closing this as inactive, @RijaAdrian if you managed to make this work feel free to post the solution here 💯

**Comment by JosielFaleiros** [comment]
I am facing the same issue :/

**Comment by stefanilie** [comment]
This is happening to me too after ```npm run eject```
