### ISSUE TITLE
Add a `label` feature to the v1 `Input`

### ISSUE THREAD

**Issue by mateen-hussain** [react-native-training/react-native-elements#892]
### Description
I'm playing with FormLabel and FormINput and this is what I have:
```
import React from 'react';
import PropTypes from 'prop-types';
import { View, Text } from 'react-native';
import { FormLabel, FormInput, FormValidationMessage } from 'react-native-elements';

const DetailsScreen = () => (
  <View>
      <FormLabel>Name</FormLabel>
      <FormInput
        placeholder = 'AB12DEF'
      />
      <FormValidationMessage>Error message</FormValidationMessage>
  </View>
);
export default DetailsScreen;
```
The above code renders to below error
<img width="276" alt="screen shot 2018-02-08 at 17 34 37" src="https://user-images.githubusercontent.com/26531653/35988500-7170854c-0cf6-11e8-9108-3b5888cd4a0d.png">

When I replace FormLabel, FormInput and replace with <Text> then I see the text message. 

My package.json

```
    "expo": "25.0.0",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-elements": "1.0.0-beta2",
```

**Comment by kristofferkarlsson93** [comment]
I have the same issue

**Comment by xavier-villelegier** [comment]
`FormInput` was replaced by the new refactored `Input` by @Monte9, and `FormLabel` was removed since the `v1.0.0-beta1`, as it is basically just a text with a styling. We're trying to focus on a modular `Input` than multiple form components, but we're open to suggestion about that 👍

**Comment by iRoachie** [comment]
This is actually a great idea. This is how I make my custom inputs for react on the web. Would definitely appreciate I you could make a PR for this.

**Comment by api182** [comment]
I'm getting this error when trying to use 'Input' also though..?

**Comment by xavier-villelegier** [comment]
@api182 If you use `v1.0.0-beta2` this shouldn't be an issue
```jsx
import { Input } from 'react-native-elements'

…
render() {
  return <Input placeholder="Test…" />
}
```

Check your `package.json` to know which version you're using

**Comment by jacklinton** [comment]
Input is not on the list of exports.
`// UI references
// https://ionicframework.com/docs/components/#buttons
// https://material.io/guidelines/components/buttons.html#buttons-raised-buttons
// https://material.angularjs.org/latest/demo/button

// Core
import Button from './buttons/Button';
import Input from './input/Input';

import Icon from './icons/Icon';
import List from './list/List';
import ListItem from './list/ListItem';
import SocialIcon from './social/SocialIcon';
import Overlay from './overlay/Overlay';

// Utilities
import SearchBar from './searchbar/SearchBar';
import Badge from './badge/badge';
import CheckBox from './checkbox/CheckBox';
import Divider from './divider/Divider';
import Slider from './slider/Slider';
import ButtonGroup from './buttons/ButtonGroup';

// Productivity
import Card from './card/Card';
import Tile from './tile/Tile';
import Avatar from './avatar/Avatar';
import Rating from './rating/Rating';
import Header from './header/Header';
import PricingCard from './pricing/PricingCard';

// helpers
import Text from './text/Text';
import colors from './config/colors';
import getIconType, { registerCustomIconType } from './helpers/getIconType';
import normalize from './helpers/normalizeText';

export {
  Badge,
  Button,
  ButtonGroup,
  Card,
  Input,
  List,
  ListItem,
  PricingCard,
  SocialIcon,
  Text,
  Divider,
  CheckBox,
  SearchBar,
  Icon,
  colors,
  getIconType,
  registerCustomIconType,
  normalize,
  Tile,
  Slider,
  Avatar,
  Rating,
  Header,
  Overlay,
};
`

**Comment by prashant3g** [comment]
@xavier-villelegier I've tried reinstalling 1.0.0-beta2 version multiple times but still `<Input>` is not showing as component while `<FormLabel> <FornInput>` are still showing as component even after it's removal from newest version 1.0.0-beta2.

**Comment by xavier-villelegier** [comment]
@prashant3g Maybe you have a package-lock that installs automatically the `v0.19.0`. Check that you have `1.0.0-beta2` in your package.json. If it is the case, try this:

```
rm -rf node_modules yarn.lock package-lock.json && npm i
```

**Comment by prashant3g** [comment]
@xavier-villelegier Newest version is installed and also tried `rm -rf node_modules yarn.lock package-lock.json && npm i`. It is listed in package.json `"react-native-elements": "^1.0.0-beta2"`.
Still facing same issue.

**Comment by xavier-villelegier** [comment]
If you have `FormLabel` and `FormInput`, and not `Input`, you don't have the version `1.0.0-beta2` installed. If you check your `node_modules/react-native-elements/package.json` which version do you have ?

**Comment by xavier-villelegier** [comment]
@prashant3g It turns a bit off topic, join us on Slack we'll help you, and post the final answer here

**Comment by Monte9** [comment]
@prashant3g @xavier-villelegier @kristofferkarlsson93 @mateen-hussain Sorry for all the confusion guys. 

I am the one that worked on the new `<Input />` component and I realize that I should have ported over the `FormLabel` feature as well. And that's def caused a lot of inconvenience to users.

I will be submitted a PR adding the `InputLabel` (aka `FormLabel`) to the next release. I'll also put together a nice little snack to show how to put them all together for your app. Stay tuned.

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/4c99586c749623716ed4c8e9dbbb8910932a8949, will be a part of the `1.0.0-beta4` release

**Comment by xavier-villelegier** [comment]
@mateen-hussain @kristofferkarlsson93 @api182 @prashant3g 
We release `v1.0.0-beta4` today, you should be able to use the `label` props on the `Input` component now 🚀  Check out [the docs](https://react-native-training.github.io/react-native-elements/docs/input.html#label)
