### ISSUE TITLE
Re-add `disabled` and `disabledStyle` for Button

### ISSUE THREAD

**Issue by Jonovono** [react-native-training/react-native-elements#893]
I noticed awhile back there was a PR to give functionality to the Button to disable them and pass in the disabled style. Looking in `src/buttons/Button.js` it seems that it's not there anymore. Am I crazy?!

**Comment by xavier-villelegier** [comment]
@Jonovono Haha you're not crazy, the code you saw is the refactored `Button` from `v1.0.0-beta2`. The one you're looking for is still available in `v0.19.0`

**Comment by iRoachie** [comment]
We really should add this back in.

**Comment by k3ithl1m** [comment]
Can I take on this issue?

**Comment by iRoachie** [comment]
Sure thing! Be sure to check how it was done previously.

These things should happen:
* User should be able to set a button as disabled 
* User should be able to customize how the button looks when disabled 
* No events should be able to be fired on a disabled button

**Comment by k3ithl1m** [comment]
alright! If you dont mind, give me a few days to work on this. 
Should i approach this by downloading the module for v0.19.0, and then look at the code and implement it to the newest one?

**Comment by iRoachie** [comment]
Sure thing, here's the link to the file on v0.19.0 https://github.com/react-native-training/react-native-elements/blob/v0.19.0/src/buttons/Button.js

**Comment by iRoachie** [comment]
Live in [1.0.0-beta3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3).
