### ISSUE TITLE
RTL languages

### ISSUE THREAD

**Issue by Mehran-Abghari** [react-native-training/react-native-elements#894]
Hello, first i should thank you to creating this great library.

I'm developing an multi language application with react native, I'm using FormInput from react-native-elements.

ReactNative version -> "react-native-elements": "^0.19.0"
ReactNativeElements version -> "react": "16.2.0", "react-native": "0.52.2",
LocaleHelper -> "react-native-i18n": "^2.0.12"
FormContoller -> "foect": "^0.1.5"

I have a login form that get Phone Number and Password from user, It works very good in LTR languages like English, But when i set language to a RTL language like Persian (فارسی) it not work correctly!

In RTL languages, user input not show in frame. Please view this videos to understand:

![FormInput in LTR language](https://user-images.githubusercontent.com/30838541/36027031-ce84d0e0-0dae-11e8-8c8f-adde66d56375.gif)
![FormInput in RTL language](https://user-images.githubusercontent.com/30838541/36027032-ceb7ec5a-0dae-11e8-8e7e-01808d3fee29.gif)

See in imagur:
https://imgur.com/wo6RFU8
https://imgur.com/aaN4qei

Sorry for my bad English

**Comment by xavier-villelegier** [comment]
Hey @Mehran-Abghari 👋

What if you add `inputStyle={{ width: '100%' }}` ?

**Comment by Mehran-Abghari** [comment]
Thank you very much @xavier-villelegier 

`inputStyle={{ width: '100%' }}` solve the problem.

**Comment by akhatriST** [comment]
@mehranabi How did you manage to change the Input's **label** and **placeholder** to show up on the right side in Arabic? 

I am unable to achieve this, can you please share the code. 

Thanks in advance.

**Comment by mehranabi** [comment]
Hello @akhatriST ,
Actually I cannot remember what project was it, to give you the code. but it's simple.

*** Changing the phone language to a RTL language (like Farsi or Arabic), will cause elements direction to be RTL.
*** Also, you can force your react native application direction to be RTL, by "I18Manager" from `react-native` package.
Checkout this link:
- https://stackoverflow.com/questions/59071472/how-to-force-react-native-app-to-be-just-rtl

**Comment by akhatriST** [comment]
@mehranabi Thank you for the response. I am using the below code to force RTL. 
`I18nManager.forceRTL(isRTL);

 RNRestart.Restart();`

My question was specific to react-native-elements **Input** component, I am using it to take input from the user. Upon forcing the rtl it still shows the _label_ and _placeholder_ on the left hand side. 

Attaching a screenshot for the reference

![Screen Shot 2020-09-11 at 12 22 38 PM](https://user-images.githubusercontent.com/6303511/92882630-83c84c80-f429-11ea-91b0-ad1a653a5222.png)
