### ISSUE TITLE
Dynamically modify the Slider value

### ISSUE THREAD

**Issue by Lawris** [react-native-training/react-native-elements#897]
### Description

1. Explain what you did : Tried to update the Slider value.
2. What you expected to happen : Expected the Slider thumb to move accordingly.
3. What actually happens : The slider thumb does not move since the `value` property is just the initial value of the Slider.

Version :  `react-native-elements@0.19.0` 

### Reproduction Steps and Sample Code

The app I am creating is websocket based, so when a value is modified on a client, it is broadcasted on every other client.

Here is a sample code
```
<View style={{marginTop:20}}>

     <Slider
        ref="container"
        minimumValue={0}
        maximumValue={100}
        value={this.state.briValue}
        onValueChange={val => {
             this.setState({ briValue: val })
             socketEmit('hue-bri', val)
         }
     }
     />

    <Text>Brightness : {this.state.briValue} %</Text>
</View>
```

![ezgif-3-1e9ef47082](https://user-images.githubusercontent.com/15719068/36063535-68818cb8-0e7e-11e8-9d8e-6acc2aaa2c7f.gif)

Every-time I receive data, I change the `value` property with : `this.setState({briValue: latestData}); `

As you can see, the Text component is live modified but the Slider is not.

### Solution

I didn't find anything that might solve my issue on this repo.
I would suggest to add a prop or modify the existing `value` prop to make it dynamic, allowing live modifications.

**Comment by xavier-villelegier** [comment]
Hey @Lawris !
The `value` props of the `Slider` hasn't anything special for preventing it to be updated if this changes. I made a [snack example](https://snack.expo.io/HkmfGc3UG) with two sliders using the same state, and you can see that they are both synchronised 🤔

**Comment by Lawris** [comment]
Hello @xavier-villelegier !

Removing the Throttle component above the Slider did the trick :
`<Throttle time="100" handler="onValueChange">`

But I don't know why it would stop the Slider from getting updated...

However, Thanks for your precious help ! 
Greetings from Corsica 😃

**Comment by xavier-villelegier** [comment]
Oh okay nice ! I didn't know that a `Throttle` component exists haha, that's cool !
Greetings from Paris 👋🇫🇷
