### ISSUE TITLE
Button won't display embedded Icon

### ISSUE THREAD

**Issue by pstanton** [react-native-training/react-native-elements#898]
### Description

1. Explain what you did

I'm trying to embed an Icon within a Button as per the documentation
```
<View style={{flexDirection:"row"}}>
	<Button icon={<Icon name="home" />} />
	<Icon name="home" />
</View>
```
2. What you expected to happen
I'm trying to make a button with an embedded icon, I'm putting an Icon next to it to prove the Icon works stand-alone.
 [(Home)] (Home)
3. What actually happens
The button displays as a blank grey box (no icon)
[grey-bg] (Home)

Also please include the version of `react-native-elements` that you are using.
```
		"react": "16.2.0",
		"react-native": "0.53.0",
		"react-native-elements": "^0.19.0",
		"react-native-gesture-handler": "^1.0.0-alpha.40",
		"react-native-vector-icons": "^4.5.0"
```

### Reproduction Steps and Sample Code

```
import React, { Component } from "react";
import { View } from "react-native";
import { Button, Icon } from "react-native-elements";

export default class App extends Component {
	render() {
		return (
			<View style={{ flexDirection: "row" }}>
				<Button icon={<Icon name="home" />} />
				<Icon name="home" />
			</View>
		);
	}
}
```

Testing on Samsung galaxy S6 using adroid 7.0.
For some reason snack/appetize won't load for me so didn't test there.

**Comment by bkazula** [comment]
I've just encountered the same problem. Use object in `icon` prop, eg. 
```
<Button icon={{ name: 'home' }} />
```

**Comment by LouisJS** [comment]
Coud you provide a snack example ? (https://snack.expo.io/)

**Comment by pstanton** [comment]
sorry Louis, no time, the workaround works and snack is not my target environment.

**Comment by xavier-villelegier** [comment]
Hey @pstanton @bkazula, the documentation is for **the v1.0.0-beta2**.

Please check your RNE version, and according to your version, use:

**>= v1.0.0-beta**
```jsx
<Button icon={<Icon name="home" />} />
```

**<= v0.19.0**
```jsx
<Button icon={{ name: 'home' }} />
```

**Comment by pstanton** [comment]
wow, that's misleading! thanks.

**Comment by pstanton** [comment]
where's the doc for the latest release version?

**Comment by iRoachie** [comment]
Here! https://react-native-training.github.io/react-native-elements/API/buttons/#button-props

**Comment by xavier-villelegier** [comment]
Yea I agree. The doc for the last release is [here](https://react-native-training.github.io/react-native-elements/) as you saw it, but the only way to check for old documentation is to check the `docs` directory of the `v0.19.0` release, you can find it [here](https://github.com/react-native-training/react-native-elements/tree/v0.19.0/docs)

**Comment by pstanton** [comment]
but that is a beta release, ie not the latest "stable" release. I was assuming the official doc would be for the latest stable release.

either my assumption is misguided (i thought not) or its misleading to make the official documentation for a non-stable release... ? 

not my problem - now I understand, but will it confuse more people?

**Comment by xavier-villelegier** [comment]
@pstanton Yep, this is true. You're not the first one to say that. @iRoachie is currently looking for a new documentation system (like docusarus) that would allow us to have versioned documentation. Thanks for your feedbacks ! 👍

**Comment by mg4u** [comment]
@bkazula which font library icon object uses, font awesome or what?
`iconRight` not working, does anyone have a solution for that?

**Comment by iRoachie** [comment]
Hey @mg4u can you make a new issue? Be sure to list your version of react-native-elements
