### ISSUE TITLE
Button won't show text

### ISSUE THREAD

**Issue by JuarezLopesJr** [react-native-training/react-native-elements#899]
### Description

1. Explain what you did
I'm trying to put a simple label in the button using text prop
2. What you expected to happen
The button name appear in the button
3. What actually happens
it renders only the blank rounded button
Also please include the version of `react-native-elements` that you are using.
"expo": "^25.0.0",
    "firebase": "^4.9.1",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-elements": "^0.19.0"

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.
https://snack.expo.io/@juarezlopes/unnamed-snack

**Comment by LouisJS** [comment]
Use `title` instead of `text`.
The actual documentation for `Button` component is accurate for the version `1.0.0-betaX`

**Comment by JuarezLopesJr** [comment]
@LouisJS Thank you! It worked perfectly

**Comment by Rah1x** [comment]
Cant believe it its not documented!! what a waste of an hour figuring out this.
