### ISSUE TITLE
icon in button is not centered

### ISSUE THREAD

**Issue by pstanton** [react-native-training/react-native-elements#901]
v0.19.0

**1. Explain what you did**

```
<Button icon={{ name: "home" }} buttonStyle={{ width: 50 }} />
<Button icon={{ name: "home" }} containerViewStyle={{ width: 50 }} />
```

**2. What you expected to happen**

According to the docs, without text the button should display centered.

https://github.com/react-native-training/react-native-elements/blob/v0.19.0/docs/API/buttons.md

"leftIcon or icon"
"displays a centered icon (when no text) or to the left (with text). (can be used along with rightIcon as well)"

**3. What actually happens**

The button is shifted left of center.

**Comment by iRoachie** [comment]
Hey there!

When the `icon` prop is passed in, it's automatically set to `leftIcon` as you can see [here](https://github.com/react-native-training/react-native-elements/blob/v0.19.0/src/buttons/Button.js#L64-L65).

The icon has a default style of `{{ marginRight: 10 }}` defined [here](https://github.com/react-native-training/react-native-elements/blob/v0.19.0/src/buttons/Button.js#L285).

However that default style is overrided by the `style` prop on the icon object we pass in [here](https://github.com/react-native-training/react-native-elements/blob/v0.19.0/src/buttons/Button.js#L81).

Which means we can override it like this!
```js
<Button icon={{ name: "home",  style: { marginRight: 0 } }} buttonStyle={{ width: 50 }} />
```

*Takes breath*:
This will be alot easier to do in future versions, actually the Button component was completely rewritten in the [beta](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta2). Try it out when you get a chance.

**Comment by xavier-villelegier** [comment]
Closing this as it seems to be resolved (thanks @iRoachie)
Feel free to try the new `Button` in the beta

**Comment by mhsekhavat** [comment]
@xavier-villelegier it seems `padding` of `<Text/>` component for the title is also another cause of this issue as I checked in beta. I just submitted a pull request to fix it.

**Comment by methodbox** [comment]
This appears to be yet another issue that was "fixed" that isn't fixed. This is my first experience with the library and so far it seems many fundamental elements are missing or broken.

I'm trying to make a round button with an icon.

You have round icons, which apparently can be made into buttons (that's not confusing) but adding an icon to a button results in the icon being, seemingly permanently so, stuck on the left side.

There's nothing in the docs to indicate how to make a round icon, so it's unclear what exactly can be done with props to do this, though there's about 15 examples at the top of the page.

You might have fewer github issues if your docs were more complete.
