### ISSUE TITLE
Searchbar, cannot find folder

### ISSUE THREAD

**Issue by adriancuco** [react-native-training/react-native-elements#904]
Hi,

Where's searchbar folder?

Thx

**Comment by xavier-villelegier** [comment]
@adriancuco In `src/searchbar` -> [here](https://github.com/react-native-training/react-native-elements/tree/master/src/searchbar)

**Comment by adriancuco** [comment]
Not in my install folder. ;(
At least weird!!!

Sent from my iPhone

On 13 Feb 2018, at 16:33, Xavier Villelégier <notifications@github.com<mailto:notifications@github.com>> wrote:


@adriancuco<https://github.com/adriancuco> In src/searchbar -> here<https://github.com/react-native-training/react-native-elements/tree/master/src/searchbar>

**Comment by xavier-villelegier** [comment]
This was introduced in the beta
```
npm install --save react-native-elements@beta
```

**Comment by adriancuco** [comment]
Hi Xavier,


It works like a charm. Really appreciate it.


BTW, I've just dropped and autoFocus feature found in the searchBar. ;)


Thx


Regards


________________________________
De: Xavier Villelégier <notifications@github.com>
Enviado: martes, 13 de febrero de 2018 17:16
Para: react-native-training/react-native-elements
Cc: adriancuco; Mention
Asunto: Re: [react-native-training/react-native-elements] Searchbar, cannot find folder (#904)


This was introduced in the beta

npm install --save react-native-elements@beta
