### ISSUE TITLE
Searchbar, left icon ni change to arrow when focus, and onCancel does not work either

### ISSUE THREAD

**Issue by adriancuco** [react-native-training/react-native-elements#905]
### Description
Android, Searchbar, left icon no change to arrow when focus, and onCancel does not work either

Thx a lot

**Comment by xavier-villelegier** [comment]
Hey @adriancuco , could you give an example ? It works fine on [this one](https://snack.expo.io/BJRQuKewf)

**Comment by adriancuco** [comment]
Maybe it has to do with the other issue, where not found searchbar folder. It works but not completed.
I do know know. I tried an easy example like yours and still not working: no back icon and no onCancel call.

Thx

Sent from my iPhone

On 13 Feb 2018, at 16:46, Xavier Villelégier <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @adriancuco<https://github.com/adriancuco> , could you give an example ? It works fine on this one<https://snack.expo.io/BJRQuKewf>
