### ISSUE TITLE
searchbar with autoFocus works ;)

### ISSUE THREAD

**Issue by adriancuco** [react-native-training/react-native-elements#908]
Hi,

I wanted to get autoFocus when showed the searchBar so I added  autoFocus={true} , and it works.
I guess the TextInput inherits the parameter.

FYI 

Regards

**Comment by JayKurniawan** [comment]
it works on iOS, but not on Android
any idea ?

**Comment by Jayiitb** [comment]
@iRoachie Thanks it worked. How did u figure out this prop? It's not mentioned on the doc.

**Comment by iRoachie** [comment]
@Jayiitb it is mentioned in the doc 
![ed407129-193f-4d60-88d2-3de961967203](https://user-images.githubusercontent.com/5962998/50213962-7d409a00-0355-11e9-847d-e4690b6f8e88.jpeg)
