### ISSUE TITLE
How to stretch button on iOS (v1.0.0-beta2)? 

### ISSUE THREAD

**Issue by ginsev** [react-native-training/react-native-elements#911]

**Comment by xavier-villelegier** [comment]
@ginsev Is this what you're trying to do ?

![img_2b4051e2bcc1-1](https://user-images.githubusercontent.com/17592779/36264769-f26b1c4e-126d-11e8-9fe7-9222880f8c4f.jpeg)

Have a look at this [snack example](https://snack.expo.io/BJD4_QmDz) ✌️

**Comment by ginsev** [comment]
Yes. `buttonStyle={alignSelf: 'stretch'}` works on android but not iOS.

**Comment by ginsev** [comment]
Thank you. It worked.
