### ISSUE TITLE
Invariant Violation: element Type is invalid

### ISSUE THREAD

**Issue by Rah1x** [react-native-training/react-native-elements#912]
i upgraded to beta version and now anyuse of `react-native-elements` leads to the error:

![image](https://user-images.githubusercontent.com/841857/36289594-d6422e70-1314-11e8-8d4b-18f05b95f55c.png)

**Comment by LouisJS** [comment]
There's breaking change. So if try to identify which component causes the issue and update it.

**Comment by ocalvet** [comment]
I'm having the same issue when I try to add a FormLabel inside a Card component
```
...
<Card containerStyle={{padding:0}}>
          <FormLabel>Email</FormLabel>
</Card>
...
```

**Comment by Rah1x** [comment]
I found the reason being the upgrade. A lot has changed in the upgrade but the documentation is listing both old and new versions. So there is no `formlabel` anymore for example. Similarly, Input field now has a icon builtin (which Ive spend like 2 day to get a perfect looking `view` with icon and a field together with previous version).. all in all, total time waste

**Comment by iRoachie** [comment]
@Rah1x Thanks for bringing this up. Totally agree that the documentation is confusing, and we apologize for that. We got a little too excited with the beta and forgot about keeping documentation live for 0.19.0. I'm just about finished a PR for a new docs site that will be able to toggle between versions. Since you're so passionate about docs, I'd love to get your opinion on it.

The instructions to install and preview are in the pull request comments as well.
https://github.com/react-native-training/react-native-elements/pull/902

**Comment by xavier-villelegier** [comment]
@Rah1x @LouisJS @ocalvet 
New documentation is live [here](https://react-native-training.github.io/react-native-elements/) ! You can now select the version of the doc you want by clicking on the version name on the top header.
A biiig shout out to @iRoachie 🎉

**Comment by LouisJS** [comment]
Awesome ! There's missing images on Avatar / Header / Overlay / Rating / Slider.
It looks great ! i'm really glad to see this library is evolving so fast !
Road to v1 💥

**Comment by iRoachie** [comment]
Fixed @LouisJS thanks for alerting!

**Comment by Rah1x** [comment]
wow this is really a great documentation. great work guys

**Comment by Monte9** [comment]
@iRoachie for President 2020!! 

Again, great work @iRoachie for taking the lead on this project and following through with it! I am super impressed. 🥇

**Comment by phuquoc** [comment]
Hello, i'm a newbie on ReactNative, I tried to learn about react-native-elements from this example https://snack.expo.io/rJu6gJfBZ 
I did not use Expo but run my apps on a virtual machine instead, I got the error below, I spent hours and hours to fix it but not worked :(((
![image](https://user-images.githubusercontent.com/20508535/55162393-0b53ca00-5168-11e9-933f-9a38a8fd6880.png)

I installed react-native-elements 1.1.0 and react-native-cli: 2.0.1 react-native: 0.52.3

PLEASEEE help me, many thanks
