### ISSUE TITLE
Setting Icon size make an error

### ISSUE THREAD

**Issue by Talkwondo** [react-native-training/react-native-elements#913]
Hello,
When I want to make an icon size which is shown in the docs as a prop of the component <Icon>
I am getting an error:

<img width="310" alt="screen shot 2018-02-16 at 15 17 38" src="https://user-images.githubusercontent.com/20122139/36309249-90157d4a-132c-11e8-92fd-ef5342d6629d.png">

Please someone assist me.

Thanks,

Tal

**Comment by iRoachie** [comment]
What code did you use?

**Comment by Talkwondo** [comment]
<Icon name={rowData.icon} size="40" type='font-awesome' color='green' />

**Comment by Talkwondo** [comment]
this:<Icon name={rowData.icon} size="40" type='font-awesome' color='green' />

**Comment by Talkwondo** [comment]
i am using font awsome                 <Icon name={rowData.icon} size="40" type='font-awesome' color='green' />

**Comment by iRoachie** [comment]
No I mean what does your code look like that produced this error

**Comment by Talkwondo** [comment]
<Icon size='40' type='font-awesome' color='green' name={rowData.name}

**Comment by Talkwondo** [comment]
with closing tag

**Comment by iRoachie** [comment]
The size prop takes in a **number** not a string.
```jsx
<Icon size={40} type='font-awesome' color='green' name={rowData.name}
```

**Comment by Talkwondo** [comment]
Thanks...
