### ISSUE TITLE
Type number for Inputs

### ISSUE THREAD

**Issue by FakhruddinAbdi** [react-native-training/react-native-elements#917]
### Description

I need to have type number to `Input` element so it will show numeric keyboard on touch the input

Version: 1.0.0-beta

Is it possible..?
Thanks

**Comment by xavier-villelegier** [comment]
Hey @FakhruddinAbdi, any props you pass to the `Input` will be passed to the `TextInput` of React Native. Considering that, you can use the [`keyboardType`](https://facebook.github.io/react-native/docs/textinput.html#keyboardtype). props of the `TextInput`.

```jsx
<Input
  placeholder="Phone number..."
  type="numeric"
/>
```

**Comment by FakhruddinAbdi** [comment]
Thanks @xavier-villelegier ... 
`keyboardType = 'numeric'` solved my problem

**Comment by iRoachie** [comment]
@mrkhoros Are you using version 1.0.0-beta5?

**Comment by FakhruddinAbdi** [comment]
try `keyboardType={'phone-pad'}`. sometimes for no reason in some devices :)  keyboard numeric doesn't work.

**Comment by Gys** [comment]
I am using 1.0.0-beta5 and when I try `keyboardType={'email-address'}` then it still shows a normal keyboard.
