### ISSUE TITLE
Allow title for `Card` to be a React Component

### ISSUE THREAD

**Issue by meganlwood** [react-native-training/react-native-elements#918]
Is there a way to change the Title at the top of a Card to be a TextInput?

**Comment by xavier-villelegier** [comment]
Hey @meganlwood, not for now ! But I'll let this opened as a possible enhancement

**Comment by iRoachie** [comment]
If anyone wants to work on this, here are the following requirements:
1. Card title should be able to pass in a string or a react element
2. If title is a react element - display it. If not display the current `Text` component with `titleStyle` and `titleNumberOfLines` https://github.com/react-native-training/react-native-elements/blob/master/src/card/Card.js#L60-L70
You can check if a variable is a react element by using `React.isValidElement(<element>)`.
Be sure to checkout the [Checkbox component](https://github.com/react-native-training/react-native-elements/blob/3437699b608ab1fda2bde54d6096bc3c9714abd6/src/checkbox/CheckBox.js#L80-L92) which does this check.

3. Update the propTypes to allow for a component or string https://github.com/react-native-training/react-native-elements/blob/master/src/card/Card.js#L121. 
It'll become `title: PropTypes.oneOfType([PropTypes.string, PropTypes.node])`
4. Update the typescript definitions to allow for a component or string
https://github.com/react-native-training/react-native-elements/blob/master/src/card/Card.js#L60-L70. 
It'll become `title?: string | JSX.Element;`

**Comment by msevestre** [comment]
@iRoachie yep count me in

**Comment by iRoachie** [comment]
Merged in https://github.com/react-native-training/react-native-elements/commit/2308b1b02519fe90a26bd03a024b00a9c8924525. Will be available in 1.0.0-beta3

**Comment by iRoachie** [comment]
Live in [1.0.0-beta3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3).
