### ISSUE TITLE
icons don't render in create-react-native-app

### ISSUE THREAD

**Issue by starblastresearch** [react-native-training/react-native-elements#919]
I have created a basic app with create-react-native-app

then I added a button, but it is rendered as a grey square without any icon. See the attached screenshot. I tried many different solutions but none of them worked.
Please let me know why it does not work.

      import { Button } from 'react-native-elements';
      import Icon from 'react-native-vector-icons/FontAwesome';

<Button
  icon={
    <Icon
      name='arrow-right'                                                                                                                                                                                  
      size={15}
      color='white'
    />
  }
/> 

![screen shot 2018-02-20 at 7 54 32 pm](https://user-images.githubusercontent.com/35978945/36462390-e9c59354-1677-11e8-9575-c9bbc030a171.png)

**Comment by Monte9** [comment]
@starblastresearch please make sure to install `yarn add react-native-elements@beta`

I suspect you currently have` v0.19`. Please update and `<Button />` should look much better :)

**Comment by starblastresearch** [comment]
Thank you, that worked!

Do you guys mind updating your installation instructions to let people know that they should not use the current production version or updating the current production version so people who did not use your library before don't run into such issues the first minute? The 0.19 version is completely unusable. I almost abandoned it altogether because adding an <Input/> component just crashes the app on the spot.

**Comment by xavier-villelegier** [comment]
@starblastresearch We're updating the documentation to be much more clear about that. You will be able to check the doc for the version you're using 🎉 Check out #902
