### ISSUE TITLE
Unable to open demo app on android

### ISSUE THREAD

**Issue by mountriv99** [react-native-training/react-native-elements#921]
### Description

1. Explain what you did
Wanted to check out the demo app on android

2. What you expected to happen
Expected it to work

3. What actually happens
Encountered errors (see attached screenshot)

![image](https://user-images.githubusercontent.com/584545/36472910-1443d09e-172e-11e8-9961-90b8e49b64e1.png)

**Comment by xavier-villelegier** [comment]
@mountriv99 You're trying to open it through [this link](https://expo.io/@monte9/react-native-elements-app) or by cloning [this repo](https://github.com/react-native-training/react-native-elements-app) ?

**Comment by mountriv99** [comment]
@xavier-villelegier Tried to do it through the link

**Comment by xavier-villelegier** [comment]
@mountriv99 Just tested on my Android and everything works, can you check if there is an update of the Expo app on the Play Store ? Which Android version do you have ?

**Comment by mountriv99** [comment]
@xavier-villelegier I updated to the newest expo app but same errors. Using android 6.0 on a Redmi Note 4

**Comment by mountriv99** [comment]
@xavier-villelegier Hey, just tried it again and it suddenly works! All good now. Guess I didn't fully close the app after updating yesterday...?

**Comment by xavier-villelegier** [comment]
Oh okay, that's good to know. Thanks 👍
