### ISSUE TITLE
Installation Guide for CLI is broken

### ISSUE THREAD

**Issue by anikets43** [react-native-training/react-native-elements#928]
Below guide URL is broken
https://react-native-training.github.io/react-native-elements/Installation/default_installation/

**Comment by xavier-villelegier** [comment]
@anikets43 Yes we're deploying a new documentation website, that's why existing Google links are broken… We'll need to wait for a reindexing of https://react-native-training.github.io/react-native-elements/ on Google

**Comment by iRoachie** [comment]
Closing this as there's no further action that can be done on our part.
