### ISSUE TITLE
Ghosting around controls on Android

### ISSUE THREAD

**Issue by starblastresearch** [react-native-training/react-native-elements#932]
We have tried your library with Expo on Android and we found that all of the rounded controls have ghosting shadows around the rounded corners. This is not the case on iOS devices. 
Is there any way around this issue? 
Please see the screenshot FYI. The LOG IN, Add To Cart button, HOME and PROFILE buttons, as well as a teal colored one with the spinner. This is not only those with high rounding radius but also those with slightly rounded corners as well. Depending on background they look very weird. 

![screenshot_2018-02-21-09-13-30](https://user-images.githubusercontent.com/35978945/36494713-be386480-16e7-11e8-8eb5-87b591f01f4e.png)

**Comment by xavier-villelegier** [comment]
Hey @starblastresearch, yes by default there is an elevation on Android, to fit Material Design, as it is specified [here in the Google guideline](https://material.io/guidelines/components/buttons.html#buttons-button-types). If don't want this you can do this:
```jsx
<Button
  title="Test"
  buttonStyle={{ elevation: 0 }}
/>
```

**Comment by starblastresearch** [comment]
Thank  you Xavier. Is there any switch that turns it off for all buttons instead of specifying it for each individual one? Also is there any auto-sensing mechanism to determine which version of Android you are at? I believe not all Android versions use material design and on those versions it looks extremely bad. It would be very cumbersome if we had to turn it off for all buttons or wrap your components into another layer.

**Comment by xavier-villelegier** [comment]
@starblastresearch For now… unfortunately yes. But in the `v1.0.0` (in development) we will introduce a theming feature. So you'll be able to customize once the theme for all your components 🔥
