### ISSUE TITLE
Docs: Overlay image is broken

### ISSUE THREAD

**Issue by gianpaj** [react-native-training/react-native-elements#934]
Link:
https://react-native-training.github.io/react-native-elements/docs/overlay.html
Source:
https://github.com/react-native-training/react-native-elements/blob/master/docs/overlay.md

I didn't find where in the repo you wanted to put the images. There is no `/img` folder. So i didn't do a PR

Here is the image:
https://raw.githubusercontent.com/react-native-training/react-native-elements/ef6aef0c7a240443df2bbe086cfb2548866e3883/docs/images/overlay.png

from this commit https://github.com/react-native-training/react-native-elements/commit/ef6aef0c7a240443df2bbe086cfb2548866e3883

**Comment by iRoachie** [comment]
Thanks! The image folder is here if you’re interested in the doing the PR.

https://github.com/react-native-training/react-native-elements/tree/master/website/static/img
