### ISSUE TITLE
Unable to install react native with react native elements

### ISSUE THREAD

**Issue by judemanutd** [react-native-training/react-native-elements#937]
React native cli globally installed version : 2.0.1

I then used react-native init project_name to set up a project with the native modules.

I then tried installing React Native Elements UI Toolkit using yarn add react-native-elements@beta followed by yarn add react-native-vector-icons and then react-native link react-native-vector-icons as per the docs here React Native Elements Docs

The install completed successfully with a package.json that looks like this

    {
      "name": "prudent_react_native",
       "version": "0.0.1",
       "private": true,
       "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest"
     },
      "dependencies": {
       "react": "16.2.0",
       "react-native": "0.53.3",
       "react-native-elements": "^1.0.0-beta2",
       "react-native-vector-icons": "^4.5.0"
     },
     "devDependencies": {
       "babel-jest": "22.4.0",
       "babel-preset-react-native": "4.0.0",
       "jest": "22.4.0",
       "react-test-renderer": "16.2.0"
     },
     "jest": {
       "preset": "react-native"
       }
     }

I have used the following as my default component

import React, {Component} from 'react';
import {View} from 'react-native';
import {Button} from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';

    export default class App extends Component {
    render() {
        return (
            // Try setting `flexDirection` to `column`.
           <View style={{flex: 1, flexDirection: 'row'}}>
            <View style={{width: 50, height: 50, backgroundColor: 
        'powderblue'}}/>
            <Button
                icon={
                    <Icon
                        name='arrow-right'
                        size={15}
                        color='white'
                    />
                }
                text='BUTTON WITH ICON'
            />
        </View>
        );
      }
    };

This throws the following error

[Error Screen](https://i.stack.imgur.com/6Gjqr.png)

I am not sure if what i did was wrong or something went wrong. I noticed that when i hadn't added `import Icon from 'react-native-vector-icons/FontAwesome';` in the project it hadn't crashed but the moment i did, it threw that error.

**Comment by iRoachie** [comment]
This is an error in metro bundler around handling paths to direct files. The issue and workarounds have been logged over at the react-native repo. 

https://github.com/facebook/react-native/issues/17610#issuecomment-357884014

I've fixed using the blacklist method. Create a `rn-cli.config.js` file in your root directory and paste in the following code.

```js
const blacklist = require('metro/src/blacklist')

module.exports = {
  getBlacklistRE() {
    return blacklist([/react-native\/local-cli\/core\/__fixtures__.*/])
  },
}
```

Be sure to restart the packager.

**Comment by judemanutd** [comment]
That worked, thank you so much.

**Comment by Monte9** [comment]
Woah! That's a solid find @iRoachie! Thanks for the linking the exact comment to the original issue! 👏 

Glad that helped you @judemanutd!

**Comment by mmnithin** [comment]
👍
