### ISSUE TITLE
input.js is missing from the src/input folder after installation

### ISSUE THREAD

**Issue by derkweijers** [react-native-training/react-native-elements#939]
### Description

1. Explain what you did
Install react-native elements with "npm install react-native-elements --save"

2. What you expected to happen
Import the Input component and use it.

3. What actually happens
Input components does not exists.

I'm using version 0.19.0
### Reproduction Steps and Sample Code
Install and try to use.

### Solution

Not sure what is going wrong. The Git repo has the input.js file in the src/input, but when I install it through NPM, I only see search.js in the src/input folder. I've tried it in multiple projects.

https://imgur.com/J15KzEM

**Comment by iRoachie** [comment]
Hey @derkweijers, they're two versions of react-native-elements available to the public right now.
0.19.0 and 1.0.0-beta2. The `Input` component is only available in the beta as we're still modifying it actively based on user feedback.

If you want to use the `Input` component then you'll have to upgrade to the beta. 
`npm install --save react-native-elements@beta`. You can read more about the reasoning behind v1 [here](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta).

If you want to stay on `0.19.0` then you'll have to use the `FormInput` component https://react-native-training.github.io/react-native-elements/docs/0.19.0/forms.html

**Comment by derkweijers** [comment]
Ah, okay! Thank you for the answer.

May I suggest some sort of label on https://react-native-training.github.io/react-native-elements/docs/input.html. Some sort of Beta label.

Kind regards,
Derk

**Comment by derkweijers** [comment]
I just found the version the docs corresponds to in the header, so never mind and sorry for the trouble!

**Comment by iRoachie** [comment]
All good, glad I could help
