### ISSUE TITLE
how to pass data to another page using navigation in react native

### ISSUE THREAD

**Issue by ishafiam124** [react-native-training/react-native-elements#941]
### Description

1. Explain what you did
2. What you expected to happen
3. What actually happens

Also please include the version of `react-native-elements` that you are using.

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by iRoachie** [comment]
Hey there @ishafiam124, your question seems to be one with react-navigation and not react-native-elements. I suggest you checkout the react-navigation document on how to [pass data between screens](https://reactnavigation.org/docs/params.html)

**Comment by xavier-villelegier** [comment]
Closing this as it seems to be clearly related to `react-navigation`, and we have absolutely no information from your description. Feel free to ping us if you have more information and it comes from RNE.
