### ISSUE TITLE
Can't set icon type for Avatar

### ISSUE THREAD

**Issue by shubhamrathi97** [react-native-training/react-native-elements#942]
### Description
`<Avatar
                        large
                        rounded
                        icon={{name:"user-female", type:"simple-line-icon", size: 25}}
                        // title="CR"
                    >`

Above code should render SimpleLineIcon of react-native-vector-icon, but instead, it is only showing icons of font awesome. 

Version
`"react-native-elements": "^1.0.0-beta2"`
`"react-native": "0.52.1"`

### Solution
As I can read in Avatar.js file, We have not handle icon type. It is only rendering font-awesome icons. 
For example : 
[Reference to Avatar.js](https://github.com/react-native-training/react-native-elements/blob/master/src/avatar/Avatar.js#L104)

It is taking the 'type' prop and passing props to Icon of react-native-vector-icon. As per vector-icons doc, We need to import different types of Icons separately. It wouldn't do anything if we pass icon prop 'type' like this.

**Comment by iksent** [comment]
I think it is not "Enhancement", but a real bug. Please, fix it as soon as possible. Very important thing, to use custom icon types in Avatar.

**Comment by iRoachie** [comment]
Sorry @iksent, I misunderstood the issue at first. Will take a look at it this evening

**Comment by vintage** [comment]
@iRoachie If I got it right, the only implementation issue here is that `Avatar` is importing direct version of `Icon` - https://github.com/react-native-training/react-native-elements/blob/master/src/avatar/Avatar.js#L17 - instead of "proxied" one - https://github.com/react-native-training/react-native-elements/blob/99f80cd8b0937e076ce17c7f99daba2ee9b0b997/src/icons/Icon.js which correctly handles the type?

**Comment by Monte9** [comment]
@vintage ah yeah. that's a good catch. 

Yup, all we need to do is to change the `Icon` import from using `react-native-vector-icons` to using our own custom `Icon.js` component. 

Feel free to submit a PR if anyone gets a chance. Also update the `Avatar` demo on the example app to show how to pass multiple icons to the Avatar component.

**Comment by vintage** [comment]
@Monte9 Fixed. I've submitted two PRs:

- First for `react-native-elements` itself to support icon type for `Avatar` - https://github.com/react-native-training/react-native-elements/pull/980
- Second for `react-native-elements-app` to show the usage of the `Avatar` (the section has been empty before my changes, strange)

**Comment by iRoachie** [comment]
Live in [1.0.0-bets3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3). Thanks again for super PRs @vintage
