### ISSUE TITLE
Input is not exported in TypeScript definitions

### ISSUE THREAD

**Issue by Mukeyii** [react-native-training/react-native-elements#947]
### Description

**1. Explain what you did**

I've updated from 0.19 to 1.0.0-beta to change the style of my Searchbar (works). Had to replace FormInput with Input to avoid the Invariant-Violation-Error.

**2. What you expected to happen**

I can still import FormInput, FormLabel etc. from the beta-version (index.d.ts), but 'Input' can't be found. 

`import {Text, Button, Input, Icon, Card} from 'react-native-elements';`

**Comment by iRoachie** [comment]
What version of the beta are you currently on?

**Comment by Mukeyii** [comment]
"react-native-elements": "^1.0.0-beta2",

**Comment by iRoachie** [comment]
You're correct! Forgot to update the definitions.

**Comment by iRoachie** [comment]
For anyone that wants to take this up, they can check the [FormInput definitions](https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L767) for an example on how to add definitions for a component.

**Comment by msevestre** [comment]
Yeah I'll take a look

**Comment by iRoachie** [comment]
Added in https://github.com/react-native-training/react-native-elements/commit/29f30d4af6161178f8d30d76eda468abf16c4622, should be apart of the 1.0.0-beta3 release

**Comment by lifeiscontent** [comment]
@iRoachie when will the release be posted?

**Comment by iRoachie** [comment]
@lifeiscontent  Sunday
