### ISSUE TITLE
Unrecognized font family 'Lato

### ISSUE THREAD

**Issue by NaleenDissanayake** [react-native-training/react-native-elements#948]
### When run ios in standard react-native project shows "Unrecognized font family 'Lato"
    "native-base": "^2.3.9",
    "react": "16.2.0",
    "react-native": "0.53.3",
    "react-native-elements": "^0.19.0",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.2.0"

<img width="399" alt="screen shot 2018-02-27 at 4 08 06 am" src="https://user-images.githubusercontent.com/14317979/36699820-e130c8fc-1b73-11e8-8858-fed19e72cf0b.png">

**Comment by iRoachie** [comment]
Hey @NaleenDissanayake that message shows up when you're trying to use a custom font without adding it to your Xcode project. We don't use the Lato font in our library, so this error is coming from your personal code.

**Comment by NaleenDissanayake** [comment]
Yes. I got that issue was in code. Thanks.

**Comment by ThomasGHenry** [comment]
@iRoachie, You might consider revising your examples then. 

https://react-native-training.github.io/react-native-elements/docs/card.html

**Comment by iRoachie** [comment]
Sure thing @ThomasGHenry
