### ISSUE TITLE
How to add local images from a dictionary to avatar?

### ISSUE THREAD

**Issue by Asinox** [react-native-training/react-native-elements#949]
Hello, I'm getting into RN, and I have this issue that I can't solve.
A FlatList with a source from a dictionary with local images, and I can't see a way to pass the images to the FlatList Avatar without getting some errors.

```
constructor(props)
    {
        super(props);

        this.state = { FlatListItems: [
            {key: 'Nail', image:'../images/Nail.png'},
            {key: 'Bone', image:'../images/bone.png'},
            ...
        ]}
    }


render(){
        return(
            <List>
                <FlatList
            data={this.state.FlatListItems}
                    renderItem={({ item }) => (
                    <ListItem
                        roundAvatar
                        title={`${item.key}`}
                       avatar={`${item.image}`}
                    />
                )}
                />
            </List>
                       
        )
    }
```

The avatar line is just showing an empty circle.

How can I pass the dictionary item.image to this avatar?
Thanks!

**Comment by LouisJS** [comment]
Hi @Asinox.

You avatar looks empty because you're not providing the right syntax to load your [Image](https://facebook.github.io/react-native/docs/image.html).

For URL, you should use : `avatar={{uri: 'www.linktourl.com/image.jpg'}}`
It looks like you are look for local resources as you're passing _relative path_.

In that case, you should use : `avatar={require('../path/to/local/image.png')}`

**Comment by iRoachie** [comment]
@Asinox local images in react native are statically analyzed and only images that are `required` are included in the final build. Check https://facebook.github.io/react-native/docs/images.html `#4`. Which means static assets have to included the same way as modules do - either by imports or requires.

This means that your above code in your dictionary/json needs to change from:
```json
{"key": "Bone", "image":"../images/bone.png"}
```

To:
```js
{"key": "Bone", "image": require("../images/bone.png") }
```

**Comment by xavier-villelegier** [comment]
Closing this as @iRoachie seems to have the good solution. Feel free to ping us if you still need help @Asinox 👍

**Comment by J-Liu** [comment]
Hi all,

I have the same problem.

the fake data source looks like
`{"key": "Bone", "image": require("../images/bone.png") }`

And this is how I use it
```
        <List>
          {users.map(user=> (
            <ListItem
              key={user.name}
              roundAvatar
              avatar={`${user.image}`}
            />
          ))}
        </List>
```

It seems ```avatar={`${user.image}`}``` is not the right way, anyone please tell me how to use it properly?

**Comment by iRoachie** [comment]
@J-Liu Can't you use `avatar={user.image}`?

**Comment by J-Liu** [comment]
@iRoachie Thank you, vvvvvvery much!
