### ISSUE TITLE
Difficulties creating Button with flex: 1

### ISSUE THREAD

**Issue by tiagoalves** [react-native-training/react-native-elements#957]
### Description

1. Explain what you did

I'm trying to have two buttons with `flex: 1`, side by side.

2. What you expected to happen

Have two buttons each with half the screen's width on both Android and iOS.

3. What actually happens

The solution I have for Android seems rather complex and it doesn't even work on iOS. There it creates two buttons that take up the full height of the screen and are just as wide as the button's text.

<img width="278" alt="screen shot 2018-03-01 at 15 45 24" src="https://user-images.githubusercontent.com/215495/36854333-a3d6ca28-1d68-11e8-84d6-2ff4820e3e00.png">

Is the code sample below the right approach for this problem?

Also please include the version of `react-native-elements` that you are using.

1.0.0-beta2

### Reproduction Steps and Sample Code

```
export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Button
          text="Button 1"
          containerStyle={{
            margin: 5,
            flex: 1,
            flexDirection: "row"
          }}
          buttonStyle={{
            flex: 1
          }}
        />
        <Button
          text="Button 1"
          containerStyle={{
            margin: 5,
            flex: 1,
            flexDirection: "row"
          }}
          buttonStyle={{
            flex: 1
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
});
```

Expo Snack: https://snack.expo.io/H1LWkjSuf

### Solution

None. However, I haven't found an upgrade guide from v0.19 to v1.0.0. It would be great to have one because our buttons worked all fine before we upgraded to v1.0.0-beta2 and now we're struggling to get our app to look like it did before.

**Comment by LouisJS** [comment]
https://snack.expo.io/H1MxbhruM

**Comment by tiagoalves** [comment]
I now got it to work with the following:

Expo Snack: https://snack.expo.io/BJA8dsr_G

```
      <View style={styles.container}>
        <Button
          text="Button 1"
          containerStyle={{
            margin: 5,
            flex: 1
          }}
          style={{
            width: "100%"
          }}
          buttonStyle={{
            width: "100%"
          }}
        />
        <Button
          text="Button 2"
          containerStyle={{
            margin: 5,
            flex: 1
          }}
          style={{
            width: "100%"
          }}
          buttonStyle={{
            width: "100%"
          }}
        />
      </View>
```

I had to add both `style` and `buttonStyle` because `style` just worked on iOS and `buttonStyle` on Android.

Does this look like the best approach?

Thanks!

**Comment by tiagoalves** [comment]
@LouisJS thanks for the help. Your example works for Android but on iOS I get the same result as in my original screenshot (two long vertical buttons).

**Comment by Monte9** [comment]
@tiagoalves Here is another way to do this: https://snack.expo.io/SJirrEp_z

And this works for ios & android both. Please see screenshots below
<div style={{flexDirection: 'row'}}>
<img width="240" alt="screen shot 2018-03-07 at 1 51 51 am" src="https://user-images.githubusercontent.com/7840686/37085620-5a785c84-21aa-11e8-98c8-36ef907ea7b0.png">
<img width="225" alt="screen shot 2018-03-07 at 1 52 14 am" src="https://user-images.githubusercontent.com/7840686/37085621-5a966ea4-21aa-11e8-8bb8-cca9cfc3dfe1.png">
</div>

**Comment by tiagoalves** [comment]
Thanks for the help. I'm closing this since I've been successfully using the approach I mentioned in this [comment](#issuecomment-369657974).
