### ISSUE TITLE
Button text not centered with "%" width

### ISSUE THREAD

**Issue by alfredkam** [react-native-training/react-native-elements#959]
###Description
Using `react-native-elements@^1.0.0-beta2`, passing a width in percentage into the Button Component caused the text align to not center.

![screen shot 2018-03-01 at 2 14 26 pm](https://user-images.githubusercontent.com/1495567/36873268-d353cc94-1d5c-11e8-876e-75cb93f42298.png)

Sample Code
```
import { StyleSheet, View } from 'react-native';
import { Button } from 'react-native-elements';

const styles = StyleSheet.create({
  buttonTest: {
    backgroundColor: "#402293",
    width: "80%",
    height: 50,
  }
});
const ButtonTest = () => (
  <View>
    <Button
       text="LOGIN"
       buttonStyle={styles.buttonTest} />
  </View>
);
```
###Solution
include
`textStyle={{width: "100%"}}`

**Comment by xavier-villelegier** [comment]
Thanks for reporting this. [Here is](https://snack.expo.io/rkYLucLuM) a snack example of the bug.
Maybe the best approach is to add `width: '100%'` by default if a `width` is defined in `buttonStyle`

**Comment by martinezguillaume** [comment]
That's weird, I tested the snack in an android phone and it works, it's just an iOS bug 🤨

**Comment by Gregjarvez** [comment]
@xavier-villelegier 
I found this fix to work for me too and it only happens on IOS hence there might be a need to make this platform specific. Leaving this  solution in doesn't affect text position on android.

```javascript
    let { textStyle = {} } = this.props;
    textStyle = (buttonStyle && buttonStyle.width) && !textStyle.width ?
             Object.assign({}, textStyle, {width: '100%'}) : textStyle;
```
what do you think ?

**Comment by xavier-villelegier** [comment]
@Gregjarvez Yep that's what I was proposing ! Feel free to open a PR, you seem to be on fire recently 🔥

**Comment by Gregjarvez** [comment]
@xavier-villelegier sure !!!!!!!!

**Comment by iRoachie** [comment]
Released in [`1.0.0-beta4`](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta4)!

**Comment by miller365** [comment]
I am having this same issue except its now with Android only and not affecting iOS.

**Comment by iRoachie** [comment]
Hey @miller365 would prefer if you created a new issue
