### ISSUE TITLE
Header icon background color is white

### ISSUE THREAD

**Issue by teamhide** [react-native-training/react-native-elements#961]
1. Explain what you did
I'm using Header with icon. If I click that, White square box appears behind the icon.

        <View>
          <Header
            leftComponent={<SearchArticle action={this._afterSearch} style={{underlayColor: '#64b5f6'}}/>}
            centerComponent={{ text: 'Board', style: { color: '#fff' } }}
            rightComponent={<WriteBoard username={this.state.userNick} refresh={this._onRefresh}/>}
          >
          </Header>
        </View>

[Before click]
<img width="98" alt="2018-03-03 10 33 02" src="https://user-images.githubusercontent.com/8403122/36934837-e0e7a13c-1f32-11e8-9811-6ba1605478d4.png">

[After click]
<img width="109" alt="back" src="https://user-images.githubusercontent.com/8403122/36934828-bd5e47e8-1f32-11e8-8b4b-7ba8e497ecd8.png">

2. What you expected to happen
I want to remove white square box behind the icon. react-native-elements version is 0.19.0. Thanks.

**Comment by xavier-villelegier** [comment]
Hey @teamhide, have a look at https://github.com/react-native-training/react-native-elements/issues/640#issuecomment-334478955, and let me know if it helps 👍

**Comment by teamhide** [comment]
@xavier-villelegier Thanks for the quick reply. I already read that, But It seems little bit different on my case. That issue just defines icon but my case,  pass component to leftComponent. (leftComponent={<SearchArticle>}). Maybe it is the same case, But I'm very new at React.js. How can I set underlayColor on my case?

**Comment by xavier-villelegier** [comment]
@teamhide Could you post your `SearchArticle` component ?

**Comment by teamhide** [comment]
@xavier-villelegier Yeap. I just uploaded source code here. https://snack.expo.io/SJcoYQOdf

**Comment by xavier-villelegier** [comment]
@teamhide This part

```jsx
<TouchableOpacity>
  <Icon
    name='search'
    style={styles.icon}
    reverseColor={'red'}
    onPress={() => this.openModal()}
  />
</TouchableOpacity>
```

You don't need yo have a `TouchableOpacity` around the `Icon`, as it handles the `onPress` for you already. This should do the job:

```jsx
<Icon
  name='search'
  underlayColor={'#2089dc'} // Or any other color, supposed to be your header background color
  style={styles.icon}
  reverseColor={'red'}
  onPress={() => this.openModal()}
/>
```

**Comment by teamhide** [comment]
@xavier-villelegier Exactly solved. Thanks!

**Comment by xavier-villelegier** [comment]
Glad I helped you 💯
