### ISSUE TITLE
Add notice to Tile for Touchable Properties

### ISSUE THREAD

**Issue by iRoachie** [react-native-training/react-native-elements#964]
The documentation for the `Tile` component should mention that it inherits all props from `Touchable` from react-native.

See notice in Button docs for an example message https://react-native-training.github.io/react-native-elements/docs/button.html#button-props.

**Comment by Gregjarvez** [comment]
@iRoachie if no one is doing this I'd like this to be my first pull request :)

**Comment by iRoachie** [comment]
@Gregjarvez That would be great! You can check out our [contributing guide](https://react-native-training.github.io/react-native-elements/docs/contributing.html) on how to get started.

**Comment by Gregjarvez** [comment]
@iRoachie awesome thanks !!!

**Comment by iRoachie** [comment]
Thanks @Gregjarvez. Changes a live! https://react-native-training.github.io/react-native-elements/docs/tile.html#tile-props
