### ISSUE TITLE
How to generate a login/ signup form in the example page

### ISSUE THREAD

**Issue by HarbinLc2014** [react-native-training/react-native-elements#966]
Dear Developer,

Hello, I want to generate a login/signup form as the example page did, which has a smooth arrow pointing to the 'login'/'signUp' text when user clicking on them, I would like to know which element I should use for this?

**Comment by martinezguillaume** [comment]
Hey ! You can have a look at [LayoutAnimation](https://medium.com/@Jpoliachik/react-native-s-layoutanimation-is-awesome-4a4d317afd3e) ! That's what we use to have beautiful animation in a easy way ! 
You can have a look too to the example code [login 1](https://github.com/react-native-training/react-native-elements-app/blob/master/src/views/login/screen2.js) or [login 2](https://github.com/react-native-training/react-native-elements-app/blob/master/src/views/login/screen3.js). Good luck !

**Comment by xavier-villelegier** [comment]
@HarbinLc2014 I'm closing this to clean a bit the issues, feel free to ping us if you need some help with LayoutAnimation
