### ISSUE TITLE
Button title not appearing

### ISSUE THREAD

**Issue by neogeno** [react-native-training/react-native-elements#967]
### Description

1. Explain what you did
`<Button title='hello'/>`

2. What you expected to happen

See a button with a title of hello

3. What actually happens

See a default blue button labelled 'Welcome to React Native Elements;

Also please include the version of `react-native-elements` that you are using.
react-native-elements@1.0.0-beta2

### Reproduction Steps and Sample Code
```
import React, { Component } from 'react';
import {
  Text,
  View,
  ScrollView
} from 'react-native';
import { Button } from 'react-native-elements';

class ReceiveScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Receive Money!</Text>
        <Button title='hello'/>
      </View>
    );
  }
}
export default  ReceiveScreen;
```

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by iRoachie** [comment]
Hey! @neogeno! If you check the docs for `1.0.0-beta2` for Button you'll see that the prop is `text` instead of `title` https://react-native-training.github.io/react-native-elements/docs/button.html#button-props

**Comment by Gregjarvez** [comment]
@iRoachie maybe we can add a warning when title is supplied instead of text ? Until people are more aware of it ?

**Comment by iRoachie** [comment]
It was actually a mistake on our(maintainers) end and the next beta will restore it back to `title`. The commit to change it back is [here](https://github.com/react-native-training/react-native-elements/commit/68ef514154d3f1ecf67c55a44dc83c3566812590).

We can't add a warning without publishing a new version. If there's any doubt, check the documentation on the website which supports showing current props by version

**Comment by Gregjarvez** [comment]
@iRoachie We can't add a warning without publishing a new version. good point lol I am such a newbie

**Comment by iRoachie** [comment]
@Gregjarvez Ha! No sweat man, small things miss me all the time :D

**Comment by neogeno** [comment]
Thanks for the update guys. Actually all the tutorials at https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html show the title props in line with React Native's own Button component, so it's best to revert it back.

**Comment by xavier-villelegier** [comment]
@neogeno That's because you're looking at the `0.19.0` docs, not `1.0.0-beta2` [here](https://react-native-training.github.io/react-native-elements/docs/button.html)

**Comment by JaManrique** [comment]
The 'Getting started' section should not encourage beta versions, as this issues might occur, I worked with the library a couple months before and my code for a simple button wasn't working. Thanks for reverting it.

**Comment by xavier-villelegier** [comment]
@JaManrique 

We just released `v1.0.0-beta3`

The `text` props **was renamed back to `title`**, to be consistent with React Native props.
Rename it to `text` in the `v1.0.0-beta` was a bad move and we're sorry for that.

We're trying to make the `v1.0.0` the best. To achieve that, we must have the most people to test it and report the bugs/possible enhancements. That's why we are encouraging newcomers to use the beta versions.

That being said, the default version (`npm i -S react-native-element`) is still the stable one, so you're free to go for this one, which is the `v0.19.0`.

**Comment by mturki** [comment]
I'm testing v1.0.0-beta3 with typescript,  and i still  have an error when i use `title`. `text` is recognised but not applied : my button is titled "**welcome to React Native Elements**" instead of "**my title**". The types declaration is probably not up to date?

**Comment by xavier-villelegier** [comment]
@mturki Types definition are not up to date, it has been merged and will be release in the next `v1.0.0-beta4` version. Have a look at #1001

**Comment by elarue53078** [comment]
I'm having a different issue.  I'm trying to display text using a white background and a different color, but the text is not showing up at all.  I've tried changing the background color to make sure it wasn't some prop that wasn't getting implemented properly, but the text just does not appear, no matter what I do.

**Comment by iRoachie** [comment]
Hey @elarue53078 would appreciate if you make a new issue, also list the version of react-native-elements you're using and the code you wrote to produce what you're seeing.
