### ISSUE TITLE
Migrate imgur image hosting to another one

### ISSUE THREAD

**Issue by pewh** [react-native-training/react-native-elements#970]
Hello,

I've using react-native-elements for a long time. But when I see new docs, I can't see images because those are hosted on imgur. FYI, imgur has been blocked in my country.

**Comment by xavier-villelegier** [comment]
Oh, we weren't aware of that, sorry. Just curious to know in which country are you ?

**Comment by pewh** [comment]
I'm from Indonesia, where imgur, reddit, vimeo, and tumblr has been blocked. So funny :D

**Comment by iRoachie** [comment]
Sorry about that. Will move kver

**Comment by iRoachie** [comment]
Sorry about that, will move over the images to github.

**Comment by iRoachie** [comment]
Merged in https://github.com/react-native-training/react-native-elements/pull/915/commits/1dee609dd48d26783d75a397fe8f6cbf91583548. Will be available next release. Thanks for pointing this out @pewh

**Comment by iRoachie** [comment]
Live in [1.0.0-beta3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3).
