### ISSUE TITLE
Failing to implement shake input on error

### ISSUE THREAD

**Issue by Craques** [react-native-training/react-native-elements#972]
**1. What I did**

I was following the example in the documentation for the input and the demo app source to create an Input. Everything works fine except for the shake animation

Here is the code 

<Input 
      leftIcon={ <Icon name='email'/>}
      ref = {input=>this.emailInput = input }
      autoCorrect={false}
      placeholder="example@myhost.com"
      //this is not working
      shake={this.state.errors.email.isInvalid}
      errorMessage={this.state.errors.email.errorMessage}
      //this is working so mistake is not in state but in calling shake method
      displayError={this.state.errors.email.isInvalid}
      style={styles.inputStyle}
      containerStyle={styles.inputContainer}
      inputStyle={styles.inputStyle}
      errorStyle={{color: "yellow", fontSize: 16, fontWeight: "400", alignSelf: "center", justifyContent: 
      "center"}}
      leftIconContainerStyle={{backgroundColor:"white"}}
      //this vodoo has to stop there has to be another way
      onChangeText={(text)=>this.onChangeText.bind(this, text, 'email')()}
/>

I am using the beta version of react-native elements as in my package.json: 
"react-native-elements": "^1.0.0-beta2".

There is no error being thrown at the screen but there is no shake effect as well, any help would be great

**Comment by martinezguillaume** [comment]
Hi !

The props `shake` is use just at the `componentDidMount` of the component. You have to use
`this. emailInput.shake()` to shake it !

But you have a good point, we need to update the docs ! Sorry about that 😅

**Comment by Craques** [comment]
Forgot to mention I used this.emailInpu.shake() when I saw the source of the app I passed it to  the email validator like so:

validateEmail(email){
		if(isEmail(email)){
			this.setState((prevState)=>{
				return {
					errors : {...prevState.errors, email: {isInvalid: false}}
				}
			})
		}else{
			this.setState((prevState)=>{
				return {
					errors : {...prevState.errors, email: {isInvalid: true, errorMessage: 'Please enter a valid email'}}
				}
			})
                        this.emailInput.shake()
			console.log(this.state.errors)
		}
	}

But it still was not shaking, is there a specific place I should place it any place where I get an error is ok

*I am using the validator.isEmail for email validation

**Comment by Craques** [comment]
Ok was just testing today and it started working, thanks.

**Comment by hpelitebook745G2** [comment]
@Craques Can you post your solution to make the input shake? Should I use a function to control the shaking or control the boolean and supply it to the `shake` props?

**Comment by Craques** [comment]
This is the bare minimum for an input, its important to add a **ref** prop as below.

`<Input 
	leftIcon={ <Icon name='email'/>}
        **ref = {input=>this.emailInput = input }**
	autoCorrect={false}

/>
`
Then whenever you want the input to shake e.g if there is a validation error, you run **this.emailInput.shake()** a method which is bundled with the Input component

`validateEmail(email){
    if(email === null || email === undefined){
        this.emailInput.shake(); //visual feedback
        return new Promise((resolve, reject) => reject("Email is required") )
    }
}`

**Comment by isaackhoo** [comment]
Anyone has had any luck with V1.1.0 Input shake?
setting shake={true} doesnt do anything, and there is no more method call to use as with the solution above.

**Comment by mdeveloper20** [comment]
I still have same problem. this.emailInput.shake() doesn't work at all.

**Comment by chrisk8er** [comment]
still not work on me...

**Comment by iRoachie** [comment]
Works fine https://snack.expo.io/@roach_iam/curious-sandwich
