### ISSUE TITLE
How to change default backgroundColor of SearchBar?

### ISSUE THREAD

**Issue by maxkarelov** [react-native-training/react-native-elements#976]
### Description

1. I've used SearchBar
2. I want to change background color of SearchBar to another (white for example)
3. Actually I've tried use `backgroundColor` in SearchBar and parent but I can't archive a result
4. version of `react-native-elements` `^1.0.0-beta2`
```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.54.0 => 0.54.0
```

### Reproduction Steps and Sample Code

![image](https://user-images.githubusercontent.com/2924696/37194981-567dcb6e-238a-11e8-87f8-1d23d8f78eb8.png)

```
<SearchBar
          showLoading={false}
          platform={Platform.OS}
          clearIcon={true}
          onChangeText={(text) => params.handleSearch(text)}
          onClearText={() => console.log('onClearText')}
          placeholder='Search..'
          cancelButtonTitle='Cancel'
        />
```

### Solution

No yet

**Comment by xavier-villelegier** [comment]
@maxkarelov That's not possible for now, but can be a good enhancement, thanks for reporting that !

**Comment by pablo-albaladejo** [comment]
@maxkarelov 

This code:

```
<SearchBar
   containerStyle={{backgroundColor: 'green'}}
   inputStyle={{backgroundColor: 'red'}}
/>
```

Provides this result:

![screen shot 2018-03-09 at 22 33 26](https://user-images.githubusercontent.com/7994467/37231092-25eef562-23ea-11e8-97b6-e62f8b8c9364.png)

Hope it helps.

**Comment by iRoachie** [comment]
@pablo-albaladejo you’re referring to the `default` SearchBar. The one he’s mentioning is the iOS version. `platform=“Ios”

**Comment by pablo-albaladejo** [comment]
You are right @iRoachie , my bad.

```
<SearchBar
   containerStyle={{backgroundColor: 'green'}}
   inputStyle={{backgroundColor: 'red'}}
   platform={Platform.OS}
/>
```
Results at iOS:
![screen shot 2018-03-10 at 01 01 16](https://user-images.githubusercontent.com/7994467/37235412-b6aef66a-23fe-11e8-8e44-e05935e54407.png)

**Comment by xavier-villelegier** [comment]
@maxkarelov @pablo-albaladejo The `containerStyle` is now applied to the outer component. This will be part of the `v1.0.0-beta4`

**Comment by muresanandrei** [comment]
When will v1.0.0-beta4 be released?

**Comment by iRoachie** [comment]
@muresanandrei Should be this weekend (Sunday)

**Comment by iRoachie** [comment]
Hot off the press! [`v1.0.0-beta4`](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta4) just released!

**Comment by grissproject** [comment]
It is still failing with I apply the ```platform="ios"``` prop. This is the result (v1.0.0-beta4):
```
<SearchBar
            lightTheme
            icon={{ type: 'font-awesome', name: 'search' }}
            placeholder="Buscar producto..."
            platform="ios"
            containerStyle={{ backgroundColor: 'blue'  }}
            inputStyle={{backgroundColor: 'red'}}
          />
```
<img width="377" alt="screen shot 2018-04-20 at 7 07 51 pm" src="https://user-images.githubusercontent.com/5286643/39077207-36018adc-44ce-11e8-8ba6-0a15505dd09c.png">

It works without the ```platform="ios"```.

**Comment by iRoachie** [comment]
Check this out https://github.com/react-native-training/react-native-elements/issues/1128#issuecomment-382729111

**Comment by grissproject** [comment]
That works! thanks a lot

**Comment by gusmarques** [comment]
<SearchBar
                 reverseColor='#fff'
         ref={(ref) => { ref }}

        placeholder="Pesquisar"
        onChangeText={text => {setSearch(text)}}
        keyExtractor={pesquisa => pesquisa._id}
        value={pesquisa}
        platform="android" 
/>  
    others..

       containerStyle={{ backgroundColor: 'blue'  }}
        inputStyle={{backgroundColor: 'red'}}
        iconStyle={{backgroundColor:'#fff'}}
        inputStyle={{backgroundColor: '#fff', borderColor:'#fff'}}
        containerStyle={{backgroundColor: 'white', borderColor:'#fff'}}
        placeholderTextColor='#444'

platform=""  android or ios

**Comment by varungarg168** [comment]
inputContainerStyle={{backgroundColor: 'white'}}
        leftIconContainerStyle={{backgroundColor: 'white'}}
        inputStyle={{backgroundColor: 'white'}}
        containerStyle={{
            backgroundColor: '#1e3d59',
            justifyContent: 'space-around',
            borderTopWidth:0,
            borderBottomWidth:0,
          }}

**Comment by jeffreybloemen** [comment]
@varungarg168  Legend of the game

**Comment by arn-ob** [comment]
@pablo-albaladejo
inputContainerStyle={{backgroundColor: 'red'}}
