### ISSUE TITLE
Custom fontFamily not working in Button 

### ISSUE THREAD

**Issue by mrcluc** [react-native-training/react-native-elements#977]
Hi, i have one problem with the component Button. I have installed one custom font in my application. This font its working in Text component and in others, however, in lib's Button the font not working.

<Button
              textStyle={{
                fontSize: 15,
                textAlign: 'center',
                paddingLeft:35,
                fontWeight:'500',
                fontFamily:'MarkPro Medium'  <<<<<<<<<<
              }}
              buttonStyle={{
                backgroundColor: "#40B9BB",
                width: 500,
                height: 50,
                borderColor: "transparent",
              }}
              text='Agendar uma demonstração'
              iconRight
              icon={
              <Icon
                name='calendar-range'
                type='material-community'
                color='white'
                size={35}
              />
            }
          />        

I have put the fontFamily prop in textStyle and in prop of button ( <Button fontFamily="" /> ).Is there any way to do this?

**Comment by iRoachie** [comment]
Hey! @mrcluc You'll want to use the `textStyle` prop

**Comment by mrcluc** [comment]
Yes, a im using textStyle prop but is not working:

`textStyle={{
fontSize: 15,
textAlign: 'center',
paddingLeft:35,
fontWeight:'500',
fontFamily:'MarkPro Medium' <<<<<<<<<<
}}`

**Comment by iRoachie** [comment]
Which version of the library are you using?

**Comment by mrcluc** [comment]
1.0.0.beta

**Comment by iRoachie** [comment]
Seems to be working fine to me @mrcluc 
<img width="1242" alt="screen shot 2018-03-10 at 9 14 49 am" src="https://user-images.githubusercontent.com/5962998/37242651-8dd3f200-2443-11e8-98f8-6af83db2788f.png">

Check if you're naming the font correctly

**Comment by mrcluc** [comment]
This font style works correctly. In this case, it is a custom font that does not work.

**Comment by iRoachie** [comment]
Using a custom font and a built in font is the same. Just make sure you added the font to your project correctly. https://medium.com/@kswanie21/custom-fonts-in-react-native-tutorial-for-ios-android-76ceeaa0eb78

**Comment by mrcluc** [comment]
It's ok, this custom font its working in tag <Text></Text> but in Button of framework not working :/

**Comment by xavier-villelegier** [comment]
@mrcluc If you're using the `v1.0.0-beta3` the `textStyle` props has been renamed to `titleStyle`

```jsx
<Button title="Test custom font" titleStyle={{ fontFamily:'MarkPro Medium' }} />
```

**Comment by soninit** [comment]
I'm using **v1.0.0-beta3** but use textStyle doesn't work


Platform: **Android**
ReactNative: **0.54.2**

Code: 
```
<Button
             icon = {
             <Icon
                   name = 'clock-start'
                   size = {15}
                   color = 'white'
                   type = 'material-community'
                   />
              }
              iconRight
              title = 'Start'
              titleStyle = {{fontFamily: 'Product Sans'}}
              buttonStyle = {{backgroundColor: primaryColor, marginTop: 10, paddingLeft: 10, paddingRight: 10}}
>
```

**Comment by iRoachie** [comment]
@soninit The fontFamily names on android are the same as the names of the font files. Can you check `android/app/src/main/assets/fonts` to check what you named it?

**Comment by soninit** [comment]
@iRoachie It work fine for me in Text Component. 

![image](https://user-images.githubusercontent.com/17592012/37617634-45b77e74-2be6-11e8-9f92-bdef42c8edf7.png)

**Comment by iRoachie** [comment]
Can you set the fontWeight to 400 on the button and try that

**Comment by soninit** [comment]
It's work ! I set fontWeight 400. But I don't need to set fontWeight in iOS though.

**Comment by iRoachie** [comment]
Glad I could help. It's something I noticed while developing, using `fontWeight` 600 on android seems to force `sans-serif-medium` font on android(default). So I just abandon using `fontWeight` all together and use `fontFamily` instead.

**Comment by xavier-villelegier** [comment]
Closing this as it seems to be resolved 🎉 . @mrcluc ping us if you still need some help

**Comment by tehzwen** [comment]
just tried to use fontFamily on a button and it isn't working, adding fontWeight gives me errors.

code looks like this ```<Button
                        titleStyle={{ fontFamily: 'Lato-Light' }}
                        title="next"
                        buttonStyle={{ backgroundColor: '#7abebd', borderRadius: 10, marginTop: 'auto', margin: 10 }}
                        onPress={() => this.props.buttonHandler()} />```
