### ISSUE TITLE
Full width `Input`

### ISSUE THREAD

**Issue by lifeiscontent** [react-native-training/react-native-elements#979]
Hey, I'm wondering why the new `Input` component doesn't nest nicely within a card. Is there something I'm missing here?

<img width="416" alt="screen shot 2018-03-10 at 10 00 10 pm" src="https://user-images.githubusercontent.com/180963/37243583-7d89c2a6-24ae-11e8-8059-ee80b1ec56d2.png">

```jsx
      <Card>
        <Text>Username</Text>
        <Input placeholder="username" />
        <Text>Password</Text>
        <Input secureTextEntry placeholder="password" />
        <Button containerStyle={{ marginTop: 10 }} text="Sign In" />
      </Card>
```

**Comment by xavier-villelegier** [comment]
Hey @lifeiscontent, can you be a bit more precise ? What do you want to achieve ?

**Comment by lifeiscontent** [comment]
@xavier-villelegier I'm just wondering why the inputs aren't full width. I'd expect them to be.

**Comment by Grohden** [comment]
@xavier-villelegier solution is working for me... btw, i think that this should be the default behavior for the input component.
Another question: why don't use flex for sizes in icons + input?
https://github.com/react-native-training/react-native-elements/blob/master/src/input/Input.js#L131

**Comment by xavier-villelegier** [comment]
@Grohden This is planned, and in [this PR](https://github.com/react-native-training/react-native-elements/pull/990/files#diff-89b1b79a7da1dd9a007d07c549ccbc3bL148) 😉

**Comment by Grohden** [comment]
@xavier-villelegier I've made some changes based on your PR, they solve my problems and use flex sizes. 
Here: https://snack.expo.io/@grohden/rn-elements-input-with-flex (on the components folder)
It's just a suggestion, i don't know if my changes broke something

**Comment by xavier-villelegier** [comment]
@Grohden Ah yea I see. We used flex sizes for the icon containers before and we switched to fixed size, because it doesn't have sens for the icon container. Imagine you rotate your screen, you want your Input to take more space but you don't want your Icon container to take useless space, as your icon itself will still have the same size. Don't know if it's clear

**Comment by xavier-villelegier** [comment]
@lifeiscontent @Grohden We refactored a bit the styles of the `Input` in `v1.0.0-beta4`, now live on npm. Feel free to test and make some feedbacks ✌️

**Comment by PMExtra** [comment]
Why does it back to `width: "90%"` in the latest version? (all of 1.0.0-beta5 and master / next branch)

**Comment by iRoachie** [comment]
@PMExtra just added a fix for this see https://github.com/react-native-training/react-native-elements/issues/1640
