### ISSUE TITLE
Some image in documentation is missing

### ISSUE THREAD

**Issue by yofriadi** [react-native-training/react-native-elements#985]
Hi, you need to update the documentation. there is a missing image like in Input section.

**Comment by yofriadi** [comment]
I dont know this, but its like imgur is blocked from my ISP. I close this.

**Comment by iRoachie** [comment]
@yofriadi We're aware of this, and we just changed over all the images from Imgur. The fix will be released today. https://github.com/react-native-training/react-native-elements/pull/974
