### ISSUE TITLE
Not existing prop title in Button component

### ISSUE THREAD

**Issue by maras333** [react-native-training/react-native-elements#988]
### Description

1. I tried to assign a title to a <Button/> component, according to documentation with 1.0.0-beta2
2. Title of a button didn't change
3. In a source code of the button there is no props as 'title'. Instead of that there is 'text' props. To resolve this you need to change name of a prop in a code from 'text' to 'title'.

**Comment by iRoachie** [comment]
Sorry about that @maras333 you are correct. The prop should've been `text` in the 1.0.0-beta2. I just sent in a PR to correct the documentation to show the correct props. https://github.com/react-native-training/react-native-elements/pull/989

**Comment by xavier-villelegier** [comment]
@maras333 Feel free to use the beta3, the props has been renamed back  to ˋtitle`

**Comment by iRoachie** [comment]
@maras333 Fixed merged in so the changes should be on the website in a few mins. Thanks for bringing it up
