### ISSUE TITLE
Missing properties in the button definition

### ISSUE THREAD

**Issue by rodrigoelp** [react-native-training/react-native-elements#992]
### Description

1. After importing `Button` I tried to create a rounded button
2. The type definition to work
3. The type definition does not have rounded property.

To reproduce this issue, just type the following code:

```typescript
const app = () => (
<View>
    <Text>whatever.</Text>
    <Button title="OK" onPress={this.handleOk} rounded={true} />
</View>
);
```

**Comment by rodrigoelp** [comment]
I have created a pull request fixing this issue
https://github.com/react-native-training/react-native-elements/pull/991

**Comment by xavier-villelegier** [comment]
Hey @rodrigoelp 👋
You're right, I think we forgot some props in the type definition for the `v0.19.0`, sorry about that. However, now we're developping the `v1.0.0` on the master branch, so we can't update the types of the old versions anymore.

Feel free to check out the `v1.0.0-beta3` and help us to improve it for the `v1.0.0` release 💪 
```
npm install --save react-native-elements@beta
```

**Comment by rodrigoelp** [comment]
In that case, how should I create a rounded button [like the first one on the screenshot](https://react-native-training.github.io/react-native-elements/docs/next/button.html)?

Feel free to discard the pull request if does not apply to the code anymore.

**Comment by rodrigoelp** [comment]
Hi @xavier-villelegier, I would love to know an answer for this. I think the rounded property was pretty cool and I don't really fancy having to call `borderTopRightRadius: 40, ...` as it seems to me a bit fragile.

**Comment by iRoachie** [comment]
@rodrigoelp You can still used the `rounded` prop in `0.19.0` as you can see the prop here https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html#button-props. It's just not defined in the typescript definitions.

You can extend the `ButtonProps` if you want to be able to use it and still have your typings correct.

```tsx
import { ButtonProps, Button } from 'react-native-elements'

class MyButton extends React.Component<ButtonProps & { rounded?: boolean }> {
  render() {
    return <Button {...this.props} />;
  }
}
```

Then use MyButton in your source code:
```tsx
<MyButton title="yea" onPress={() => alert('ey')} rounded />
```

You'll be able to use `rounded` without typescript complaining.
