### ISSUE TITLE
Multiple rows in ButtonGroup

### ISSUE THREAD

**Issue by Gittekken** [react-native-training/react-native-elements#993]
Rows of Buttons in One Button Group

Currently I am only able to achieve a single row of buttons in ButtonGroup.

I was wondering how to go about splitting the buttons into rows of buttons in ButtonGroup? For example, have react native make 3 buttons per row but all buttons are bounded to one group. 

For example: https://g6ling.gitbooks.io/react-native-tutorial-korean/content/1-7ko.html or a simple calculator app.

**Comment by xavier-villelegier** [comment]
Hey @Gittekken ! 👋
This is a bit handy but you can do this manually, check out [this snack example](https://snack.expo.io/SyCA9bStM).

<img src="https://user-images.githubusercontent.com/17592779/37330198-9d923224-26a0-11e8-803e-1a8f5f1a37df.png" width="300" />


I think the use case for the `ButtonGroup` is more like segmented controls on iOS, not really a bunch of buttons like a calculator app.

![image](https://user-images.githubusercontent.com/17592779/37330285-df9bde90-26a0-11e8-918b-a186fb5f21b0.png)

However I'll let this opened as an possible enhancement, and see if this is really something people need for the `ButtonGroup`

**Comment by Gittekken** [comment]
Thanks for the quick response and help @Xavier-villelegier. The problem is that it is bonded to two different button arrays. I would like to have the one ButtonGroup bonded to one buttons array so that I can selectIndex to one array. ['First', 'Buttons', 'Row'] and ['Second', 'Buttons', 'Row'] the index array would be [0,1,2] for both arrays. An array of ['First', 'Buttons', 'Row', 'Second', 'Buttons', 'Row'] I get [0, 1, 2, 3, 4, 5, 6]. Thanks for adding it to the enhancements.

**Comment by xavier-villelegier** [comment]
@Gittekken Okay I see, this is a bit more complicated then, but still feasible, [check this example](https://snack.expo.io/r1PmDMHtf).

<img src="https://user-images.githubusercontent.com/17592779/37332754-e3c9059a-26a7-11e8-9e30-2e54d4d8c5d2.png" width="300" />

**Comment by Gittekken** [comment]
Thanks @xavier-villelegier
