### ISSUE TITLE
Invariant Violation: Element type is invalid error in react-native and CRNA projects

### ISSUE THREAD

**Issue by SujaYuga** [react-native-training/react-native-elements#996]
### Description

I have installed the package as directed
npm i react-native-elements --save
npm i --save react-native-vector-icons
react-native link react-native-vector-icons

Version: "react-native-elements": "^0.19.0",

When importing components like Input or Overlay (to name a few) and using them throws below error.

import { Input } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';

<Input
  placeholder='INPUT WITH ICON'
  icon={
    <Icon
      name='user'
      size={24}
      color='black'
    />
  }
/>

Invariant Violation: Element type is invalid:
expected a string (for built-in components)
or a class/function....

This error is located at:
in RCTView (at View.js: 71)..

Note: The expo CRNA app also has the same error. The same issue also when testing on IOS and Android device using react-native app.

**Comment by LouisJS** [comment]
You shouldn't do :
```
npm i --save react-native-vector-icons
react-native link react-native-vector-icons
```

And if you are using expo, you can't do `react-native link`.

**Comment by SujaYuga** [comment]
I used react-native link for the react-native project. For the CRNA project, i only used npm i react-native-elements --save. These 2 projects are on different machines react-native on Mac and CRNA on Windows. Hope this clarifies. Please suggest a solution.

**Comment by iRoachie** [comment]
`Input` and `Overlay` are only available in version `1.0.0-beta2` and higher.

**Comment by SujaYuga** [comment]
is there any documentation or links, where i can find the supported components for the latest production release"react-native-elements": "^0.19.0"? Also, is 1.0.0-beta2 a production release? Please let me know.

**Comment by xavier-villelegier** [comment]
@SujaYuga Here are all the versioned doc https://react-native-training.github.io/react-native-elements/versions.html

The last "stable" release is `v0.19.0`, but we're encouraging people to use the beta version to help us improve it and make it better 💪

**Comment by mturki** [comment]
I have exactly same error with beta 3 version. `react-native-vector-icons` is installed, linked and fully functional with `v0.19.0`. But this error appeared today after upgrading to beta 3. Just to make i tried 

```npm i --save react-native-vector-icons
react-native link react-native-vector-icons
```

my simplified render() function 
```
        return (
            <ScrollView>
                <FormLabel>Username</FormLabel>
            </ScrollView>

        )```

My error :
```
ExceptionsManager.js:73 Unhandled JS Exception: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Login`.

This error is located at:
    in RCTScrollContentView (at ScrollView.js:793)
    in RCTScrollView (at ScrollView.js:889)
    in ScrollView (created by Login)
    in Login (created by inject-Login-with-uiStore-authStore)
    in inject-Login-with-uiStore-authStore (at Navigation.js:83)
    in MobxRnnProvider (at Navigation.js:82)
    in _class2 (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
reactConsoleErrorHandler @ ExceptionsManager.js:73
console.error @ YellowBox.js:71
logToConsole @ RCTLog.js:48
logIfNoNativeHook @ RCTLog.js:31
__callFunction @ MessageQueue.js:353
(anonymous) @ MessageQueue.js:118
__guardSafe @ MessageQueue.js:316
callFunctionReturnFlushedQueue @ MessageQueue.js:117
t @ RNDebuggerWorker.js:1```

PS. The doc. link for beta3 in this [page](https://react-native-training.github.io/react-native-elements/versions.html) does not seem to be up to date (beta 2 doc is ok) : For exemple, in the doc, the deprecated `label` button prop is present.

**Comment by xavier-villelegier** [comment]
@mturki There is no `FormLabel` anymore in the `v1.0.0-beta3`. We will include this label feature in the `Input` component in the `v1.0.0-beta4` coming soon

**Comment by xavier-villelegier** [comment]
Closing this as it seems to be just an issue with the import name.

Be sure you look at the [good version of the docs](https://react-native-training.github.io/react-native-elements/versions.html) to now which components you can use

**Comment by aliraza4167** [comment]
I get the same error with some components of "react-native-elements" library. I get this error when I use Input component, tried solutions provided above but didn't work for me.

**Comment by iRoachie** [comment]
Hey @aliraza4167, can you create a new issue? It's important you list the version of react-native-elements you're using and the code you wrote that shows the error

**Comment by tomtom94** [comment]
Just add the right version of the dependence

"react-native-elements": "^1.0.0-beta5",
